/**
 * Afrikaans — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * de rang, en commentaire, sont là pour qu'on puisse le vérifier à l'œil.
 */

export const af: readonly string[] = [
  /* 1 */ "Met die beheerder",
  /* 2 */ "A speel · X gunsteling · Y bysny · L1/R1 konsoles · L2/R2 letter · B terug",
  /* 3 */ "Oor EvaChi",
  /* 4 */ "Oor…",
  /* 5 */ "Binnekort: beeldbuisfilters, ruitpatroon, skanderlyne. Die plek is gereed, die filters kom hierheen.",
  /* 6 */ "Verfris biblioteek",
  /* 7 */ "Aansig",
  /* 8 */ "Wys speletjie-omslae",
  /* 9 */ "Hulp",
  /* 10 */ "Voeg 'n speletjiegids by…",
  /* 11 */ "Voeg 'n gids by…",
  /* 12 */ "Druk 'n knoppie op die beheerder: die ooreenstemmende toets lig op. Om een te verander, skakel oor na hertoewysing, klik die toets wat moet verander, en druk dan die knoppie wat jy wil hê.",
  /* 13 */ "Argumente",
  /* 14 */ "Met die sleutelbord",
  /* 15 */ "Geen speletjies",
  /* 16 */ "Geen beheerder bespeur nie.",
  /* 17 */ "Biblioteek",
  /* 18 */ "Keuseklanke met die beheerder",
  /* 19 */ "Sommige konsoles begin nie sonder hul oorspronklike fermware nie. EvaChi kan dit nie verskaf nie: dit is kode onder kopiereg, wat jy van die masjien af kopieer wat jy self besit. Wat sy wel doen, is om te sê watter een ontbreek, onder watter naam, en waar om dit neer te sit.",
  /* 20 */ "Hierdie konsoles het nie 'n libretro-kern nie: hul emulator is 'n aparte program wat EvaChi by haarself installeer en reguit in die speletjie in laat loop — sonder om deur sy eie kieslys te gaan. Die speletjies, die sleutels en die stelsellêers bly jou saak.",
  /* 21 */ "Hierdie instellings raak net die interne kerne. 'n Eksterne emulator het sy eie, en EvaChi bemoei haar nie daarmee nie.",
  /* 22 */ "Hierdie word nie meer aangebied nie: hulle het nie op die navraag geantwoord nie, of hulle het EvaChi laat val. Om hulle te herstel installeer hulle nie oor nie — dit sit hulle net weer op die lys.",
  /* 23 */ "Laai toestand",
  /* 24 */ "Net interne kerne. Klik 'n kortpad en druk dan die toets of knoppie wat jy wil hê; met die beheerder vat ons twee knoppies gelyk, want elkeen van hulle werk reeds vir die speletjie.",
  /* 25 */ "Kontroles",
  /* 26 */ "Kontroles…",
  /* 27 */ "Onlangse konsoles",
  /* 28 */ "Meld 'n ander emulator aan",
  /* 29 */ "Rigtings / linkerstok",
  /* 30 */ "Speletjiegidse",
  /* 31 */ "Sit hierdie emulator opsy",
  /* 32 */ "Hulle kom op aanvraag van die libretro-projek se duimnaelbediener af. Sonder die merkie vra die biblioteek niks meer van die netwerk nie.",
  /* 33 */ "Stoorgleuwe",
  /* 34 */ "Gleuwe…",
  /* 35 */ "Emulators",
  /* 36 */ "Opsygesette emulators",
  /* 37 */ "Eksterne emulators",
  /* 38 */ "Eksterne emulators…",
  /* 39 */ "Emulators…",
  /* 40 */ "Emulasie",
  /* 41 */ "Tydens 'n speletjie terug na die biblioteek — twee knoppies gelyk, want elkeen van hulle werk vir die speletjie",
  /* 42 */ "Stoor",
  /* 43 */ "Uitbreidings",
  /* 44 */ "Maak toe",
  /* 45 */ "Lêer",
  /* 46 */ "Stelsellêers wat jy self moet installeer",
  /* 47 */ "Galery",
  /* 48 */ "Bestuur gidse…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Wys die gids waar jou speletjies is.",
  /* 52 */ "Installasie",
  /* 53 */ "Installeer die keuse",
  /* 54 */ "Installeer emulators…",
  /* 55 */ "Vertolker",
  /* 56 */ "Jy hoef nie te weet waarheen nie: wys die gids waar alles rondlê — BIOS, sleutels, fermware, argiewe, subgidse ingesluit — en EvaChi dra elke lêer na die regte plek, vir die kerne sowel as vir die selfstandige emulators. Wat niemand vra nie, word nie geskuif nie.",
  /* 57 */ "Omslae",
  /* 58 */ "Logboek",
  /* 59 */ "Logboek…",
  /* 60 */ "Die vorige keer het sleg geëindig",
  /* 61 */ "Begin die speletjie, bevestig",
  /* 62 */ "Taal",
  /* 63 */ "Die keuse word van die een begin tot die volgende onthou. Elkeen is nagegaan vir leesbaarheid: die teks behou oral genoeg kontras teen sy agtergrond.",
  /* 64 */ "Hou hom",
  /* 65 */ "Die emulators hieronder is reeds opgestel — argumente en formate ingesluit. EvaChi soek hulle op jou skyf; sy installeer hulle nie.",
  /* 66 */ "Oorspronklike koppelings",
  /* 67 */ "Gladmaking",
  /* 68 */ "Maak die speletjie 'n gunsteling, of haal dit daaruit",
  /* 69 */ "Musiek van die bewegende kieslys",
  /* 70 */ "Naam",
  /* 71 */ "Maak die kieslysbalk oop",
  /* 72 */ "Maak die gids oop",
  /* 73 */ "Maak die gids oop…",
  /* 74 */ "Maak 'n speletjie oop…",
  /* 75 */ "per raam",
  /* 76 */ "Kerninstellings",
  /* 77 */ "Kerninstellings…",
  /* 78 */ "Beweeg deur die biblioteek, die vensters en die kieslysbalk",
  /* 79 */ "Blaai…",
  /* 80 */ "Pouse",
  /* 81 */ "Volskerm",
  /* 82 */ "Vir konsoles sonder 'n libretro-kern. EvaChi begin die program met die speletjie as argument: die emulator begin reguit in die spel, sonder om deur sy eie kieslys te gaan.",
  /* 83 */ "Neem 'n skermkiekie",
  /* 84 */ "Uitleg",
  /* 85 */ "Gereed",
  /* 86 */ "Program",
  /* 87 */ "'n Paar aangehoue akkoorde en verspreide note, wat ter plaatse saamgestel word eerder as opgeneem: die stuk kom nooit weer by dieselfde plek uit nie. Dit hou vanself op sodra 'n speletjie begin.",
  /* 88 */ "Ruim 'n gids op…",
  /* 89 */ "Hertoewys…",
  /* 90 */ "Soek 'n speletjie…",
  /* 91 */ "Stel terug",
  /* 92 */ "Terug na die biblioteek",
  /* 93 */ "Gaan terug, maak toe",
  /* 94 */ "Kitsstoor",
  /* 95 */ "Stoor toestand",
  /* 96 */ "Shaders",
  /* 97 */ "Klank",
  /* 98 */ "Start",
  /* 99 */ "Beeldgrootte",
  /* 100 */ "Temas",
  /* 101 */ "Temas…",
  /* 102 */ "Net een lêer…",
  /* 103 */ "'n Kort tik wanneer jy van speletjie verander, nog een wanneer jy dit begin. Net met die beheerder: met die muis en die sleutelbord voel jy die beweging klaar.",
  /* 104 */ "Spoed",
  /* 105 */ "Bekyk skermkiekies…",
  /* 106 */ "Jy kan net 'n deel daarvan installeer — net die konsoles waarvan die emulator geïnstalleer is, verskyn in die biblioteek.",
  /* 107 */ "{0} — gelaai",
  /* 108 */ "{0} — regsklik om te wis",
  /* 109 */ "{0} — as gunsteling gemerk",
  /* 110 */ "{0} — teruggestel",
  /* 111 */ "{0} — uit gunstelinge gehaal",
  /* 112 */ "{0} — laai af…",
  /* 113 */ "{0}: misluk, kyk in die logboek",
  /* 114 */ "{0} beskikbaar",
  /* 115 */ "{0} gestoor",
  /* 116 */ "{0} is 'n eksterne emulator: dit word begin, dit word nie gehuisves nie",
  /* 117 */ "{0} r/s",
  /* 118 */ "{0} geïnstalleer",
  /* 119 */ "{0} geïnstalleer — {1}",
  /* 120 */ "{0} geïnstalleer en gereed",
  /* 121 */ "{0} geïnstalleer, {1} misluk — kyk in die logboek",
  /* 122 */ "{0} herstel",
  /* 123 */ "{0} verwyder",
  /* 124 */ "{0} van {1}",
  /* 125 */ "{0} op die skyf, maar geen geïnstalleerde kern maak dit oop nie.",
  /* 126 */ "te kry by {0}, dan “Blaai…”",
  /* 127 */ "om af te laai",
  /* 128 */ "afwesig, opsioneel",
  /* 129 */ "Aktiveer",
  /* 130 */ "Versag",
  /* 131 */ "kon nie byvoeg nie — {0}",
  /* 132 */ "Pas in",
  /* 133 */ "Amber",
  /* 134 */ "Leiklip",
  /* 135 */ "gestop — {0}",
  /* 136 */ "skielike stop die vorige keer — {0}",
  /* 137 */ "geen",
  /* 138 */ "geen kern teruggegee terwyl {0} bekend was — vorige lys behou",
  /* 139 */ "geen emulator",
  /* 140 */ "Geen emulator geïnstalleer nie",
  /* 141 */ "Geen speletjie herken nie",
  /* 142 */ "Geen resultate",
  /* 143 */ "geen",
  /* 144 */ "biblioteek onleesbaar — {0}",
  /* 145 */ "ingeprop",
  /* 146 */ "skermkiekie",
  /* 147 */ "Verander die omslag…",
  /* 148 */ "Verander…",
  /* 149 */ "Elke pixel op nege",
  /* 150 */ "Elke pixel op vier: skerp, sonder vervorming",
  /* 151 */ "Elke pixel op sestien — vir groot skerms",
  /* 152 */ "Laai",
  /* 153 */ "Kies 'n omslag…",
  /* 154 */ "kies eers 'n speletjie in die biblioteek",
  /* 155 */ "kern: {0}",
  /* 156 */ "kern nie geïnstalleer nie",
  /* 157 */ "Geïnstalleerde kerne",
  /* 158 */ "libretro-kerne",
  /* 159 */ "Hoë kontras",
  /* 160 */ "inheemse dop: {0}",
  /* 161 */ "onvolledige ontlaai — {0}",
  /* 162 */ "ontdekking: {0}",
  /* 163 */ "ontdekking onderbreek — {0}",
  /* 164 */ "Wys self die program van {0} aan",
  /* 165 */ "gids bygevoeg: {0}",
  /* 166 */ "gids oopgemaak: {0}",
  /* 167 */ "Verstekgids",
  /* 168 */ "Bygevoegde gidse",
  /* 169 */ "Esc",
  /* 170 */ "Gleuf {0}",
  /* 171 */ "gleuf {0} — {1}",
  /* 172 */ "Emulator vir hierdie gids",
  /* 173 */ "eksterne emulators",
  /* 174 */ "besig",
  /* 175 */ "in plek",
  /* 176 */ "kon nie stoor nie — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi kan hulle van libretro se amptelike bouwerf aflaai. Kies die konsoles wat jou interesseer.",
  /* 179 */ "EvaChi het gaan staan terwyl sy “{0}” begin het, met die emulator {1}.",
  /* 180 */ "EvaChi het gaan staan, met die emulator {0}.",
  /* 181 */ "external_systems → {0} emulators aangemeld",
  /* 182 */ "Gunsteling",
  /* 183 */ "Gunstelinge",
  /* 184 */ "stelsellêers onleesbaar — {0}",
  /* 185 */ "Pyltjies",
  /* 186 */ "Game Boy",
  /* 187 */ "Rooster",
  /* 188 */ "{0} ontbreek by geïnstalleerde konsoles",
  /* 189 */ "installasie klaar: {0}",
  /* 190 */ "Installeer tans…",
  /* 191 */ "geïnstalleer",
  /* 192 */ "deur EvaChi geïnstalleer",
  /* 193 */ "Installeer",
  /* 194 */ "vertolker: {0}",
  /* 195 */ "navraag by die geïnstalleerde kerne…",
  /* 196 */ "Begin",
  /* 197 */ "Begin die gekose speletjie",
  /* 198 */ "Laventel",
  /* 199 */ "Die konsoles in 'n ry, die speletjies in 'n kolom, 'n agtergrond wat golf. Soos 'n sitkamerkonsole.",
  /* 200 */ "Die rande vloei ineen — nader aan 'n ou televisie",
  /* 201 */ "Die omslae groot, deurgeblaai met die beheerder. Bedoel vir die rusbank.",
  /* 202 */ "Die pixels bly vierkantig, soos op die oorspronklike masjien",
  /* 203 */ "beheerderkoppelings teruggestel na oorspronklik",
  /* 204 */ "list_cores → {0} kerne aangekondig",
  /* 205 */ "Lys",
  /* 206 */ "kernlys nie beskikbaar nie — {0}",
  /* 207 */ "emulatorlys nie beskikbaar nie — {0}",
  /* 208 */ "Beheerder",
  /* 209 */ "beheerder: {0}",
  /* 210 */ "Beheerder: {0}",
  /* 211 */ "beheerder uitgeprop",
  /* 212 */ "ONTBREEK",
  /* 213 */ "Mint",
  /* 214 */ "Bewegende kieslys",
  /* 215 */ "Werk by",
  /* 216 */ "Maak gunsteling",
  /* 217 */ "opsy gesit: {0} · {1}",
  /* 218 */ "minder as 'n minuut",
  /* 219 */ "Skerp",
  /* 220 */ "naam, program en uitbreidings is almal nodig",
  /* 221 */ "NEE",
  /* 222 */ "nie op hierdie masjien geïnstalleer nie",
  /* 223 */ "Pienk nag",
  /* 224 */ "Oseaan",
  /* 225 */ "of",
  /* 226 */ "ja",
  /* 227 */ "kon nie oopmaak nie — {0}",
  /* 228 */ "webblad: net die interne kerne is beskikbaar, sonder biblioteek",
  /* 229 */ "Papier",
  /* 230 */ "verstek",
  /* 231 */ "Beweeg deur die rooster en die bewegende kieslys",
  /* 232 */ "volskerm geweier — {0}",
  /* 233 */ "druk die knoppie wat jy wil hê op die beheerder",
  /* 234 */ "druk 'n toets…",
  /* 235 */ "opruiming: {0} · {1}",
  /* 236 */ "kon nie opruim nie — {0}",
  /* 237 */ "soektog na emulators onderbreek — {0}",
  /* 238 */ "Maak 'n venster toe",
  /* 239 */ "kon nie terugstel nie — {0}",
  /* 240 */ "Vul die venster en hou die verhoudings",
  /* 241 */ "Hervat",
  /* 242 */ "Hervat hierdie stoorpunt — regsklik om dit leeg te maak",
  /* 243 */ "Herstel",
  /* 244 */ "kon nie herstel nie — {0}",
  /* 245 */ "Verwyder",
  /* 246 */ "Haal uit gunstelinge",
  /* 247 */ "Verwyder die omslag",
  /* 248 */ "kon nie verwyder nie — {0}",
  /* 249 */ "niks om op te ruim nie",
  /* 250 */ "niks blokkeer nie",
  /* 251 */ "Niks stem ooreen met “{0}” nie.",
  /* 252 */ "Pienk en wit",
  /* 253 */ "sonder prent",
  /* 254 */ "Stoor",
  /* 255 */ "Stoor hier",
  /* 256 */ "kon nie kies nie — {0}",
  /* 257 */ "Die konsole se oorspronklike grootte, tot op die pixel",
  /* 258 */ "Voltooi",
  /* 259 */ "ligte tema",
  /* 260 */ "donker tema",
  /* 261 */ "alles is geïnstalleer",
  /* 262 */ "gevind: {0}",
  /* 263 */ "Een paneel per konsole, in 'n tabel. Die digste met die muis.",
  /* 264 */ "leeg",
  /* 265 */ "sit dit hier neer, soos die speletjies se romsets: FinalBurn Neo soek net in hierdie gids",
  /* 266 */ "voeg die konsole se aanvangskerm by",
  /* 267 */ "die masjien se opstartkode",
  /* 268 */ "baie speletjies begin daarsonder; die konsole se kieslys nie",
  /* 269 */ "Amerikaanse BIOS",
  /* 270 */ "Amerikaanse en Europese BIOS",
  /* 271 */ "Europese BIOS",
  /* 272 */ "Japannese BIOS",
  /* 273 */ "ontsyferingsleutels; daarsonder word 'n geënkripteerde storting geweier",
  /* 274 */ "die Machines-gids van die blueMSX-verspreiding, met Databases langsaan",
  /* 275 */ "dieselfde",
  /* 276 */ "onmisbaar vir CD-speletjies, nutteloos vir HuCard-kaarte",
  /* 277 */ "onmisbaar vir Mega-CD-speletjies, nutteloos vir kassette",
  /* 278 */ "Kickstart 1.3; andersins val PUAE terug op AROS, vry maar minder versoenbaar",
  /* 279 */ "Kickstart 3.1; nodig vir AGA-speletjies, wat die A500 nie kan laat loop nie",
  /* 280 */ "melonDS emuleer die BIOS by verstek; die egte een is getrouer",
  /* 281 */ "mGBA kom daarsonder klaar; 'n paar speletjies eis dit vir hul aanvangskerm",
  /* 282 */ "die konsole se fermware",
  /* 283 */ "die masjien se fermware",
  /* 284 */ "Panasonic FZ-10-fermware; dit is die naam wat Opera by verstek neem",
  /* 285 */ "deur melonDS verander, wat die oorspronklike as .bak bewaar",
  /* 286 */ "lettertipes",
  /* 287 */ "die konsole se instellings en datum",
  /* 288 */ "daarsonder loop die kern, maar die skerm bly swart",
  /* 289 */ "die konsole se karaktertabel",
  /* 290 */ "Amerikaanse variant, vir Sega CD-speletjies uit die Verenigde State",
  /* 291 */ "Japannese variant, vir Japannese Mega-CD-speletjies",
  /* 292 */ "skermkiekies",
  /* 293 */ "skermkiekies",
  /* 294 */ "skermkiekie",
  /* 295 */ "skermkiekies",
  /* 296 */ "skermkiekies",
  /* 297 */ "skermkiekies",
  /* 298 */ "kerne",
  /* 299 */ "kerne",
  /* 300 */ "kern",
  /* 301 */ "kerne",
  /* 302 */ "kerne",
  /* 303 */ "kerne",
  /* 304 */ "emulators",
  /* 305 */ "emulators",
  /* 306 */ "emulator",
  /* 307 */ "emulators",
  /* 308 */ "emulators",
  /* 309 */ "emulators",
  /* 310 */ "lêers",
  /* 311 */ "lêers",
  /* 312 */ "lêer",
  /* 313 */ "lêers",
  /* 314 */ "lêers",
  /* 315 */ "lêers",
  /* 316 */ "speletjies",
  /* 317 */ "speletjies",
  /* 318 */ "speletjie",
  /* 319 */ "speletjies",
  /* 320 */ "speletjies",
  /* 321 */ "speletjies",
  /* 322 */ "<code>{rom}</code> word deur die speletjie se pad vervang. Daarsonder word die pad aan die einde bygevoeg — wat die meeste emulators verwag.",
  /* 323 */ "<strong>Buite 'n speletjie gebeur alles met die beheerder:</strong> die rigtings beweeg deur die biblioteek, die vensters en die kieslysbalk; <strong>A</strong> bevestig, <strong>B</strong> gaan terug, <strong>Start</strong> maak die kieslysbalk oop. Tydens 'n speletjie bring <strong>Select en Start saam</strong> jou terug na die biblioteek — twee knoppies gelyk, want elkeen van hulle werk vir die speletjie.",
  /* 324 */ "Geen skermkiekies nie. Druk <strong>F12</strong> tydens 'n speletjie, of <strong>Select + Y</strong> op die beheerder.",
  /* 325 */ "Elke konsole het sy eie emulator nodig. EvaChi gaan haal hulle by die libretro-projek se amptelike bouwerf, <code>buildbot.libretro.com</code>, en installeer hulle in haar eie gids. Niks word herversprei nie: dit is die weergawes wat hul makers self uitgegee het.",
  /* 326 */ "Vier gleuwe per speletjie, op die skyf gehou. Die gleuf in vetdruk is die een wat <strong>F2</strong> en <strong>F4</strong> gebruik — en <strong>Select + L1</strong> / <strong>Select + R1</strong> op die beheerder. Regsklik op 'n gleuf om dit leeg te maak.",
  /* 327 */ "'n Emulator loop in dieselfde venster as EvaChi: as hy val, sleep hy haar saam, sonder 'n boodskap. Om hierdie emulator opsy te sit laat hom geïnstalleer, maar hy word nie meer aangebied nie. Jy kan hom enige tyd herstel by <strong>Lêer → Emulators</strong>, onder in die venster.",
  /* 328 */ "Net een lêer per speletjie op die skyf <small> 'n Speletjie op CD kom as een <code>.cue</code>-blaadjie en soveel <code>.bin</code>-lêers as wat die skyf snitte gehad het. Net die blaadjie word begin: die snitte word versteek wanneer dit daar is. Sonder 'n blaadjie word niks versteek nie. </small>",
  /* 329 */ "(leeg) of --fullscreen {rom}",
  /* 330 */ "Honderd persent is die konsole se eie snelheid. Daaronder loop die speletjie stadiger, daarbo jaag dit — en die klank volg saam, dieper of hoër. Op die beheerder skuif links en regs van die een stap na die volgende. Net vir die interne kerne: 'n eksterne emulator hou by sy eie snelheid.",
  /* 331 */ "Vyf konsoles op 'n slag",
  /* 332 */ "Rigtingkruis",
  /* 333 */ "Van een beginletter na die volgende",
  /* 334 */ "In die geanimeerde kieslys, vyf speletjies op 'n slag",
  /* 335 */ "Spelsnelheid",
  /* 336 */ "Kanselleer",
  /* 337 */ "Sleep die raam, of trek aan 'n hoek. Met die pyltjies skuif jy dit, en hou Shift in om dit groter of kleiner te maak. Steek dit buite die prent uit, dan kom daar deursigtige rande by — so zoom jy uit op 'n omslag wat te styf sit. Met die kontroleerder skuif die rigtings dit, en die snellers stel die grootte.",
  /* 338 */ "Bysny",
  /* 339 */ "Omslag bysny",
  /* 340 */ "Hele prent",
  /* 341 */ "{0} — omslag bygesny",
  /* 342 */ "{0} — geen omslag om by te sny nie",
  /* 343 */ "omslag onleesbaar — {0}",
  /* 344 */ "kon nie bysny nie — {0}",
  /* 345 */ "Omslag bysny…",
];
