/**
 * Le catalan — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros mis en commentaire devant chaque phrase sont là pour qu'on puisse
 * le vérifier à l'œil.
 */

export const ca: readonly string[] = [
  /* 1 */ "Amb el comandament",
  /* 2 */ "A engegar · X preferit · Y retallar · L1/R1 consoles · L2/R2 lletra · B enrere",
  /* 3 */ "Quant a EvaChi",
  /* 4 */ "Quant a…",
  /* 5 */ "Aviat: filtres de tub catòdic, quadrícula, escombratge. L'espai ja hi és, els filtres arribaran aquí.",
  /* 6 */ "Actualitza la biblioteca",
  /* 7 */ "Visualització",
  /* 8 */ "Mostra les caràtules dels jocs",
  /* 9 */ "Ajuda",
  /* 10 */ "Afegeix una carpeta de jocs…",
  /* 11 */ "Afegeix una carpeta…",
  /* 12 */ "Premeu un botó del comandament: la tecla corresponent s'encén. Per canviar-ne una, passeu a reassignació, feu clic a la tecla que voleu modificar i premeu el botó que vulgueu.",
  /* 13 */ "Arguments",
  /* 14 */ "Amb el teclat",
  /* 15 */ "Cap joc",
  /* 16 */ "No s'ha detectat cap comandament.",
  /* 17 */ "Biblioteca",
  /* 18 */ "Sons de selecció amb el comandament",
  /* 19 */ "Algunes consoles no arrenquen sense el seu microprogramari original. EvaChi no el pot proporcionar: és codi amb drets d'autor, que es copia de la màquina que un té. El que sí que fa és dir quin falta, amb quin nom i on deixar-lo.",
  /* 20 */ "Aquestes consoles no tenen nucli libretro: el seu emulador és un programa a part, que EvaChi instal·la a casa seva i engega directament dins del joc — sense passar pel seu menú. Els jocs, les claus i els fitxers de sistema van a càrrec vostre.",
  /* 21 */ "Aquests paràmetres només afecten els nuclis interns. Un emulador extern té els seus, i EvaChi no s'hi fica.",
  /* 22 */ "Aquests ja no s'ofereixen: no han respost a la consulta, o han fet caure EvaChi. Restablir-los no els reinstal·la — només els torna a posar a la llista.",
  /* 23 */ "Carrega l'estat",
  /* 24 */ "Només nuclis interns. Feu clic en una drecera i premeu la tecla o el botó que vulgueu; amb el comandament se'n prenen dos alhora, perquè cadascun ja serveix per al joc.",
  /* 25 */ "Controls",
  /* 26 */ "Controls…",
  /* 27 */ "Consoles recents",
  /* 28 */ "Declara un altre emulador",
  /* 29 */ "Direccions / palanca esquerra",
  /* 30 */ "Carpetes de jocs",
  /* 31 */ "Aparta aquest emulador",
  /* 32 */ "Vénen del servidor de miniatures del projecte libretro, a petició. Si es desmarca, la biblioteca ja no demana res a la xarxa.",
  /* 33 */ "Ranures de desament",
  /* 34 */ "Ranures…",
  /* 35 */ "Emuladors",
  /* 36 */ "Emuladors apartats",
  /* 37 */ "Emuladors externs",
  /* 38 */ "Emuladors externs…",
  /* 39 */ "Emuladors…",
  /* 40 */ "Emulació",
  /* 41 */ "Durant la partida, tornar a la biblioteca — dos botons alhora, perquè cadascun serveix per al joc",
  /* 42 */ "Desa",
  /* 43 */ "Extensions",
  /* 44 */ "Tanca",
  /* 45 */ "Fitxer",
  /* 46 */ "Fitxers de sistema per instal·lar un mateix",
  /* 47 */ "Galeria",
  /* 48 */ "Gestiona les carpetes…",
  /* 49 */ "Gràfics",
  /* 50 */ "Gràfics…",
  /* 51 */ "Indiqueu la carpeta on teniu els jocs.",
  /* 52 */ "Instal·lació",
  /* 53 */ "Instal·la la selecció",
  /* 54 */ "Instal·la els emuladors…",
  /* 55 */ "Intèrpret",
  /* 56 */ "No cal saber on: ensenyeu la carpeta on hi ha de tot — BIOS, claus, microprogramaris, arxius, subcarpetes incloses — i EvaChi porta cada fitxer al lloc que li toca, tant per als nuclis com per als emuladors autònoms. El que ningú no reclama no es mou.",
  /* 57 */ "Caràtules",
  /* 58 */ "Registre",
  /* 59 */ "Registre…",
  /* 60 */ "L'últim cop va acabar malament",
  /* 61 */ "Iniciar el joc, confirmar",
  /* 62 */ "Idioma",
  /* 63 */ "L'elecció es manté d'una engegada a l'altra. S'ha comprovat que tots són llegibles: pertot el text conserva prou contrast sobre el seu fons.",
  /* 64 */ "Conserva'l",
  /* 65 */ "Els emuladors de sota ja estan configurats — arguments i formats inclosos. EvaChi els busca al vostre disc; no els instal·la.",
  /* 66 */ "Assignacions originals",
  /* 67 */ "Suavitzat",
  /* 68 */ "Afegir el joc als preferits, o treure'l",
  /* 69 */ "Música dels menús animats",
  /* 70 */ "Nom",
  /* 71 */ "Obrir la barra de menús",
  /* 72 */ "Obre la carpeta",
  /* 73 */ "Obre la carpeta…",
  /* 74 */ "Obre un joc…",
  /* 75 */ "per fotograma",
  /* 76 */ "Paràmetres del nucli",
  /* 77 */ "Paràmetres del nucli…",
  /* 78 */ "Recórrer la biblioteca, les finestres i la barra de menús",
  /* 79 */ "Navega…",
  /* 80 */ "Pausa",
  /* 81 */ "Pantalla completa",
  /* 82 */ "Per a les consoles sense nucli libretro. EvaChi engega el programa amb el joc com a argument: l'emulador arrenca directament dins la partida, sense passar pel seu propi menú.",
  /* 83 */ "Fes una captura",
  /* 84 */ "Presentació",
  /* 85 */ "A punt",
  /* 86 */ "Programa",
  /* 87 */ "Uns quants acords sostinguts i notes escampades, compostos sobre la marxa més que no pas enregistrats: la peça no torna mai a passar pel mateix lloc. S'atura tota sola així que arrenca un joc.",
  /* 88 */ "Endreça una carpeta…",
  /* 89 */ "Reassigna…",
  /* 90 */ "Cerca un joc…",
  /* 91 */ "Reinicia",
  /* 92 */ "Torna a la biblioteca",
  /* 93 */ "Tornar enrere, tancar",
  /* 94 */ "Desament ràpid",
  /* 95 */ "Desa l'estat",
  /* 96 */ "Shaders",
  /* 97 */ "So",
  /* 98 */ "Start",
  /* 99 */ "Mida de la imatge",
  /* 100 */ "Temes",
  /* 101 */ "Temes…",
  /* 102 */ "Un sol fitxer…",
  /* 103 */ "Un tic breu en canviar de joc, un altre en iniciar-lo. Només amb el comandament: amb el ratolí i el teclat, el gest ja es nota.",
  /* 104 */ "Velocitat",
  /* 105 */ "Mostra les captures…",
  /* 106 */ "Podeu instal·lar-ne només una part — a la biblioteca només hi surten les consoles que tenen l'emulador instal·lat.",
  /* 107 */ "{0} — carregat",
  /* 108 */ "{0} — clic dret per buidar",
  /* 109 */ "{0} — afegit als preferits",
  /* 110 */ "{0} — reinicialitzat",
  /* 111 */ "{0} — tret dels preferits",
  /* 112 */ "{0} — baixant…",
  /* 113 */ "{0}: ha fallat, vegeu el registre",
  /* 114 */ "{0} a disposició",
  /* 115 */ "{0} desat",
  /* 116 */ "{0} és un emulador extern: s'engega, no s'allotja",
  /* 117 */ "{0} img/s",
  /* 118 */ "{0} instal·lat",
  /* 119 */ "{0} instal·lat — {1}",
  /* 120 */ "{0} instal·lat i a punt",
  /* 121 */ "{0} instal·lats, {1} amb error — vegeu el registre",
  /* 122 */ "{0} restablert",
  /* 123 */ "{0} retirat",
  /* 124 */ "{0} de {1}",
  /* 125 */ "{0} al disc, però cap nucli instal·lat no els obre.",
  /* 126 */ "a obtenir de {0}, després «Navega…»",
  /* 127 */ "a baixar",
  /* 128 */ "absent, opcional",
  /* 129 */ "Activa",
  /* 130 */ "Suau",
  /* 131 */ "no s'ha pogut afegir — {0}",
  /* 132 */ "Ajusta",
  /* 133 */ "Ambre",
  /* 134 */ "Pissarra",
  /* 135 */ "aturada — {0}",
  /* 136 */ "aturada brusca l'últim cop — {0}",
  /* 137 */ "cap",
  /* 138 */ "cap nucli retornat tot i que se'n coneixien {0} — es manté la llista anterior",
  /* 139 */ "cap emulador",
  /* 140 */ "Cap emulador instal·lat",
  /* 141 */ "Cap joc reconegut",
  /* 142 */ "Cap resultat",
  /* 143 */ "cap",
  /* 144 */ "biblioteca il·legible — {0}",
  /* 145 */ "connectat",
  /* 146 */ "captura",
  /* 147 */ "Canvia la caràtula…",
  /* 148 */ "Canvia…",
  /* 149 */ "Cada píxel en nou",
  /* 150 */ "Cada píxel en quatre: nítid, sense deformació",
  /* 151 */ "Cada píxel en setze — per a les pantalles grans",
  /* 152 */ "Carrega",
  /* 153 */ "Tria una caràtula…",
  /* 154 */ "trieu primer un joc a la biblioteca",
  /* 155 */ "nucli: {0}",
  /* 156 */ "nucli no instal·lat",
  /* 157 */ "Nuclis instal·lats",
  /* 158 */ "nuclis libretro",
  /* 159 */ "Contrast alt",
  /* 160 */ "embolcall natiu: {0}",
  /* 161 */ "alliberament incomplet — {0}",
  /* 162 */ "descoberta: {0}",
  /* 163 */ "descoberta interrompuda — {0}",
  /* 164 */ "Indicar un mateix el programa de {0}",
  /* 165 */ "carpeta afegida: {0}",
  /* 166 */ "carpeta oberta: {0}",
  /* 167 */ "Carpeta per defecte",
  /* 168 */ "Carpetes afegides",
  /* 169 */ "Esc",
  /* 170 */ "Ranura {0}",
  /* 171 */ "ranura {0} — {1}",
  /* 172 */ "Emulador utilitzat per a aquesta carpeta",
  /* 173 */ "emuladors externs",
  /* 174 */ "en curs",
  /* 175 */ "al seu lloc",
  /* 176 */ "no s'ha pogut desar — {0}",
  /* 177 */ "Retorn",
  /* 178 */ "EvaChi els pot baixar de la forja oficial de libretro. Trieu les consoles que us interessin.",
  /* 179 */ "EvaChi s'ha aturat en engegar «{0}», amb l'emulador {1}.",
  /* 180 */ "EvaChi s'ha aturat, amb l'emulador {0}.",
  /* 181 */ "external_systems → {0} emuladors declarats",
  /* 182 */ "Preferit",
  /* 183 */ "Preferits",
  /* 184 */ "fitxers de sistema il·legibles — {0}",
  /* 185 */ "Fletxes",
  /* 186 */ "Game Boy",
  /* 187 */ "Graella",
  /* 188 */ "falten {0} a consoles instal·lades",
  /* 189 */ "instal·lació acabada: {0}",
  /* 190 */ "Instal·lant…",
  /* 191 */ "instal·lat",
  /* 192 */ "instal·lat per EvaChi",
  /* 193 */ "Instal·la",
  /* 194 */ "intèrpret: {0}",
  /* 195 */ "consultant els nuclis instal·lats…",
  /* 196 */ "Inicia",
  /* 197 */ "Iniciar el joc triat",
  /* 198 */ "Lavanda",
  /* 199 */ "Les consoles en fila, els jocs en columna, un fons que ondula. A l'estil d'una consola de sobretaula.",
  /* 200 */ "Els contorns es fonen — més a prop d'un televisor antic",
  /* 201 */ "Les caràtules en gran, recorregudes amb el comandament. Pensat per al sofà.",
  /* 202 */ "Els píxels es mantenen quadrats, com a la màquina original",
  /* 203 */ "assignacions del comandament tornades a l'origen",
  /* 204 */ "list_cores → {0} nuclis anunciats",
  /* 205 */ "Llista",
  /* 206 */ "llista de nuclis no disponible — {0}",
  /* 207 */ "llista d'emuladors no disponible — {0}",
  /* 208 */ "Comandament",
  /* 209 */ "comandament: {0}",
  /* 210 */ "Comandament: {0}",
  /* 211 */ "comandament desconnectat",
  /* 212 */ "FALTA",
  /* 213 */ "Menta",
  /* 214 */ "Menú animat",
  /* 215 */ "Actualitza",
  /* 216 */ "Afegeix als preferits",
  /* 217 */ "apartat: {0} · {1}",
  /* 218 */ "menys d'un minut",
  /* 219 */ "Nítid",
  /* 220 */ "calen el nom, el programa i les extensions",
  /* 221 */ "NO",
  /* 222 */ "no instal·lat en aquesta màquina",
  /* 223 */ "Nit rosa",
  /* 224 */ "Oceà",
  /* 225 */ "o",
  /* 226 */ "sí",
  /* 227 */ "no s'ha pogut obrir — {0}",
  /* 228 */ "pàgina web: només hi ha els nuclis interns, sense biblioteca",
  /* 229 */ "Paper",
  /* 230 */ "per defecte",
  /* 231 */ "Recórrer la graella i els menús animats",
  /* 232 */ "pantalla completa rebutjada — {0}",
  /* 233 */ "premeu el botó que vulgueu al comandament",
  /* 234 */ "premeu una tecla…",
  /* 235 */ "endreça: {0} · {1}",
  /* 236 */ "no s'ha pogut endreçar — {0}",
  /* 237 */ "cerca d'emuladors interrompuda — {0}",
  /* 238 */ "Tancar una finestra",
  /* 239 */ "no s'ha pogut reinicialitzar — {0}",
  /* 240 */ "Omple la finestra tot mantenint les proporcions",
  /* 241 */ "Reprèn",
  /* 242 */ "Reprèn aquest desament — clic dret per buidar-lo",
  /* 243 */ "Restableix",
  /* 244 */ "no s'ha pogut restablir — {0}",
  /* 245 */ "Retira",
  /* 246 */ "Treu dels preferits",
  /* 247 */ "Retira la caràtula",
  /* 248 */ "no s'ha pogut retirar — {0}",
  /* 249 */ "res a endreçar",
  /* 250 */ "res no bloqueja",
  /* 251 */ "No hi ha res que coincideixi amb «{0}».",
  /* 252 */ "Rosa i blanc",
  /* 253 */ "sense imatge",
  /* 254 */ "Desa",
  /* 255 */ "Desa aquí",
  /* 256 */ "no s'ha pogut seleccionar — {0}",
  /* 257 */ "Mida original de la consola, píxel a píxel",
  /* 258 */ "Acaba",
  /* 259 */ "tema clar",
  /* 260 */ "tema fosc",
  /* 261 */ "tot està instal·lat",
  /* 262 */ "trobat: {0}",
  /* 263 */ "Una secció per consola, en taula. El més dens amb el ratolí.",
  /* 264 */ "buit",
  /* 265 */ "s'ha de deixar aquí, com els romsets dels jocs: FinalBurn Neo només busca en aquesta carpeta",
  /* 266 */ "afegeix la pantalla d'inici de la consola",
  /* 267 */ "arrencada de la màquina",
  /* 268 */ "molts jocs arrenquen sense; el menú de la consola no",
  /* 269 */ "BIOS dels Estats Units",
  /* 270 */ "BIOS dels Estats Units i d'Europa",
  /* 271 */ "BIOS d'Europa",
  /* 272 */ "BIOS del Japó",
  /* 273 */ "claus de desxifratge; sense elles, un bolcat xifrat es rebutja",
  /* 274 */ "carpeta de màquines de la distribució blueMSX, amb Databases al costat",
  /* 275 */ "ídem",
  /* 276 */ "imprescindible per als jocs en CD, inútil per a les targetes HuCard",
  /* 277 */ "imprescindible per als jocs Mega-CD, inútil per als cartutxos",
  /* 278 */ "Kickstart 1.3; si no, PUAE recorre a AROS, lliure però menys compatible",
  /* 279 */ "Kickstart 3.1; cal per als jocs AGA, que l'A500 no sap fer funcionar",
  /* 280 */ "melonDS emula la BIOS per defecte; la de debò és més fidel",
  /* 281 */ "mGBA se'n pot estar; alguns jocs l'exigeixen per a la pantalla d'inici",
  /* 282 */ "microprogramari de la consola",
  /* 283 */ "microprogramari de la màquina",
  /* 284 */ "microprogramari Panasonic FZ-10; és aquest el nom que Opera pren per defecte",
  /* 285 */ "modificat per melonDS, que conserva l'original en .bak",
  /* 286 */ "tipus de lletra",
  /* 287 */ "paràmetres i data de la consola",
  /* 288 */ "sense ell el nucli funciona però la pantalla es queda negra",
  /* 289 */ "taula de caràcters de la consola",
  /* 290 */ "variant americana, per als jocs Sega CD dels Estats Units",
  /* 291 */ "variant japonesa, per als jocs Mega-CD japonesos",
  /* 292 */ "captures",
  /* 293 */ "captures",
  /* 294 */ "captura",
  /* 295 */ "captures",
  /* 296 */ "captures",
  /* 297 */ "captures",
  /* 298 */ "nuclis",
  /* 299 */ "nuclis",
  /* 300 */ "nucli",
  /* 301 */ "nuclis",
  /* 302 */ "nuclis",
  /* 303 */ "nuclis",
  /* 304 */ "emuladors",
  /* 305 */ "emuladors",
  /* 306 */ "emulador",
  /* 307 */ "emuladors",
  /* 308 */ "emuladors",
  /* 309 */ "emuladors",
  /* 310 */ "fitxers",
  /* 311 */ "fitxers",
  /* 312 */ "fitxer",
  /* 313 */ "fitxers",
  /* 314 */ "fitxers",
  /* 315 */ "fitxers",
  /* 316 */ "jocs",
  /* 317 */ "jocs",
  /* 318 */ "joc",
  /* 319 */ "jocs",
  /* 320 */ "jocs",
  /* 321 */ "jocs",
  /* 322 */ "<code>{rom}</code> se substituirà pel camí del joc. Sense això, el camí s'afegeix al final — que és el que esperen la majoria d'emuladors.",
  /* 323 */ "<strong>Fora de joc, tot es fa amb el comandament:</strong> les direccions recorren la biblioteca, les finestres i la barra de menús; <strong>A</strong> confirma, <strong>B</strong> torna enrere, <strong>Start</strong> obre la barra de menús. Durant la partida, <strong>Select i Start alhora</strong> tornen a la biblioteca — dos botons a la vegada, perquè cadascun serveix per al joc.",
  /* 324 */ "Cap captura. Premeu <strong>F12</strong> durant la partida, o <strong>Select + Y</strong> amb el comandament.",
  /* 325 */ "Cada consola necessita el seu emulador. EvaChi els va a buscar a la forja oficial del projecte libretro, <code>buildbot.libretro.com</code>, i els instal·la en una carpeta seva. No es redistribueix res: són les versions publicades pels seus autors.",
  /* 326 */ "Quatre ranures per joc, desades al disc. La ranura en negreta és la que fan servir <strong>F2</strong> i <strong>F4</strong> — i <strong>Select + L1</strong> / <strong>Select + R1</strong> amb el comandament. Clic dret en una ranura per buidar-la.",
  /* 327 */ "Cada emulador funciona en un procés propi: quan cau, EvaChi ho veu i torna a la biblioteca. La partida en curs es perd, i pot ser que el desament del joc no s'hagi escrit. Apartar aquest emulador el deixa instal·lat però deixa d'oferir-lo. El podreu restablir en qualsevol moment des de <strong>Fitxer → Emuladors</strong>, a baix de la finestra.",
  /* 328 */ "Un sol fitxer per joc al disc <small> Un joc en CD arriba en un full <code>.cue</code> i en tants fitxers <code>.bin</code> com pistes tenia el disc. Només el full s'inicia: les pistes queden amagades mentre hi és. Sense full, no s'amaga res. </small>",
  /* 329 */ "(buit) o --fullscreen {rom}",
  /* 330 */ "Cent per cent és la velocitat pròpia de la consola. Per sota, el joc va més lent; per damunt, vola — i el so el segueix, més greu o més agut. Amb el comandament, l'esquerra i la dreta passen d'un graó al següent. Només els nuclis interns: un emulador extern manté la seva.",
  /* 331 */ "Cinc consoles alhora",
  /* 332 */ "Creu direccional",
  /* 333 */ "D'una inicial a la següent",
  /* 334 */ "Als menús animats, cinc jocs alhora",
  /* 335 */ "Velocitat del joc",
  /* 336 */ "Cancel·la",
  /* 337 */ "Arrossegueu el marc o estireu-ne un cantó. Amb les fletxes el moveu, i amb Maj el feu més gran o més petit. Si surt de la imatge, hi apareixen bandes transparents al voltant: així s'allunya una caràtula massa ajustada. Amb el comandament, les direccions el mouen i els gallets en regulen la mida.",
  /* 338 */ "Retalla",
  /* 339 */ "Retalla la caràtula",
  /* 340 */ "Tota la imatge",
  /* 341 */ "{0} — caràtula retallada",
  /* 342 */ "{0} — cap caràtula per retallar",
  /* 343 */ "caràtula il·legible — {0}",
  /* 344 */ "no s'ha pogut retallar — {0}",
  /* 345 */ "Retalla la caràtula…",
  /* 346 */ "Avanç ràpid, mentre les dues palanques es mantinguin premudes",
  /* 347 */ "{0} apartat",
  /* 348 */ "L'emulador {0} s'ha aturat durant «{1}».",
  /* 349 */ "L'emulador {0} s'ha aturat.",
  /* 350 */ "L'emulador s'ha aturat",
  /* 351 */ "no s'ha pogut apartar — {0}",
  /* 352 */ "s'ha de deixar aquí: {0}",
  /* 353 */ "falta un fitxer de sistema: {0}",
  /* 354 */ "Crèdits",
  /* 355 */ "Llicència no comercial, a saber abans de reprendre aquest treball: {0}.",
  /* 356 */ "EvaChi no escriu cap emulador: n'allotja. Cadascun és un projecte lliure de ple dret, escrit per altres, que EvaChi va a buscar als seus autors a petició — aquí no s'ha copiat ni una línia del seu codi, ni s'ha redistribuït ni un sol byte. Els noms i les llicències de sota són els que cada projecte declara ell mateix.",
  /* 357 */ "Carrusel",
  /* 358 */ "Les caràtules de cara, les consoles en pila, una pols que puja. A la manera d’un expositor.",
  /* 359 */ "Com la interfície",
  /* 360 */ "Llengua de la interfície",
  /* 361 */ "Llengua dels jocs",
  /* 362 */ "Llengua dels jocs: {0}. S'aplicarà al pròxim llançament.",
  /* 363 */ "Enrere",
  /* 364 */ "Cerca",
  /* 365 */ "Cerca les fitxes",
  /* 366 */ "Cerca un valor",
  /* 367 */ "Diferent",
  /* 368 */ "Igual",
  /* 369 */ "Amplada",
  /* 370 */ "El projecte libretro publica fitxes de trucs, una per joc. EvaChi només reté les que van exactament al vostre — mateix títol, mateixa regió, mateixa revisió — i prefereix no proposar res abans que una aproximació: els codis escrits per a una altra versió no escriuen una mica al costat, escriuen en un altre lloc.",
  /* 371 */ "Els trucs",
  /* 372 */ "Menys",
  /* 373 */ "Plafó de trucs",
  /* 374 */ "Més",
  /* 375 */ "Torna a començar",
  /* 376 */ "Trucs",
  /* 377 */ "Trucs…",
  /* 378 */ "Valor",
  /* 379 */ "Val",
  /* 380 */ "{0} adreces possibles",
  /* 381 */ "{0} fitxes posades, {1} retirades",
  /* 382 */ "{0} jocs de {1} tenen una fitxa",
  /* 383 */ "{0} bytes de memòria",
  /* 384 */ "{0} valors descartats: fora de la memòria d’aquest joc",
  /* 385 */ "Cap fitxa per a aquest joc. El plafó « Trucs… » del menú Emulació en cerca una; si no, la cerca de valors funciona amb qualsevol joc.",
  /* 386 */ "Congelada",
  /* 387 */ "Congela",
  /* 388 */ "Jugueu una mica i digueu què ha fet el valor.",
  /* 389 */ "La partida s’ha desat abans del primer truc.",
  /* 390 */ "Cercant…",
];
