/**
 * Les phrases françaises de l'interface, dans l'ordre.
 *
 * Ce fichier est écrit par `outils/cles.mjs`, à partir du contenu réel de la
 * page, du code de la fenêtre et des notes tenues côté natif : une apostrophe
 * droite prise pour une courbe suffirait à ce qu'une traduction ne se trouve
 * plus, et c'est arrivé au premier essai. Chaque langue fournit ses
 * traductions dans ce même ordre, ce qui rend l'alignement vérifiable.
 *
 * Le rang d'une clé connue ne change plus : les nouvelles s'ajoutent à la fin.
 * Ajouter une phrase demande donc une ligne par langue, pas une traduction
 * entière. L'ordre n'est plus alphabétique pour cette raison.
 *
 * 7 d'entre elles portent des balises : ce sont les paragraphes dont le
 * français mêle texte et mise en forme, traduits d'un seul tenant parce que
 * l'ordre des mots change d'une langue à l'autre.
 *
 * Les clés en `nom#categorie` sont les formes d'un nom compté. Elles ne
 * s'affichent jamais telles quelles : `compte()` choisit la bonne selon les
 * règles de la langue.
 */

export const CLES: readonly string[] = [
  "À la manette",
  "A lancer · X favori · L1/R1 consoles · L2/R2 lettre · B retour · Start",
  "À propos d'EvaChi",
  "À propos…",
  "À venir : filtres de tube cathodique, quadrillage, balayage. La place est prête, les filtres arriveront ici.",
  "Actualiser la bibliothèque",
  "Affichage",
  "Afficher les jaquettes des jeux",
  "Aide",
  "Ajouter un dossier de jeux…",
  "Ajouter un dossier…",
  "Appuyez sur un bouton de la manette : la touche correspondante s'allume. Pour en changer une, passez en réassignation, cliquez la touche à modifier, puis pressez le bouton voulu.",
  "Arguments",
  "Au clavier",
  "Aucun jeu",
  "Aucune manette détectée.",
  "Bibliothèque",
  "Bruits de sélection à la manette",
  "Certaines consoles ne démarrent pas sans leur micrologiciel d'origine. EvaChi ne peut pas le fournir : c'est du code sous copyright, qui se copie depuis la machine qu'on possède. Elle dit en revanche lequel manque, sous quel nom, et où le déposer.",
  "Ces consoles n'ont pas de cœur libretro : leur émulateur est un programme à part, qu'EvaChi installe chez elle et lance directement dans le jeu — sans passer par son menu. Les jeux, les clés et les fichiers système restent à votre charge.",
  "Ces réglages ne touchent qu'aux cœurs internes. Un émulateur externe a les siens, et EvaChi ne s'en mêle pas.",
  "Ceux-ci ne sont plus proposés : ils n'ont pas répondu à l'interrogation, ou ils ont fait tomber EvaChi. Les rétablir ne les réinstalle pas — cela les remet simplement dans la liste.",
  "Charger l'état",
  "Cœurs internes seulement. Cliquez un raccourci puis pressez la touche ou le bouton voulu ; à la manette on prend deux boutons à la fois, car chacun d'eux sert déjà au jeu.",
  "Commandes",
  "Commandes…",
  "Consoles récentes",
  "Déclarer un autre émulateur",
  "Directions / stick gauche",
  "Dossiers de jeux",
  "Écarter cet émulateur",
  "Elles viennent du serveur de vignettes du projet libretro, à la demande. Décochée, la bibliothèque ne demande plus rien au réseau.",
  "Emplacements de sauvegarde",
  "Emplacements…",
  "Émulateurs",
  "Émulateurs écartés",
  "Émulateurs externes",
  "Émulateurs externes…",
  "Émulateurs…",
  "Émulation",
  "En cours de partie, revenir à la bibliothèque — deux boutons à la fois, car chacun d'eux sert au jeu",
  "Enregistrer",
  "Extensions",
  "Fermer",
  "Fichier",
  "Fichiers système à installer soi-même",
  "Galerie",
  "Gérer les dossiers…",
  "Graphisme",
  "Graphisme…",
  "Indiquez le dossier où se trouvent vos jeux.",
  "Installation",
  "Installer la sélection",
  "Installer les émulateurs…",
  "Interpréteur",
  "Inutile de savoir où : montrez le dossier où tout traîne — BIOS, clés, micrologiciels, archives, sous-dossiers compris — et EvaChi porte chaque fichier au bon endroit, pour les cœurs comme pour les émulateurs autonomes. Ce que personne ne réclame n'est pas déplacé.",
  "Jaquettes",
  "Journal",
  "Journal…",
  "La fois précédente s'est mal terminée",
  "Lancer le jeu, valider",
  "Langue",
  "Le choix est retenu d'un lancement à l'autre. Chacun a été vérifié lisible : le texte garde partout un contraste suffisant sur son fond.",
  "Le garder",
  "Les émulateurs ci-dessous sont déjà configurés — arguments et formats compris. EvaChi les cherche sur votre disque ; il ne les installe pas.",
  "Liaisons d'origine",
  "Lissage",
  "Mettre le jeu en favori, ou l'en retirer",
  "Musique du menu animé",
  "Nom",
  "Ouvrir la barre de menus",
  "Ouvrir le dossier",
  "Ouvrir le dossier…",
  "Ouvrir un jeu…",
  "par trame",
  "Paramètres du cœur",
  "Paramètres du cœur…",
  "Parcourir la bibliothèque, les fenêtres et la barre de menus",
  "Parcourir…",
  "Pause",
  "Plein écran",
  "Pour les consoles sans cœur libretro. EvaChi lance le programme avec le jeu en argument : l'émulateur démarre directement dans la partie, sans passer par son propre menu.",
  "Prendre une capture",
  "Présentation",
  "Prêt",
  "Programme",
  "Quelques accords tenus et des notes éparses, composés à mesure plutôt qu'enregistrés : le morceau ne repasse jamais au même endroit. Il s'arrête de lui-même dès qu'un jeu démarre.",
  "Ranger un dossier…",
  "Réassigner…",
  "Rechercher un jeu…",
  "Réinitialiser",
  "Retour à la bibliothèque",
  "Revenir en arrière, refermer",
  "Sauvegarde rapide",
  "Sauvegarder l'état",
  "Shaders",
  "Son",
  "Start",
  "Taille de l'image",
  "Thèmes",
  "Thèmes…",
  "Un seul fichier…",
  "Un tic bref en changeant de jeu, un autre en le lançant. Uniquement à la manette : à la souris et au clavier, le geste se sent déjà.",
  "Vitesse",
  "Voir les captures…",
  "Vous pouvez n'en installer qu'une partie — seules les consoles dont l'émulateur est installé apparaissent dans la bibliothèque.",
  "{0} — chargé",
  "{0} — clic droit pour effacer",
  "{0} — mis en favori",
  "{0} — réinitialisé",
  "{0} — retiré des favoris",
  "{0} — téléchargement…",
  "{0} : échec, voir le journal",
  "{0} à disposition",
  "{0} enregistré",
  "{0} est un émulateur externe : il se lance, il ne s'héberge pas",
  "{0} im/s",
  "{0} installé",
  "{0} installé — {1}",
  "{0} installé et prêt",
  "{0} installés, {1} en échec — voir le journal",
  "{0} rétabli",
  "{0} retiré",
  "{0} sur {1}",
  "{0} sur le disque, mais aucun cœur installé ne l'ouvre.",
  "à prendre sur {0}, puis « Parcourir… »",
  "à télécharger",
  "absent, facultatif",
  "Activer",
  "Adouci",
  "ajout impossible — {0}",
  "Ajuster",
  "Ambre",
  "Ardoise",
  "arrêt — {0}",
  "arrêt brutal la fois précédente — {0}",
  "aucun",
  "aucun cœur renvoyé alors que {0} étaient connus — liste précédente conservée",
  "aucun émulateur",
  "Aucun émulateur installé",
  "Aucun jeu reconnu",
  "Aucun résultat",
  "aucune",
  "bibliothèque illisible — {0}",
  "branchée",
  "capture",
  "Changer la jaquette…",
  "Changer…",
  "Chaque pixel sur neuf",
  "Chaque pixel sur quatre : net, sans déformation",
  "Chaque pixel sur seize — pour les grands écrans",
  "Charger",
  "Choisir une jaquette…",
  "choisissez d'abord un jeu dans la bibliothèque",
  "cœur : {0}",
  "cœur non installé",
  "Cœurs installés",
  "cœurs libretro",
  "Contraste élevé",
  "coque native : {0}",
  "déchargement incomplet — {0}",
  "découverte : {0}",
  "découverte interrompue — {0}",
  "Désigner soi-même le programme de {0}",
  "dossier ajouté : {0}",
  "dossier ouvert : {0}",
  "Dossier par défaut",
  "Dossiers ajoutés",
  "Échap",
  "Emplacement {0}",
  "emplacement {0} — {1}",
  "Émulateur utilisé pour ce dossier",
  "émulateurs externes",
  "en cours",
  "en place",
  "enregistrement impossible — {0}",
  "Entrée",
  "EvaChi peut les télécharger depuis la forge officielle libretro. Choisissez les consoles qui vous intéressent.",
  "EvaChi s'est arrêtée en lançant « {0} », avec l'émulateur {1}.",
  "EvaChi s'est arrêtée, avec l'émulateur {0}.",
  "external_systems → {0} émulateurs déclarés",
  "Favori",
  "Favoris",
  "fichiers système illisibles — {0}",
  "Flèches",
  "Game Boy",
  "Grille",
  "il manque {0} à des consoles installées",
  "installation terminée : {0}",
  "Installation…",
  "installé",
  "installé par EvaChi",
  "Installer",
  "interpréteur : {0}",
  "interrogation des cœurs installés…",
  "Lancer",
  "Lancer le jeu choisi",
  "Lavande",
  "Les consoles en rangée, les jeux en colonne, un fond qui ondule. Façon console de salon.",
  "Les contours sont fondus — plus proche d’un vieux téléviseur",
  "Les jaquettes en grand, parcourues à la manette. Pensé pour le canapé.",
  "Les pixels restent carrés, comme sur la machine d’origine",
  "liaisons de manette remises d’origine",
  "list_cores → {0} cœurs annoncés",
  "Liste",
  "liste des cœurs indisponible — {0}",
  "liste des émulateurs indisponible — {0}",
  "Manette",
  "manette : {0}",
  "Manette : {0}",
  "manette débranchée",
  "MANQUANT",
  "Menthe",
  "Menu animé",
  "Mettre à jour",
  "Mettre en favoris",
  "mis à l'écart : {0} · {1}",
  "moins d’une minute",
  "Net",
  "nom, programme et extensions sont tous nécessaires",
  "NON",
  "non installé sur cette machine",
  "Nuit rose",
  "Océan",
  "ou",
  "oui",
  "ouverture impossible — {0}",
  "page web : seuls les cœurs internes sont disponibles, sans bibliothèque",
  "Papier",
  "par défaut",
  "Parcourir la grille et le menu animé",
  "plein écran refusé — {0}",
  "pressez le bouton voulu sur la manette",
  "pressez une touche…",
  "rangement : {0} · {1}",
  "rangement impossible — {0}",
  "recherche des émulateurs interrompue — {0}",
  "Refermer une fenêtre",
  "réinitialisation impossible — {0}",
  "Remplit la fenêtre en gardant les proportions",
  "Reprendre",
  "Reprendre cette sauvegarde — clic droit pour la vider",
  "Rétablir",
  "rétablissement impossible — {0}",
  "Retirer",
  "Retirer des favoris",
  "Retirer la jaquette",
  "retrait impossible — {0}",
  "rien à ranger",
  "rien ne bloque",
  "Rien ne correspond à « {0} ».",
  "Rose et blanc",
  "sans image",
  "Sauvegarder",
  "Sauvegarder ici",
  "sélection impossible — {0}",
  "Taille d’origine de la console, au pixel près",
  "Terminer",
  "thème clair",
  "thème sombre",
  "tout est installé",
  "trouvé : {0}",
  "Un volet par console, en tableau. Le plus dense à la souris.",
  "vide",
  "a poser ici, comme les romsets de jeux : FinalBurn Neo ne cherche que dans ce dossier",
  "ajoute l'écran d'accueil de la console",
  "amorce de la machine",
  "beaucoup de jeux démarrent sans ; le menu de la console non",
  "BIOS américain",
  "BIOS américain et européen",
  "BIOS européen",
  "BIOS japonais",
  "clés de déchiffrement ; sans elles un dépôt chiffré est refusé",
  "dossier des machines de la distribution blueMSX, avec Databases à côté",
  "idem",
  "indispensable aux jeux CD, inutile aux cartes HuCard",
  "indispensable aux jeux Mega-CD, inutile aux cartouches",
  "Kickstart 1.3 ; PUAE se rabat sinon sur AROS, libre mais moins compatible",
  "Kickstart 3.1 ; nécessaire aux jeux AGA, que l'A500 ne sait pas faire tourner",
  "melonDS émule le BIOS par défaut ; le vrai est plus fidèle",
  "mGBA s'en passe ; quelques jeux l'exigent pour leur écran d'accueil",
  "micrologiciel de la console",
  "micrologiciel de la machine",
  "micrologiciel Panasonic FZ-10 ; c'est ce nom qu'Opera prend par défaut",
  "modifié par melonDS, qui préserve l'original en .bak",
  "polices de caractères",
  "réglages et date de la console",
  "sans lui le cœur tourne mais l'écran reste noir",
  "table de caractères de la console",
  "variante américaine, pour les jeux Sega CD des États-Unis",
  "variante japonaise, pour les jeux Mega-CD japonais",
  "capture#few",
  "capture#many",
  "capture#one",
  "capture#other",
  "capture#two",
  "capture#zero",
  "cœur#few",
  "cœur#many",
  "cœur#one",
  "cœur#other",
  "cœur#two",
  "cœur#zero",
  "émulateur#few",
  "émulateur#many",
  "émulateur#one",
  "émulateur#other",
  "émulateur#two",
  "émulateur#zero",
  "fichier#few",
  "fichier#many",
  "fichier#one",
  "fichier#other",
  "fichier#two",
  "fichier#zero",
  "jeu#few",
  "jeu#many",
  "jeu#one",
  "jeu#other",
  "jeu#two",
  "jeu#zero",
  "<code>{rom}</code> sera remplacé par le chemin du jeu. Sans lui, le chemin est ajouté à la fin — ce qu'attendent la plupart des émulateurs.",
  "<strong>Hors jeu, tout se fait à la manette :</strong> les directions parcourent la bibliothèque, les fenêtres et la barre de menus ; <strong>A</strong> valide, <strong>B</strong> revient en arrière, <strong>Start</strong> ouvre la barre de menus. En cours de partie, <strong>Select et Start ensemble</strong> ramènent à la bibliothèque — deux boutons à la fois, car chacun d'eux sert au jeu.",
  "Aucune capture. Pressez <strong>F12</strong> en cours de partie, ou <strong>Select + Y</strong> à la manette.",
  "Chaque console a besoin de son émulateur. EvaChi va les chercher sur la forge officielle du projet libretro, <code>buildbot.libretro.com</code>, et les installe dans son propre dossier. Rien n'est redistribué : ce sont les versions publiées par leurs auteurs.",
  "Quatre emplacements par jeu, gardés sur le disque. L'emplacement en gras est celui qu'utilisent <strong>F2</strong> et <strong>F4</strong> — et <strong>Select + L1</strong> / <strong>Select + R1</strong> à la manette. Clic droit sur un emplacement pour le vider.",
  "Un émulateur tourne dans la même fenêtre qu'EvaChi : quand il tombe, il l'emporte avec lui, sans message. Écarter cet émulateur le laisse installé mais cesse de le proposer. Vous pourrez le rétablir à tout moment depuis <strong>Fichier → Émulateurs</strong>, en bas de la fenêtre.",
  "Un seul fichier par jeu sur disque <small> Un jeu sur CD arrive en un feuillet <code>.cue</code> et en autant de fichiers <code>.bin</code> que le disque avait de pistes. Seul le feuillet se lance : les pistes sont masquées quand il est là. Sans feuillet, rien n'est masqué. </small>",
  "(vide) ou --fullscreen {rom}",
  "Cent pour cent, c'est la vitesse de la console. En dessous le jeu ralentit, au-dessus il file — et le son suit, plus grave ou plus aigu. À la manette, gauche et droite passent d'un palier au suivant. Les cœurs internes seulement : un émulateur externe garde la sienne.",
  "Cinq consoles à la fois",
  "Croix directionnelle",
  "D'une initiale à la suivante",
  "Dans le menu animé, cinq jeux à la fois",
  "Vitesse du jeu",
];

/**
 * Les rangs des phrases qui portent des balises.
 *
 * Relevés sur les clés elles-mêmes plutôt que comptés depuis la fin : les
 * nouvelles clés s'ajoutant après, « les sept dernières » a cessé d'être vrai.
 */
export const AVEC_BALISES: readonly number[] = CLES.reduce<number[]>(
  (rangs, clef, rang) => (/<\/?[a-z]+>/.test(clef) ? [...rangs, rang] : rangs),
  [],
);
