/**
 * Tchèque — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros portés en commentaire sont là pour qu'on puisse le vérifier à
 * l'œil, ligne à ligne.
 */

export const cs: readonly string[] = [
  /* 1 */ "Na ovladači",
  /* 2 */ "A spustit · X oblíbená · Y oříznout · L1/R1 konzole · L2/R2 písmeno · B zpět",
  /* 3 */ "O aplikaci EvaChi",
  /* 4 */ "O aplikaci…",
  /* 5 */ "Co obrazovka s elektronkou dělala s obrazem a co tehdejší hry braly jako samozřejmost. Platí jen pro jádra hraná zde: samostatný emulátor kreslí svůj obraz sám.",
  /* 6 */ "Obnovit knihovnu",
  /* 7 */ "Zobrazení",
  /* 8 */ "Zobrazovat obaly her",
  /* 9 */ "Nápověda",
  /* 10 */ "Přidat složku s hrami…",
  /* 11 */ "Přidat složku…",
  /* 12 */ "Stiskněte tlačítko na ovladači: odpovídající příkaz se rozsvítí. Chcete-li nějaký změnit, klikněte na políčko dole a stiskněte požadované tlačítko. Tlačítko pak změní majitele: dva příkazy na jednom tlačítku by vypadaly jako porucha.",
  /* 13 */ "Argumenty",
  /* 14 */ "Na klávesnici",
  /* 15 */ "Žádné hry",
  /* 16 */ "Nenalezen žádný ovladač.",
  /* 17 */ "Knihovna",
  /* 18 */ "Zvuky výběru na ovladači",
  /* 19 */ "Některé konzole se bez původního firmwaru nespustí. EvaChi ho dodat nemůže: je to chráněný kód, který se kopíruje z přístroje, jejž člověk vlastní. Řekne ale, který chybí, pod jakým názvem a kam ho položit.",
  /* 20 */ "Tyto konzole nemají libretro jádro: jejich emulátor je samostatný program, který si EvaChi nainstaluje k sobě a spouští rovnou ve hře — bez procházení jeho nabídky. Hry, klíče a systémové soubory zůstávají na vás.",
  /* 21 */ "Tato nastavení se týkají jen vnitřních jader. Externí emulátor má svá vlastní a EvaChi do nich nezasahuje.",
  /* 22 */ "Tyto se už nenabízejí: neodpověděly na dotaz, nebo shodily EvaChi. Obnovením se znovu nenainstalují — jen se vrátí do seznamu.",
  /* 23 */ "Načíst stav…",
  /* 24 */ "Jen vnitřní jádra. Klikněte na zkratku a stiskněte požadovanou klávesu nebo tlačítko; na ovladači se berou dvě tlačítka najednou, protože každé z nich už slouží hře.",
  /* 25 */ "Ovládání",
  /* 26 */ "Ovládání…",
  /* 27 */ "Nedávné konzole",
  /* 28 */ "Přidat další emulátor",
  /* 29 */ "Směry / levá páčka",
  /* 30 */ "Složky s hrami",
  /* 31 */ "Vyřadit tento emulátor",
  /* 32 */ "Berou se na vyžádání ze serveru s náhledy projektu libretro. Bez zaškrtnutí si knihovna ze sítě nevyžádá nic.",
  /* 33 */ "Pozice uložení",
  /* 34 */ "Pozice uložení…",
  /* 35 */ "Emulátory",
  /* 36 */ "Vyřazené emulátory",
  /* 37 */ "Externí emulátory",
  /* 38 */ "Externí emulátory…",
  /* 39 */ "Emulátory…",
  /* 40 */ "Emulace",
  /* 41 */ "Během hry návrat do knihovny — dvě tlačítka najednou, protože každé z nich slouží hře",
  /* 42 */ "Uložit",
  /* 43 */ "Přípony",
  /* 44 */ "Zavřít",
  /* 45 */ "Soubor",
  /* 46 */ "Systémové soubory, které doplníte sami",
  /* 47 */ "Galerie",
  /* 48 */ "Spravovat složky…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Určete složku, kde máte hry.",
  /* 52 */ "Instalace",
  /* 53 */ "Nainstalovat vybrané",
  /* 54 */ "Nainstalovat emulátory…",
  /* 55 */ "Interpret",
  /* 56 */ "Nemusíte vědět kam: ukažte složku, kde se to všechno válí — BIOSy, klíče, firmware, archivy i s podsložkami — a EvaChi odnese každý soubor na správné místo, pro jádra i pro samostatné emulátory. Co nikdo nežádá, zůstane ležet.",
  /* 57 */ "Obaly",
  /* 58 */ "Záznam",
  /* 59 */ "Záznam…",
  /* 60 */ "Minule to skončilo špatně",
  /* 61 */ "Spustit hru, potvrdit",
  /* 62 */ "Jazyk",
  /* 63 */ "Volba se pamatuje mezi spuštěními. U každého je ověřená čitelnost: text má všude dostatečný kontrast vůči svému pozadí.",
  /* 64 */ "Ponechat",
  /* 65 */ "Emulátory níže jsou už nastavené — včetně argumentů a formátů. EvaChi je hledá na vašem disku; neinstaluje je.",
  /* 66 */ "Výchozí přiřazení",
  /* 67 */ "Vyhlazování",
  /* 68 */ "Přidat hru k oblíbeným, nebo ji odebrat",
  /* 69 */ "Hudba animovaných nabídek",
  /* 70 */ "Název",
  /* 71 */ "Otevřít panel nabídek",
  /* 72 */ "Otevřít složku",
  /* 73 */ "Otevřít složku…",
  /* 74 */ "Otevřít hru…",
  /* 75 */ "na snímek",
  /* 76 */ "Nastavení jádra",
  /* 77 */ "Nastavení jádra…",
  /* 78 */ "Procházet knihovnu, okna a panel nabídek",
  /* 79 */ "Procházet…",
  /* 80 */ "Pauza",
  /* 81 */ "Celá obrazovka",
  /* 82 */ "Pro konzole bez libretro jádra. EvaChi spustí program s hrou jako argumentem: emulátor naskočí rovnou do hry, aniž by šel přes vlastní nabídku.",
  /* 83 */ "Pořídit snímek",
  /* 84 */ "Rozvržení",
  /* 85 */ "Připraveno",
  /* 86 */ "Program",
  /* 87 */ "Pár držených akordů a roztroušené tóny, skládané za pochodu místo nahrané: skladba se nikdy nevrátí na stejné místo. Sama ztichne, jakmile se spustí hra.",
  /* 88 */ "Uklidit složku…",
  /* 89 */ "Vyprázdnit",
  /* 90 */ "Hledat hru…",
  /* 91 */ "Vrátit výchozí",
  /* 92 */ "Zpět do knihovny",
  /* 93 */ "Vrátit se zpět, zavřít",
  /* 94 */ "Rychlé uložení",
  /* 95 */ "Uložit stav…",
  /* 96 */ "Shadery",
  /* 97 */ "Zvuk",
  /* 98 */ "Start",
  /* 99 */ "Velikost obrazu",
  /* 100 */ "Motivy",
  /* 101 */ "Motivy…",
  /* 102 */ "Jeden soubor…",
  /* 103 */ "Krátké cvaknutí při přechodu na jinou hru, další při jejím spuštění. Jen na ovladači: u myši a klávesnice je pohyb cítit sám o sobě.",
  /* 104 */ "Rychlost",
  /* 105 */ "Zobrazit snímky…",
  /* 106 */ "Nemusíte instalovat všechny — v knihovně se objeví jen konzole, jejichž emulátor je nainstalovaný.",
  /* 107 */ "{0} — načteno",
  /* 108 */ "{0} — pravým tlačítkem vymažete",
  /* 109 */ "{0} — přidáno k oblíbeným",
  /* 110 */ "{0} — vráceno na výchozí",
  /* 111 */ "{0} — odebráno z oblíbených",
  /* 112 */ "{0} — stahování…",
  /* 113 */ "{0}: nezdařilo se, viz záznam",
  /* 114 */ "{0} k dispozici",
  /* 115 */ "{0} uloženo",
  /* 116 */ "{0} je externí emulátor: spouští se zvlášť, uvnitř neběží",
  /* 117 */ "{0} sn/s",
  /* 118 */ "{0} nainstalováno",
  /* 119 */ "{0} nainstalováno — {1}",
  /* 120 */ "{0} nainstalováno a připraveno",
  /* 121 */ "{0} nainstalováno, {1} se nezdařilo — viz záznam",
  /* 122 */ "{0} obnoveno",
  /* 123 */ "{0} odebráno",
  /* 124 */ "{0} z {1}",
  /* 125 */ "{0} na disku, ale žádné nainstalované jádro je neotevře.",
  /* 126 */ "vezměte z {0}, pak „Procházet…“",
  /* 127 */ "ke stažení",
  /* 128 */ "chybí, nepovinné",
  /* 129 */ "Zapnout",
  /* 130 */ "Měkké",
  /* 131 */ "nelze přidat — {0}",
  /* 132 */ "Přizpůsobit",
  /* 133 */ "Jantar",
  /* 134 */ "Břidlice",
  /* 135 */ "zastaveno — {0}",
  /* 136 */ "minule náhlý pád — {0}",
  /* 137 */ "žádný",
  /* 138 */ "nevrácena žádná jádra, ačkoli {0} byla známa — ponechán předchozí seznam",
  /* 139 */ "žádný emulátor",
  /* 140 */ "Není nainstalovaný žádný emulátor",
  /* 141 */ "Žádná rozpoznaná hra",
  /* 142 */ "Žádný výsledek",
  /* 143 */ "žádná",
  /* 144 */ "knihovnu nelze přečíst — {0}",
  /* 145 */ "připojen",
  /* 146 */ "snímek",
  /* 147 */ "Změnit obal…",
  /* 148 */ "Změnit…",
  /* 149 */ "Každý pixel na devět",
  /* 150 */ "Každý pixel na čtyři: ostré, bez deformace",
  /* 151 */ "Každý pixel na šestnáct — pro velké obrazovky",
  /* 152 */ "Načíst",
  /* 153 */ "Vybrat obal…",
  /* 154 */ "nejdřív vyberte hru v knihovně",
  /* 155 */ "jádro: {0}",
  /* 156 */ "jádro není nainstalované",
  /* 157 */ "Nainstalovaná jádra",
  /* 158 */ "libretro jádra",
  /* 159 */ "Vysoký kontrast",
  /* 160 */ "nativní obal: {0}",
  /* 161 */ "neúplné uvolnění — {0}",
  /* 162 */ "objeveno: {0}",
  /* 163 */ "hledání přerušeno — {0}",
  /* 164 */ "Určit program pro {0} ručně",
  /* 165 */ "složka přidána: {0}",
  /* 166 */ "složka otevřena: {0}",
  /* 167 */ "Výchozí složka",
  /* 168 */ "Přidané složky",
  /* 169 */ "Esc",
  /* 170 */ "Pozice {0}",
  /* 171 */ "pozice {0} — {1}",
  /* 172 */ "Emulátor pro tuto složku",
  /* 173 */ "externí emulátory",
  /* 174 */ "probíhá",
  /* 175 */ "na místě",
  /* 176 */ "nelze uložit — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi je umí stáhnout z oficiální dílny libretro. Vyberte konzole, které vás zajímají.",
  /* 179 */ "EvaChi se zastavila při spouštění „{0}“ s emulátorem {1}.",
  /* 180 */ "EvaChi se zastavila, s emulátorem {0}.",
  /* 181 */ "external_systems → ohlášeno emulátorů: {0}",
  /* 182 */ "Oblíbená",
  /* 183 */ "Oblíbené",
  /* 184 */ "systémové soubory nelze přečíst — {0}",
  /* 185 */ "Šipky",
  /* 186 */ "Game Boy",
  /* 187 */ "Mřížka",
  /* 188 */ "nainstalovaným konzolím chybí {0}",
  /* 189 */ "instalace dokončena: {0}",
  /* 190 */ "Instalace…",
  /* 191 */ "nainstalováno",
  /* 192 */ "nainstalovala EvaChi",
  /* 193 */ "Nainstalovat",
  /* 194 */ "interpret: {0}",
  /* 195 */ "dotaz na nainstalovaná jádra…",
  /* 196 */ "Spustit",
  /* 197 */ "Spustit vybranou hru",
  /* 198 */ "Levandule",
  /* 199 */ "Konzole v řadě, hry ve sloupci, vlnící se pozadí. Po vzoru herní konzole.",
  /* 200 */ "Obrysy jsou rozmlžené — blíž starému televizoru",
  /* 201 */ "Obaly ve velkém, procházené ovladačem. Myšleno pro gauč.",
  /* 202 */ "Pixely zůstávají hranaté, jako na původním přístroji",
  /* 203 */ "přiřazení ovladače vrácena na výchozí",
  /* 204 */ "list_cores → ohlášeno jader: {0}",
  /* 205 */ "Seznam",
  /* 206 */ "seznam jader není dostupný — {0}",
  /* 207 */ "seznam emulátorů není dostupný — {0}",
  /* 208 */ "Ovladač",
  /* 209 */ "ovladač: {0}",
  /* 210 */ "Ovladač: {0}",
  /* 211 */ "ovladač odpojen",
  /* 212 */ "CHYBÍ",
  /* 213 */ "Máta",
  /* 214 */ "Animovaná nabídka",
  /* 215 */ "Aktualizovat",
  /* 216 */ "Přidat k oblíbeným",
  /* 217 */ "vyřazeno: {0} · {1}",
  /* 218 */ "méně než minuta",
  /* 219 */ "Ostré",
  /* 220 */ "název, program i přípony jsou potřeba všechny",
  /* 221 */ "NE",
  /* 222 */ "na tomto počítači není nainstalován",
  /* 223 */ "Růžová noc",
  /* 224 */ "Oceán",
  /* 225 */ "nebo",
  /* 226 */ "ano",
  /* 227 */ "nelze otevřít — {0}",
  /* 228 */ "webová stránka: dostupná jsou jen vnitřní jádra, bez knihovny",
  /* 229 */ "Papír",
  /* 230 */ "výchozí",
  /* 231 */ "Procházet mřížku a animované nabídky",
  /* 232 */ "celá obrazovka odmítnuta — {0}",
  /* 233 */ "stiskněte požadované tlačítko na ovladači",
  /* 234 */ "stiskněte klávesu…",
  /* 235 */ "úklid: {0} · {1}",
  /* 236 */ "úklid se nezdařil — {0}",
  /* 237 */ "hledání emulátorů přerušeno — {0}",
  /* 238 */ "Zavřít okno",
  /* 239 */ "nelze vrátit výchozí — {0}",
  /* 240 */ "Vyplní okno se zachováním poměru stran",
  /* 241 */ "Pokračovat",
  /* 242 */ "Nahradit",
  /* 243 */ "Obnovit",
  /* 244 */ "nelze obnovit — {0}",
  /* 245 */ "Odebrat",
  /* 246 */ "Odebrat z oblíbených",
  /* 247 */ "Odebrat obal",
  /* 248 */ "nelze odebrat — {0}",
  /* 249 */ "není co uklízet",
  /* 250 */ "nic nepřekáží",
  /* 251 */ "Nic neodpovídá „{0}“.",
  /* 252 */ "Růžová a bílá",
  /* 253 */ "bez obrázku",
  /* 254 */ "Uložit",
  /* 255 */ "Uložit sem",
  /* 256 */ "nelze vybrat — {0}",
  /* 257 */ "Původní velikost konzole, pixel na pixel",
  /* 258 */ "Zahodit",
  /* 259 */ "světlý motiv",
  /* 260 */ "tmavý motiv",
  /* 261 */ "vše je nainstalováno",
  /* 262 */ "nalezeno: {0}",
  /* 263 */ "Jeden oddíl pro každou konzoli, v tabulce. S myší nejhustší.",
  /* 264 */ "prázdné",
  /* 265 */ "položte sem, stejně jako romsety her: FinalBurn Neo hledá jen v této složce",
  /* 266 */ "přidá úvodní obrazovku konzole",
  /* 267 */ "zavaděč přístroje",
  /* 268 */ "spousta her se spustí i bez něj; nabídka konzole ne",
  /* 269 */ "americký BIOS",
  /* 270 */ "americký a evropský BIOS",
  /* 271 */ "evropský BIOS",
  /* 272 */ "japonský BIOS",
  /* 273 */ "dešifrovací klíče; bez nich se zašifrovaná kopie odmítne",
  /* 274 */ "složka Machines z distribuce blueMSX, vedle ní Databases",
  /* 275 */ "totéž",
  /* 276 */ "nutný pro hry na CD, pro karty HuCard zbytečný",
  /* 277 */ "nutný pro hry Mega-CD, pro cartridge zbytečný",
  /* 278 */ "Kickstart 1.3; jinak PUAE sáhne po AROS, svobodném, ale méně kompatibilním",
  /* 279 */ "Kickstart 3.1; nutný pro hry AGA, které A500 neutáhne",
  /* 280 */ "melonDS ve výchozím stavu BIOS emuluje; ten pravý je věrnější",
  /* 281 */ "mGBA se bez něj obejde; pár her ho vyžaduje kvůli úvodní obrazovce",
  /* 282 */ "firmware konzole",
  /* 283 */ "firmware přístroje",
  /* 284 */ "firmware Panasonic FZ-10; právě tento název bere Opera jako výchozí",
  /* 285 */ "upravuje ho melonDS, původní zachová jako .bak",
  /* 286 */ "písma",
  /* 287 */ "nastavení a datum konzole",
  /* 288 */ "bez něj jádro běží, ale obrazovka zůstane černá",
  /* 289 */ "znaková sada konzole",
  /* 290 */ "americká varianta, pro hry Sega CD ze Spojených států",
  /* 291 */ "japonská varianta, pro japonské hry Mega-CD",
  /* 292 */ "snímky",
  /* 293 */ "snímku",
  /* 294 */ "snímek",
  /* 295 */ "snímků",
  /* 296 */ "snímky",
  /* 297 */ "snímků",
  /* 298 */ "jádra",
  /* 299 */ "jádra",
  /* 300 */ "jádro",
  /* 301 */ "jader",
  /* 302 */ "jádra",
  /* 303 */ "jader",
  /* 304 */ "emulátory",
  /* 305 */ "emulátoru",
  /* 306 */ "emulátor",
  /* 307 */ "emulátorů",
  /* 308 */ "emulátory",
  /* 309 */ "emulátorů",
  /* 310 */ "soubory",
  /* 311 */ "souboru",
  /* 312 */ "soubor",
  /* 313 */ "souborů",
  /* 314 */ "soubory",
  /* 315 */ "souborů",
  /* 316 */ "hry",
  /* 317 */ "hry",
  /* 318 */ "hra",
  /* 319 */ "her",
  /* 320 */ "hry",
  /* 321 */ "her",
  /* 322 */ "<code>{rom}</code> se nahradí cestou ke hře. Bez něj se cesta připojí na konec — což většina emulátorů očekává.",
  /* 323 */ "<strong>Mimo hru se všechno dělá ovladačem:</strong> směry procházejí knihovnu, okna i panel nabídek; <strong>A</strong> potvrzuje, <strong>B</strong> vrací zpět, <strong>Start</strong> otevírá panel nabídek. Během hry vrátí do knihovny <strong>Select a Start naráz</strong> — dvě tlačítka najednou, protože každé z nich slouží hře.",
  /* 324 */ "Žádné snímky. Během hry stiskněte <strong>F12</strong>, nebo <strong>Select + Y</strong> na ovladači.",
  /* 325 */ "Každá konzole potřebuje svůj emulátor. EvaChi je stahuje z oficiální dílny projektu libretro, <code>buildbot.libretro.com</code>, a instaluje je do své vlastní složky. Nic se nešíří dál: jsou to verze vydané jejich autory.",
  /* 326 */ "Čtyři pozice na hru, uložené na disku. Každý úkon je napsaný pod pozicí a nahrazení či vyprázdnění si žádá potvrzení. <strong>F2</strong> a <strong>F4</strong> — a <strong>Select + L1</strong> / <strong>Select + R1</strong> na ovladači — míří rovnou na tučnou pozici, aniž by se na cokoli ptaly.",
  /* 327 */ "Každý emulátor běží ve vlastním procesu: když spadne, EvaChi to vidí a vrátí se do knihovny. Rozehraná hra je ztracená a její uložení se možná nestihlo zapsat. Vyřazením zůstane nainstalovaný, jen se přestane nabízet. Kdykoli ho můžete obnovit přes <strong>Soubor → Emulátory</strong>, dole v okně.",
  /* 328 */ "Jeden soubor na hru na disku <small> Hra na CD přijde jako soupis <code>.cue</code> a tolik souborů <code>.bin</code>, kolik mělo CD stop. Spouští se jen soupis: stopy se skryjí, když je na místě. Bez soupisu se neskryje nic. </small>",
  /* 329 */ "(prázdné) nebo --fullscreen {rom}",
  /* 330 */ "Sto procent je vlastní rychlost konzole. Pod ní se hra zpomalí, nad ní letí — a zvuk jde s ní, hlubší, nebo vyšší. Na ovladači vlevo a vpravo přepínají z jednoho stupně na další. Jen vnitřní jádra: externí emulátor si drží svou rychlost.",
  /* 331 */ "Pět konzolí najednou",
  /* 332 */ "Směrový kříž",
  /* 333 */ "Z jednoho počátečního písmene na další",
  /* 334 */ "V animovaných nabídkách pět her najednou",
  /* 335 */ "Rychlost hry",
  /* 336 */ "Zrušit",
  /* 337 */ "Přetáhněte rámeček nebo zatáhněte za roh. Šipkami se posouvá, se Shiftem se zvětšuje a zmenšuje. Když přesáhne obrázek, přibudou kolem průhledné pruhy – tak oddálíte obal, který je moc natěsno. Na ovladači posouvají směrová tlačítka a velikost ladí spouště.",
  /* 338 */ "Oříznout",
  /* 339 */ "Oříznout obal",
  /* 340 */ "Celý obrázek",
  /* 341 */ "{0} — obal oříznut",
  /* 342 */ "{0} — žádný obal k oříznutí",
  /* 343 */ "obal nečitelný — {0}",
  /* 344 */ "oříznutí se nezdařilo — {0}",
  /* 345 */ "Oříznout obal…",
  /* 346 */ "Rychlý posun vpřed, dokud obě páčky zůstávají stisknuté",
  /* 347 */ "{0} vyřazeno",
  /* 348 */ "Emulátor {0} se zastavil během „{1}“.",
  /* 349 */ "Emulátor {0} se zastavil.",
  /* 350 */ "Emulátor se zastavil",
  /* 351 */ "vyřazení se nezdařilo — {0}",
  /* 352 */ "položte sem: {0}",
  /* 353 */ "chybí systémový soubor: {0}",
  /* 354 */ "Zásluhy",
  /* 355 */ "Nekomerční licence, o které je dobré vědět, než na tuto práci někdo naváže: {0}.",
  /* 356 */ "EvaChi nepíše žádný emulátor: hostí je. Každý z nich je plnohodnotný svobodný projekt, napsaný jinými, a EvaChi si pro něj na vyžádání dojde k jeho autorům — ani řádek jejich kódu se zde neopisuje, ani bajt se dál nešíří. Jména a licence níže jsou ty, které každý projekt uvádí sám o sobě.",
  /* 357 */ "Kolotoč",
  /* 358 */ "Obaly zpředu, konzole na sobě, stoupající prach. Ve stylu výkladního stojanu.",
  /* 359 */ "Jako rozhraní",
  /* 360 */ "Jazyk rozhraní",
  /* 361 */ "Jazyk her",
  /* 362 */ "Jazyk her: {0}. Projeví se při příštím spuštění.",
  /* 363 */ "Zpět",
  /* 364 */ "Hledat",
  /* 365 */ "Najít soubory",
  /* 366 */ "Najít hodnotu",
  /* 367 */ "Jiné",
  /* 368 */ "Stejné",
  /* 369 */ "Šířka",
  /* 370 */ "Projekt libretro zveřejňuje soubory s cheaty, jeden na hru. EvaChi ponechá jen ty, které se k vaší hře hodí přesně — stejný název, stejný region, stejná revize — a raději nenabídne nic než přibližnost: kódy psané pro jinou verzi nezapisují kousek vedle, zapisují jinam.",
  /* 371 */ "Cheaty",
  /* 372 */ "Méně",
  /* 373 */ "Panel cheatů",
  /* 374 */ "Více",
  /* 375 */ "Začít znovu",
  /* 376 */ "Cheaty",
  /* 377 */ "Cheaty…",
  /* 378 */ "Hodnota",
  /* 379 */ "Rovná se",
  /* 380 */ "{0} možných adres",
  /* 381 */ "{0} souborů uloženo, {1} odebráno",
  /* 382 */ "{0} z {1} her má soubor",
  /* 383 */ "{0} bajtů paměti",
  /* 384 */ "{0} hodnot vyřazeno: mimo paměť této hry",
  /* 385 */ "Pro tuto hru není soubor. Panel „Cheaty…“ v nabídce Emulace jej hledá; jinak hledání hodnoty funguje u každé hry.",
  /* 386 */ "Zmrazena",
  /* 387 */ "Zmrazit",
  /* 388 */ "Chvíli hrajte a pak řekněte, co hodnota udělala.",
  /* 389 */ "Hra byla odložena stranou před prvním cheatem.",
  /* 390 */ "Hledání…",
  /* 391 */ "Co se položí do « drop u'r rom », putuje ke konzoli, kterou určuje přípona. Když ji sdílí několik konzolí — obrazy disků — EvaChi se raději zeptá, než aby hádala.",
  /* 392 */ "Potvrzení",
  /* 393 */ "Smazat uloženou hru…",
  /* 394 */ "Roztažení",
  /* 395 */ "Hra si své počty drží v paměti, ale neřekne kde. Najdou se vylučováním: řeknete, co zobrazené číslo udělalo, a EvaChi vyřadí adresy, které to neudělaly také.",
  /* 396 */ "Ano",
  /* 397 */ "Málokterá konzole má poměry dnešní obrazovky, odtud černé pruhy po stranách. Na nule si obraz své poměry zachová; na stu vyplní okno, i za cenu protažení.",
  /* 398 */ "Uklízení her",
  /* 399 */ "Uklidit",
  /* 400 */ "Uklidit odložené hry…",
  /* 401 */ "Vidíte 47 životů: napište 47 do pole « Hodnota » a stiskněte « Hledat ». Jeden ztraťte, napište 46 a stiskněte « Rovná se ». Pokud číslo není nikde napsané, nechte « Hodnota » prázdné a mezi dvěma okamžiky hry řekněte jen « Více », « Méně », « Jiné » nebo « Stejné ». Nalezenou hodnotu pak udrží « Zmrazit ». « Šířka » je velikost čísla: 1 do 255, 2 výše, 4 pro velké čítače.",
  /* 402 */ "uklizeno: {0}",
  /* 403 */ "není co mazat",
  /* 404 */ "Tlačítka",
  /* 405 */ "Už v knihovně: {0}",
  /* 406 */ "Smazat uloženou hru {0} a začít od začátku? Probíhající hra se zastaví a to, co si hra poznamenala, bude ztraceno.",
  /* 407 */ "Spouště",
  /* 408 */ "Ponechat obojí",
  /* 409 */ "Nechat v odkladišti",
  /* 410 */ "Odkladiště je prázdné.",
  /* 411 */ "Nahradit pozici {0}? Co je tam uloženo, bude ztraceno.",
  /* 412 */ "uložená hra smazána — {0}",
  /* 413 */ "Systém",
  /* 414 */ "Vyprázdnit pozici {0}? Co je tam uloženo, bude ztraceno.",
  /* 415 */ "Mrtvá zóna je ta část páčky, ve které ji ještě považujeme za v klidu. Příliš malá — postava se sama rozejde, i když ovladač leží na stole; příliš velká — drobné pohyby se ztratí. Některé hry chtějí, abyste konzolí zatřásli: když to ovladač neumí ucítit, dvě tlačítka níže hru přesvědčí, že se tak stalo.",
  /* 416 */ "Páčka",
  /* 417 */ "Samostatné emulátory mají vlastní tlačítka ve vlastních souborech. Co zde změníte, se k nim okamžitě přenese — u těch, jejichž formát známe z první ruky: PCSX2, PPSSPP a Dolphin. Staré nastavení se při prvním průchodu odloží stranou, pod stejným jménem s příponou « .avant-evachi ».",
  /* 418 */ "Přenést do externích emulátorů",
  /* 419 */ "Mrtvá zóna",
  /* 420 */ "Promítání",
  /* 421 */ "Hlína",
  /* 422 */ "žádný externí emulátor zatím nezapsal své nastavení",
  /* 423 */ "Žhavé uhlí",
  /* 424 */ "Popel",
  /* 425 */ "Višeň",
  /* 426 */ "Korál",
  /* 427 */ "Balíček",
  /* 428 */ "Les",
  /* 429 */ "Jinovatka",
  /* 430 */ "externí emulátory už tato tlačítka měly",
  /* 431 */ "Půlnoc",
  /* 432 */ "Mech",
  /* 433 */ "Neon",
  /* 434 */ "Švestka",
  /* 435 */ "Písek",
  /* 436 */ "Zatřást",
  /* 437 */ "Sépie",
  /* 438 */ "přenesená tlačítka: {0}",
  /* 439 */ "Tyrkys",
  /* 440 */ "Obaly držené ve vějíři jako karty v ruce. Zápěstí se otočí a čtená karta se narovná.",
  /* 441 */ "Temný sál, kužel světla plný prachu a hra promítaná ve velkém. Ostatní čekají v zásobníku.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Meruňka",
  /* 444 */ "Vřes",
  /* 445 */ "Karamel",
  /* 446 */ "Měď",
  /* 447 */ "Inkoust",
  /* 448 */ "Famicom",
  /* 449 */ "Nefrit",
  /* 450 */ "Borůvka",
  /* 451 */ "Bouře",
  /* 452 */ "Perla",
  /* 453 */ "Pistácie",
  /* 454 */ "Žádný",
  /* 455 */ "Řádkování",
  /* 456 */ "Každý pixel ve třech štěrbinách: červené, zelené a modré",
  /* 457 */ "Obraz jádra, pixel po pixelu",
  /* 458 */ "Vypouklé sklo, řádky, štěrbiny a zhaslé okraje",
  /* 459 */ "Mřížka",
  /* 460 */ "Obrazovka",
  /* 461 */ "Každý druhý řádek ztmavený, jako na televizi",
  /* 462 */ "Otevře emulátor v jeho vlastním okně, bez hry",
  /* 463 */ "Otevřít",
  /* 464 */ "Hlasitost",
  /* 465 */ "Disk",
  /* 466 */ "disk nelze vyměnit — {0}",
  /* 467 */ "disk {0}",
];
