/**
 * Danois — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros mis en commentaire devant chaque ligne sont là pour qu'on puisse
 * le vérifier à l'œil.
 */

export const da: readonly string[] = [
  /* 1 */ "Med controller",
  /* 2 */ "A start · X favorit · L1/R1 konsoller · L2/R2 bogstav · B tilbage · Start",
  /* 3 */ "Om EvaChi",
  /* 4 */ "Om…",
  /* 5 */ "På vej: filtre til billedrør, pixelgitter og scanlines. Pladsen er gjort klar, filtrene lander her.",
  /* 6 */ "Opdater biblioteket",
  /* 7 */ "Vis",
  /* 8 */ "Vis spillenes omslag",
  /* 9 */ "Hjælp",
  /* 10 */ "Tilføj en spilmappe…",
  /* 11 */ "Tilføj en mappe…",
  /* 12 */ "Tryk på en knap på controlleren: den tilsvarende tast lyser op. Vil du ændre en, så skift til omtildeling, klik på tasten, der skal ændres, og tryk så på den ønskede knap.",
  /* 13 */ "Argumenter",
  /* 14 */ "På tastatur",
  /* 15 */ "Ingen spil",
  /* 16 */ "Ingen controller fundet.",
  /* 17 */ "Bibliotek",
  /* 18 */ "Lyd ved valg med controller",
  /* 19 */ "Nogle konsoller starter ikke uden deres oprindelige firmware. EvaChi kan ikke levere den: det er ophavsretligt beskyttet kode, som kopieres fra den maskine, man selv ejer. Til gengæld fortæller EvaChi hvilken der mangler, under hvilket navn, og hvor den skal lægges.",
  /* 20 */ "Disse konsoller har ingen libretro-kerne: deres emulator er et program for sig, som EvaChi installerer hos sig selv og starter direkte ind i spillet — uden om emulatorens egen menu. Spillene, nøglerne og systemfilerne står du selv for.",
  /* 21 */ "Disse indstillinger rører kun de indbyggede kerner. En ekstern emulator har sine egne, og dem blander EvaChi sig ikke i.",
  /* 22 */ "Disse bliver ikke længere tilbudt: de svarede ikke, da de blev spurgt, eller de fik EvaChi til at gå ned. At gendanne dem geninstallerer dem ikke — det sætter dem blot tilbage på listen.",
  /* 23 */ "Indlæs tilstand",
  /* 24 */ "Kun indbyggede kerner. Klik på en genvej, og tryk så på den ønskede tast eller knap; på controlleren tages to knapper ad gangen, for hver enkelt af dem bruges allerede i spillet.",
  /* 25 */ "Betjening",
  /* 26 */ "Betjening…",
  /* 27 */ "Seneste konsoller",
  /* 28 */ "Tilføj en anden emulator",
  /* 29 */ "Retninger / venstre stik",
  /* 30 */ "Spilmapper",
  /* 31 */ "Fravælg denne emulator",
  /* 32 */ "De hentes efter behov fra billedserveren i libretro-projektet. Uden flueben spørger biblioteket ikke længere netværket om noget.",
  /* 33 */ "Gemmepladser",
  /* 34 */ "Pladser…",
  /* 35 */ "Emulatorer",
  /* 36 */ "Fravalgte emulatorer",
  /* 37 */ "Eksterne emulatorer",
  /* 38 */ "Eksterne emulatorer…",
  /* 39 */ "Emulatorer…",
  /* 40 */ "Emulering",
  /* 41 */ "Tilbage til biblioteket under spil — to knapper ad gangen, for hver enkelt af dem bruges i spillet",
  /* 42 */ "Gem",
  /* 43 */ "Filendelser",
  /* 44 */ "Luk",
  /* 45 */ "Filer",
  /* 46 */ "Systemfiler du selv skal lægge ind",
  /* 47 */ "Galleri",
  /* 48 */ "Håndter mapper…",
  /* 49 */ "Grafik",
  /* 50 */ "Grafik…",
  /* 51 */ "Peg på den mappe, hvor dine spil ligger.",
  /* 52 */ "Installation",
  /* 53 */ "Installer det valgte",
  /* 54 */ "Installer emulatorer…",
  /* 55 */ "Fortolker",
  /* 56 */ "Du behøver ikke vide hvorhen: vis mappen, hvor det hele ligger og flyder — BIOS, nøgler, firmware, arkiver, undermapper med — så bærer EvaChi hver fil hen på rette plads, både til kernerne og til de selvstændige emulatorer. Det, ingen efterspørger, bliver liggende.",
  /* 57 */ "Omslag",
  /* 58 */ "Log",
  /* 59 */ "Log…",
  /* 60 */ "Sidste gang endte galt",
  /* 61 */ "Start spillet, bekræft",
  /* 62 */ "Sprog",
  /* 63 */ "Valget huskes fra gang til gang. Hvert tema er tjekket for læsbarhed: teksten har overalt kontrast nok til sin baggrund.",
  /* 64 */ "Behold den",
  /* 65 */ "Emulatorerne nedenfor er allerede sat op — argumenter og formater med. EvaChi leder efter dem på din disk; den installerer dem ikke.",
  /* 66 */ "Oprindelige tildelinger",
  /* 67 */ "Udjævning",
  /* 68 */ "Gør spillet til favorit, eller fjern det igen",
  /* 69 */ "Musik i den animerede menu",
  /* 70 */ "Navn",
  /* 71 */ "Åbn menulinjen",
  /* 72 */ "Åbn mappen",
  /* 73 */ "Åbn mappen…",
  /* 74 */ "Åbn et spil…",
  /* 75 */ "pr. billede",
  /* 76 */ "Kerneindstillinger",
  /* 77 */ "Kerneindstillinger…",
  /* 78 */ "Bevæg dig gennem biblioteket, vinduerne og menulinjen",
  /* 79 */ "Gennemse…",
  /* 80 */ "Pause",
  /* 81 */ "Fuld skærm",
  /* 82 */ "Til konsoller uden libretro-kerne. EvaChi starter programmet med spillet som argument: emulatoren går direkte i gang med spillet, uden om sin egen menu.",
  /* 83 */ "Tag et skærmbillede",
  /* 84 */ "Visning",
  /* 85 */ "Klar",
  /* 86 */ "Program",
  /* 87 */ "Nogle få lange akkorder og spredte toner, skabt undervejs frem for indspillet: stykket kommer aldrig forbi det samme sted to gange. Det stopper af sig selv, så snart et spil går i gang.",
  /* 88 */ "Ryd op i en mappe…",
  /* 89 */ "Omtildel…",
  /* 90 */ "Søg efter et spil…",
  /* 91 */ "Nulstil",
  /* 92 */ "Tilbage til biblioteket",
  /* 93 */ "Gå tilbage, luk",
  /* 94 */ "Hurtiggem",
  /* 95 */ "Gem tilstand",
  /* 96 */ "Shaders",
  /* 97 */ "Lyd",
  /* 98 */ "Start",
  /* 99 */ "Billedstørrelse",
  /* 100 */ "Temaer",
  /* 101 */ "Temaer…",
  /* 102 */ "Én fil pr. spil…",
  /* 103 */ "Et kort klik når du skifter spil, og et til når du starter det. Kun med controller: med mus og tastatur mærker man allerede sin egen bevægelse.",
  /* 104 */ "Hastighed",
  /* 105 */ "Se skærmbillederne…",
  /* 106 */ "Du kan nøjes med at installere nogle af dem — kun de konsoller, hvis emulator er installeret, dukker op i biblioteket.",
  /* 107 */ "{0} — indlæst",
  /* 108 */ "{0} — højreklik for at rydde",
  /* 109 */ "{0} — gjort til favorit",
  /* 110 */ "{0} — nulstillet",
  /* 111 */ "{0} — fjernet fra favoritter",
  /* 112 */ "{0} — henter…",
  /* 113 */ "{0}: mislykkedes, se loggen",
  /* 114 */ "{0} til rådighed",
  /* 115 */ "{0} gemt",
  /* 116 */ "{0} er en ekstern emulator: den startes, den huses ikke",
  /* 117 */ "{0} fps",
  /* 118 */ "{0} installeret",
  /* 119 */ "{0} installeret — {1}",
  /* 120 */ "{0} installeret og klar",
  /* 121 */ "{0} installeret, {1} mislykkedes — se loggen",
  /* 122 */ "{0} gendannet",
  /* 123 */ "{0} fjernet",
  /* 124 */ "{0} af {1}",
  /* 125 */ "{0} på disken, men ingen installeret kerne åbner dem.",
  /* 126 */ "hentes fra {0}, derefter »Gennemse…«",
  /* 127 */ "kan hentes",
  /* 128 */ "mangler, valgfri",
  /* 129 */ "Aktivér",
  /* 130 */ "Blødt",
  /* 131 */ "kunne ikke tilføjes — {0}",
  /* 132 */ "Tilpas",
  /* 133 */ "Rav",
  /* 134 */ "Skifer",
  /* 135 */ "stoppet — {0}",
  /* 136 */ "brat stop sidste gang — {0}",
  /* 137 */ "ingen",
  /* 138 */ "ingen kerner meldt tilbage, skønt {0} var kendt — forrige liste beholdt",
  /* 139 */ "ingen emulator",
  /* 140 */ "Ingen emulator installeret",
  /* 141 */ "Ingen spil genkendt",
  /* 142 */ "Ingen resultater",
  /* 143 */ "ingen",
  /* 144 */ "biblioteket kunne ikke læses — {0}",
  /* 145 */ "tilsluttet",
  /* 146 */ "skærmbillede",
  /* 147 */ "Skift omslag…",
  /* 148 */ "Skift…",
  /* 149 */ "Hver pixel bliver til ni",
  /* 150 */ "Hver pixel bliver til fire: skarpt og uden forvrængning",
  /* 151 */ "Hver pixel bliver til seksten — til store skærme",
  /* 152 */ "Indlæs",
  /* 153 */ "Vælg et omslag…",
  /* 154 */ "vælg først et spil i biblioteket",
  /* 155 */ "kerne: {0}",
  /* 156 */ "kerne ikke installeret",
  /* 157 */ "Installerede kerner",
  /* 158 */ "libretro-kerner",
  /* 159 */ "Høj kontrast",
  /* 160 */ "indbygget skal: {0}",
  /* 161 */ "ufuldstændig nedlukning — {0}",
  /* 162 */ "afsøgning: {0}",
  /* 163 */ "afsøgning afbrudt — {0}",
  /* 164 */ "Vælg selv programmet til {0}",
  /* 165 */ "mappe tilføjet: {0}",
  /* 166 */ "mappe åbnet: {0}",
  /* 167 */ "Standardmappe",
  /* 168 */ "Tilføjede mapper",
  /* 169 */ "Esc",
  /* 170 */ "Plads {0}",
  /* 171 */ "plads {0} — {1}",
  /* 172 */ "Emulator til denne mappe",
  /* 173 */ "eksterne emulatorer",
  /* 174 */ "i gang",
  /* 175 */ "på plads",
  /* 176 */ "kunne ikke gemmes — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi kan hente dem fra libretro-projektets officielle byggeserver. Vælg de konsoller, du er interesseret i.",
  /* 179 */ "EvaChi stoppede, mens »{0}« blev startet, med emulatoren {1}.",
  /* 180 */ "EvaChi stoppede, med emulatoren {0}.",
  /* 181 */ "external_systems → {0} emulatorer angivet",
  /* 182 */ "Favorit",
  /* 183 */ "Favoritter",
  /* 184 */ "systemfilerne kunne ikke læses — {0}",
  /* 185 */ "Piletaster",
  /* 186 */ "Game Boy",
  /* 187 */ "Gitter",
  /* 188 */ "der mangler {0} til installerede konsoller",
  /* 189 */ "installation færdig: {0}",
  /* 190 */ "Installerer…",
  /* 191 */ "installeret",
  /* 192 */ "installeret af EvaChi",
  /* 193 */ "Installer",
  /* 194 */ "fortolker: {0}",
  /* 195 */ "spørger de installerede kerner…",
  /* 196 */ "Start",
  /* 197 */ "Start det valgte spil",
  /* 198 */ "Lavendel",
  /* 199 */ "Konsollerne på række, spillene i søjle, en baggrund der bølger. Som på en stuekonsol.",
  /* 200 */ "Kanterne flyder sammen — tættere på et gammelt fjernsyn",
  /* 201 */ "Omslagene i stort format, gennemset med controlleren. Tænkt til sofaen.",
  /* 202 */ "Pixlerne bliver firkantede, som på den oprindelige maskine",
  /* 203 */ "controllertildelinger sat tilbage til de oprindelige",
  /* 204 */ "list_cores → {0} kerner meldt",
  /* 205 */ "Liste",
  /* 206 */ "kernelisten er ikke tilgængelig — {0}",
  /* 207 */ "emulatorlisten er ikke tilgængelig — {0}",
  /* 208 */ "Controller",
  /* 209 */ "controller: {0}",
  /* 210 */ "Controller: {0}",
  /* 211 */ "controller frakoblet",
  /* 212 */ "MANGLER",
  /* 213 */ "Mynte",
  /* 214 */ "Animeret menu",
  /* 215 */ "Opdater",
  /* 216 */ "Gør til favorit",
  /* 217 */ "fravalgt: {0} · {1}",
  /* 218 */ "mindre end et minut",
  /* 219 */ "Skarpt",
  /* 220 */ "navn, program og filendelser skal alle udfyldes",
  /* 221 */ "NEJ",
  /* 222 */ "ikke installeret på denne maskine",
  /* 223 */ "Rosa nat",
  /* 224 */ "Ocean",
  /* 225 */ "eller",
  /* 226 */ "ja",
  /* 227 */ "kunne ikke åbnes — {0}",
  /* 228 */ "webside: kun de indbyggede kerner er til rådighed, uden bibliotek",
  /* 229 */ "Papir",
  /* 230 */ "standard",
  /* 231 */ "Bevæg dig gennem gitteret og den animerede menu",
  /* 232 */ "fuld skærm afvist — {0}",
  /* 233 */ "tryk på den ønskede knap på controlleren",
  /* 234 */ "tryk på en tast…",
  /* 235 */ "oprydning: {0} · {1}",
  /* 236 */ "oprydning mislykkedes — {0}",
  /* 237 */ "søgningen efter emulatorer afbrudt — {0}",
  /* 238 */ "Luk et vindue",
  /* 239 */ "nulstilling mislykkedes — {0}",
  /* 240 */ "Fylder vinduet ud og bevarer forholdet",
  /* 241 */ "Fortsæt",
  /* 242 */ "Fortsæt fra denne gemning — højreklik for at rydde den",
  /* 243 */ "Gendan",
  /* 244 */ "gendannelse mislykkedes — {0}",
  /* 245 */ "Fjern",
  /* 246 */ "Fjern fra favoritter",
  /* 247 */ "Fjern omslaget",
  /* 248 */ "kunne ikke fjernes — {0}",
  /* 249 */ "intet at rydde op",
  /* 250 */ "intet i vejen",
  /* 251 */ "Intet passer på »{0}«.",
  /* 252 */ "Rosa og hvid",
  /* 253 */ "uden billede",
  /* 254 */ "Gem",
  /* 255 */ "Gem her",
  /* 256 */ "valget mislykkedes — {0}",
  /* 257 */ "Konsollens oprindelige størrelse, pixel for pixel",
  /* 258 */ "Afslut",
  /* 259 */ "lyst tema",
  /* 260 */ "mørkt tema",
  /* 261 */ "alt er installeret",
  /* 262 */ "fundet: {0}",
  /* 263 */ "Én sektion pr. konsol, stillet op som en tabel. Den tætteste, når man bruger mus.",
  /* 264 */ "tom",
  /* 265 */ "lægges her ligesom spillenes romsets: FinalBurn Neo leder kun i denne mappe",
  /* 266 */ "tilføjer konsollens velkomstskærm",
  /* 267 */ "maskinens opstarts-ROM",
  /* 268 */ "mange spil starter uden den; konsollens menu gør ikke",
  /* 269 */ "amerikansk BIOS",
  /* 270 */ "amerikansk og europæisk BIOS",
  /* 271 */ "europæisk BIOS",
  /* 272 */ "japansk BIOS",
  /* 273 */ "dekrypteringsnøgler; uden dem afvises en krypteret dump",
  /* 274 */ "mappen Machines fra blueMSX-distributionen, med Databases ved siden af",
  /* 275 */ "ditto",
  /* 276 */ "nødvendig til CD-spil, overflødig til HuCard",
  /* 277 */ "nødvendig til Mega-CD-spil, overflødig til kassetter",
  /* 278 */ "Kickstart 1.3; ellers falder PUAE tilbage på AROS, frit men mindre kompatibelt",
  /* 279 */ "Kickstart 3.1; nødvendig til AGA-spil, som A500 ikke kan køre",
  /* 280 */ "melonDS emulerer som standard BIOS'en; den ægte er mere tro",
  /* 281 */ "mGBA klarer sig uden; enkelte spil kræver den til deres velkomstskærm",
  /* 282 */ "konsollens firmware",
  /* 283 */ "maskinens firmware",
  /* 284 */ "Panasonic FZ-10-firmware; det er det navn, Opera bruger som standard",
  /* 285 */ "ændres af melonDS, som bevarer originalen som .bak",
  /* 286 */ "skrifttyper",
  /* 287 */ "konsollens indstillinger og dato",
  /* 288 */ "uden den kører kernen, men skærmen forbliver sort",
  /* 289 */ "konsollens tegntabel",
  /* 290 */ "amerikansk variant, til Sega CD-spil fra USA",
  /* 291 */ "japansk variant, til japanske Mega-CD-spil",
  /* 292 */ "skærmbilleder",
  /* 293 */ "skærmbilleder",
  /* 294 */ "skærmbillede",
  /* 295 */ "skærmbilleder",
  /* 296 */ "skærmbilleder",
  /* 297 */ "skærmbilleder",
  /* 298 */ "kerner",
  /* 299 */ "kerner",
  /* 300 */ "kerne",
  /* 301 */ "kerner",
  /* 302 */ "kerner",
  /* 303 */ "kerner",
  /* 304 */ "emulatorer",
  /* 305 */ "emulatorer",
  /* 306 */ "emulator",
  /* 307 */ "emulatorer",
  /* 308 */ "emulatorer",
  /* 309 */ "emulatorer",
  /* 310 */ "filer",
  /* 311 */ "filer",
  /* 312 */ "fil",
  /* 313 */ "filer",
  /* 314 */ "filer",
  /* 315 */ "filer",
  /* 316 */ "spil",
  /* 317 */ "spil",
  /* 318 */ "spil",
  /* 319 */ "spil",
  /* 320 */ "spil",
  /* 321 */ "spil",
  /* 322 */ "<code>{rom}</code> erstattes af spillets sti. Uden den lægges stien til sidst — og det er, hvad de fleste emulatorer forventer.",
  /* 323 */ "<strong>Uden for spillet klares alt med controlleren:</strong> retningerne fører dig gennem biblioteket, vinduerne og menulinjen; <strong>A</strong> bekræfter, <strong>B</strong> går tilbage, <strong>Start</strong> åbner menulinjen. Under spillet fører <strong>Select og Start sammen</strong> tilbage til biblioteket — to knapper ad gangen, for hver enkelt af dem bruges i spillet.",
  /* 324 */ "Ingen skærmbilleder. Tryk på <strong>F12</strong> under spillet, eller <strong>Select + Y</strong> på controlleren.",
  /* 325 */ "Hver konsol har brug for sin emulator. EvaChi henter dem fra libretro-projektets officielle byggeserver, <code>buildbot.libretro.com</code>, og installerer dem i sin egen mappe. Intet videredistribueres: det er de udgaver, forfatterne selv har udgivet.",
  /* 326 */ "Fire pladser pr. spil, gemt på disken. Pladsen med fed er den, <strong>F2</strong> og <strong>F4</strong> bruger — og <strong>Select + L1</strong> / <strong>Select + R1</strong> på controlleren. Højreklik på en plads for at rydde den.",
  /* 327 */ "En emulator kører i samme vindue som EvaChi: når den falder, tager den EvaChi med sig, uden et ord. At fravælge emulatoren lader den blive installeret, men den bliver ikke længere tilbudt. Du kan gendanne den når som helst under <strong>Filer → Emulatorer</strong>, nederst i vinduet.",
  /* 328 */ "Én fil pr. spil på disken <small> Et spil på CD kommer som et <code>.cue</code>-ark og lige så mange <code>.bin</code>-filer, som disken havde spor. Kun arket kan startes: sporene skjules, når det er der. Uden ark skjules intet. </small>",
  /* 329 */ "(tom) eller --fullscreen {rom}",
];
