/**
 * Allemand — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros mis en commentaire devant chaque ligne sont là pour qu'on puisse
 * le vérifier à l'œil.
 */

export const de: readonly string[] = [
  /* 1 */ "Mit dem Controller",
  /* 2 */ "A starten · X Favorit · Y zuschneiden · L1/R1 Konsolen · L2/R2 Buchstabe · B zurück",
  /* 3 */ "Über EvaChi",
  /* 4 */ "Über…",
  /* 5 */ "Was ein Röhrenfernseher mit dem Bild machte und was die Spiele von damals voraussetzten. Gilt nur für Kerne, die hier laufen: ein eigenständiger Emulator zeichnet sein Bild selbst.",
  /* 6 */ "Bibliothek aktualisieren",
  /* 7 */ "Ansicht",
  /* 8 */ "Cover der Spiele anzeigen",
  /* 9 */ "Hilfe",
  /* 10 */ "Spieleordner hinzufügen…",
  /* 11 */ "Ordner hinzufügen…",
  /* 12 */ "Drücken Sie einen Knopf am Controller: der zugehörige Befehl leuchtet auf. Um einen zu ändern, klicken Sie das Feld darunter an und drücken dann den gewünschten Knopf. Der Knopf wechselt dabei den Besitzer: zwei Befehle auf demselben Knopf sähen wie ein Defekt aus.",
  /* 13 */ "Argumente",
  /* 14 */ "Mit der Tastatur",
  /* 15 */ "Keine Spiele",
  /* 16 */ "Kein Controller erkannt.",
  /* 17 */ "Bibliothek",
  /* 18 */ "Auswahlgeräusche am Controller",
  /* 19 */ "Manche Konsolen starten nicht ohne ihre originale Firmware. EvaChi kann sie nicht mitliefern: Das ist urheberrechtlich geschützter Code, den man vom eigenen Gerät kopiert. Dafür sagt EvaChi, welche fehlt, unter welchem Namen, und wohin sie gehört.",
  /* 20 */ "Diese Konsolen haben keinen libretro-Core: Ihr Emulator ist ein eigenes Programm, das EvaChi bei sich installiert und direkt ins Spiel startet — ohne Umweg über dessen Menü. Spiele, Schlüssel und Systemdateien bleiben Ihre Sache.",
  /* 21 */ "Diese Einstellungen betreffen nur die internen Cores. Ein externer Emulator hat seine eigenen, und EvaChi mischt sich da nicht ein.",
  /* 22 */ "Diese werden nicht mehr angeboten: Sie haben auf die Abfrage nicht geantwortet, oder sie haben EvaChi zu Fall gebracht. Sie wiederherzustellen installiert sie nicht neu — es setzt sie nur wieder auf die Liste.",
  /* 23 */ "Zustand laden…",
  /* 24 */ "Nur interne Cores. Klicken Sie ein Kürzel an und drücken Sie dann die gewünschte Taste oder den gewünschten Knopf; am Controller nimmt man zwei Knöpfe zugleich, denn jeder einzelne wird schon vom Spiel gebraucht.",
  /* 25 */ "Steuerung",
  /* 26 */ "Steuerung…",
  /* 27 */ "Letzte Konsolen",
  /* 28 */ "Weiteren Emulator eintragen",
  /* 29 */ "Richtungen / linker Stick",
  /* 30 */ "Spieleordner",
  /* 31 */ "Diesen Emulator beiseitelegen",
  /* 32 */ "Sie kommen bei Bedarf vom Vorschaubild-Server des libretro-Projekts. Ohne Häkchen fragt die Bibliothek nichts mehr aus dem Netz ab.",
  /* 33 */ "Speicherplätze",
  /* 34 */ "Speicherplätze…",
  /* 35 */ "Emulatoren",
  /* 36 */ "Beiseitegelegte Emulatoren",
  /* 37 */ "Externe Emulatoren",
  /* 38 */ "Externe Emulatoren…",
  /* 39 */ "Emulatoren…",
  /* 40 */ "Emulation",
  /* 41 */ "Im laufenden Spiel zurück zur Bibliothek — zwei Knöpfe zugleich, denn jeder einzelne wird vom Spiel gebraucht",
  /* 42 */ "Speichern",
  /* 43 */ "Dateiendungen",
  /* 44 */ "Schließen",
  /* 45 */ "Datei",
  /* 46 */ "Selbst einzuspielende Systemdateien",
  /* 47 */ "Galerie",
  /* 48 */ "Ordner verwalten…",
  /* 49 */ "Grafik",
  /* 50 */ "Grafik…",
  /* 51 */ "Geben Sie den Ordner an, in dem Ihre Spiele liegen.",
  /* 52 */ "Installation",
  /* 53 */ "Auswahl installieren",
  /* 54 */ "Emulatoren installieren…",
  /* 55 */ "Interpreter",
  /* 56 */ "Sie müssen nicht wissen, wohin: Zeigen Sie einfach den Ordner, in dem alles herumliegt — BIOS, Schlüssel, Firmware, Archive, Unterordner inbegriffen — und EvaChi trägt jede Datei an den richtigen Ort, für die Cores wie für die eigenständigen Emulatoren. Was niemand verlangt, bleibt liegen.",
  /* 57 */ "Cover",
  /* 58 */ "Protokoll",
  /* 59 */ "Protokoll…",
  /* 60 */ "Das letzte Mal ging es schief",
  /* 61 */ "Spiel starten, bestätigen",
  /* 62 */ "Sprache",
  /* 63 */ "Die Wahl bleibt von einem Start zum nächsten erhalten. Jedes wurde auf Lesbarkeit geprüft: Der Text behält überall genug Kontrast zu seinem Hintergrund.",
  /* 64 */ "Behalten",
  /* 65 */ "Die Emulatoren unten sind bereits eingerichtet — samt Argumenten und Formaten. EvaChi sucht sie auf Ihrer Festplatte; installieren tut es sie nicht.",
  /* 66 */ "Standardbelegung",
  /* 67 */ "Glättung",
  /* 68 */ "Das Spiel zu den Favoriten nehmen oder daraus entfernen",
  /* 69 */ "Musik in den bewegten Menüs",
  /* 70 */ "Name",
  /* 71 */ "Menüleiste öffnen",
  /* 72 */ "Ordner öffnen",
  /* 73 */ "Ordner öffnen…",
  /* 74 */ "Spiel öffnen…",
  /* 75 */ "pro Bild",
  /* 76 */ "Core-Einstellungen",
  /* 77 */ "Core-Einstellungen…",
  /* 78 */ "Durch Bibliothek, Fenster und Menüleiste navigieren",
  /* 79 */ "Durchsuchen…",
  /* 80 */ "Pause",
  /* 81 */ "Vollbild",
  /* 82 */ "Für Konsolen ohne libretro-Core. EvaChi ruft das Programm mit dem Spiel als Argument auf: Der Emulator startet direkt in der Partie, ohne Umweg über sein eigenes Menü.",
  /* 83 */ "Screenshot aufnehmen",
  /* 84 */ "Darstellung",
  /* 85 */ "Bereit",
  /* 86 */ "Programm",
  /* 87 */ "Ein paar gehaltene Akkorde und vereinzelte Töne, im Augenblick erzeugt statt aufgenommen: Das Stück kommt nie zweimal an dieselbe Stelle. Sobald ein Spiel startet, hört es von selbst auf.",
  /* 88 */ "Einen Ordner einräumen…",
  /* 89 */ "Leeren",
  /* 90 */ "Spiel suchen…",
  /* 91 */ "Zurücksetzen",
  /* 92 */ "Zurück zur Bibliothek",
  /* 93 */ "Zurückgehen, schließen",
  /* 94 */ "Schnellspeichern",
  /* 95 */ "Zustand speichern…",
  /* 96 */ "Shader",
  /* 97 */ "Ton",
  /* 98 */ "Start",
  /* 99 */ "Bildgröße",
  /* 100 */ "Designs",
  /* 101 */ "Designs…",
  /* 102 */ "Nur eine Datei…",
  /* 103 */ "Ein kurzer Klick beim Wechsel von Spiel zu Spiel, ein zweiter beim Starten. Nur am Controller: Mit Maus und Tastatur spürt man die Geste ohnehin.",
  /* 104 */ "Geschwindigkeit",
  /* 105 */ "Screenshots ansehen…",
  /* 106 */ "Sie können auch nur einen Teil installieren — in der Bibliothek erscheinen nur die Konsolen, deren Emulator installiert ist.",
  /* 107 */ "{0} — geladen",
  /* 108 */ "{0} — Rechtsklick zum Leeren",
  /* 109 */ "{0} — als Favorit gesetzt",
  /* 110 */ "{0} — zurückgesetzt",
  /* 111 */ "{0} — aus den Favoriten entfernt",
  /* 112 */ "{0} — wird heruntergeladen…",
  /* 113 */ "{0}: fehlgeschlagen, siehe Protokoll",
  /* 114 */ "{0} verfügbar",
  /* 115 */ "{0} gespeichert",
  /* 116 */ "{0} ist ein externer Emulator: er wird gestartet, nicht eingebettet",
  /* 117 */ "{0} Bilder/s",
  /* 118 */ "{0} installiert",
  /* 119 */ "{0} installiert — {1}",
  /* 120 */ "{0} installiert und bereit",
  /* 121 */ "{0} installiert, {1} fehlgeschlagen — siehe Protokoll",
  /* 122 */ "{0} wiederhergestellt",
  /* 123 */ "{0} entfernt",
  /* 124 */ "{0} von {1}",
  /* 125 */ "{0} auf der Festplatte, aber kein installierter Core öffnet sie.",
  /* 126 */ "bei {0} zu holen, dann „Durchsuchen…“",
  /* 127 */ "zum Herunterladen",
  /* 128 */ "fehlt, optional",
  /* 129 */ "Aktivieren",
  /* 130 */ "Weich",
  /* 131 */ "Hinzufügen nicht möglich — {0}",
  /* 132 */ "Einpassen",
  /* 133 */ "Bernstein",
  /* 134 */ "Schiefer",
  /* 135 */ "beendet — {0}",
  /* 136 */ "letztes Mal abgestürzt — {0}",
  /* 137 */ "keiner",
  /* 138 */ "kein Core zurückgemeldet, obwohl {0} bekannt waren — vorherige Liste behalten",
  /* 139 */ "kein Emulator",
  /* 140 */ "Kein Emulator installiert",
  /* 141 */ "Kein Spiel erkannt",
  /* 142 */ "Kein Treffer",
  /* 143 */ "keine",
  /* 144 */ "Bibliothek nicht lesbar — {0}",
  /* 145 */ "angeschlossen",
  /* 146 */ "Screenshot",
  /* 147 */ "Cover ändern…",
  /* 148 */ "Ändern…",
  /* 149 */ "Jedes Pixel auf neun",
  /* 150 */ "Jedes Pixel auf vier: scharf, ohne Verzerrung",
  /* 151 */ "Jedes Pixel auf sechzehn — für große Bildschirme",
  /* 152 */ "Laden",
  /* 153 */ "Cover auswählen…",
  /* 154 */ "wählen Sie zuerst ein Spiel in der Bibliothek",
  /* 155 */ "Core: {0}",
  /* 156 */ "Core nicht installiert",
  /* 157 */ "Installierte Cores",
  /* 158 */ "libretro-Cores",
  /* 159 */ "Hoher Kontrast",
  /* 160 */ "native Hülle: {0}",
  /* 161 */ "Entladen unvollständig — {0}",
  /* 162 */ "Suche: {0}",
  /* 163 */ "Suche abgebrochen — {0}",
  /* 164 */ "Das Programm für {0} selbst angeben",
  /* 165 */ "Ordner hinzugefügt: {0}",
  /* 166 */ "Ordner geöffnet: {0}",
  /* 167 */ "Standardordner",
  /* 168 */ "Hinzugefügte Ordner",
  /* 169 */ "Esc",
  /* 170 */ "Platz {0}",
  /* 171 */ "Platz {0} — {1}",
  /* 172 */ "Emulator für diesen Ordner",
  /* 173 */ "externe Emulatoren",
  /* 174 */ "läuft",
  /* 175 */ "vorhanden",
  /* 176 */ "Speichern nicht möglich — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi kann sie vom offiziellen Buildserver von libretro herunterladen. Wählen Sie die Konsolen aus, die Sie interessieren.",
  /* 179 */ "EvaChi ist beim Starten von „{0}“ abgestürzt, mit dem Emulator {1}.",
  /* 180 */ "EvaChi ist abgestürzt, mit dem Emulator {0}.",
  /* 181 */ "external_systems → {0} Emulatoren eingetragen",
  /* 182 */ "Favorit",
  /* 183 */ "Favoriten",
  /* 184 */ "Systemdateien nicht lesbar — {0}",
  /* 185 */ "Pfeiltasten",
  /* 186 */ "Game Boy",
  /* 187 */ "Raster",
  /* 188 */ "installierten Konsolen fehlen {0}",
  /* 189 */ "Installation fertig: {0}",
  /* 190 */ "Installation…",
  /* 191 */ "installiert",
  /* 192 */ "von EvaChi installiert",
  /* 193 */ "Installieren",
  /* 194 */ "Interpreter: {0}",
  /* 195 */ "installierte Cores werden abgefragt…",
  /* 196 */ "Starten",
  /* 197 */ "Das gewählte Spiel starten",
  /* 198 */ "Lavendel",
  /* 199 */ "Die Konsolen in der Reihe, die Spiele in der Spalte, ein Hintergrund, der wogt. Wie bei einer Wohnzimmerkonsole.",
  /* 200 */ "Die Kanten verschwimmen — näher an einem alten Fernseher",
  /* 201 */ "Die Cover groß, mit dem Controller durchblättert. Fürs Sofa gedacht.",
  /* 202 */ "Die Pixel bleiben eckig, wie auf dem Gerät von damals",
  /* 203 */ "Controller-Belegung auf Standard zurückgesetzt",
  /* 204 */ "list_cores → {0} Cores gemeldet",
  /* 205 */ "Liste",
  /* 206 */ "Liste der Cores nicht verfügbar — {0}",
  /* 207 */ "Liste der Emulatoren nicht verfügbar — {0}",
  /* 208 */ "Controller",
  /* 209 */ "Controller: {0}",
  /* 210 */ "Controller: {0}",
  /* 211 */ "Controller abgezogen",
  /* 212 */ "FEHLT",
  /* 213 */ "Minze",
  /* 214 */ "Bewegtes Menü",
  /* 215 */ "Aktualisieren",
  /* 216 */ "Zu den Favoriten",
  /* 217 */ "beiseitegelegt: {0} · {1}",
  /* 218 */ "weniger als eine Minute",
  /* 219 */ "Scharf",
  /* 220 */ "Name, Programm und Dateiendungen werden alle drei gebraucht",
  /* 221 */ "NEIN",
  /* 222 */ "auf diesem Rechner nicht installiert",
  /* 223 */ "Rosa Nacht",
  /* 224 */ "Ozean",
  /* 225 */ "oder",
  /* 226 */ "ja",
  /* 227 */ "Öffnen nicht möglich — {0}",
  /* 228 */ "Webseite: nur die internen Cores sind verfügbar, ohne Bibliothek",
  /* 229 */ "Papier",
  /* 230 */ "Standard",
  /* 231 */ "Durch das Raster und die bewegten Menüs navigieren",
  /* 232 */ "Vollbild abgelehnt — {0}",
  /* 233 */ "drücken Sie den gewünschten Knopf am Controller",
  /* 234 */ "drücken Sie eine Taste…",
  /* 235 */ "Einräumen: {0} · {1}",
  /* 236 */ "Einräumen nicht möglich — {0}",
  /* 237 */ "Suche nach Emulatoren abgebrochen — {0}",
  /* 238 */ "Ein Fenster schließen",
  /* 239 */ "Zurücksetzen nicht möglich — {0}",
  /* 240 */ "Füllt das Fenster und behält die Proportionen",
  /* 241 */ "Fortsetzen",
  /* 242 */ "Ersetzen",
  /* 243 */ "Wiederherstellen",
  /* 244 */ "Wiederherstellen nicht möglich — {0}",
  /* 245 */ "Entfernen",
  /* 246 */ "Aus den Favoriten",
  /* 247 */ "Cover entfernen",
  /* 248 */ "Entfernen nicht möglich — {0}",
  /* 249 */ "nichts einzuräumen",
  /* 250 */ "nichts blockiert",
  /* 251 */ "Nichts passt zu „{0}“.",
  /* 252 */ "Rosa und Weiß",
  /* 253 */ "ohne Bild",
  /* 254 */ "Speichern",
  /* 255 */ "Hier speichern",
  /* 256 */ "Auswahl nicht möglich — {0}",
  /* 257 */ "Originalgröße der Konsole, pixelgenau",
  /* 258 */ "Wegwerfen",
  /* 259 */ "helles Design",
  /* 260 */ "dunkles Design",
  /* 261 */ "alles ist installiert",
  /* 262 */ "gefunden: {0}",
  /* 263 */ "Ein Abschnitt je Konsole, als Tabelle. Mit der Maus am dichtesten.",
  /* 264 */ "leer",
  /* 265 */ "hier ablegen, wie die Romsets der Spiele: FinalBurn Neo sucht nur in diesem Ordner",
  /* 266 */ "fügt den Startbildschirm der Konsole hinzu",
  /* 267 */ "Startroutine des Geräts",
  /* 268 */ "viele Spiele starten auch ohne; das Menü der Konsole nicht",
  /* 269 */ "US-BIOS",
  /* 270 */ "US- und Europa-BIOS",
  /* 271 */ "Europa-BIOS",
  /* 272 */ "Japan-BIOS",
  /* 273 */ "Schlüssel zum Entschlüsseln; ohne sie wird ein verschlüsselter Dump abgelehnt",
  /* 274 */ "Machines-Ordner der blueMSX-Distribution, mit Databases daneben",
  /* 275 */ "ebenso",
  /* 276 */ "unerlässlich für CD-Spiele, unnötig für HuCard-Karten",
  /* 277 */ "unerlässlich für Mega-CD-Spiele, unnötig für Module",
  /* 278 */ "Kickstart 1.3; sonst weicht PUAE auf AROS aus, frei, aber weniger verträglich",
  /* 279 */ "Kickstart 3.1; nötig für AGA-Spiele, die der A500 nicht ausführen kann",
  /* 280 */ "melonDS emuliert das BIOS von Haus aus; das echte ist originalgetreuer",
  /* 281 */ "mGBA kommt ohne aus; einige Spiele brauchen es für ihren Startbildschirm",
  /* 282 */ "Firmware der Konsole",
  /* 283 */ "Firmware des Geräts",
  /* 284 */ "Firmware der Panasonic FZ-10; unter diesem Namen sucht Opera von Haus aus",
  /* 285 */ "wird von melonDS verändert, das Original bleibt als .bak erhalten",
  /* 286 */ "Schriftarten",
  /* 287 */ "Einstellungen und Datum der Konsole",
  /* 288 */ "ohne sie läuft der Core, aber der Bildschirm bleibt schwarz",
  /* 289 */ "Zeichentabelle der Konsole",
  /* 290 */ "US-Variante, für Sega-CD-Spiele aus den Vereinigten Staaten",
  /* 291 */ "japanische Variante, für japanische Mega-CD-Spiele",
  /* 292 */ "Screenshots",
  /* 293 */ "Screenshots",
  /* 294 */ "Screenshot",
  /* 295 */ "Screenshots",
  /* 296 */ "Screenshots",
  /* 297 */ "Screenshots",
  /* 298 */ "Cores",
  /* 299 */ "Cores",
  /* 300 */ "Core",
  /* 301 */ "Cores",
  /* 302 */ "Cores",
  /* 303 */ "Cores",
  /* 304 */ "Emulatoren",
  /* 305 */ "Emulatoren",
  /* 306 */ "Emulator",
  /* 307 */ "Emulatoren",
  /* 308 */ "Emulatoren",
  /* 309 */ "Emulatoren",
  /* 310 */ "Dateien",
  /* 311 */ "Dateien",
  /* 312 */ "Datei",
  /* 313 */ "Dateien",
  /* 314 */ "Dateien",
  /* 315 */ "Dateien",
  /* 316 */ "Spiele",
  /* 317 */ "Spiele",
  /* 318 */ "Spiel",
  /* 319 */ "Spiele",
  /* 320 */ "Spiele",
  /* 321 */ "Spiele",
  /* 322 */ "<code>{rom}</code> wird durch den Pfad des Spiels ersetzt. Fehlt es, wird der Pfad hinten angehängt — so erwarten es die meisten Emulatoren.",
  /* 323 */ "<strong>Außerhalb des Spiels geht alles mit dem Controller:</strong> Die Richtungen führen durch die Bibliothek, die Fenster und die Menüleiste; <strong>A</strong> bestätigt, <strong>B</strong> geht zurück, <strong>Start</strong> öffnet die Menüleiste. Im laufenden Spiel bringen <strong>Select und Start zusammen</strong> zurück zur Bibliothek — zwei Knöpfe zugleich, denn jeder einzelne wird vom Spiel gebraucht.",
  /* 324 */ "Keine Screenshots. Drücken Sie im laufenden Spiel <strong>F12</strong>, oder <strong>Select + Y</strong> am Controller.",
  /* 325 */ "Jede Konsole braucht ihren Emulator. EvaChi holt sie vom offiziellen Buildserver des libretro-Projekts, <code>buildbot.libretro.com</code>, und installiert sie in ihrem eigenen Ordner. Nichts wird weiterverbreitet: Es sind die Fassungen, die ihre Urheber selbst veröffentlicht haben.",
  /* 326 */ "Vier Plätze je Spiel, auf der Festplatte behalten. Jede Handlung steht unter dem Platz geschrieben, und Ersetzen oder Leeren fragt vorher nach. <strong>F2</strong> und <strong>F4</strong> — und <strong>Select + L1</strong> / <strong>Select + R1</strong> am Controller — gehen ohne Nachfrage direkt auf den fett gesetzten Platz.",
  /* 327 */ "Jeder Emulator läuft in seinem eigenen Prozess: Wenn er fällt, sieht EvaChi es und kehrt zur Bibliothek zurück. Das laufende Spiel ist verloren, und der Spielstand ist vielleicht nicht geschrieben worden. Diesen Emulator beiseitezulegen lässt ihn installiert, bietet ihn aber nicht mehr an. Sie können ihn jederzeit unter <strong>Datei → Emulatoren</strong> am unteren Rand des Fensters wiederherstellen.",
  /* 328 */ "Nur eine Datei je Spiel auf der Festplatte <small> Ein Spiel auf CD kommt als <code>.cue</code>-Blatt und als so viele <code>.bin</code>-Dateien, wie die CD Spuren hatte. Nur das Blatt startet: Ist es da, werden die Spuren ausgeblendet. Ohne Blatt wird nichts ausgeblendet. </small>",
  /* 329 */ "(leer) oder --fullscreen {rom}",
  /* 330 */ "Hundert Prozent ist die Geschwindigkeit der Konsole selbst. Darunter läuft das Spiel langsamer, darüber rast es — und der Ton geht mit, tiefer oder höher. Am Controller springen links und rechts von einer Stufe zur nächsten. Nur bei internen Cores: ein externer Emulator behält seine eigene Geschwindigkeit.",
  /* 331 */ "Fünf Konsolen auf einmal",
  /* 332 */ "Steuerkreuz",
  /* 333 */ "Zum nächsten Anfangsbuchstaben",
  /* 334 */ "In den animierten Menüs fünf Spiele auf einmal",
  /* 335 */ "Spielgeschwindigkeit",
  /* 336 */ "Abbrechen",
  /* 337 */ "Ziehen Sie den Rahmen, oder fassen Sie eine Ecke. Mit den Pfeiltasten verschieben Sie ihn, mit Umschalt wird er größer oder kleiner. Ragt er über das Bild hinaus, kommen ringsum durchsichtige Streifen dazu – so zoomen Sie ein zu eng sitzendes Cover heraus. Am Gamepad verschieben die Richtungstasten, und die Schultertasten stellen die Größe ein.",
  /* 338 */ "Zuschneiden",
  /* 339 */ "Cover zuschneiden",
  /* 340 */ "Ganzes Bild",
  /* 341 */ "{0} — Cover zugeschnitten",
  /* 342 */ "{0} — kein Cover zum Zuschneiden",
  /* 343 */ "Cover nicht lesbar — {0}",
  /* 344 */ "Zuschneiden nicht möglich — {0}",
  /* 345 */ "Cover zuschneiden…",
  /* 346 */ "Schnellvorlauf, solange beide Sticks gedrückt bleiben",
  /* 347 */ "{0} beiseitegelegt",
  /* 348 */ "Der Emulator {0} ist während „{1}“ abgestürzt.",
  /* 349 */ "Der Emulator {0} ist abgestürzt.",
  /* 350 */ "Der Emulator ist abgestürzt",
  /* 351 */ "Beiseitelegen nicht möglich — {0}",
  /* 352 */ "hier ablegen: {0}",
  /* 353 */ "es fehlt eine Systemdatei: {0}",
  /* 354 */ "Danksagungen",
  /* 355 */ "Nicht kommerzielle Lizenz, zu beachten, bevor jemand darauf aufbaut: {0}.",
  /* 356 */ "EvaChi schreibt keinen einzigen Emulator: Sie beherbergt sie. Jeder ist ein eigenständiges freies Projekt, von anderen geschrieben, das EvaChi bei Bedarf von seinen Urhebern holt — keine Zeile ihres Codes ist hier abgeschrieben, kein Byte wird weiterverbreitet. Die Namen und die Lizenzen weiter unten sind die, die jedes Projekt selbst angibt.",
  /* 357 */ "Karussell",
  /* 358 */ "Die Cover von vorn, die Konsolen gestapelt, aufsteigender Staub. Wie eine Auslage.",
  /* 359 */ "Wie die Oberfläche",
  /* 360 */ "Sprache der Oberfläche",
  /* 361 */ "Sprache der Spiele",
  /* 362 */ "Sprache der Spiele: {0}. Sie gilt ab dem nächsten Start.",
  /* 363 */ "Zurück",
  /* 364 */ "Suchen",
  /* 365 */ "Dateien suchen",
  /* 366 */ "Einen Wert suchen",
  /* 367 */ "Anders",
  /* 368 */ "Gleich",
  /* 369 */ "Breite",
  /* 370 */ "Das libretro-Projekt veröffentlicht Cheat-Dateien, eine pro Spiel. EvaChi behält nur jene, die genau zu Ihrem Spiel passen — gleicher Titel, gleiche Region, gleiche Revision — und schlägt lieber nichts vor als etwas Ungefähres: Codes für eine andere Fassung schreiben nicht ein wenig daneben, sie schreiben woandershin.",
  /* 371 */ "Die Cheats",
  /* 372 */ "Weniger",
  /* 373 */ "Cheat-Panel",
  /* 374 */ "Mehr",
  /* 375 */ "Von vorn",
  /* 376 */ "Cheats",
  /* 377 */ "Cheats…",
  /* 378 */ "Wert",
  /* 379 */ "Gleich",
  /* 380 */ "{0} mögliche Adressen",
  /* 381 */ "{0} Dateien abgelegt, {1} entfernt",
  /* 382 */ "{0} von {1} Spielen haben eine Datei",
  /* 383 */ "{0} Byte Speicher",
  /* 384 */ "{0} Werte verworfen: außerhalb des Speichers dieses Spiels",
  /* 385 */ "Keine Datei für dieses Spiel. Das Panel „Cheats…“ im Menü Emulation sucht eine; andernfalls funktioniert die Wertsuche bei jedem Spiel.",
  /* 386 */ "Eingefroren",
  /* 387 */ "Einfrieren",
  /* 388 */ "Spielen Sie kurz weiter und sagen Sie dann, was der Wert getan hat.",
  /* 389 */ "Der Spielstand wurde vor dem ersten Cheat beiseitegelegt.",
  /* 390 */ "Suche läuft…",
  /* 391 */ "Was in « drop u'r rom » abgelegt wird, geht zu der Konsole, die seine Dateiendung nennt. Teilen sich mehrere Konsolen dieselbe — Abbilder von Datenträgern —, fragt EvaChi lieber nach, statt zu raten.",
  /* 392 */ "Bestätigung",
  /* 393 */ "Spielstand löschen…",
  /* 394 */ "Dehnung",
  /* 395 */ "Das Spiel hält seine Zählstände im Speicher, ohne zu sagen wo. Man findet sie durch Ausschluss: Sie sagen, was die angezeigte Zahl getan hat, und EvaChi verwirft alle Adressen, die es nicht ebenso getan haben.",
  /* 396 */ "Ja",
  /* 397 */ "Wenige Konsolen haben die Maße eines heutigen Bildschirms, daher die schwarzen Balken an den Seiten. Bei null behält das Bild seine Maße; bei hundert füllt es das Fenster, und sei es gedehnt.",
  /* 398 */ "Spiele einräumen",
  /* 399 */ "Einräumen",
  /* 400 */ "Abgelegte Spiele einräumen…",
  /* 401 */ "Sie sehen 47 Leben: Tippen Sie 47 in « Wert » und drücken Sie « Suchen ». Verlieren Sie eines, tippen Sie 46 und drücken Sie « Gleich ». Steht die Zahl nirgends geschrieben, lassen Sie « Wert » leer und sagen zwischen zwei Spielmomenten nur « Mehr », « Weniger », « Anders » oder « Gleich ». « Einfrieren » hält den gefundenen Wert danach fest. « Breite » ist die Größe der Zahl: 1 bis 255, 2 darüber, 4 für große Zähler.",
  /* 402 */ "{0} eingeräumt",
  /* 403 */ "kein Spielstand zum Löschen",
  /* 404 */ "Knöpfe",
  /* 405 */ "Schon in der Bibliothek: {0}",
  /* 406 */ "Den Spielstand von {0} löschen und von vorn beginnen? Die laufende Partie wird beendet, und was das Spiel notiert hatte, geht verloren.",
  /* 407 */ "Schultertasten",
  /* 408 */ "Beide behalten",
  /* 409 */ "Im Ablageordner lassen",
  /* 410 */ "Der Ablageordner ist leer.",
  /* 411 */ "Platz {0} ersetzen? Was dort liegt, geht verloren.",
  /* 412 */ "Spielstand gelöscht — {0}",
  /* 413 */ "System",
  /* 414 */ "Platz {0} leeren? Was dort liegt, geht verloren.",
  /* 415 */ "Die Totzone ist der Teil des Sticks, in dem er noch als in Ruhe gilt. Zu klein, und die Figur läuft von allein los, während der Controller auf dem Tisch liegt; zu groß, und die kleinen Bewegungen gehen verloren. Manche Spiele verlangen, die Konsole zu schütteln: wenn der Controller das nicht spüren kann, machen die beiden Knöpfe unten es dem Spiel glauben.",
  /* 416 */ "Der Stick",
  /* 417 */ "Eigenständige Emulatoren haben ihre eigenen Tasten, in ihren eigenen Dateien. Was Sie hier ändern, wird sofort dorthin übertragen — für jene, deren Format wir aus erster Hand kennen: PCSX2, PPSSPP und Dolphin. Die alte Einstellung wird beim ersten Mal beiseitegelegt, unter demselben Namen mit « .avant-evachi » dahinter.",
  /* 418 */ "An externe Emulatoren übertragen",
  /* 419 */ "Totzone",
  /* 420 */ "Vorführung",
  /* 421 */ "Ton",
  /* 422 */ "noch kein externer Emulator hat seine Einstellungen geschrieben",
  /* 423 */ "Glut",
  /* 424 */ "Asche",
  /* 425 */ "Kirsche",
  /* 426 */ "Koralle",
  /* 427 */ "Kartenblatt",
  /* 428 */ "Wald",
  /* 429 */ "Raureif",
  /* 430 */ "die externen Emulatoren hatten diese Tasten bereits",
  /* 431 */ "Mitternacht",
  /* 432 */ "Moos",
  /* 433 */ "Neon",
  /* 434 */ "Pflaume",
  /* 435 */ "Sand",
  /* 436 */ "Schütteln",
  /* 437 */ "Sepia",
  /* 438 */ "Tasten übertragen: {0}",
  /* 439 */ "Türkis",
  /* 440 */ "Die Cover wie ein Kartenblatt aufgefächert. Das Handgelenk dreht sich, und die gelesene Karte richtet sich auf.",
  /* 441 */ "Ein dunkler Saal, ein Lichtkegel voller Staub und das Spiel groß projiziert. Der Rest wartet im Magazin.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Aprikose",
  /* 444 */ "Heidekraut",
  /* 445 */ "Karamell",
  /* 446 */ "Kupfer",
  /* 447 */ "Tinte",
  /* 448 */ "Famicom",
  /* 449 */ "Jade",
  /* 450 */ "Heidelbeere",
  /* 451 */ "Gewitter",
  /* 452 */ "Perle",
  /* 453 */ "Pistazie",
  /* 454 */ "Keiner",
  /* 455 */ "Zeilen",
  /* 456 */ "Jeder Bildpunkt in drei Schlitzen: rot, grün und blau",
  /* 457 */ "Das Bild des Kerns, Punkt für Punkt",
  /* 458 */ "Das gewölbte Glas, die Zeilen, die Schlitze und die dunklen Ränder",
  /* 459 */ "Schlitzmaske",
  /* 460 */ "Bildröhre",
  /* 461 */ "Jede zweite Zeile abgedunkelt, wie auf einem Fernseher",
  /* 462 */ "Öffnet den Emulator in seinem eigenen Fenster, ohne Spiel",
  /* 463 */ "Öffnen",
];
