/**
 * L'anglais — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros mis en commentaire devant chaque phrase sont là pour qu'on puisse
 * le vérifier à l'œil.
 */

export const en: readonly string[] = [
  /* 1 */ "On the gamepad",
  /* 2 */ "A play · X favorite · Y crop · L1/R1 consoles · L2/R2 letter · B back",
  /* 3 */ "About EvaChi",
  /* 4 */ "About…",
  /* 5 */ "What a cathode-ray television did to the picture, and that the games of the day took for granted. Only for cores played here: a standalone emulator draws its own picture.",
  /* 6 */ "Refresh the library",
  /* 7 */ "View",
  /* 8 */ "Show game cover art",
  /* 9 */ "Help",
  /* 10 */ "Add a game folder…",
  /* 11 */ "Add a folder…",
  /* 12 */ "Press a button on the gamepad: the matching command lights up. To change one, click the box underneath, then press the button you want. The button then changes hands: two commands on the same button would look like a fault.",
  /* 13 */ "Arguments",
  /* 14 */ "On the keyboard",
  /* 15 */ "No games",
  /* 16 */ "No gamepad detected.",
  /* 17 */ "Library",
  /* 18 */ "Selection sounds on the gamepad",
  /* 19 */ "Some consoles won't start without their original firmware. EvaChi can't supply it: it is copyrighted code, copied from the machine you own. What it can do is tell you which one is missing, under what name, and where to put it.",
  /* 20 */ "These consoles have no libretro core: their emulator is a separate program, which EvaChi installs in its own folder and starts straight into the game — without going through the emulator's own menu. The games, the keys and the system files are still up to you.",
  /* 21 */ "These settings only touch the built-in cores. An external emulator has its own, and EvaChi leaves them be.",
  /* 22 */ "These are no longer offered: they didn't answer when asked, or they brought EvaChi down with them. Restoring one doesn't reinstall it — it simply puts it back in the list.",
  /* 23 */ "Load state…",
  /* 24 */ "Built-in cores only. Click a shortcut, then press the key or button you want; on the gamepad it takes two buttons at once, since each one is already busy with the game.",
  /* 25 */ "Controls",
  /* 26 */ "Controls…",
  /* 27 */ "Recent consoles",
  /* 28 */ "Add another emulator",
  /* 29 */ "D-pad / left stick",
  /* 30 */ "Game folders",
  /* 31 */ "Set this emulator aside",
  /* 32 */ "They come from the libretro project's thumbnail server, on demand. Unchecked, the library asks nothing of the network.",
  /* 33 */ "Save slots",
  /* 34 */ "Save slots…",
  /* 35 */ "Emulators",
  /* 36 */ "Emulators set aside",
  /* 37 */ "External emulators",
  /* 38 */ "External emulators…",
  /* 39 */ "Emulators…",
  /* 40 */ "Emulation",
  /* 41 */ "During a game, come back to the library — two buttons at once, since each one is busy with the game",
  /* 42 */ "Save",
  /* 43 */ "Extensions",
  /* 44 */ "Close",
  /* 45 */ "File",
  /* 46 */ "System files to install yourself",
  /* 47 */ "Gallery",
  /* 48 */ "Manage folders…",
  /* 49 */ "Graphics",
  /* 50 */ "Graphics…",
  /* 51 */ "Point to the folder where your games live.",
  /* 52 */ "Installation",
  /* 53 */ "Install the selection",
  /* 54 */ "Install emulators…",
  /* 55 */ "Interpreter",
  /* 56 */ "No need to know where: show EvaChi the folder where it all sits — BIOS, keys, firmware, archives, subfolders included — and it carries each file to the right place, for the cores as well as the standalone emulators. Whatever nobody asks for stays where it is.",
  /* 57 */ "Cover art",
  /* 58 */ "Log",
  /* 59 */ "Log…",
  /* 60 */ "Last time ended badly",
  /* 61 */ "Launch the game, confirm",
  /* 62 */ "Language",
  /* 63 */ "Your choice is kept from one launch to the next. Each one has been checked for legibility: the text keeps enough contrast against its background everywhere.",
  /* 64 */ "Keep it",
  /* 65 */ "The emulators below are already set up — arguments and formats included. EvaChi looks for them on your disk; it doesn't install them.",
  /* 66 */ "Default bindings",
  /* 67 */ "Smoothing",
  /* 68 */ "Add the game to favorites, or take it out",
  /* 69 */ "Music in the animated menus",
  /* 70 */ "Name",
  /* 71 */ "Open the menu bar",
  /* 72 */ "Open the folder",
  /* 73 */ "Open the folder…",
  /* 74 */ "Open a game…",
  /* 75 */ "per frame",
  /* 76 */ "Core settings",
  /* 77 */ "Core settings…",
  /* 78 */ "Move through the library, the windows and the menu bar",
  /* 79 */ "Browse…",
  /* 80 */ "Pause",
  /* 81 */ "Fullscreen",
  /* 82 */ "For consoles with no libretro core. EvaChi runs the program with the game as an argument: the emulator starts straight into the game, without going through its own menu.",
  /* 83 */ "Take a screenshot",
  /* 84 */ "Layout",
  /* 85 */ "Ready",
  /* 86 */ "Program",
  /* 87 */ "A few held chords and scattered notes, made up as it goes rather than recorded: the piece never comes back to the same place twice. It stops on its own as soon as a game starts.",
  /* 88 */ "Tidy up a folder…",
  /* 89 */ "Empty",
  /* 90 */ "Search for a game…",
  /* 91 */ "Reset",
  /* 92 */ "Back to the library",
  /* 93 */ "Go back, close",
  /* 94 */ "Quick save",
  /* 95 */ "Save state…",
  /* 96 */ "Shaders",
  /* 97 */ "Sound",
  /* 98 */ "Start",
  /* 99 */ "Image size",
  /* 100 */ "Themes",
  /* 101 */ "Themes…",
  /* 102 */ "A single file…",
  /* 103 */ "A short tick as you move from game to game, another as you launch one. Gamepad only: with a mouse or a keyboard you feel the gesture already.",
  /* 104 */ "Speed",
  /* 105 */ "See the screenshots…",
  /* 106 */ "You can install only some of them — only the consoles whose emulator is installed show up in the library.",
  /* 107 */ "{0} — loaded",
  /* 108 */ "{0} — right-click to clear",
  /* 109 */ "{0} — added to favorites",
  /* 110 */ "{0} — reset",
  /* 111 */ "{0} — taken out of favorites",
  /* 112 */ "{0} — downloading…",
  /* 113 */ "{0}: failed, see the log",
  /* 114 */ "{0} on hand",
  /* 115 */ "{0} saved",
  /* 116 */ "{0} is an external emulator: it gets launched, not hosted",
  /* 117 */ "{0} fps",
  /* 118 */ "{0} installed",
  /* 119 */ "{0} installed — {1}",
  /* 120 */ "{0} installed and ready",
  /* 121 */ "{0} installed, {1} failed — see the log",
  /* 122 */ "{0} restored",
  /* 123 */ "{0} removed",
  /* 124 */ "{0} of {1}",
  /* 125 */ "{0} on the disk, but no installed core opens them.",
  /* 126 */ "to be taken from {0}, then “Browse…”",
  /* 127 */ "to download",
  /* 128 */ "missing, optional",
  /* 129 */ "Enable",
  /* 130 */ "Soft",
  /* 131 */ "couldn't add — {0}",
  /* 132 */ "Fit",
  /* 133 */ "Amber",
  /* 134 */ "Slate",
  /* 135 */ "stopped — {0}",
  /* 136 */ "hard stop last time — {0}",
  /* 137 */ "none",
  /* 138 */ "no core returned though {0} were known — previous list kept",
  /* 139 */ "no emulator",
  /* 140 */ "No emulator installed",
  /* 141 */ "No game recognized",
  /* 142 */ "No results",
  /* 143 */ "none",
  /* 144 */ "library unreadable — {0}",
  /* 145 */ "plugged in",
  /* 146 */ "screenshot",
  /* 147 */ "Change the cover art…",
  /* 148 */ "Change…",
  /* 149 */ "One pixel becomes nine",
  /* 150 */ "One pixel becomes four: sharp, nothing stretched",
  /* 151 */ "One pixel becomes sixteen — for large screens",
  /* 152 */ "Load",
  /* 153 */ "Choose cover art…",
  /* 154 */ "pick a game in the library first",
  /* 155 */ "core: {0}",
  /* 156 */ "core not installed",
  /* 157 */ "Installed cores",
  /* 158 */ "libretro cores",
  /* 159 */ "High contrast",
  /* 160 */ "native shell: {0}",
  /* 161 */ "unload incomplete — {0}",
  /* 162 */ "discovery: {0}",
  /* 163 */ "discovery cut short — {0}",
  /* 164 */ "Point to the {0} program yourself",
  /* 165 */ "folder added: {0}",
  /* 166 */ "folder opened: {0}",
  /* 167 */ "Default folder",
  /* 168 */ "Added folders",
  /* 169 */ "Esc",
  /* 170 */ "Slot {0}",
  /* 171 */ "slot {0} — {1}",
  /* 172 */ "Emulator used for this folder",
  /* 173 */ "external emulators",
  /* 174 */ "under way",
  /* 175 */ "in place",
  /* 176 */ "couldn't save — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi can download them from the official libretro build server. Pick the consoles you care about.",
  /* 179 */ "EvaChi stopped while launching “{0}”, with the {1} emulator.",
  /* 180 */ "EvaChi stopped, with the {0} emulator.",
  /* 181 */ "external_systems → {0} emulators declared",
  /* 182 */ "Favorite",
  /* 183 */ "Favorites",
  /* 184 */ "system files unreadable — {0}",
  /* 185 */ "Arrow keys",
  /* 186 */ "Game Boy",
  /* 187 */ "Grid",
  /* 188 */ "installed consoles are missing {0}",
  /* 189 */ "install finished: {0}",
  /* 190 */ "Installing…",
  /* 191 */ "installed",
  /* 192 */ "installed by EvaChi",
  /* 193 */ "Install",
  /* 194 */ "interpreter: {0}",
  /* 195 */ "asking the installed cores…",
  /* 196 */ "Play",
  /* 197 */ "Launch the chosen game",
  /* 198 */ "Lavender",
  /* 199 */ "Consoles in a row, games in a column, a background that ripples. Living-room console style.",
  /* 200 */ "Edges are blurred — closer to an old television set",
  /* 201 */ "Cover art writ large, browsed with the gamepad. Made for the couch.",
  /* 202 */ "Pixels stay square, just as on the original machine",
  /* 203 */ "gamepad bindings back to their defaults",
  /* 204 */ "list_cores → {0} cores announced",
  /* 205 */ "List",
  /* 206 */ "core list unavailable — {0}",
  /* 207 */ "emulator list unavailable — {0}",
  /* 208 */ "Gamepad",
  /* 209 */ "gamepad: {0}",
  /* 210 */ "Gamepad: {0}",
  /* 211 */ "gamepad unplugged",
  /* 212 */ "MISSING",
  /* 213 */ "Mint",
  /* 214 */ "Wave menu",
  /* 215 */ "Update",
  /* 216 */ "Add to favorites",
  /* 217 */ "set aside: {0} · {1}",
  /* 218 */ "less than a minute",
  /* 219 */ "Sharp",
  /* 220 */ "name, program and extensions are all needed",
  /* 221 */ "NO",
  /* 222 */ "not installed on this machine",
  /* 223 */ "Pink night",
  /* 224 */ "Ocean",
  /* 225 */ "or",
  /* 226 */ "yes",
  /* 227 */ "couldn't open — {0}",
  /* 228 */ "web page: only the built-in cores are available, and no library",
  /* 229 */ "Paper",
  /* 230 */ "default",
  /* 231 */ "Move through the grid and the animated menus",
  /* 232 */ "fullscreen refused — {0}",
  /* 233 */ "press the button you want on the gamepad",
  /* 234 */ "press a key…",
  /* 235 */ "tidied up: {0} · {1}",
  /* 236 */ "couldn't tidy up — {0}",
  /* 237 */ "emulator search cut short — {0}",
  /* 238 */ "Close a window",
  /* 239 */ "couldn't reset — {0}",
  /* 240 */ "Fills the window, keeping the proportions",
  /* 241 */ "Resume",
  /* 242 */ "Replace",
  /* 243 */ "Restore",
  /* 244 */ "couldn't restore — {0}",
  /* 245 */ "Remove",
  /* 246 */ "Remove from favorites",
  /* 247 */ "Remove the cover art",
  /* 248 */ "couldn't remove — {0}",
  /* 249 */ "nothing to tidy up",
  /* 250 */ "nothing in the way",
  /* 251 */ "Nothing matches “{0}”.",
  /* 252 */ "Pink and white",
  /* 253 */ "no picture",
  /* 254 */ "Save",
  /* 255 */ "Save here",
  /* 256 */ "couldn't select — {0}",
  /* 257 */ "The console's own size, down to the pixel",
  /* 258 */ "Discard",
  /* 259 */ "light theme",
  /* 260 */ "dark theme",
  /* 261 */ "everything is installed",
  /* 262 */ "found: {0}",
  /* 263 */ "One section per console, laid out as a table. The densest with a mouse.",
  /* 264 */ "empty",
  /* 265 */ "to be dropped in here, like the game romsets: FinalBurn Neo only looks in this folder",
  /* 266 */ "adds the console's boot screen",
  /* 267 */ "the machine's boot ROM",
  /* 268 */ "plenty of games start without it; the console menu doesn't",
  /* 269 */ "US BIOS",
  /* 270 */ "US and European BIOS",
  /* 271 */ "European BIOS",
  /* 272 */ "Japanese BIOS",
  /* 273 */ "decryption keys; without them an encrypted dump is turned away",
  /* 274 */ "the Machines folder from the blueMSX distribution, with Databases beside it",
  /* 275 */ "same again",
  /* 276 */ "essential for CD games, useless for HuCard cards",
  /* 277 */ "essential for Mega-CD games, useless for cartridges",
  /* 278 */ "Kickstart 1.3; otherwise PUAE falls back on AROS, free but less compatible",
  /* 279 */ "Kickstart 3.1; needed for AGA games, which the A500 can't run",
  /* 280 */ "melonDS emulates the BIOS by default; the real one is truer",
  /* 281 */ "mGBA does without it; a few games ask for it for their boot screen",
  /* 282 */ "the console's firmware",
  /* 283 */ "the machine's firmware",
  /* 284 */ "Panasonic FZ-10 firmware; that is the name Opera expects by default",
  /* 285 */ "changed by melonDS, which keeps the original as .bak",
  /* 286 */ "character fonts",
  /* 287 */ "the console's settings and date",
  /* 288 */ "without it the core runs but the screen stays black",
  /* 289 */ "the console's character table",
  /* 290 */ "US variant, for Sega CD games from the States",
  /* 291 */ "Japanese variant, for Japanese Mega-CD games",
  /* 292 */ "screenshots",
  /* 293 */ "screenshots",
  /* 294 */ "screenshot",
  /* 295 */ "screenshots",
  /* 296 */ "screenshots",
  /* 297 */ "screenshots",
  /* 298 */ "cores",
  /* 299 */ "cores",
  /* 300 */ "core",
  /* 301 */ "cores",
  /* 302 */ "cores",
  /* 303 */ "cores",
  /* 304 */ "emulators",
  /* 305 */ "emulators",
  /* 306 */ "emulator",
  /* 307 */ "emulators",
  /* 308 */ "emulators",
  /* 309 */ "emulators",
  /* 310 */ "files",
  /* 311 */ "files",
  /* 312 */ "file",
  /* 313 */ "files",
  /* 314 */ "files",
  /* 315 */ "files",
  /* 316 */ "games",
  /* 317 */ "games",
  /* 318 */ "game",
  /* 319 */ "games",
  /* 320 */ "games",
  /* 321 */ "games",
  /* 322 */ "<code>{rom}</code> will be replaced by the path to the game. Without it, the path is added at the end — which is what most emulators expect.",
  /* 323 */ "<strong>Outside a game, everything is done on the gamepad:</strong> the directions move through the library, the windows and the menu bar; <strong>A</strong> confirms, <strong>B</strong> goes back, <strong>Start</strong> opens the menu bar. During a game, <strong>Select and Start together</strong> bring you back to the library — two buttons at once, since each one is busy with the game.",
  /* 324 */ "No screenshots. Press <strong>F12</strong> during a game, or <strong>Select + Y</strong> on the gamepad.",
  /* 325 */ "Every console needs its emulator. EvaChi goes and fetches them from the libretro project's official build server, <code>buildbot.libretro.com</code>, and installs them in a folder of its own. Nothing is redistributed: these are the builds published by their authors.",
  /* 326 */ "Four slots per game, kept on the disk. Every action is written under the slot, and replacing or emptying asks first. <strong>F2</strong> and <strong>F4</strong> — and <strong>Select + L1</strong> / <strong>Select + R1</strong> on the gamepad — go straight to the slot in bold, asking nothing.",
  /* 327 */ "Every emulator runs in its own process: when it falls, EvaChi sees it and comes back to the library. The game in progress is lost, and the game's own save may not have been written. Setting this emulator aside leaves it installed but stops offering it. You can restore it at any time from <strong>File → Emulators</strong>, at the bottom of the window.",
  /* 328 */ "A single file per game on the disk <small> A game on CD arrives as one <code>.cue</code> sheet and as many <code>.bin</code> files as the disc had tracks. Only the sheet starts: the tracks are hidden while it is there. With no sheet, nothing is hidden. </small>",
  /* 329 */ "(empty) or --fullscreen {rom}",
  /* 330 */ "One hundred percent is the console's own speed. Below that the game slows down, above it the game races — and the sound follows along, lower or higher. On the controller, left and right step from one notch to the next. Internal cores only: an external emulator keeps its own speed.",
  /* 331 */ "Five consoles at a time",
  /* 332 */ "D-pad",
  /* 333 */ "From one letter to the next",
  /* 334 */ "In the animated menus, five games at a time",
  /* 335 */ "Game speed",
  /* 336 */ "Cancel",
  /* 337 */ "Drag the frame, or pull a corner. The arrow keys move it, and with Shift it grows or shrinks. Let it spill past the image and transparent bands appear around it — that's how you zoom out a cover that sits too tight. On the controller, the directions move it and the triggers set the size.",
  /* 338 */ "Crop",
  /* 339 */ "Crop the cover",
  /* 340 */ "Whole image",
  /* 341 */ "{0} — cover cropped",
  /* 342 */ "{0} — no cover to crop",
  /* 343 */ "cover unreadable — {0}",
  /* 344 */ "crop failed — {0}",
  /* 345 */ "Crop the cover…",
  /* 346 */ "Fast-forward, for as long as both sticks are pressed in",
  /* 347 */ "{0} set aside",
  /* 348 */ "The {0} emulator stopped during “{1}”.",
  /* 349 */ "The {0} emulator stopped.",
  /* 350 */ "The emulator stopped",
  /* 351 */ "couldn't set aside — {0}",
  /* 352 */ "to be dropped in here: {0}",
  /* 353 */ "a system file is missing: {0}",
  /* 354 */ "Credits",
  /* 355 */ "Non-commercial license, worth knowing before anyone builds on this work: {0}.",
  /* 356 */ "EvaChi writes no emulator of its own: it hosts them. Each one is a free project in its own right, written by others, which EvaChi goes and fetches from its authors on demand — not a line of their code is copied here, not a byte is redistributed. The names and the licenses below are the ones each project declares for itself.",
  /* 357 */ "Carousel",
  /* 358 */ "Covers face-on, consoles in a stack, dust drifting up. Display-stand style.",
  /* 359 */ "Same as the interface",
  /* 360 */ "Interface language",
  /* 361 */ "Game language",
  /* 362 */ "Game language: {0}. It takes effect from the next launch.",
  /* 363 */ "Back",
  /* 364 */ "Search",
  /* 365 */ "Find the files",
  /* 366 */ "Search for a value",
  /* 367 */ "Different",
  /* 368 */ "Unchanged",
  /* 369 */ "Width",
  /* 370 */ "The libretro project publishes cheat files, one per game. EvaChi keeps only those that fit your game exactly — same title, same region, same revision — and would rather offer nothing than something close: codes written for another version do not write slightly off, they write somewhere else entirely.",
  /* 371 */ "The cheats",
  /* 372 */ "Less",
  /* 373 */ "Cheat panel",
  /* 374 */ "More",
  /* 375 */ "Start over",
  /* 376 */ "Cheats",
  /* 377 */ "Cheats…",
  /* 378 */ "Value",
  /* 379 */ "Equals",
  /* 380 */ "{0} possible addresses",
  /* 381 */ "{0} files installed, {1} removed",
  /* 382 */ "{0} of {1} games have a file",
  /* 383 */ "{0} bytes of memory",
  /* 384 */ "{0} values discarded: outside this game’s memory",
  /* 385 */ "No file for this game. The “Cheats…” panel in the Emulation menu looks for one; failing that, the value search works on any game.",
  /* 386 */ "Frozen",
  /* 387 */ "Freeze",
  /* 388 */ "Play for a moment, then say what the value did.",
  /* 389 */ "The game was set aside before the first cheat.",
  /* 390 */ "Searching…",
  /* 391 */ "Whatever is dropped into « drop u'r rom » goes to the console its extension names. When several consoles share the same one — disc images — EvaChi asks rather than gambles.",
  /* 392 */ "Confirmation",
  /* 393 */ "Erase the game save…",
  /* 394 */ "Stretch",
  /* 395 */ "A game keeps its counters in memory without saying where. You find them by elimination: you say what the number on screen did, and EvaChi drops every address that did not do the same.",
  /* 396 */ "Yes",
  /* 397 */ "Few consoles have the proportions of a screen of today, hence the black bars on the sides. At zero the picture keeps its proportions; at a hundred it fills the window, stretched if need be.",
  /* 398 */ "Sorting the games",
  /* 399 */ "Sort",
  /* 400 */ "Sort the dropped games…",
  /* 401 */ "You see 47 lives: type 47 into « Value » and press « Search ». Lose one, type 46 and press « Equals ». If the number is written nowhere, leave « Value » empty and simply say « More », « Less », « Different » or « Unchanged » between two moments of play. « Freeze » then holds the value found. « Width » is the size of the number: 1 up to 255, 2 beyond, 4 for large counters.",
  /* 402 */ "{0} sorted",
  /* 403 */ "no game save to erase",
  /* 404 */ "Buttons",
  /* 405 */ "Already in the library: {0}",
  /* 406 */ "Erase the save of {0} and start over? The game in progress will be stopped, and whatever the game had written down will be lost.",
  /* 407 */ "Triggers",
  /* 408 */ "Keep both",
  /* 409 */ "Leave it in the drop folder",
  /* 410 */ "The drop folder is empty.",
  /* 411 */ "Replace slot {0}? Whatever is stored there will be lost.",
  /* 412 */ "game save erased — {0}",
  /* 413 */ "System",
  /* 414 */ "Empty slot {0}? Whatever is stored there will be lost.",
  /* 415 */ "The dead zone is the part of the stick where it still counts as at rest. Too small, and the character drifts off by itself with the controller on the table; too large, and the small movements are lost. Some games ask you to shake the console: when the gamepad cannot feel that, the two shortcuts below make the game believe it.",
  /* 416 */ "The stick",
  /* 417 */ "Standalone emulators have their own bindings, in their own files. What you change here is carried over at once, for the ones whose format we know first-hand: PCSX2, PPSSPP and Dolphin. The old setting is set aside on the first pass, under the same name followed by « .avant-evachi ».",
  /* 418 */ "Carry over to external emulators",
  /* 419 */ "Dead zone",
  /* 420 */ "Screening",
  /* 421 */ "Clay",
  /* 422 */ "no external emulator has written its settings yet",
  /* 423 */ "Ember",
  /* 424 */ "Ash",
  /* 425 */ "Cherry",
  /* 426 */ "Coral",
  /* 427 */ "Deck",
  /* 428 */ "Forest",
  /* 429 */ "Frost",
  /* 430 */ "the external emulators already had these bindings",
  /* 431 */ "Midnight",
  /* 432 */ "Moss",
  /* 433 */ "Neon",
  /* 434 */ "Plum",
  /* 435 */ "Sand",
  /* 436 */ "Shake",
  /* 437 */ "Sepia",
  /* 438 */ "bindings carried over: {0}",
  /* 439 */ "Turquoise",
  /* 440 */ "The covers held in a fan, like a hand of cards. The wrist turns, and the card being read straightens up.",
  /* 441 */ "A dark room, a beam full of dust, and the game projected large. The rest waits in the tray.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Apricot",
  /* 444 */ "Heather",
  /* 445 */ "Caramel",
  /* 446 */ "Copper",
  /* 447 */ "Ink",
  /* 448 */ "Famicom",
  /* 449 */ "Jade",
  /* 450 */ "Blueberry",
  /* 451 */ "Storm",
  /* 452 */ "Pearl",
  /* 453 */ "Pistachio",
  /* 454 */ "None",
  /* 455 */ "Scanlines",
  /* 456 */ "Each pixel as three slits: red, green and blue",
  /* 457 */ "The core’s picture, pixel for pixel",
  /* 458 */ "The curved glass, the lines, the slits and the dimmed edges",
  /* 459 */ "Shadow mask",
  /* 460 */ "Cathode-ray tube",
  /* 461 */ "Every other line darkened, as on a television",
];
