/**
 * Espagnol — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * numérotées en commentaire sont là pour qu'on puisse le vérifier à l'œil.
 */

export const es: readonly string[] = [
  /* 1 */ "Con el mando",
  /* 2 */ "A jugar · X favorito · Y recortar · L1/R1 consolas · L2/R2 letra · B volver",
  /* 3 */ "Acerca de EvaChi",
  /* 4 */ "Acerca de…",
  /* 5 */ "Lo que un televisor de tubo hacía con la imagen, y que los juegos de entonces daban por hecho. Solo vale para los núcleos jugados aquí: un emulador autónomo dibuja su propia imagen.",
  /* 6 */ "Actualizar la biblioteca",
  /* 7 */ "Ver",
  /* 8 */ "Mostrar las carátulas de los juegos",
  /* 9 */ "Ayuda",
  /* 10 */ "Añadir una carpeta de juegos…",
  /* 11 */ "Añadir una carpeta…",
  /* 12 */ "Pulsa un botón del mando: la orden correspondiente se enciende. Para cambiar una, haz clic en la casilla de abajo y pulsa el botón que quieras. El botón cambia entonces de dueño: dos órdenes en el mismo botón parecerían una avería.",
  /* 13 */ "Argumentos",
  /* 14 */ "Con el teclado",
  /* 15 */ "Ningún juego",
  /* 16 */ "No se detecta ningún mando.",
  /* 17 */ "Biblioteca",
  /* 18 */ "Sonidos de selección con el mando",
  /* 19 */ "Algunas consolas no arrancan sin su firmware original. EvaChi no puede facilitarlo: es código con copyright, que se copia de la máquina que uno tiene. Lo que sí hace es decir cuál falta, con qué nombre y dónde ponerlo.",
  /* 20 */ "Estas consolas no tienen núcleo libretro: su emulador es un programa aparte, que EvaChi instala en su propia carpeta y abre directamente en el juego, sin pasar por su menú. Los juegos, las claves y los archivos de sistema corren de tu cuenta.",
  /* 21 */ "Estos ajustes solo tocan los núcleos internos. Un emulador externo tiene los suyos, y EvaChi no se mete en eso.",
  /* 22 */ "Estos ya no se ofrecen: no respondieron al sondeo, o hicieron caer a EvaChi. Recuperarlos no los reinstala: simplemente vuelven a la lista.",
  /* 23 */ "Cargar estado…",
  /* 24 */ "Solo núcleos internos. Haz clic en un atajo y pulsa la tecla o el botón deseado; con el mando se toman dos botones a la vez, porque cada uno ya le sirve al juego.",
  /* 25 */ "Controles",
  /* 26 */ "Controles…",
  /* 27 */ "Consolas recientes",
  /* 28 */ "Declarar otro emulador",
  /* 29 */ "Direcciones / stick izquierdo",
  /* 30 */ "Carpetas de juegos",
  /* 31 */ "Apartar este emulador",
  /* 32 */ "Vienen del servidor de miniaturas del proyecto libretro, según hacen falta. Sin marcar, la biblioteca ya no pide nada a la red.",
  /* 33 */ "Ranuras de guardado",
  /* 34 */ "Ranuras…",
  /* 35 */ "Emuladores",
  /* 36 */ "Emuladores apartados",
  /* 37 */ "Emuladores externos",
  /* 38 */ "Emuladores externos…",
  /* 39 */ "Emuladores…",
  /* 40 */ "Emulación",
  /* 41 */ "Durante la partida, volver a la biblioteca — dos botones a la vez, porque cada uno le sirve al juego",
  /* 42 */ "Guardar",
  /* 43 */ "Extensiones",
  /* 44 */ "Cerrar",
  /* 45 */ "Archivo",
  /* 46 */ "Archivos de sistema que hay que instalar uno mismo",
  /* 47 */ "Galería",
  /* 48 */ "Gestionar las carpetas…",
  /* 49 */ "Gráficos",
  /* 50 */ "Gráficos…",
  /* 51 */ "Indica la carpeta donde están tus juegos.",
  /* 52 */ "Instalación",
  /* 53 */ "Instalar la selección",
  /* 54 */ "Instalar los emuladores…",
  /* 55 */ "Intérprete",
  /* 56 */ "No hace falta saber dónde va cada cosa: señala la carpeta donde ande todo — BIOS, claves, firmwares, archivos comprimidos, subcarpetas incluidas — y EvaChi lleva cada archivo a su sitio, tanto para los núcleos como para los emuladores autónomos. Lo que nadie reclama no se mueve.",
  /* 57 */ "Carátulas",
  /* 58 */ "Registro",
  /* 59 */ "Registro…",
  /* 60 */ "La vez anterior acabó mal",
  /* 61 */ "Iniciar el juego, confirmar",
  /* 62 */ "Idioma",
  /* 63 */ "La elección se recuerda de un arranque a otro. Cada uno se ha comprobado legible: el texto mantiene en todas partes un contraste suficiente sobre su fondo.",
  /* 64 */ "Conservarlo",
  /* 65 */ "Los emuladores de abajo ya vienen configurados, argumentos y formatos incluidos. EvaChi los busca en tu disco; no los instala.",
  /* 66 */ "Asignaciones originales",
  /* 67 */ "Suavizado",
  /* 68 */ "Marcar el juego como favorito, o quitarlo",
  /* 69 */ "Música de los menús animados",
  /* 70 */ "Nombre",
  /* 71 */ "Abrir la barra de menús",
  /* 72 */ "Abrir la carpeta",
  /* 73 */ "Abrir la carpeta…",
  /* 74 */ "Abrir un juego…",
  /* 75 */ "por fotograma",
  /* 76 */ "Ajustes del núcleo",
  /* 77 */ "Ajustes del núcleo…",
  /* 78 */ "Recorrer la biblioteca, las ventanas y la barra de menús",
  /* 79 */ "Examinar…",
  /* 80 */ "Pausa",
  /* 81 */ "Pantalla completa",
  /* 82 */ "Para las consolas sin núcleo libretro. EvaChi lanza el programa con el juego como argumento: el emulador arranca directamente en la partida, sin pasar por su propio menú.",
  /* 83 */ "Hacer una captura",
  /* 84 */ "Presentación",
  /* 85 */ "Listo",
  /* 86 */ "Programa",
  /* 87 */ "Unos acordes sostenidos y algunas notas sueltas, compuestas sobre la marcha en vez de grabadas: la pieza nunca vuelve a pasar por el mismo sitio. Se detiene sola en cuanto arranca un juego.",
  /* 88 */ "Clasificar una carpeta…",
  /* 89 */ "Vaciar",
  /* 90 */ "Buscar un juego…",
  /* 91 */ "Reiniciar",
  /* 92 */ "Volver a la biblioteca",
  /* 93 */ "Volver atrás, cerrar",
  /* 94 */ "Guardado rápido",
  /* 95 */ "Guardar estado…",
  /* 96 */ "Shaders",
  /* 97 */ "Sonido",
  /* 98 */ "Start",
  /* 99 */ "Tamaño de la imagen",
  /* 100 */ "Temas",
  /* 101 */ "Temas…",
  /* 102 */ "Un solo archivo…",
  /* 103 */ "Un tic breve al cambiar de juego, otro al iniciarlo. Solo con el mando: con el ratón y el teclado, el gesto ya se nota.",
  /* 104 */ "Velocidad",
  /* 105 */ "Ver las capturas…",
  /* 106 */ "Puedes instalar solo una parte: en la biblioteca solo aparecen las consolas cuyo emulador está instalado.",
  /* 107 */ "{0} — cargado",
  /* 108 */ "{0} — clic derecho para borrar",
  /* 109 */ "{0} — marcado como favorito",
  /* 110 */ "{0} — reiniciado",
  /* 111 */ "{0} — quitado de favoritos",
  /* 112 */ "{0} — descargando…",
  /* 113 */ "{0}: falló, ver el registro",
  /* 114 */ "{0} a disposición",
  /* 115 */ "{0} guardado",
  /* 116 */ "{0} es un emulador externo: se lanza, no se aloja",
  /* 117 */ "{0} img/s",
  /* 118 */ "{0} instalado",
  /* 119 */ "{0} instalado — {1}",
  /* 120 */ "{0} instalado y listo",
  /* 121 */ "{0} instalados, {1} fallidos — ver el registro",
  /* 122 */ "{0} recuperado",
  /* 123 */ "{0} retirado",
  /* 124 */ "{0} de {1}",
  /* 125 */ "{0} en el disco, pero ningún núcleo instalado lo abre.",
  /* 126 */ "a conseguir en {0}, luego « Examinar… »",
  /* 127 */ "por descargar",
  /* 128 */ "ausente, opcional",
  /* 129 */ "Activar",
  /* 130 */ "Suave",
  /* 131 */ "no se pudo añadir — {0}",
  /* 132 */ "Ajustar",
  /* 133 */ "Ámbar",
  /* 134 */ "Pizarra",
  /* 135 */ "parada — {0}",
  /* 136 */ "parada brusca la vez anterior — {0}",
  /* 137 */ "ninguno",
  /* 138 */ "ningún núcleo devuelto aunque se conocían {0} — se conserva la lista anterior",
  /* 139 */ "ningún emulador",
  /* 140 */ "Ningún emulador instalado",
  /* 141 */ "Ningún juego reconocido",
  /* 142 */ "Sin resultados",
  /* 143 */ "ninguna",
  /* 144 */ "biblioteca ilegible — {0}",
  /* 145 */ "conectado",
  /* 146 */ "captura",
  /* 147 */ "Cambiar la carátula…",
  /* 148 */ "Cambiar…",
  /* 149 */ "Cada píxel en nueve",
  /* 150 */ "Cada píxel en cuatro: nítido, sin deformación",
  /* 151 */ "Cada píxel en dieciséis — para pantallas grandes",
  /* 152 */ "Cargar",
  /* 153 */ "Elegir una carátula…",
  /* 154 */ "elige primero un juego en la biblioteca",
  /* 155 */ "núcleo: {0}",
  /* 156 */ "núcleo no instalado",
  /* 157 */ "Núcleos instalados",
  /* 158 */ "núcleos libretro",
  /* 159 */ "Contraste alto",
  /* 160 */ "carcasa nativa: {0}",
  /* 161 */ "liberación incompleta — {0}",
  /* 162 */ "descubrimiento: {0}",
  /* 163 */ "descubrimiento interrumpido — {0}",
  /* 164 */ "Indicar uno mismo el programa de {0}",
  /* 165 */ "carpeta añadida: {0}",
  /* 166 */ "carpeta abierta: {0}",
  /* 167 */ "Carpeta por defecto",
  /* 168 */ "Carpetas añadidas",
  /* 169 */ "Esc",
  /* 170 */ "Ranura {0}",
  /* 171 */ "ranura {0} — {1}",
  /* 172 */ "Emulador usado para esta carpeta",
  /* 173 */ "emuladores externos",
  /* 174 */ "en curso",
  /* 175 */ "en su sitio",
  /* 176 */ "no se pudo guardar — {0}",
  /* 177 */ "Intro",
  /* 178 */ "EvaChi puede descargarlos del servidor oficial de libretro. Elige las consolas que te interesen.",
  /* 179 */ "EvaChi se detuvo al iniciar « {0} », con el emulador {1}.",
  /* 180 */ "EvaChi se detuvo, con el emulador {0}.",
  /* 181 */ "external_systems → {0} emuladores declarados",
  /* 182 */ "Favorito",
  /* 183 */ "Favoritos",
  /* 184 */ "archivos de sistema ilegibles — {0}",
  /* 185 */ "Flechas",
  /* 186 */ "Game Boy",
  /* 187 */ "Cuadrícula",
  /* 188 */ "faltan {0} en consolas instaladas",
  /* 189 */ "instalación terminada: {0}",
  /* 190 */ "Instalando…",
  /* 191 */ "instalado",
  /* 192 */ "instalado por EvaChi",
  /* 193 */ "Instalar",
  /* 194 */ "intérprete: {0}",
  /* 195 */ "consultando los núcleos instalados…",
  /* 196 */ "Iniciar",
  /* 197 */ "Iniciar el juego elegido",
  /* 198 */ "Lavanda",
  /* 199 */ "Las consolas en fila, los juegos en columna, un fondo que ondula. Al estilo de una consola de salón.",
  /* 200 */ "Los contornos se difuminan — más cerca de un televisor viejo",
  /* 201 */ "Las carátulas en grande, recorridas con el mando. Pensado para el sofá.",
  /* 202 */ "Los píxeles siguen siendo cuadrados, como en la máquina original",
  /* 203 */ "asignaciones del mando restablecidas",
  /* 204 */ "list_cores → {0} núcleos anunciados",
  /* 205 */ "Lista",
  /* 206 */ "lista de núcleos no disponible — {0}",
  /* 207 */ "lista de emuladores no disponible — {0}",
  /* 208 */ "Mando",
  /* 209 */ "mando: {0}",
  /* 210 */ "Mando: {0}",
  /* 211 */ "mando desconectado",
  /* 212 */ "FALTA",
  /* 213 */ "Menta",
  /* 214 */ "Menú animado",
  /* 215 */ "Actualizar",
  /* 216 */ "Añadir a favoritos",
  /* 217 */ "apartado: {0} · {1}",
  /* 218 */ "menos de un minuto",
  /* 219 */ "Nítido",
  /* 220 */ "nombre, programa y extensiones son todos necesarios",
  /* 221 */ "NO",
  /* 222 */ "no instalado en esta máquina",
  /* 223 */ "Noche rosa",
  /* 224 */ "Océano",
  /* 225 */ "o",
  /* 226 */ "sí",
  /* 227 */ "no se pudo abrir — {0}",
  /* 228 */ "página web: solo están disponibles los núcleos internos, sin biblioteca",
  /* 229 */ "Papel",
  /* 230 */ "por defecto",
  /* 231 */ "Recorrer la cuadrícula y los menús animados",
  /* 232 */ "pantalla completa denegada — {0}",
  /* 233 */ "pulsa el botón deseado en el mando",
  /* 234 */ "pulsa una tecla…",
  /* 235 */ "clasificación: {0} · {1}",
  /* 236 */ "no se pudo clasificar — {0}",
  /* 237 */ "búsqueda de emuladores interrumpida — {0}",
  /* 238 */ "Cerrar una ventana",
  /* 239 */ "no se pudo reiniciar — {0}",
  /* 240 */ "Llena la ventana manteniendo las proporciones",
  /* 241 */ "Reanudar",
  /* 242 */ "Reemplazar",
  /* 243 */ "Recuperar",
  /* 244 */ "no se pudo recuperar — {0}",
  /* 245 */ "Quitar",
  /* 246 */ "Quitar de favoritos",
  /* 247 */ "Quitar la carátula",
  /* 248 */ "no se pudo quitar — {0}",
  /* 249 */ "nada que clasificar",
  /* 250 */ "nada bloquea",
  /* 251 */ "Nada coincide con « {0} ».",
  /* 252 */ "Rosa y blanco",
  /* 253 */ "sin imagen",
  /* 254 */ "Guardar",
  /* 255 */ "Guardar aquí",
  /* 256 */ "no se pudo seleccionar — {0}",
  /* 257 */ "Tamaño original de la consola, píxel a píxel",
  /* 258 */ "Desechar",
  /* 259 */ "tema claro",
  /* 260 */ "tema oscuro",
  /* 261 */ "todo está instalado",
  /* 262 */ "encontrado: {0}",
  /* 263 */ "Una sección por consola, en tabla. Lo más denso con el ratón.",
  /* 264 */ "vacío",
  /* 265 */ "hay que ponerlo aquí, como los romsets de los juegos: FinalBurn Neo solo busca en esta carpeta",
  /* 266 */ "añade la pantalla de inicio de la consola",
  /* 267 */ "arranque de la máquina",
  /* 268 */ "muchos juegos arrancan sin él; el menú de la consola no",
  /* 269 */ "BIOS estadounidense",
  /* 270 */ "BIOS estadounidense y europeo",
  /* 271 */ "BIOS europeo",
  /* 272 */ "BIOS japonés",
  /* 273 */ "claves de descifrado; sin ellas se rechaza un volcado cifrado",
  /* 274 */ "carpeta Machines de la distribución de blueMSX, con Databases al lado",
  /* 275 */ "ídem",
  /* 276 */ "imprescindible para los juegos en CD, inútil para las HuCard",
  /* 277 */ "imprescindible para los juegos Mega-CD, inútil para los cartuchos",
  /* 278 */ "Kickstart 1.3; si no, PUAE recurre a AROS, libre pero menos compatible",
  /* 279 */ "Kickstart 3.1; necesario para los juegos AGA, que la A500 no sabe mover",
  /* 280 */ "melonDS emula el BIOS por defecto; el de verdad es más fiel",
  /* 281 */ "mGBA se apaña sin él; algunos juegos lo exigen para su pantalla de inicio",
  /* 282 */ "firmware de la consola",
  /* 283 */ "firmware de la máquina",
  /* 284 */ "firmware de la Panasonic FZ-10; es el nombre que Opera toma por defecto",
  /* 285 */ "melonDS lo modifica y conserva el original en .bak",
  /* 286 */ "tipos de letra",
  /* 287 */ "ajustes y fecha de la consola",
  /* 288 */ "sin él el núcleo funciona pero la pantalla se queda en negro",
  /* 289 */ "tabla de caracteres de la consola",
  /* 290 */ "variante estadounidense, para los juegos de Sega CD de Estados Unidos",
  /* 291 */ "variante japonesa, para los juegos Mega-CD japoneses",
  /* 292 */ "capturas",
  /* 293 */ "capturas",
  /* 294 */ "captura",
  /* 295 */ "capturas",
  /* 296 */ "capturas",
  /* 297 */ "capturas",
  /* 298 */ "núcleos",
  /* 299 */ "núcleos",
  /* 300 */ "núcleo",
  /* 301 */ "núcleos",
  /* 302 */ "núcleos",
  /* 303 */ "núcleos",
  /* 304 */ "emuladores",
  /* 305 */ "emuladores",
  /* 306 */ "emulador",
  /* 307 */ "emuladores",
  /* 308 */ "emuladores",
  /* 309 */ "emuladores",
  /* 310 */ "archivos",
  /* 311 */ "archivos",
  /* 312 */ "archivo",
  /* 313 */ "archivos",
  /* 314 */ "archivos",
  /* 315 */ "archivos",
  /* 316 */ "juegos",
  /* 317 */ "juegos",
  /* 318 */ "juego",
  /* 319 */ "juegos",
  /* 320 */ "juegos",
  /* 321 */ "juegos",
  /* 322 */ "<code>{rom}</code> se sustituirá por la ruta del juego. Sin él, la ruta se añade al final — que es lo que esperan la mayoría de los emuladores.",
  /* 323 */ "<strong>Fuera del juego, todo se hace con el mando:</strong> las direcciones recorren la biblioteca, las ventanas y la barra de menús; <strong>A</strong> confirma, <strong>B</strong> vuelve atrás, <strong>Start</strong> abre la barra de menús. Durante la partida, <strong>Select y Start a la vez</strong> devuelven a la biblioteca — dos botones a la vez, porque cada uno le sirve al juego.",
  /* 324 */ "Ninguna captura. Pulsa <strong>F12</strong> durante la partida, o <strong>Select + Y</strong> con el mando.",
  /* 325 */ "Cada consola necesita su emulador. EvaChi los busca en el servidor oficial del proyecto libretro, <code>buildbot.libretro.com</code>, y los instala en su propia carpeta. No se redistribuye nada: son las versiones publicadas por sus autores.",
  /* 326 */ "Cuatro ranuras por juego, guardadas en el disco. Cada gesto está escrito bajo la ranura, y reemplazar o vaciar pide confirmación. <strong>F2</strong> y <strong>F4</strong> — y <strong>Select + L1</strong> / <strong>Select + R1</strong> con el mando — van directos a la ranura en negrita, sin preguntar nada.",
  /* 327 */ "Cada emulador funciona en su propio proceso: cuando cae, EvaChi lo ve y vuelve a la biblioteca. La partida en curso se pierde, y puede que el guardado del juego no se haya escrito. Apartar este emulador lo deja instalado pero deja de ofrecerlo. Podrás recuperarlo cuando quieras desde <strong>Archivo → Emuladores</strong>, abajo en la ventana.",
  /* 328 */ "Un solo archivo por juego en el disco <small> Un juego en CD llega como una hoja <code>.cue</code> y tantos archivos <code>.bin</code> como pistas tuviera el disco. Solo se inicia la hoja: las pistas quedan ocultas cuando está. Sin hoja, no se oculta nada. </small>",
  /* 329 */ "(vacío) o --fullscreen {rom}",
  /* 330 */ "El cien por cien es la velocidad de la propia consola. Por debajo el juego se ralentiza, por encima vuela — y el sonido lo acompaña, más grave o más agudo. En el mando, izquierda y derecha pasan de un escalón al siguiente. Solo los núcleos internos: un emulador externo mantiene la suya.",
  /* 331 */ "Cinco consolas a la vez",
  /* 332 */ "Cruceta",
  /* 333 */ "De una inicial a la siguiente",
  /* 334 */ "En los menús animados, cinco juegos a la vez",
  /* 335 */ "Velocidad del juego",
  /* 336 */ "Cancelar",
  /* 337 */ "Arrastra el marco o tira de una esquina. Con las flechas lo mueves; con Mayús lo agrandas o lo reduces. Si se sale de la imagen, se añaden bandas transparentes: así se aleja una carátula demasiado ajustada. Con el mando, las direcciones lo mueven y los gatillos ajustan el tamaño.",
  /* 338 */ "Recortar",
  /* 339 */ "Recortar la carátula",
  /* 340 */ "Toda la imagen",
  /* 341 */ "{0} — carátula recortada",
  /* 342 */ "{0} — no hay carátula que recortar",
  /* 343 */ "carátula ilegible — {0}",
  /* 344 */ "no se pudo recortar — {0}",
  /* 345 */ "Recortar la carátula…",
  /* 346 */ "Avance rápido, mientras los dos sticks sigan pulsados",
  /* 347 */ "{0} apartado",
  /* 348 */ "El emulador {0} se ha detenido durante « {1} ».",
  /* 349 */ "El emulador {0} se ha detenido.",
  /* 350 */ "El emulador se ha detenido",
  /* 351 */ "no se pudo apartar — {0}",
  /* 352 */ "a poner aquí: {0}",
  /* 353 */ "falta un archivo de sistema: {0}",
  /* 354 */ "Créditos",
  /* 355 */ "Licencia no comercial, conviene saberlo antes de reutilizar este trabajo: {0}.",
  /* 356 */ "EvaChi no escribe ningún emulador: los aloja. Cada uno es un proyecto libre por derecho propio, escrito por otros, que EvaChi va a buscar a casa de sus autores según hace falta — ni una línea de su código se copia aquí, ni un byte se redistribuye. Los nombres y las licencias de abajo son los que declara cada proyecto por sí mismo.",
  /* 357 */ "Carrusel",
  /* 358 */ "Las carátulas de frente, las consolas apiladas, un polvo que sube. A la manera de un expositor.",
  /* 359 */ "Como la interfaz",
  /* 360 */ "Idioma de la interfaz",
  /* 361 */ "Idioma de los juegos",
  /* 362 */ "Idioma de los juegos: {0}. Se aplicará en el próximo arranque.",
  /* 363 */ "Atrás",
  /* 364 */ "Buscar",
  /* 365 */ "Buscar las fichas",
  /* 366 */ "Buscar un valor",
  /* 367 */ "Distinto",
  /* 368 */ "Igual",
  /* 369 */ "Anchura",
  /* 370 */ "El proyecto libretro publica fichas de trucos, una por juego. EvaChi solo conserva las que encajan exactamente con el suyo — mismo título, misma región, misma revisión — y prefiere no proponer nada antes que algo aproximado: los códigos escritos para otra versión no escriben un poco al lado, escriben en otro sitio.",
  /* 371 */ "Los trucos",
  /* 372 */ "Menos",
  /* 373 */ "Panel de trucos",
  /* 374 */ "Más",
  /* 375 */ "Empezar de nuevo",
  /* 376 */ "Trucos",
  /* 377 */ "Trucos…",
  /* 378 */ "Valor",
  /* 379 */ "Vale",
  /* 380 */ "{0} direcciones posibles",
  /* 381 */ "{0} fichas puestas, {1} retiradas",
  /* 382 */ "{0} de {1} juegos tienen ficha",
  /* 383 */ "{0} bytes de memoria",
  /* 384 */ "{0} valores descartados: fuera de la memoria de este juego",
  /* 385 */ "Ninguna ficha para este juego. El panel « Trucos… » del menú Emulación busca una; en su defecto, la búsqueda de valores funciona con cualquier juego.",
  /* 386 */ "Congelada",
  /* 387 */ "Congelar",
  /* 388 */ "Juegue un poco y diga después qué ha hecho el valor.",
  /* 389 */ "La partida se ha guardado aparte antes del primer truco.",
  /* 390 */ "Buscando…",
  /* 391 */ "Lo que se deja en « drop u'r rom » va hacia la consola que indica su extensión. Cuando varias consolas comparten la misma — las imágenes de disco — EvaChi pregunta en lugar de apostar.",
  /* 392 */ "Confirmación",
  /* 393 */ "Borrar la partida guardada…",
  /* 394 */ "Estiramiento",
  /* 395 */ "El juego guarda sus cuentas en la memoria sin decir dónde. Se encuentran por eliminación: dices qué ha hecho el número que se ve, y EvaChi descarta las direcciones que no han hecho lo mismo.",
  /* 396 */ "Sí",
  /* 397 */ "Pocas consolas tienen las proporciones de una pantalla de hoy, de ahí las bandas negras a los lados. En cero la imagen mantiene sus proporciones; en cien llena la ventana, aunque se alargue.",
  /* 398 */ "Ordenación de los juegos",
  /* 399 */ "Ordenar",
  /* 400 */ "Ordenar los juegos depositados…",
  /* 401 */ "Ves 47 vidas: escribe 47 en « Valor » y pulsa « Buscar ». Pierde una, escribe 46 y pulsa « Vale ». Si el número no está escrito en ninguna parte, deja « Valor » vacío y di solamente « Más », « Menos », « Distinto » o « Igual » entre dos momentos de juego. Después, « Congelar » mantiene el valor encontrado. « Anchura » es el tamaño del número: 1 hasta 255, 2 por encima, 4 para los contadores grandes.",
  /* 402 */ "{0} ordenados",
  /* 403 */ "ninguna partida guardada que borrar",
  /* 404 */ "Botones",
  /* 405 */ "Ya está en la biblioteca: {0}",
  /* 406 */ "¿Borrar la partida guardada de {0} y empezar de cero? La partida en curso se detendrá y se perderá lo que el juego había anotado.",
  /* 407 */ "Gatillos",
  /* 408 */ "Conservar ambos",
  /* 409 */ "Dejarlo en el depósito",
  /* 410 */ "El depósito está vacío.",
  /* 411 */ "¿Reemplazar la ranura {0}? Se perderá lo que hay guardado en ella.",
  /* 412 */ "partida guardada borrada — {0}",
  /* 413 */ "Sistema",
  /* 414 */ "¿Vaciar la ranura {0}? Se perderá lo que hay guardado en ella.",
  /* 415 */ "La zona muerta es la parte de la palanca en la que aún se considera en reposo. Demasiado pequeña, el personaje se mueve solo con el mando en la mesa; demasiado grande, los movimientos pequeños se pierden. Algunos juegos piden agitar la consola: cuando el mando no sabe notarlo, los dos botones de abajo se lo hacen creer al juego.",
  /* 416 */ "La palanca",
  /* 417 */ "Los emuladores autónomos tienen sus propias teclas, en sus propios archivos. Lo que cambies aquí se traslada allí enseguida, para aquellos cuyo formato conocemos de primera mano: PCSX2, PPSSPP y Dolphin. La configuración anterior se aparta en la primera pasada, con el mismo nombre seguido de « .avant-evachi ».",
  /* 418 */ "Trasladar a los emuladores externos",
  /* 419 */ "Zona muerta",
  /* 420 */ "Sesión",
  /* 421 */ "Arcilla",
  /* 422 */ "ningún emulador externo ha escrito todavía su configuración",
  /* 423 */ "Brasa",
  /* 424 */ "Ceniza",
  /* 425 */ "Cereza",
  /* 426 */ "Coral",
  /* 427 */ "Baraja",
  /* 428 */ "Bosque",
  /* 429 */ "Escarcha",
  /* 430 */ "los emuladores externos ya tenían estas teclas",
  /* 431 */ "Medianoche",
  /* 432 */ "Musgo",
  /* 433 */ "Neón",
  /* 434 */ "Ciruela",
  /* 435 */ "Arena",
  /* 436 */ "Agitar",
  /* 437 */ "Sepia",
  /* 438 */ "teclas trasladadas: {0}",
  /* 439 */ "Turquesa",
  /* 440 */ "Las carátulas sostenidas en abanico, como una mano de cartas. La muñeca gira y la carta que se lee se endereza.",
  /* 441 */ "Una sala a oscuras, un haz lleno de polvo y el juego proyectado en grande. El resto espera en el carro.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Albaricoque",
  /* 444 */ "Brezo",
  /* 445 */ "Caramelo",
  /* 446 */ "Cobre",
  /* 447 */ "Tinta",
  /* 448 */ "Famicom",
  /* 449 */ "Jade",
  /* 450 */ "Arándano",
  /* 451 */ "Tormenta",
  /* 452 */ "Perla",
  /* 453 */ "Pistacho",
  /* 454 */ "Ninguno",
  /* 455 */ "Barrido",
  /* 456 */ "Cada píxel en tres ranuras: roja, verde y azul",
  /* 457 */ "La imagen del núcleo, píxel a píxel",
  /* 458 */ "El vidrio abombado, las líneas, las ranuras y los bordes apagados",
  /* 459 */ "Rejilla",
  /* 460 */ "Tubo catódico",
  /* 461 */ "Una línea de cada dos oscurecida, como en un televisor",
  /* 462 */ "Abre el emulador en su propia ventana, sin juego",
  /* 463 */ "Abrir",
];
