/**
 * Estonien — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * de rang en commentaire sont là pour qu'on puisse le vérifier à l'œil.
 */

export const et: readonly string[] = [
  /* 1 */ "Mängupuldiga",
  /* 2 */ "A käivita · X lemmik · Y kärbi · L1/R1 konsoolid · L2/R2 täht · B tagasi",
  /* 3 */ "EvaChist",
  /* 4 */ "EvaChist…",
  /* 5 */ "Tulekul: kineskoobifiltrid, pikslivõre, realaotus. Koht on valmis, filtrid jõuavad siia.",
  /* 6 */ "Värskenda mängukogu",
  /* 7 */ "Vaade",
  /* 8 */ "Näita mängude kaanepilte",
  /* 9 */ "Abi",
  /* 10 */ "Lisa mängude kaust…",
  /* 11 */ "Lisa kaust…",
  /* 12 */ "Vajutage puldil mõnd nuppu: vastav klahv süttib. Mõne muutmiseks minge ümbermääramisse, klõpsake muudetavat klahvi ja vajutage siis soovitud nuppu.",
  /* 13 */ "Argumendid",
  /* 14 */ "Klaviatuuriga",
  /* 15 */ "Mänge pole",
  /* 16 */ "Mängupulti ei leitud.",
  /* 17 */ "Mängukogu",
  /* 18 */ "Puldi valikuhelid",
  /* 19 */ "Mõni konsool ei käivitu ilma oma algupärase püsivarata. EvaChi ei saa seda anda: see on autorikaitse all olev kood, mille kopeerib oma masinast. Küll aga ütleb ta, milline puudub, mis nime all ja kuhu see panna.",
  /* 20 */ "Neil konsoolidel pole libretro tuuma: nende emulaator on eraldi programm, mille EvaChi paigaldab oma kausta ja käivitab otse mängu sisse — emulaatori enda menüüst läbi käimata. Mängud, võtmed ja süsteemifailid jäävad teie hooleks.",
  /* 21 */ "Need sätted puudutavad ainult sisemisi tuumi. Välisel emulaatoril on omad ja EvaChi neisse ei sekku.",
  /* 22 */ "Neid enam ei pakuta: nad ei vastanud päringule või ajasid EvaChi ümber. Taastamine ei paigalda neid uuesti — see toob nad lihtsalt nimekirja tagasi.",
  /* 23 */ "Laadi olek",
  /* 24 */ "Ainult sisemised tuumad. Klõpsake kiirklahvi ja vajutage siis soovitud klahvi või nuppu; puldil võetakse kaks nuppu korraga, sest igaüht neist läheb mängus juba tarvis.",
  /* 25 */ "Juhtimine",
  /* 26 */ "Juhtimine…",
  /* 27 */ "Hiljutised konsoolid",
  /* 28 */ "Lisa muu emulaator",
  /* 29 */ "Suunad / vasak kang",
  /* 30 */ "Mängude kaustad",
  /* 31 */ "Pane see emulaator kõrvale",
  /* 32 */ "Need tulevad vajaduse korral libretro projekti pisipiltide serverist. Linnukest eemaldades ei küsi mängukogu võrgust enam midagi.",
  /* 33 */ "Salvestuspesad",
  /* 34 */ "Salvestuspesad…",
  /* 35 */ "Emulaatorid",
  /* 36 */ "Kõrvale pandud emulaatorid",
  /* 37 */ "Välised emulaatorid",
  /* 38 */ "Välised emulaatorid…",
  /* 39 */ "Emulaatorid…",
  /* 40 */ "Emuleerimine",
  /* 41 */ "Mängu ajal mängukogusse naasmine — kaks nuppu korraga, sest igaüht neist läheb mängus tarvis",
  /* 42 */ "Salvesta",
  /* 43 */ "Laiendid",
  /* 44 */ "Sulge",
  /* 45 */ "Fail",
  /* 46 */ "Ise paigaldatavad süsteemifailid",
  /* 47 */ "Galerii",
  /* 48 */ "Halda kaustu…",
  /* 49 */ "Graafika",
  /* 50 */ "Graafika…",
  /* 51 */ "Näidake kaust, kus teie mängud asuvad.",
  /* 52 */ "Paigaldus",
  /* 53 */ "Paigalda valitud",
  /* 54 */ "Paigalda emulaatorid…",
  /* 55 */ "Interpretaator",
  /* 56 */ "Pole vaja teada, kuhu: näidake kaust, kus kõik vedeleb — BIOS-id, võtmed, püsivara, arhiivid, alamkaustad kaasa arvatud — ja EvaChi viib iga faili õigesse kohta, nii tuumade kui ka eraldiseisvate emulaatorite jaoks. Mida keegi ei küsi, seda ei liigutata.",
  /* 57 */ "Kaanepildid",
  /* 58 */ "Logi",
  /* 59 */ "Logi…",
  /* 60 */ "Eelmine kord lõppes halvasti",
  /* 61 */ "Käivita mäng, kinnita",
  /* 62 */ "Keel",
  /* 63 */ "Valik jääb meelde ühest käivitusest teise. Iga teema loetavust on kontrollitud: tekst püsib kõikjal taustal piisava kontrastiga.",
  /* 64 */ "Jäta alles",
  /* 65 */ "Allpool olevad emulaatorid on juba seadistatud — koos argumentide ja vormingutega. EvaChi otsib neid teie kettalt; ta ei paigalda neid.",
  /* 66 */ "Algsed seosed",
  /* 67 */ "Silumine",
  /* 68 */ "Lisa mäng lemmikutesse või eemalda sealt",
  /* 69 */ "Animeeritud menüü muusika",
  /* 70 */ "Nimi",
  /* 71 */ "Ava menüüriba",
  /* 72 */ "Ava kaust",
  /* 73 */ "Ava kaust…",
  /* 74 */ "Ava mäng…",
  /* 75 */ "kaadri kohta",
  /* 76 */ "Tuuma sätted",
  /* 77 */ "Tuuma sätted…",
  /* 78 */ "Liikumine mängukogus, akendes ja menüüribal",
  /* 79 */ "Sirvi…",
  /* 80 */ "Paus",
  /* 81 */ "Täisekraan",
  /* 82 */ "Konsoolidele, millel pole libretro tuuma. EvaChi käivitab programmi nii, et mäng on argumendiks: emulaator alustab otse mängust, käimata läbi oma menüüst.",
  /* 83 */ "Tee ekraanipilt",
  /* 84 */ "Kuvaviis",
  /* 85 */ "Valmis",
  /* 86 */ "Programm",
  /* 87 */ "Mõni pikk akord ja hajusad noodid, mis pigem sünnivad käigu pealt kui on lindistatud: lugu ei jõua kunagi samasse kohta tagasi. Niipea kui mäng käivitub, jääb see ise vait.",
  /* 88 */ "Korrasta kaust…",
  /* 89 */ "Määra ümber…",
  /* 90 */ "Otsi mängu…",
  /* 91 */ "Lähtesta",
  /* 92 */ "Tagasi mängukogusse",
  /* 93 */ "Mine tagasi, sulge",
  /* 94 */ "Kiirsalvestus",
  /* 95 */ "Salvesta olek",
  /* 96 */ "Shaderid",
  /* 97 */ "Heli",
  /* 98 */ "Start",
  /* 99 */ "Pildi suurus",
  /* 100 */ "Teemad",
  /* 101 */ "Teemad…",
  /* 102 */ "Üks fail…",
  /* 103 */ "Lühike naks mängu vahetamisel, teine selle käivitamisel. Ainult puldiga: hiire ja klaviatuuriga on liigutus niigi tunda.",
  /* 104 */ "Kiirus",
  /* 105 */ "Vaata ekraanipilte…",
  /* 106 */ "Võite paigaldada neist vaid osa — mängukogus on näha ainult need konsoolid, mille emulaator on paigaldatud.",
  /* 107 */ "{0} — laaditud",
  /* 108 */ "{0} — paremklõps kustutab",
  /* 109 */ "{0} — lisatud lemmikutesse",
  /* 110 */ "{0} — lähtestatud",
  /* 111 */ "{0} — eemaldatud lemmikutest",
  /* 112 */ "{0} — allalaadimine…",
  /* 113 */ "{0}: nurjus, vaadake logi",
  /* 114 */ "{0} saadaval",
  /* 115 */ "{0} salvestatud",
  /* 116 */ "{0} on väline emulaator: seda käivitatakse, mitte ei majutata",
  /* 117 */ "{0} k/s",
  /* 118 */ "{0} paigaldatud",
  /* 119 */ "{0} paigaldatud — {1}",
  /* 120 */ "{0} paigaldatud ja valmis",
  /* 121 */ "{0} paigaldatud, {1} nurjus — vaadake logi",
  /* 122 */ "{0} taastatud",
  /* 123 */ "{0} eemaldatud",
  /* 124 */ "{0} / {1}",
  /* 125 */ "{0} on kettal, kuid ükski paigaldatud tuum neid ei ava.",
  /* 126 */ "võtke see {0} pealt, seejärel „Sirvi…“",
  /* 127 */ "alla laadida",
  /* 128 */ "puudub, pole kohustuslik",
  /* 129 */ "Luba",
  /* 130 */ "Pehme",
  /* 131 */ "lisamine ei õnnestunud — {0}",
  /* 132 */ "Sobita",
  /* 133 */ "Merevaik",
  /* 134 */ "Kiltkivi",
  /* 135 */ "seiskus — {0}",
  /* 136 */ "eelmisel korral järsk seiskumine — {0}",
  /* 137 */ "puudub",
  /* 138 */ "ühtki tuuma ei tulnud tagasi, kuigi {0} olid teada — eelmine nimekiri jäeti alles",
  /* 139 */ "emulaatoreid pole",
  /* 140 */ "Ühtki emulaatorit pole paigaldatud",
  /* 141 */ "Ühtki mängu ei tuntud ära",
  /* 142 */ "Tulemusi pole",
  /* 143 */ "pole ühtegi",
  /* 144 */ "mängukogu on loetamatu — {0}",
  /* 145 */ "ühendatud",
  /* 146 */ "ekraanipilt",
  /* 147 */ "Muuda kaanepilti…",
  /* 148 */ "Muuda…",
  /* 149 */ "Iga piksel üheksaks",
  /* 150 */ "Iga piksel neljaks: terav, moonutusteta",
  /* 151 */ "Iga piksel kuueteistkümneks — suurtele ekraanidele",
  /* 152 */ "Laadi",
  /* 153 */ "Vali kaanepilt…",
  /* 154 */ "valige kõigepealt mängukogust mäng",
  /* 155 */ "tuum: {0}",
  /* 156 */ "tuum pole paigaldatud",
  /* 157 */ "Paigaldatud tuumad",
  /* 158 */ "libretro tuumad",
  /* 159 */ "Kõrge kontrast",
  /* 160 */ "natiivne kest: {0}",
  /* 161 */ "mahalaadimine jäi poolikuks — {0}",
  /* 162 */ "avastamine: {0}",
  /* 163 */ "avastamine katkes — {0}",
  /* 164 */ "Määra ise {0} programm",
  /* 165 */ "kaust lisatud: {0}",
  /* 166 */ "kaust avatud: {0}",
  /* 167 */ "Vaikekaust",
  /* 168 */ "Lisatud kaustad",
  /* 169 */ "Esc",
  /* 170 */ "Pesa {0}",
  /* 171 */ "pesa {0} — {1}",
  /* 172 */ "Selle kausta jaoks kasutatav emulaator",
  /* 173 */ "välised emulaatorid",
  /* 174 */ "pooleli",
  /* 175 */ "paigas",
  /* 176 */ "salvestamine ei õnnestunud — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi saab need libretro ametlikust sepikojast alla laadida. Valige konsoolid, mis teid huvitavad.",
  /* 179 */ "EvaChi jäi seisma mängu „{0}“ käivitades, emulaatoriga {1}.",
  /* 180 */ "EvaChi jäi seisma emulaatoriga {0}.",
  /* 181 */ "external_systems → {0} kirja pandud emulaatorit",
  /* 182 */ "Lemmik",
  /* 183 */ "Lemmikud",
  /* 184 */ "süsteemifailid loetamatud — {0}",
  /* 185 */ "Nooled",
  /* 186 */ "Game Boy",
  /* 187 */ "Ruudustik",
  /* 188 */ "paigaldatud konsoolidel on puudu {0}",
  /* 189 */ "paigaldus lõpetatud: {0}",
  /* 190 */ "Paigaldamine…",
  /* 191 */ "paigaldatud",
  /* 192 */ "EvaChi paigaldatud",
  /* 193 */ "Paigalda",
  /* 194 */ "interpretaator: {0}",
  /* 195 */ "paigaldatud tuumade pärimine…",
  /* 196 */ "Käivita",
  /* 197 */ "Käivita valitud mäng",
  /* 198 */ "Lavendel",
  /* 199 */ "Konsoolid reas, mängud veerus, laineline taust. Nagu kodukonsoolil.",
  /* 200 */ "Servad on sulatatud — lähemal vanale telerile",
  /* 201 */ "Suured kaanepildid, sirvimine puldiga. Mõeldud diivanile.",
  /* 202 */ "Pikslid jäävad kandiliseks, nagu algsel masinal",
  /* 203 */ "puldi seosed lähtestatud algseks",
  /* 204 */ "list_cores → {0} teadaantud tuuma",
  /* 205 */ "Loend",
  /* 206 */ "tuumade loend pole saadaval — {0}",
  /* 207 */ "emulaatorite loend pole saadaval — {0}",
  /* 208 */ "Mängupult",
  /* 209 */ "pult: {0}",
  /* 210 */ "Mängupult: {0}",
  /* 211 */ "pult lahti ühendatud",
  /* 212 */ "PUUDUB",
  /* 213 */ "Piparmünt",
  /* 214 */ "Animeeritud menüü",
  /* 215 */ "Uuenda",
  /* 216 */ "Lisa lemmikutesse",
  /* 217 */ "kõrvale pandud: {0} · {1}",
  /* 218 */ "vähem kui minut",
  /* 219 */ "Terav",
  /* 220 */ "nimi, programm ja laiendid on kõik vajalikud",
  /* 221 */ "EI",
  /* 222 */ "pole sellesse masinasse paigaldatud",
  /* 223 */ "Roosa öö",
  /* 224 */ "Ookean",
  /* 225 */ "või",
  /* 226 */ "jah",
  /* 227 */ "avamine ei õnnestunud — {0}",
  /* 228 */ "veebileht: saadaval on ainult sisemised tuumad, mängukoguta",
  /* 229 */ "Paber",
  /* 230 */ "vaikimisi",
  /* 231 */ "Liikumine ruudustikus ja animeeritud menüüs",
  /* 232 */ "täisekraanist keelduti — {0}",
  /* 233 */ "vajutage puldil soovitud nuppu",
  /* 234 */ "vajutage mõnd klahvi…",
  /* 235 */ "korrastus: {0} · {1}",
  /* 236 */ "korrastamine ei õnnestunud — {0}",
  /* 237 */ "emulaatorite otsimine katkes — {0}",
  /* 238 */ "Akna sulgemine",
  /* 239 */ "lähtestamine ei õnnestunud — {0}",
  /* 240 */ "Täidab akna, hoides proportsioone",
  /* 241 */ "Jätka",
  /* 242 */ "Jätka sellest salvestusest — paremklõps tühjendab",
  /* 243 */ "Taasta",
  /* 244 */ "taastamine ei õnnestunud — {0}",
  /* 245 */ "Eemalda",
  /* 246 */ "Eemalda lemmikutest",
  /* 247 */ "Eemalda kaanepilt",
  /* 248 */ "eemaldamine ei õnnestunud — {0}",
  /* 249 */ "korrastada pole midagi",
  /* 250 */ "miski ei takista",
  /* 251 */ "Miski ei vasta otsingule „{0}“.",
  /* 252 */ "Roosa ja valge",
  /* 253 */ "pildita",
  /* 254 */ "Salvesta",
  /* 255 */ "Salvesta siia",
  /* 256 */ "valimine ei õnnestunud — {0}",
  /* 257 */ "Konsooli algne suurus, piksli täpsusega",
  /* 258 */ "Lõpeta",
  /* 259 */ "hele teema",
  /* 260 */ "tume teema",
  /* 261 */ "kõik on paigaldatud",
  /* 262 */ "leitud: {0}",
  /* 263 */ "Iga konsooli kohta üks paneel, tabelina. Hiirega kõige tihedam.",
  /* 264 */ "tühi",
  /* 265 */ "pange siia, nagu mängude romsetid: FinalBurn Neo otsib ainult sellest kaustast",
  /* 266 */ "lisab konsooli avaekraani",
  /* 267 */ "masina alglaadur",
  /* 268 */ "paljud mängud käivituvad ilma; konsooli menüü mitte",
  /* 269 */ "Ameerika BIOS",
  /* 270 */ "Ameerika ja Euroopa BIOS",
  /* 271 */ "Euroopa BIOS",
  /* 272 */ "Jaapani BIOS",
  /* 273 */ "dekrüpteerimisvõtmed; ilma nendeta krüpteeritud tõmmist vastu ei võeta",
  /* 274 */ "blueMSX-i jaotuspaketi Machines-kaust, Databases selle kõrval",
  /* 275 */ "sama",
  /* 276 */ "CD-mängudele hädavajalik, HuCard-kaartidele tarbetu",
  /* 277 */ "Mega-CD mängudele hädavajalik, kassettidele tarbetu",
  /* 278 */ "Kickstart 1.3; muidu langeb PUAE tagasi AROS-ile, mis on vaba, aga vähem ühilduv",
  /* 279 */ "Kickstart 3.1; vajalik AGA mängudele, mida A500 käivitada ei oska",
  /* 280 */ "melonDS emuleerib vaikimisi BIOS-t; päris oma on truum",
  /* 281 */ "mGBA saab ilma hakkama; mõni mäng nõuab seda oma avaekraani jaoks",
  /* 282 */ "konsooli püsivara",
  /* 283 */ "masina püsivara",
  /* 284 */ "Panasonic FZ-10 püsivara; just selle nime võtab Opera vaikimisi",
  /* 285 */ "melonDS muudab seda, algne jääb alles .bak-failina",
  /* 286 */ "kirjatüübid",
  /* 287 */ "konsooli sätted ja kuupäev",
  /* 288 */ "ilma selleta tuum töötab, aga ekraan jääb mustaks",
  /* 289 */ "konsooli märgitabel",
  /* 290 */ "Ameerika variant, Ühendriikide Sega CD mängudele",
  /* 291 */ "Jaapani variant, Jaapani Mega-CD mängudele",
  /* 292 */ "ekraanipilti",
  /* 293 */ "ekraanipilti",
  /* 294 */ "ekraanipilt",
  /* 295 */ "ekraanipilti",
  /* 296 */ "ekraanipilti",
  /* 297 */ "ekraanipilti",
  /* 298 */ "tuuma",
  /* 299 */ "tuuma",
  /* 300 */ "tuum",
  /* 301 */ "tuuma",
  /* 302 */ "tuuma",
  /* 303 */ "tuuma",
  /* 304 */ "emulaatorit",
  /* 305 */ "emulaatorit",
  /* 306 */ "emulaator",
  /* 307 */ "emulaatorit",
  /* 308 */ "emulaatorit",
  /* 309 */ "emulaatorit",
  /* 310 */ "faili",
  /* 311 */ "faili",
  /* 312 */ "fail",
  /* 313 */ "faili",
  /* 314 */ "faili",
  /* 315 */ "faili",
  /* 316 */ "mängu",
  /* 317 */ "mängu",
  /* 318 */ "mäng",
  /* 319 */ "mängu",
  /* 320 */ "mängu",
  /* 321 */ "mängu",
  /* 322 */ "<code>{rom}</code> asendatakse mängu teega. Ilma selleta lisatakse tee lõppu — just seda ootab enamik emulaatoreid.",
  /* 323 */ "<strong>Väljaspool mängu käib kõik puldiga:</strong> suunad liiguvad mängukogus, akendes ja menüüribal; <strong>A</strong> kinnitab, <strong>B</strong> viib tagasi, <strong>Start</strong> avab menüüriba. Mängu ajal toovad <strong>Select ja Start koos</strong> mängukogusse tagasi — kaks nuppu korraga, sest igaüht neist läheb mängus tarvis.",
  /* 324 */ "Ekraanipilte pole. Vajutage mängu ajal <strong>F12</strong> või puldil <strong>Select + Y</strong>.",
  /* 325 */ "Iga konsool vajab oma emulaatorit. EvaChi toob need libretro projekti ametlikust sepikojast <code>buildbot.libretro.com</code> ja paigaldab oma kausta. Midagi ei levitata edasi: need on autorite endi avaldatud versioonid.",
  /* 326 */ "Neli pesa mängu kohta, hoitud kettal. Rasvases kirjas pesa on see, mida kasutavad <strong>F2</strong> ja <strong>F4</strong> — ning puldil <strong>Select + L1</strong> / <strong>Select + R1</strong>. Pesa tühjendamiseks tehke sellel paremklõps.",
  /* 327 */ "Emulaator töötab EvaChiga samas aknas: kui ta kukub, viib ta EvaChi endaga kaasa, ilma ühegi teateta. Emulaatori kõrvale panek jätab selle paigaldatuks, aga lakkab seda pakkumast. Saate selle igal ajal taastada akna allservas <strong>Fail → Emulaatorid</strong> alt.",
  /* 328 */ "Üks fail mängu kohta kettal <small> CD-mäng saabub ühe <code>.cue</code>-lehena ja nii mitme <code>.bin</code>-failina, kui palju kettal radu oli. Käivitub ainult leht: kui see on olemas, on rajad peidetud. Lehe puudumisel ei peideta midagi. </small>",
  /* 329 */ "(tühi) või --fullscreen {rom}",
  /* 330 */ "Sada protsenti on konsooli enda kiirus. Sellest allpool mäng aeglustub, ülalpool kiireneb — ja heli tuleb kaasa, madalamaks või kõrgemaks. Puldil viivad vasak ja parem ühelt astmelt järgmisele. Ainult sisemised tuumad: väline emulaator hoiab oma kiirust.",
  /* 331 */ "Viis konsooli korraga",
  /* 332 */ "Suunanupud",
  /* 333 */ "Ühelt algustähelt järgmisele",
  /* 334 */ "Animeeritud menüüs viis mängu korraga",
  /* 335 */ "Mängu kiirus",
  /* 336 */ "Loobu",
  /* 337 */ "Lohista raami või tõmba selle nurgast. Nooleklahvid nihutavad raami, Shiftiga muudad selle suuremaks või väiksemaks. Kui raam ulatub pildist välja, lisanduvad läbipaistvad ribad: nii saad liiga kitsa kaanepildi kaugemale tõmmata. Puldil liigutavad suunanupud ja päästikud muudavad suurust.",
  /* 338 */ "Kärbi",
  /* 339 */ "Kärbi kaanepilti",
  /* 340 */ "Kogu pilt",
  /* 341 */ "{0} — kaanepilt kärbitud",
  /* 342 */ "{0} — pole kaanepilti, mida kärpida",
  /* 343 */ "loetamatu kaanepilt — {0}",
  /* 344 */ "kärpimine ebaõnnestus — {0}",
  /* 345 */ "Kärbi kaanepilti…",
];
