/**
 * Basque — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros mis en commentaire devant chaque phrase sont là pour qu'on puisse
 * le vérifier à l'œil.
 */

export const eu: readonly string[] = [
  /* 1 */ "Kontrolagailuarekin",
  /* 2 */ "A abiarazi · X gogokoa · Y moztu · L1/R1 kontsolak · L2/R2 letra · B atzera",
  /* 3 */ "EvaChi-ri buruz",
  /* 4 */ "Honi buruz…",
  /* 5 */ "Laster: izpi-hodiaren iragazkiak, lauki-sarea, eskaneo-lerroak. Lekua prest dago, iragazkiak hona etorriko dira.",
  /* 6 */ "Eguneratu liburutegia",
  /* 7 */ "Ikusi",
  /* 8 */ "Erakutsi jokoen azalak",
  /* 9 */ "Laguntza",
  /* 10 */ "Gehitu jokoen karpeta…",
  /* 11 */ "Gehitu karpeta…",
  /* 12 */ "Sakatu botoi bat aginte-makilan: dagokion agindua piztuko da. Bat aldatzeko, egin klik beheko laukian eta sakatu nahi duzun botoia. Orduan botoiak jabez aldatzen du: bi agindu botoi berean matxura baten itxura izango luke.",
  /* 13 */ "Argumentuak",
  /* 14 */ "Teklatuarekin",
  /* 15 */ "Jokorik ez",
  /* 16 */ "Ez da kontrolagailurik atzeman.",
  /* 17 */ "Liburutegia",
  /* 18 */ "Hautaketa-soinuak kontrolagailuan",
  /* 19 */ "Kontsola batzuk ez dira abiatzen jatorrizko firmwarerik gabe. EvaChi-k ezin dizu eman: copyright-dun kodea da, norberak duen makinatik kopiatzen dena. Baina esaten dizu zein falta den, zer izenekin eta non utzi behar duzun.",
  /* 20 */ "Kontsola hauek ez dute libretro nukleorik: haien emulagailua aparteko programa bat da, EvaChi-k bere etxean instalatu eta zuzenean jokoan barrena abiarazten duena — bere menutik pasatu gabe. Jokoak, gakoak eta sistema-fitxategiak zure gain daude.",
  /* 21 */ "Ezarpen hauek barneko nukleoei baino ez diete eragiten. Kanpoko emulagailu batek bereak ditu, eta EvaChi ez da haietan sartzen.",
  /* 22 */ "Hauek ez dira gehiago eskaintzen: ez dute galderari erantzun, edo EvaChi erorarazi dute. Berrezartzeak ez ditu berriro instalatzen — zerrendara itzultzen ditu, besterik ez.",
  /* 23 */ "Kargatu egoera…",
  /* 24 */ "Barneko nukleoak soilik. Egin klik lasterbide batean eta sakatu nahi duzun tekla edo botoia; kontrolagailuan bi botoi batera hartzen dira, bakoitza jokoan erabiltzen baita jada.",
  /* 25 */ "Kontrolak",
  /* 26 */ "Kontrolak…",
  /* 27 */ "Azken kontsolak",
  /* 28 */ "Adierazi beste emulagailu bat",
  /* 29 */ "Norabideak / ezkerreko palanka",
  /* 30 */ "Jokoen karpetak",
  /* 31 */ "Baztertu emulagailu hau",
  /* 32 */ "libretro proiektuaren iruditxo-zerbitzaritik datoz, eskatu ahala. Desmarkatuta, liburutegiak ez dio ezer eskatzen sareari.",
  /* 33 */ "Gordetzeko tokiak",
  /* 34 */ "Tokiak…",
  /* 35 */ "Emulagailuak",
  /* 36 */ "Baztertutako emulagailuak",
  /* 37 */ "Kanpoko emulagailuak",
  /* 38 */ "Kanpoko emulagailuak…",
  /* 39 */ "Emulagailuak…",
  /* 40 */ "Emulazioa",
  /* 41 */ "Jokoan zehar, liburutegira itzultzeko — bi botoi aldi berean, bakoitza jokoan erabiltzen baita",
  /* 42 */ "Gorde",
  /* 43 */ "Luzapenak",
  /* 44 */ "Itxi",
  /* 45 */ "Fitxategia",
  /* 46 */ "Norberak instalatu beharreko sistema-fitxategiak",
  /* 47 */ "Galeria",
  /* 48 */ "Kudeatu karpetak…",
  /* 49 */ "Grafikoak",
  /* 50 */ "Grafikoak…",
  /* 51 */ "Adierazi zure jokoak dauden karpeta.",
  /* 52 */ "Instalazioa",
  /* 53 */ "Instalatu hautatutakoak",
  /* 54 */ "Instalatu emulagailuak…",
  /* 55 */ "Interpretatzailea",
  /* 56 */ "Ez duzu non jakin beharrik: erakutsi dena pilatuta dagoen karpeta — BIOSak, gakoak, firmwareak, artxiboak, azpikarpetak barne — eta EvaChi-k fitxategi bakoitza bere tokira eramango du, bai nukleoentzat, bai emulagailu autonomoentzat. Inork eskatzen ez duena ez da mugitzen.",
  /* 57 */ "Azalak",
  /* 58 */ "Egunkaria",
  /* 59 */ "Egunkaria…",
  /* 60 */ "Aurreko aldia gaizki bukatu zen",
  /* 61 */ "Abiarazi jokoa, berretsi",
  /* 62 */ "Hizkuntza",
  /* 63 */ "Hautua saio batetik bestera gordetzen da. Bakoitza irakurgarria dela egiaztatu da: testuak kontraste nahikoa gordetzen du nonahi bere hondoaren gainean.",
  /* 64 */ "Mantendu",
  /* 65 */ "Beheko emulagailuak konfiguratuta daude jada — argumentuak eta formatuak barne. EvaChi-k zure diskoan bilatzen ditu; ez ditu instalatzen.",
  /* 66 */ "Jatorrizko loturak",
  /* 67 */ "Leuntzea",
  /* 68 */ "Jarri jokoa gogokoetan, edo kendu handik",
  /* 69 */ "Menu animatuen musika",
  /* 70 */ "Izena",
  /* 71 */ "Ireki menu-barra",
  /* 72 */ "Ireki karpeta",
  /* 73 */ "Ireki karpeta…",
  /* 74 */ "Ireki joko bat…",
  /* 75 */ "fotogramako",
  /* 76 */ "Nukleoaren ezarpenak",
  /* 77 */ "Nukleoaren ezarpenak…",
  /* 78 */ "Liburutegian, leihoetan eta menu-barran ibili",
  /* 79 */ "Arakatu…",
  /* 80 */ "Pausatu",
  /* 81 */ "Pantaila osoa",
  /* 82 */ "libretro nukleorik gabeko kontsolentzat. EvaChi-k programa abiarazten du jokoa argumentu gisa emanda: emulagailua zuzenean partidan sartzen da, bere menutik pasatu gabe.",
  /* 83 */ "Hartu pantaila-argazkia",
  /* 84 */ "Aurkezpena",
  /* 85 */ "Prest",
  /* 86 */ "Programa",
  /* 87 */ "Akorde luze batzuk eta noizbehinkako notak, grabatu beharrean unean bertan sortuak: doinua ez da inoiz leku berera itzultzen. Bere kabuz isiltzen da joko bat abiatu bezain laster.",
  /* 88 */ "Antolatu karpeta bat…",
  /* 89 */ "Hustu",
  /* 90 */ "Bilatu joko bat…",
  /* 91 */ "Berrezarri",
  /* 92 */ "Liburutegira itzuli",
  /* 93 */ "Atzera egin, itxi",
  /* 94 */ "Gordetze azkarra",
  /* 95 */ "Gorde egoera…",
  /* 96 */ "Shaderrak",
  /* 97 */ "Soinua",
  /* 98 */ "Start",
  /* 99 */ "Irudiaren tamaina",
  /* 100 */ "Gaiak",
  /* 101 */ "Gaiak…",
  /* 102 */ "Fitxategi bakarra…",
  /* 103 */ "Klask labur bat jokoz aldatzean, beste bat abiaraztean. Kontrolagailuan soilik: saguarekin eta teklatuarekin keinua bera sumatzen da jada.",
  /* 104 */ "Abiadura",
  /* 105 */ "Ikusi pantaila-argazkiak…",
  /* 106 */ "Batzuk bakarrik instala ditzakezu — emulagailua instalatuta duten kontsolak baino ez dira liburutegian agertzen.",
  /* 107 */ "{0} — kargatuta",
  /* 108 */ "{0} — eskuineko klika hustzeko",
  /* 109 */ "{0} — gogokoetan jarrita",
  /* 110 */ "{0} — berrezarrita",
  /* 111 */ "{0} — gogokoetatik kenduta",
  /* 112 */ "{0} — deskargatzen…",
  /* 113 */ "{0}: huts egin du, ikusi egunkaria",
  /* 114 */ "{0} eskuragarri",
  /* 115 */ "{0} gordeta",
  /* 116 */ "{0} kanpoko emulagailua da: abiarazi egiten da, ez da barnean hartzen",
  /* 117 */ "{0} irudi/s",
  /* 118 */ "{0} instalatuta",
  /* 119 */ "{0} instalatuta — {1}",
  /* 120 */ "{0} instalatuta eta prest",
  /* 121 */ "{0} instalatuta, {1} hutsegite — ikusi egunkaria",
  /* 122 */ "{0} leheneratuta",
  /* 123 */ "{0} kenduta",
  /* 124 */ "{1}(e)tik {0}",
  /* 125 */ "{0} diskoan dago, baina instalatutako nukleorik ez du irekitzen.",
  /* 126 */ "{0}(e)tik hartzekoa, gero « Arakatu… »",
  /* 127 */ "deskargatzeko",
  /* 128 */ "ez dago, aukerakoa",
  /* 129 */ "Gaitu",
  /* 130 */ "Leuna",
  /* 131 */ "ezin izan da gehitu — {0}",
  /* 132 */ "Doitu",
  /* 133 */ "Anbarra",
  /* 134 */ "Arbela",
  /* 135 */ "gelditu — {0}",
  /* 136 */ "ustekabeko gelditzea aurreko aldian — {0}",
  /* 137 */ "bat ere ez",
  /* 138 */ "ez du nukleorik itzuli, {0} ezagunak zirelarik — aurreko zerrenda gorde da",
  /* 139 */ "emulagailurik ez",
  /* 140 */ "Ez dago emulagailurik instalatuta",
  /* 141 */ "Ez da jokorik ezagutu",
  /* 142 */ "Emaitzarik ez",
  /* 143 */ "bat ere ez",
  /* 144 */ "liburutegia irakurtezina — {0}",
  /* 145 */ "konektatuta",
  /* 146 */ "pantaila-argazkia",
  /* 147 */ "Aldatu azala…",
  /* 148 */ "Aldatu…",
  /* 149 */ "Pixel bakoitza bederatzitan",
  /* 150 */ "Pixel bakoitza lautan: garbia, deformaziorik gabe",
  /* 151 */ "Pixel bakoitza hamaseitan — pantaila handietarako",
  /* 152 */ "Kargatu",
  /* 153 */ "Hautatu azal bat…",
  /* 154 */ "hautatu lehenik joko bat liburutegian",
  /* 155 */ "nukleoa: {0}",
  /* 156 */ "nukleoa ez dago instalatuta",
  /* 157 */ "Instalatutako nukleoak",
  /* 158 */ "libretro nukleoak",
  /* 159 */ "Kontraste handia",
  /* 160 */ "oskol natiboa: {0}",
  /* 161 */ "memoriatik hustea osatu gabe — {0}",
  /* 162 */ "aurkikuntza: {0}",
  /* 163 */ "aurkikuntza etenda — {0}",
  /* 164 */ "Zeuk adierazi {0}(r)en programa",
  /* 165 */ "karpeta gehituta: {0}",
  /* 166 */ "karpeta irekita: {0}",
  /* 167 */ "Karpeta lehenetsia",
  /* 168 */ "Gehitutako karpetak",
  /* 169 */ "Ihes",
  /* 170 */ "{0}. tokia",
  /* 171 */ "{0}. tokia — {1}",
  /* 172 */ "Karpeta honetarako erabiltzen den emulagailua",
  /* 173 */ "kanpoko emulagailuak",
  /* 174 */ "abian",
  /* 175 */ "bere tokian",
  /* 176 */ "ezin izan da gorde — {0}",
  /* 177 */ "Sartu",
  /* 178 */ "EvaChi-k libretro-ren forja ofizialetik deskarga ditzake. Hautatu interesatzen zaizkizun kontsolak.",
  /* 179 */ "EvaChi gelditu egin da « {0} » abiarazten ari zela, {1} emulagailuarekin.",
  /* 180 */ "EvaChi gelditu egin da, {0} emulagailuarekin.",
  /* 181 */ "external_systems → {0} emulagailu adierazita",
  /* 182 */ "Gogokoa",
  /* 183 */ "Gogokoak",
  /* 184 */ "sistema-fitxategiak irakurtezinak — {0}",
  /* 185 */ "Geziak",
  /* 186 */ "Game Boy",
  /* 187 */ "Sareta",
  /* 188 */ "instalatutako kontsola batzuei {0} falta zaizkie",
  /* 189 */ "instalazioa bukatuta: {0}",
  /* 190 */ "Instalatzen…",
  /* 191 */ "instalatuta",
  /* 192 */ "EvaChi-k instalatuta",
  /* 193 */ "Instalatu",
  /* 194 */ "interpretatzailea: {0}",
  /* 195 */ "instalatutako nukleoak galdekatzen…",
  /* 196 */ "Abiarazi",
  /* 197 */ "Abiarazi hautatutako jokoa",
  /* 198 */ "Izpilikua",
  /* 199 */ "Kontsolak errenkadan, jokoak zutabean, hondo uhindua. Egongelako kontsolen erara.",
  /* 200 */ "Ertzak lausotuta — telebista zahar baten antzekoago",
  /* 201 */ "Azalak handi-handi, kontrolagailuz arakatuta. Sofarako pentsatua.",
  /* 202 */ "Pixelak koadratu mantentzen dira, jatorrizko makinan bezala",
  /* 203 */ "kontrolagailuaren loturak jatorrira itzulita",
  /* 204 */ "list_cores → {0} nukleo iragarrita",
  /* 205 */ "Zerrenda",
  /* 206 */ "nukleoen zerrenda eskuraezina — {0}",
  /* 207 */ "emulagailuen zerrenda eskuraezina — {0}",
  /* 208 */ "Kontrolagailua",
  /* 209 */ "kontrolagailua: {0}",
  /* 210 */ "Kontrolagailua: {0}",
  /* 211 */ "kontrolagailua deskonektatuta",
  /* 212 */ "FALTA",
  /* 213 */ "Menda",
  /* 214 */ "Menu animatua",
  /* 215 */ "Eguneratu",
  /* 216 */ "Jarri gogokoetan",
  /* 217 */ "baztertuta: {0} · {1}",
  /* 218 */ "minutu bat baino gutxiago",
  /* 219 */ "Zorrotza",
  /* 220 */ "izena, programa eta luzapenak, hirurak behar dira",
  /* 221 */ "EZ",
  /* 222 */ "ez dago makina honetan instalatuta",
  /* 223 */ "Gau arrosa",
  /* 224 */ "Ozeanoa",
  /* 225 */ "edo",
  /* 226 */ "bai",
  /* 227 */ "ezin izan da ireki — {0}",
  /* 228 */ "web orria: barneko nukleoak baino ez daude eskuragarri, liburutegirik gabe",
  /* 229 */ "Papera",
  /* 230 */ "lehenetsia",
  /* 231 */ "Saretan eta menu animatuetan ibili",
  /* 232 */ "pantaila osoa ukatuta — {0}",
  /* 233 */ "sakatu nahi duzun botoia kontrolagailuan",
  /* 234 */ "sakatu tekla bat…",
  /* 235 */ "antolaketa: {0} · {1}",
  /* 236 */ "ezin izan da antolatu — {0}",
  /* 237 */ "emulagailuen bilaketa etenda — {0}",
  /* 238 */ "Leiho bat itxi",
  /* 239 */ "ezin izan da berrezarri — {0}",
  /* 240 */ "Leihoa betetzen du proportzioak gordez",
  /* 241 */ "Jarraitu",
  /* 242 */ "Ordeztu",
  /* 243 */ "Leheneratu",
  /* 244 */ "ezin izan da leheneratu — {0}",
  /* 245 */ "Kendu",
  /* 246 */ "Kendu gogokoetatik",
  /* 247 */ "Kendu azala",
  /* 248 */ "ezin izan da kendu — {0}",
  /* 249 */ "ez dago zer antolaturik",
  /* 250 */ "ez dago oztoporik",
  /* 251 */ "Ez dago « {0} »(r)ekin bat datorren ezer.",
  /* 252 */ "Arrosa eta zuria",
  /* 253 */ "irudirik gabe",
  /* 254 */ "Gorde",
  /* 255 */ "Gorde hemen",
  /* 256 */ "ezin izan da hautatu — {0}",
  /* 257 */ "Kontsolaren jatorrizko tamaina, pixelez pixel",
  /* 258 */ "Bota",
  /* 259 */ "gai argia",
  /* 260 */ "gai iluna",
  /* 261 */ "dena instalatuta dago",
  /* 262 */ "aurkituta: {0}",
  /* 263 */ "Atal bat kontsola bakoitzeko, taula gisa. Saguarekin trinkoena.",
  /* 264 */ "hutsik",
  /* 265 */ "hemen utzi behar da, jokoen romset-ak bezala: FinalBurn Neo-k karpeta honetan bakarrik bilatzen du",
  /* 266 */ "kontsolaren hasierako pantaila gehitzen du",
  /* 267 */ "makinaren abioa",
  /* 268 */ "joko asko hura gabe abiatzen dira; kontsolaren menua ez",
  /* 269 */ "BIOS amerikarra",
  /* 270 */ "BIOS amerikarra eta europarra",
  /* 271 */ "BIOS europarra",
  /* 272 */ "BIOS japoniarra",
  /* 273 */ "deszifratze-gakoak; haiek gabe zifratutako kopia bat ez da onartzen",
  /* 274 */ "blueMSX banaketaren makinen karpeta, Databases ondoan duela",
  /* 275 */ "berdin",
  /* 276 */ "ezinbestekoa CD jokoetarako, alferrikakoa HuCard txarteletarako",
  /* 277 */ "ezinbestekoa Mega-CD jokoetarako, alferrikakoa kartutxoetarako",
  /* 278 */ "Kickstart 1.3; bestela PUAE AROSera jotzen du, librea baina gutxiago bateragarria",
  /* 279 */ "Kickstart 3.1; AGA jokoetarako beharrezkoa, A500ek ezin baititu abiarazi",
  /* 280 */ "melonDS-ek BIOSa emulatzen du lehenespenez; egiazkoa fidelagoa da",
  /* 281 */ "mGBA-k ez du behar; joko batzuek eskatzen dute hasierako pantailarako",
  /* 282 */ "kontsolaren firmwarea",
  /* 283 */ "makinaren firmwarea",
  /* 284 */ "Panasonic FZ-10 firmwarea; izen hori hartzen du Operak lehenespenez",
  /* 285 */ "melonDS-ek aldatzen du, jatorrizkoa .bak gisa gordez",
  /* 286 */ "letra-tipoak",
  /* 287 */ "kontsolaren ezarpenak eta data",
  /* 288 */ "hura gabe nukleoa badabil, baina pantaila beltz geratzen da",
  /* 289 */ "kontsolaren karaktere-taula",
  /* 290 */ "aldaera amerikarra, Estatu Batuetako Sega CD jokoetarako",
  /* 291 */ "aldaera japoniarra, Japoniako Mega-CD jokoetarako",
  /* 292 */ "pantaila-argazki",
  /* 293 */ "pantaila-argazki",
  /* 294 */ "pantaila-argazki",
  /* 295 */ "pantaila-argazki",
  /* 296 */ "pantaila-argazki",
  /* 297 */ "pantaila-argazki",
  /* 298 */ "nukleo",
  /* 299 */ "nukleo",
  /* 300 */ "nukleo",
  /* 301 */ "nukleo",
  /* 302 */ "nukleo",
  /* 303 */ "nukleo",
  /* 304 */ "emulagailu",
  /* 305 */ "emulagailu",
  /* 306 */ "emulagailu",
  /* 307 */ "emulagailu",
  /* 308 */ "emulagailu",
  /* 309 */ "emulagailu",
  /* 310 */ "fitxategi",
  /* 311 */ "fitxategi",
  /* 312 */ "fitxategi",
  /* 313 */ "fitxategi",
  /* 314 */ "fitxategi",
  /* 315 */ "fitxategi",
  /* 316 */ "joko",
  /* 317 */ "joko",
  /* 318 */ "joko",
  /* 319 */ "joko",
  /* 320 */ "joko",
  /* 321 */ "joko",
  /* 322 */ "<code>{rom}</code> jokoaren bide-izenaz ordezkatuko da. Hura gabe, bide-izena amaieran eransten da — emulagailu gehienek hori espero dute.",
  /* 323 */ "<strong>Jokotik kanpo, dena kontrolagailuaz egiten da:</strong> norabideek liburutegian, leihoetan eta menu-barran ibiltzeko balio dute; <strong>A</strong> botoiak berresten du, <strong>B</strong> botoiak atzera egiten du, <strong>Start</strong> botoiak menu-barra irekitzen du. Jokoan zehar, <strong>Select eta Start batera</strong> sakatuta liburutegira itzultzen zara — bi botoi aldi berean, bakoitza jokoan erabiltzen baita.",
  /* 324 */ "Pantaila-argazkirik ez. Sakatu <strong>F12</strong> jokoan zehar, edo <strong>Select + Y</strong> kontrolagailuan.",
  /* 325 */ "Kontsola bakoitzak bere emulagailua behar du. EvaChi-k libretro proiektuaren forja ofizialean bilatzen ditu, <code>buildbot.libretro.com</code> gunean, eta bere karpetan instalatzen ditu. Ez da ezer birbanatzen: egileek argitaratutako bertsioak dira.",
  /* 326 */ "Lau toki joko bakoitzeko, diskoan gordeta. Keinu bakoitza tokiaren azpian idatzita dago, eta ordezteak edo husteak berrespena eskatzen du. <strong>F2</strong> eta <strong>F4</strong> — eta <strong>Select + L1</strong> / <strong>Select + R1</strong> aginte-makilan — zuzenean doaz lodiz dagoen tokira, ezer galdetu gabe.",
  /* 327 */ "Emulagailu bakoitza bere prozesuan dabil: erortzen denean, EvaChi-k ikusi egiten du eta liburutegira itzultzen da. Abian den partida galdu egiten da, eta baliteke jokoaren gordetzea idatzi gabe gelditu izana. Emulagailu hau baztertzeak instalatuta uzten du, baina ez du gehiago eskaintzen. Edonoiz leheneratu ahal izango duzu <strong>Fitxategia → Emulagailuak</strong> atalean, leihoaren behealdean.",
  /* 328 */ "Fitxategi bakarra joko bakoitzeko diskoan <small> CDko joko bat <code>.cue</code> orri batean eta diskoak pista adina <code>.bin</code> fitxategitan iristen da. Orria bakarrik abiarazten da: pistak ezkutatuta gelditzen dira hura dagoenean. Orririk gabe, ez da ezer ezkutatzen. </small>",
  /* 329 */ "(hutsik) edo --fullscreen {rom}",
  /* 330 */ "Ehuneko ehun kontsolaren beraren abiadura da. Hortik behera jokoa mantsotzen da, gorago azkartzen — eta soinuak jarraitzen dio, baxuagoa edo altuagoa. Kontrolagailuan, ezkerrak eta eskuinak maila batetik hurrengora eramaten dute. Barneko nukleoetan bakarrik: kanpoko emuladoreak berea gordetzen du.",
  /* 331 */ "Bost kontsola aldi berean",
  /* 332 */ "Norabide-gurutzea",
  /* 333 */ "Hasierako letra batetik hurrengora",
  /* 334 */ "Menu animatuetan, bost joko aldi berean",
  /* 335 */ "Jokoaren abiadura",
  /* 336 */ "Utzi",
  /* 337 */ "Arrastatu markoa, edo tira izkina batetik. Gezi-teklek mugitu egiten dute; Maius sakatuta, handitu edo txikitu. Markoa iruditik kanpo ateratzen bada, zerrenda gardenak gehitzen zaizkio: horrela urruntzen da azal estuegi bat. Agintean, norabideek mugitzen dute eta gatiluek tamaina doitzen dute.",
  /* 338 */ "Moztu",
  /* 339 */ "Moztu azala",
  /* 340 */ "Irudi osoa",
  /* 341 */ "{0} — azala moztuta",
  /* 342 */ "{0} — ez dago azalik mozteko",
  /* 343 */ "azala ezin irakurri — {0}",
  /* 344 */ "ezin izan da moztu — {0}",
  /* 345 */ "Moztu azala…",
  /* 346 */ "Aurreratze azkarra, bi palankak sakatuta dauden bitartean",
  /* 347 */ "{0} baztertuta",
  /* 348 */ "{0} emulagailua gelditu egin da « {1} » jokoan ari zela.",
  /* 349 */ "{0} emulagailua gelditu egin da.",
  /* 350 */ "Emulagailua gelditu egin da",
  /* 351 */ "ezin izan da baztertu — {0}",
  /* 352 */ "hemen utzi: {0}",
  /* 353 */ "sistema-fitxategi bat falta da: {0}",
  /* 354 */ "Kredituak",
  /* 355 */ "Lizentzia ez komertziala, lan hau berrerabili aurretik jakin beharrekoa: {0}.",
  /* 356 */ "EvaChi-k ez du emulagailurik idazten: ostatu ematen die. Bakoitza berez proiektu libre oso bat da, beste batzuek idatzia, eta EvaChi-k bere egileengana jotzen du bila, eskatu ahala — haien kodearen lerro bakar bat ere ez dago hemen kopiatuta, byte bakar bat ere ez da birbanatzen. Beheko izenak eta lizentziak proiektu bakoitzak berak aitortzen dituenak dira.",
  /* 357 */ "Karrusela",
  /* 358 */ "Azalak aurrez aurre, kontsolak pilan, gora doan hautsa. Erakusmahai baten gisara.",
  /* 359 */ "Interfazearen berdina",
  /* 360 */ "Interfazearen hizkuntza",
  /* 361 */ "Jokoen hizkuntza",
  /* 362 */ "Jokoen hizkuntza: {0}. Hurrengo abiaraztetik aurrera balioko du.",
  /* 363 */ "Atzera",
  /* 364 */ "Bilatu",
  /* 365 */ "Bilatu fitxak",
  /* 366 */ "Bilatu balio bat",
  /* 367 */ "Desberdina",
  /* 368 */ "Berdina",
  /* 369 */ "Zabalera",
  /* 370 */ "libretro proiektuak iruzur-fitxak argitaratzen ditu, bat joko bakoitzeko. EvaChik zure jokoarekin zehazki bat datozenak baino ez ditu gordetzen — izenburu bera, eskualde bera, berrikuspen bera — eta nahiago du ezer ez proposatu gutxi gorabeherako zerbait baino: beste bertsio baterako idatzitako kodeek ez dute alboan idazten, beste leku batean baizik.",
  /* 371 */ "Iruzurrak",
  /* 372 */ "Gutxiago",
  /* 373 */ "Iruzur-panela",
  /* 374 */ "Gehiago",
  /* 375 */ "Hasi berriro",
  /* 376 */ "Iruzurrak",
  /* 377 */ "Iruzurrak…",
  /* 378 */ "Balioa",
  /* 379 */ "Berdin",
  /* 380 */ "{0} helbide posible",
  /* 381 */ "{0} fitxa jarrita, {1} kenduta",
  /* 382 */ "{1} jokotik {0}(e)k fitxa dute",
  /* 383 */ "{0} byte memoria",
  /* 384 */ "{0} balio baztertuta: joko honen memoriatik kanpo",
  /* 385 */ "Ez dago fitxarik joko honetarako. Emulazioa menuko « Iruzurrak… » panelak bat bilatzen du; bestela, balio-bilaketak edozein jokotan funtzionatzen du.",
  /* 386 */ "Izoztuta",
  /* 387 */ "Izoztu",
  /* 388 */ "Jokatu pixka bat eta esan gero balioak zer egin duen.",
  /* 389 */ "Partida albo batera gorde da lehen iruzurraren aurretik.",
  /* 390 */ "Bilatzen…",
  /* 391 */ "« drop u'r rom » karpetan uzten dena bere luzapenak adierazten duen kontsolara doa. Kontsola bat baino gehiagok luzapen bera partekatzen dutenean — diskoen irudiak — EvaChik galdetu egiten du, asmatzen saiatu ordez.",
  /* 392 */ "Berrespena",
  /* 393 */ "Ezabatu jokoaren gordetzea…",
  /* 394 */ "Luzapena",
  /* 395 */ "Jokoak bere kontuak memorian gordetzen ditu, non esan gabe. Baztertuz aurkitzen dira: pantailan ikusten den zenbakiak zer egin duen esaten duzu, eta EvaChik gauza bera egin ez duten helbideak baztertzen ditu.",
  /* 396 */ "Bai",
  /* 397 */ "Kontsola gutxik dituzte gaurko pantaila baten proportzioak, hortik alboetako banda beltzak. Zeroan irudiak bere proportzioak gordetzen ditu; ehunean leihoa betetzen du, luzatu behar badu ere.",
  /* 398 */ "Jokoak antolatzea",
  /* 399 */ "Antolatu",
  /* 400 */ "Antolatu utzitako jokoak…",
  /* 401 */ "47 bizitza ikusten dituzu: idatzi 47 « Balioa » eremuan eta sakatu « Bilatu ». Galdu bat, idatzi 46 eta sakatu « Berdin ». Zenbakia inon idatzita ez badago, utzi « Balioa » hutsik eta esan besterik gabe « Gehiago », « Gutxiago », « Desberdina » edo « Berdina » jokoaren bi une artean. Ondoren « Izoztu » aukerak aurkitutako balioa mantentzen du. « Zabalera » zenbakiaren tamaina da: 1 255era arte, 2 handiagoetarako, 4 kontagailu handietarako.",
  /* 402 */ "{0} antolatuta",
  /* 403 */ "ez dago ezabatzeko gordetzerik",
  /* 404 */ "Botoiak",
  /* 405 */ "Liburutegian dago jada: {0}",
  /* 406 */ "{0} jokoaren gordetzea ezabatu eta hasieratik hasi nahi duzu? Abian den partida gelditu egingo da, eta jokoak idatzitakoa galdu egingo da.",
  /* 407 */ "Kakoak",
  /* 408 */ "Gorde biak",
  /* 409 */ "Utzi karpetan",
  /* 410 */ "Uzteko karpeta hutsik dago.",
  /* 411 */ "{0}. tokia ordeztu? Han gordeta dagoena galdu egingo da.",
  /* 412 */ "gordetzea ezabatuta — {0}",
  /* 413 */ "Sistema",
  /* 414 */ "{0}. tokia hustu? Han gordeta dagoena galdu egingo da.",
];
