/**
 * Le finnois — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * marques numérotées sont là pour qu'on puisse le vérifier à l'œil.
 */

export const fi: readonly string[] = [
  /* 1 */ "Ohjaimella",
  /* 2 */ "A käynnistä · X suosikki · Y rajaa · L1/R1 konsolit · L2/R2 kirjain · B takaisin",
  /* 3 */ "Tietoja EvaChista",
  /* 4 */ "Tietoja…",
  /* 5 */ "Tulossa: kuvaputkisuotimet, pikseliruudukko, juovitus. Paikka on valmis, suotimet saapuvat tänne.",
  /* 6 */ "Päivitä kirjasto",
  /* 7 */ "Näytä",
  /* 8 */ "Näytä pelien kansikuvat",
  /* 9 */ "Ohje",
  /* 10 */ "Lisää pelikansio…",
  /* 11 */ "Lisää kansio…",
  /* 12 */ "Paina ohjaimen painiketta: vastaava näppäin syttyy. Jos haluat vaihtaa jonkin, siirry uudelleenmääritykseen, napsauta muutettavaa näppäintä ja paina sitten haluamaasi painiketta.",
  /* 13 */ "Argumentit",
  /* 14 */ "Näppäimistöllä",
  /* 15 */ "Ei pelejä",
  /* 16 */ "Ohjainta ei havaittu.",
  /* 17 */ "Kirjasto",
  /* 18 */ "Valintaäänet ohjaimella",
  /* 19 */ "Jotkin konsolit eivät käynnisty ilman alkuperäistä laiteohjelmistoaan. EvaChi ei voi sitä toimittaa: se on tekijänoikeuden alaista koodia, joka kopioidaan omasta laitteesta. Se kertoo kuitenkin, mikä puuttuu, millä nimellä ja mihin se pannaan.",
  /* 20 */ "Näillä konsoleilla ei ole libretro-ydintä: niiden emulaattori on erillinen ohjelma, jonka EvaChi asentaa omaan kansioonsa ja käynnistää suoraan peliin — sen omaa valikkoa avaamatta. Pelit, avaimet ja järjestelmätiedostot jäävät sinun huoleksesi.",
  /* 21 */ "Nämä asetukset koskevat vain sisäisiä ytimiä. Ulkoisella emulaattorilla on omansa, eikä EvaChi puutu niihin.",
  /* 22 */ "Näitä ei enää tarjota: ne eivät vastanneet kyselyyn tai ne kaatoivat EvaChin. Palauttaminen ei asenna niitä uudelleen — se vain tuo ne takaisin luetteloon.",
  /* 23 */ "Lataa tila",
  /* 24 */ "Vain sisäiset ytimet. Napsauta pikanäppäintä ja paina sitten haluamaasi näppäintä tai painiketta; ohjaimella otetaan kaksi painiketta kerrallaan, sillä kukin niistä on jo pelin käytössä.",
  /* 25 */ "Ohjaus",
  /* 26 */ "Ohjaus…",
  /* 27 */ "Viimeisimmät konsolit",
  /* 28 */ "Lisää muu emulaattori",
  /* 29 */ "Suunnat / vasen sauva",
  /* 30 */ "Pelikansiot",
  /* 31 */ "Poista tämä emulaattori käytöstä",
  /* 32 */ "Ne haetaan tarvittaessa libretro-projektin kuvapalvelimelta. Kun valinta on pois, kirjasto ei pyydä verkosta enää mitään.",
  /* 33 */ "Tallennuspaikat",
  /* 34 */ "Tallennuspaikat…",
  /* 35 */ "Emulaattorit",
  /* 36 */ "Käytöstä poistetut emulaattorit",
  /* 37 */ "Ulkoiset emulaattorit",
  /* 38 */ "Ulkoiset emulaattorit…",
  /* 39 */ "Emulaattorit…",
  /* 40 */ "Emulointi",
  /* 41 */ "Pelin aikana takaisin kirjastoon — kaksi painiketta kerrallaan, sillä kumpikin on pelin käytössä",
  /* 42 */ "Tallenna",
  /* 43 */ "Tiedostopäätteet",
  /* 44 */ "Sulje",
  /* 45 */ "Tiedosto",
  /* 46 */ "Itse asennettavat järjestelmätiedostot",
  /* 47 */ "Galleria",
  /* 48 */ "Hallitse kansioita…",
  /* 49 */ "Grafiikka",
  /* 50 */ "Grafiikka…",
  /* 51 */ "Osoita kansio, jossa pelisi ovat.",
  /* 52 */ "Asennus",
  /* 53 */ "Asenna valitut",
  /* 54 */ "Asenna emulaattorit…",
  /* 55 */ "Tulkki",
  /* 56 */ "Ei tarvitse tietää minne: osoita kansio, jossa kaikki lojuu — BIOSit, avaimet, laiteohjelmistot, arkistot ja alikansiot mukaan lukien — niin EvaChi vie jokaisen tiedoston oikeaan paikkaan, niin ytimille kuin erillisille emulaattoreillekin. Mitä kukaan ei kaipaa, sitä ei siirretä.",
  /* 57 */ "Kansikuvat",
  /* 58 */ "Loki",
  /* 59 */ "Loki…",
  /* 60 */ "Edellinen kerta päättyi huonosti",
  /* 61 */ "Käynnistä peli, vahvista",
  /* 62 */ "Kieli",
  /* 63 */ "Valinta säilyy käynnistyskerrasta toiseen. Jokainen on tarkistettu luettavaksi: teksti erottuu kaikkialla riittävästi taustastaan.",
  /* 64 */ "Pidä se",
  /* 65 */ "Alla olevat emulaattorit on jo valmiiksi määritetty — argumentit ja tiedostomuodot mukaan lukien. EvaChi etsii ne levyltäsi; se ei asenna niitä.",
  /* 66 */ "Oletusmääritykset",
  /* 67 */ "Pehmennys",
  /* 68 */ "Merkitse peli suosikiksi tai poista merkintä",
  /* 69 */ "Liikkuvan valikon musiikki",
  /* 70 */ "Nimi",
  /* 71 */ "Avaa valikkorivi",
  /* 72 */ "Avaa kansio",
  /* 73 */ "Avaa kansio…",
  /* 74 */ "Avaa peli…",
  /* 75 */ "ruutua kohti",
  /* 76 */ "Ytimen asetukset",
  /* 77 */ "Ytimen asetukset…",
  /* 78 */ "Selaa kirjastoa, ikkunoita ja valikkoriviä",
  /* 79 */ "Selaa…",
  /* 80 */ "Tauko",
  /* 81 */ "Koko näyttö",
  /* 82 */ "Konsoleille, joilla ei ole libretro-ydintä. EvaChi käynnistää ohjelman peli argumenttinaan: emulaattori avautuu suoraan peliin, omaa valikkoaan avaamatta.",
  /* 83 */ "Ota kuvakaappaus",
  /* 84 */ "Näkymä",
  /* 85 */ "Valmis",
  /* 86 */ "Ohjelma",
  /* 87 */ "Muutama pitkä sointu ja hajanaisia säveliä, sävellettyinä lennossa eikä nauhoitettuina: kappale ei koskaan kulje kahdesti samaa kohtaa. Se vaimenee itsestään heti kun peli käynnistyy.",
  /* 88 */ "Järjestä kansio…",
  /* 89 */ "Määritä uudelleen…",
  /* 90 */ "Etsi peliä…",
  /* 91 */ "Nollaa",
  /* 92 */ "Takaisin kirjastoon",
  /* 93 */ "Palaa takaisin, sulje",
  /* 94 */ "Pikatallennus",
  /* 95 */ "Tallenna tila",
  /* 96 */ "Shaderit",
  /* 97 */ "Ääni",
  /* 98 */ "Start",
  /* 99 */ "Kuvan koko",
  /* 100 */ "Teemat",
  /* 101 */ "Teemat…",
  /* 102 */ "Yksi tiedosto…",
  /* 103 */ "Lyhyt naksahdus peliä vaihdettaessa, toinen sitä käynnistettäessä. Vain ohjaimella: hiirellä ja näppäimistöllä liike tuntuu jo itsessään.",
  /* 104 */ "Nopeus",
  /* 105 */ "Näytä kuvakaappaukset…",
  /* 106 */ "Voit asentaa niistä vain osan — kirjastossa näkyvät vain ne konsolit, joiden emulaattori on asennettu.",
  /* 107 */ "{0} — ladattu",
  /* 108 */ "{0} — oikea napsautus tyhjentää",
  /* 109 */ "{0} — merkitty suosikiksi",
  /* 110 */ "{0} — nollattu",
  /* 111 */ "{0} — poistettu suosikeista",
  /* 112 */ "{0} — ladataan…",
  /* 113 */ "{0}: epäonnistui, katso loki",
  /* 114 */ "{0} käytettävissä",
  /* 115 */ "{0} tallennettu",
  /* 116 */ "{0} on ulkoinen emulaattori: se käynnistetään erikseen, ei EvaChin sisällä",
  /* 117 */ "{0} k/s",
  /* 118 */ "{0} asennettu",
  /* 119 */ "{0} asennettu — {1}",
  /* 120 */ "{0} asennettu ja valmis",
  /* 121 */ "{0} asennettu, {1} epäonnistui — katso loki",
  /* 122 */ "{0} palautettu",
  /* 123 */ "{0} poistettu",
  /* 124 */ "{0} / {1}",
  /* 125 */ "{0} levyllä, mutta mikään asennettu ydin ei avaa niitä.",
  /* 126 */ "otettava laitteesta {0}, sitten ”Selaa…”",
  /* 127 */ "ladattava",
  /* 128 */ "puuttuu, valinnainen",
  /* 129 */ "Ota käyttöön",
  /* 130 */ "Pehmeä",
  /* 131 */ "lisäys ei onnistu — {0}",
  /* 132 */ "Sovita",
  /* 133 */ "Meripihka",
  /* 134 */ "Liuske",
  /* 135 */ "pysäytys — {0}",
  /* 136 */ "äkkipysähdys edellisellä kerralla — {0}",
  /* 137 */ "ei mitään",
  /* 138 */ "ei yhtään ydintä palautettu, vaikka {0} tunnettiin — edellinen luettelo säilytetty",
  /* 139 */ "ei emulaattoreita",
  /* 140 */ "Ei asennettuja emulaattoreita",
  /* 141 */ "Ei tunnistettuja pelejä",
  /* 142 */ "Ei tuloksia",
  /* 143 */ "ei mitään",
  /* 144 */ "kirjastoa ei voi lukea — {0}",
  /* 145 */ "kytketty",
  /* 146 */ "kuvakaappaus",
  /* 147 */ "Vaihda kansikuva…",
  /* 148 */ "Vaihda…",
  /* 149 */ "Jokainen pikseli yhdeksänä",
  /* 150 */ "Jokainen pikseli neljänä: terävä, vääristymättä",
  /* 151 */ "Jokainen pikseli kuutenatoista — suurille näytöille",
  /* 152 */ "Lataa",
  /* 153 */ "Valitse kansikuva…",
  /* 154 */ "valitse ensin peli kirjastosta",
  /* 155 */ "ydin: {0}",
  /* 156 */ "ydintä ei ole asennettu",
  /* 157 */ "Asennetut ytimet",
  /* 158 */ "libretro-ytimet",
  /* 159 */ "Suuri kontrasti",
  /* 160 */ "natiivikuori: {0}",
  /* 161 */ "purkaminen jäi kesken — {0}",
  /* 162 */ "kartoitus: {0}",
  /* 163 */ "kartoitus keskeytyi — {0}",
  /* 164 */ "Osoita itse, missä {0} on",
  /* 165 */ "kansio lisätty: {0}",
  /* 166 */ "kansio avattu: {0}",
  /* 167 */ "Oletuskansio",
  /* 168 */ "Lisätyt kansiot",
  /* 169 */ "Esc",
  /* 170 */ "Paikka {0}",
  /* 171 */ "paikka {0} — {1}",
  /* 172 */ "Tälle kansiolle käytettävä emulaattori",
  /* 173 */ "ulkoiset emulaattorit",
  /* 174 */ "käynnissä",
  /* 175 */ "paikallaan",
  /* 176 */ "tallennus ei onnistu — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi voi ladata ne libretron viralliselta käännöspalvelimelta. Valitse konsolit, jotka sinua kiinnostavat.",
  /* 179 */ "EvaChi pysähtyi käynnistäessään peliä ”{0}” emulaattorilla {1}.",
  /* 180 */ "EvaChi pysähtyi emulaattorilla {0}.",
  /* 181 */ "external_systems → {0} ilmoitettua emulaattoria",
  /* 182 */ "Suosikki",
  /* 183 */ "Suosikit",
  /* 184 */ "järjestelmätiedostoja ei voi lukea — {0}",
  /* 185 */ "Nuolinäppäimet",
  /* 186 */ "Game Boy",
  /* 187 */ "Ruudukko",
  /* 188 */ "asennetuilta konsoleilta puuttuu {0}",
  /* 189 */ "asennus valmis: {0}",
  /* 190 */ "Asennetaan…",
  /* 191 */ "asennettu",
  /* 192 */ "EvaChin asentama",
  /* 193 */ "Asenna",
  /* 194 */ "tulkki: {0}",
  /* 195 */ "kysellään asennettuja ytimiä…",
  /* 196 */ "Käynnistä",
  /* 197 */ "Käynnistä valittu peli",
  /* 198 */ "Laventeli",
  /* 199 */ "Konsolit rivissä, pelit sarakkeessa, aaltoileva tausta. Olohuonekonsolin tapaan.",
  /* 200 */ "Reunat sulautuvat — lähempänä vanhaa televisiota",
  /* 201 */ "Kansikuvat suurina, ohjaimella selattavina. Ajateltu sohvaa varten.",
  /* 202 */ "Pikselit pysyvät neliöinä, kuten alkuperäisessä laitteessa",
  /* 203 */ "ohjaimen määritykset palautettu oletuksiksi",
  /* 204 */ "list_cores → {0} ilmoitettua ydintä",
  /* 205 */ "Luettelo",
  /* 206 */ "ydinluetteloa ei saatavilla — {0}",
  /* 207 */ "emulaattoriluetteloa ei saatavilla — {0}",
  /* 208 */ "Ohjain",
  /* 209 */ "ohjain: {0}",
  /* 210 */ "Ohjain: {0}",
  /* 211 */ "ohjain irrotettu",
  /* 212 */ "PUUTTUU",
  /* 213 */ "Minttu",
  /* 214 */ "Liikkuva valikko",
  /* 215 */ "Päivitä",
  /* 216 */ "Lisää suosikkeihin",
  /* 217 */ "poistettu käytöstä: {0} · {1}",
  /* 218 */ "alle minuutti",
  /* 219 */ "Terävä",
  /* 220 */ "nimi, ohjelma ja tiedostopäätteet ovat kaikki tarpeen",
  /* 221 */ "EI",
  /* 222 */ "ei asennettu tähän koneeseen",
  /* 223 */ "Ruusuinen yö",
  /* 224 */ "Valtameri",
  /* 225 */ "tai",
  /* 226 */ "kyllä",
  /* 227 */ "avaaminen ei onnistu — {0}",
  /* 228 */ "verkkosivu: vain sisäiset ytimet käytettävissä, ei kirjastoa",
  /* 229 */ "Paperi",
  /* 230 */ "oletus",
  /* 231 */ "Selaa ruudukkoa ja liikkuvaa valikkoa",
  /* 232 */ "koko näyttö evätty — {0}",
  /* 233 */ "paina haluamaasi painiketta ohjaimessa",
  /* 234 */ "paina jotakin näppäintä…",
  /* 235 */ "järjestely: {0} · {1}",
  /* 236 */ "järjestely ei onnistu — {0}",
  /* 237 */ "emulaattorien etsintä keskeytyi — {0}",
  /* 238 */ "Sulje ikkuna",
  /* 239 */ "nollaus ei onnistu — {0}",
  /* 240 */ "Täyttää ikkunan kuvasuhteen säilyttäen",
  /* 241 */ "Jatka",
  /* 242 */ "Jatka tästä tallennuksesta — oikea napsautus tyhjentää",
  /* 243 */ "Palauta",
  /* 244 */ "palautus ei onnistu — {0}",
  /* 245 */ "Poista",
  /* 246 */ "Poista suosikeista",
  /* 247 */ "Poista kansikuva",
  /* 248 */ "poisto ei onnistu — {0}",
  /* 249 */ "ei järjestettävää",
  /* 250 */ "mikään ei estä",
  /* 251 */ "Mikään ei vastaa hakua ”{0}”.",
  /* 252 */ "Ruusu ja valkoinen",
  /* 253 */ "ei kuvaa",
  /* 254 */ "Tallenna",
  /* 255 */ "Tallenna tähän",
  /* 256 */ "valinta ei onnistu — {0}",
  /* 257 */ "Konsolin alkuperäinen koko, pikselilleen",
  /* 258 */ "Lopeta",
  /* 259 */ "vaalea teema",
  /* 260 */ "tumma teema",
  /* 261 */ "kaikki on asennettu",
  /* 262 */ "löytyi: {0}",
  /* 263 */ "Yksi osio konsolia kohti, taulukkona. Tihein näkymä hiirelle.",
  /* 264 */ "tyhjä",
  /* 265 */ "pantava tähän, kuten pelien romsetit: FinalBurn Neo etsii vain tästä kansiosta",
  /* 266 */ "lisää konsolin aloitusruudun",
  /* 267 */ "laitteen käynnistyskoodi",
  /* 268 */ "moni peli käynnistyy ilman; konsolin valikko ei",
  /* 269 */ "amerikkalainen BIOS",
  /* 270 */ "amerikkalainen ja eurooppalainen BIOS",
  /* 271 */ "eurooppalainen BIOS",
  /* 272 */ "japanilainen BIOS",
  /* 273 */ "salauksen purkuavaimet; ilman niitä salattua vedosta ei hyväksytä",
  /* 274 */ "blueMSX-jakelun Machines-kansio, Databases sen vierellä",
  /* 275 */ "sama",
  /* 276 */ "välttämätön CD-peleille, turha HuCard-korteille",
  /* 277 */ "välttämätön Mega-CD-peleille, turha kaseteille",
  /* 278 */ "Kickstart 1.3; muuten PUAE turvautuu AROSiin, joka on vapaa mutta huonommin yhteensopiva",
  /* 279 */ "Kickstart 3.1; tarpeen AGA-peleille, joita A500 ei osaa ajaa",
  /* 280 */ "melonDS emuloi BIOSia oletuksena; oikea on uskollisempi",
  /* 281 */ "mGBA tulee toimeen ilman; muutama peli vaatii sen aloitusruutuunsa",
  /* 282 */ "konsolin laiteohjelmisto",
  /* 283 */ "laitteen laiteohjelmisto",
  /* 284 */ "Panasonic FZ-10:n laiteohjelmisto; tämän nimen Opera ottaa oletuksena",
  /* 285 */ "melonDS muokkaa tätä ja säilyttää alkuperäisen .bak-tiedostona",
  /* 286 */ "kirjasimet",
  /* 287 */ "konsolin asetukset ja päiväys",
  /* 288 */ "ilman sitä ydin käy mutta ruutu pysyy mustana",
  /* 289 */ "konsolin merkistötaulu",
  /* 290 */ "amerikkalainen muunnos, Yhdysvaltain Sega CD -peleille",
  /* 291 */ "japanilainen muunnos, japanilaisille Mega-CD-peleille",
  /* 292 */ "kuvakaappausta",
  /* 293 */ "kuvakaappausta",
  /* 294 */ "kuvakaappaus",
  /* 295 */ "kuvakaappausta",
  /* 296 */ "kuvakaappausta",
  /* 297 */ "kuvakaappausta",
  /* 298 */ "ydintä",
  /* 299 */ "ydintä",
  /* 300 */ "ydin",
  /* 301 */ "ydintä",
  /* 302 */ "ydintä",
  /* 303 */ "ydintä",
  /* 304 */ "emulaattoria",
  /* 305 */ "emulaattoria",
  /* 306 */ "emulaattori",
  /* 307 */ "emulaattoria",
  /* 308 */ "emulaattoria",
  /* 309 */ "emulaattoria",
  /* 310 */ "tiedostoa",
  /* 311 */ "tiedostoa",
  /* 312 */ "tiedosto",
  /* 313 */ "tiedostoa",
  /* 314 */ "tiedostoa",
  /* 315 */ "tiedostoa",
  /* 316 */ "peliä",
  /* 317 */ "peliä",
  /* 318 */ "peli",
  /* 319 */ "peliä",
  /* 320 */ "peliä",
  /* 321 */ "peliä",
  /* 322 */ "<code>{rom}</code> korvataan pelin polulla. Ilman sitä polku lisätään loppuun — juuri niin kuin useimmat emulaattorit odottavat.",
  /* 323 */ "<strong>Pelin ulkopuolella kaikki hoituu ohjaimella:</strong> suunnat selaavat kirjastoa, ikkunoita ja valikkoriviä; <strong>A</strong> vahvistaa, <strong>B</strong> palaa takaisin, <strong>Start</strong> avaa valikkorivin. Pelin aikana <strong>Select ja Start yhdessä</strong> vievät takaisin kirjastoon — kaksi painiketta kerrallaan, sillä kumpikin on pelin käytössä.",
  /* 324 */ "Ei kuvakaappauksia. Paina pelin aikana <strong>F12</strong> tai ohjaimella <strong>Select + Y</strong>.",
  /* 325 */ "Jokainen konsoli tarvitsee oman emulaattorinsa. EvaChi hakee ne libretro-projektin viralliselta käännöspalvelimelta <code>buildbot.libretro.com</code> ja asentaa ne omaan kansioonsa. Mitään ei levitetä edelleen: nämä ovat tekijöidensä julkaisemat versiot.",
  /* 326 */ "Neljä tallennuspaikkaa peliä kohti, levylle säilöttyinä. Lihavoitua paikkaa käyttävät <strong>F2</strong> ja <strong>F4</strong> — sekä ohjaimella <strong>Select + L1</strong> / <strong>Select + R1</strong>. Tyhjennä paikka napsauttamalla sitä oikealla.",
  /* 327 */ "Emulaattori pyörii samassa ikkunassa kuin EvaChi: kun se kaatuu, se vie EvaChin mukanaan ilman varoitusta. Käytöstä poistaminen jättää emulaattorin asennetuksi mutta lakkaa tarjoamasta sitä. Voit palauttaa sen milloin tahansa kohdasta <strong>Tiedosto → Emulaattorit</strong>, ikkunan alaosasta.",
  /* 328 */ "Yksi tiedosto peliä kohti levyllä <small> CD-peli saapuu yhtenä <code>.cue</code>-luettelona ja niin monena <code>.bin</code>-tiedostona kuin levyllä oli raitoja. Vain luettelo käynnistyy: raidat piilotetaan, kun se on paikallaan. Ilman luetteloa mitään ei piiloteta. </small>",
  /* 329 */ "(tyhjä) tai --fullscreen {rom}",
  /* 330 */ "Sata prosenttia on konsolin oma nopeus. Sitä pienemmällä peli hidastuu, suuremmalla se kiitää — ja ääni seuraa mukana, matalampana tai korkeampana. Ohjaimella vasen ja oikea siirtyvät portaalta seuraavalle. Vain sisäiset ytimet: ulkoinen emulaattori pitää oman nopeutensa.",
  /* 331 */ "Viisi konsolia kerrallaan",
  /* 332 */ "Ristiohjain",
  /* 333 */ "Alkukirjaimesta seuraavaan",
  /* 334 */ "Animoidussa valikossa viisi peliä kerrallaan",
  /* 335 */ "Pelin nopeus",
  /* 336 */ "Peruuta",
  /* 337 */ "Vedä kehystä tai tartu sen kulmaan. Nuolinäppäimet siirtävät kehystä, ja Vaihto-näppäimen kanssa se kasvaa tai kutistuu. Jos kehys ulottuu kuvan ulkopuolelle, reunoille tulee läpinäkyvät kaistaleet: näin saat liian tiukan kansikuvan näkymään väljempänä. Ohjaimessa suuntanapit siirtävät ja liipaisimet säätävät kokoa.",
  /* 338 */ "Rajaa",
  /* 339 */ "Rajaa kansikuva",
  /* 340 */ "Koko kuva",
  /* 341 */ "{0} — kansikuva rajattu",
  /* 342 */ "{0} — ei kansikuvaa rajattavaksi",
  /* 343 */ "kansikuvaa ei voi lukea — {0}",
  /* 344 */ "rajaus ei onnistunut — {0}",
  /* 345 */ "Rajaa kansikuva…",
];
