/**
 * Filipino (philippin) — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * sont là pour qu'on puisse le vérifier à l'œil.
 */

export const fil: readonly string[] = [  /* 1 */ "Sa controller",
  /* 2 */ "A simulan · X paborito · Y i-crop · L1/R1 konsola · L2/R2 letra · B balik",
  /* 3 */ "Tungkol sa EvaChi",
  /* 4 */ "Tungkol dito…",
  /* 5 */ "Paparating: mga filter na CRT, grid, at scanline. Handa na ang puwang, dito lilitaw ang mga filter.",
  /* 6 */ "I-refresh ang aklatan",
  /* 7 */ "Tanawin",
  /* 8 */ "Ipakita ang mga cover ng laro",
  /* 9 */ "Tulong",
  /* 10 */ "Magdagdag ng folder ng mga laro…",
  /* 11 */ "Magdagdag ng folder…",
  /* 12 */ "Pindutin ang isang pindutan ng controller: magliliwanag ang katumbas nitong key. Para baguhin ang isa, lumipat sa muling pagtatalaga, i-click ang key na babaguhin, saka pindutin ang gustong pindutan.",
  /* 13 */ "Mga argumento",
  /* 14 */ "Sa keyboard",
  /* 15 */ "Walang laro",
  /* 16 */ "Walang natukoy na controller.",
  /* 17 */ "Aklatan",
  /* 18 */ "Tunog ng pagpili sa controller",
  /* 19 */ "May mga console na hindi umaandar nang wala ang orihinal nilang firmware. Hindi ito maibibigay ng EvaChi: may copyright ang code na iyon, at sa makinang pag-aari mo ito kinokopya. Sinasabi naman niya kung alin ang kulang, sa anong pangalan, at saan ito ilalagay.",
  /* 20 */ "Walang libretro core ang mga console na ito: hiwalay na programa ang emulator nila, na ini-install ng EvaChi sa sarili niyang folder at diretsong inilulunsad sa laro — hindi na dumaraan sa menu nito. Nasa iyo pa rin ang mga laro, ang mga key at ang mga system file.",
  /* 21 */ "Ang mga setting na ito ay para lamang sa mga panloob na core. May sarili nito ang panlabas na emulator, at hindi nakikialam ang EvaChi.",
  /* 22 */ "Hindi na inaalok ang mga ito: hindi sila sumagot nang tanungin, o pinabagsak nila ang EvaChi. Ang pagbabalik sa kanila ay hindi muling pag-install — ibinabalik lamang sila sa listahan.",
  /* 23 */ "I-load ang state",
  /* 24 */ "Mga panloob na core lamang. I-click ang isang shortcut saka pindutin ang gustong key o pindutan; sa controller ay dalawang pindutan nang sabay, dahil bawat isa sa kanila ay gamit na ng laro.",
  /* 25 */ "Mga kontrol",
  /* 26 */ "Mga kontrol…",
  /* 27 */ "Mga kamakailang console",
  /* 28 */ "Magdagdag ng ibang emulator",
  /* 29 */ "Mga direksyon / kaliwang stick",
  /* 30 */ "Mga folder ng laro",
  /* 31 */ "Isantabi ang emulator na ito",
  /* 32 */ "Galing ang mga ito sa thumbnail server ng proyektong libretro, kapag kailangan. Kapag inalis ang tsek, wala nang hinihingi ang aklatan sa network.",
  /* 33 */ "Mga save slot",
  /* 34 */ "Mga slot…",
  /* 35 */ "Mga emulator",
  /* 36 */ "Mga naisantabing emulator",
  /* 37 */ "Mga panlabas na emulator",
  /* 38 */ "Mga panlabas na emulator…",
  /* 39 */ "Mga emulator…",
  /* 40 */ "Emulasyon",
  /* 41 */ "Habang naglalaro, bumalik sa aklatan — dalawang pindutan nang sabay, dahil bawat isa ay gamit ng laro",
  /* 42 */ "I-save",
  /* 43 */ "Mga extension",
  /* 44 */ "Isara",
  /* 45 */ "File",
  /* 46 */ "Mga system file na ikaw ang maglalagay",
  /* 47 */ "Galerya",
  /* 48 */ "Pamahalaan ang mga folder…",
  /* 49 */ "Graphics",
  /* 50 */ "Graphics…",
  /* 51 */ "Ituro ang folder kung saan naroon ang mga laro mo.",
  /* 52 */ "Pag-install",
  /* 53 */ "I-install ang napili",
  /* 54 */ "Mag-install ng mga emulator…",
  /* 55 */ "Interpreter",
  /* 56 */ "Hindi mo kailangang malaman kung saan: ituro lang ang folder kung saan nagkalat ang lahat — BIOS, mga key, firmware, mga archive, pati mga subfolder — at dadalhin ng EvaChi ang bawat file sa tamang lugar, para sa mga core at gayundin sa mga nakahiwalay na emulator. Ang walang humihingi ay hindi ginagalaw.",
  /* 57 */ "Mga cover",
  /* 58 */ "Talaan",
  /* 59 */ "Talaan…",
  /* 60 */ "Hindi maayos na natapos ang huling takbo",
  /* 61 */ "Simulan ang laro, kumpirmahin",
  /* 62 */ "Wika",
  /* 63 */ "Naaalala ang napili mula sa isang pagbukas hanggang sa susunod. Nasuri ang bawat isa na nababasa: sapat sa lahat ng dako ang kontrast ng teksto sa likuran nito.",
  /* 64 */ "Panatilihin ito",
  /* 65 */ "Nakahanda na ang mga emulator sa ibaba — pati ang mga argumento at format. Hinahanap sila ng EvaChi sa disk mo; hindi niya sila ini-install.",
  /* 66 */ "Orihinal na mga takda",
  /* 67 */ "Paglalambot",
  /* 68 */ "Gawing paborito ang laro, o alisin ito roon",
  /* 69 */ "Musika ng animadong menu",
  /* 70 */ "Pangalan",
  /* 71 */ "Buksan ang menu bar",
  /* 72 */ "Buksan ang folder",
  /* 73 */ "Buksan ang folder…",
  /* 74 */ "Magbukas ng laro…",
  /* 75 */ "bawat frame",
  /* 76 */ "Mga setting ng core",
  /* 77 */ "Mga setting ng core…",
  /* 78 */ "Maglibot sa aklatan, sa mga bintana at sa menu bar",
  /* 79 */ "Mag-browse…",
  /* 80 */ "Pause",
  /* 81 */ "Buong screen",
  /* 82 */ "Para sa mga console na walang libretro core. Inilulunsad ng EvaChi ang programa na ang laro ang argumento: diretso sa laro magsisimula ang emulator, hindi na dumaraan sa sarili nitong menu.",
  /* 83 */ "Kumuha ng screenshot",
  /* 84 */ "Anyo",
  /* 85 */ "Handa",
  /* 86 */ "Programa",
  /* 87 */ "Ilang mahahabang akorde at kalat-kalat na nota, nilikha habang tumutugtog sa halip na naitala: hindi kailanman dumadaan muli sa parehong lugar ang piyesa. Kusa itong humihinto sa oras na magsimula ang isang laro.",
  /* 88 */ "Mag-ayos ng folder…",
  /* 89 */ "Italaga muli…",
  /* 90 */ "Maghanap ng laro…",
  /* 91 */ "I-reset",
  /* 92 */ "Bumalik sa aklatan",
  /* 93 */ "Bumalik, isara",
  /* 94 */ "Mabilis na pag-save",
  /* 95 */ "I-save ang state",
  /* 96 */ "Shaders",
  /* 97 */ "Tunog",
  /* 98 */ "Start",
  /* 99 */ "Laki ng imahe",
  /* 100 */ "Mga tema",
  /* 101 */ "Mga tema…",
  /* 102 */ "Isang file lamang…",
  /* 103 */ "Isang maikling tiktik kapag lumipat ng laro, isa pa kapag sinimulan ito. Sa controller lamang: sa mouse at keyboard, ramdam na agad ang kilos.",
  /* 104 */ "Bilis",
  /* 105 */ "Tingnan ang mga screenshot…",
  /* 106 */ "Puwede mong i-install ang ilan lamang — ang mga console lamang na naka-install ang emulator ang lumilitaw sa aklatan.",
  /* 107 */ "{0} — na-load",
  /* 108 */ "{0} — kanang klik para burahin",
  /* 109 */ "{0} — ginawang paborito",
  /* 110 */ "{0} — na-reset",
  /* 111 */ "{0} — inalis sa mga paborito",
  /* 112 */ "{0} — dina-download…",
  /* 113 */ "{0}: bigo, tingnan ang talaan",
  /* 114 */ "{0} ang magagamit",
  /* 115 */ "na-save ang {0}",
  /* 116 */ "panlabas na emulator ang {0}: inilulunsad ito, hindi pinapatakbo sa loob",
  /* 117 */ "{0} fps",
  /* 118 */ "na-install ang {0}",
  /* 119 */ "na-install ang {0} — {1}",
  /* 120 */ "na-install at handa na ang {0}",
  /* 121 */ "{0} ang na-install, {1} ang bigo — tingnan ang talaan",
  /* 122 */ "naibalik ang {0}",
  /* 123 */ "inalis ang {0}",
  /* 124 */ "{0} sa {1}",
  /* 125 */ "{0} ang nasa disk, ngunit walang naka-install na core na makakabukas ng mga ito.",
  /* 126 */ "kunin sa {0}, saka “Mag-browse…”",
  /* 127 */ "ida-download",
  /* 128 */ "wala, opsyonal",
  /* 129 */ "Paganahin",
  /* 130 */ "Malambot",
  /* 131 */ "hindi maidagdag — {0}",
  /* 132 */ "Iakma",
  /* 133 */ "Ambar",
  /* 134 */ "Pisara",
  /* 135 */ "huminto — {0}",
  /* 136 */ "biglaang paghinto noong huli — {0}",
  /* 137 */ "wala",
  /* 138 */ "walang naibalik na core gayong {0} ang dating kilala — pinanatili ang nakaraang listahan",
  /* 139 */ "walang emulator",
  /* 140 */ "Walang naka-install na emulator",
  /* 141 */ "Walang nakilalang laro",
  /* 142 */ "Walang nahanap",
  /* 143 */ "wala",
  /* 144 */ "hindi mabasa ang aklatan — {0}",
  /* 145 */ "nakakabit",
  /* 146 */ "screenshot",
  /* 147 */ "Palitan ang cover…",
  /* 148 */ "Palitan…",
  /* 149 */ "Bawat pixel sa siyam",
  /* 150 */ "Bawat pixel sa apat: matalas, walang pagbaluktot",
  /* 151 */ "Bawat pixel sa labing-anim — para sa malalaking screen",
  /* 152 */ "I-load",
  /* 153 */ "Pumili ng cover…",
  /* 154 */ "pumili muna ng laro sa aklatan",
  /* 155 */ "core: {0}",
  /* 156 */ "hindi naka-install ang core",
  /* 157 */ "Mga naka-install na core",
  /* 158 */ "mga libretro core",
  /* 159 */ "Mataas na kontrast",
  /* 160 */ "native shell: {0}",
  /* 161 */ "hindi kumpleto ang pag-unload — {0}",
  /* 162 */ "natuklasan: {0}",
  /* 163 */ "naputol ang pagtuklas — {0}",
  /* 164 */ "Ikaw ang magtukoy ng programa ng {0}",
  /* 165 */ "naidagdag na folder: {0}",
  /* 166 */ "binuksang folder: {0}",
  /* 167 */ "Default na folder",
  /* 168 */ "Mga naidagdag na folder",
  /* 169 */ "Esc",
  /* 170 */ "Slot {0}",
  /* 171 */ "slot {0} — {1}",
  /* 172 */ "Emulator na ginagamit para sa folder na ito",
  /* 173 */ "mga panlabas na emulator",
  /* 174 */ "isinasagawa",
  /* 175 */ "nakalagay",
  /* 176 */ "hindi ma-save — {0}",
  /* 177 */ "Enter",
  /* 178 */ "Maida-download ng EvaChi ang mga ito mula sa opisyal na pagawaan ng libretro. Piliin ang mga console na gusto mo.",
  /* 179 */ "Huminto ang EvaChi habang binubuksan ang “{0}”, gamit ang emulator na {1}.",
  /* 180 */ "Huminto ang EvaChi, gamit ang emulator na {0}.",
  /* 181 */ "external_systems → {0} na emulator ang nakatala",
  /* 182 */ "Paborito",
  /* 183 */ "Mga paborito",
  /* 184 */ "hindi mabasa ang mga system file — {0}",
  /* 185 */ "Arrow keys",
  /* 186 */ "Game Boy",
  /* 187 */ "Grid",
  /* 188 */ "kulang ng {0} ang ilang naka-install na console",
  /* 189 */ "tapos na ang pag-install: {0}",
  /* 190 */ "Ini-install…",
  /* 191 */ "naka-install",
  /* 192 */ "ini-install ng EvaChi",
  /* 193 */ "I-install",
  /* 194 */ "interpreter: {0}",
  /* 195 */ "tinatanong ang mga naka-install na core…",
  /* 196 */ "Simulan",
  /* 197 */ "Simulan ang napiling laro",
  /* 198 */ "Lavender",
  /* 199 */ "Nakahanay ang mga console, nakahanay pababa ang mga laro, at gumagalaw ang likuran. Parang console sa sala.",
  /* 200 */ "Lumalabo ang mga gilid — mas malapit sa lumang telebisyon",
  /* 201 */ "Malalaking cover, nililibot sa controller. Ginawa para sa sopa.",
  /* 202 */ "Nananatiling parisukat ang mga pixel, gaya sa orihinal na makina",
  /* 203 */ "naibalik sa orihinal ang mga takda ng controller",
  /* 204 */ "list_cores → {0} na core ang iniulat",
  /* 205 */ "Listahan",
  /* 206 */ "walang makuhang listahan ng mga core — {0}",
  /* 207 */ "walang makuhang listahan ng mga emulator — {0}",
  /* 208 */ "Controller",
  /* 209 */ "controller: {0}",
  /* 210 */ "Controller: {0}",
  /* 211 */ "natanggal ang controller",
  /* 212 */ "KULANG",
  /* 213 */ "Mint",
  /* 214 */ "Animadong menu",
  /* 215 */ "I-update",
  /* 216 */ "Gawing paborito",
  /* 217 */ "naisantabi: {0} · {1}",
  /* 218 */ "wala pang isang minuto",
  /* 219 */ "Matalas",
  /* 220 */ "kailangan ang pangalan, ang programa at ang mga extension",
  /* 221 */ "HINDI",
  /* 222 */ "hindi naka-install sa makinang ito",
  /* 223 */ "Gabing rosas",
  /* 224 */ "Karagatan",
  /* 225 */ "o",
  /* 226 */ "oo",
  /* 227 */ "hindi mabuksan — {0}",
  /* 228 */ "web page: mga panloob na core lamang ang magagamit, walang aklatan",
  /* 229 */ "Papel",
  /* 230 */ "default",
  /* 231 */ "Maglibot sa grid at sa animadong menu",
  /* 232 */ "tinanggihan ang buong screen — {0}",
  /* 233 */ "pindutin ang gustong pindutan sa controller",
  /* 234 */ "pindutin ang isang key…",
  /* 235 */ "pag-aayos: {0} · {1}",
  /* 236 */ "hindi maiayos — {0}",
  /* 237 */ "naputol ang paghahanap ng mga emulator — {0}",
  /* 238 */ "Isara ang isang bintana",
  /* 239 */ "hindi ma-reset — {0}",
  /* 240 */ "Pinupuno ang bintana nang hindi nasisira ang proporsyon",
  /* 241 */ "Ipagpatuloy",
  /* 242 */ "Ipagpatuloy ang save na ito — kanang klik para burahin",
  /* 243 */ "Ibalik",
  /* 244 */ "hindi maibalik — {0}",
  /* 245 */ "Alisin",
  /* 246 */ "Alisin sa mga paborito",
  /* 247 */ "Alisin ang cover",
  /* 248 */ "hindi maalis — {0}",
  /* 249 */ "walang aayusin",
  /* 250 */ "walang humaharang",
  /* 251 */ "Walang tumutugma sa “{0}”.",
  /* 252 */ "Rosas at puti",
  /* 253 */ "walang larawan",
  /* 254 */ "I-save",
  /* 255 */ "I-save dito",
  /* 256 */ "hindi mapili — {0}",
  /* 257 */ "Orihinal na laki ng console, pixel sa pixel",
  /* 258 */ "Tapusin",
  /* 259 */ "maliwanag na tema",
  /* 260 */ "madilim na tema",
  /* 261 */ "lahat ay naka-install",
  /* 262 */ "nahanap: {0}",
  /* 263 */ "Isang seksyon bawat console, nasa talahanayan. Ang pinakasiksik kapag mouse ang gamit.",
  /* 264 */ "walang laman",
  /* 265 */ "ilagay dito, gaya ng mga romset ng laro: sa folder na ito lamang naghahanap ang FinalBurn Neo",
  /* 266 */ "idinaragdag ang panimulang screen ng console",
  /* 267 */ "pampasimula ng makina",
  /* 268 */ "maraming laro ang umaandar nang wala nito; ang menu ng console, hindi",
  /* 269 */ "BIOS ng Amerika",
  /* 270 */ "BIOS ng Amerika at Europa",
  /* 271 */ "BIOS ng Europa",
  /* 272 */ "BIOS ng Japan",
  /* 273 */ "mga key sa pag-decrypt; kung wala ang mga ito, tinatanggihan ang naka-encrypt na dump",
  /* 274 */ "folder ng Machines ng distribusyon ng blueMSX, kasama ang Databases sa tabi",
  /* 275 */ "gayundin",
  /* 276 */ "kailangang-kailangan sa mga larong CD, hindi naman sa mga HuCard",
  /* 277 */ "kailangang-kailangan sa mga larong Mega-CD, hindi naman sa mga cartridge",
  /* 278 */ "Kickstart 1.3; kung wala ito, sa AROS babagsak ang PUAE, malaya ngunit mas kaunti ang kayang patakbuhin",
  /* 279 */ "Kickstart 3.1; kailangan ng mga larong AGA, na hindi kayang patakbuhin ng A500",
  /* 280 */ "iniemula ng melonDS ang BIOS bilang default; mas tapat ang totoo",
  /* 281 */ "hindi ito kailangan ng mGBA; hinihingi ito ng ilang laro para sa panimulang screen nila",
  /* 282 */ "firmware ng console",
  /* 283 */ "firmware ng makina",
  /* 284 */ "firmware ng Panasonic FZ-10; ito ang pangalang kinukuha ng Opera bilang default",
  /* 285 */ "binabago ng melonDS, na iniingatan ang orihinal bilang .bak",
  /* 286 */ "mga font",
  /* 287 */ "mga setting at petsa ng console",
  /* 288 */ "kapag wala ito, umaandar ang core pero nananatiling itim ang screen",
  /* 289 */ "talaan ng mga karakter ng console",
  /* 290 */ "bersyong Amerikano, para sa mga larong Sega CD ng Estados Unidos",
  /* 291 */ "bersyong Hapon, para sa mga larong Mega-CD ng Japan",
  /* 292 */ "screenshot",
  /* 293 */ "screenshot",
  /* 294 */ "screenshot",
  /* 295 */ "screenshot",
  /* 296 */ "screenshot",
  /* 297 */ "screenshot",
  /* 298 */ "core",
  /* 299 */ "core",
  /* 300 */ "core",
  /* 301 */ "core",
  /* 302 */ "core",
  /* 303 */ "core",
  /* 304 */ "emulator",
  /* 305 */ "emulator",
  /* 306 */ "emulator",
  /* 307 */ "emulator",
  /* 308 */ "emulator",
  /* 309 */ "emulator",
  /* 310 */ "file",
  /* 311 */ "file",
  /* 312 */ "file",
  /* 313 */ "file",
  /* 314 */ "file",
  /* 315 */ "file",
  /* 316 */ "laro",
  /* 317 */ "laro",
  /* 318 */ "laro",
  /* 319 */ "laro",
  /* 320 */ "laro",
  /* 321 */ "laro",
  /* 322 */ "Papalitan ang <code>{rom}</code> ng landas patungo sa laro. Kapag wala ito, idinaragdag ang landas sa dulo — iyon ang inaasahan ng karamihan sa mga emulator.",
  /* 323 */ "<strong>Kapag wala sa laro, lahat ay kayang gawin sa controller:</strong> ang mga direksyon ang naglilibot sa aklatan, sa mga bintana at sa menu bar; ang <strong>A</strong> ang kumukumpirma, ang <strong>B</strong> ang bumabalik, ang <strong>Start</strong> ang nagbubukas ng menu bar. Habang naglalaro, ang <strong>Select at Start nang sabay</strong> ang nagbabalik sa aklatan — dalawang pindutan nang sabay, dahil bawat isa ay gamit ng laro.",
  /* 324 */ "Walang screenshot. Pindutin ang <strong>F12</strong> habang naglalaro, o ang <strong>Select + Y</strong> sa controller.",
  /* 325 */ "Kailangan ng bawat console ang sarili nitong emulator. Kinukuha ng EvaChi ang mga ito sa opisyal na pagawaan ng proyektong libretro, <code>buildbot.libretro.com</code>, at ini-install ang mga ito sa sarili nitong folder. Walang ipinamamahaging muli: ang mga bersyong inilabas mismo ng mga may-akda nila ang ginagamit.",
  /* 326 */ "Apat na slot bawat laro, itinatago sa disk. Ang slot na naka-bold ang ginagamit ng <strong>F2</strong> at <strong>F4</strong> — at ng <strong>Select + L1</strong> / <strong>Select + R1</strong> sa controller. Kanang klik sa isang slot para burahin ito.",
  /* 327 */ "Sa iisang bintana ng EvaChi tumatakbo ang emulator: kapag bumagsak ito, kasama nitong bumabagsak ang EvaChi, nang walang anumang mensahe. Kapag isinantabi ang emulator na ito, mananatili itong naka-install ngunit hindi na ito iaalok. Maibabalik mo ito anumang oras mula sa <strong>File → Mga emulator</strong>, sa ibaba ng bintana.",
  /* 328 */ "Isang file lamang bawat laro sa disk <small> Ang larong nasa CD ay dumarating bilang isang <code>.cue</code> na talaan at kasingdami ng <code>.bin</code> na file ng mga track ng disc. Ang talaan lamang ang nabubuksan: itinatago ang mga track kapag naroon ito. Kapag walang talaan, walang itinatago. </small>",
  /* 329 */ "(walang laman) o --fullscreen {rom}",
  /* 330 */ "Sandaang porsyento — iyon ang bilis ng console. Pababa, bumabagal ang laro; pataas, humaharurot ito — at sumasabay ang tunog, mas mababa o mas matinis. Sa controller, ang kaliwa at kanan ay lumilipat sa susunod na baitang. Sa panloob na core lang: sariling bilis ang hawak ng panlabas na emulator.",
  /* 331 */ "Lima-limang console",
  /* 332 */ "Direksyonal na pad",
  /* 333 */ "Sa susunod na unang titik",
  /* 334 */ "Sa animadong menu, lima-limang laro",
  /* 335 */ "Bilis ng laro",
  /* 336 */ "Kanselahin",
  /* 337 */ "Hilahin ang kuwadro, o ang isang sulok nito. Inililipat ito ng mga arrow key, at pinaliliit kapag may Shift. Sa controller, naglilipat ang mga direksyon at nagpapaliit o nagpapalaki ang mga trigger.",
  /* 338 */ "I-crop",
  /* 339 */ "I-crop ang cover",
  /* 340 */ "Buong larawan",
  /* 341 */ "{0} — na-crop ang cover",
  /* 342 */ "{0} — walang cover na i-crop",
  /* 343 */ "hindi mabasa ang cover — {0}",
  /* 344 */ "hindi ma-crop — {0}",
  /* 345 */ "I-crop ang cover…",
];
