/**
 * Filipino (philippin) — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * sont là pour qu'on puisse le vérifier à l'œil.
 */

export const fil: readonly string[] = [
  /* 1 */ "Sa controller",
  /* 2 */ "A simulan · X paborito · Y i-crop · L1/R1 konsola · L2/R2 letra · B balik",
  /* 3 */ "Tungkol sa EvaChi",
  /* 4 */ "Tungkol dito…",
  /* 5 */ "Ang ginagawa ng telebisyong may cathode ray sa larawan, at ipinagpapalagay ng mga larong noon. Para lamang sa mga core na pinapatakbo rito: sariling iginuguhit ng nakatayong emulator ang larawan nito.",
  /* 6 */ "I-refresh ang aklatan",
  /* 7 */ "Tanawin",
  /* 8 */ "Ipakita ang mga cover ng laro",
  /* 9 */ "Tulong",
  /* 10 */ "Magdagdag ng folder ng mga laro…",
  /* 11 */ "Magdagdag ng folder…",
  /* 12 */ "Pindutin ang isang butones sa kontrol: magniningas ang katumbas na utos. Para palitan ang isa, i-click ang kahon sa ibaba at pindutin ang butones na gusto mo. Lilipat noon ang butones: dalawang utos sa iisang butones ay magmumukhang sira.",
  /* 13 */ "Mga argumento",
  /* 14 */ "Sa keyboard",
  /* 15 */ "Walang laro",
  /* 16 */ "Walang natukoy na controller.",
  /* 17 */ "Aklatan",
  /* 18 */ "Tunog ng pagpili sa controller",
  /* 19 */ "May mga console na hindi umaandar nang wala ang orihinal nilang firmware. Hindi ito maibibigay ng EvaChi: may copyright ang code na iyon, at sa makinang pag-aari mo ito kinokopya. Sinasabi naman niya kung alin ang kulang, sa anong pangalan, at saan ito ilalagay.",
  /* 20 */ "Walang libretro core ang mga console na ito: hiwalay na programa ang emulator nila, na ini-install ng EvaChi sa sarili niyang folder at diretsong inilulunsad sa laro — hindi na dumaraan sa menu nito. Nasa iyo pa rin ang mga laro, ang mga key at ang mga system file.",
  /* 21 */ "Ang mga setting na ito ay para lamang sa mga panloob na core. May sarili nito ang panlabas na emulator, at hindi nakikialam ang EvaChi.",
  /* 22 */ "Hindi na inaalok ang mga ito: hindi sila sumagot nang tanungin, o pinabagsak nila ang EvaChi. Ang pagbabalik sa kanila ay hindi muling pag-install — ibinabalik lamang sila sa listahan.",
  /* 23 */ "I-load ang state…",
  /* 24 */ "Mga panloob na core lamang. I-click ang isang shortcut saka pindutin ang gustong key o pindutan; sa controller ay dalawang pindutan nang sabay, dahil bawat isa sa kanila ay gamit na ng laro.",
  /* 25 */ "Mga kontrol",
  /* 26 */ "Mga kontrol…",
  /* 27 */ "Mga kamakailang console",
  /* 28 */ "Magdagdag ng ibang emulator",
  /* 29 */ "Mga direksyon / kaliwang stick",
  /* 30 */ "Mga folder ng laro",
  /* 31 */ "Isantabi ang emulator na ito",
  /* 32 */ "Galing ang mga ito sa thumbnail server ng proyektong libretro, kapag kailangan. Kapag inalis ang tsek, wala nang hinihingi ang aklatan sa network.",
  /* 33 */ "Mga save slot",
  /* 34 */ "Mga slot…",
  /* 35 */ "Mga emulator",
  /* 36 */ "Mga naisantabing emulator",
  /* 37 */ "Mga panlabas na emulator",
  /* 38 */ "Mga panlabas na emulator…",
  /* 39 */ "Mga emulator…",
  /* 40 */ "Emulasyon",
  /* 41 */ "Habang naglalaro, bumalik sa aklatan — dalawang pindutan nang sabay, dahil bawat isa ay gamit ng laro",
  /* 42 */ "I-save",
  /* 43 */ "Mga extension",
  /* 44 */ "Isara",
  /* 45 */ "File",
  /* 46 */ "Mga system file na ikaw ang maglalagay",
  /* 47 */ "Galerya",
  /* 48 */ "Pamahalaan ang mga folder…",
  /* 49 */ "Graphics",
  /* 50 */ "Graphics…",
  /* 51 */ "Ituro ang folder kung saan naroon ang mga laro mo.",
  /* 52 */ "Pag-install",
  /* 53 */ "I-install ang napili",
  /* 54 */ "Mag-install ng mga emulator…",
  /* 55 */ "Interpreter",
  /* 56 */ "Hindi mo kailangang malaman kung saan: ituro lang ang folder kung saan nagkalat ang lahat — BIOS, mga key, firmware, mga archive, pati mga subfolder — at dadalhin ng EvaChi ang bawat file sa tamang lugar, para sa mga core at gayundin sa mga nakahiwalay na emulator. Ang walang humihingi ay hindi ginagalaw.",
  /* 57 */ "Mga cover",
  /* 58 */ "Talaan",
  /* 59 */ "Talaan…",
  /* 60 */ "Hindi maayos na natapos ang huling takbo",
  /* 61 */ "Simulan ang laro, kumpirmahin",
  /* 62 */ "Wika",
  /* 63 */ "Naaalala ang napili mula sa isang pagbukas hanggang sa susunod. Nasuri ang bawat isa na nababasa: sapat sa lahat ng dako ang kontrast ng teksto sa likuran nito.",
  /* 64 */ "Panatilihin ito",
  /* 65 */ "Nakahanda na ang mga emulator sa ibaba — pati ang mga argumento at format. Hinahanap sila ng EvaChi sa disk mo; hindi niya sila ini-install.",
  /* 66 */ "Orihinal na mga takda",
  /* 67 */ "Paglalambot",
  /* 68 */ "Gawing paborito ang laro, o alisin ito roon",
  /* 69 */ "Musika ng mga animadong menu",
  /* 70 */ "Pangalan",
  /* 71 */ "Buksan ang menu bar",
  /* 72 */ "Buksan ang folder",
  /* 73 */ "Buksan ang folder…",
  /* 74 */ "Magbukas ng laro…",
  /* 75 */ "bawat frame",
  /* 76 */ "Mga setting ng core",
  /* 77 */ "Mga setting ng core…",
  /* 78 */ "Maglibot sa aklatan, sa mga bintana at sa menu bar",
  /* 79 */ "Mag-browse…",
  /* 80 */ "Pause",
  /* 81 */ "Buong screen",
  /* 82 */ "Para sa mga console na walang libretro core. Inilulunsad ng EvaChi ang programa na ang laro ang argumento: diretso sa laro magsisimula ang emulator, hindi na dumaraan sa sarili nitong menu.",
  /* 83 */ "Kumuha ng screenshot",
  /* 84 */ "Anyo",
  /* 85 */ "Handa",
  /* 86 */ "Programa",
  /* 87 */ "Ilang mahahabang akorde at kalat-kalat na nota, nilikha habang tumutugtog sa halip na naitala: hindi kailanman dumadaan muli sa parehong lugar ang piyesa. Kusa itong humihinto sa oras na magsimula ang isang laro.",
  /* 88 */ "Mag-ayos ng folder…",
  /* 89 */ "Bakantehin",
  /* 90 */ "Maghanap ng laro…",
  /* 91 */ "I-reset",
  /* 92 */ "Bumalik sa aklatan",
  /* 93 */ "Bumalik, isara",
  /* 94 */ "Mabilis na pag-save",
  /* 95 */ "I-save ang state…",
  /* 96 */ "Shaders",
  /* 97 */ "Tunog",
  /* 98 */ "Start",
  /* 99 */ "Laki ng imahe",
  /* 100 */ "Mga tema",
  /* 101 */ "Mga tema…",
  /* 102 */ "Isang file lamang…",
  /* 103 */ "Isang maikling tiktik kapag lumipat ng laro, isa pa kapag sinimulan ito. Sa controller lamang: sa mouse at keyboard, ramdam na agad ang kilos.",
  /* 104 */ "Bilis",
  /* 105 */ "Tingnan ang mga screenshot…",
  /* 106 */ "Puwede mong i-install ang ilan lamang — ang mga console lamang na naka-install ang emulator ang lumilitaw sa aklatan.",
  /* 107 */ "{0} — na-load",
  /* 108 */ "{0} — kanang klik para burahin",
  /* 109 */ "{0} — ginawang paborito",
  /* 110 */ "{0} — na-reset",
  /* 111 */ "{0} — inalis sa mga paborito",
  /* 112 */ "{0} — dina-download…",
  /* 113 */ "{0}: bigo, tingnan ang talaan",
  /* 114 */ "{0} ang magagamit",
  /* 115 */ "na-save ang {0}",
  /* 116 */ "panlabas na emulator ang {0}: inilulunsad ito, hindi pinapatakbo sa loob",
  /* 117 */ "{0} fps",
  /* 118 */ "na-install ang {0}",
  /* 119 */ "na-install ang {0} — {1}",
  /* 120 */ "na-install at handa na ang {0}",
  /* 121 */ "{0} ang na-install, {1} ang bigo — tingnan ang talaan",
  /* 122 */ "naibalik ang {0}",
  /* 123 */ "inalis ang {0}",
  /* 124 */ "{0} sa {1}",
  /* 125 */ "{0} ang nasa disk, ngunit walang naka-install na core na makakabukas ng mga ito.",
  /* 126 */ "kunin sa {0}, saka “Mag-browse…”",
  /* 127 */ "ida-download",
  /* 128 */ "wala, opsyonal",
  /* 129 */ "Paganahin",
  /* 130 */ "Malambot",
  /* 131 */ "hindi maidagdag — {0}",
  /* 132 */ "Iakma",
  /* 133 */ "Ambar",
  /* 134 */ "Pisara",
  /* 135 */ "huminto — {0}",
  /* 136 */ "biglaang paghinto noong huli — {0}",
  /* 137 */ "wala",
  /* 138 */ "walang naibalik na core gayong {0} ang dating kilala — pinanatili ang nakaraang listahan",
  /* 139 */ "walang emulator",
  /* 140 */ "Walang naka-install na emulator",
  /* 141 */ "Walang nakilalang laro",
  /* 142 */ "Walang nahanap",
  /* 143 */ "wala",
  /* 144 */ "hindi mabasa ang aklatan — {0}",
  /* 145 */ "nakakabit",
  /* 146 */ "screenshot",
  /* 147 */ "Palitan ang cover…",
  /* 148 */ "Palitan…",
  /* 149 */ "Bawat pixel sa siyam",
  /* 150 */ "Bawat pixel sa apat: matalas, walang pagbaluktot",
  /* 151 */ "Bawat pixel sa labing-anim — para sa malalaking screen",
  /* 152 */ "I-load",
  /* 153 */ "Pumili ng cover…",
  /* 154 */ "pumili muna ng laro sa aklatan",
  /* 155 */ "core: {0}",
  /* 156 */ "hindi naka-install ang core",
  /* 157 */ "Mga naka-install na core",
  /* 158 */ "mga libretro core",
  /* 159 */ "Mataas na kontrast",
  /* 160 */ "native shell: {0}",
  /* 161 */ "hindi kumpleto ang pag-unload — {0}",
  /* 162 */ "natuklasan: {0}",
  /* 163 */ "naputol ang pagtuklas — {0}",
  /* 164 */ "Ikaw ang magtukoy ng programa ng {0}",
  /* 165 */ "naidagdag na folder: {0}",
  /* 166 */ "binuksang folder: {0}",
  /* 167 */ "Default na folder",
  /* 168 */ "Mga naidagdag na folder",
  /* 169 */ "Esc",
  /* 170 */ "Slot {0}",
  /* 171 */ "slot {0} — {1}",
  /* 172 */ "Emulator na ginagamit para sa folder na ito",
  /* 173 */ "mga panlabas na emulator",
  /* 174 */ "isinasagawa",
  /* 175 */ "nakalagay",
  /* 176 */ "hindi ma-save — {0}",
  /* 177 */ "Enter",
  /* 178 */ "Maida-download ng EvaChi ang mga ito mula sa opisyal na pagawaan ng libretro. Piliin ang mga console na gusto mo.",
  /* 179 */ "Huminto ang EvaChi habang binubuksan ang “{0}”, gamit ang emulator na {1}.",
  /* 180 */ "Huminto ang EvaChi, gamit ang emulator na {0}.",
  /* 181 */ "external_systems → {0} na emulator ang nakatala",
  /* 182 */ "Paborito",
  /* 183 */ "Mga paborito",
  /* 184 */ "hindi mabasa ang mga system file — {0}",
  /* 185 */ "Arrow keys",
  /* 186 */ "Game Boy",
  /* 187 */ "Grid",
  /* 188 */ "kulang ng {0} ang ilang naka-install na console",
  /* 189 */ "tapos na ang pag-install: {0}",
  /* 190 */ "Ini-install…",
  /* 191 */ "naka-install",
  /* 192 */ "ini-install ng EvaChi",
  /* 193 */ "I-install",
  /* 194 */ "interpreter: {0}",
  /* 195 */ "tinatanong ang mga naka-install na core…",
  /* 196 */ "Simulan",
  /* 197 */ "Simulan ang napiling laro",
  /* 198 */ "Lavender",
  /* 199 */ "Nakahanay ang mga console, nakahanay pababa ang mga laro, at gumagalaw ang likuran. Parang console sa sala.",
  /* 200 */ "Lumalabo ang mga gilid — mas malapit sa lumang telebisyon",
  /* 201 */ "Malalaking cover, nililibot sa controller. Ginawa para sa sopa.",
  /* 202 */ "Nananatiling parisukat ang mga pixel, gaya sa orihinal na makina",
  /* 203 */ "naibalik sa orihinal ang mga takda ng controller",
  /* 204 */ "list_cores → {0} na core ang iniulat",
  /* 205 */ "Listahan",
  /* 206 */ "walang makuhang listahan ng mga core — {0}",
  /* 207 */ "walang makuhang listahan ng mga emulator — {0}",
  /* 208 */ "Controller",
  /* 209 */ "controller: {0}",
  /* 210 */ "Controller: {0}",
  /* 211 */ "natanggal ang controller",
  /* 212 */ "KULANG",
  /* 213 */ "Mint",
  /* 214 */ "Animadong menu",
  /* 215 */ "I-update",
  /* 216 */ "Gawing paborito",
  /* 217 */ "naisantabi: {0} · {1}",
  /* 218 */ "wala pang isang minuto",
  /* 219 */ "Matalas",
  /* 220 */ "kailangan ang pangalan, ang programa at ang mga extension",
  /* 221 */ "HINDI",
  /* 222 */ "hindi naka-install sa makinang ito",
  /* 223 */ "Gabing rosas",
  /* 224 */ "Karagatan",
  /* 225 */ "o",
  /* 226 */ "oo",
  /* 227 */ "hindi mabuksan — {0}",
  /* 228 */ "web page: mga panloob na core lamang ang magagamit, walang aklatan",
  /* 229 */ "Papel",
  /* 230 */ "default",
  /* 231 */ "Maglibot sa grid at sa mga animadong menu",
  /* 232 */ "tinanggihan ang buong screen — {0}",
  /* 233 */ "pindutin ang gustong pindutan sa controller",
  /* 234 */ "pindutin ang isang key…",
  /* 235 */ "pag-aayos: {0} · {1}",
  /* 236 */ "hindi maiayos — {0}",
  /* 237 */ "naputol ang paghahanap ng mga emulator — {0}",
  /* 238 */ "Isara ang isang bintana",
  /* 239 */ "hindi ma-reset — {0}",
  /* 240 */ "Pinupuno ang bintana nang hindi nasisira ang proporsyon",
  /* 241 */ "Ipagpatuloy",
  /* 242 */ "Palitan",
  /* 243 */ "Ibalik",
  /* 244 */ "hindi maibalik — {0}",
  /* 245 */ "Alisin",
  /* 246 */ "Alisin sa mga paborito",
  /* 247 */ "Alisin ang cover",
  /* 248 */ "hindi maalis — {0}",
  /* 249 */ "walang aayusin",
  /* 250 */ "walang humaharang",
  /* 251 */ "Walang tumutugma sa “{0}”.",
  /* 252 */ "Rosas at puti",
  /* 253 */ "walang larawan",
  /* 254 */ "I-save",
  /* 255 */ "I-save dito",
  /* 256 */ "hindi mapili — {0}",
  /* 257 */ "Orihinal na laki ng console, pixel sa pixel",
  /* 258 */ "Itapon",
  /* 259 */ "maliwanag na tema",
  /* 260 */ "madilim na tema",
  /* 261 */ "lahat ay naka-install",
  /* 262 */ "nahanap: {0}",
  /* 263 */ "Isang seksyon bawat console, nasa talahanayan. Ang pinakasiksik kapag mouse ang gamit.",
  /* 264 */ "walang laman",
  /* 265 */ "ilagay dito, gaya ng mga romset ng laro: sa folder na ito lamang naghahanap ang FinalBurn Neo",
  /* 266 */ "idinaragdag ang panimulang screen ng console",
  /* 267 */ "pampasimula ng makina",
  /* 268 */ "maraming laro ang umaandar nang wala nito; ang menu ng console, hindi",
  /* 269 */ "BIOS ng Amerika",
  /* 270 */ "BIOS ng Amerika at Europa",
  /* 271 */ "BIOS ng Europa",
  /* 272 */ "BIOS ng Japan",
  /* 273 */ "mga key sa pag-decrypt; kung wala ang mga ito, tinatanggihan ang naka-encrypt na dump",
  /* 274 */ "folder ng Machines ng distribusyon ng blueMSX, kasama ang Databases sa tabi",
  /* 275 */ "gayundin",
  /* 276 */ "kailangang-kailangan sa mga larong CD, hindi naman sa mga HuCard",
  /* 277 */ "kailangang-kailangan sa mga larong Mega-CD, hindi naman sa mga cartridge",
  /* 278 */ "Kickstart 1.3; kung wala ito, sa AROS babagsak ang PUAE, malaya ngunit mas kaunti ang kayang patakbuhin",
  /* 279 */ "Kickstart 3.1; kailangan ng mga larong AGA, na hindi kayang patakbuhin ng A500",
  /* 280 */ "iniemula ng melonDS ang BIOS bilang default; mas tapat ang totoo",
  /* 281 */ "hindi ito kailangan ng mGBA; hinihingi ito ng ilang laro para sa panimulang screen nila",
  /* 282 */ "firmware ng console",
  /* 283 */ "firmware ng makina",
  /* 284 */ "firmware ng Panasonic FZ-10; ito ang pangalang kinukuha ng Opera bilang default",
  /* 285 */ "binabago ng melonDS, na iniingatan ang orihinal bilang .bak",
  /* 286 */ "mga font",
  /* 287 */ "mga setting at petsa ng console",
  /* 288 */ "kapag wala ito, umaandar ang core pero nananatiling itim ang screen",
  /* 289 */ "talaan ng mga karakter ng console",
  /* 290 */ "bersyong Amerikano, para sa mga larong Sega CD ng Estados Unidos",
  /* 291 */ "bersyong Hapon, para sa mga larong Mega-CD ng Japan",
  /* 292 */ "screenshot",
  /* 293 */ "screenshot",
  /* 294 */ "screenshot",
  /* 295 */ "screenshot",
  /* 296 */ "screenshot",
  /* 297 */ "screenshot",
  /* 298 */ "core",
  /* 299 */ "core",
  /* 300 */ "core",
  /* 301 */ "core",
  /* 302 */ "core",
  /* 303 */ "core",
  /* 304 */ "emulator",
  /* 305 */ "emulator",
  /* 306 */ "emulator",
  /* 307 */ "emulator",
  /* 308 */ "emulator",
  /* 309 */ "emulator",
  /* 310 */ "file",
  /* 311 */ "file",
  /* 312 */ "file",
  /* 313 */ "file",
  /* 314 */ "file",
  /* 315 */ "file",
  /* 316 */ "laro",
  /* 317 */ "laro",
  /* 318 */ "laro",
  /* 319 */ "laro",
  /* 320 */ "laro",
  /* 321 */ "laro",
  /* 322 */ "Papalitan ang <code>{rom}</code> ng landas patungo sa laro. Kapag wala ito, idinaragdag ang landas sa dulo — iyon ang inaasahan ng karamihan sa mga emulator.",
  /* 323 */ "<strong>Kapag wala sa laro, lahat ay kayang gawin sa controller:</strong> ang mga direksyon ang naglilibot sa aklatan, sa mga bintana at sa menu bar; ang <strong>A</strong> ang kumukumpirma, ang <strong>B</strong> ang bumabalik, ang <strong>Start</strong> ang nagbubukas ng menu bar. Habang naglalaro, ang <strong>Select at Start nang sabay</strong> ang nagbabalik sa aklatan — dalawang pindutan nang sabay, dahil bawat isa ay gamit ng laro.",
  /* 324 */ "Walang screenshot. Pindutin ang <strong>F12</strong> habang naglalaro, o ang <strong>Select + Y</strong> sa controller.",
  /* 325 */ "Kailangan ng bawat console ang sarili nitong emulator. Kinukuha ng EvaChi ang mga ito sa opisyal na pagawaan ng proyektong libretro, <code>buildbot.libretro.com</code>, at ini-install ang mga ito sa sarili nitong folder. Walang ipinamamahaging muli: ang mga bersyong inilabas mismo ng mga may-akda nila ang ginagamit.",
  /* 326 */ "Apat na slot bawat laro, nakatago sa disk. Bawat kilos ay nakasulat sa ilalim ng slot, at ang pagpapalit o pagbakante ay humihingi muna ng kumpirmasyon. Ang <strong>F2</strong> at <strong>F4</strong> — at <strong>Select + L1</strong> / <strong>Select + R1</strong> sa kontrol — ay diretso sa slot na naka-bold, walang tinatanong.",
  /* 327 */ "Sa sariling proseso tumatakbo ang bawat emulator: kapag bumagsak ito, nakikita ito ng EvaChi at bumabalik sa aklatan. Nawawala ang kasalukuyang laro, at maaaring hindi pa naisulat ang save ng laro. Kapag isinantabi ang emulator na ito, mananatili itong naka-install ngunit hindi na ito iaalok. Maibabalik mo ito anumang oras mula sa <strong>File → Mga emulator</strong>, sa ibaba ng bintana.",
  /* 328 */ "Isang file lamang bawat laro sa disk <small> Ang larong nasa CD ay dumarating bilang isang <code>.cue</code> na talaan at kasingdami ng <code>.bin</code> na file ng mga track ng disc. Ang talaan lamang ang nabubuksan: itinatago ang mga track kapag naroon ito. Kapag walang talaan, walang itinatago. </small>",
  /* 329 */ "(walang laman) o --fullscreen {rom}",
  /* 330 */ "Sandaang porsyento — iyon ang bilis ng console. Pababa, bumabagal ang laro; pataas, humaharurot ito — at sumasabay ang tunog, mas mababa o mas matinis. Sa controller, ang kaliwa at kanan ay lumilipat sa susunod na baitang. Sa panloob na core lang: sariling bilis ang hawak ng panlabas na emulator.",
  /* 331 */ "Lima-limang console",
  /* 332 */ "Direksyonal na pad",
  /* 333 */ "Sa susunod na unang titik",
  /* 334 */ "Sa mga animadong menu, lima-limang laro",
  /* 335 */ "Bilis ng laro",
  /* 336 */ "Kanselahin",
  /* 337 */ "I-drag ang frame, o hilahin ang isang sulok. Inililipat ito ng mga arrow key, at kapag hawak ang Shift ay lumalaki o lumiliit. Kapag lumampas ito sa larawan, nadaragdagan ng transparent na espasyo ang mga gilid: ganito pinalalayo ang cover na masyadong masikip. Sa controller, inililipat ito ng mga direksiyon at ang laki naman ay inaayos ng mga trigger.",
  /* 338 */ "I-crop",
  /* 339 */ "I-crop ang cover",
  /* 340 */ "Buong larawan",
  /* 341 */ "{0} — na-crop ang cover",
  /* 342 */ "{0} — walang cover na i-crop",
  /* 343 */ "hindi mabasa ang cover — {0}",
  /* 344 */ "hindi ma-crop — {0}",
  /* 345 */ "I-crop ang cover…",
  /* 346 */ "Fast forward, hangga't nakapindot ang dalawang stick",
  /* 347 */ "naisantabi ang {0}",
  /* 348 */ "Huminto ang emulator na {0} habang tumatakbo ang “{1}”.",
  /* 349 */ "Huminto ang emulator na {0}.",
  /* 350 */ "Huminto ang emulator",
  /* 351 */ "hindi maisantabi — {0}",
  /* 352 */ "ilagay dito: {0}",
  /* 353 */ "may kulang na system file: {0}",
  /* 354 */ "Mga kredito",
  /* 355 */ "Lisensyang hindi pangkomersyo, mabuting malaman bago ituloy ang gawaing ito: {0}.",
  /* 356 */ "Walang isinusulat na emulator ang EvaChi: pinatutuloy niya sila. Bawat isa ay isang ganap na malayang proyekto, isinulat ng iba, na kinukuha ng EvaChi sa mga may-akda nito kapag kailangan — walang isang linya ng kanilang code ang kinopya rito, walang isang byte ang ipinamamahaging muli. Ang mga pangalan at lisensyang nasa ibaba ay ang mismong idinedeklara ng bawat proyekto.",
  /* 357 */ "Karusel",
  /* 358 */ "Nakaharap ang mga balat, nakasalansan ang mga konsola, may alikabok na pumapaitaas. Parang display stand.",
  /* 359 */ "Gaya ng interface",
  /* 360 */ "Wika ng interface",
  /* 361 */ "Wika ng mga laro",
  /* 362 */ "Wika ng mga laro: {0}. Iiral ito sa susunod na pagbukas.",
  /* 363 */ "Bumalik",
  /* 364 */ "Maghanap",
  /* 365 */ "Hanapin ang mga file",
  /* 366 */ "Maghanap ng halaga",
  /* 367 */ "Iba",
  /* 368 */ "Pareho",
  /* 369 */ "Lapad",
  /* 370 */ "Naglalathala ang proyektong libretro ng mga cheat file, isa kada laro. Ang tanging iniingatan ng EvaChi ay ang eksaktong tumutugma sa inyong laro — parehong pamagat, parehong rehiyon, parehong rebisyon — at mas gugustuhin pa nitong walang imungkahi kaysa isang halos-tama: ang mga code na isinulat para sa ibang bersyon ay hindi sumusulat sa tabi lang, sumusulat sila sa ibang lugar.",
  /* 371 */ "Ang mga cheat",
  /* 372 */ "Mas mababa",
  /* 373 */ "Panel ng cheat",
  /* 374 */ "Mas mataas",
  /* 375 */ "Ulitin",
  /* 376 */ "Mga cheat",
  /* 377 */ "Mga cheat…",
  /* 378 */ "Halaga",
  /* 379 */ "Katumbas ng",
  /* 380 */ "{0} posibleng address",
  /* 381 */ "{0} file ang nailagay, {1} ang inalis",
  /* 382 */ "{0} sa {1} laro ay may file",
  /* 383 */ "{0} byte ng memorya",
  /* 384 */ "{0} halaga ang isinantabi: labas sa memorya ng larong ito",
  /* 385 */ "Walang file para sa larong ito. Ang panel na « Mga cheat… » sa menu ng Emulation ay naghahanap ng isa; kung wala, gumagana ang paghahanap ng halaga sa kahit anong laro.",
  /* 386 */ "Nakapirmi",
  /* 387 */ "Ipirmi",
  /* 388 */ "Maglaro sandali, saka sabihin kung ano ang ginawa ng halaga.",
  /* 389 */ "Naitabi ang laro bago ang unang cheat.",
  /* 390 */ "Naghahanap…",
  /* 391 */ "Ang inilalagay sa « drop u'r rom » ay pupunta sa konsolang itinuturo ng extension nito. Kapag maraming konsola ang may parehong extension — mga disc image — nagtatanong ang EvaChi sa halip na manghula.",
  /* 392 */ "Kumpirmasyon",
  /* 393 */ "Burahin ang save ng laro…",
  /* 394 */ "Pag-unat",
  /* 395 */ "Itinatago ng laro ang mga bilang nito sa memorya nang hindi sinasabi kung saan. Natatagpuan ang mga ito sa pamamagitan ng pagtanggal: sinasabi mo kung ano ang ginawa ng bilang sa screen, at itinatapon ng EvaChi ang mga address na hindi gumawa ng gayon.",
  /* 396 */ "Oo",
  /* 397 */ "Kakaunting konsola ang may sukat ng screen ngayon, kaya may itim na guhit sa magkabilang gilid. Sa zero, pinananatili ng larawan ang sukat nito; sa isandaan, pinupuno nito ang bintana kahit umunat.",
  /* 398 */ "Pag-aayos ng mga laro",
  /* 399 */ "Ayusin",
  /* 400 */ "Ayusin ang mga inilagay na laro…",
  /* 401 */ "Nakikita mong 47 buhay: i-type ang 47 sa « Halaga » at pindutin ang « Maghanap ». Mawalan ng isa, i-type ang 46 at pindutin ang « Katumbas ng ». Kung hindi nakasulat kahit saan ang bilang, iwang walang laman ang « Halaga » at sabihin lamang ang « Mas mataas », « Mas mababa », « Iba » o « Pareho » sa pagitan ng dalawang sandali ng paglalaro. Pagkatapos ay hinahawakan ng « Ipirmi » ang natagpuang halaga. Ang « Lapad » ang laki ng bilang: 1 hanggang 255, 2 kapag lampas, 4 para sa malalaking counter.",
  /* 402 */ "{0} ang naiayos",
  /* 403 */ "walang save na mabubura",
  /* 404 */ "Mga butones",
  /* 405 */ "Nasa aklatan na: {0}",
  /* 406 */ "Burahin ang save ng {0} at magsimulang muli? Ihihinto ang kasalukuyang laro, at mawawala ang lahat ng naitala ng laro.",
  /* 407 */ "Mga trigger",
  /* 408 */ "Itago pareho",
  /* 409 */ "Iwan sa folder",
  /* 410 */ "Walang laman ang folder.",
  /* 411 */ "Palitan ang slot {0}? Mawawala ang nakatago roon.",
  /* 412 */ "nabura ang save — {0}",
  /* 413 */ "Sistema",
  /* 414 */ "Bakantehin ang slot {0}? Mawawala ang nakatago roon.",
  /* 415 */ "Ang dead zone ang bahagi ng stick na itinuturing pa ring nakapahinga. Kapag masyadong maliit, kusang gumagalaw ang tauhan kahit nakapatong lang sa mesa ang kontrol; kapag masyadong malaki, nawawala ang maliliit na galaw. May mga larong humihingi na yugyugin ang konsola: kapag hindi iyon nararamdaman ng kontrol, pinapaniwala iyon ng dalawang pindutan sa ibaba.",
  /* 416 */ "Ang stick",
  /* 417 */ "May sariling mga pindutan ang mga nakatayong emulador, sa sarili nilang file. Ang binabago mo rito ay agad na inililipat doon, para sa mga alam namin mismo ang pormat: PCSX2, PPSSPP at Dolphin. Itinatabi ang lumang setting sa unang pagkakataon, sa parehong pangalan na susundan ng « .avant-evachi ».",
  /* 418 */ "Ilipat sa mga panlabas na emulador",
  /* 419 */ "Dead zone",
  /* 420 */ "Palabas",
  /* 421 */ "Luad",
  /* 422 */ "wala pang panlabas na emulador ang nagsulat ng setting nito",
  /* 423 */ "Baga",
  /* 424 */ "Abo",
  /* 425 */ "Seresa",
  /* 426 */ "Koral",
  /* 427 */ "Baraha",
  /* 428 */ "Kagubatan",
  /* 429 */ "Hamog na yelo",
  /* 430 */ "nasa mga panlabas na emulador na ang mga pindutang ito",
  /* 431 */ "Hatinggabi",
  /* 432 */ "Lumot",
  /* 433 */ "Neon",
  /* 434 */ "Siruwelas",
  /* 435 */ "Buhangin",
  /* 436 */ "Yugyugin",
  /* 437 */ "Sepia",
  /* 438 */ "mga pindutang nailipat: {0}",
  /* 439 */ "Turkesa",
  /* 440 */ "Ang mga takip na hawak nang pamaypay, parang baraha sa kamay. Umiikot ang pulso, at tumutuwid ang kartang binabasa.",
  /* 441 */ "Isang madilim na bulwagan, isang sinag na puno ng alikabok, at ang larong malaking nakaprojekta. Naghihintay ang iba sa tray.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Aprikot",
  /* 444 */ "Heather",
  /* 445 */ "Karamelo",
  /* 446 */ "Tanso",
  /* 447 */ "Tinta",
  /* 448 */ "Famicom",
  /* 449 */ "Jade",
  /* 450 */ "Blueberry",
  /* 451 */ "Bagyo",
  /* 452 */ "Perlas",
  /* 453 */ "Pistatsyo",
  /* 454 */ "Wala",
  /* 455 */ "Mga guhit",
  /* 456 */ "Bawat pixel bilang tatlong siwang: pula, berde at asul",
  /* 457 */ "Ang larawan ng core, pixel kada pixel",
  /* 458 */ "Ang kurbadong salamin, ang mga guhit, ang mga siwang at ang dumidilim na gilid",
  /* 459 */ "Rehas",
  /* 460 */ "Cathode ray tube",
  /* 461 */ "Isa sa bawat dalawang guhit ay pinadilim, gaya sa telebisyon",
  /* 462 */ "Binubuksan ang emulator sa sarili nitong bintana, walang laro",
  /* 463 */ "Buksan",
];
