/**
 * Irlandais (gaeilge) — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * de rang, en commentaire devant chaque entrée, sont là pour qu'on puisse le
 * vérifier à l'œil.
 */

export const ga: readonly string[] = [
  /* 1 */ "Leis an rialtóir",
  /* 2 */ "A tosaigh · X ceanán · Y bearr · L1/R1 consóil · L2/R2 litir · B siar",
  /* 3 */ "Maidir le EvaChi",
  /* 4 */ "Maidir leis…",
  /* 5 */ "Le teacht: scagairí feadán cathóideach, greille picteilíní, línte scanta. Tá an áit ullamh, tiocfaidh na scagairí anseo.",
  /* 6 */ "Athnuaigh an leabharlann",
  /* 7 */ "Amharc",
  /* 8 */ "Taispeáin clúdaigh na gcluichí",
  /* 9 */ "Cabhair",
  /* 10 */ "Cuir fillteán cluichí leis…",
  /* 11 */ "Cuir fillteán leis…",
  /* 12 */ "Brúigh cnaipe ar an rialtóir: lasann an eochair a fhreagraíonn dó. Chun ceann acu a athrú, téigh i mód athshannta, cliceáil an eochair atá le hathrú, ansin brúigh an cnaipe atá uait.",
  /* 13 */ "Argóintí",
  /* 14 */ "Ar an méarchlár",
  /* 15 */ "Gan chluiche",
  /* 16 */ "Níor aimsíodh rialtóir ar bith.",
  /* 17 */ "Leabharlann",
  /* 18 */ "Fuaimeanna roghnaithe ar an rialtóir",
  /* 19 */ "Ní thosaíonn consóil áirithe gan a ndochtearraí bunaidh. Ní féidir le EvaChi iad a sholáthar: cód faoi chóipcheart atá ann, a chóipeáiltear ón meaisín atá agat féin. Deir sí leat, áfach, cé acu atá in easnamh, cén t-ainm atá air, agus cá gcuirfeá é.",
  /* 20 */ "Níl croí libretro ag na consóil seo: clár ar leith is ea a n-aithriseoir, a shuiteálann EvaChi ina fillteán féin agus a thosaíonn caol díreach sa chluiche — gan dul trína roghchlár féin. Is fút féin atá na cluichí, na heochracha agus na comhaid chórais.",
  /* 21 */ "Ní bhaineann na socruithe seo ach leis na croíthe inmheánacha. Tá a chuid féin ag aithriseoir seachtrach, agus ní chuireann EvaChi isteach orthu.",
  /* 22 */ "Ní chuirtear iad seo ar fáil a thuilleadh: níor fhreagair siad an cheistiú, nó thug siad EvaChi anuas leo. Ní shuiteálann an t-athchóiriú arís iad — ní dhéanann sé ach iad a chur ar ais sa liosta.",
  /* 23 */ "Luchtaigh an staid",
  /* 24 */ "Croíthe inmheánacha amháin. Cliceáil aicearra ansin brúigh an eochair nó an cnaipe atá uait; ar an rialtóir tógtar dhá chnaipe in éineacht, mar tá gach ceann acu in úsáid ag an gcluiche cheana.",
  /* 25 */ "Rialuithe",
  /* 26 */ "Rialuithe…",
  /* 27 */ "Consóil le déanaí",
  /* 28 */ "Cláraigh aithriseoir eile",
  /* 29 */ "Treonna / maide clé",
  /* 30 */ "Fillteáin chluichí",
  /* 31 */ "Cuir an t-aithriseoir seo i leataobh",
  /* 32 */ "Tagann siad ó fhreastalaí mionsamhlacha thionscadal libretro, de réir mar a theastaíonn. Gan tic, ní iarrann an leabharlann aon rud ar an líonra.",
  /* 33 */ "Sliotáin sábhála",
  /* 34 */ "Sliotáin…",
  /* 35 */ "Aithriseoirí",
  /* 36 */ "Aithriseoirí curtha i leataobh",
  /* 37 */ "Aithriseoirí seachtracha",
  /* 38 */ "Aithriseoirí seachtracha…",
  /* 39 */ "Aithriseoirí…",
  /* 40 */ "Aithris",
  /* 41 */ "Le linn cluiche, filleadh ar an leabharlann — dhá chnaipe in éineacht, mar tá gach ceann acu in úsáid ag an gcluiche",
  /* 42 */ "Sábháil",
  /* 43 */ "Iarmhíreanna",
  /* 44 */ "Dún",
  /* 45 */ "Comhad",
  /* 46 */ "Comhaid chórais le suiteáil agat féin",
  /* 47 */ "Gailearaí",
  /* 48 */ "Bainistigh na fillteáin…",
  /* 49 */ "Grafaic",
  /* 50 */ "Grafaic…",
  /* 51 */ "Taispeáin an fillteán ina bhfuil do chuid cluichí.",
  /* 52 */ "Suiteáil",
  /* 53 */ "Suiteáil an rogha",
  /* 54 */ "Suiteáil na haithriseoirí…",
  /* 55 */ "Léirmhínitheoir",
  /* 56 */ "Ní gá duit a fhios a bheith agat cá: taispeáin an fillteán ina bhfuil gach rud caite — BIOS, eochracha, dochtearraí, cartlanna, fofhillteáin san áireamh — agus cuireann EvaChi gach comhad san áit cheart, do na croíthe agus do na haithriseoirí neamhspleácha araon. Ní bhogtar an rud nach n-iarrann duine ar bith.",
  /* 57 */ "Clúdaigh",
  /* 58 */ "Loga",
  /* 59 */ "Loga…",
  /* 60 */ "Chríochnaigh an uair dheireanach go dona",
  /* 61 */ "Tosaigh an cluiche, deimhnigh",
  /* 62 */ "Teanga",
  /* 63 */ "Coinnítear an rogha ó thosú go tosú. Seiceáladh gach ceann acu le cinntiú go bhfuil sé inléite: coinníonn an téacs codarsnacht mhaith ar a chúlra i ngach áit.",
  /* 64 */ "Coinnigh é",
  /* 65 */ "Tá na haithriseoirí thíos cumraithe cheana — argóintí agus formáidí san áireamh. Cuardaíonn EvaChi ar do dhiosca iad; ní shuiteálann sí iad.",
  /* 66 */ "Ceangail bhunaidh",
  /* 67 */ "Smúdáil",
  /* 68 */ "Cuir an cluiche leis na ceanáin, nó bain díobh é",
  /* 69 */ "Ceol na roghchlár beo",
  /* 70 */ "Ainm",
  /* 71 */ "Oscail an barra roghchláir",
  /* 72 */ "Oscail an fillteán",
  /* 73 */ "Oscail an fillteán…",
  /* 74 */ "Oscail cluiche…",
  /* 75 */ "in aghaidh an fhráma",
  /* 76 */ "Socruithe an chroí",
  /* 77 */ "Socruithe an chroí…",
  /* 78 */ "Siúl tríd an leabharlann, trí na fuinneoga agus tríd an mbarra roghchláir",
  /* 79 */ "Brabhsáil…",
  /* 80 */ "Sos",
  /* 81 */ "Lánscáileán",
  /* 82 */ "Do na consóil nach bhfuil croí libretro acu. Tosaíonn EvaChi an clár agus an cluiche mar argóint: tosaíonn an t-aithriseoir caol díreach sa chluiche, gan dul trína roghchlár féin.",
  /* 83 */ "Tóg seat scáileáin",
  /* 84 */ "Leagan amach",
  /* 85 */ "Réidh",
  /* 86 */ "Clár",
  /* 87 */ "Roinnt corda fada agus nótaí scaipthe, á gcumadh beo seachas á dtaifeadadh: ní fhilleann an port ar an áit chéanna riamh. Stopann sé uaidh féin a luaithe a thosaíonn cluiche.",
  /* 88 */ "Cuir fillteán in ord…",
  /* 89 */ "Athshann…",
  /* 90 */ "Cuardaigh cluiche…",
  /* 91 */ "Athshocraigh",
  /* 92 */ "Ar ais go dtí an leabharlann",
  /* 93 */ "Dul ar ais, dúnadh",
  /* 94 */ "Sábháil thapa",
  /* 95 */ "Sábháil an staid",
  /* 96 */ "Shaders",
  /* 97 */ "Fuaim",
  /* 98 */ "Start",
  /* 99 */ "Méid na híomhá",
  /* 100 */ "Téamaí",
  /* 101 */ "Téamaí…",
  /* 102 */ "Comhad amháin…",
  /* 103 */ "Cnag gairid agus tú ag athrú cluiche, ceann eile agus tú á thosú. Ar an rialtóir amháin: leis an luch agus leis an méarchlár, braitheann tú an gotha cheana.",
  /* 104 */ "Luas",
  /* 105 */ "Féach ar na seatanna…",
  /* 106 */ "Ní gá duit ach cuid díobh a shuiteáil — ní thagann ar an leabharlann ach na consóil a bhfuil a n-aithriseoir suiteáilte.",
  /* 107 */ "{0} — luchtaithe",
  /* 108 */ "{0} — deaschliceáil chun é a ghlanadh",
  /* 109 */ "{0} — curtha sna ceanáin",
  /* 110 */ "{0} — athshocraithe",
  /* 111 */ "{0} — bainte de na ceanáin",
  /* 112 */ "{0} — á íoslódáil…",
  /* 113 */ "{0}: theip air, féach an loga",
  /* 114 */ "{0} ar fáil",
  /* 115 */ "{0} sábháilte",
  /* 116 */ "is aithriseoir seachtrach é {0}: tosaítear é, ní óstáiltear é",
  /* 117 */ "{0} f/s",
  /* 118 */ "{0} suiteáilte",
  /* 119 */ "{0} suiteáilte — {1}",
  /* 120 */ "{0} suiteáilte agus réidh",
  /* 121 */ "{0} suiteáilte, theip ar {1} — féach an loga",
  /* 122 */ "{0} curtha ar ais",
  /* 123 */ "{0} bainte",
  /* 124 */ "{0} as {1}",
  /* 125 */ "{0} ar an diosca, ach níl croí suiteáilte ar bith a osclaíonn é.",
  /* 126 */ "le fáil ó {0}, ansin “Brabhsáil…”",
  /* 127 */ "le híoslódáil",
  /* 128 */ "in easnamh, roghnach",
  /* 129 */ "Cumasaigh",
  /* 130 */ "Bog",
  /* 131 */ "níorbh fhéidir é a chur leis — {0}",
  /* 132 */ "Oiriúnaigh",
  /* 133 */ "Ómra",
  /* 134 */ "Scláta",
  /* 135 */ "stop — {0}",
  /* 136 */ "tuairt an uair dheireanach — {0}",
  /* 137 */ "ceann ar bith",
  /* 138 */ "níor tugadh croí ar bith ar ais cé go raibh {0} ar eolas — coinníodh an seanliosta",
  /* 139 */ "gan aithriseoir",
  /* 140 */ "Níl aithriseoir ar bith suiteáilte",
  /* 141 */ "Níor aithníodh cluiche ar bith",
  /* 142 */ "Gan toradh",
  /* 143 */ "ceann ar bith",
  /* 144 */ "leabharlann doléite — {0}",
  /* 145 */ "plugáilte isteach",
  /* 146 */ "seat scáileáin",
  /* 147 */ "Athraigh an clúdach…",
  /* 148 */ "Athraigh…",
  /* 149 */ "Gach picteilín ina naoi gcinn",
  /* 150 */ "Gach picteilín ina cheithre cinn: glan, gan díchumadh",
  /* 151 */ "Gach picteilín ina sé cinn déag — do scáileáin mhóra",
  /* 152 */ "Luchtaigh",
  /* 153 */ "Roghnaigh clúdach…",
  /* 154 */ "roghnaigh cluiche sa leabharlann ar dtús",
  /* 155 */ "croí: {0}",
  /* 156 */ "croí gan suiteáil",
  /* 157 */ "Croíthe suiteáilte",
  /* 158 */ "croíthe libretro",
  /* 159 */ "Ardchodarsnacht",
  /* 160 */ "blaosc dhúchasach: {0}",
  /* 161 */ "díluchtú neamhiomlán — {0}",
  /* 162 */ "aimsiú: {0}",
  /* 163 */ "cuireadh isteach ar an aimsiú — {0}",
  /* 164 */ "Roghnaigh clár {0} tú féin",
  /* 165 */ "fillteán curtha leis: {0}",
  /* 166 */ "fillteán oscailte: {0}",
  /* 167 */ "Fillteán réamhshocraithe",
  /* 168 */ "Fillteáin curtha leis",
  /* 169 */ "Esc",
  /* 170 */ "Sliotán {0}",
  /* 171 */ "sliotán {0} — {1}",
  /* 172 */ "An t-aithriseoir a úsáidtear don fhillteán seo",
  /* 173 */ "aithriseoirí seachtracha",
  /* 174 */ "ar siúl",
  /* 175 */ "i láthair",
  /* 176 */ "níorbh fhéidir é a shábháil — {0}",
  /* 177 */ "Enter",
  /* 178 */ "Is féidir le EvaChi iad a íoslódáil ó cheárta oifigiúil libretro. Roghnaigh na consóil a bhfuil suim agat iontu.",
  /* 179 */ "Stop EvaChi agus “{0}” á thosú aici, leis an aithriseoir {1}.",
  /* 180 */ "Stop EvaChi, leis an aithriseoir {0}.",
  /* 181 */ "external_systems → {0} aithriseoir cláraithe",
  /* 182 */ "Ceanán",
  /* 183 */ "Ceanáin",
  /* 184 */ "comhaid chórais doléite — {0}",
  /* 185 */ "Saigheada",
  /* 186 */ "Game Boy",
  /* 187 */ "Eangach",
  /* 188 */ "tá {0} in easnamh ar chonsóil shuiteáilte",
  /* 189 */ "suiteáil críochnaithe: {0}",
  /* 190 */ "Á suiteáil…",
  /* 191 */ "suiteáilte",
  /* 192 */ "suiteáilte ag EvaChi",
  /* 193 */ "Suiteáil",
  /* 194 */ "léirmhínitheoir: {0}",
  /* 195 */ "na croíthe suiteáilte á gceistiú…",
  /* 196 */ "Tosaigh",
  /* 197 */ "Tosaigh an cluiche roghnaithe",
  /* 198 */ "Labhandar",
  /* 199 */ "Na consóil ina rangóid, na cluichí ina gcolún, cúlra ag tonnadh. Ar nós consóil parlúis.",
  /* 200 */ "Tá na himlínte leáite — níos cóngaraí do sheanteilifíseán",
  /* 201 */ "Na clúdaigh go mór, iad á siúl leis an rialtóir. Deartha don tolg.",
  /* 202 */ "Fanann na picteilíní cearnógach, mar a bhí ar an meaisín bunaidh",
  /* 203 */ "ceangail an rialtóra curtha ar ais mar a bhí",
  /* 204 */ "list_cores → {0} chroí fógartha",
  /* 205 */ "Liosta",
  /* 206 */ "liosta na gcroíthe gan fáil — {0}",
  /* 207 */ "liosta na n-aithriseoirí gan fáil — {0}",
  /* 208 */ "Rialtóir",
  /* 209 */ "rialtóir: {0}",
  /* 210 */ "Rialtóir: {0}",
  /* 211 */ "rialtóir dícheangailte",
  /* 212 */ "IN EASNAMH",
  /* 213 */ "Miontas",
  /* 214 */ "Roghchlár beo",
  /* 215 */ "Nuashonraigh",
  /* 216 */ "Cuir sna ceanáin",
  /* 217 */ "curtha i leataobh: {0} · {1}",
  /* 218 */ "níos lú ná nóiméad",
  /* 219 */ "Géar",
  /* 220 */ "tá gá leis an ainm, leis an gclár agus leis na hiarmhíreanna ar fad",
  /* 221 */ "NÍL",
  /* 222 */ "gan suiteáil ar an meaisín seo",
  /* 223 */ "Oíche bhándearg",
  /* 224 */ "Aigéan",
  /* 225 */ "nó",
  /* 226 */ "tá",
  /* 227 */ "níorbh fhéidir é a oscailt — {0}",
  /* 228 */ "leathanach gréasáin: níl ar fáil ach na croíthe inmheánacha, gan leabharlann",
  /* 229 */ "Páipéar",
  /* 230 */ "réamhshocraithe",
  /* 231 */ "Siúl tríd an eangach agus trí na roghchláir bheo",
  /* 232 */ "diúltaíodh don lánscáileán — {0}",
  /* 233 */ "brúigh an cnaipe atá uait ar an rialtóir",
  /* 234 */ "brúigh eochair…",
  /* 235 */ "curtha in ord: {0} · {1}",
  /* 236 */ "níorbh fhéidir é a chur in ord — {0}",
  /* 237 */ "cuireadh isteach ar chuardach na n-aithriseoirí — {0}",
  /* 238 */ "Fuinneog a dhúnadh",
  /* 239 */ "níorbh fhéidir é a athshocrú — {0}",
  /* 240 */ "Líonann sé an fhuinneog agus na cóimheasa á gcoinneáil",
  /* 241 */ "Lean ar aghaidh",
  /* 242 */ "Lean ar aghaidh ón sábháil seo — deaschliceáil chun í a fholmhú",
  /* 243 */ "Cuir ar ais",
  /* 244 */ "níorbh fhéidir é a chur ar ais — {0}",
  /* 245 */ "Bain",
  /* 246 */ "Bain de na ceanáin",
  /* 247 */ "Bain an clúdach",
  /* 248 */ "níorbh fhéidir é a bhaint — {0}",
  /* 249 */ "níl aon rud le cur in ord",
  /* 250 */ "níl aon rud sa bhealach",
  /* 251 */ "Níl aon rud ag teacht le “{0}”.",
  /* 252 */ "Bándearg is bán",
  /* 253 */ "gan íomhá",
  /* 254 */ "Sábháil",
  /* 255 */ "Sábháil anseo",
  /* 256 */ "níorbh fhéidir é a roghnú — {0}",
  /* 257 */ "Bunmhéid an chonsóil, go dtí an picteilín",
  /* 258 */ "Críochnaigh",
  /* 259 */ "téama geal",
  /* 260 */ "téama dorcha",
  /* 261 */ "tá gach rud suiteáilte",
  /* 262 */ "aimsíodh: {0}",
  /* 263 */ "Painéal in aghaidh gach consóil, i dtábla. An ceann is dlúithe leis an luch.",
  /* 264 */ "folamh",
  /* 265 */ "le cur anseo, mar a chuirtear romsets na gcluichí: ní chuardaíonn FinalBurn Neo ach san fhillteán seo",
  /* 266 */ "cuireann sé scáileán fáilte an chonsóil leis",
  /* 267 */ "cód tosaithe an mheaisín",
  /* 268 */ "tosaíonn a lán cluichí dá cheal; ní thosaíonn roghchlár an chonsóil",
  /* 269 */ "BIOS Meiriceánach",
  /* 270 */ "BIOS Meiriceánach agus Eorpach",
  /* 271 */ "BIOS Eorpach",
  /* 272 */ "BIOS Seapánach",
  /* 273 */ "eochracha díchriptithe; dá n-uireasa diúltaítear do dhúmpáil chriptithe",
  /* 274 */ "fillteán Machines ó dháileadh blueMSX, agus Databases lena thaobh",
  /* 275 */ "mar an gcéanna",
  /* 276 */ "riachtanach do chluichí CD, gan tairbhe do chártaí HuCard",
  /* 277 */ "riachtanach do chluichí Mega-CD, gan tairbhe do chartúis",
  /* 278 */ "Kickstart 1.3; dá cheal titeann PUAE ar ais ar AROS, atá saor ach nach bhfuil chomh comhoiriúnach",
  /* 279 */ "Kickstart 3.1; riachtanach do chluichí AGA, nach féidir leis an A500 a rith",
  /* 280 */ "déanann melonDS aithris ar an BIOS de réir réamhshocraithe; tá an ceann ceart níos dílse",
  /* 281 */ "déanann mGBA a cheal; teastaíonn sé ó roinnt cluichí dá scáileán fáilte",
  /* 282 */ "dochtearraí an chonsóil",
  /* 283 */ "dochtearraí an mheaisín",
  /* 284 */ "dochtearraí Panasonic FZ-10; sin an t-ainm a thógann Opera de réir réamhshocraithe",
  /* 285 */ "athraithe ag melonDS, a choinníonn an bunchomhad mar .bak",
  /* 286 */ "clófhoirne",
  /* 287 */ "socruithe agus dáta an chonsóil",
  /* 288 */ "dá cheal ritheann an croí ach fanann an scáileán dubh",
  /* 289 */ "tábla carachtar an chonsóil",
  /* 290 */ "leagan Meiriceánach, do chluichí Sega CD na Stát Aontaithe",
  /* 291 */ "leagan Seapánach, do chluichí Mega-CD na Seapáine",
  /* 292 */ "sheat scáileáin",
  /* 293 */ "seat scáileáin",
  /* 294 */ "seat scáileáin",
  /* 295 */ "seat scáileáin",
  /* 296 */ "sheat scáileáin",
  /* 297 */ "seat scáileáin",
  /* 298 */ "chroí",
  /* 299 */ "gcroí",
  /* 300 */ "croí",
  /* 301 */ "croí",
  /* 302 */ "chroí",
  /* 303 */ "croí",
  /* 304 */ "aithriseoir",
  /* 305 */ "n-aithriseoir",
  /* 306 */ "aithriseoir",
  /* 307 */ "aithriseoir",
  /* 308 */ "aithriseoir",
  /* 309 */ "aithriseoir",
  /* 310 */ "chomhad",
  /* 311 */ "gcomhad",
  /* 312 */ "comhad",
  /* 313 */ "comhad",
  /* 314 */ "chomhad",
  /* 315 */ "comhad",
  /* 316 */ "chluiche",
  /* 317 */ "gcluiche",
  /* 318 */ "cluiche",
  /* 319 */ "cluiche",
  /* 320 */ "chluiche",
  /* 321 */ "cluiche",
  /* 322 */ "Cuirfear conair an chluiche in ionad <code>{rom}</code>. Dá cheal, cuirtear an chonair leis ag an deireadh — sin a mbíonn formhór na n-aithriseoirí ag súil leis.",
  /* 323 */ "<strong>Lasmuigh de chluiche, déantar gach rud leis an rialtóir:</strong> siúlann na treonna tríd an leabharlann, trí na fuinneoga agus tríd an mbarra roghchláir; deimhníonn <strong>A</strong>, téann <strong>B</strong> ar ais, osclaíonn <strong>Start</strong> an barra roghchláir. Le linn cluiche, tugann <strong>Select agus Start in éineacht</strong> ar ais go dtí an leabharlann thú — dhá chnaipe in éineacht, mar tá gach ceann acu in úsáid ag an gcluiche.",
  /* 324 */ "Gan seat scáileáin ar bith. Brúigh <strong>F12</strong> le linn cluiche, nó <strong>Select + Y</strong> ar an rialtóir.",
  /* 325 */ "Teastaíonn a aithriseoir féin ó gach consól. Faigheann EvaChi iad ó cheárta oifigiúil thionscadal libretro, <code>buildbot.libretro.com</code>, agus suiteálann sí ina fillteán féin iad. Ní athdháiltear rud ar bith: is iad na leaganacha a d'fhoilsigh a n-údair féin atá ann.",
  /* 326 */ "Ceithre shliotán in aghaidh an chluiche, coinnithe ar an diosca. Is é an sliotán trom an ceann a úsáideann <strong>F2</strong> agus <strong>F4</strong> — agus <strong>Select + L1</strong> / <strong>Select + R1</strong> ar an rialtóir. Deaschliceáil ar shliotán chun é a fholmhú.",
  /* 327 */ "Ritheann gach aithriseoir ina phróiseas féin: nuair a thiteann sé, feiceann EvaChi é agus filleann sí ar an leabharlann. Cailltear an cluiche atá ar siúl, agus b'fhéidir nár scríobhadh sábháil an chluiche. Má chuirtear an t-aithriseoir seo i leataobh fanann sé suiteáilte ach ní thairgtear a thuilleadh é. Is féidir leat é a chur ar ais am ar bith ó <strong>Comhad → Aithriseoirí</strong>, ag bun na fuinneoige.",
  /* 328 */ "Comhad amháin in aghaidh an chluiche ar an diosca <small> Tagann cluiche ar CD i bhfoirm bileoige <code>.cue</code> agus an oiread comhad <code>.bin</code> agus a bhí de rianta ar an diosca. Ní thosaíonn ach an bhileog: cuirtear na rianta i bhfolach nuair atá sí ann. Gan bhileog, ní chuirtear rud ar bith i bhfolach. </small>",
  /* 329 */ "(folamh) nó --fullscreen {rom}",
  /* 330 */ "Is é céad faoin gcéad luas dílis an chonsóil. Faoina bhun moillíonn an cluiche, os a chionn scinneann sé — agus leanann an fhuaim é, níos doimhne nó níos géire. Ar an rialtán, tugann clé agus deas ó chéim go dtí an chéad chéim eile. Na croíthe inmheánacha amháin: coinníonn aithriseoir seachtrach a luas féin.",
  /* 331 */ "Cúig chonsól san am",
  /* 332 */ "Ceap treo",
  /* 333 */ "Go dtí an chéad litir eile",
  /* 334 */ "Sna roghchláir bheoite, cúig chluiche san am",
  /* 335 */ "Luas an chluiche",
  /* 336 */ "Cealaigh",
  /* 337 */ "Tarraing an fráma, nó beir ar chúinne de. Bogann na heochracha saighde é; le Shift, méadaítear nó laghdaítear é. Má théann sé thar imeall na híomhá, cuirtear stríoca trédhearcacha leis: sin mar a zúmáiltear amach clúdach atá róchúng. Ar an rialtán, bogann na treonna é agus socraíonn na truicir an mhéid.",
  /* 338 */ "Bearr",
  /* 339 */ "Bearr an clúdach",
  /* 340 */ "An íomhá iomlán",
  /* 341 */ "{0} — clúdach bearrtha",
  /* 342 */ "{0} — níl clúdach ann le bearradh",
  /* 343 */ "clúdach doléite — {0}",
  /* 344 */ "níorbh fhéidir bearradh — {0}",
  /* 345 */ "Bearr an clúdach…",
  /* 346 */ "Mearluas, an fhad is atá an dá mhaide analógach brúite isteach",
  /* 347 */ "{0} curtha i leataobh",
  /* 348 */ "Stop an t-aithriseoir {0} le linn “{1}”.",
  /* 349 */ "Stop an t-aithriseoir {0}.",
  /* 350 */ "Tá an t-aithriseoir stoptha",
  /* 351 */ "níorbh fhéidir é a chur i leataobh — {0}",
  /* 352 */ "le cur anseo: {0}",
  /* 353 */ "tá comhad córais in easnamh: {0}",
  /* 354 */ "Creidiúintí",
  /* 355 */ "Ceadúnas neamhthráchtála, rud is maith a bheith ar eolas roimh aon athúsáid: {0}.",
  /* 356 */ "Ní scríobhann EvaChi aithriseoir ar bith: óstáil a dhéanann sí orthu. Is tionscadal saor ann féin é gach ceann acu, scríofa ag daoine eile, agus faigheann EvaChi óna n-údair féin iad de réir mar a theastaíonn — níl líne dá gcód cóipeáilte anseo, níl beart dá gcuid á athdháileadh. Is iad na hainmneacha agus na ceadúnais thíos na cinn a dhearbhaíonn gach tionscadal é féin.",
  /* 357 */ "Roithleán",
  /* 358 */ "Na clúdaigh ar aghaidh, na consóil ina gcruach, deannach ag éirí. Ar nós seastán taispeána.",
];
