/**
 * Galicien — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * numérotées en commentaire sont là pour qu'on puisse le vérifier à l'œil.
 */

export const gl: readonly string[] = [
  /* 1 */ "Co mando",
  /* 2 */ "A iniciar · X favorito · Y recortar · L1/R1 consolas · L2/R2 letra · B volver",
  /* 3 */ "Sobre EvaChi",
  /* 4 */ "Sobre…",
  /* 5 */ "Aínda por chegar: filtros de tubo de raios catódicos, reixa, varrido. O sitio xa está preparado, os filtros virán aquí.",
  /* 6 */ "Actualizar a biblioteca",
  /* 7 */ "Vista",
  /* 8 */ "Amosar as portadas dos xogos",
  /* 9 */ "Axuda",
  /* 10 */ "Engadir un cartafol de xogos…",
  /* 11 */ "Engadir un cartafol…",
  /* 12 */ "Preme un botón do mando: a orde correspondente acéndese. Para cambiar unha, fai clic na caixa de abaixo e preme o botón que queiras. O botón cambia entón de dono: dúas ordes no mesmo botón parecerían unha avaría.",
  /* 13 */ "Argumentos",
  /* 14 */ "Co teclado",
  /* 15 */ "Ningún xogo",
  /* 16 */ "Non se detectou ningún mando.",
  /* 17 */ "Biblioteca",
  /* 18 */ "Sons de selección co mando",
  /* 19 */ "Algunhas consolas non arrincan sen o seu firmware orixinal. EvaChi non pode fornecelo: é código con dereitos de autor, que se copia da máquina que un ten. O que si fai é dicir cal falta, con que nome, e onde deixalo.",
  /* 20 */ "Estas consolas non teñen núcleo libretro: o seu emulador é un programa á parte, que EvaChi instala na súa propia casa e arrinca directamente no xogo — sen pasar polo seu menú. Os xogos, as chaves e os ficheiros de sistema quedan ao seu cargo.",
  /* 21 */ "Estes axustes só tocan os núcleos internos. Un emulador externo ten os seus, e EvaChi non se mete niso.",
  /* 22 */ "Estes xa non se ofrecen: non responderon á consulta, ou fixeron caer a EvaChi. Restauralos non os reinstala — só os devolve á lista.",
  /* 23 */ "Cargar o estado…",
  /* 24 */ "Só núcleos internos. Prema nun atallo e despois na tecla ou no botón desexado; co mando cóllense dous botóns á vez, porque cada un deles xa serve para o xogo.",
  /* 25 */ "Controis",
  /* 26 */ "Controis…",
  /* 27 */ "Consolas recentes",
  /* 28 */ "Declarar outro emulador",
  /* 29 */ "Direccións / stick esquerdo",
  /* 30 */ "Cartafoles de xogos",
  /* 31 */ "Apartar este emulador",
  /* 32 */ "Veñen do servidor de miniaturas do proxecto libretro, baixo demanda. Sen marcar, a biblioteca xa non lle pide nada á rede.",
  /* 33 */ "Espazos de gardado",
  /* 34 */ "Espazos…",
  /* 35 */ "Emuladores",
  /* 36 */ "Emuladores apartados",
  /* 37 */ "Emuladores externos",
  /* 38 */ "Emuladores externos…",
  /* 39 */ "Emuladores…",
  /* 40 */ "Emulación",
  /* 41 */ "Durante a partida, volver á biblioteca — dous botóns á vez, porque cada un deles serve para o xogo",
  /* 42 */ "Gardar",
  /* 43 */ "Extensións",
  /* 44 */ "Pechar",
  /* 45 */ "Ficheiro",
  /* 46 */ "Ficheiros de sistema para poñer un mesmo",
  /* 47 */ "Galería",
  /* 48 */ "Xestionar os cartafoles…",
  /* 49 */ "Gráficos",
  /* 50 */ "Gráficos…",
  /* 51 */ "Indique o cartafol onde están os seus xogos.",
  /* 52 */ "Instalación",
  /* 53 */ "Instalar o escollido",
  /* 54 */ "Instalar os emuladores…",
  /* 55 */ "Intérprete",
  /* 56 */ "Non cómpre saber onde: amose o cartafol onde anda todo — BIOS, chaves, firmware, arquivos, subcartafoles incluídos — e EvaChi leva cada ficheiro ao seu sitio, tanto para os núcleos coma para os emuladores autónomos. O que ninguén reclama non se move.",
  /* 57 */ "Portadas",
  /* 58 */ "Rexistro",
  /* 59 */ "Rexistro…",
  /* 60 */ "A vez anterior acabou mal",
  /* 61 */ "Iniciar o xogo, confirmar",
  /* 62 */ "Idioma",
  /* 63 */ "A escolla consérvase dun arranque para outro. Comprobouse que todos son lexibles: o texto mantén en todas partes contraste abondo sobre o seu fondo.",
  /* 64 */ "Conservalo",
  /* 65 */ "Os emuladores de embaixo xa veñen configurados — argumentos e formatos incluídos. EvaChi búscaos no seu disco; non os instala.",
  /* 66 */ "Asignacións de orixe",
  /* 67 */ "Suavizado",
  /* 68 */ "Marcar o xogo como favorito, ou quitalo",
  /* 69 */ "Música dos menús animados",
  /* 70 */ "Nome",
  /* 71 */ "Abrir a barra de menús",
  /* 72 */ "Abrir o cartafol",
  /* 73 */ "Abrir o cartafol…",
  /* 74 */ "Abrir un xogo…",
  /* 75 */ "por fotograma",
  /* 76 */ "Axustes do núcleo",
  /* 77 */ "Axustes do núcleo…",
  /* 78 */ "Percorrer a biblioteca, as xanelas e a barra de menús",
  /* 79 */ "Examinar…",
  /* 80 */ "Pausa",
  /* 81 */ "Pantalla completa",
  /* 82 */ "Para as consolas sen núcleo libretro. EvaChi arrinca o programa co xogo como argumento: o emulador comeza directamente na partida, sen pasar polo seu propio menú.",
  /* 83 */ "Facer unha captura",
  /* 84 */ "Presentación",
  /* 85 */ "Listo",
  /* 86 */ "Programa",
  /* 87 */ "Uns acordes sostidos e unhas notas soltas, compostos sobre a marcha en vez de gravados: a peza nunca volve polo mesmo sitio. Párase ela soa en canto arrinca un xogo.",
  /* 88 */ "Ordenar un cartafol…",
  /* 89 */ "Baleirar",
  /* 90 */ "Buscar un xogo…",
  /* 91 */ "Reiniciar",
  /* 92 */ "Volver á biblioteca",
  /* 93 */ "Volver atrás, pechar",
  /* 94 */ "Gardado rápido",
  /* 95 */ "Gardar o estado…",
  /* 96 */ "Shaders",
  /* 97 */ "Son",
  /* 98 */ "Start",
  /* 99 */ "Tamaño da imaxe",
  /* 100 */ "Temas",
  /* 101 */ "Temas…",
  /* 102 */ "Un só ficheiro…",
  /* 103 */ "Un chasquido breve ao cambiar de xogo, outro ao inicialo. Só co mando: co rato e co teclado, o xesto xa se sente.",
  /* 104 */ "Velocidade",
  /* 105 */ "Ver as capturas…",
  /* 106 */ "Pode instalar só unha parte — na biblioteca só aparecen as consolas que teñen o emulador instalado.",
  /* 107 */ "{0} — cargado",
  /* 108 */ "{0} — clic dereito para borrar",
  /* 109 */ "{0} — marcado como favorito",
  /* 110 */ "{0} — reiniciado",
  /* 111 */ "{0} — quitado dos favoritos",
  /* 112 */ "{0} — descargando…",
  /* 113 */ "{0}: fallou, vexa o rexistro",
  /* 114 */ "{0} á disposición",
  /* 115 */ "{0} gardado",
  /* 116 */ "{0} é un emulador externo: lánzase, non se aloxa",
  /* 117 */ "{0} img/s",
  /* 118 */ "{0} instalado",
  /* 119 */ "{0} instalado — {1}",
  /* 120 */ "{0} instalado e listo",
  /* 121 */ "{0} instalados, {1} con fallo — vexa o rexistro",
  /* 122 */ "{0} restaurado",
  /* 123 */ "{0} retirado",
  /* 124 */ "{0} de {1}",
  /* 125 */ "{0} no disco, pero ningún núcleo instalado os abre.",
  /* 126 */ "cóllese en {0}, e despois « Examinar… »",
  /* 127 */ "por descargar",
  /* 128 */ "ausente, opcional",
  /* 129 */ "Activar",
  /* 130 */ "Suave",
  /* 131 */ "non se puido engadir — {0}",
  /* 132 */ "Axustar",
  /* 133 */ "Ámbar",
  /* 134 */ "Lousa",
  /* 135 */ "parada — {0}",
  /* 136 */ "parada brusca a vez anterior — {0}",
  /* 137 */ "ningún",
  /* 138 */ "ningún núcleo devolto cando se coñecían {0} — consérvase a lista anterior",
  /* 139 */ "ningún emulador",
  /* 140 */ "Ningún emulador instalado",
  /* 141 */ "Ningún xogo recoñecido",
  /* 142 */ "Sen resultados",
  /* 143 */ "ningunha",
  /* 144 */ "biblioteca ilexible — {0}",
  /* 145 */ "conectado",
  /* 146 */ "captura",
  /* 147 */ "Cambiar a portada…",
  /* 148 */ "Cambiar…",
  /* 149 */ "Cada píxel en nove",
  /* 150 */ "Cada píxel en catro: nítido, sen deformación",
  /* 151 */ "Cada píxel en dezaseis — para as pantallas grandes",
  /* 152 */ "Cargar",
  /* 153 */ "Escoller unha portada…",
  /* 154 */ "escolla primeiro un xogo na biblioteca",
  /* 155 */ "núcleo: {0}",
  /* 156 */ "núcleo non instalado",
  /* 157 */ "Núcleos instalados",
  /* 158 */ "núcleos libretro",
  /* 159 */ "Contraste alto",
  /* 160 */ "envoltorio nativo: {0}",
  /* 161 */ "liberación incompleta — {0}",
  /* 162 */ "descuberta: {0}",
  /* 163 */ "descuberta interrompida — {0}",
  /* 164 */ "Indicar un mesmo o programa de {0}",
  /* 165 */ "cartafol engadido: {0}",
  /* 166 */ "cartafol aberto: {0}",
  /* 167 */ "Cartafol predeterminado",
  /* 168 */ "Cartafoles engadidos",
  /* 169 */ "Esc",
  /* 170 */ "Espazo {0}",
  /* 171 */ "espazo {0} — {1}",
  /* 172 */ "Emulador usado para este cartafol",
  /* 173 */ "emuladores externos",
  /* 174 */ "en curso",
  /* 175 */ "no sitio",
  /* 176 */ "non se puido gardar — {0}",
  /* 177 */ "Intro",
  /* 178 */ "EvaChi pode descargalos da forxa oficial de libretro. Escolla as consolas que lle interesen.",
  /* 179 */ "EvaChi detívose ao iniciar « {0} », co emulador {1}.",
  /* 180 */ "EvaChi detívose, co emulador {0}.",
  /* 181 */ "external_systems → {0} emuladores declarados",
  /* 182 */ "Favorito",
  /* 183 */ "Favoritos",
  /* 184 */ "ficheiros de sistema ilexibles — {0}",
  /* 185 */ "Frechas",
  /* 186 */ "Game Boy",
  /* 187 */ "Grella",
  /* 188 */ "faltan {0} en consolas instaladas",
  /* 189 */ "instalación rematada: {0}",
  /* 190 */ "Instalando…",
  /* 191 */ "instalado",
  /* 192 */ "instalado por EvaChi",
  /* 193 */ "Instalar",
  /* 194 */ "intérprete: {0}",
  /* 195 */ "consultando os núcleos instalados…",
  /* 196 */ "Iniciar",
  /* 197 */ "Iniciar o xogo escollido",
  /* 198 */ "Lavanda",
  /* 199 */ "As consolas en fila, os xogos en columna, un fondo que ondea. Ao xeito dunha consola de salón.",
  /* 200 */ "Os contornos fúndense — máis preto dun televisor vello",
  /* 201 */ "As portadas en grande, percorridas co mando. Pensado para o sofá.",
  /* 202 */ "Os píxeles seguen cadrados, coma na máquina de orixe",
  /* 203 */ "asignacións do mando devoltas ás de orixe",
  /* 204 */ "list_cores → {0} núcleos anunciados",
  /* 205 */ "Lista",
  /* 206 */ "lista de núcleos non dispoñible — {0}",
  /* 207 */ "lista de emuladores non dispoñible — {0}",
  /* 208 */ "Mando",
  /* 209 */ "mando: {0}",
  /* 210 */ "Mando: {0}",
  /* 211 */ "mando desconectado",
  /* 212 */ "FALTA",
  /* 213 */ "Menta",
  /* 214 */ "Menú animado",
  /* 215 */ "Actualizar",
  /* 216 */ "Engadir aos favoritos",
  /* 217 */ "apartado: {0} · {1}",
  /* 218 */ "menos dun minuto",
  /* 219 */ "Nítido",
  /* 220 */ "o nome, o programa e as extensións son todos necesarios",
  /* 221 */ "NON",
  /* 222 */ "non instalado nesta máquina",
  /* 223 */ "Noite rosa",
  /* 224 */ "Océano",
  /* 225 */ "ou",
  /* 226 */ "si",
  /* 227 */ "non se puido abrir — {0}",
  /* 228 */ "páxina web: só están dispoñibles os núcleos internos, sen biblioteca",
  /* 229 */ "Papel",
  /* 230 */ "predeterminado",
  /* 231 */ "Percorrer a grella e os menús animados",
  /* 232 */ "pantalla completa rexeitada — {0}",
  /* 233 */ "prema o botón desexado no mando",
  /* 234 */ "prema unha tecla…",
  /* 235 */ "ordenado: {0} · {1}",
  /* 236 */ "non se puido ordenar — {0}",
  /* 237 */ "busca de emuladores interrompida — {0}",
  /* 238 */ "Pechar unha xanela",
  /* 239 */ "non se puido reiniciar — {0}",
  /* 240 */ "Enche a xanela mantendo as proporcións",
  /* 241 */ "Continuar",
  /* 242 */ "Substituír",
  /* 243 */ "Restaurar",
  /* 244 */ "non se puido restaurar — {0}",
  /* 245 */ "Quitar",
  /* 246 */ "Quitar dos favoritos",
  /* 247 */ "Quitar a portada",
  /* 248 */ "non se puido quitar — {0}",
  /* 249 */ "nada que ordenar",
  /* 250 */ "nada bloquea",
  /* 251 */ "Non hai nada que coincida con « {0} ».",
  /* 252 */ "Rosa e branco",
  /* 253 */ "sen imaxe",
  /* 254 */ "Gardar",
  /* 255 */ "Gardar aquí",
  /* 256 */ "non se puido seleccionar — {0}",
  /* 257 */ "Tamaño de orixe da consola, ao píxel",
  /* 258 */ "Desbotar",
  /* 259 */ "tema claro",
  /* 260 */ "tema escuro",
  /* 261 */ "está todo instalado",
  /* 262 */ "atopado: {0}",
  /* 263 */ "Un panel por consola, en táboa. O máis denso co rato.",
  /* 264 */ "baleiro",
  /* 265 */ "hai que poñelo aquí, coma os romsets dos xogos: FinalBurn Neo só busca neste cartafol",
  /* 266 */ "engade a pantalla de inicio da consola",
  /* 267 */ "arranque da máquina",
  /* 268 */ "moitos xogos arrincan sen el; o menú da consola non",
  /* 269 */ "BIOS americano",
  /* 270 */ "BIOS americano e europeo",
  /* 271 */ "BIOS europeo",
  /* 272 */ "BIOS xaponés",
  /* 273 */ "chaves de descifrado; sen elas rexéitase unha copia cifrada",
  /* 274 */ "cartafol das máquinas da distribución blueMSX, con Databases ao lado",
  /* 275 */ "o mesmo",
  /* 276 */ "imprescindible para os xogos en CD, inútil para as tarxetas HuCard",
  /* 277 */ "imprescindible para os xogos de Mega-CD, inútil para os cartuchos",
  /* 278 */ "Kickstart 1.3; se non, PUAE tira de AROS, libre pero menos compatible",
  /* 279 */ "Kickstart 3.1; necesario para os xogos AGA, que a A500 non sabe mover",
  /* 280 */ "melonDS emula o BIOS por defecto; o de verdade é máis fiel",
  /* 281 */ "mGBA pode sen el; algúns xogos esíxeno para a súa pantalla de inicio",
  /* 282 */ "firmware da consola",
  /* 283 */ "firmware da máquina",
  /* 284 */ "firmware da Panasonic FZ-10; é ese o nome que Opera colle por defecto",
  /* 285 */ "modificado por melonDS, que conserva o orixinal en .bak",
  /* 286 */ "tipos de letra",
  /* 287 */ "axustes e data da consola",
  /* 288 */ "sen el o núcleo funciona pero a pantalla queda negra",
  /* 289 */ "táboa de caracteres da consola",
  /* 290 */ "variante americana, para os xogos de Sega CD dos Estados Unidos",
  /* 291 */ "variante xaponesa, para os xogos de Mega-CD xaponeses",
  /* 292 */ "capturas",
  /* 293 */ "capturas",
  /* 294 */ "captura",
  /* 295 */ "capturas",
  /* 296 */ "capturas",
  /* 297 */ "capturas",
  /* 298 */ "núcleos",
  /* 299 */ "núcleos",
  /* 300 */ "núcleo",
  /* 301 */ "núcleos",
  /* 302 */ "núcleos",
  /* 303 */ "núcleos",
  /* 304 */ "emuladores",
  /* 305 */ "emuladores",
  /* 306 */ "emulador",
  /* 307 */ "emuladores",
  /* 308 */ "emuladores",
  /* 309 */ "emuladores",
  /* 310 */ "ficheiros",
  /* 311 */ "ficheiros",
  /* 312 */ "ficheiro",
  /* 313 */ "ficheiros",
  /* 314 */ "ficheiros",
  /* 315 */ "ficheiros",
  /* 316 */ "xogos",
  /* 317 */ "xogos",
  /* 318 */ "xogo",
  /* 319 */ "xogos",
  /* 320 */ "xogos",
  /* 321 */ "xogos",
  /* 322 */ "<code>{rom}</code> substituirase pola ruta do xogo. Sen el, a ruta engádese ao final — que é o que agarda a maioría dos emuladores.",
  /* 323 */ "<strong>Fóra do xogo, todo se fai co mando:</strong> as direccións percorren a biblioteca, as xanelas e a barra de menús; <strong>A</strong> confirma, <strong>B</strong> volve atrás, <strong>Start</strong> abre a barra de menús. Durante a partida, <strong>Select e Start á vez</strong> devolven á biblioteca — dous botóns ao mesmo tempo, porque cada un deles serve para o xogo.",
  /* 324 */ "Non hai capturas. Prema <strong>F12</strong> durante a partida, ou <strong>Select + Y</strong> no mando.",
  /* 325 */ "Cada consola precisa do seu emulador. EvaChi vai buscalos á forxa oficial do proxecto libretro, <code>buildbot.libretro.com</code>, e instálaos no seu propio cartafol. Non se redistribúe nada: son as versións publicadas polos seus autores.",
  /* 326 */ "Catro espazos por xogo, gardados no disco. Cada xesto está escrito baixo o espazo, e substituír ou baleirar pide confirmación. <strong>F2</strong> e <strong>F4</strong> — e <strong>Select + L1</strong> / <strong>Select + R1</strong> co mando — van directos ao espazo en negra, sen preguntar nada.",
  /* 327 */ "Cada emulador corre no seu propio proceso: cando cae, EvaChi dáse conta e volve á biblioteca. A partida en curso pérdese, e pode que o gardado do xogo non chegase a escribirse. Apartar este emulador déixao instalado pero deixa de ofrecelo. Poderá restauralo cando queira desde <strong>Ficheiro → Emuladores</strong>, ao pé da xanela.",
  /* 328 */ "Un só ficheiro por xogo no disco <small> Un xogo en CD chega nunha folla <code>.cue</code> e en tantos ficheiros <code>.bin</code> como pistas tiña o disco. Só se inicia a folla: as pistas agóchanse cando ela está. Sen folla, non se agocha nada. </small>",
  /* 329 */ "(baleiro) ou --fullscreen {rom}",
  /* 330 */ "O cen por cento é a velocidade propia da consola. Por debaixo o xogo vai máis lento, por riba voa — e o son vai con el, máis grave ou máis agudo. No mando, esquerda e dereita pasan dun paso ao seguinte. Só nos núcleos internos: un emulador externo mantén a súa propia.",
  /* 331 */ "Cinco consolas de cada vez",
  /* 332 */ "Cruceta direccional",
  /* 333 */ "Dunha inicial á seguinte",
  /* 334 */ "Nos menús animados, cinco xogos de cada vez",
  /* 335 */ "Velocidade do xogo",
  /* 336 */ "Cancelar",
  /* 337 */ "Arrastra o marco ou tira dunha esquina. Coas frechas móveo, e con Maiús faino máis grande ou máis pequeno. Se sae da imaxe, engádense bandas transparentes: así se afasta unha portada demasiado axustada. No mando, as direccións móveno e os gatillos axustan o tamaño.",
  /* 338 */ "Recortar",
  /* 339 */ "Recortar a portada",
  /* 340 */ "Imaxe enteira",
  /* 341 */ "{0} — portada recortada",
  /* 342 */ "{0} — non hai portada que recortar",
  /* 343 */ "portada ilexible — {0}",
  /* 344 */ "non se puido recortar — {0}",
  /* 345 */ "Recortar a portada…",
  /* 346 */ "Avance rápido, mentres as dúas pancas sigan premidas",
  /* 347 */ "{0} apartado",
  /* 348 */ "O emulador {0} detívose durante « {1} ».",
  /* 349 */ "O emulador {0} detívose.",
  /* 350 */ "O emulador detívose",
  /* 351 */ "non se puido apartar — {0}",
  /* 352 */ "hai que poñelo aquí: {0}",
  /* 353 */ "falta un ficheiro de sistema: {0}",
  /* 354 */ "Créditos",
  /* 355 */ "Licenza non comercial, que convén saber antes de retomar o traballo: {0}.",
  /* 356 */ "EvaChi non escribe ningún emulador: alóxaos. Cada un é un proxecto libre de seu, escrito por outras persoas, e que EvaChi vai buscar aos seus autores baixo demanda — nin unha liña do código deles se copia aquí, nin un byte se redistribúe. Os nomes e as licenzas de embaixo son os que cada proxecto declara por si mesmo.",
  /* 357 */ "Carrusel",
  /* 358 */ "As carátulas de fronte, as consolas en pila, un po que sobe. Á maneira dun expositor.",
  /* 359 */ "Como a interface",
  /* 360 */ "Idioma da interface",
  /* 361 */ "Idioma dos xogos",
  /* 362 */ "Idioma dos xogos: {0}. Aplicarase no vindeiro arranque.",
  /* 363 */ "Atrás",
  /* 364 */ "Buscar",
  /* 365 */ "Buscar as fichas",
  /* 366 */ "Buscar un valor",
  /* 367 */ "Distinto",
  /* 368 */ "Igual",
  /* 369 */ "Anchura",
  /* 370 */ "O proxecto libretro publica fichas de trucos, unha por xogo. EvaChi só conserva as que encaixan exactamente co seu — mesmo título, mesma rexión, mesma revisión — e prefire non propor nada antes que algo aproximado: os códigos escritos para outra versión non escriben un pouco ao lado, escriben noutro sitio.",
  /* 371 */ "Os trucos",
  /* 372 */ "Menos",
  /* 373 */ "Panel de trucos",
  /* 374 */ "Máis",
  /* 375 */ "Comezar de novo",
  /* 376 */ "Trucos",
  /* 377 */ "Trucos…",
  /* 378 */ "Valor",
  /* 379 */ "Vale",
  /* 380 */ "{0} enderezos posibles",
  /* 381 */ "{0} fichas postas, {1} retiradas",
  /* 382 */ "{0} de {1} xogos teñen ficha",
  /* 383 */ "{0} bytes de memoria",
  /* 384 */ "{0} valores descartados: fóra da memoria deste xogo",
  /* 385 */ "Ningunha ficha para este xogo. O panel « Trucos… » do menú Emulación busca unha; en falta, a busca de valores funciona con calquera xogo.",
  /* 386 */ "Conxelada",
  /* 387 */ "Conxelar",
  /* 388 */ "Xogue un pouco e diga despois que fixo o valor.",
  /* 389 */ "A partida gardouse á parte antes do primeiro truco.",
  /* 390 */ "Buscando…",
  /* 391 */ "O que se deixa en « drop u'r rom » vai cara á consola que indica a súa extensión. Cando varias consolas comparten a mesma — as imaxes de disco — EvaChi pregunta no canto de apostar.",
  /* 392 */ "Confirmación",
  /* 393 */ "Borrar a partida gardada…",
  /* 394 */ "Estiramento",
  /* 395 */ "O xogo garda as súas contas na memoria sen dicir onde. Atópanse por eliminación: dis que fixo o número que se ve, e EvaChi descarta os enderezos que non fixeron o mesmo.",
  /* 396 */ "Si",
  /* 397 */ "Poucas consolas teñen as proporcións dunha pantalla de hoxe, de aí as bandas negras nos lados. En cero a imaxe mantén as súas proporcións; en cen enche a xanela, aínda que se alongue.",
  /* 398 */ "Ordenación dos xogos",
  /* 399 */ "Ordenar",
  /* 400 */ "Ordenar os xogos depositados…",
  /* 401 */ "Ves 47 vidas: escribe 47 en « Valor » e preme « Buscar ». Perde unha, escribe 46 e preme « Vale ». Se o número non está escrito en ningures, deixa « Valor » baleiro e di só « Máis », « Menos », « Distinto » ou « Igual » entre dous momentos de xogo. Despois, « Conxelar » mantén o valor atopado. « Anchura » é o tamaño do número: 1 ata 255, 2 por riba, 4 para os contadores grandes.",
  /* 402 */ "{0} ordenados",
  /* 403 */ "ningunha partida gardada que borrar",
  /* 404 */ "Botóns",
  /* 405 */ "Xa está na biblioteca: {0}",
  /* 406 */ "Borrar a partida gardada de {0} e comezar de cero? A partida en curso deterase e perderase o que o xogo anotara.",
  /* 407 */ "Gatillos",
  /* 408 */ "Conservar ambos",
  /* 409 */ "Deixalo no depósito",
  /* 410 */ "O depósito está baleiro.",
  /* 411 */ "Substituír o espazo {0}? Perderase o que hai gardado nel.",
  /* 412 */ "partida gardada borrada — {0}",
  /* 413 */ "Sistema",
  /* 414 */ "Baleirar o espazo {0}? Perderase o que hai gardado nel.",
  /* 415 */ "A zona morta é a parte da panca na que aínda se considera en repouso. Moi pequena, o personaxe móvese só co mando na mesa; moi grande, os movementos pequenos pérdense. Algúns xogos piden axitar a consola: cando o mando non sabe notalo, os dous botóns de abaixo fanllo crer ao xogo.",
  /* 416 */ "A panca",
  /* 417 */ "Os emuladores autónomos teñen os seus propios botóns, nos seus propios ficheiros. O que cambies aquí trasládase alí de contado, para aqueles dos que coñecemos o formato de primeira man: PCSX2, PPSSPP e Dolphin. A configuración anterior gárdase á parte na primeira pasada, co mesmo nome seguido de « .avant-evachi ».",
  /* 418 */ "Trasladar aos emuladores externos",
  /* 419 */ "Zona morta",
  /* 420 */ "Sesión",
  /* 421 */ "Arxila",
  /* 422 */ "ningún emulador externo escribiu aínda a súa configuración",
  /* 423 */ "Brasa",
  /* 424 */ "Cinza",
  /* 425 */ "Cereixa",
  /* 426 */ "Coral",
  /* 427 */ "Baralla",
  /* 428 */ "Bosque",
  /* 429 */ "Xeada",
  /* 430 */ "os emuladores externos xa tiñan estes botóns",
  /* 431 */ "Medianoite",
  /* 432 */ "Musgo",
  /* 433 */ "Neón",
  /* 434 */ "Ameixa",
  /* 435 */ "Area",
  /* 436 */ "Axitar",
  /* 437 */ "Sepia",
  /* 438 */ "botóns trasladados: {0}",
  /* 439 */ "Turquesa",
  /* 440 */ "As carátulas sostidas en abano, coma unha man de cartas. O pulso xira e a carta que se le endereitase.",
  /* 441 */ "Unha sala ás escuras, un feixe cheo de po e o xogo proxectado en grande. O resto agarda no carro.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Albaricoque",
  /* 444 */ "Breixo",
  /* 445 */ "Caramelo",
  /* 446 */ "Cobre",
  /* 447 */ "Tinta",
  /* 448 */ "Famicom",
  /* 449 */ "Xade",
  /* 450 */ "Arando",
  /* 451 */ "Tormenta",
  /* 452 */ "Perla",
  /* 453 */ "Pistacho",
];
