/**
 * Croate — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros portés en commentaire sont là pour qu'on puisse le vérifier à
 * l'œil, ligne à ligne.
 */

export const hr: readonly string[] = [
  /* 1 */ "Na kontroleru",
  /* 2 */ "A pokreni · X favorit · Y obreži · L1/R1 konzole · L2/R2 slovo · B natrag",
  /* 3 */ "O EvaChi",
  /* 4 */ "O programu…",
  /* 5 */ "Ono što je televizor s katodnom cijevi radio sa slikom i što su igre onog doba uzimale zdravo za gotovo. Vrijedi samo za jezgre koje se igraju ovdje: samostalni emulator sam crta svoju sliku.",
  /* 6 */ "Osvježi knjižnicu",
  /* 7 */ "Prikaz",
  /* 8 */ "Prikazuj omote igara",
  /* 9 */ "Pomoć",
  /* 10 */ "Dodaj mapu s igrama…",
  /* 11 */ "Dodaj mapu…",
  /* 12 */ "Pritisnite tipku na upravljaču: odgovarajuća naredba se upali. Da biste neku promijenili, kliknite polje ispod i pritisnite željenu tipku. Tipka tada mijenja vlasnika: dvije naredbe na istoj tipki izgledale bi kao kvar.",
  /* 13 */ "Argumenti",
  /* 14 */ "Na tipkovnici",
  /* 15 */ "Nema igara",
  /* 16 */ "Nije pronađen nijedan kontroler.",
  /* 17 */ "Knjižnica",
  /* 18 */ "Zvukovi odabira na kontroleru",
  /* 19 */ "Neke se konzole ne pokreću bez izvornog firmvera. EvaChi ga ne može isporučiti: to je kod pod autorskim pravom, koji se prepisuje sa stroja koji posjedujete. Zato vam kaže koji nedostaje, pod kojim imenom i kamo ga staviti.",
  /* 20 */ "Ove konzole nemaju libretro jezgru: njihov je emulator zaseban program koji EvaChi instalira kod sebe i pokreće ravno u igri — bez njegova izbornika. Igre, ključevi i sistemske datoteke ostaju na vama.",
  /* 21 */ "Ove postavke vrijede samo za ugrađene jezgre. Vanjski emulator ima svoje, a EvaChi se u njih ne miješa.",
  /* 22 */ "Ovi se više ne nude: nisu odgovorili na upit ili su srušili EvaChi. Vraćanje ih ne instalira ponovno — samo ih vraća na popis.",
  /* 23 */ "Učitaj stanje…",
  /* 24 */ "Samo ugrađene jezgre. Kliknite prečac pa pritisnite željenu tipku ili gumb; na kontroleru se uzimaju dva gumba odjednom jer svaki od njih već služi igri.",
  /* 25 */ "Upravljanje",
  /* 26 */ "Upravljanje…",
  /* 27 */ "Nedavne konzole",
  /* 28 */ "Dodaj drugi emulator",
  /* 29 */ "Smjerovi / lijeva palica",
  /* 30 */ "Mape s igrama",
  /* 31 */ "Isključi ovaj emulator",
  /* 32 */ "Dolaze s poslužitelja sličica projekta libretro, po potrebi. Kad je isključeno, knjižnica više ništa ne traži s mreže.",
  /* 33 */ "Mjesta spremanja",
  /* 34 */ "Mjesta spremanja…",
  /* 35 */ "Emulatori",
  /* 36 */ "Isključeni emulatori",
  /* 37 */ "Vanjski emulatori",
  /* 38 */ "Vanjski emulatori…",
  /* 39 */ "Emulatori…",
  /* 40 */ "Emulacija",
  /* 41 */ "Tijekom igre, povratak u knjižnicu — dva gumba odjednom jer svaki od njih služi igri",
  /* 42 */ "Spremi",
  /* 43 */ "Nastavci",
  /* 44 */ "Zatvori",
  /* 45 */ "Datoteka",
  /* 46 */ "Sistemske datoteke koje instalirate sami",
  /* 47 */ "Galerija",
  /* 48 */ "Upravljanje mapama…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Pokažite mapu u kojoj su vaše igre.",
  /* 52 */ "Instalacija",
  /* 53 */ "Instaliraj odabrano",
  /* 54 */ "Instaliraj emulatore…",
  /* 55 */ "Tumač",
  /* 56 */ "Ne morate znati kamo: pokažite mapu u kojoj sve leži — BIOS-i, ključevi, firmveri, arhive, podmape uključene — i EvaChi će svaku datoteku odnijeti na pravo mjesto, i za jezgre i za samostalne emulatore. Što nitko ne traži, ne miče se s mjesta.",
  /* 57 */ "Omoti",
  /* 58 */ "Dnevnik",
  /* 59 */ "Dnevnik…",
  /* 60 */ "Prošli put je loše završilo",
  /* 61 */ "Pokretanje igre, potvrda",
  /* 62 */ "Jezik",
  /* 63 */ "Odabir se pamti od pokretanja do pokretanja. Svaka je provjereno čitljiva: tekst posvuda ima dovoljan kontrast prema podlozi.",
  /* 64 */ "Zadrži ga",
  /* 65 */ "Emulatori u nastavku već su podešeni — s argumentima i formatima. EvaChi ih traži na vašem disku; ne instalira ih.",
  /* 66 */ "Izvorne tipke",
  /* 67 */ "Zaglađivanje",
  /* 68 */ "Dodavanje igre u favorite ili uklanjanje",
  /* 69 */ "Glazba animiranih izbornika",
  /* 70 */ "Naziv",
  /* 71 */ "Otvaranje trake izbornika",
  /* 72 */ "Otvori mapu",
  /* 73 */ "Otvori mapu…",
  /* 74 */ "Otvori igru…",
  /* 75 */ "po sličici",
  /* 76 */ "Postavke jezgre",
  /* 77 */ "Postavke jezgre…",
  /* 78 */ "Kretanje knjižnicom, prozorima i trakom izbornika",
  /* 79 */ "Pregledaj…",
  /* 80 */ "Pauza",
  /* 81 */ "Cijeli zaslon",
  /* 82 */ "Za konzole bez libretro jezgre. EvaChi pokreće program s igrom kao argumentom: emulator kreće ravno u igru, bez svog izbornika.",
  /* 83 */ "Snimi zaslon",
  /* 84 */ "Raspored",
  /* 85 */ "Spremno",
  /* 86 */ "Program",
  /* 87 */ "Nekoliko izdržanih akorda i pokoji rasuti ton, skladani u hodu umjesto snimljeni: skladba nikad dvaput ne prođe istim putem. Sama prestaje čim igra krene.",
  /* 88 */ "Razvrstaj mapu…",
  /* 89 */ "Isprazni",
  /* 90 */ "Traži igru…",
  /* 91 */ "Ponovno pokreni",
  /* 92 */ "Povratak u knjižnicu",
  /* 93 */ "Povratak, zatvaranje",
  /* 94 */ "Brzo spremanje",
  /* 95 */ "Spremi stanje…",
  /* 96 */ "Shaderi",
  /* 97 */ "Zvuk",
  /* 98 */ "Start",
  /* 99 */ "Veličina slike",
  /* 100 */ "Teme",
  /* 101 */ "Teme…",
  /* 102 */ "Samo jedna datoteka…",
  /* 103 */ "Kratak klik pri prelasku s igre na igru, još jedan pri pokretanju. Samo na kontroleru: uz miš i tipkovnicu pokret se ionako osjeti.",
  /* 104 */ "Brzina",
  /* 105 */ "Pogledaj snimke…",
  /* 106 */ "Možete instalirati i samo dio njih — u knjižnici se pojavljuju samo konzole čiji je emulator instaliran.",
  /* 107 */ "{0} — učitano",
  /* 108 */ "{0} — desni klik briše",
  /* 109 */ "{0} — dodano u favorite",
  /* 110 */ "{0} — ponovno pokrenuto",
  /* 111 */ "{0} — uklonjeno iz favorita",
  /* 112 */ "{0} — preuzimanje…",
  /* 113 */ "{0}: neuspjeh, pogledajte dnevnik",
  /* 114 */ "{0} na raspolaganju",
  /* 115 */ "{0} spremljen",
  /* 116 */ "{0} je vanjski emulator: pokreće se, ne ugošćuje se",
  /* 117 */ "{0} sl/s",
  /* 118 */ "{0} instaliran",
  /* 119 */ "{0} instaliran — {1}",
  /* 120 */ "{0} instaliran i spreman",
  /* 121 */ "{0} instalirano, {1} neuspjelo — pogledajte dnevnik",
  /* 122 */ "{0} vraćen",
  /* 123 */ "{0} uklonjen",
  /* 124 */ "{0} od {1}",
  /* 125 */ "{0} na disku, ali nijedna instalirana jezgra ih ne otvara.",
  /* 126 */ "uzima se s {0}, zatim „Pregledaj…”",
  /* 127 */ "za preuzimanje",
  /* 128 */ "nedostaje, nije obavezno",
  /* 129 */ "Uključi",
  /* 130 */ "Mekano",
  /* 131 */ "dodavanje nije uspjelo — {0}",
  /* 132 */ "Prilagodi",
  /* 133 */ "Jantar",
  /* 134 */ "Škriljevac",
  /* 135 */ "zaustavljeno — {0}",
  /* 136 */ "prošli put naglo prekinuto — {0}",
  /* 137 */ "nijedan",
  /* 138 */ "nijedna jezgra nije vraćena, a poznato ih je bilo {0} — zadržan prethodni popis",
  /* 139 */ "nema emulatora",
  /* 140 */ "Nijedan emulator nije instaliran",
  /* 141 */ "Nijedna igra nije prepoznata",
  /* 142 */ "Nema rezultata",
  /* 143 */ "nijedna",
  /* 144 */ "knjižnica se ne da pročitati — {0}",
  /* 145 */ "priključen",
  /* 146 */ "snimka zaslona",
  /* 147 */ "Promijeni omot…",
  /* 148 */ "Promijeni…",
  /* 149 */ "Svaki piksel na devet",
  /* 150 */ "Svaki piksel na četiri: oštro, bez izobličenja",
  /* 151 */ "Svaki piksel na šesnaest — za velike zaslone",
  /* 152 */ "Učitaj",
  /* 153 */ "Odaberi omot…",
  /* 154 */ "najprije odaberite igru u knjižnici",
  /* 155 */ "jezgra: {0}",
  /* 156 */ "jezgra nije instalirana",
  /* 157 */ "Instalirane jezgre",
  /* 158 */ "libretro jezgre",
  /* 159 */ "Visoki kontrast",
  /* 160 */ "izvorna ljuska: {0}",
  /* 161 */ "nepotpuno isključivanje — {0}",
  /* 162 */ "otkrivanje: {0}",
  /* 163 */ "otkrivanje prekinuto — {0}",
  /* 164 */ "Sami odredite program za {0}",
  /* 165 */ "mapa dodana: {0}",
  /* 166 */ "mapa otvorena: {0}",
  /* 167 */ "Zadana mapa",
  /* 168 */ "Dodane mape",
  /* 169 */ "Esc",
  /* 170 */ "Mjesto {0}",
  /* 171 */ "mjesto {0} — {1}",
  /* 172 */ "Emulator za ovu mapu",
  /* 173 */ "vanjski emulatori",
  /* 174 */ "u tijeku",
  /* 175 */ "na mjestu",
  /* 176 */ "spremanje nije uspjelo — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi ih može preuzeti sa službene libretro radionice. Odaberite konzole koje vas zanimaju.",
  /* 179 */ "EvaChi se zaustavila pokrećući „{0}”, s emulatorom {1}.",
  /* 180 */ "EvaChi se zaustavila, s emulatorom {0}.",
  /* 181 */ "external_systems → prijavljeno emulatora: {0}",
  /* 182 */ "Favorit",
  /* 183 */ "Favoriti",
  /* 184 */ "sistemske datoteke se ne mogu pročitati — {0}",
  /* 185 */ "Strelice",
  /* 186 */ "Game Boy",
  /* 187 */ "Mreža",
  /* 188 */ "instaliranim konzolama nedostaje {0}",
  /* 189 */ "instalacija dovršena: {0}",
  /* 190 */ "Instalacija…",
  /* 191 */ "instaliran",
  /* 192 */ "instalirao EvaChi",
  /* 193 */ "Instaliraj",
  /* 194 */ "tumač: {0}",
  /* 195 */ "ispitivanje instaliranih jezgri…",
  /* 196 */ "Pokreni",
  /* 197 */ "Pokreni odabranu igru",
  /* 198 */ "Lavanda",
  /* 199 */ "Konzole u redu, igre u stupcu, pozadina koja se talasa. Kao na kućnoj konzoli.",
  /* 200 */ "Rubovi su stopljeni — bliže starom televizoru",
  /* 201 */ "Omoti u velikom, listaju se kontrolerom. Zamišljeno za kauč.",
  /* 202 */ "Pikseli ostaju četvrtasti, kao na izvornom stroju",
  /* 203 */ "tipke kontrolera vraćene na izvorne",
  /* 204 */ "list_cores → najavljeno jezgri: {0}",
  /* 205 */ "Popis",
  /* 206 */ "popis jezgri nije dostupan — {0}",
  /* 207 */ "popis emulatora nije dostupan — {0}",
  /* 208 */ "Kontroler",
  /* 209 */ "kontroler: {0}",
  /* 210 */ "Kontroler: {0}",
  /* 211 */ "kontroler odspojen",
  /* 212 */ "NEDOSTAJE",
  /* 213 */ "Metvica",
  /* 214 */ "Animirani izbornik",
  /* 215 */ "Ažuriraj",
  /* 216 */ "Dodaj u favorite",
  /* 217 */ "isključeno: {0} · {1}",
  /* 218 */ "manje od minute",
  /* 219 */ "Oštro",
  /* 220 */ "potrebni su naziv, program i nastavci",
  /* 221 */ "NE",
  /* 222 */ "nije instaliran na ovom računalu",
  /* 223 */ "Ružičasta noć",
  /* 224 */ "Ocean",
  /* 225 */ "ili",
  /* 226 */ "da",
  /* 227 */ "otvaranje nije uspjelo — {0}",
  /* 228 */ "web-stranica: dostupne su samo ugrađene jezgre, bez knjižnice",
  /* 229 */ "Papir",
  /* 230 */ "zadano",
  /* 231 */ "Kretanje mrežom i animiranim izbornicima",
  /* 232 */ "cijeli zaslon odbijen — {0}",
  /* 233 */ "pritisnite željeni gumb na kontroleru",
  /* 234 */ "pritisnite tipku…",
  /* 235 */ "razvrstavanje: {0} · {1}",
  /* 236 */ "razvrstavanje nije uspjelo — {0}",
  /* 237 */ "traženje emulatora prekinuto — {0}",
  /* 238 */ "Zatvaranje prozora",
  /* 239 */ "ponovno pokretanje nije uspjelo — {0}",
  /* 240 */ "Ispunjava prozor uz očuvanje omjera",
  /* 241 */ "Nastavi",
  /* 242 */ "Zamijeni",
  /* 243 */ "Vrati",
  /* 244 */ "vraćanje nije uspjelo — {0}",
  /* 245 */ "Ukloni",
  /* 246 */ "Ukloni iz favorita",
  /* 247 */ "Ukloni omot",
  /* 248 */ "uklanjanje nije uspjelo — {0}",
  /* 249 */ "nema se što razvrstati",
  /* 250 */ "ništa ne priječi",
  /* 251 */ "Ništa ne odgovara upitu „{0}”.",
  /* 252 */ "Ružičasto i bijelo",
  /* 253 */ "bez slike",
  /* 254 */ "Spremi",
  /* 255 */ "Spremi ovdje",
  /* 256 */ "odabir nije uspio — {0}",
  /* 257 */ "Izvorna veličina konzole, na piksel točno",
  /* 258 */ "Baci",
  /* 259 */ "svijetla tema",
  /* 260 */ "tamna tema",
  /* 261 */ "sve je instalirano",
  /* 262 */ "pronađeno: {0}",
  /* 263 */ "Jedan odjeljak po konzoli, u tablici. Najzbijenije uz miš.",
  /* 264 */ "prazno",
  /* 265 */ "stavlja se ovamo, kao i romsetovi igara: FinalBurn Neo traži samo u ovoj mapi",
  /* 266 */ "dodaje početni zaslon konzole",
  /* 267 */ "pokretački kod stroja",
  /* 268 */ "mnoge se igre pokreću i bez njega; izbornik konzole ne",
  /* 269 */ "američki BIOS",
  /* 270 */ "američki i europski BIOS",
  /* 271 */ "europski BIOS",
  /* 272 */ "japanski BIOS",
  /* 273 */ "ključevi za dešifriranje; bez njih se šifrirani zapis odbija",
  /* 274 */ "mapa Machines iz blueMSX distribucije, a uz nju Databases",
  /* 275 */ "isto",
  /* 276 */ "nužno za CD igre, nepotrebno za HuCard kartice",
  /* 277 */ "nužno za Mega-CD igre, nepotrebno za kartridže",
  /* 278 */ "Kickstart 1.3; inače PUAE poseže za AROS-om, slobodnim ali slabije usklađenim",
  /* 279 */ "Kickstart 3.1; potreban za AGA igre, koje A500 ne zna pokrenuti",
  /* 280 */ "melonDS prema zadanom oponaša BIOS; pravi je vjerniji",
  /* 281 */ "mGBA ga ne treba; neke ga igre traže zbog svog početnog zaslona",
  /* 282 */ "firmver konzole",
  /* 283 */ "firmver stroja",
  /* 284 */ "firmver Panasonic FZ-10; to je ime koje Opera uzima prema zadanom",
  /* 285 */ "mijenja ga melonDS, koji izvornik čuva kao .bak",
  /* 286 */ "fontovi",
  /* 287 */ "postavke i datum konzole",
  /* 288 */ "bez njega jezgra radi, ali zaslon ostaje crn",
  /* 289 */ "tablica znakova konzole",
  /* 290 */ "američka inačica, za Sega CD igre iz Sjedinjenih Država",
  /* 291 */ "japanska inačica, za japanske Mega-CD igre",
  /* 292 */ "snimke zaslona",
  /* 293 */ "snimaka zaslona",
  /* 294 */ "snimka zaslona",
  /* 295 */ "snimaka zaslona",
  /* 296 */ "snimke zaslona",
  /* 297 */ "snimaka zaslona",
  /* 298 */ "jezgre",
  /* 299 */ "jezgri",
  /* 300 */ "jezgra",
  /* 301 */ "jezgri",
  /* 302 */ "jezgre",
  /* 303 */ "jezgri",
  /* 304 */ "emulatora",
  /* 305 */ "emulatora",
  /* 306 */ "emulator",
  /* 307 */ "emulatora",
  /* 308 */ "emulatora",
  /* 309 */ "emulatora",
  /* 310 */ "datoteke",
  /* 311 */ "datoteka",
  /* 312 */ "datoteka",
  /* 313 */ "datoteka",
  /* 314 */ "datoteke",
  /* 315 */ "datoteka",
  /* 316 */ "igre",
  /* 317 */ "igara",
  /* 318 */ "igra",
  /* 319 */ "igara",
  /* 320 */ "igre",
  /* 321 */ "igara",
  /* 322 */ "<code>{rom}</code> bit će zamijenjen putanjom do igre. Bez njega se putanja dodaje na kraj — što i očekuje većina emulatora.",
  /* 323 */ "<strong>Izvan igre sve ide preko kontrolera:</strong> smjerovi vode kroz knjižnicu, prozore i traku izbornika; <strong>A</strong> potvrđuje, <strong>B</strong> vraća natrag, <strong>Start</strong> otvara traku izbornika. Tijekom igre <strong>Select i Start zajedno</strong> vraćaju u knjižnicu — dva gumba odjednom jer svaki od njih služi igri.",
  /* 324 */ "Nema snimaka. Pritisnite <strong>F12</strong> tijekom igre ili <strong>Select + Y</strong> na kontroleru.",
  /* 325 */ "Svaka konzola treba svoj emulator. EvaChi ih donosi sa službene radionice projekta libretro, <code>buildbot.libretro.com</code>, i instalira ih u vlastitu mapu. Ništa se ne raspačava: to su inačice koje su objavili njihovi autori.",
  /* 326 */ "Četiri mjesta po igri, čuvana na disku. Svaka je radnja napisana ispod mjesta, a zamjena ili pražnjenje traže potvrdu. <strong>F2</strong> i <strong>F4</strong> — te <strong>Select + L1</strong> / <strong>Select + R1</strong> na upravljaču — idu ravno na podebljano mjesto, ne pitajući ništa.",
  /* 327 */ "Svaki emulator radi u vlastitom procesu: kad padne, EvaChi to vidi i vraća se u knjižnicu. Igra u tijeku izgubljena je, a spremanje igre možda nije ni zapisano. Isključivanje tog emulatora ostavlja ga instaliranim, ali ga se prestaje nuditi. Možete ga vratiti u svakom trenutku preko <strong>Datoteka → Emulatori</strong>, na dnu prozora.",
  /* 328 */ "Samo jedna datoteka po igri na disku <small> Igra s CD-a dolazi kao <code>.cue</code> listić i onoliko <code>.bin</code> datoteka koliko je disk imao staza. Pokreće se samo listić: staze su skrivene dok je on tu. Bez listića ništa nije skriveno. </small>",
  /* 329 */ "(prazno) ili --fullscreen {rom}",
  /* 330 */ "Sto posto je vlastita brzina konzole. Ispod toga igra se vuče, iznad leti — a zvuk ide za njom, dublji ili viši. Na kontroleru lijevo i desno pomiču brzinu s jedne stepenice na sljedeću. Samo unutarnje jezgre: vanjski emulator zadržava svoju.",
  /* 331 */ "Pet konzola odjednom",
  /* 332 */ "Smjerne tipke",
  /* 333 */ "Na sljedeće početno slovo",
  /* 334 */ "U animiranim izbornicima, pet igara odjednom",
  /* 335 */ "Brzina igre",
  /* 336 */ "Odustani",
  /* 337 */ "Povucite okvir ili uhvatite jedan njegov kut. Strelice ga pomiču, a sa Shiftom se povećava ili smanjuje. Kad okvir izađe izvan slike, oko omota se pojave prozirne trake: tako se omot koji je pretijesan prikaže šire. Na kontroleru smjerovi pomiču okvir, a okidači mu mijenjaju veličinu.",
  /* 338 */ "Obreži",
  /* 339 */ "Obreži omot",
  /* 340 */ "Cijela slika",
  /* 341 */ "{0} — omot obrezan",
  /* 342 */ "{0} — nema omota za obrezivanje",
  /* 343 */ "omot nečitljiv — {0}",
  /* 344 */ "obrezivanje nije uspjelo — {0}",
  /* 345 */ "Obreži omot…",
  /* 346 */ "Brzo premotavanje naprijed, dok su obje palice pritisnute",
  /* 347 */ "{0} isključen",
  /* 348 */ "Emulator {0} se zaustavio tijekom „{1}”.",
  /* 349 */ "Emulator {0} se zaustavio.",
  /* 350 */ "Emulator se zaustavio",
  /* 351 */ "isključivanje nije uspjelo — {0}",
  /* 352 */ "stavlja se ovamo: {0}",
  /* 353 */ "nedostaje sistemska datoteka: {0}",
  /* 354 */ "Zasluge",
  /* 355 */ "Nekomercijalna licencija, dobro je znati prije nego što se ovaj posao preuzme: {0}.",
  /* 356 */ "EvaChi ne piše nijedan emulator: ona ih ugošćuje. Svaki je od njih zaseban slobodan projekt, koji su napisali drugi, a EvaChi ga po potrebi donosi od njegovih autora — nijedan redak njihova koda nije ovdje prepisan, nijedan se bajt ne raspačava. Imena i licencije u nastavku svaki projekt navodi sam.",
  /* 357 */ "Vrtuljak",
  /* 358 */ "Omoti sprijeda, konzole na hrpi, prašina koja se diže. Poput izložbenog stalka.",
  /* 359 */ "Kao sučelje",
  /* 360 */ "Jezik sučelja",
  /* 361 */ "Jezik igara",
  /* 362 */ "Jezik igara: {0}. Vrijedit će od sljedećeg pokretanja.",
  /* 363 */ "Natrag",
  /* 364 */ "Traži",
  /* 365 */ "Pronađi datoteke",
  /* 366 */ "Traži vrijednost",
  /* 367 */ "Drukčije",
  /* 368 */ "Jednako",
  /* 369 */ "Širina",
  /* 370 */ "Projekt libretro objavljuje datoteke s varanjima, jednu po igri. EvaChi zadržava samo one koje točno odgovaraju vašoj igri — isti naslov, ista regija, ista revizija — i radije ne predlaže ništa nego nešto približno: kodovi pisani za drugu inačicu ne pišu malo pokraj, nego posve drugdje.",
  /* 371 */ "Varanja",
  /* 372 */ "Manje",
  /* 373 */ "Ploča varanja",
  /* 374 */ "Više",
  /* 375 */ "Ispočetka",
  /* 376 */ "Varanja",
  /* 377 */ "Varanja…",
  /* 378 */ "Vrijednost",
  /* 379 */ "Jednako je",
  /* 380 */ "{0} mogućih adresa",
  /* 381 */ "{0} datoteka postavljeno, {1} uklonjeno",
  /* 382 */ "{0} od {1} igara ima datoteku",
  /* 383 */ "{0} bajtova memorije",
  /* 384 */ "{0} vrijednosti odbačeno: izvan memorije ove igre",
  /* 385 */ "Nema datoteke za ovu igru. Ploča „Varanja…“ u izborniku Emulacija traži jednu; inače pretraga vrijednosti radi na svakoj igri.",
  /* 386 */ "Zamrznuta",
  /* 387 */ "Zamrzni",
  /* 388 */ "Odigrajte malo pa recite što je vrijednost učinila.",
  /* 389 */ "Igra je odložena prije prvog varanja.",
  /* 390 */ "Traženje…",
  /* 391 */ "Ono što se ostavi u « drop u'r rom » odlazi konzoli koju njegov nastavak označava. Kad isti nastavak dijeli više konzola — preslike diskova — EvaChi radije pita nego da nagađa.",
  /* 392 */ "Potvrda",
  /* 393 */ "Obriši spremljenu igru…",
  /* 394 */ "Rastezanje",
  /* 395 */ "Igra drži svoje brojeve u memoriji, a ne kaže gdje. Nalaze se izbacivanjem: kažete što je učinio broj koji vidite, a EvaChi odbacuje adrese koje nisu učinile isto.",
  /* 396 */ "Da",
  /* 397 */ "Malo konzola ima omjere današnjeg zaslona, otuda crne trake sa strane. Na nuli slika zadržava svoje omjere; na sto ispunjava prozor, makar se rastegnula.",
  /* 398 */ "Razvrstavanje igara",
  /* 399 */ "Razvrstaj",
  /* 400 */ "Razvrstaj ostavljene igre…",
  /* 401 */ "Vidite 47 života: upišite 47 u « Vrijednost » i pritisnite « Traži ». Izgubite jedan, upišite 46 i pritisnite « Jednako je ». Ako broj nigdje nije ispisan, ostavite « Vrijednost » praznom i između dva trenutka igre recite samo « Više », « Manje », « Drukčije » ili « Jednako ». Nađenu vrijednost zatim drži « Zamrzni ». « Širina » je veličina broja: 1 do 255, 2 iznad toga, 4 za velike brojače.",
  /* 402 */ "razvrstano: {0}",
  /* 403 */ "nema spremljene igre za brisanje",
  /* 404 */ "Tipke",
  /* 405 */ "Već u knjižnici: {0}",
  /* 406 */ "Obrisati spremljenu igru {0} i krenuti ispočetka? Tekuća će se igra zaustaviti, a ono što je igra zabilježila bit će izgubljeno.",
  /* 407 */ "Okidači",
  /* 408 */ "Zadrži oboje",
  /* 409 */ "Ostavi u mapi",
  /* 410 */ "Mapa je prazna.",
  /* 411 */ "Zamijeniti mjesto {0}? Ono što je ondje spremljeno bit će izgubljeno.",
  /* 412 */ "spremljena igra obrisana — {0}",
  /* 413 */ "Sustav",
  /* 414 */ "Isprazniti mjesto {0}? Ono što je ondje spremljeno bit će izgubljeno.",
  /* 415 */ "Mrtva zona je onaj dio palice u kojem se još smatra da miruje. Premala — lik se sam pomiče dok upravljač leži na stolu; prevelika — sitni pokreti se gube. Neke igre traže da se konzola protrese: kad to upravljač ne zna osjetiti, dvije tipke ispod natjeraju igru da u to povjeruje.",
  /* 416 */ "Palica",
  /* 417 */ "Samostalni emulatori imaju vlastite tipke, u vlastitim datotekama. Ono što ovdje promijenite prenosi se onamo odmah — za one čiji format poznajemo iz prve ruke: PCSX2, PPSSPP i Dolphin. Stara postavka odlaže se u prvom prolazu, pod istim imenom iza kojeg slijedi « .avant-evachi ».",
  /* 418 */ "Prenesi u vanjske emulatore",
  /* 419 */ "Mrtva zona",
  /* 420 */ "Projekcija",
  /* 421 */ "Glina",
  /* 422 */ "nijedan vanjski emulator još nije zapisao svoje postavke",
  /* 423 */ "Žeravica",
  /* 424 */ "Pepeo",
  /* 425 */ "Trešnja",
  /* 426 */ "Koralj",
  /* 427 */ "Špil",
  /* 428 */ "Šuma",
  /* 429 */ "Inje",
  /* 430 */ "vanjski emulatori već su imali ove tipke",
  /* 431 */ "Ponoć",
  /* 432 */ "Mahovina",
  /* 433 */ "Neon",
  /* 434 */ "Šljiva",
  /* 435 */ "Pijesak",
  /* 436 */ "Protresi",
  /* 437 */ "Sepija",
  /* 438 */ "prenesene tipke: {0}",
  /* 439 */ "Tirkiz",
  /* 440 */ "Omoti držani u lepezi, poput karata u ruci. Zapešće se okreće, a karta koja se čita uspravlja.",
  /* 441 */ "Mračna dvorana, snop pun prašine i igra projicirana u velikom. Ostali čekaju u spremniku.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Marelica",
  /* 444 */ "Vrijesak",
  /* 445 */ "Karamela",
  /* 446 */ "Bakar",
  /* 447 */ "Tinta",
  /* 448 */ "Famicom",
  /* 449 */ "Žad",
  /* 450 */ "Borovnica",
  /* 451 */ "Oluja",
  /* 452 */ "Biser",
  /* 453 */ "Pistacija",
  /* 454 */ "Nijedan",
  /* 455 */ "Crte",
  /* 456 */ "Svaki piksel u tri proreza: crveni, zeleni i plavi",
  /* 457 */ "Slika jezgre, piksel po piksel",
  /* 458 */ "Ispupčeno staklo, crte, prorezi i ugašeni rubovi",
  /* 459 */ "Rešetka",
  /* 460 */ "Katodna cijev",
  /* 461 */ "Svaki drugi redak potamnjen, kao na televizoru",
];
