/**
 * Le hongrois — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * marques numérotées sont là pour qu'on puisse le vérifier à l'œil.
 *
 * Le hongrois garde le nom au singulier après un nombre — « 3 játék », jamais
 * « 3 játékok » : les six catégories de pluriel portent donc la même forme.
 */

export const hu: readonly string[] = [
  /* 1 */ "Kontrolleren",
  /* 2 */ "A indítás · X kedvenc · Y levágás · L1/R1 konzolok · L2/R2 betű · B vissza",
  /* 3 */ "Az EvaChi névjegye",
  /* 4 */ "Névjegy…",
  /* 5 */ "Amit egy képcsöves televízió tett a képpel, és amit a kor játékai magától értetődőnek vettek. Csak az itt futtatott magokra vonatkozik: az önálló emulátor maga rajzolja a képét.",
  /* 6 */ "Könyvtár frissítése",
  /* 7 */ "Nézet",
  /* 8 */ "Játékborítók megjelenítése",
  /* 9 */ "Súgó",
  /* 10 */ "Játékmappa hozzáadása…",
  /* 11 */ "Mappa hozzáadása…",
  /* 12 */ "Nyomjon meg egy gombot a kontrolleren: a hozzá tartozó parancs felgyullad. Ha módosítani szeretne egyet, kattintson az alatta lévő mezőre, majd nyomja meg a kívánt gombot. A gomb ekkor gazdát cserél: két parancs ugyanazon a gombon hibának tűnne.",
  /* 13 */ "Argumentumok",
  /* 14 */ "Billentyűzeten",
  /* 15 */ "Nincs játék",
  /* 16 */ "Nem található kontroller.",
  /* 17 */ "Könyvtár",
  /* 18 */ "Kiválasztási hangok a kontrolleren",
  /* 19 */ "Egyes konzolok nem indulnak el az eredeti firmware nélkül. Az EvaChi nem tudja mellékelni: szerzői joggal védett kód, amelyet a saját készülékéről kell átmásolni. Azt viszont megmondja, melyik hiányzik, milyen néven, és hová kell tenni.",
  /* 20 */ "Ezeknek a konzoloknak nincs libretro magjuk: az emulátoruk külön program, amelyet az EvaChi a saját mappájába telepít, és egyenesen a játékba indít — az emulátor saját menüje nélkül. A játékokról, a kulcsokról és a rendszerfájlokról továbbra is önnek kell gondoskodnia.",
  /* 21 */ "Ezek a beállítások csak a beépített magokra vonatkoznak. A külső emulátornak megvannak a sajátjai, azokba az EvaChi nem szól bele.",
  /* 22 */ "Ezeket már nem ajánlja fel: nem válaszoltak a lekérdezésre, vagy magukkal rántották az EvaChit. A visszaállítás nem telepíti újra őket — csak visszakerülnek a listába.",
  /* 23 */ "Állás betöltése…",
  /* 24 */ "Csak a beépített magok. Kattintson egy gyorsbillentyűre, majd nyomja meg a kívánt billentyűt vagy gombot; a kontrolleren két gomb kell egyszerre, mert külön-külön mindegyikre szükség van a játékban.",
  /* 25 */ "Vezérlés",
  /* 26 */ "Vezérlés…",
  /* 27 */ "Legutóbbi konzolok",
  /* 28 */ "Másik emulátor megadása",
  /* 29 */ "Iránygombok / bal kar",
  /* 30 */ "Játékmappák",
  /* 31 */ "Emulátor félretétele",
  /* 32 */ "A libretro projekt miniatűr-kiszolgálójáról érkeznek, igény szerint. Kikapcsolva a könyvtár semmit sem kér a hálózattól.",
  /* 33 */ "Mentési helyek",
  /* 34 */ "Mentési helyek…",
  /* 35 */ "Emulátorok",
  /* 36 */ "Félretett emulátorok",
  /* 37 */ "Külső emulátorok",
  /* 38 */ "Külső emulátorok…",
  /* 39 */ "Emulátorok…",
  /* 40 */ "Emuláció",
  /* 41 */ "Játék közben vissza a könyvtárba — két gomb egyszerre, mert külön-külön mindegyikre szükség van a játékban",
  /* 42 */ "Mentés",
  /* 43 */ "Kiterjesztések",
  /* 44 */ "Bezárás",
  /* 45 */ "Fájl",
  /* 46 */ "Saját kezűleg telepítendő rendszerfájlok",
  /* 47 */ "Galéria",
  /* 48 */ "Mappák kezelése…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Adja meg a mappát, ahol a játékai vannak.",
  /* 52 */ "Telepítés",
  /* 53 */ "Kijelöltek telepítése",
  /* 54 */ "Emulátorok telepítése…",
  /* 55 */ "Értelmező",
  /* 56 */ "Nem kell tudnia, hova: mutassa meg a mappát, ahol minden együtt hever — BIOS, kulcsok, firmware-ek, archívumok, almappákkal együtt —, és az EvaChi minden fájlt a helyére visz, a magokhoz és az önálló emulátorokhoz egyaránt. Amit senki sem kér, az a helyén marad.",
  /* 57 */ "Borítók",
  /* 58 */ "Napló",
  /* 59 */ "Napló…",
  /* 60 */ "A legutóbbi indítás rosszul végződött",
  /* 61 */ "Játék indítása, jóváhagyás",
  /* 62 */ "Nyelv",
  /* 63 */ "A választás indításról indításra megmarad. Mindegyiket ellenőriztük, hogy olvasható legyen: a szöveg mindenütt elég kontrasztos marad a háttéren.",
  /* 64 */ "Megtartás",
  /* 65 */ "Az alábbi emulátorok már be vannak állítva — az argumentumokkal és a formátumokkal együtt. Az EvaChi megkeresi őket a lemezen; telepíteni nem telepíti őket.",
  /* 66 */ "Eredeti kiosztás",
  /* 67 */ "Simítás",
  /* 68 */ "Játék felvétele a kedvencek közé vagy kivétele onnan",
  /* 69 */ "Az animált menük zenéje",
  /* 70 */ "Név",
  /* 71 */ "Menüsor megnyitása",
  /* 72 */ "Mappa megnyitása",
  /* 73 */ "Mappa megnyitása…",
  /* 74 */ "Játék megnyitása…",
  /* 75 */ "képkockánként",
  /* 76 */ "A mag beállításai",
  /* 77 */ "A mag beállításai…",
  /* 78 */ "Mozgás a könyvtárban, az ablakokban és a menüsorban",
  /* 79 */ "Tallózás…",
  /* 80 */ "Szünet",
  /* 81 */ "Teljes képernyő",
  /* 82 */ "A libretro mag nélküli konzolokhoz. Az EvaChi a játékot argumentumként adja át a programnak: az emulátor egyenesen a játékba lép, a saját menüje nélkül.",
  /* 83 */ "Képernyőkép készítése",
  /* 84 */ "Elrendezés",
  /* 85 */ "Kész",
  /* 86 */ "Program",
  /* 87 */ "Néhány kitartott akkord és elszórt hang, menet közben születik, nem felvételről szól: a darab soha nem tér vissza ugyanoda. Magától elhallgat, amint egy játék elindul.",
  /* 88 */ "Mappa rendezése…",
  /* 89 */ "Ürítés",
  /* 90 */ "Játék keresése…",
  /* 91 */ "Alaphelyzet",
  /* 92 */ "Vissza a könyvtárba",
  /* 93 */ "Visszalépés, bezárás",
  /* 94 */ "Gyors mentés",
  /* 95 */ "Állás mentése…",
  /* 96 */ "Shaderek",
  /* 97 */ "Hang",
  /* 98 */ "Start",
  /* 99 */ "Képméret",
  /* 100 */ "Témák",
  /* 101 */ "Témák…",
  /* 102 */ "Egyetlen fájl…",
  /* 103 */ "Rövid kattanás, amikor játékról játékra lép, és még egy, amikor elindítja. Csak kontrolleren: egérrel és billentyűzettel úgyis érezni a mozdulatot.",
  /* 104 */ "Sebesség",
  /* 105 */ "Képernyőképek megtekintése…",
  /* 106 */ "Nem kell mindet telepítenie — a könyvtárban csak azok a konzolok jelennek meg, amelyeknek az emulátora telepítve van.",
  /* 107 */ "{0} — betöltve",
  /* 108 */ "{0} — jobb kattintás a törléshez",
  /* 109 */ "{0} — kedvenc lett",
  /* 110 */ "{0} — alaphelyzetbe állítva",
  /* 111 */ "{0} — kikerült a kedvencek közül",
  /* 112 */ "{0} — letöltés…",
  /* 113 */ "{0}: sikertelen, lásd a naplót",
  /* 114 */ "{0} elérhető",
  /* 115 */ "{0} mentve",
  /* 116 */ "{0} külső emulátor: elindítani lehet, otthont adni neki nem",
  /* 117 */ "{0} kép/mp",
  /* 118 */ "{0} telepítve",
  /* 119 */ "{0} telepítve — {1}",
  /* 120 */ "{0} telepítve, indulásra kész",
  /* 121 */ "{0} telepítve, {1} sikertelen — lásd a naplót",
  /* 122 */ "{0} visszaállítva",
  /* 123 */ "{0} eltávolítva",
  /* 124 */ "{0} / {1}",
  /* 125 */ "{0} a lemezen, de egyik telepített mag sem nyitja meg.",
  /* 126 */ "innen szerezhető be: {0}, majd „Tallózás…”",
  /* 127 */ "letöltendő",
  /* 128 */ "hiányzik, nem kötelező",
  /* 129 */ "Bekapcsolás",
  /* 130 */ "Lágy",
  /* 131 */ "nem sikerült hozzáadni — {0}",
  /* 132 */ "Igazítás",
  /* 133 */ "Borostyán",
  /* 134 */ "Palaszürke",
  /* 135 */ "leállt — {0}",
  /* 136 */ "legutóbb váratlanul leállt — {0}",
  /* 137 */ "nincs",
  /* 138 */ "egyetlen magot sem adott vissza, pedig {0} volt ismert — marad az előző lista",
  /* 139 */ "nincs emulátor",
  /* 140 */ "Nincs telepített emulátor",
  /* 141 */ "Nincs felismert játék",
  /* 142 */ "Nincs találat",
  /* 143 */ "nincs",
  /* 144 */ "a könyvtár olvashatatlan — {0}",
  /* 145 */ "csatlakoztatva",
  /* 146 */ "képernyőkép",
  /* 147 */ "Borító cseréje…",
  /* 148 */ "Csere…",
  /* 149 */ "Egy pixelből kilenc lesz",
  /* 150 */ "Egy pixelből négy: éles, torzítás nélkül",
  /* 151 */ "Egy pixelből tizenhat — nagy képernyőkre",
  /* 152 */ "Betöltés",
  /* 153 */ "Borító választása…",
  /* 154 */ "előbb válasszon játékot a könyvtárból",
  /* 155 */ "mag: {0}",
  /* 156 */ "a mag nincs telepítve",
  /* 157 */ "Telepített magok",
  /* 158 */ "libretro magok",
  /* 159 */ "Nagy kontraszt",
  /* 160 */ "natív héj: {0}",
  /* 161 */ "a leválasztás nem fejeződött be — {0}",
  /* 162 */ "felderítés: {0}",
  /* 163 */ "a felderítés megszakadt — {0}",
  /* 164 */ "A(z) {0} programjának megadása",
  /* 165 */ "mappa hozzáadva: {0}",
  /* 166 */ "mappa megnyitva: {0}",
  /* 167 */ "Alapértelmezett mappa",
  /* 168 */ "Hozzáadott mappák",
  /* 169 */ "Esc",
  /* 170 */ "{0}. hely",
  /* 171 */ "{0}. hely — {1}",
  /* 172 */ "Ehhez a mappához használt emulátor",
  /* 173 */ "külső emulátorok",
  /* 174 */ "folyamatban",
  /* 175 */ "a helyén",
  /* 176 */ "a mentés nem sikerült — {0}",
  /* 177 */ "Enter",
  /* 178 */ "Az EvaChi le tudja tölteni őket a libretro hivatalos build-kiszolgálójáról. Válassza ki az önt érdeklő konzolokat.",
  /* 179 */ "Az EvaChi leállt a(z) „{0}” indítása közben, a(z) {1} emulátorral.",
  /* 180 */ "Az EvaChi leállt, a(z) {0} emulátorral.",
  /* 181 */ "external_systems → {0} emulátor bejelentve",
  /* 182 */ "Kedvenc",
  /* 183 */ "Kedvencek",
  /* 184 */ "a rendszerfájlok olvashatatlanok — {0}",
  /* 185 */ "Nyílbillentyűk",
  /* 186 */ "Game Boy",
  /* 187 */ "Rács",
  /* 188 */ "telepített konzolokról hiányzik {0}",
  /* 189 */ "a telepítés befejeződött: {0}",
  /* 190 */ "Telepítés…",
  /* 191 */ "telepítve",
  /* 192 */ "az EvaChi telepítette",
  /* 193 */ "Telepítés",
  /* 194 */ "értelmező: {0}",
  /* 195 */ "a telepített magok lekérdezése…",
  /* 196 */ "Indítás",
  /* 197 */ "A kiválasztott játék indítása",
  /* 198 */ "Levendula",
  /* 199 */ "Konzolok sorban, játékok oszlopban, hullámzó háttér. Nappali konzol módjára.",
  /* 200 */ "Az élek elmosódnak — közelebb egy régi tévéhez",
  /* 201 */ "Nagy borítók, kontrollerrel lapozva. A kanapéra tervezve.",
  /* 202 */ "A pixelek négyzetek maradnak, mint az eredeti gépen",
  /* 203 */ "a kontroller kiosztása visszaállt az eredetire",
  /* 204 */ "list_cores → {0} mag bejelentve",
  /* 205 */ "Lista",
  /* 206 */ "a magok listája nem érhető el — {0}",
  /* 207 */ "az emulátorok listája nem érhető el — {0}",
  /* 208 */ "Kontroller",
  /* 209 */ "kontroller: {0}",
  /* 210 */ "Kontroller: {0}",
  /* 211 */ "a kontrollert kihúzták",
  /* 212 */ "HIÁNYZIK",
  /* 213 */ "Menta",
  /* 214 */ "Hullámmenü",
  /* 215 */ "Frissítés",
  /* 216 */ "Kedvencek közé",
  /* 217 */ "félretéve: {0} · {1}",
  /* 218 */ "kevesebb mint egy perc",
  /* 219 */ "Éles",
  /* 220 */ "a név, a program és a kiterjesztések mind kellenek",
  /* 221 */ "NEM",
  /* 222 */ "ezen a gépen nincs telepítve",
  /* 223 */ "Rózsaszín éjszaka",
  /* 224 */ "Óceán",
  /* 225 */ "vagy",
  /* 226 */ "igen",
  /* 227 */ "a megnyitás nem sikerült — {0}",
  /* 228 */ "weboldal: csak a beépített magok érhetők el, könyvtár nélkül",
  /* 229 */ "Papír",
  /* 230 */ "alapértelmezett",
  /* 231 */ "Mozgás a rácsban és az animált menükben",
  /* 232 */ "a teljes képernyő nem sikerült — {0}",
  /* 233 */ "nyomja meg a kívánt gombot a kontrolleren",
  /* 234 */ "nyomjon meg egy billentyűt…",
  /* 235 */ "rendezés: {0} · {1}",
  /* 236 */ "a rendezés nem sikerült — {0}",
  /* 237 */ "az emulátorok keresése megszakadt — {0}",
  /* 238 */ "Ablak bezárása",
  /* 239 */ "az alaphelyzetbe állítás nem sikerült — {0}",
  /* 240 */ "Kitölti az ablakot, megtartva az arányokat",
  /* 241 */ "Folytatás",
  /* 242 */ "Csere",
  /* 243 */ "Visszaállítás",
  /* 244 */ "a visszaállítás nem sikerült — {0}",
  /* 245 */ "Eltávolítás",
  /* 246 */ "Kivétel a kedvencek közül",
  /* 247 */ "Borító eltávolítása",
  /* 248 */ "az eltávolítás nem sikerült — {0}",
  /* 249 */ "nincs mit rendezni",
  /* 250 */ "semmi sem akadályozza",
  /* 251 */ "Nincs találat erre: „{0}”.",
  /* 252 */ "Rózsaszín és fehér",
  /* 253 */ "nincs kép",
  /* 254 */ "Mentés",
  /* 255 */ "Mentés ide",
  /* 256 */ "a kiválasztás nem sikerült — {0}",
  /* 257 */ "A konzol eredeti mérete, pixelre pontosan",
  /* 258 */ "Eldobás",
  /* 259 */ "világos téma",
  /* 260 */ "sötét téma",
  /* 261 */ "minden telepítve van",
  /* 262 */ "megtalálva: {0}",
  /* 263 */ "Konzolonként egy szakasz, táblázatba rendezve. Egérrel ez a legsűrűbb.",
  /* 264 */ "üres",
  /* 265 */ "ide kell másolni, akárcsak a játékok romsetjeit: a FinalBurn Neo csak ebben a mappában keres",
  /* 266 */ "hozzáadja a konzol indítóképernyőjét",
  /* 267 */ "a gép indító ROM-ja",
  /* 268 */ "sok játék elindul nélküle; a konzol menüje nem",
  /* 269 */ "amerikai BIOS",
  /* 270 */ "amerikai és európai BIOS",
  /* 271 */ "európai BIOS",
  /* 272 */ "japán BIOS",
  /* 273 */ "visszafejtő kulcsok; nélkülük a titkosított másolatot nem fogadja el",
  /* 274 */ "a blueMSX csomag Machines mappája, mellette a Databases",
  /* 275 */ "ugyanaz",
  /* 276 */ "a CD-s játékokhoz nélkülözhetetlen, a HuCard kártyákhoz felesleges",
  /* 277 */ "a Mega-CD játékokhoz nélkülözhetetlen, a kazettákhoz felesleges",
  /* 278 */ "Kickstart 1.3; enélkül a PUAE az AROS-ra vált, ami szabad, de kevésbé kompatibilis",
  /* 279 */ "Kickstart 3.1; az AGA játékokhoz kell, amelyeket az A500 nem tud futtatni",
  /* 280 */ "a melonDS alapból emulálja a BIOS-t; az igazi hűbb",
  /* 281 */ "az mGBA elvan nélküle; néhány játék az indítóképernyőjéhez kéri",
  /* 282 */ "a konzol firmware-e",
  /* 283 */ "a gép firmware-e",
  /* 284 */ "Panasonic FZ-10 firmware; alapból ezt a nevet várja az Opera",
  /* 285 */ "a melonDS módosítja, az eredetit .bak néven megőrzi",
  /* 286 */ "betűkészletek",
  /* 287 */ "a konzol beállításai és dátuma",
  /* 288 */ "nélküle a mag fut, de a képernyő fekete marad",
  /* 289 */ "a konzol karaktertáblája",
  /* 290 */ "amerikai változat, az egyesült államokbeli Sega CD játékokhoz",
  /* 291 */ "japán változat, a japán Mega-CD játékokhoz",
  /* 292 */ "képernyőkép",
  /* 293 */ "képernyőkép",
  /* 294 */ "képernyőkép",
  /* 295 */ "képernyőkép",
  /* 296 */ "képernyőkép",
  /* 297 */ "képernyőkép",
  /* 298 */ "mag",
  /* 299 */ "mag",
  /* 300 */ "mag",
  /* 301 */ "mag",
  /* 302 */ "mag",
  /* 303 */ "mag",
  /* 304 */ "emulátor",
  /* 305 */ "emulátor",
  /* 306 */ "emulátor",
  /* 307 */ "emulátor",
  /* 308 */ "emulátor",
  /* 309 */ "emulátor",
  /* 310 */ "fájl",
  /* 311 */ "fájl",
  /* 312 */ "fájl",
  /* 313 */ "fájl",
  /* 314 */ "fájl",
  /* 315 */ "fájl",
  /* 316 */ "játék",
  /* 317 */ "játék",
  /* 318 */ "játék",
  /* 319 */ "játék",
  /* 320 */ "játék",
  /* 321 */ "játék",
  /* 322 */ "<code>{rom}</code> helyére a játék elérési útja kerül. Nélküle az elérési út a végére kerül — a legtöbb emulátor is ezt várja.",
  /* 323 */ "<strong>Játékon kívül minden a kontrollerrel megy:</strong> az iránygombokkal mozoghat a könyvtárban, az ablakokban és a menüsorban; az <strong>A</strong> jóváhagy, a <strong>B</strong> visszalép, a <strong>Start</strong> megnyitja a menüsort. Játék közben a <strong>Select és a Start együtt</strong> visszavisz a könyvtárba — két gomb egyszerre, mert külön-külön mindegyikre szükség van a játékban.",
  /* 324 */ "Nincs képernyőkép. Nyomja meg az <strong>F12</strong> billentyűt játék közben, vagy a <strong>Select + Y</strong> gombokat a kontrolleren.",
  /* 325 */ "Minden konzolhoz kell a saját emulátora. Az EvaChi a libretro projekt hivatalos build-kiszolgálójáról, a <code>buildbot.libretro.com</code> címről hozza el őket, és a saját mappájába telepíti. Semmit nem terjeszt tovább: ezek a szerzőik által közzétett kiadások.",
  /* 326 */ "Négy hely játékonként, a lemezen megőrizve. Minden művelet a hely alatt olvasható, a csere és az ürítés pedig megerősítést kér. Az <strong>F2</strong> és az <strong>F4</strong> — és a kontrolleren a <strong>Select + L1</strong> / <strong>Select + R1</strong> — kérdés nélkül egyenesen a félkövér helyre megy.",
  /* 327 */ "Minden emulátor a saját folyamatában fut: ha elesik, az EvaChi észreveszi, és visszatér a könyvtárba. Az éppen futó játék elvész, és a játék mentése talán nem íródott ki. Ha félreteszi ezt az emulátort, telepítve marad, csak nem ajánlja fel többé. Bármikor visszaállíthatja a <strong>Fájl → Emulátorok</strong> menüpontból, az ablak alján.",
  /* 328 */ "Játékonként egyetlen fájl a lemezen <small> A CD-s játék egy <code>.cue</code> leíróból és annyi <code>.bin</code> fájlból áll, ahány sávja a lemeznek volt. Csak a leíró indul el: mellette a sávok rejtve maradnak. Leíró nélkül semmi sincs elrejtve. </small>",
  /* 329 */ "(üres) vagy --fullscreen {rom}",
  /* 330 */ "Száz százalék a konzol saját sebessége. Ez alatt a játék lelassul, fölötte száguld – és a hang is követi, mélyebben vagy élesebben. A kontrolleren a balra és a jobbra egyik fokozatról a másikra lép. Csak a belső magokra vonatkozik: a külső emulátor a sajátját tartja meg.",
  /* 331 */ "Öt konzol egyszerre",
  /* 332 */ "Iránykereszt",
  /* 333 */ "Kezdőbetűről a következőre",
  /* 334 */ "Az animált menükben öt játék egyszerre",
  /* 335 */ "Játék sebessége",
  /* 336 */ "Mégse",
  /* 337 */ "Húzza a keretet, vagy fogja meg az egyik sarkát. A nyilakkal mozgathatja, Shifttel nagyíthatja vagy kicsinyítheti. Ha a keret kilóg a képből, átlátszó sávok kerülnek a borító köré: így tud kicsinyíteni egy túl szűk borítót. Kontrolleren az iránygombok mozgatják, a ravaszok pedig a méretét állítják.",
  /* 338 */ "Levágás",
  /* 339 */ "Borító levágása",
  /* 340 */ "Teljes kép",
  /* 341 */ "{0} — borító levágva",
  /* 342 */ "{0} — nincs levágható borító",
  /* 343 */ "olvashatatlan borító — {0}",
  /* 344 */ "nem sikerült a levágás — {0}",
  /* 345 */ "Borító levágása…",
  /* 346 */ "Gyorsítás, amíg mindkét kart nyomva tartja",
  /* 347 */ "{0} félretéve",
  /* 348 */ "A(z) {0} emulátor leállt a(z) „{1}” futása közben.",
  /* 349 */ "A(z) {0} emulátor leállt.",
  /* 350 */ "Az emulátor leállt",
  /* 351 */ "nem sikerült a félretétel — {0}",
  /* 352 */ "ide kell tenni: {0}",
  /* 353 */ "hiányzik egy rendszerfájl: {0}",
  /* 354 */ "Köszönetnyilvánítás",
  /* 355 */ "Nem kereskedelmi licenc, tudnivaló minden továbbhasznosítás előtt: {0}.",
  /* 356 */ "Az EvaChi egyetlen emulátort sem ír: helyet ad nekik. Mindegyikük teljes értékű, önálló szabad projekt, amelyet mások írtak, és amelyet az EvaChi kérésre a szerzőitől hoz el — egyetlen soruk sincs ide másolva, egyetlen bájtjukat sem terjeszti tovább. Az alábbi nevek és licencek azok, amelyeket az egyes projektek maguk adnak meg.",
  /* 357 */ "Körhinta",
  /* 358 */ "A borítók szemből, a konzolok egymáson, felszálló por. Mint egy kirakat.",
  /* 359 */ "Mint a felület",
  /* 360 */ "A felület nyelve",
  /* 361 */ "A játékok nyelve",
  /* 362 */ "A játékok nyelve: {0}. A következő indítástól érvényes.",
  /* 363 */ "Vissza",
  /* 364 */ "Keresés",
  /* 365 */ "Fájlok keresése",
  /* 366 */ "Érték keresése",
  /* 367 */ "Más",
  /* 368 */ "Ugyanaz",
  /* 369 */ "Szélesség",
  /* 370 */ "A libretro projekt csalásfájlokat tesz közzé, játékonként egyet. Az EvaChi csak azokat tartja meg, amelyek pontosan illenek a játékához — ugyanaz a cím, ugyanaz a régió, ugyanaz a változat —, és inkább semmit sem ajánl, mint valami hozzávetőlegeset: a más kiadáshoz írt kódok nem kicsit mellé írnak, hanem egészen máshová.",
  /* 371 */ "A csalások",
  /* 372 */ "Kevesebb",
  /* 373 */ "Csaláspanel",
  /* 374 */ "Több",
  /* 375 */ "Elölről",
  /* 376 */ "Csalások",
  /* 377 */ "Csalások…",
  /* 378 */ "Érték",
  /* 379 */ "Egyenlő",
  /* 380 */ "{0} lehetséges cím",
  /* 381 */ "{0} fájl letéve, {1} eltávolítva",
  /* 382 */ "{1} játékból {0} rendelkezik fájllal",
  /* 383 */ "{0} bájt memória",
  /* 384 */ "{0} érték elvetve: e játék memóriáján kívül",
  /* 385 */ "Ehhez a játékhoz nincs fájl. Az Emuláció menü „Csalások…” panelje keres egyet; ha nincs, az értékkeresés bármelyik játékkal működik.",
  /* 386 */ "Rögzítve",
  /* 387 */ "Rögzítés",
  /* 388 */ "Játsszon egy kicsit, majd mondja meg, mit tett az érték.",
  /* 389 */ "A játékállás félre lett téve az első csalás előtt.",
  /* 390 */ "Keresés…",
  /* 391 */ "Ami a « drop u'r rom » mappába kerül, ahhoz a konzolhoz megy, amelyet a kiterjesztése megnevez. Ha több konzol osztozik ugyanazon — a lemezképek — az EvaChi inkább kérdez, mintsem tippeljen.",
  /* 392 */ "Megerősítés",
  /* 393 */ "A játék mentésének törlése…",
  /* 394 */ "Nyújtás",
  /* 395 */ "A játék a memóriában tartja a számlálóit, de nem mondja meg, hol. Kizárással találhatók meg: megmondja, mit tett a képernyőn látott szám, az EvaChi pedig kiveti azokat a címeket, amelyek nem ugyanezt tették.",
  /* 396 */ "Igen",
  /* 397 */ "Kevés konzol arányai felelnek meg egy mai képernyőnek, innen a fekete sávok az oldalakon. Nullán a kép megtartja az arányait; százon kitölti az ablakot, még ha meg is nyúlik.",
  /* 398 */ "A játékok rendezése",
  /* 399 */ "Rendezés",
  /* 400 */ "A lerakott játékok rendezése…",
  /* 401 */ "47 életet lát: írjon 47-et az « Érték » mezőbe, majd nyomja meg a « Keresés » gombot. Veszítsen el egyet, írjon 46-ot, majd nyomja meg az « Egyenlő » gombot. Ha a szám sehol nincs kiírva, hagyja üresen az « Érték » mezőt, és két játékpillanat között csak annyit mondjon: « Több », « Kevesebb », « Más » vagy « Ugyanaz ». A megtalált értéket ezután a « Rögzítés » tartja meg. A « Szélesség » a szám mérete: 1 egészen 255-ig, 2 azon felül, 4 a nagy számlálókhoz.",
  /* 402 */ "{0} elrendezve",
  /* 403 */ "nincs törölhető mentés",
  /* 404 */ "Gombok",
  /* 405 */ "Már a könyvtárban: {0}",
  /* 406 */ "Törli {0} mentését, és kezdi elölről? A folyamatban lévő játék leáll, és elvész mindaz, amit a játék feljegyzett.",
  /* 407 */ "Ravaszok",
  /* 408 */ "Mindkettő megtartása",
  /* 409 */ "Maradjon a mappában",
  /* 410 */ "A mappa üres.",
  /* 411 */ "Lecseréli a(z) {0}. helyet? Ami ott van, elvész.",
  /* 412 */ "mentés törölve — {0}",
  /* 413 */ "Rendszer",
  /* 414 */ "Kiüríti a(z) {0}. helyet? Ami ott van, elvész.",
  /* 415 */ "A holtsáv a kar azon része, ahol még nyugalomban lévőnek tekintjük. Ha túl kicsi, a figura magától elindul, miközben a kontroller az asztalon hever; ha túl nagy, elvesznek az apró mozdulatok. Néhány játék azt kéri, hogy rázza meg a konzolt: ha ezt a kontroller nem tudja érzékelni, az alábbi két gomb elhiteti a játékkal.",
  /* 416 */ "A kar",
  /* 417 */ "Az önálló emulátoroknak saját gombjaik vannak, saját fájlokban. Amit itt módosít, az azonnal átkerül oda — azokhoz, amelyek formátumát első kézből ismerjük: PCSX2, PPSSPP és Dolphin. A régi beállítás az első alkalommal félretevődik, ugyanazon a néven, « .avant-evachi » utótaggal.",
  /* 418 */ "Átvitel a külső emulátorokba",
  /* 419 */ "Holtsáv",
  /* 420 */ "Vetítés",
  /* 421 */ "Agyag",
  /* 422 */ "egyetlen külső emulátor sem írta még ki a beállításait",
  /* 423 */ "Parázs",
  /* 424 */ "Hamu",
  /* 425 */ "Cseresznye",
  /* 426 */ "Korall",
  /* 427 */ "Kártyapakli",
  /* 428 */ "Erdő",
  /* 429 */ "Dér",
  /* 430 */ "a külső emulátoroknak már megvoltak ezek a gombjai",
  /* 431 */ "Éjfél",
  /* 432 */ "Moha",
  /* 433 */ "Neon",
  /* 434 */ "Szilva",
  /* 435 */ "Homok",
  /* 436 */ "Rázás",
  /* 437 */ "Szépia",
  /* 438 */ "átvitt gombok: {0}",
  /* 439 */ "Türkiz",
  /* 440 */ "A borítók legyezőben tartva, akár egy lapkéz. A csukló fordul, és az olvasott lap felegyenesedik.",
  /* 441 */ "Sötét terem, porral teli fénynyaláb, és a játék nagyban kivetítve. A többi a tárban várakozik.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Sárgabarack",
  /* 444 */ "Hanga",
  /* 445 */ "Karamell",
  /* 446 */ "Réz",
  /* 447 */ "Tinta",
  /* 448 */ "Famicom",
  /* 449 */ "Jade",
  /* 450 */ "Áfonya",
  /* 451 */ "Vihar",
  /* 452 */ "Gyöngy",
  /* 453 */ "Pisztácia",
  /* 454 */ "Nincs",
  /* 455 */ "Sorok",
  /* 456 */ "Minden képpont három résben: vörös, zöld és kék",
  /* 457 */ "A mag képe, képpontról képpontra",
  /* 458 */ "A domború üveg, a sorok, a rések és a sötétedő szélek",
  /* 459 */ "Résmaszk",
  /* 460 */ "Képcső",
  /* 461 */ "Minden második sor sötétebb, mint a televízión",
  /* 462 */ "Megnyitja az emulátort a saját ablakában, játék nélkül",
  /* 463 */ "Megnyitás",
  /* 464 */ "Hangerő",
];
