/**
 * Indonésien — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * marques numérotées sont là pour qu'on puisse le vérifier à l'œil.
 */

export const id: readonly string[] = [
  /* 1 */ "Dengan gamepad",
  /* 2 */ "A mainkan · X favorit · Y pangkas · L1/R1 konsol · L2/R2 huruf · B kembali",
  /* 3 */ "Tentang EvaChi",
  /* 4 */ "Tentang…",
  /* 5 */ "Segera hadir: filter tabung katoda, kisi piksel, garis pindai. Tempatnya sudah siap, filternya akan muncul di sini.",
  /* 6 */ "Segarkan pustaka",
  /* 7 */ "Tampilan",
  /* 8 */ "Tampilkan sampul game",
  /* 9 */ "Bantuan",
  /* 10 */ "Tambahkan folder game…",
  /* 11 */ "Tambahkan folder…",
  /* 12 */ "Tekan sebuah tombol pada gamepad: tombol keyboard yang sepadan akan menyala. Untuk menggantinya, masuk ke mode penetapan ulang, klik tombol yang ingin diubah, lalu tekan tombol gamepad yang Anda mau.",
  /* 13 */ "Argumen",
  /* 14 */ "Dengan keyboard",
  /* 15 */ "Tidak ada game",
  /* 16 */ "Tidak ada gamepad yang terdeteksi.",
  /* 17 */ "Pustaka",
  /* 18 */ "Bunyi saat memilih dengan gamepad",
  /* 19 */ "Sebagian konsol tidak mau menyala tanpa firmware aslinya. EvaChi tidak bisa menyediakannya: itu kode berhak cipta, yang disalin dari mesin milik Anda sendiri. Yang ia lakukan: memberi tahu mana yang kurang, dengan nama apa, dan di mana harus diletakkan.",
  /* 20 */ "Konsol berikut tidak punya core libretro: emulatornya program tersendiri, yang dipasang EvaChi di tempatnya lalu dijalankan langsung ke dalam game — tanpa mampir ke menunya. Game, kunci, dan berkas sistemnya tetap menjadi urusan Anda.",
  /* 21 */ "Pengaturan ini hanya menyentuh core internal. Emulator eksternal punya pengaturannya sendiri, dan EvaChi tidak ikut campur.",
  /* 22 */ "Yang berikut ini tidak lagi ditawarkan: mereka tidak menjawab saat ditanya, atau membuat EvaChi jatuh. Memulihkannya tidak memasangnya ulang — hanya mengembalikannya ke daftar.",
  /* 23 */ "Muat state",
  /* 24 */ "Core internal saja. Klik satu pintasan lalu tekan tombol keyboard atau tombol gamepad yang Anda mau; pada gamepad dipakai dua tombol sekaligus, karena masing-masing sudah punya tugas di dalam game.",
  /* 25 */ "Kontrol",
  /* 26 */ "Kontrol…",
  /* 27 */ "Konsol terbaru",
  /* 28 */ "Daftarkan emulator lain",
  /* 29 */ "Arah / stik kiri",
  /* 30 */ "Folder game",
  /* 31 */ "Singkirkan emulator ini",
  /* 32 */ "Sampul datang dari server thumbnail proyek libretro, sesuai kebutuhan. Bila centangnya dilepas, pustaka tidak lagi meminta apa pun dari jaringan.",
  /* 33 */ "Slot penyimpanan",
  /* 34 */ "Slot…",
  /* 35 */ "Emulator",
  /* 36 */ "Emulator yang disingkirkan",
  /* 37 */ "Emulator eksternal",
  /* 38 */ "Emulator eksternal…",
  /* 39 */ "Emulator…",
  /* 40 */ "Emulasi",
  /* 41 */ "Saat bermain, kembali ke pustaka — dua tombol sekaligus, karena masing-masing sudah dipakai game",
  /* 42 */ "Simpan",
  /* 43 */ "Ekstensi",
  /* 44 */ "Tutup",
  /* 45 */ "Berkas",
  /* 46 */ "Berkas sistem yang dipasang sendiri",
  /* 47 */ "Galeri",
  /* 48 */ "Kelola folder…",
  /* 49 */ "Grafis",
  /* 50 */ "Grafis…",
  /* 51 */ "Tunjukkan folder tempat game Anda berada.",
  /* 52 */ "Pemasangan",
  /* 53 */ "Pasang yang dipilih",
  /* 54 */ "Pasang emulator…",
  /* 55 */ "Interpreter",
  /* 56 */ "Tak perlu tahu ke mana: tunjukkan saja folder tempat semuanya berserakan — BIOS, kunci, firmware, arsip, subfolder sekalian — dan EvaChi mengantar tiap berkas ke tempat yang benar, untuk core maupun untuk emulator mandiri. Yang tidak diminta siapa pun tidak dipindahkan.",
  /* 57 */ "Sampul",
  /* 58 */ "Log",
  /* 59 */ "Log…",
  /* 60 */ "Kali sebelumnya berakhir buruk",
  /* 61 */ "Mainkan game, konfirmasi",
  /* 62 */ "Bahasa",
  /* 63 */ "Pilihan Anda diingat dari satu sesi ke sesi berikutnya. Semuanya sudah diperiksa agar terbaca: di mana pun, teksnya tetap cukup kontras dengan latarnya.",
  /* 64 */ "Tetap pakai",
  /* 65 */ "Emulator di bawah ini sudah diatur lengkap — argumen dan formatnya sekalian. EvaChi mencarinya di disk Anda; ia tidak memasangnya.",
  /* 66 */ "Pemetaan bawaan",
  /* 67 */ "Penghalusan",
  /* 68 */ "Jadikan game favorit, atau lepaskan dari favorit",
  /* 69 */ "Musik menu animasi",
  /* 70 */ "Nama",
  /* 71 */ "Buka bilah menu",
  /* 72 */ "Buka folder",
  /* 73 */ "Buka folder…",
  /* 74 */ "Buka game…",
  /* 75 */ "per frame",
  /* 76 */ "Pengaturan core",
  /* 77 */ "Pengaturan core…",
  /* 78 */ "Menjelajahi pustaka, jendela, dan bilah menu",
  /* 79 */ "Telusuri…",
  /* 80 */ "Jeda",
  /* 81 */ "Layar penuh",
  /* 82 */ "Untuk konsol tanpa core libretro. EvaChi menjalankan programnya dengan game sebagai argumen: emulatornya langsung masuk ke permainan, tanpa mampir ke menunya sendiri.",
  /* 83 */ "Ambil tangkapan layar",
  /* 84 */ "Tata letak",
  /* 85 */ "Siap",
  /* 86 */ "Program",
  /* 87 */ "Beberapa akor panjang dan nada yang berjauhan, disusun saat itu juga alih-alih direkam: lagunya tidak pernah lewat di tempat yang sama dua kali. Ia berhenti sendiri begitu sebuah game dimulai.",
  /* 88 */ "Rapikan sebuah folder…",
  /* 89 */ "Tetapkan ulang…",
  /* 90 */ "Cari game…",
  /* 91 */ "Setel ulang",
  /* 92 */ "Kembali ke pustaka",
  /* 93 */ "Kembali, tutup",
  /* 94 */ "Simpan cepat",
  /* 95 */ "Simpan state",
  /* 96 */ "Shader",
  /* 97 */ "Suara",
  /* 98 */ "Start",
  /* 99 */ "Ukuran gambar",
  /* 100 */ "Tema",
  /* 101 */ "Tema…",
  /* 102 */ "Satu berkas saja…",
  /* 103 */ "Satu klik singkat saat berpindah game, satu lagi saat menjalankannya. Hanya dengan gamepad: dengan mouse dan keyboard, gerakannya sudah terasa sendiri.",
  /* 104 */ "Kecepatan",
  /* 105 */ "Lihat tangkapan layar…",
  /* 106 */ "Anda boleh memasang sebagiannya saja — hanya konsol yang emulatornya terpasang yang muncul di pustaka.",
  /* 107 */ "{0} — dimuat",
  /* 108 */ "{0} — klik kanan untuk mengosongkan",
  /* 109 */ "{0} — dijadikan favorit",
  /* 110 */ "{0} — disetel ulang",
  /* 111 */ "{0} — dilepas dari favorit",
  /* 112 */ "{0} — mengunduh…",
  /* 113 */ "{0}: gagal, lihat log",
  /* 114 */ "{0} tersedia",
  /* 115 */ "{0} tersimpan",
  /* 116 */ "{0} adalah emulator eksternal: ia dijalankan, bukan ditampung",
  /* 117 */ "{0} fps",
  /* 118 */ "{0} terpasang",
  /* 119 */ "{0} terpasang — {1}",
  /* 120 */ "{0} terpasang dan siap",
  /* 121 */ "{0} terpasang, {1} gagal — lihat log",
  /* 122 */ "{0} dipulihkan",
  /* 123 */ "{0} dihapus",
  /* 124 */ "{0} dari {1}",
  /* 125 */ "{0} ada di disk, tetapi tidak ada core terpasang yang membukanya.",
  /* 126 */ "ambil dari {0}, lalu “Telusuri…”",
  /* 127 */ "perlu diunduh",
  /* 128 */ "tidak ada, opsional",
  /* 129 */ "Aktifkan",
  /* 130 */ "Halus",
  /* 131 */ "gagal menambahkan — {0}",
  /* 132 */ "Sesuaikan",
  /* 133 */ "Ambar",
  /* 134 */ "Batu tulis",
  /* 135 */ "berhenti — {0}",
  /* 136 */ "berhenti mendadak pada sesi sebelumnya — {0}",
  /* 137 */ "tidak ada",
  /* 138 */ "tidak ada core yang dikembalikan padahal {0} sudah dikenal — daftar sebelumnya dipertahankan",
  /* 139 */ "tidak ada emulator",
  /* 140 */ "Tidak ada emulator terpasang",
  /* 141 */ "Tidak ada game yang dikenali",
  /* 142 */ "Tidak ada hasil",
  /* 143 */ "tidak ada",
  /* 144 */ "pustaka tidak terbaca — {0}",
  /* 145 */ "tersambung",
  /* 146 */ "tangkapan layar",
  /* 147 */ "Ganti sampul…",
  /* 148 */ "Ganti…",
  /* 149 */ "Tiap piksel jadi sembilan",
  /* 150 */ "Tiap piksel jadi empat: tajam, tanpa cacat bentuk",
  /* 151 */ "Tiap piksel jadi enam belas — untuk layar besar",
  /* 152 */ "Muat",
  /* 153 */ "Pilih sampul…",
  /* 154 */ "pilih dulu sebuah game di pustaka",
  /* 155 */ "core: {0}",
  /* 156 */ "core belum terpasang",
  /* 157 */ "Core terpasang",
  /* 158 */ "core libretro",
  /* 159 */ "Kontras tinggi",
  /* 160 */ "cangkang asli: {0}",
  /* 161 */ "pelepasan tidak tuntas — {0}",
  /* 162 */ "penemuan: {0}",
  /* 163 */ "penemuan terputus — {0}",
  /* 164 */ "Tentukan sendiri program untuk {0}",
  /* 165 */ "folder ditambahkan: {0}",
  /* 166 */ "folder dibuka: {0}",
  /* 167 */ "Folder bawaan",
  /* 168 */ "Folder yang ditambahkan",
  /* 169 */ "Esc",
  /* 170 */ "Slot {0}",
  /* 171 */ "slot {0} — {1}",
  /* 172 */ "Emulator untuk folder ini",
  /* 173 */ "emulator eksternal",
  /* 174 */ "sedang berjalan",
  /* 175 */ "sudah ada",
  /* 176 */ "gagal menyimpan — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi bisa mengunduhnya dari server resmi libretro. Pilih konsol yang Anda minati.",
  /* 179 */ "EvaChi berhenti saat menjalankan “{0}”, dengan emulator {1}.",
  /* 180 */ "EvaChi berhenti, dengan emulator {0}.",
  /* 181 */ "external_systems → {0} emulator terdaftar",
  /* 182 */ "Favorit",
  /* 183 */ "Favorit",
  /* 184 */ "berkas sistem tidak terbaca — {0}",
  /* 185 */ "Panah",
  /* 186 */ "Game Boy",
  /* 187 */ "Kisi",
  /* 188 */ "ada {0} yang kurang pada konsol terpasang",
  /* 189 */ "pemasangan selesai: {0}",
  /* 190 */ "Memasang…",
  /* 191 */ "terpasang",
  /* 192 */ "dipasang oleh EvaChi",
  /* 193 */ "Pasang",
  /* 194 */ "interpreter: {0}",
  /* 195 */ "menanyai core yang terpasang…",
  /* 196 */ "Mainkan",
  /* 197 */ "Mainkan game yang dipilih",
  /* 198 */ "Lavender",
  /* 199 */ "Konsol berjajar mendatar, game menurun, latar yang beriak. Ala konsol ruang keluarga.",
  /* 200 */ "Tepiannya melebur — lebih dekat ke televisi tua",
  /* 201 */ "Sampul besar-besar, dijelajahi dengan gamepad. Dibuat untuk di sofa.",
  /* 202 */ "Pikselnya tetap kotak, seperti pada mesin aslinya",
  /* 203 */ "pemetaan gamepad dikembalikan ke bawaan",
  /* 204 */ "list_cores → {0} core dilaporkan",
  /* 205 */ "Daftar",
  /* 206 */ "daftar core tidak tersedia — {0}",
  /* 207 */ "daftar emulator tidak tersedia — {0}",
  /* 208 */ "Gamepad",
  /* 209 */ "gamepad: {0}",
  /* 210 */ "Gamepad: {0}",
  /* 211 */ "gamepad dicabut",
  /* 212 */ "TIDAK ADA",
  /* 213 */ "Mint",
  /* 214 */ "Menu animasi",
  /* 215 */ "Perbarui",
  /* 216 */ "Jadikan favorit",
  /* 217 */ "disingkirkan: {0} · {1}",
  /* 218 */ "kurang dari semenit",
  /* 219 */ "Tajam",
  /* 220 */ "nama, program, dan ekstensi semuanya wajib diisi",
  /* 221 */ "TIDAK",
  /* 222 */ "tidak terpasang di mesin ini",
  /* 223 */ "Malam merah muda",
  /* 224 */ "Samudra",
  /* 225 */ "atau",
  /* 226 */ "ya",
  /* 227 */ "gagal membuka — {0}",
  /* 228 */ "halaman web: hanya core internal yang tersedia, tanpa pustaka",
  /* 229 */ "Kertas",
  /* 230 */ "bawaan",
  /* 231 */ "Menjelajahi kisi dan menu animasi",
  /* 232 */ "layar penuh ditolak — {0}",
  /* 233 */ "tekan tombol yang Anda mau pada gamepad",
  /* 234 */ "tekan sebuah tombol…",
  /* 235 */ "perapian: {0} · {1}",
  /* 236 */ "gagal merapikan — {0}",
  /* 237 */ "pencarian emulator terputus — {0}",
  /* 238 */ "Menutup jendela",
  /* 239 */ "gagal menyetel ulang — {0}",
  /* 240 */ "Mengisi jendela tanpa mengubah proporsi",
  /* 241 */ "Lanjutkan",
  /* 242 */ "Lanjutkan dari simpanan ini — klik kanan untuk mengosongkannya",
  /* 243 */ "Pulihkan",
  /* 244 */ "gagal memulihkan — {0}",
  /* 245 */ "Hapus",
  /* 246 */ "Lepas dari favorit",
  /* 247 */ "Hapus sampul",
  /* 248 */ "gagal menghapus — {0}",
  /* 249 */ "tidak ada yang perlu dirapikan",
  /* 250 */ "tidak ada yang menghalangi",
  /* 251 */ "Tidak ada yang cocok dengan “{0}”.",
  /* 252 */ "Merah muda dan putih",
  /* 253 */ "tanpa gambar",
  /* 254 */ "Simpan",
  /* 255 */ "Simpan di sini",
  /* 256 */ "gagal memilih — {0}",
  /* 257 */ "Ukuran asli konsol, tepat sampai pikselnya",
  /* 258 */ "Selesai",
  /* 259 */ "tema terang",
  /* 260 */ "tema gelap",
  /* 261 */ "semuanya sudah terpasang",
  /* 262 */ "ditemukan: {0}",
  /* 263 */ "Satu panel per konsol, tersusun sebagai tabel. Paling padat bila memakai mouse.",
  /* 264 */ "kosong",
  /* 265 */ "letakkan di sini, sama seperti romset game: FinalBurn Neo hanya mencari di folder ini",
  /* 266 */ "menambahkan layar sambutan konsol",
  /* 267 */ "pemuat awal mesin",
  /* 268 */ "banyak game jalan tanpanya; menu konsolnya tidak",
  /* 269 */ "BIOS Amerika",
  /* 270 */ "BIOS Amerika dan Eropa",
  /* 271 */ "BIOS Eropa",
  /* 272 */ "BIOS Jepang",
  /* 273 */ "kunci dekripsi; tanpanya salinan terenkripsi akan ditolak",
  /* 274 */ "folder Machines dari distribusi blueMSX, dengan Databases di sebelahnya",
  /* 275 */ "sama",
  /* 276 */ "wajib untuk game CD, tidak perlu untuk kartu HuCard",
  /* 277 */ "wajib untuk game Mega-CD, tidak perlu untuk kartrid",
  /* 278 */ "Kickstart 1.3; tanpanya PUAE beralih ke AROS, bebas tetapi kurang cocok",
  /* 279 */ "Kickstart 3.1; diperlukan game AGA, yang tidak bisa dijalankan A500",
  /* 280 */ "melonDS meniru BIOS secara bawaan; yang asli lebih setia",
  /* 281 */ "mGBA bisa tanpanya; beberapa game memerlukannya untuk layar pembuka",
  /* 282 */ "firmware konsol",
  /* 283 */ "firmware mesin",
  /* 284 */ "firmware Panasonic FZ-10; nama inilah yang dipakai Opera secara bawaan",
  /* 285 */ "diubah oleh melonDS, yang menyimpan aslinya sebagai .bak",
  /* 286 */ "kumpulan font",
  /* 287 */ "pengaturan dan tanggal konsol",
  /* 288 */ "tanpanya core tetap jalan tetapi layarnya gelap",
  /* 289 */ "tabel karakter konsol",
  /* 290 */ "varian Amerika, untuk game Sega CD dari Amerika Serikat",
  /* 291 */ "varian Jepang, untuk game Mega-CD Jepang",
  /* 292 */ "tangkapan layar",
  /* 293 */ "tangkapan layar",
  /* 294 */ "tangkapan layar",
  /* 295 */ "tangkapan layar",
  /* 296 */ "tangkapan layar",
  /* 297 */ "tangkapan layar",
  /* 298 */ "core",
  /* 299 */ "core",
  /* 300 */ "core",
  /* 301 */ "core",
  /* 302 */ "core",
  /* 303 */ "core",
  /* 304 */ "emulator",
  /* 305 */ "emulator",
  /* 306 */ "emulator",
  /* 307 */ "emulator",
  /* 308 */ "emulator",
  /* 309 */ "emulator",
  /* 310 */ "berkas",
  /* 311 */ "berkas",
  /* 312 */ "berkas",
  /* 313 */ "berkas",
  /* 314 */ "berkas",
  /* 315 */ "berkas",
  /* 316 */ "game",
  /* 317 */ "game",
  /* 318 */ "game",
  /* 319 */ "game",
  /* 320 */ "game",
  /* 321 */ "game",
  /* 322 */ "<code>{rom}</code> akan diganti dengan lokasi berkas game. Tanpanya, lokasi itu ditambahkan di bagian akhir — dan itulah yang diharapkan kebanyakan emulator.",
  /* 323 */ "<strong>Di luar permainan, semuanya bisa dilakukan dengan gamepad:</strong> tombol arah menjelajahi pustaka, jendela, dan bilah menu; <strong>A</strong> mengiyakan, <strong>B</strong> kembali, <strong>Start</strong> membuka bilah menu. Saat bermain, <strong>Select dan Start bersamaan</strong> mengembalikan Anda ke pustaka — dua tombol sekaligus, karena masing-masing sudah dipakai game.",
  /* 324 */ "Belum ada tangkapan layar. Tekan <strong>F12</strong> saat bermain, atau <strong>Select + Y</strong> pada gamepad.",
  /* 325 */ "Tiap konsol butuh emulatornya sendiri. EvaChi mengambilnya dari server resmi proyek libretro, <code>buildbot.libretro.com</code>, lalu memasangnya di foldernya sendiri. Tidak ada yang diedarkan ulang: semuanya versi yang diterbitkan oleh para pembuatnya.",
  /* 326 */ "Empat slot untuk tiap game, disimpan di disk. Slot yang dicetak tebal adalah slot yang dipakai <strong>F2</strong> dan <strong>F4</strong> — juga <strong>Select + L1</strong> / <strong>Select + R1</strong> pada gamepad. Klik kanan sebuah slot untuk mengosongkannya.",
  /* 327 */ "Emulator berjalan di jendela yang sama dengan EvaChi: ketika ia jatuh, ia membawa EvaChi serta, tanpa sepatah pesan. Menyingkirkan emulator ini membiarkannya tetap terpasang, tetapi berhenti menawarkannya. Anda bisa memulihkannya kapan saja dari <strong>Berkas → Emulator</strong>, di bagian bawah jendela.",
  /* 328 */ "Satu berkas saja per game di disk <small> Game CD datang sebagai satu lembar <code>.cue</code> dan sebanyak itu berkas <code>.bin</code> sesuai jumlah trek pada cakramnya. Hanya lembarnya yang bisa dijalankan: trek-treknya disembunyikan selama lembar itu ada. Tanpa lembar itu, tidak ada yang disembunyikan. </small>",
  /* 329 */ "(kosong) atau --fullscreen {rom}",
  /* 330 */ "Seratus persen adalah kecepatan asli konsol. Di bawah itu game melambat, di atasnya melaju kencang — dan suaranya ikut, jadi lebih berat atau lebih melengking. Pada kontroler, kiri dan kanan berpindah dari satu tingkat ke tingkat berikutnya. Hanya untuk core internal: emulator eksternal tetap memakai kecepatannya sendiri.",
  /* 331 */ "Lima konsol sekaligus",
  /* 332 */ "Tombol arah",
  /* 333 */ "Dari satu huruf awal ke berikutnya",
  /* 334 */ "Di menu beranimasi, lima game sekaligus",
  /* 335 */ "Kecepatan game",
  /* 336 */ "Batal",
  /* 337 */ "Geser bingkainya, atau tarik salah satu sudutnya. Tombol panah memindahkannya, dan dengan Shift bingkai membesar atau mengecil. Kalau bingkai keluar dari gambar, sampul akan dikelilingi bidang transparan: begitulah cara memperkecil sampul yang terlalu rapat. Pada gamepad, tombol arah memindahkan bingkai dan tombol pelatuk mengatur ukurannya.",
  /* 338 */ "Pangkas",
  /* 339 */ "Pangkas sampul",
  /* 340 */ "Seluruh gambar",
  /* 341 */ "{0} — sampul dipangkas",
  /* 342 */ "{0} — tidak ada sampul untuk dipangkas",
  /* 343 */ "sampul tidak terbaca — {0}",
  /* 344 */ "gagal memangkas — {0}",
  /* 345 */ "Pangkas sampul…",
];
