/**
 * L'islandais — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * marques numérotées sont là pour qu'on puisse le vérifier à l'œil.
 */

export const is: readonly string[] = [
  /* 1 */ "Með leikjastýringu",
  /* 2 */ "A spila · X uppáhald · Y sníða · L1/R1 leikjatölvur · L2/R2 stafur · B til baka",
  /* 3 */ "Um EvaChi",
  /* 4 */ "Um forritið…",
  /* 5 */ "Væntanlegt: túbuskjássíur, dílanet, skannlínur. Plássið er tilbúið, síurnar koma hingað.",
  /* 6 */ "Endurnýja safnið",
  /* 7 */ "Sýn",
  /* 8 */ "Sýna kápumyndir leikjanna",
  /* 9 */ "Hjálp",
  /* 10 */ "Bæta við leikjamöppu…",
  /* 11 */ "Bæta við möppu…",
  /* 12 */ "Ýttu á hnapp á leikjastýringunni: samsvarandi lykill lýsist upp. Til að breyta einum, farðu í endurtengingu, smelltu á lykilinn sem á að breyta og ýttu svo á hnappinn sem þú vilt.",
  /* 13 */ "Viðföng",
  /* 14 */ "Á lyklaborði",
  /* 15 */ "Enginn leikur",
  /* 16 */ "Engin leikjastýring fannst.",
  /* 17 */ "Safn",
  /* 18 */ "Hljóð við val með stýringu",
  /* 19 */ "Sumar leikjatölvur ræsast ekki án upprunalega fastbúnaðarins. EvaChi getur ekki útvegað hann: þetta er höfundarréttarvarinn kóði sem afritast af vélinni sem maður á. Forritið segir hins vegar hvað vantar, undir hvaða heiti og hvar á að leggja það.",
  /* 20 */ "Þessar leikjatölvur eiga sér engan libretro-kjarna: hermir þeirra er sérstakt forrit sem EvaChi setur upp hjá sér og ræsir beint inn í leikinn — án viðkomu í valmynd hans. Leikirnir, lyklarnir og kerfisskrárnar eru áfram á þína ábyrgð.",
  /* 21 */ "Þessar stillingar ná aðeins til innri kjarnanna. Utanaðkomandi hermir hefur sínar eigin og EvaChi skiptir sér ekki af þeim.",
  /* 22 */ "Þessir eru ekki lengur í boði: þeir svöruðu ekki fyrirspurninni eða þeir felldu EvaChi. Að endurvekja þá setur þá ekki upp á nýtt — það kemur þeim einfaldlega aftur á listann.",
  /* 23 */ "Hlaða stöðu",
  /* 24 */ "Aðeins innri kjarnar. Smelltu á flýtileið og ýttu svo á þann lykil eða hnapp sem þú vilt; á stýringunni tökum við tvo hnappa í einu, því hver þeirra þjónar leiknum fyrir.",
  /* 25 */ "Stýringar",
  /* 26 */ "Stýringar…",
  /* 27 */ "Nýlegar leikjatölvur",
  /* 28 */ "Skrá annan hermi",
  /* 29 */ "Áttir / vinstri stýripinni",
  /* 30 */ "Leikjamöppur",
  /* 31 */ "Leggja þennan hermi til hliðar",
  /* 32 */ "Þær koma af smámyndaþjóni libretro-verkefnisins, eftir þörfum. Sé hakið tekið burt biður safnið netið ekki um neitt.",
  /* 33 */ "Vistunarhólf",
  /* 34 */ "Hólf…",
  /* 35 */ "Hermar",
  /* 36 */ "Hermar lagðir til hliðar",
  /* 37 */ "Utanaðkomandi hermar",
  /* 38 */ "Utanaðkomandi hermar…",
  /* 39 */ "Hermar…",
  /* 40 */ "Hermun",
  /* 41 */ "Meðan á leik stendur, aftur í safnið — tveir hnappar í einu, því hvor þeirra þjónar leiknum",
  /* 42 */ "Vista",
  /* 43 */ "Skráarendingar",
  /* 44 */ "Loka",
  /* 45 */ "Skrá",
  /* 46 */ "Kerfisskrár sem þarf að setja upp sjálfur",
  /* 47 */ "Gallerí",
  /* 48 */ "Sýsla með möppur…",
  /* 49 */ "Grafík",
  /* 50 */ "Grafík…",
  /* 51 */ "Bentu á möppuna þar sem leikirnir þínir eru.",
  /* 52 */ "Uppsetning",
  /* 53 */ "Setja upp valið",
  /* 54 */ "Setja upp herma…",
  /* 55 */ "Túlkur",
  /* 56 */ "Óþarfi að vita hvert: bentu á möppuna þar sem allt liggur — BIOS, lyklar, fastbúnaður, safnskrár, undirmöppur líka — og EvaChi ber hverja skrá á réttan stað, jafnt fyrir kjarnana sem sjálfstæðu hermana. Það sem enginn kallar eftir er ekki fært úr stað.",
  /* 57 */ "Kápumyndir",
  /* 58 */ "Annáll",
  /* 59 */ "Annáll…",
  /* 60 */ "Síðast endaði illa",
  /* 61 */ "Ræsa leikinn, staðfesta",
  /* 62 */ "Tungumál",
  /* 63 */ "Valið helst milli ræsinga. Hvert þeirra hefur verið prófað læsilegt: textinn heldur alls staðar nægum birtuskilum við bakgrunninn.",
  /* 64 */ "Halda honum",
  /* 65 */ "Hermarnir hér að neðan eru þegar stilltir — viðföng og snið líka. EvaChi leitar að þeim á disknum þínum; forritið setur þá ekki upp.",
  /* 66 */ "Sjálfgefnar tengingar",
  /* 67 */ "Mýking",
  /* 68 */ "Setja leikinn í uppáhald, eða taka hann þaðan",
  /* 69 */ "Tónlist hreyfivalmyndanna",
  /* 70 */ "Heiti",
  /* 71 */ "Opna valmyndastikuna",
  /* 72 */ "Opna möppuna",
  /* 73 */ "Opna möppu…",
  /* 74 */ "Opna leik…",
  /* 75 */ "á ramma",
  /* 76 */ "Stillingar kjarnans",
  /* 77 */ "Stillingar kjarnans…",
  /* 78 */ "Fara um safnið, gluggana og valmyndastikuna",
  /* 79 */ "Velja…",
  /* 80 */ "Hlé",
  /* 81 */ "Heilskjár",
  /* 82 */ "Fyrir leikjatölvur án libretro-kjarna. EvaChi ræsir forritið með leikinn sem viðfang: hermirinn fer beint inn í leikinn, án viðkomu í sinni eigin valmynd.",
  /* 83 */ "Taka skjámynd",
  /* 84 */ "Kynning",
  /* 85 */ "Tilbúið",
  /* 86 */ "Forrit",
  /* 87 */ "Nokkrir haldnir hljómar og stöku nótur, samið jafnóðum frekar en hljóðritað: lagið kemur aldrei aftur á sama stað. Það hættir af sjálfu sér um leið og leikur fer í gang.",
  /* 88 */ "Ganga frá möppu…",
  /* 89 */ "Endurtengja…",
  /* 90 */ "Leita að leik…",
  /* 91 */ "Endurstilla",
  /* 92 */ "Aftur í safnið",
  /* 93 */ "Fara til baka, loka",
  /* 94 */ "Skyndivistun",
  /* 95 */ "Vista stöðu",
  /* 96 */ "Shaders",
  /* 97 */ "Hljóð",
  /* 98 */ "Start",
  /* 99 */ "Stærð myndar",
  /* 100 */ "Þemu",
  /* 101 */ "Þemu…",
  /* 102 */ "Ein skrá á leik…",
  /* 103 */ "Stutt tikk þegar skipt er um leik, annað þegar hann er ræstur. Aðeins með stýringu: með mús og lyklaborði finnst hreyfingin hvort eð er.",
  /* 104 */ "Hraði",
  /* 105 */ "Skoða skjámyndir…",
  /* 106 */ "Þú þarft ekki að setja allt upp — aðeins þær leikjatölvur sem eiga uppsettan hermi birtast í safninu.",
  /* 107 */ "{0} — hlaðið",
  /* 108 */ "{0} — hægrismelltu til að hreinsa",
  /* 109 */ "{0} — sett í uppáhald",
  /* 110 */ "{0} — endurstillt",
  /* 111 */ "{0} — tekið úr uppáhaldi",
  /* 112 */ "{0} — sæki…",
  /* 113 */ "{0}: mistókst, sjá annál",
  /* 114 */ "{0} í boði",
  /* 115 */ "{0} vistað",
  /* 116 */ "{0} er utanaðkomandi hermir: hann er ræstur, ekki hýstur",
  /* 117 */ "{0} r/s",
  /* 118 */ "{0} uppsett",
  /* 119 */ "{0} uppsett — {1}",
  /* 120 */ "{0} uppsett og tilbúið",
  /* 121 */ "{0} uppsett, {1} mistókst — sjá annál",
  /* 122 */ "{0} endurvakið",
  /* 123 */ "{0} fjarlægt",
  /* 124 */ "{0} af {1}",
  /* 125 */ "{0} á disknum, en enginn uppsettur kjarni opnar þá.",
  /* 126 */ "að sækja á {0}, síðan „Velja…“",
  /* 127 */ "til niðurhals",
  /* 128 */ "vantar, valfrjálst",
  /* 129 */ "Virkja",
  /* 130 */ "Mýkt",
  /* 131 */ "gat ekki bætt við — {0}",
  /* 132 */ "Aðlaga",
  /* 133 */ "Raf",
  /* 134 */ "Grásteinn",
  /* 135 */ "stöðvun — {0}",
  /* 136 */ "snöggt stopp síðast — {0}",
  /* 137 */ "enginn",
  /* 138 */ "enginn kjarni skilaði sér þótt {0} væru þekktir — fyrri listi geymdur",
  /* 139 */ "enginn hermir",
  /* 140 */ "Enginn hermir uppsettur",
  /* 141 */ "Enginn leikur þekktist",
  /* 142 */ "Engar niðurstöður",
  /* 143 */ "engin",
  /* 144 */ "safnið ólæsilegt — {0}",
  /* 145 */ "tengd",
  /* 146 */ "skjámynd",
  /* 147 */ "Skipta um kápumynd…",
  /* 148 */ "Skipta…",
  /* 149 */ "Hver díll verður að níu",
  /* 150 */ "Hver díll verður að fjórum: skýrt, án bjögunar",
  /* 151 */ "Hver díll verður að sextán — fyrir stóra skjái",
  /* 152 */ "Hlaða",
  /* 153 */ "Velja kápumynd…",
  /* 154 */ "veldu fyrst leik í safninu",
  /* 155 */ "kjarni: {0}",
  /* 156 */ "kjarni ekki uppsettur",
  /* 157 */ "Uppsettir kjarnar",
  /* 158 */ "libretro-kjarnar",
  /* 159 */ "Mikil birtuskil",
  /* 160 */ "eigin skel: {0}",
  /* 161 */ "losun ófullgerð — {0}",
  /* 162 */ "könnun: {0}",
  /* 163 */ "könnun rofin — {0}",
  /* 164 */ "Velja forritið fyrir {0} handvirkt",
  /* 165 */ "mappa bætt við: {0}",
  /* 166 */ "mappa opnuð: {0}",
  /* 167 */ "Sjálfgefin mappa",
  /* 168 */ "Viðbættar möppur",
  /* 169 */ "Esc",
  /* 170 */ "Hólf {0}",
  /* 171 */ "hólf {0} — {1}",
  /* 172 */ "Hermir fyrir þessa möppu",
  /* 173 */ "utanaðkomandi hermar",
  /* 174 */ "í gangi",
  /* 175 */ "á sínum stað",
  /* 176 */ "gat ekki vistað — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi getur sótt þá af opinberri smiðju libretro. Veldu þær leikjatölvur sem þú hefur áhuga á.",
  /* 179 */ "EvaChi stöðvaðist við að ræsa „{0}“, með herminum {1}.",
  /* 180 */ "EvaChi stöðvaðist, með herminum {0}.",
  /* 181 */ "external_systems → {0} hermar skráðir",
  /* 182 */ "Uppáhald",
  /* 183 */ "Uppáhöld",
  /* 184 */ "kerfisskrár ólæsilegar — {0}",
  /* 185 */ "Örvatakkar",
  /* 186 */ "Game Boy",
  /* 187 */ "Reitir",
  /* 188 */ "{0} vantar hjá uppsettum leikjatölvum",
  /* 189 */ "uppsetningu lokið: {0}",
  /* 190 */ "Set upp…",
  /* 191 */ "uppsett",
  /* 192 */ "sett upp af EvaChi",
  /* 193 */ "Setja upp",
  /* 194 */ "túlkur: {0}",
  /* 195 */ "spyr uppsetta kjarna…",
  /* 196 */ "Ræsa",
  /* 197 */ "Ræsa valinn leik",
  /* 198 */ "Lofnarblóm",
  /* 199 */ "Leikjatölvurnar í röð, leikirnir í dálki, bakgrunnur sem bylgjast. Að hætti leikjatölvu í stofunni.",
  /* 200 */ "Útlínurnar renna saman — líkara gömlu sjónvarpi",
  /* 201 */ "Kápumyndirnar stórar, flettar með stýringu. Hugsað fyrir sófann.",
  /* 202 */ "Dílarnir haldast ferkantaðir, eins og á upprunalegu vélinni",
  /* 203 */ "tengingar stýringar færðar í upphaflegt horf",
  /* 204 */ "list_cores → {0} kjarnar tilkynntir",
  /* 205 */ "Listi",
  /* 206 */ "listi kjarna ófáanlegur — {0}",
  /* 207 */ "listi herma ófáanlegur — {0}",
  /* 208 */ "Leikjastýring",
  /* 209 */ "stýring: {0}",
  /* 210 */ "Stýring: {0}",
  /* 211 */ "stýring aftengd",
  /* 212 */ "VANTAR",
  /* 213 */ "Minta",
  /* 214 */ "Hreyfivalmynd",
  /* 215 */ "Uppfæra",
  /* 216 */ "Setja í uppáhald",
  /* 217 */ "lagt til hliðar: {0} · {1}",
  /* 218 */ "innan við mínúta",
  /* 219 */ "Skýrt",
  /* 220 */ "heiti, forrit og skráarendingar eru öll nauðsynleg",
  /* 221 */ "NEI",
  /* 222 */ "ekki uppsett á þessari vél",
  /* 223 */ "Bleik nótt",
  /* 224 */ "Úthaf",
  /* 225 */ "eða",
  /* 226 */ "já",
  /* 227 */ "gat ekki opnað — {0}",
  /* 228 */ "vefsíða: aðeins innri kjarnar í boði, ekkert safn",
  /* 229 */ "Pappír",
  /* 230 */ "sjálfgefið",
  /* 231 */ "Fara um reitina og hreyfivalmyndirnar",
  /* 232 */ "heilskjá hafnað — {0}",
  /* 233 */ "ýttu á hnappinn sem þú vilt á stýringunni",
  /* 234 */ "ýttu á lykil…",
  /* 235 */ "frágangur: {0} · {1}",
  /* 236 */ "frágangur mistókst — {0}",
  /* 237 */ "leit að hermum rofin — {0}",
  /* 238 */ "Loka glugga",
  /* 239 */ "gat ekki endurstillt — {0}",
  /* 240 */ "Fyllir gluggann og heldur hlutföllunum",
  /* 241 */ "Halda áfram",
  /* 242 */ "Halda áfram frá þessari vistun — hægrismelltu til að tæma hana",
  /* 243 */ "Endurvekja",
  /* 244 */ "gat ekki endurvakið — {0}",
  /* 245 */ "Fjarlægja",
  /* 246 */ "Taka úr uppáhaldi",
  /* 247 */ "Fjarlægja kápumynd",
  /* 248 */ "gat ekki fjarlægt — {0}",
  /* 249 */ "ekkert að ganga frá",
  /* 250 */ "ekkert stendur í vegi",
  /* 251 */ "Ekkert passar við „{0}“.",
  /* 252 */ "Bleikt og hvítt",
  /* 253 */ "engin mynd",
  /* 254 */ "Vista",
  /* 255 */ "Vista hér",
  /* 256 */ "gat ekki valið — {0}",
  /* 257 */ "Upprunaleg stærð leikjatölvunnar, upp á díl",
  /* 258 */ "Ljúka",
  /* 259 */ "ljóst þema",
  /* 260 */ "dökkt þema",
  /* 261 */ "allt er uppsett",
  /* 262 */ "fannst: {0}",
  /* 263 */ "Einn kafli á hverja leikjatölvu, í töflu. Þéttasta sýnin fyrir músina.",
  /* 264 */ "tómt",
  /* 265 */ "leggist hér, eins og romsettin: FinalBurn Neo leitar aðeins í þessari möppu",
  /* 266 */ "bætir við upphafsskjá leikjatölvunnar",
  /* 267 */ "ræsikóði vélarinnar",
  /* 268 */ "margir leikir ræsast án hans; valmynd leikjatölvunnar ekki",
  /* 269 */ "amerískt BIOS",
  /* 270 */ "amerískt og evrópskt BIOS",
  /* 271 */ "evrópskt BIOS",
  /* 272 */ "japanskt BIOS",
  /* 273 */ "afkóðunarlyklar; án þeirra er dulkóðuðu afriti hafnað",
  /* 274 */ "Machines-mappan úr blueMSX-dreifingunni, með Databases við hliðina",
  /* 275 */ "sama",
  /* 276 */ "nauðsynlegt fyrir CD-leiki, óþarft fyrir HuCard-kort",
  /* 277 */ "nauðsynlegt fyrir Mega-CD-leiki, óþarft fyrir hylki",
  /* 278 */ "Kickstart 1.3; annars fellur PUAE aftur á AROS, frjálst en síður samhæft",
  /* 279 */ "Kickstart 3.1; nauðsynlegt fyrir AGA-leiki, sem A500 ræður ekki við",
  /* 280 */ "melonDS hermir BIOS sjálfgefið; það raunverulega er trúrra",
  /* 281 */ "mGBA kemst af án þess; nokkrir leikir krefjast þess fyrir upphafsskjáinn",
  /* 282 */ "fastbúnaður leikjatölvunnar",
  /* 283 */ "fastbúnaður vélarinnar",
  /* 284 */ "fastbúnaður Panasonic FZ-10; það er þetta heiti sem Opera tekur sjálfgefið",
  /* 285 */ "melonDS breytir henni og geymir frumritið sem .bak",
  /* 286 */ "leturgerðir",
  /* 287 */ "stillingar og dagsetning leikjatölvunnar",
  /* 288 */ "án hans gengur kjarninn en skjárinn helst svartur",
  /* 289 */ "stafatafla leikjatölvunnar",
  /* 290 */ "amerísk útgáfa, fyrir Sega CD-leiki frá Bandaríkjunum",
  /* 291 */ "japönsk útgáfa, fyrir japanska Mega-CD-leiki",
  /* 292 */ "skjámyndir",
  /* 293 */ "skjámyndir",
  /* 294 */ "skjámynd",
  /* 295 */ "skjámyndir",
  /* 296 */ "skjámyndir",
  /* 297 */ "skjámyndir",
  /* 298 */ "kjarnar",
  /* 299 */ "kjarnar",
  /* 300 */ "kjarni",
  /* 301 */ "kjarnar",
  /* 302 */ "kjarnar",
  /* 303 */ "kjarnar",
  /* 304 */ "hermar",
  /* 305 */ "hermar",
  /* 306 */ "hermir",
  /* 307 */ "hermar",
  /* 308 */ "hermar",
  /* 309 */ "hermar",
  /* 310 */ "skrár",
  /* 311 */ "skrár",
  /* 312 */ "skrá",
  /* 313 */ "skrár",
  /* 314 */ "skrár",
  /* 315 */ "skrár",
  /* 316 */ "leikir",
  /* 317 */ "leikir",
  /* 318 */ "leikur",
  /* 319 */ "leikir",
  /* 320 */ "leikir",
  /* 321 */ "leikir",
  /* 322 */ "<code>{rom}</code> verður skipt út fyrir slóð leiksins. Án þess er slóðinni bætt aftast — það er einmitt það sem flestir hermar búast við.",
  /* 323 */ "<strong>Utan leiks er allt gert með stýringunni:</strong> áttirnar fara um safnið, gluggana og valmyndastikuna; <strong>A</strong> staðfestir, <strong>B</strong> fer til baka, <strong>Start</strong> opnar valmyndastikuna. Meðan á leik stendur skila <strong>Select og Start saman</strong> þér aftur í safnið — tveir hnappar í einu, því hvor um sig þjónar leiknum.",
  /* 324 */ "Engar skjámyndir. Ýttu á <strong>F12</strong> meðan á leik stendur, eða <strong>Select + Y</strong> á stýringunni.",
  /* 325 */ "Hver leikjatölva þarf sinn hermi. EvaChi sækir þá á opinbera smiðju libretro-verkefnisins, <code>buildbot.libretro.com</code>, og setur þá upp í sinni eigin möppu. Engu er dreift áfram: þetta eru útgáfurnar sem höfundar þeirra gáfu út.",
  /* 326 */ "Fjögur hólf á hvern leik, geymd á disknum. Feitletraða hólfið er það sem <strong>F2</strong> og <strong>F4</strong> nota — og <strong>Select + L1</strong> / <strong>Select + R1</strong> á stýringunni. Hægrismelltu á hólf til að tæma það.",
  /* 327 */ "Hver hermir keyrir í sínu eigin ferli: þegar hann fellur, sér EvaChi það og fer aftur í safnið. Leikurinn sem stendur yfir tapast og vistun leiksins hefur kannski ekki náð að skrifast. Að leggja herminn til hliðar skilur hann eftir uppsettan en hættir að bjóða hann. Þú getur endurvakið hann hvenær sem er í <strong>Skrá → Hermar</strong>, neðst í glugganum.",
  /* 328 */ "Ein skrá á hvern leik á disknum <small> CD-leikur kemur sem eitt <code>.cue</code>-blað og jafnmargar <code>.bin</code>-skrár og lögin voru á disknum. Aðeins blaðið ræsist: lögin eru falin þegar það er til staðar. Án blaðs er ekkert falið. </small>",
  /* 329 */ "(tómt) eða --fullscreen {rom}",
  /* 330 */ "Hundrað prósent er hraði leikjatölvunnar sjálfrar. Undir því hægist á leiknum, yfir því flýgur hann af stað — og hljóðið fylgir með, dýpra eða hvellara. Á leikjastýringunni færa vinstri og hægri þig um eitt þrep í senn. Gildir aðeins um innri kjarna: ytri hermir heldur sínum eigin hraða.",
  /* 331 */ "Fimm leikjatölvur í einu",
  /* 332 */ "Stýrikross",
  /* 333 */ "Frá einum upphafsstaf til næsta",
  /* 334 */ "Í hreyfivalmyndunum, fimm leikir í einu",
  /* 335 */ "Leikhraði",
  /* 336 */ "Hætta við",
  /* 337 */ "Dragðu rammann til, eða gríptu í eitt horn hans. Örvalyklarnir færa hann, og með Shift stækkar hann eða minnkar. Fari ramminn út fyrir myndina bætast gegnsæjar rendur við kápuna: þannig sýnirðu kápu sem er of þröng aðeins víðar. Á leikjastýringunni færa stefnutakkarnir rammann og gikkirnir stilla stærðina.",
  /* 338 */ "Sníða",
  /* 339 */ "Sníða kápuna",
  /* 340 */ "Öll myndin",
  /* 341 */ "{0} — kápan sniðin",
  /* 342 */ "{0} — engin kápa til að sníða",
  /* 343 */ "ólæsileg kápa — {0}",
  /* 344 */ "tókst ekki að sníða — {0}",
  /* 345 */ "Sníða kápuna…",
  /* 346 */ "Hraðspólun, meðan báðum stýripinnum er haldið niðri",
  /* 347 */ "{0} lagt til hliðar",
  /* 348 */ "Hermirinn {0} stöðvaðist meðan á „{1}“ stóð.",
  /* 349 */ "Hermirinn {0} stöðvaðist.",
  /* 350 */ "Hermirinn stöðvaðist",
  /* 351 */ "tókst ekki að leggja til hliðar — {0}",
  /* 352 */ "leggist hér: {0}",
  /* 353 */ "vantar kerfisskrá: {0}",
  /* 354 */ "Þakkir",
  /* 355 */ "Leyfi sem heimilar ekki viðskiptanotkun, vert að vita áður en byggt er á þessu verki: {0}.",
  /* 356 */ "EvaChi skrifar engan hermi: hún hýsir þá. Hver og einn er sjálfstætt frjálst verkefni, skrifað af öðrum, sem EvaChi sækir til höfunda sinna þegar á þarf að halda — ekki ein lína af kóða þeirra er afrituð hingað, engu bæti er dreift áfram. Nöfnin og leyfin hér að neðan eru þau sem hvert verkefni gefur upp sjálft.",
  /* 357 */ "Hringekja",
  /* 358 */ "Kápurnar að framan, tölvurnar í stafla, ryk sem stígur. Eins og sýningarstandur.",
];
