/**
 * Italien — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * numérotées en commentaire sont là pour qu'on puisse le vérifier à l'œil.
 */

export const it: readonly string[] = [
  /* 1 */ "Col controller",
  /* 2 */ "A avvia · X preferito · Y ritaglia · L1/R1 console · L2/R2 lettera · B indietro",
  /* 3 */ "Informazioni su EvaChi",
  /* 4 */ "Informazioni…",
  /* 5 */ "In arrivo: filtri a tubo catodico, griglia, scansione. Il posto è pronto, i filtri arriveranno qui.",
  /* 6 */ "Aggiorna la libreria",
  /* 7 */ "Visualizza",
  /* 8 */ "Mostra le copertine dei giochi",
  /* 9 */ "Aiuto",
  /* 10 */ "Aggiungi una cartella di giochi…",
  /* 11 */ "Aggiungi una cartella…",
  /* 12 */ "Premi un pulsante del controller: il tasto corrispondente si illumina. Per cambiarne uno, passa alla riassegnazione, clicca il tasto da modificare, poi premi il pulsante voluto.",
  /* 13 */ "Argomenti",
  /* 14 */ "Con la tastiera",
  /* 15 */ "Nessun gioco",
  /* 16 */ "Nessun controller rilevato.",
  /* 17 */ "Libreria",
  /* 18 */ "Suoni di selezione col controller",
  /* 19 */ "Alcune console non si avviano senza il firmware originale. EvaChi non può fornirlo: è codice protetto da copyright, che si copia dalla macchina che si possiede. Ti dice però quale manca, con che nome, e dove metterlo.",
  /* 20 */ "Queste console non hanno un core libretro: il loro emulatore è un programma a parte, che EvaChi installa nella propria cartella e avvia direttamente nel gioco — senza passare dal suo menu. I giochi, le chiavi e i file di sistema restano a tuo carico.",
  /* 21 */ "Queste impostazioni riguardano solo i core interni. Un emulatore esterno ha le proprie, ed EvaChi non se ne occupa.",
  /* 22 */ "Questi non vengono più proposti: non hanno risposto all'interrogazione, oppure hanno fatto cadere EvaChi. Ripristinarli non li reinstalla — li rimette semplicemente nell'elenco.",
  /* 23 */ "Carica lo stato",
  /* 24 */ "Solo core interni. Clicca una scorciatoia poi premi il tasto o il pulsante voluto; col controller se ne prendono due alla volta, perché ognuno di essi serve già al gioco.",
  /* 25 */ "Comandi",
  /* 26 */ "Comandi…",
  /* 27 */ "Console recenti",
  /* 28 */ "Dichiara un altro emulatore",
  /* 29 */ "Direzioni / stick sinistro",
  /* 30 */ "Cartelle di giochi",
  /* 31 */ "Escludi questo emulatore",
  /* 32 */ "Arrivano dal server di miniature del progetto libretro, su richiesta. Se togli la spunta, la libreria non chiede più nulla alla rete.",
  /* 33 */ "Slot di salvataggio",
  /* 34 */ "Slot…",
  /* 35 */ "Emulatori",
  /* 36 */ "Emulatori esclusi",
  /* 37 */ "Emulatori esterni",
  /* 38 */ "Emulatori esterni…",
  /* 39 */ "Emulatori…",
  /* 40 */ "Emulazione",
  /* 41 */ "Durante la partita, tornare alla libreria — due pulsanti alla volta, perché ognuno di essi serve al gioco",
  /* 42 */ "Salva",
  /* 43 */ "Estensioni",
  /* 44 */ "Chiudi",
  /* 45 */ "File",
  /* 46 */ "File di sistema da installare a mano",
  /* 47 */ "Galleria",
  /* 48 */ "Gestisci le cartelle…",
  /* 49 */ "Grafica",
  /* 50 */ "Grafica…",
  /* 51 */ "Indica la cartella dove si trovano i tuoi giochi.",
  /* 52 */ "Installazione",
  /* 53 */ "Installa la selezione",
  /* 54 */ "Installa gli emulatori…",
  /* 55 */ "Interprete",
  /* 56 */ "Non serve sapere dove: mostra la cartella dove sta tutto alla rinfusa — BIOS, chiavi, firmware, archivi, sottocartelle comprese — ed EvaChi porta ogni file al posto giusto, per i core come per gli emulatori autonomi. Quello che nessuno reclama non viene spostato.",
  /* 57 */ "Copertine",
  /* 58 */ "Registro",
  /* 59 */ "Registro…",
  /* 60 */ "La volta precedente è finita male",
  /* 61 */ "Avviare il gioco, confermare",
  /* 62 */ "Lingua",
  /* 63 */ "La scelta viene conservata da un avvio all'altro. Ognuno è stato verificato leggibile: il testo mantiene ovunque un contrasto sufficiente sul suo sfondo.",
  /* 64 */ "Tienilo",
  /* 65 */ "Gli emulatori qui sotto sono già configurati — argomenti e formati compresi. EvaChi li cerca sul tuo disco; non li installa.",
  /* 66 */ "Associazioni originali",
  /* 67 */ "Smussatura",
  /* 68 */ "Aggiungere il gioco ai preferiti, o toglierlo",
  /* 69 */ "Musica del menu animato",
  /* 70 */ "Nome",
  /* 71 */ "Aprire la barra dei menu",
  /* 72 */ "Apri la cartella",
  /* 73 */ "Apri la cartella…",
  /* 74 */ "Apri un gioco…",
  /* 75 */ "per fotogramma",
  /* 76 */ "Impostazioni del core",
  /* 77 */ "Impostazioni del core…",
  /* 78 */ "Scorrere la libreria, le finestre e la barra dei menu",
  /* 79 */ "Sfoglia…",
  /* 80 */ "Pausa",
  /* 81 */ "Schermo intero",
  /* 82 */ "Per le console senza core libretro. EvaChi avvia il programma con il gioco come argomento: l'emulatore parte direttamente nella partita, senza passare dal suo menu.",
  /* 83 */ "Catturare una schermata",
  /* 84 */ "Presentazione",
  /* 85 */ "Pronto",
  /* 86 */ "Programma",
  /* 87 */ "Qualche accordo tenuto e qualche nota sparsa, composti sul momento invece che registrati: il brano non ripassa mai dallo stesso punto. Si ferma da solo appena un gioco parte.",
  /* 88 */ "Sistema una cartella…",
  /* 89 */ "Riassegna…",
  /* 90 */ "Cerca un gioco…",
  /* 91 */ "Riavvia",
  /* 92 */ "Torna alla libreria",
  /* 93 */ "Tornare indietro, chiudere",
  /* 94 */ "Salvataggio rapido",
  /* 95 */ "Salva lo stato",
  /* 96 */ "Shader",
  /* 97 */ "Audio",
  /* 98 */ "Start",
  /* 99 */ "Dimensione dell'immagine",
  /* 100 */ "Temi",
  /* 101 */ "Temi…",
  /* 102 */ "Un solo file…",
  /* 103 */ "Un breve tic quando cambi gioco, un altro quando lo avvii. Solo col controller: con il mouse e la tastiera il gesto si sente già.",
  /* 104 */ "Velocità",
  /* 105 */ "Vedi le schermate…",
  /* 106 */ "Puoi installarne solo una parte — nella libreria compaiono solo le console il cui emulatore è installato.",
  /* 107 */ "{0} — caricato",
  /* 108 */ "{0} — clic destro per cancellare",
  /* 109 */ "{0} — aggiunto ai preferiti",
  /* 110 */ "{0} — riavviato",
  /* 111 */ "{0} — tolto dai preferiti",
  /* 112 */ "{0} — scaricamento…",
  /* 113 */ "{0}: fallito, vedi il registro",
  /* 114 */ "{0} a disposizione",
  /* 115 */ "{0} salvato",
  /* 116 */ "{0} è un emulatore esterno: si avvia, non si ospita",
  /* 117 */ "{0} fps",
  /* 118 */ "{0} installato",
  /* 119 */ "{0} installato — {1}",
  /* 120 */ "{0} installato e pronto",
  /* 121 */ "{0} installati, {1} falliti — vedi il registro",
  /* 122 */ "{0} ripristinato",
  /* 123 */ "{0} rimosso",
  /* 124 */ "{0} su {1}",
  /* 125 */ "{0} sul disco, ma nessun core installato li apre.",
  /* 126 */ "da prendere su {0}, poi «Sfoglia…»",
  /* 127 */ "da scaricare",
  /* 128 */ "assente, facoltativo",
  /* 129 */ "Attiva",
  /* 130 */ "Ammorbidito",
  /* 131 */ "aggiunta impossibile — {0}",
  /* 132 */ "Adatta",
  /* 133 */ "Ambra",
  /* 134 */ "Ardesia",
  /* 135 */ "arresto — {0}",
  /* 136 */ "arresto improvviso la volta precedente — {0}",
  /* 137 */ "nessuno",
  /* 138 */ "nessun core restituito mentre {0} erano noti — elenco precedente conservato",
  /* 139 */ "nessun emulatore",
  /* 140 */ "Nessun emulatore installato",
  /* 141 */ "Nessun gioco riconosciuto",
  /* 142 */ "Nessun risultato",
  /* 143 */ "nessuna",
  /* 144 */ "libreria illeggibile — {0}",
  /* 145 */ "collegato",
  /* 146 */ "schermata",
  /* 147 */ "Cambia la copertina…",
  /* 148 */ "Cambia…",
  /* 149 */ "Ogni pixel su nove",
  /* 150 */ "Ogni pixel su quattro: nitido, senza deformazione",
  /* 151 */ "Ogni pixel su sedici — per i grandi schermi",
  /* 152 */ "Carica",
  /* 153 */ "Scegli una copertina…",
  /* 154 */ "scegli prima un gioco nella libreria",
  /* 155 */ "core: {0}",
  /* 156 */ "core non installato",
  /* 157 */ "Core installati",
  /* 158 */ "core libretro",
  /* 159 */ "Contrasto elevato",
  /* 160 */ "shell nativa: {0}",
  /* 161 */ "rilascio incompleto — {0}",
  /* 162 */ "scoperta: {0}",
  /* 163 */ "scoperta interrotta — {0}",
  /* 164 */ "Indica tu il programma di {0}",
  /* 165 */ "cartella aggiunta: {0}",
  /* 166 */ "cartella aperta: {0}",
  /* 167 */ "Cartella predefinita",
  /* 168 */ "Cartelle aggiunte",
  /* 169 */ "Esc",
  /* 170 */ "Slot {0}",
  /* 171 */ "slot {0} — {1}",
  /* 172 */ "Emulatore usato per questa cartella",
  /* 173 */ "emulatori esterni",
  /* 174 */ "in corso",
  /* 175 */ "presente",
  /* 176 */ "salvataggio impossibile — {0}",
  /* 177 */ "Invio",
  /* 178 */ "EvaChi può scaricarli dal server ufficiale del progetto libretro. Scegli le console che ti interessano.",
  /* 179 */ "EvaChi si è fermata mentre avviava «{0}», con l'emulatore {1}.",
  /* 180 */ "EvaChi si è fermata, con l'emulatore {0}.",
  /* 181 */ "external_systems → {0} emulatori dichiarati",
  /* 182 */ "Preferito",
  /* 183 */ "Preferiti",
  /* 184 */ "file di sistema illeggibili — {0}",
  /* 185 */ "Frecce",
  /* 186 */ "Game Boy",
  /* 187 */ "Griglia",
  /* 188 */ "mancano {0} a console installate",
  /* 189 */ "installazione terminata: {0}",
  /* 190 */ "Installazione…",
  /* 191 */ "installato",
  /* 192 */ "installato da EvaChi",
  /* 193 */ "Installa",
  /* 194 */ "interprete: {0}",
  /* 195 */ "interrogazione dei core installati…",
  /* 196 */ "Avvia",
  /* 197 */ "Avvia il gioco scelto",
  /* 198 */ "Lavanda",
  /* 199 */ "Le console in riga, i giochi in colonna, uno sfondo che ondeggia. Come su una console da salotto.",
  /* 200 */ "I contorni sono sfumati — più vicino a un vecchio televisore",
  /* 201 */ "Le copertine in grande, sfogliate col controller. Pensato per il divano.",
  /* 202 */ "I pixel restano quadrati, come sulla macchina originale",
  /* 203 */ "associazioni del controller riportate all'origine",
  /* 204 */ "list_cores → {0} core annunciati",
  /* 205 */ "Elenco",
  /* 206 */ "elenco dei core non disponibile — {0}",
  /* 207 */ "elenco degli emulatori non disponibile — {0}",
  /* 208 */ "Controller",
  /* 209 */ "controller: {0}",
  /* 210 */ "Controller: {0}",
  /* 211 */ "controller scollegato",
  /* 212 */ "MANCANTE",
  /* 213 */ "Menta",
  /* 214 */ "Menu animato",
  /* 215 */ "Aggiorna",
  /* 216 */ "Aggiungi ai preferiti",
  /* 217 */ "escluso: {0} · {1}",
  /* 218 */ "meno di un minuto",
  /* 219 */ "Nitido",
  /* 220 */ "nome, programma ed estensioni sono tutti necessari",
  /* 221 */ "NO",
  /* 222 */ "non installato su questa macchina",
  /* 223 */ "Notte rosa",
  /* 224 */ "Oceano",
  /* 225 */ "o",
  /* 226 */ "sì",
  /* 227 */ "apertura impossibile — {0}",
  /* 228 */ "pagina web: solo i core interni sono disponibili, senza libreria",
  /* 229 */ "Carta",
  /* 230 */ "predefinito",
  /* 231 */ "Scorrere la griglia e il menu animato",
  /* 232 */ "schermo intero rifiutato — {0}",
  /* 233 */ "premi il pulsante voluto sul controller",
  /* 234 */ "premi un tasto…",
  /* 235 */ "sistemazione: {0} · {1}",
  /* 236 */ "sistemazione impossibile — {0}",
  /* 237 */ "ricerca degli emulatori interrotta — {0}",
  /* 238 */ "Chiudere una finestra",
  /* 239 */ "riavvio impossibile — {0}",
  /* 240 */ "Riempie la finestra mantenendo le proporzioni",
  /* 241 */ "Riprendi",
  /* 242 */ "Riprendi questo salvataggio — clic destro per svuotarlo",
  /* 243 */ "Ripristina",
  /* 244 */ "ripristino impossibile — {0}",
  /* 245 */ "Rimuovi",
  /* 246 */ "Togli dai preferiti",
  /* 247 */ "Rimuovi la copertina",
  /* 248 */ "rimozione impossibile — {0}",
  /* 249 */ "niente da sistemare",
  /* 250 */ "nessun blocco",
  /* 251 */ "Niente corrisponde a «{0}».",
  /* 252 */ "Rosa e bianco",
  /* 253 */ "senza immagine",
  /* 254 */ "Salva",
  /* 255 */ "Salva qui",
  /* 256 */ "selezione impossibile — {0}",
  /* 257 */ "Dimensione originale della console, al pixel",
  /* 258 */ "Termina",
  /* 259 */ "tema chiaro",
  /* 260 */ "tema scuro",
  /* 261 */ "è installato tutto",
  /* 262 */ "trovato: {0}",
  /* 263 */ "Una sezione per console, a tabella. Il più fitto col mouse.",
  /* 264 */ "vuoto",
  /* 265 */ "da mettere qui, come i romset dei giochi: FinalBurn Neo cerca solo in questa cartella",
  /* 266 */ "aggiunge la schermata iniziale della console",
  /* 267 */ "avvio della macchina",
  /* 268 */ "molti giochi partono senza; il menu della console no",
  /* 269 */ "BIOS americano",
  /* 270 */ "BIOS americano ed europeo",
  /* 271 */ "BIOS europeo",
  /* 272 */ "BIOS giapponese",
  /* 273 */ "chiavi di decifratura; senza di esse un dump cifrato viene rifiutato",
  /* 274 */ "cartella delle macchine della distribuzione blueMSX, con Databases accanto",
  /* 275 */ "idem",
  /* 276 */ "indispensabile per i giochi su CD, inutile per le HuCard",
  /* 277 */ "indispensabile per i giochi Mega-CD, inutile per le cartucce",
  /* 278 */ "Kickstart 1.3; altrimenti PUAE ripiega su AROS, libero ma meno compatibile",
  /* 279 */ "Kickstart 3.1; necessario per i giochi AGA, che l'A500 non sa far girare",
  /* 280 */ "melonDS emula il BIOS per impostazione predefinita; quello vero è più fedele",
  /* 281 */ "mGBA ne fa a meno; qualche gioco lo richiede per la schermata iniziale",
  /* 282 */ "firmware della console",
  /* 283 */ "firmware della macchina",
  /* 284 */ "firmware Panasonic FZ-10; è questo il nome che Opera usa per impostazione predefinita",
  /* 285 */ "modificato da melonDS, che conserva l'originale in .bak",
  /* 286 */ "caratteri tipografici",
  /* 287 */ "impostazioni e data della console",
  /* 288 */ "senza di esso il core gira ma lo schermo resta nero",
  /* 289 */ "tabella dei caratteri della console",
  /* 290 */ "variante americana, per i giochi Sega CD statunitensi",
  /* 291 */ "variante giapponese, per i giochi Mega-CD giapponesi",
  /* 292 */ "schermate",
  /* 293 */ "schermate",
  /* 294 */ "schermata",
  /* 295 */ "schermate",
  /* 296 */ "schermate",
  /* 297 */ "schermate",
  /* 298 */ "core",
  /* 299 */ "core",
  /* 300 */ "core",
  /* 301 */ "core",
  /* 302 */ "core",
  /* 303 */ "core",
  /* 304 */ "emulatori",
  /* 305 */ "emulatori",
  /* 306 */ "emulatore",
  /* 307 */ "emulatori",
  /* 308 */ "emulatori",
  /* 309 */ "emulatori",
  /* 310 */ "file",
  /* 311 */ "file",
  /* 312 */ "file",
  /* 313 */ "file",
  /* 314 */ "file",
  /* 315 */ "file",
  /* 316 */ "giochi",
  /* 317 */ "giochi",
  /* 318 */ "gioco",
  /* 319 */ "giochi",
  /* 320 */ "giochi",
  /* 321 */ "giochi",
  /* 322 */ "<code>{rom}</code> verrà sostituito dal percorso del gioco. Senza di esso, il percorso viene aggiunto alla fine — è quello che si aspetta la maggior parte degli emulatori.",
  /* 323 */ "<strong>Fuori dal gioco, tutto si fa col controller:</strong> le direzioni scorrono la libreria, le finestre e la barra dei menu; <strong>A</strong> conferma, <strong>B</strong> torna indietro, <strong>Start</strong> apre la barra dei menu. Durante la partita, <strong>Select e Start insieme</strong> riportano alla libreria — due pulsanti alla volta, perché ognuno di essi serve al gioco.",
  /* 324 */ "Nessuna schermata. Premi <strong>F12</strong> durante la partita, o <strong>Select + Y</strong> col controller.",
  /* 325 */ "Ogni console ha bisogno del suo emulatore. EvaChi li prende dal server ufficiale del progetto libretro, <code>buildbot.libretro.com</code>, e li installa nella propria cartella. Niente viene ridistribuito: sono le versioni pubblicate dai loro autori.",
  /* 326 */ "Quattro slot per gioco, conservati sul disco. Lo slot in grassetto è quello che usano <strong>F2</strong> e <strong>F4</strong> — e <strong>Select + L1</strong> / <strong>Select + R1</strong> col controller. Clic destro su uno slot per svuotarlo.",
  /* 327 */ "Ogni emulatore gira nel proprio processo: quando cade, EvaChi se ne accorge e torna alla libreria. La partita in corso è persa, e il salvataggio del gioco potrebbe non essere stato scritto. Escluderlo lo lascia installato ma smette di proporlo. Potrai ripristinarlo in qualsiasi momento da <strong>File → Emulatori</strong>, in fondo alla finestra.",
  /* 328 */ "Un solo file per gioco su disco <small> Un gioco su CD arriva come un foglietto <code>.cue</code> e tanti file <code>.bin</code> quante erano le tracce del disco. Si avvia solo il foglietto: le tracce sono nascoste quando c'è. Senza foglietto, non si nasconde niente. </small>",
  /* 329 */ "(vuoto) o --fullscreen {rom}",
  /* 330 */ "Il cento per cento è la velocità della console. Sotto, il gioco rallenta; sopra, corre — e il suono lo segue, più grave o più acuto. Sul controller, sinistra e destra passano da una tacca alla successiva. Solo per i core interni: un emulatore esterno mantiene la sua.",
  /* 331 */ "Cinque console alla volta",
  /* 332 */ "Croce direzionale",
  /* 333 */ "Da un'iniziale alla successiva",
  /* 334 */ "Nel menu animato, cinque giochi alla volta",
  /* 335 */ "Velocità del gioco",
  /* 336 */ "Annulla",
  /* 337 */ "Trascina il riquadro, oppure tira un angolo. Le frecce lo spostano, con Maiusc lo ingrandisci o lo rimpicciolisci. Se esce dall'immagine, intorno alla copertina compaiono bande trasparenti: è così che si allarga una copertina troppo stretta. Con il controller le direzioni lo spostano e i grilletti ne regolano la dimensione.",
  /* 338 */ "Ritaglia",
  /* 339 */ "Ritaglia la copertina",
  /* 340 */ "Tutta l'immagine",
  /* 341 */ "{0} — copertina ritagliata",
  /* 342 */ "{0} — nessuna copertina da ritagliare",
  /* 343 */ "copertina illeggibile — {0}",
  /* 344 */ "ritaglio impossibile — {0}",
  /* 345 */ "Ritaglia la copertina…",
  /* 346 */ "Avanzamento rapido, finché entrambi gli stick restano premuti",
  /* 347 */ "{0} escluso",
  /* 348 */ "L'emulatore {0} si è fermato durante «{1}».",
  /* 349 */ "L'emulatore {0} si è fermato.",
  /* 350 */ "L'emulatore si è fermato",
  /* 351 */ "esclusione impossibile — {0}",
];
