/**
 * Lituanien — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * de rang en commentaire sont là pour qu'on puisse le vérifier à l'œil.
 */

export const lt: readonly string[] = [
  /* 1 */ "Pulteliu",
  /* 2 */ "A paleisti · X mėgstamas · Y apkirpti · L1/R1 konsolės · L2/R2 raidė · B atgal",
  /* 3 */ "Apie EvaChi",
  /* 4 */ "Apie…",
  /* 5 */ "Netrukus: kineskopo filtrai, pikselių tinklelis, eilučių skleistinė. Vieta paruošta, filtrai atsiras čia.",
  /* 6 */ "Atnaujinti biblioteką",
  /* 7 */ "Rodinys",
  /* 8 */ "Rodyti žaidimų viršelius",
  /* 9 */ "Žinynas",
  /* 10 */ "Pridėti žaidimų aplanką…",
  /* 11 */ "Pridėti aplanką…",
  /* 12 */ "Paspauskite pulto mygtuką: atitinkama komanda užsidega. Norėdami ją pakeisti, spustelėkite laukelį apačioje ir paspauskite norimą mygtuką. Tada mygtukas pereina kitai komandai: dvi komandos ant to paties mygtuko atrodytų kaip gedimas.",
  /* 13 */ "Argumentai",
  /* 14 */ "Klaviatūra",
  /* 15 */ "Žaidimų nėra",
  /* 16 */ "Pultelių neaptikta.",
  /* 17 */ "Biblioteka",
  /* 18 */ "Pasirinkimo garsai pulteliu",
  /* 19 */ "Kai kurios konsolės neužsiveda be originalios mikroprogramos. EvaChi negali jos pateikti: tai autorių teisių saugomas kodas, kopijuojamas iš savo pačių mašinos. Užtat ji pasako, kurios trūksta, kokiu vardu ir kur ją padėti.",
  /* 20 */ "Šios konsolės neturi libretro branduolio: jų emuliatorius yra atskira programa, kurią EvaChi įsirašo pas save ir paleidžia tiesiai į žaidimą — aplenkdama jo paties meniu. Žaidimai, raktai ir sisteminiai failai lieka jūsų rūpestis.",
  /* 21 */ "Šie nustatymai liečia tik vidinius branduolius. Išorinis emuliatorius turi savus, ir EvaChi į juos nesikiša.",
  /* 22 */ "Šie nebesiūlomi: jie neatsiliepė į užklausą arba parvertė EvaChi. Atkūrimas jų iš naujo neįdiegia — tiesiog grąžina į sąrašą.",
  /* 23 */ "Įkelti būseną…",
  /* 24 */ "Tik vidiniai branduoliai. Spustelėkite spartųjį klavišą ir paspauskite norimą klavišą ar mygtuką; pulteliu imami du mygtukai iš karto, nes kiekvienas jų jau reikalingas žaidimui.",
  /* 25 */ "Valdymas",
  /* 26 */ "Valdymas…",
  /* 27 */ "Paskiausios konsolės",
  /* 28 */ "Nurodyti kitą emuliatorių",
  /* 29 */ "Kryptys / kairioji svirtelė",
  /* 30 */ "Žaidimų aplankai",
  /* 31 */ "Atidėti šį emuliatorių",
  /* 32 */ "Jie imami iš libretro projekto miniatiūrų serverio, pagal poreikį. Atžymėjus, biblioteka nieko iš tinklo nebeprašo.",
  /* 33 */ "Išsaugojimo vietos",
  /* 34 */ "Vietos…",
  /* 35 */ "Emuliatoriai",
  /* 36 */ "Atidėti emuliatoriai",
  /* 37 */ "Išoriniai emuliatoriai",
  /* 38 */ "Išoriniai emuliatoriai…",
  /* 39 */ "Emuliatoriai…",
  /* 40 */ "Emuliacija",
  /* 41 */ "Žaidimo metu grįžti į biblioteką — du mygtukai iš karto, nes kiekvienas jų reikalingas žaidimui",
  /* 42 */ "Įrašyti",
  /* 43 */ "Plėtiniai",
  /* 44 */ "Užverti",
  /* 45 */ "Failas",
  /* 46 */ "Sisteminiai failai, kuriuos reikia įdiegti pačiam",
  /* 47 */ "Galerija",
  /* 48 */ "Tvarkyti aplankus…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Nurodykite aplanką, kuriame yra jūsų žaidimai.",
  /* 52 */ "Diegimas",
  /* 53 */ "Įdiegti pažymėtus",
  /* 54 */ "Įdiegti emuliatorius…",
  /* 55 */ "Interpretatorius",
  /* 56 */ "Nereikia žinoti, kur: parodykite aplanką, kuriame viskas mėtosi — BIOS, raktai, mikroprogramos, archyvai, kartu su poaplankiais — ir EvaChi nuneš kiekvieną failą į savo vietą, tiek branduoliams, tiek savarankiškiems emuliatoriams. Ko niekas neprašo, lieka nepajudinta.",
  /* 57 */ "Viršeliai",
  /* 58 */ "Žurnalas",
  /* 59 */ "Žurnalas…",
  /* 60 */ "Praėjusį kartą baigėsi blogai",
  /* 61 */ "Paleisti žaidimą, patvirtinti",
  /* 62 */ "Kalba",
  /* 63 */ "Pasirinkimas įsimenamas tarp paleidimų. Kiekviena patikrinta, ar įskaitoma: tekstas visur išlaiko pakankamą kontrastą su fonu.",
  /* 64 */ "Palikti",
  /* 65 */ "Toliau išvardyti emuliatoriai jau sutvarkyti — su argumentais ir formatais. EvaChi ieško jų jūsų diske; ji jų neįdiegia.",
  /* 66 */ "Pradiniai priskyrimai",
  /* 67 */ "Glodinimas",
  /* 68 */ "Įtraukti žaidimą į mėgstamus arba iš jų pašalinti",
  /* 69 */ "Animuotų meniu muzika",
  /* 70 */ "Pavadinimas",
  /* 71 */ "Atverti meniu juostą",
  /* 72 */ "Atverti aplanką",
  /* 73 */ "Atverti aplanką…",
  /* 74 */ "Atverti žaidimą…",
  /* 75 */ "per kadrą",
  /* 76 */ "Branduolio nustatymai",
  /* 77 */ "Branduolio nustatymai…",
  /* 78 */ "Naršyti biblioteką, langus ir meniu juostą",
  /* 79 */ "Naršyti…",
  /* 80 */ "Pauzė",
  /* 81 */ "Visas ekranas",
  /* 82 */ "Konsolėms, neturinčioms libretro branduolio. EvaChi paleidžia programą su žaidimu kaip argumentu: emuliatorius pradeda tiesiai nuo žaidimo, aplenkdamas savo paties meniu.",
  /* 83 */ "Padaryti ekrano kopiją",
  /* 84 */ "Vaizdas",
  /* 85 */ "Parengta",
  /* 86 */ "Programa",
  /* 87 */ "Keli užlaikyti akordai ir pavienės natos, kuriamos čia pat, o ne įrašytos: kūrinys niekada nepraeina to paties taško antrą kartą. Jis nutyla pats, vos tik pradedamas žaidimas.",
  /* 88 */ "Sutvarkyti aplanką…",
  /* 89 */ "Ištuštinti",
  /* 90 */ "Ieškoti žaidimo…",
  /* 91 */ "Atstatyti",
  /* 92 */ "Grįžti į biblioteką",
  /* 93 */ "Grįžti atgal, užverti",
  /* 94 */ "Greitas išsaugojimas",
  /* 95 */ "Išsaugoti būseną…",
  /* 96 */ "Shaders",
  /* 97 */ "Garsas",
  /* 98 */ "Start",
  /* 99 */ "Vaizdo dydis",
  /* 100 */ "Temos",
  /* 101 */ "Temos…",
  /* 102 */ "Tik vienas failas…",
  /* 103 */ "Trumpas spragtelėjimas perėjus prie kito žaidimo ir dar vienas jį paleidus. Tik pulteliu: su pele ir klaviatūra judesys ir taip jaučiamas.",
  /* 104 */ "Greitis",
  /* 105 */ "Peržiūrėti ekrano kopijas…",
  /* 106 */ "Galite įdiegti tik dalį jų — bibliotekoje matomos tik tos konsolės, kurių emuliatorius įdiegtas.",
  /* 107 */ "{0} — įkelta",
  /* 108 */ "{0} — dešinysis spustelėjimas ištrina",
  /* 109 */ "{0} — įtraukta į mėgstamus",
  /* 110 */ "{0} — atstatyta",
  /* 111 */ "{0} — pašalinta iš mėgstamų",
  /* 112 */ "{0} — atsiunčiama…",
  /* 113 */ "{0}: nepavyko, žr. žurnalą",
  /* 114 */ "prieinama {0}",
  /* 115 */ "{0} įrašyta",
  /* 116 */ "{0} yra išorinis emuliatorius: jis paleidžiamas, o ne priglaudžiamas",
  /* 117 */ "{0} k/s",
  /* 118 */ "{0} įdiegta",
  /* 119 */ "{0} įdiegta — {1}",
  /* 120 */ "{0} įdiegta ir parengta",
  /* 121 */ "įdiegta {0}, nepavyko {1} — žr. žurnalą",
  /* 122 */ "{0} atkurta",
  /* 123 */ "{0} pašalinta",
  /* 124 */ "{0} iš {1}",
  /* 125 */ "Diske {0}, bet nė vienas įdiegtas branduolys jų neatidaro.",
  /* 126 */ "paimkite iš {0}, tada „Naršyti…“",
  /* 127 */ "reikia atsiųsti",
  /* 128 */ "nėra, neprivalomas",
  /* 129 */ "Įjungti",
  /* 130 */ "Suglodintas",
  /* 131 */ "nepavyko pridėti — {0}",
  /* 132 */ "Pritaikyti",
  /* 133 */ "Gintaras",
  /* 134 */ "Skalūnas",
  /* 135 */ "sustojo — {0}",
  /* 136 */ "praėjusį kartą nulūžo — {0}",
  /* 137 */ "nėra",
  /* 138 */ "negrąžinta nė vieno branduolio, nors žinota {0} — paliktas ankstesnis sąrašas",
  /* 139 */ "emuliatorių nėra",
  /* 140 */ "Neįdiegta nė vieno emuliatoriaus",
  /* 141 */ "Neatpažinta nė vieno žaidimo",
  /* 142 */ "Nieko nerasta",
  /* 143 */ "nėra",
  /* 144 */ "biblioteka neįskaitoma — {0}",
  /* 145 */ "prijungtas",
  /* 146 */ "ekrano kopija",
  /* 147 */ "Keisti viršelį…",
  /* 148 */ "Keisti…",
  /* 149 */ "Kiekvienas pikselis virsta devyniais",
  /* 150 */ "Kiekvienas pikselis virsta keturiais: ryšku, be iškraipymų",
  /* 151 */ "Kiekvienas pikselis virsta šešiolika — dideliems ekranams",
  /* 152 */ "Įkelti",
  /* 153 */ "Pasirinkti viršelį…",
  /* 154 */ "pirmiausia pasirinkite žaidimą bibliotekoje",
  /* 155 */ "branduolys: {0}",
  /* 156 */ "branduolys neįdiegtas",
  /* 157 */ "Įdiegti branduoliai",
  /* 158 */ "libretro branduoliai",
  /* 159 */ "Didelis kontrastas",
  /* 160 */ "savasis apvalkalas: {0}",
  /* 161 */ "iškrauta ne iki galo — {0}",
  /* 162 */ "aptikta: {0}",
  /* 163 */ "aptikimas nutrūko — {0}",
  /* 164 */ "Pačiam nurodyti {0} programą",
  /* 165 */ "pridėtas aplankas: {0}",
  /* 166 */ "atvertas aplankas: {0}",
  /* 167 */ "Numatytasis aplankas",
  /* 168 */ "Pridėti aplankai",
  /* 169 */ "Esc",
  /* 170 */ "Vieta {0}",
  /* 171 */ "vieta {0} — {1}",
  /* 172 */ "Šiam aplankui naudojamas emuliatorius",
  /* 173 */ "išoriniai emuliatoriai",
  /* 174 */ "vykdoma",
  /* 175 */ "vietoje",
  /* 176 */ "nepavyko įrašyti — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi gali juos atsiųsti iš oficialios libretro dirbtuvės. Pasirinkite jus dominančias konsoles.",
  /* 179 */ "EvaChi nutrūko paleisdama „{0}“ su emuliatoriumi {1}.",
  /* 180 */ "EvaChi nutrūko su emuliatoriumi {0}.",
  /* 181 */ "external_systems → paskelbta emuliatorių: {0}",
  /* 182 */ "Mėgstamas",
  /* 183 */ "Mėgstami",
  /* 184 */ "sisteminiai failai neįskaitomi — {0}",
  /* 185 */ "Rodyklės",
  /* 186 */ "Game Boy",
  /* 187 */ "Tinklelis",
  /* 188 */ "įdiegtoms konsolėms trūksta: {0}",
  /* 189 */ "diegimas baigtas: {0}",
  /* 190 */ "Diegiama…",
  /* 191 */ "įdiegta",
  /* 192 */ "įdiegė EvaChi",
  /* 193 */ "Įdiegti",
  /* 194 */ "interpretatorius: {0}",
  /* 195 */ "klausinėjami įdiegti branduoliai…",
  /* 196 */ "Paleisti",
  /* 197 */ "Paleisti pasirinktą žaidimą",
  /* 198 */ "Levanda",
  /* 199 */ "Konsolės eilėje, žaidimai stulpelyje, banguojantis fonas. Kaip stacionarioje konsolėje.",
  /* 200 */ "Kontūrai suliejami — arčiau seno televizoriaus",
  /* 201 */ "Dideli viršeliai, naršomi pulteliu. Sumanyta sofai.",
  /* 202 */ "Pikseliai lieka kvadratiniai, kaip originalioje mašinoje",
  /* 203 */ "pultelio priskyrimai grąžinti į pradinius",
  /* 204 */ "list_cores → paskelbta branduolių: {0}",
  /* 205 */ "Sąrašas",
  /* 206 */ "branduolių sąrašas neprieinamas — {0}",
  /* 207 */ "emuliatorių sąrašas neprieinamas — {0}",
  /* 208 */ "Pultelis",
  /* 209 */ "pultelis: {0}",
  /* 210 */ "Pultelis: {0}",
  /* 211 */ "pultelis atjungtas",
  /* 212 */ "TRŪKSTA",
  /* 213 */ "Mėta",
  /* 214 */ "Animuotas meniu",
  /* 215 */ "Atnaujinti",
  /* 216 */ "Įtraukti į mėgstamus",
  /* 217 */ "atidėta: {0} · {1}",
  /* 218 */ "mažiau nei minutė",
  /* 219 */ "Ryšku",
  /* 220 */ "reikia visų trijų: pavadinimo, programos ir plėtinių",
  /* 221 */ "NE",
  /* 222 */ "šioje mašinoje neįdiegtas",
  /* 223 */ "Rožinė naktis",
  /* 224 */ "Vandenynas",
  /* 225 */ "arba",
  /* 226 */ "taip",
  /* 227 */ "nepavyko atverti — {0}",
  /* 228 */ "tinklalapis: prieinami tik vidiniai branduoliai, be bibliotekos",
  /* 229 */ "Popierius",
  /* 230 */ "numatytasis",
  /* 231 */ "Naršyti tinklelį ir animuotus meniu",
  /* 232 */ "viso ekrano atsisakyta — {0}",
  /* 233 */ "paspauskite norimą mygtuką pultelyje",
  /* 234 */ "paspauskite klavišą…",
  /* 235 */ "tvarkymas: {0} · {1}",
  /* 236 */ "nepavyko sutvarkyti — {0}",
  /* 237 */ "emuliatorių paieška nutrūko — {0}",
  /* 238 */ "Užverti langą",
  /* 239 */ "nepavyko atstatyti — {0}",
  /* 240 */ "Užpildo langą išlaikydamas proporcijas",
  /* 241 */ "Tęsti",
  /* 242 */ "Pakeisti",
  /* 243 */ "Atkurti",
  /* 244 */ "nepavyko atkurti — {0}",
  /* 245 */ "Pašalinti",
  /* 246 */ "Pašalinti iš mėgstamų",
  /* 247 */ "Pašalinti viršelį",
  /* 248 */ "nepavyko pašalinti — {0}",
  /* 249 */ "nėra ko tvarkyti",
  /* 250 */ "niekas netrukdo",
  /* 251 */ "Pagal „{0}“ nieko nerasta.",
  /* 252 */ "Rožinė ir balta",
  /* 253 */ "be paveikslėlio",
  /* 254 */ "Išsaugoti",
  /* 255 */ "Išsaugoti čia",
  /* 256 */ "nepavyko pasirinkti — {0}",
  /* 257 */ "Originalus konsolės dydis, pikselis į pikselį",
  /* 258 */ "Išmesti",
  /* 259 */ "šviesi tema",
  /* 260 */ "tamsi tema",
  /* 261 */ "viskas įdiegta",
  /* 262 */ "rasta: {0}",
  /* 263 */ "Po skiltį kiekvienai konsolei, lentele. Tankiausia pelei.",
  /* 264 */ "tuščia",
  /* 265 */ "dėkite čia, kaip ir žaidimų romsetus: FinalBurn Neo ieško tik šiame aplanke",
  /* 266 */ "prideda konsolės pasveikinimo ekraną",
  /* 267 */ "mašinos paleidiklis",
  /* 268 */ "daug žaidimų pasileidžia ir be jos; konsolės meniu – ne",
  /* 269 */ "amerikietiškas BIOS",
  /* 270 */ "amerikietiškas ir europietiškas BIOS",
  /* 271 */ "europietiškas BIOS",
  /* 272 */ "japoniškas BIOS",
  /* 273 */ "iššifravimo raktai; be jų šifruota rinkmena atmetama",
  /* 274 */ "blueMSX paketo mašinų aplankas, šalia jo – Databases",
  /* 275 */ "tas pats",
  /* 276 */ "būtinas CD žaidimams, nereikalingas HuCard kortelėms",
  /* 277 */ "būtinas Mega-CD žaidimams, nereikalingas kasetėms",
  /* 278 */ "Kickstart 1.3; kitaip PUAE griebiasi AROS – laisvo, bet mažiau suderinamo",
  /* 279 */ "Kickstart 3.1; reikalingas AGA žaidimams, kurių A500 paleisti nemoka",
  /* 280 */ "melonDS pagal numatymą emuliuoja BIOS; tikrasis yra tikslesnis",
  /* 281 */ "mGBA apsieina be jo; keli žaidimai jo reikalauja dėl pasveikinimo ekrano",
  /* 282 */ "konsolės mikroprograma",
  /* 283 */ "mašinos mikroprograma",
  /* 284 */ "Panasonic FZ-10 mikroprograma; būtent šio vardo Opera ieško pagal numatymą",
  /* 285 */ "melonDS jį pakeičia, o originalą išsaugo su .bak",
  /* 286 */ "šriftai",
  /* 287 */ "konsolės nustatymai ir data",
  /* 288 */ "be jo branduolys sukasi, bet ekranas lieka juodas",
  /* 289 */ "konsolės simbolių lentelė",
  /* 290 */ "amerikietiškas variantas, JAV Sega CD žaidimams",
  /* 291 */ "japoniškas variantas, japoniškiems Mega-CD žaidimams",
  /* 292 */ "ekrano kopijos",
  /* 293 */ "ekrano kopijos",
  /* 294 */ "ekrano kopija",
  /* 295 */ "ekrano kopijų",
  /* 296 */ "ekrano kopijos",
  /* 297 */ "ekrano kopijų",
  /* 298 */ "branduoliai",
  /* 299 */ "branduolio",
  /* 300 */ "branduolys",
  /* 301 */ "branduolių",
  /* 302 */ "branduoliai",
  /* 303 */ "branduolių",
  /* 304 */ "emuliatoriai",
  /* 305 */ "emuliatoriaus",
  /* 306 */ "emuliatorius",
  /* 307 */ "emuliatorių",
  /* 308 */ "emuliatoriai",
  /* 309 */ "emuliatorių",
  /* 310 */ "failai",
  /* 311 */ "failo",
  /* 312 */ "failas",
  /* 313 */ "failų",
  /* 314 */ "failai",
  /* 315 */ "failų",
  /* 316 */ "žaidimai",
  /* 317 */ "žaidimo",
  /* 318 */ "žaidimas",
  /* 319 */ "žaidimų",
  /* 320 */ "žaidimai",
  /* 321 */ "žaidimų",
  /* 322 */ "<code>{rom}</code> bus pakeistas žaidimo keliu. Be jo kelias pridedamas gale — būtent to tikisi dauguma emuliatorių.",
  /* 323 */ "<strong>Už žaidimo ribų viskas daroma pulteliu:</strong> kryptys naršo biblioteką, langus ir meniu juostą; <strong>A</strong> patvirtina, <strong>B</strong> grąžina atgal, <strong>Start</strong> atveria meniu juostą. Žaidimo metu <strong>Select ir Start kartu</strong> grąžina į biblioteką — du mygtukai iš karto, nes kiekvienas jų reikalingas žaidimui.",
  /* 324 */ "Ekrano kopijų nėra. Žaidimo metu paspauskite <strong>F12</strong> arba <strong>Select + Y</strong> pultelyje.",
  /* 325 */ "Kiekvienai konsolei reikia savo emuliatoriaus. EvaChi paima juos iš oficialios libretro projekto dirbtuvės <code>buildbot.libretro.com</code> ir įdiegia į savo aplanką. Niekas nėra platinama iš naujo: tai pačių autorių paskelbtos versijos.",
  /* 326 */ "Keturios vietos kiekvienam žaidimui, laikomos diske. Kiekvienas veiksmas užrašytas po vieta, o pakeitimas ar ištuštinimas prašo patvirtinimo. <strong>F2</strong> ir <strong>F4</strong> — bei <strong>Select + L1</strong> / <strong>Select + R1</strong> pulte — eina tiesiai į paryškintą vietą nieko neklausdami.",
  /* 327 */ "Kiekvienas emuliatorius sukasi savame procese: kai jis krinta, EvaChi tai pamato ir grįžta į biblioteką. Vykstantis žaidimas prarandamas, o žaidimo išsaugojimas galbūt nebuvo įrašytas. Atidėjus šį emuliatorių, jis lieka įdiegtas, bet nebesiūlomas. Bet kada galėsite jį atkurti per <strong>Failas → Emuliatoriai</strong>, lango apačioje.",
  /* 328 */ "Tik vienas failas kiekvienam žaidimui diske <small> CD žaidimas ateina vienu <code>.cue</code> lapeliu ir tiek <code>.bin</code> failų, kiek diske buvo takelių. Paleidžiamas tik lapelis: kai jis yra, takeliai paslepiami. Be lapelio nieko neslepiama. </small>",
  /* 329 */ "(tuščia) arba --fullscreen {rom}",
  /* 330 */ "Šimtas procentų – tikrasis konsolės greitis. Žemiau žaidimas sulėtėja, aukščiau – skuodžia, o garsas seka iš paskos: žemesnis arba aukštesnis. Pulte kairė ir dešinė perkelia iš vienos padalos į kitą. Tik vidiniams branduoliams: išorinis emuliatorius laikosi savojo greičio.",
  /* 331 */ "Penkios konsolės iš karto",
  /* 332 */ "Krypčių kryžiukas",
  /* 333 */ "Iš vienos pradinės raidės į kitą",
  /* 334 */ "Animuotuose meniu – penki žaidimai iš karto",
  /* 335 */ "Žaidimo greitis",
  /* 336 */ "Atšaukti",
  /* 337 */ "Vilkite rėmelį arba tempkite vieną jo kampą. Rodyklės jį perkelia, o su Shift jis didėja arba mažėja. Kai rėmelis išlenda už paveikslėlio, aplink viršelį atsiranda skaidrios juostos: taip per ankštas viršelis parodomas plačiau. Su pulteliu kryptiniai mygtukai rėmelį perkelia, o gaidukai keičia jo dydį.",
  /* 338 */ "Apkirpti",
  /* 339 */ "Apkirpti viršelį",
  /* 340 */ "Visas vaizdas",
  /* 341 */ "{0} — viršelis apkirptas",
  /* 342 */ "{0} — nėra viršelio, kurį apkirpti",
  /* 343 */ "viršelis neįskaitomas — {0}",
  /* 344 */ "apkirpti nepavyko — {0}",
  /* 345 */ "Apkirpti viršelį…",
  /* 346 */ "Greitas prasukimas, kol abi svirtelės laikomos nuspaustos",
  /* 347 */ "{0} atidėta",
  /* 348 */ "Emuliatorius {0} sustojo žaidžiant „{1}“.",
  /* 349 */ "Emuliatorius {0} sustojo.",
  /* 350 */ "Emuliatorius sustojo",
  /* 351 */ "nepavyko atidėti — {0}",
  /* 352 */ "dėkite čia: {0}",
  /* 353 */ "trūksta sisteminio failo: {0}",
  /* 354 */ "Padėkos",
  /* 355 */ "Nekomercinė licencija — verta žinoti prieš perimant šį darbą: {0}.",
  /* 356 */ "EvaChi nerašo nė vieno emuliatoriaus: ji juos priglaudžia. Kiekvienas iš jų yra savarankiškas laisvas projektas, parašytas kitų, ir EvaChi jį prireikus parsisiunčia iš pačių autorių — nė viena jų kodo eilutė čia nenukopijuota, nė vienas baitas iš naujo neplatinamas. Toliau nurodyti pavadinimai ir licencijos yra tie, kuriuos kiekvienas projektas skelbia pats.",
  /* 357 */ "Karuselė",
  /* 358 */ "Viršeliai priekyje, konsolės krūvoje, kylančios dulkės. Tarsi vitrina.",
  /* 359 */ "Kaip sąsajos",
  /* 360 */ "Sąsajos kalba",
  /* 361 */ "Žaidimų kalba",
  /* 362 */ "Žaidimų kalba: {0}. Ji galios nuo kito paleidimo.",
  /* 363 */ "Atgal",
  /* 364 */ "Ieškoti",
  /* 365 */ "Rasti failus",
  /* 366 */ "Ieškoti reikšmės",
  /* 367 */ "Kitokia",
  /* 368 */ "Tokia pati",
  /* 369 */ "Plotis",
  /* 370 */ "Projektas libretro skelbia sukčiavimo failus, po vieną kiekvienam žaidimui. EvaChi palieka tik tuos, kurie tiksliai tinka jūsų žaidimui — tas pats pavadinimas, tas pats regionas, ta pati laida — ir verčiau nesiūlo nieko nei ką nors apytikslio: kodai, parašyti kitai versijai, rašo ne šiek tiek greta, o visai kitur.",
  /* 371 */ "Sukčiavimai",
  /* 372 */ "Mažiau",
  /* 373 */ "Sukčiavimų skydelis",
  /* 374 */ "Daugiau",
  /* 375 */ "Pradėti iš naujo",
  /* 376 */ "Sukčiavimai",
  /* 377 */ "Sukčiavimai…",
  /* 378 */ "Reikšmė",
  /* 379 */ "Lygu",
  /* 380 */ "{0} galimų adresų",
  /* 381 */ "Įdėta {0} failų, pašalinta {1}",
  /* 382 */ "{0} iš {1} žaidimų turi failą",
  /* 383 */ "{0} baitų atminties",
  /* 384 */ "Atmesta {0} reikšmių: už šio žaidimo atminties ribų",
  /* 385 */ "Šiam žaidimui failo nėra. Emuliavimo meniu skydelis „Sukčiavimai…“ jo ieško; jei nėra, reikšmės paieška veikia su bet kuriuo žaidimu.",
  /* 386 */ "Užšaldyta",
  /* 387 */ "Užšaldyti",
  /* 388 */ "Pažaiskite kiek ir pasakykite, ką reikšmė padarė.",
  /* 389 */ "Žaidimas buvo padėtas į šalį prieš pirmą sukčiavimą.",
  /* 390 */ "Ieškoma…",
  /* 391 */ "Tai, kas paliekama aplanke « drop u'r rom », keliauja į konsolę, kurią nurodo plėtinys. Kai tą patį plėtinį dalijasi kelios konsolės — disko atvaizdai — EvaChi verčiau paklausia, nei spėlioja.",
  /* 392 */ "Patvirtinimas",
  /* 393 */ "Ištrinti žaidimo įrašą…",
  /* 394 */ "Ištempimas",
  /* 395 */ "Žaidimas laiko savo skaičius atmintyje, bet nesako kur. Jie randami atmetant: jūs pasakote, kas nutiko ekrane matomam skaičiui, o EvaChi atmeta adresus, kuriems nutiko kitaip.",
  /* 396 */ "Taip",
  /* 397 */ "Nedaug konsolių turi šiandienio ekrano proporcijas, iš čia juodos juostos šonuose. Ties nuliu vaizdas išlaiko savo proporcijas; ties šimtu užpildo langą, net jei tenka ištempti.",
  /* 398 */ "Žaidimų tvarkymas",
  /* 399 */ "Sutvarkyti",
  /* 400 */ "Sutvarkyti paliktus žaidimus…",
  /* 401 */ "Matote 47 gyvybes: įrašykite 47 laukelyje « Reikšmė » ir spauskite « Ieškoti ». Praraskite vieną, įrašykite 46 ir spauskite « Lygu ». Jei skaičius niekur neužrašytas, palikite « Reikšmė » tuščią ir tarp dviejų žaidimo akimirkų pasakykite tik « Daugiau », « Mažiau », « Kitokia » arba « Tokia pati ». Rastą reikšmę paskui laiko « Užšaldyti ». « Plotis » yra skaičiaus dydis: 1 iki 255, 2 virš to, 4 dideliems skaitikliams.",
  /* 402 */ "sutvarkyta: {0}",
  /* 403 */ "nėra įrašo, kurį būtų galima ištrinti",
  /* 404 */ "Mygtukai",
  /* 405 */ "Jau bibliotekoje: {0}",
  /* 406 */ "Ištrinti {0} įrašą ir pradėti iš naujo? Vykstantis žaidimas bus sustabdytas, o tai, ką žaidimas buvo užsirašęs, bus prarasta.",
  /* 407 */ "Gaidukai",
  /* 408 */ "Palikti abu",
  /* 409 */ "Palikti aplanke",
  /* 410 */ "Aplankas tuščias.",
  /* 411 */ "Pakeisti vietą {0}? Tai, kas ten padėta, bus prarasta.",
  /* 412 */ "įrašas ištrintas — {0}",
  /* 413 */ "Sistema",
  /* 414 */ "Ištuštinti vietą {0}? Tai, kas ten padėta, bus prarasta.",
  /* 415 */ "Negyvoji zona – ta svirties dalis, kurioje ji dar laikoma ramybėje. Per maža – veikėjas pats nuslysta, pultui gulint ant stalo; per didelė – smulkūs judesiai pradingsta. Kai kurie žaidimai prašo papurtyti konsolę: kai pultas to pajusti nemoka, du žemiau esantys mygtukai priverčia žaidimą tuo patikėti.",
  /* 416 */ "Svirtis",
  /* 417 */ "Savarankiški emuliatoriai turi savus mygtukus, savuose failuose. Tai, ką čia pakeisite, iškart perkeliama ten – tiems, kurių formatą žinome iš pirmų lūpų: PCSX2, PPSSPP ir Dolphin. Seni nustatymai per pirmą kartą padedami į šalį, tuo pačiu vardu su galūne « .avant-evachi ».",
  /* 418 */ "Perkelti į išorinius emuliatorius",
  /* 419 */ "Negyvoji zona",
  /* 420 */ "Salynas",
  /* 421 */ "Molis",
  /* 422 */ "nė vienas išorinis emuliatorius dar neįrašė savo nustatymų",
  /* 423 */ "Žarijos",
  /* 424 */ "Pelenai",
  /* 425 */ "Vyšnia",
  /* 426 */ "Koralas",
  /* 427 */ "Lentyna",
  /* 428 */ "Miškas",
  /* 429 */ "Šerkšnas",
  /* 430 */ "išoriniai emuliatoriai jau turėjo šiuos mygtukus",
  /* 431 */ "Vidurnaktis",
  /* 432 */ "Samanos",
  /* 433 */ "Neonas",
  /* 434 */ "Slyva",
  /* 435 */ "Smėlis",
  /* 436 */ "Papurtyti",
  /* 437 */ "Sepija",
  /* 438 */ "perkelti mygtukai: {0}",
  /* 439 */ "Turkis",
  /* 440 */ "Lentynų siena: po vieną lentą kiekvienai konsolei, ir dėžutės, storos kaip jų failas.",
  /* 441 */ "Po vieną salą kiekvienai konsolei, žaidimai pasėti aplink, ir kamera, skriejanti viršumi. Žaidimo vieta niekada nesikeičia.",
  /* 442 */ "Virtual Boy",
];
