/**
 * Letton — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * de rang en commentaire sont là pour qu'on puisse le vérifier à l'œil.
 */

export const lv: readonly string[] = [
  /* 1 */ "Ar spēļu pulti",
  /* 2 */ "A palaist · X izlase · Y apgriezt · L1/R1 konsoles · L2/R2 burts · B atpakaļ",
  /* 3 */ "Par EvaChi",
  /* 4 */ "Par programmu…",
  /* 5 */ "Drīzumā: kineskopa filtri, pikseļu režģis, rindu līnijas. Vieta ir gatava, filtri parādīsies šeit.",
  /* 6 */ "Atsvaidzināt bibliotēku",
  /* 7 */ "Skats",
  /* 8 */ "Rādīt spēļu vāku attēlus",
  /* 9 */ "Palīdzība",
  /* 10 */ "Pievienot spēļu mapi…",
  /* 11 */ "Pievienot mapi…",
  /* 12 */ "Nospiediet pogu uz kontroliera: atbilstošā komanda iedegas. Lai kādu mainītu, noklikšķiniet uz lodziņa apakšā un pēc tam nospiediet vēlamo pogu. Poga tad maina saimnieku: divas komandas uz vienas pogas izskatītos pēc bojājuma.",
  /* 13 */ "Argumenti",
  /* 14 */ "Ar tastatūru",
  /* 15 */ "Nav spēļu",
  /* 16 */ "Nav atrasta neviena spēļu pults.",
  /* 17 */ "Bibliotēka",
  /* 18 */ "Izvēles skaņas ar pulti",
  /* 19 */ "Dažas konsoles nesāk darboties bez savas sākotnējās programmaparatūras. EvaChi to nevar iedot: tas ir ar autortiesībām aizsargāts kods, ko pārkopē no savas iekārtas. Toties tā pasaka, kuras trūkst, ar kādu nosaukumu un kur to nolikt.",
  /* 20 */ "Šīm konsolēm nav libretro kodola: to emulators ir atsevišķa programma, ko EvaChi uzstāda pie sevis un palaiž uzreiz spēlē — neejot caur tā izvēlni. Spēles, atslēgas un sistēmas faili paliek jūsu ziņā.",
  /* 21 */ "Šie iestatījumi skar tikai iekšējos kodolus. Ārējam emulatoram ir savējie, un EvaChi tajos neiejaucas.",
  /* 22 */ "Šie vairs netiek piedāvāti: tie neatbildēja uz vaicājumu vai nogāza EvaChi. Atjaunošana tos neuzstāda no jauna — tā vienkārši atgriež tos sarakstā.",
  /* 23 */ "Ielādēt stāvokli…",
  /* 24 */ "Tikai iekšējie kodoli. Noklikšķiniet uz saīsnes un tad nospiediet vēlamo taustiņu vai pogu; ar pulti ņem divas pogas reizē, jo katra no tām jau noder spēlē.",
  /* 25 */ "Vadība",
  /* 26 */ "Vadība…",
  /* 27 */ "Nesenās konsoles",
  /* 28 */ "Pievienot citu emulatoru",
  /* 29 */ "Virzieni / kreisā svira",
  /* 30 */ "Spēļu mapes",
  /* 31 */ "Nolikt šo emulatoru malā",
  /* 32 */ "Tie nāk no libretro projekta sīktēlu servera, pēc pieprasījuma. Ja atzīme noņemta, bibliotēka vairs neko no tīkla neprasa.",
  /* 33 */ "Saglabājumu vietas",
  /* 34 */ "Saglabājumu vietas…",
  /* 35 */ "Emulatori",
  /* 36 */ "Malā noliktie emulatori",
  /* 37 */ "Ārējie emulatori",
  /* 38 */ "Ārējie emulatori…",
  /* 39 */ "Emulatori…",
  /* 40 */ "Emulācija",
  /* 41 */ "Spēles laikā atgriezties bibliotēkā — divas pogas reizē, jo katra no tām noder spēlē",
  /* 42 */ "Saglabāt",
  /* 43 */ "Paplašinājumi",
  /* 44 */ "Aizvērt",
  /* 45 */ "Fails",
  /* 46 */ "Sistēmas faili, kas jāuzstāda pašam",
  /* 47 */ "Galerija",
  /* 48 */ "Pārvaldīt mapes…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Norādiet mapi, kurā atrodas jūsu spēles.",
  /* 52 */ "Uzstādīšana",
  /* 53 */ "Uzstādīt izvēlētos",
  /* 54 */ "Uzstādīt emulatorus…",
  /* 55 */ "Interpretators",
  /* 56 */ "Nav jāzina, kur: parādiet mapi, kurā viss mētājas — BIOS, atslēgas, programmaparatūra, arhīvi, apakšmapes ieskaitot — un EvaChi aiznes katru failu īstajā vietā, gan kodoliem, gan patstāvīgajiem emulatoriem. To, ko neviens neprasa, nepārvieto.",
  /* 57 */ "Vāku attēli",
  /* 58 */ "Žurnāls",
  /* 59 */ "Žurnāls…",
  /* 60 */ "Iepriekšējā reize beidzās slikti",
  /* 61 */ "Palaist spēli, apstiprināt",
  /* 62 */ "Valoda",
  /* 63 */ "Izvēle saglabājas no vienas palaišanas līdz nākamajai. Katrs ir pārbaudīts kā lasāms: tekstam visur ir pietiekams kontrasts pret savu fonu.",
  /* 64 */ "Paturēt to",
  /* 65 */ "Zemāk redzamie emulatori jau ir noregulēti — argumenti un formāti ieskaitot. EvaChi tos meklē jūsu diskā; tā tos neuzstāda.",
  /* 66 */ "Sākotnējās piesaistes",
  /* 67 */ "Gludināšana",
  /* 68 */ "Pievienot spēli favorītiem vai noņemt no tiem",
  /* 69 */ "Animēto izvēlņu mūzika",
  /* 70 */ "Nosaukums",
  /* 71 */ "Atvērt izvēlņu joslu",
  /* 72 */ "Atvērt mapi",
  /* 73 */ "Atvērt mapi…",
  /* 74 */ "Atvērt spēli…",
  /* 75 */ "uz kadru",
  /* 76 */ "Kodola iestatījumi",
  /* 77 */ "Kodola iestatījumi…",
  /* 78 */ "Pārvietoties pa bibliotēku, logiem un izvēlņu joslu",
  /* 79 */ "Pārlūkot…",
  /* 80 */ "Pauze",
  /* 81 */ "Pilnekrāna režīms",
  /* 82 */ "Konsolēm bez libretro kodola. EvaChi palaiž programmu ar spēli kā argumentu: emulators sākas uzreiz spēlē, neejot caur savu izvēlni.",
  /* 83 */ "Uzņemt ekrānuzņēmumu",
  /* 84 */ "Izkārtojums",
  /* 85 */ "Gatavs",
  /* 86 */ "Programma",
  /* 87 */ "Daži ieturēti akordi un retas notis, kas top turpat uz vietas, nevis ir ierakstītas: skaņdarbs nekad neatgriežas tajā pašā vietā. Tas apstājas pats, tiklīdz sākas spēle.",
  /* 88 */ "Sakārtot mapi…",
  /* 89 */ "Iztukšot",
  /* 90 */ "Meklēt spēli…",
  /* 91 */ "Atiestatīt",
  /* 92 */ "Atpakaļ uz bibliotēku",
  /* 93 */ "Atgriezties atpakaļ, aizvērt",
  /* 94 */ "Ātrā saglabāšana",
  /* 95 */ "Saglabāt stāvokli…",
  /* 96 */ "Ēnotāji",
  /* 97 */ "Skaņa",
  /* 98 */ "Start",
  /* 99 */ "Attēla izmērs",
  /* 100 */ "Motīvi",
  /* 101 */ "Motīvi…",
  /* 102 */ "Tikai viens fails…",
  /* 103 */ "Īss klikšķis, mainot spēli, un vēl viens, to palaižot. Tikai ar pulti: ar peli un tastatūru kustība jau tāpat ir jūtama.",
  /* 104 */ "Ātrums",
  /* 105 */ "Skatīt ekrānuzņēmumus…",
  /* 106 */ "Varat uzstādīt tikai daļu no tiem — bibliotēkā parādās vienīgi tās konsoles, kuru emulators ir uzstādīts.",
  /* 107 */ "{0} — ielādēts",
  /* 108 */ "{0} — labais klikšķis dzēš",
  /* 109 */ "{0} — pievienots favorītiem",
  /* 110 */ "{0} — atiestatīts",
  /* 111 */ "{0} — noņemts no favorītiem",
  /* 112 */ "{0} — lejupielāde…",
  /* 113 */ "{0}: neizdevās, skatiet žurnālu",
  /* 114 */ "{0} pieejami",
  /* 115 */ "{0} saglabāts",
  /* 116 */ "{0} ir ārējais emulators: to palaiž, nevis uzņem pie sevis",
  /* 117 */ "{0} k/s",
  /* 118 */ "{0} uzstādīts",
  /* 119 */ "{0} uzstādīts — {1}",
  /* 120 */ "{0} uzstādīts un gatavs",
  /* 121 */ "{0} uzstādīti, {1} neizdevās — skatiet žurnālu",
  /* 122 */ "{0} atjaunots",
  /* 123 */ "{0} noņemts",
  /* 124 */ "{0} no {1}",
  /* 125 */ "{0} diskā, bet neviens uzstādītais kodols tās neatver.",
  /* 126 */ "jāņem no {0}, tad „Pārlūkot…“",
  /* 127 */ "lejupielādējams",
  /* 128 */ "trūkst, nav obligāts",
  /* 129 */ "Ieslēgt",
  /* 130 */ "Mīkstināts",
  /* 131 */ "pievienot neizdevās — {0}",
  /* 132 */ "Pielāgot",
  /* 133 */ "Dzintars",
  /* 134 */ "Slāneklis",
  /* 135 */ "apturēts — {0}",
  /* 136 */ "pēkšņa apstāšanās iepriekšējā reizē — {0}",
  /* 137 */ "neviens",
  /* 138 */ "nav atgriezts neviens kodols, lai gan {0} bija zināmi — paturēts iepriekšējais saraksts",
  /* 139 */ "nav emulatoru",
  /* 140 */ "Nav uzstādīta neviena emulatora",
  /* 141 */ "Neviena spēle nav atpazīta",
  /* 142 */ "Nav rezultātu",
  /* 143 */ "neviena",
  /* 144 */ "bibliotēka nav nolasāma — {0}",
  /* 145 */ "pievienota",
  /* 146 */ "ekrānuzņēmums",
  /* 147 */ "Mainīt vāka attēlu…",
  /* 148 */ "Mainīt…",
  /* 149 */ "Katrs pikselis uz deviņiem",
  /* 150 */ "Katrs pikselis uz četriem: ass, bez izkropļojumiem",
  /* 151 */ "Katrs pikselis uz sešpadsmit — lieliem ekrāniem",
  /* 152 */ "Ielādēt",
  /* 153 */ "Izvēlēties vāka attēlu…",
  /* 154 */ "vispirms izvēlieties spēli bibliotēkā",
  /* 155 */ "kodols: {0}",
  /* 156 */ "kodols nav uzstādīts",
  /* 157 */ "Uzstādītie kodoli",
  /* 158 */ "libretro kodoli",
  /* 159 */ "Augsts kontrasts",
  /* 160 */ "sistēmas čaula: {0}",
  /* 161 */ "atbrīvošana nepabeigta — {0}",
  /* 162 */ "izpēte: {0}",
  /* 163 */ "izpēte pārtraukta — {0}",
  /* 164 */ "Pašam norādīt {0} programmu",
  /* 165 */ "mape pievienota: {0}",
  /* 166 */ "mape atvērta: {0}",
  /* 167 */ "Noklusējuma mape",
  /* 168 */ "Pievienotās mapes",
  /* 169 */ "Esc",
  /* 170 */ "Vieta {0}",
  /* 171 */ "vieta {0} — {1}",
  /* 172 */ "Šai mapei izmantotais emulators",
  /* 173 */ "ārējie emulatori",
  /* 174 */ "notiek",
  /* 175 */ "vietā",
  /* 176 */ "saglabāt neizdevās — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi var tos lejupielādēt no libretro oficiālās darbnīcas. Izvēlieties konsoles, kas jūs interesē.",
  /* 179 */ "EvaChi apstājās, palaižot „{0}“ ar emulatoru {1}.",
  /* 180 */ "EvaChi apstājās, strādājot ar emulatoru {0}.",
  /* 181 */ "external_systems → norādīti {0} emulatori",
  /* 182 */ "Favorīts",
  /* 183 */ "Favorīti",
  /* 184 */ "sistēmas faili nav nolasāmi — {0}",
  /* 185 */ "Bultiņas",
  /* 186 */ "Game Boy",
  /* 187 */ "Režģis",
  /* 188 */ "uzstādītajām konsolēm trūkst {0}",
  /* 189 */ "uzstādīšana pabeigta: {0}",
  /* 190 */ "Uzstādīšana…",
  /* 191 */ "uzstādīts",
  /* 192 */ "uzstādījusi EvaChi",
  /* 193 */ "Uzstādīt",
  /* 194 */ "interpretators: {0}",
  /* 195 */ "uzstādīto kodolu aptauja…",
  /* 196 */ "Palaist",
  /* 197 */ "Palaist izvēlēto spēli",
  /* 198 */ "Lavanda",
  /* 199 */ "Konsoles rindā, spēles kolonnā, viļņojošs fons. Gluži kā istabas konsolē.",
  /* 200 */ "Kontūras ir izpludinātas — tuvāk vecam televizoram",
  /* 201 */ "Lieli vāku attēli, ko pārlūko ar pulti. Domāts dīvānam.",
  /* 202 */ "Pikseļi paliek kvadrātaini, kā uz sākotnējās iekārtas",
  /* 203 */ "pults piesaistes atgrieztas sākotnējās",
  /* 204 */ "list_cores → paziņoti {0} kodoli",
  /* 205 */ "Saraksts",
  /* 206 */ "kodolu saraksts nav pieejams — {0}",
  /* 207 */ "emulatoru saraksts nav pieejams — {0}",
  /* 208 */ "Spēļu pults",
  /* 209 */ "pults: {0}",
  /* 210 */ "Pults: {0}",
  /* 211 */ "pults atvienota",
  /* 212 */ "TRŪKST",
  /* 213 */ "Piparmētra",
  /* 214 */ "Animētā izvēlne",
  /* 215 */ "Atjaunināt",
  /* 216 */ "Pievienot favorītiem",
  /* 217 */ "nolikts malā: {0} · {1}",
  /* 218 */ "mazāk par minūti",
  /* 219 */ "Ass",
  /* 220 */ "vajadzīgs gan nosaukums, gan programma, gan paplašinājumi",
  /* 221 */ "NĒ",
  /* 222 */ "šajā datorā nav uzstādīts",
  /* 223 */ "Rozā nakts",
  /* 224 */ "Okeāns",
  /* 225 */ "vai",
  /* 226 */ "jā",
  /* 227 */ "atvērt neizdevās — {0}",
  /* 228 */ "tīmekļa lapa: pieejami tikai iekšējie kodoli, bez bibliotēkas",
  /* 229 */ "Papīrs",
  /* 230 */ "noklusējums",
  /* 231 */ "Pārvietoties pa režģi un animētajām izvēlnēm",
  /* 232 */ "pilnekrāna režīms atteikts — {0}",
  /* 233 */ "nospiediet vēlamo pogu uz pults",
  /* 234 */ "nospiediet taustiņu…",
  /* 235 */ "sakārtošana: {0} · {1}",
  /* 236 */ "sakārtot neizdevās — {0}",
  /* 237 */ "emulatoru meklēšana pārtraukta — {0}",
  /* 238 */ "Aizvērt logu",
  /* 239 */ "atiestatīt neizdevās — {0}",
  /* 240 */ "Aizpilda logu, saglabājot proporcijas",
  /* 241 */ "Turpināt",
  /* 242 */ "Aizstāt",
  /* 243 */ "Atjaunot",
  /* 244 */ "atjaunot neizdevās — {0}",
  /* 245 */ "Noņemt",
  /* 246 */ "Noņemt no favorītiem",
  /* 247 */ "Noņemt vāka attēlu",
  /* 248 */ "noņemt neizdevās — {0}",
  /* 249 */ "nav ko kārtot",
  /* 250 */ "nekas netraucē",
  /* 251 */ "Nekas neatbilst vaicājumam „{0}“.",
  /* 252 */ "Rozā un balts",
  /* 253 */ "bez attēla",
  /* 254 */ "Saglabāt",
  /* 255 */ "Saglabāt šeit",
  /* 256 */ "izvēlēties neizdevās — {0}",
  /* 257 */ "Konsoles sākotnējais izmērs, līdz pat pikselim",
  /* 258 */ "Izmest",
  /* 259 */ "gaišs motīvs",
  /* 260 */ "tumšs motīvs",
  /* 261 */ "viss ir uzstādīts",
  /* 262 */ "atrasts: {0}",
  /* 263 */ "Katrai konsolei sava sadaļa, tabulā. Visblīvākais skats ar peli.",
  /* 264 */ "tukšs",
  /* 265 */ "jāliek šeit, tāpat kā spēļu romseti: FinalBurn Neo meklē tikai šajā mapē",
  /* 266 */ "pievieno konsoles sākuma ekrānu",
  /* 267 */ "iekārtas sāknētājs",
  /* 268 */ "daudzas spēles sākas arī bez tā; konsoles izvēlne ne",
  /* 269 */ "ASV BIOS",
  /* 270 */ "ASV un Eiropas BIOS",
  /* 271 */ "Eiropas BIOS",
  /* 272 */ "Japānas BIOS",
  /* 273 */ "atšifrēšanas atslēgas; bez tām šifrēta kopija netiek pieņemta",
  /* 274 */ "blueMSX izplatījuma mape Machines, ar Databases blakus",
  /* 275 */ "tāpat",
  /* 276 */ "nepieciešams CD spēlēm, HuCard kartēm ne",
  /* 277 */ "nepieciešams Mega-CD spēlēm, kasetnēm ne",
  /* 278 */ "Kickstart 1.3; citādi PUAE ķeras pie AROS — brīvas, bet mazāk saderīgas",
  /* 279 */ "Kickstart 3.1; vajadzīgs AGA spēlēm, ko A500 nespēj darbināt",
  /* 280 */ "melonDS pēc noklusējuma emulē BIOS; īstais ir precīzāks",
  /* 281 */ "mGBA iztiek bez tā; dažas spēles to prasa savam sākuma ekrānam",
  /* 282 */ "konsoles programmaparatūra",
  /* 283 */ "iekārtas programmaparatūra",
  /* 284 */ "Panasonic FZ-10 programmaparatūra; tieši šo nosaukumu Opera ņem pēc noklusējuma",
  /* 285 */ "melonDS to pārveido, saglabājot oriģinālu kā .bak",
  /* 286 */ "fonti",
  /* 287 */ "konsoles iestatījumi un datums",
  /* 288 */ "bez tā kodols darbojas, bet ekrāns paliek melns",
  /* 289 */ "konsoles rakstzīmju tabula",
  /* 290 */ "amerikāņu variants, ASV Sega CD spēlēm",
  /* 291 */ "japāņu variants, japāņu Mega-CD spēlēm",
  /* 292 */ "ekrānuzņēmumi",
  /* 293 */ "ekrānuzņēmumi",
  /* 294 */ "ekrānuzņēmums",
  /* 295 */ "ekrānuzņēmumi",
  /* 296 */ "ekrānuzņēmumi",
  /* 297 */ "ekrānuzņēmumu",
  /* 298 */ "kodoli",
  /* 299 */ "kodoli",
  /* 300 */ "kodols",
  /* 301 */ "kodoli",
  /* 302 */ "kodoli",
  /* 303 */ "kodolu",
  /* 304 */ "emulatori",
  /* 305 */ "emulatori",
  /* 306 */ "emulators",
  /* 307 */ "emulatori",
  /* 308 */ "emulatori",
  /* 309 */ "emulatoru",
  /* 310 */ "faili",
  /* 311 */ "faili",
  /* 312 */ "fails",
  /* 313 */ "faili",
  /* 314 */ "faili",
  /* 315 */ "failu",
  /* 316 */ "spēles",
  /* 317 */ "spēles",
  /* 318 */ "spēle",
  /* 319 */ "spēles",
  /* 320 */ "spēles",
  /* 321 */ "spēļu",
  /* 322 */ "<code>{rom}</code> tiks aizstāts ar spēles ceļu. Bez tā ceļš tiek pievienots beigās — tieši to gaida lielākā daļa emulatoru.",
  /* 323 */ "<strong>Ārpus spēles viss notiek ar pulti:</strong> virzieni pārvieto pa bibliotēku, logiem un izvēlņu joslu; <strong>A</strong> apstiprina, <strong>B</strong> ved atpakaļ, <strong>Start</strong> atver izvēlņu joslu. Spēles laikā <strong>Select un Start kopā</strong> atgriež bibliotēkā — divas pogas reizē, jo katra no tām noder spēlē.",
  /* 324 */ "Nav neviena ekrānuzņēmuma. Spēles laikā nospiediet <strong>F12</strong> vai uz pults <strong>Select + Y</strong>.",
  /* 325 */ "Katrai konsolei vajag savu emulatoru. EvaChi tos atnes no libretro projekta oficiālās darbnīcas <code>buildbot.libretro.com</code> un uzstāda savā mapē. Nekas netiek izplatīts tālāk: tās ir pašu autoru publicētās versijas.",
  /* 326 */ "Četras vietas katrai spēlei, glabātas diskā. Katra darbība ir uzrakstīta zem vietas, un aizstāšana vai iztukšošana prasa apstiprinājumu. <strong>F2</strong> un <strong>F4</strong> — un <strong>Select + L1</strong> / <strong>Select + R1</strong> uz kontroliera — dodas tieši uz treknrakstā iezīmēto vietu, neko nejautājot.",
  /* 327 */ "Katrs emulators darbojas savā procesā: kad tas nokrīt, EvaChi to pamana un atgriežas bibliotēkā. Iesāktā spēle ir zaudēta, un spēles saglabājums, iespējams, nav ierakstīts. Noliekot šo emulatoru malā, tas paliek uzstādīts, bet vairs netiek piedāvāts. Jebkurā brīdī to varēsiet atjaunot loga apakšā, sadaļā <strong>Fails → Emulatori</strong>.",
  /* 328 */ "Tikai viens fails katrai spēlei diskā <small> CD spēle nāk kā viena <code>.cue</code> lapiņa un tik daudz <code>.bin</code> failu, cik diskam bija celiņu. Palaižas tikai lapiņa: kad tā ir klāt, celiņi ir paslēpti. Bez lapiņas nekas netiek slēpts. </small>",
  /* 329 */ "(tukšs) vai --fullscreen {rom}",
  /* 330 */ "Simts procenti ir pašas konsoles ātrums. Zemāk spēle palēninās, augstāk tā traucas uz priekšu — un skaņa seko līdzi, zemāka vai augstāka. Ar kontrolieri kreisais un labais virziens pārslēdz no vienas pakāpes uz nākamo. Tikai iekšējiem kodoliem: ārējs emulators patur savu ātrumu.",
  /* 331 */ "Piecas konsoles uzreiz",
  /* 332 */ "Virzienu krusts",
  /* 333 */ "No viena sākuma burta uz nākamo",
  /* 334 */ "Animētajās izvēlnēs piecas spēles uzreiz",
  /* 335 */ "Spēles ātrums",
  /* 336 */ "Atcelt",
  /* 337 */ "Velciet rāmi vai pavelciet kādu tā stūri. Bultiņas to pārvieto, bet ar Shift tas palielinās vai samazinās. Kad rāmis iziet ārpus attēla, ap vāku parādās caurspīdīgas joslas: tā pārāk cieši kadrētu vāku var parādīt plašāk. Ar kontrolieri virzienu pogas pārvieto rāmi, bet sprūdi maina tā izmēru.",
  /* 338 */ "Apgriezt",
  /* 339 */ "Apgriezt vāku",
  /* 340 */ "Viss attēls",
  /* 341 */ "{0} — vāks apgriezts",
  /* 342 */ "{0} — nav vāka, ko apgriezt",
  /* 343 */ "vāks nav nolasāms — {0}",
  /* 344 */ "apgriezt neizdevās — {0}",
  /* 345 */ "Apgriezt vāku…",
  /* 346 */ "Ātrā pārtīšana, kamēr abas sviras paliek nospiestas",
  /* 347 */ "{0} nolikts malā",
  /* 348 */ "Emulators {0} apstājās spēles „{1}“ laikā.",
  /* 349 */ "Emulators {0} apstājās.",
  /* 350 */ "Emulators apstājās",
  /* 351 */ "nolikt malā neizdevās — {0}",
  /* 352 */ "jāliek šeit: {0}",
  /* 353 */ "trūkst sistēmas faila: {0}",
  /* 354 */ "Pateicības",
  /* 355 */ "Nekomerciāla licence, ko der zināt pirms šā darba pārņemšanas: {0}.",
  /* 356 */ "EvaChi neraksta nevienu emulatoru: tā tos izmitina. Katrs no tiem ir pilnvērtīgs brīvs projekts, ko sarakstījuši citi un ko EvaChi pēc vajadzības atnes no pašu autoriem — šeit nav pārkopēta neviena viņu koda rindiņa, nav tālāk izplatīts neviens baits. Zemāk redzamie nosaukumi un licences ir tie, ko katrs projekts paziņo pats.",
  /* 357 */ "Karuselis",
  /* 358 */ "Vāki no priekšas, konsoles kaudzē, augšup ceļoši putekļi. Kā izstādes stends.",
  /* 359 */ "Tāpat kā saskarnē",
  /* 360 */ "Saskarnes valoda",
  /* 361 */ "Spēļu valoda",
  /* 362 */ "Spēļu valoda: {0}. Tā stāsies spēkā nākamajā palaišanā.",
  /* 363 */ "Atpakaļ",
  /* 364 */ "Meklēt",
  /* 365 */ "Atrast failus",
  /* 366 */ "Meklēt vērtību",
  /* 367 */ "Atšķirīga",
  /* 368 */ "Tāda pati",
  /* 369 */ "Platums",
  /* 370 */ "Projekts libretro publicē krāpšanās failus — pa vienam katrai spēlei. EvaChi patur tikai tos, kas precīzi atbilst jūsu spēlei — tas pats nosaukums, tas pats reģions, tā pati redakcija — un labāk neiesaka neko, nekā ko tuvu esošu: citai versijai rakstīti kodi neraksta mazliet blakus, tie raksta pavisam citur.",
  /* 371 */ "Krāpšanās",
  /* 372 */ "Mazāk",
  /* 373 */ "Krāpšanās panelis",
  /* 374 */ "Vairāk",
  /* 375 */ "Sākt no jauna",
  /* 376 */ "Krāpšanās",
  /* 377 */ "Krāpšanās…",
  /* 378 */ "Vērtība",
  /* 379 */ "Vienāda ar",
  /* 380 */ "{0} iespējamās adreses",
  /* 381 */ "Ielikti {0} faili, noņemti {1}",
  /* 382 */ "{0} no {1} spēlēm ir fails",
  /* 383 */ "{0} baiti atmiņas",
  /* 384 */ "Atmestas {0} vērtības: ārpus šīs spēles atmiņas",
  /* 385 */ "Šai spēlei faila nav. Emulācijas izvēlnes panelis “Krāpšanās…” to meklē; ja nav, vērtību meklēšana darbojas ar jebkuru spēli.",
  /* 386 */ "Iesaldēta",
  /* 387 */ "Iesaldēt",
  /* 388 */ "Paspēlējiet mazliet un tad sakiet, ko vērtība darīja.",
  /* 389 */ "Spēle tika nolikta malā pirms pirmās krāpšanās.",
  /* 390 */ "Meklē…",
  /* 391 */ "Tas, kas nolikts mapē « drop u'r rom », nonāk pie konsoles, ko norāda tā paplašinājums. Kad vienu un to pašu paplašinājumu dala vairākas konsoles — disku attēli — EvaChi labāk jautā, nekā min.",
  /* 392 */ "Apstiprinājums",
  /* 393 */ "Dzēst spēles saglabājumu…",
  /* 394 */ "Izstiepums",
  /* 395 */ "Spēle glabā savus skaitļus atmiņā, nesakot, kur. Tos atrod, izslēdzot: jūs pasakāt, kas notika ar ekrānā redzamo skaitli, un EvaChi atmet adreses, ar kurām notika citādi.",
  /* 396 */ "Jā",
  /* 397 */ "Retai konsolei ir mūsdienu ekrāna proporcijas, no tā arī melnās joslas sānos. Pie nulles attēls saglabā savas proporcijas; pie simta tas aizpilda logu, kaut arī izstiepjoties.",
  /* 398 */ "Spēļu sakārtošana",
  /* 399 */ "Sakārtot",
  /* 400 */ "Sakārtot noliktās spēles…",
  /* 401 */ "Jūs redzat 47 dzīvības: ierakstiet 47 laukā « Vērtība » un nospiediet « Meklēt ». Zaudējiet vienu, ierakstiet 46 un nospiediet « Vienāda ar ». Ja skaitlis nekur nav rakstīts, atstājiet « Vērtība » tukšu un starp diviem spēles mirkļiem sakiet tikai « Vairāk », « Mazāk », « Atšķirīga » vai « Tāda pati ». Atrasto vērtību pēc tam notur « Iesaldēt ». « Platums » ir skaitļa lielums: 1 līdz 255, 2 virs tā, 4 lielajiem skaitītājiem.",
  /* 402 */ "sakārtotas: {0}",
  /* 403 */ "nav saglabājuma, ko dzēst",
  /* 404 */ "Pogas",
  /* 405 */ "Jau bibliotēkā: {0}",
  /* 406 */ "Dzēst {0} saglabājumu un sākt no gala? Notiekošā spēle tiks apturēta, un tas, ko spēle bija pierakstījusi, tiks zaudēts.",
  /* 407 */ "Mēlītes",
  /* 408 */ "Paturēt abus",
  /* 409 */ "Atstāt mapē",
  /* 410 */ "Mape ir tukša.",
  /* 411 */ "Aizstāt vietu {0}? Tas, kas tur glabāts, tiks zaudēts.",
  /* 412 */ "saglabājums dzēsts — {0}",
  /* 413 */ "Sistēma",
  /* 414 */ "Iztukšot vietu {0}? Tas, kas tur glabāts, tiks zaudēts.",
  /* 415 */ "Nedzīvā zona ir tā kursorsviras daļa, kurā to vēl uzskata par mierā esošu. Pārāk maza — tēls sāk kustēties pats, vadības pultij guļot uz galda; pārāk liela — sīkās kustības pazūd. Dažas spēles prasa sakratīt konsoli: kad pults to sajust neprot, divas zemāk esošās pogas liek spēlei tam noticēt.",
  /* 416 */ "Kursorsvira",
  /* 417 */ "Patstāvīgajiem emulatoriem ir savas pogas, savos failos. Tas, ko te maināt, tiek pārnests uz turieni uzreiz — tiem, kuru formātu pazīstam no pirmavota: PCSX2, PPSSPP un Dolphin. Vecais iestatījums pirmajā reizē tiek nolikts malā, ar to pašu nosaukumu un galotni « .avant-evachi ».",
  /* 418 */ "Pārnest uz ārējiem emulatoriem",
  /* 419 */ "Nedzīvā zona",
  /* 420 */ "Seanss",
  /* 421 */ "Māls",
  /* 422 */ "neviens ārējais emulators vēl nav ierakstījis savus iestatījumus",
  /* 423 */ "Kvēlojošās ogles",
  /* 424 */ "Pelni",
  /* 425 */ "Ķirsis",
  /* 426 */ "Korallis",
  /* 427 */ "Kāršu kava",
  /* 428 */ "Mežs",
  /* 429 */ "Sarma",
  /* 430 */ "ārējiem emulatoriem šīs pogas jau bija",
  /* 431 */ "Pusnakts",
  /* 432 */ "Sūnas",
  /* 433 */ "Neons",
  /* 434 */ "Plūme",
  /* 435 */ "Smiltis",
  /* 436 */ "Sakratīt",
  /* 437 */ "Sēpija",
  /* 438 */ "pārnestās pogas: {0}",
  /* 439 */ "Tirkīzs",
  /* 440 */ "Vāki turēti vēdeklī kā kāršu rokā. Plauksta pagriežas, un lasāmā kārts iztaisnojas.",
  /* 441 */ "Tumša zāle, putekļu pilns stars un liela izmēra projicēta spēle. Pārējās gaida magazīnā.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Aprikoze",
  /* 444 */ "Virsis",
  /* 445 */ "Karamele",
  /* 446 */ "Varš",
  /* 447 */ "Tinte",
  /* 448 */ "Famicom",
  /* 449 */ "Nefrīts",
  /* 450 */ "Mellene",
  /* 451 */ "Negaiss",
  /* 452 */ "Pērle",
  /* 453 */ "Pistācija",
];
