/**
 * Malais — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * marques numérotées sont là pour qu'on puisse le vérifier à l'œil.
 */

export const ms: readonly string[] = [
  /* 1 */ "Pada pad kawalan",
  /* 2 */ "A main · X kegemaran · Y pangkas · L1/R1 konsol · L2/R2 huruf · B kembali",
  /* 3 */ "Tentang EvaChi",
  /* 4 */ "Tentang…",
  /* 5 */ "Apa yang dilakukan televisyen tiub kepada gambar, dan yang dianggap biasa oleh permainan zaman itu. Hanya untuk teras yang dimainkan di sini: emulator berdiri sendiri melukis gambarnya sendiri.",
  /* 6 */ "Segarkan pustaka",
  /* 7 */ "Paparan",
  /* 8 */ "Tunjukkan kulit permainan",
  /* 9 */ "Bantuan",
  /* 10 */ "Tambah folder permainan…",
  /* 11 */ "Tambah folder…",
  /* 12 */ "Tekan satu butang pada pengawal: perintah yang sepadan akan menyala. Untuk menukarnya, klik kotak di bawah lalu tekan butang yang dikehendaki. Butang itu kemudian bertukar tangan: dua perintah pada butang yang sama akan kelihatan seperti kerosakan.",
  /* 13 */ "Argumen",
  /* 14 */ "Pada papan kekunci",
  /* 15 */ "Tiada permainan",
  /* 16 */ "Tiada pad kawalan dikesan.",
  /* 17 */ "Pustaka",
  /* 18 */ "Bunyi pilihan pada pad kawalan",
  /* 19 */ "Sesetengah konsol tidak akan hidup tanpa perisian tegar asalnya. EvaChi tidak boleh membekalkannya: itu kod berhak cipta, yang disalin daripada mesin yang anda miliki sendiri. Sebaliknya, ia memberitahu yang mana hilang, dengan nama apa, dan di mana hendak meletakkannya.",
  /* 20 */ "Konsol ini tiada teras libretro: emulatornya sebuah program berasingan, yang dipasang oleh EvaChi dalam foldernya sendiri dan dilancarkan terus ke dalam permainan — tanpa melalui menunya. Permainan, kunci dan fail sistem tetap menjadi tanggungjawab anda.",
  /* 21 */ "Tetapan ini hanya menyentuh teras dalaman. Emulator luaran ada tetapannya sendiri, dan EvaChi tidak campur tangan.",
  /* 22 */ "Yang berikut tidak lagi ditawarkan: ia tidak menjawab ketika disoal, atau ia menjatuhkan EvaChi. Memulihkannya tidak memasangnya semula — ia cuma dikembalikan ke dalam senarai.",
  /* 23 */ "Muat keadaan…",
  /* 24 */ "Teras dalaman sahaja. Klik satu pintasan kemudian tekan kekunci atau butang yang dikehendaki; pada pad kawalan kita ambil dua butang serentak, kerana setiap satunya sudah pun digunakan oleh permainan.",
  /* 25 */ "Kawalan",
  /* 26 */ "Kawalan…",
  /* 27 */ "Konsol terkini",
  /* 28 */ "Daftar emulator lain",
  /* 29 */ "Arah / stik kiri",
  /* 30 */ "Folder permainan",
  /* 31 */ "Ketepikan emulator ini",
  /* 32 */ "Ia diambil daripada pelayan gambar kecil projek libretro, apabila diperlukan. Jika kotak ini dikosongkan, pustaka tidak lagi meminta apa-apa daripada rangkaian.",
  /* 33 */ "Slot simpanan",
  /* 34 */ "Slot simpanan…",
  /* 35 */ "Emulator",
  /* 36 */ "Emulator yang diketepikan",
  /* 37 */ "Emulator luaran",
  /* 38 */ "Emulator luaran…",
  /* 39 */ "Emulator…",
  /* 40 */ "Emulasi",
  /* 41 */ "Semasa bermain, kembali ke pustaka — dua butang serentak, kerana setiap satunya digunakan oleh permainan",
  /* 42 */ "Simpan",
  /* 43 */ "Sambungan fail",
  /* 44 */ "Tutup",
  /* 45 */ "Fail",
  /* 46 */ "Fail sistem yang perlu dipasang sendiri",
  /* 47 */ "Galeri",
  /* 48 */ "Urus folder…",
  /* 49 */ "Grafik",
  /* 50 */ "Grafik…",
  /* 51 */ "Tunjukkan folder tempat permainan anda berada.",
  /* 52 */ "Pemasangan",
  /* 53 */ "Pasang yang dipilih",
  /* 54 */ "Pasang emulator…",
  /* 55 */ "Pentafsir",
  /* 56 */ "Tidak perlu tahu di mana: tunjukkan folder tempat semuanya bersepah — BIOS, kunci, perisian tegar, arkib, termasuk subfolder — dan EvaChi akan membawa setiap fail ke tempatnya yang betul, untuk teras mahupun emulator berdiri sendiri. Apa yang tiada sesiapa minta tidak akan dialihkan.",
  /* 57 */ "Kulit permainan",
  /* 58 */ "Log",
  /* 59 */ "Log…",
  /* 60 */ "Kali sebelum ini berakhir dengan buruk",
  /* 61 */ "Mulakan permainan, sahkan",
  /* 62 */ "Bahasa",
  /* 63 */ "Pilihan anda dikekalkan dari satu larian ke larian berikutnya. Setiap satu telah disemak agar mudah dibaca: teksnya sentiasa mempunyai kontras yang cukup dengan latarnya.",
  /* 64 */ "Kekalkan",
  /* 65 */ "Emulator di bawah sudah pun disediakan — termasuk argumen dan formatnya. EvaChi mencarinya pada cakera anda; ia tidak memasangnya.",
  /* 66 */ "Ikatan asal",
  /* 67 */ "Pelicinan",
  /* 68 */ "Jadikan permainan ini kegemaran, atau tanggalkannya",
  /* 69 */ "Muzik menu-menu beranimasi",
  /* 70 */ "Nama",
  /* 71 */ "Buka bar menu",
  /* 72 */ "Buka folder",
  /* 73 */ "Buka folder…",
  /* 74 */ "Buka permainan…",
  /* 75 */ "per bingkai",
  /* 76 */ "Tetapan teras",
  /* 77 */ "Tetapan teras…",
  /* 78 */ "Mengemudi pustaka, tetingkap dan bar menu",
  /* 79 */ "Semak imbas…",
  /* 80 */ "Jeda",
  /* 81 */ "Skrin penuh",
  /* 82 */ "Untuk konsol yang tiada teras libretro. EvaChi melancarkan program itu dengan permainan sebagai argumen: emulator terus bermula di dalam permainan, tanpa melalui menunya sendiri.",
  /* 83 */ "Ambil tangkapan skrin",
  /* 84 */ "Susun atur",
  /* 85 */ "Sedia",
  /* 86 */ "Program",
  /* 87 */ "Beberapa kord yang panjang dan not yang bertaburan, digubah sambil berjalan dan bukannya dirakam: lagunya tidak pernah berulang di tempat yang sama. Ia berhenti sendiri sebaik sahaja sesebuah permainan bermula.",
  /* 88 */ "Kemaskan sebuah folder…",
  /* 89 */ "Kosongkan",
  /* 90 */ "Cari permainan…",
  /* 91 */ "Set semula",
  /* 92 */ "Kembali ke pustaka",
  /* 93 */ "Undur, tutup semula",
  /* 94 */ "Simpanan pantas",
  /* 95 */ "Simpan keadaan…",
  /* 96 */ "Shaders",
  /* 97 */ "Bunyi",
  /* 98 */ "Start",
  /* 99 */ "Saiz imej",
  /* 100 */ "Tema",
  /* 101 */ "Tema…",
  /* 102 */ "Satu fail sahaja…",
  /* 103 */ "Satu bunyi tik pendek apabila bertukar permainan, satu lagi apabila melancarkannya. Pada pad kawalan sahaja: dengan tetikus dan papan kekunci, gerakannya sudah terasa.",
  /* 104 */ "Kelajuan",
  /* 105 */ "Lihat tangkapan skrin…",
  /* 106 */ "Anda boleh memasang sebahagian sahaja — hanya konsol yang emulatornya dipasang akan muncul dalam pustaka.",
  /* 107 */ "{0} — dimuatkan",
  /* 108 */ "{0} — klik kanan untuk mengosongkan",
  /* 109 */ "{0} — dijadikan kegemaran",
  /* 110 */ "{0} — diset semula",
  /* 111 */ "{0} — dibuang daripada kegemaran",
  /* 112 */ "{0} — memuat turun…",
  /* 113 */ "{0}: gagal, lihat log",
  /* 114 */ "{0} tersedia",
  /* 115 */ "{0} disimpan",
  /* 116 */ "{0} ialah emulator luaran: ia dilancarkan, bukan dihoskan",
  /* 117 */ "{0} bingkai/s",
  /* 118 */ "{0} dipasang",
  /* 119 */ "{0} dipasang — {1}",
  /* 120 */ "{0} dipasang dan sedia",
  /* 121 */ "{0} dipasang, {1} gagal — lihat log",
  /* 122 */ "{0} dipulihkan",
  /* 123 */ "{0} dibuang",
  /* 124 */ "{0} daripada {1}",
  /* 125 */ "{0} ada pada cakera, tetapi tiada teras yang dipasang dapat membukanya.",
  /* 126 */ "ambil daripada {0}, kemudian “Semak imbas…”",
  /* 127 */ "untuk dimuat turun",
  /* 128 */ "tiada, pilihan",
  /* 129 */ "Aktifkan",
  /* 130 */ "Lembut",
  /* 131 */ "gagal menambah — {0}",
  /* 132 */ "Sesuaikan",
  /* 133 */ "Ambar",
  /* 134 */ "Batu tulis",
  /* 135 */ "berhenti — {0}",
  /* 136 */ "terhenti mengejut kali sebelum ini — {0}",
  /* 137 */ "tiada",
  /* 138 */ "tiada teras dikembalikan sedangkan {0} telah diketahui — senarai sebelumnya dikekalkan",
  /* 139 */ "tiada emulator",
  /* 140 */ "Tiada emulator dipasang",
  /* 141 */ "Tiada permainan dikenali",
  /* 142 */ "Tiada hasil",
  /* 143 */ "tiada",
  /* 144 */ "pustaka tidak dapat dibaca — {0}",
  /* 145 */ "bersambung",
  /* 146 */ "tangkapan skrin",
  /* 147 */ "Tukar kulit…",
  /* 148 */ "Tukar…",
  /* 149 */ "Setiap piksel jadi sembilan",
  /* 150 */ "Setiap piksel jadi empat: tajam, tanpa herotan",
  /* 151 */ "Setiap piksel jadi enam belas — untuk skrin besar",
  /* 152 */ "Muat",
  /* 153 */ "Pilih kulit…",
  /* 154 */ "pilih dahulu sebuah permainan dalam pustaka",
  /* 155 */ "teras: {0}",
  /* 156 */ "teras tidak dipasang",
  /* 157 */ "Teras yang dipasang",
  /* 158 */ "teras libretro",
  /* 159 */ "Kontras tinggi",
  /* 160 */ "cengkerang asli: {0}",
  /* 161 */ "nyahmuat tidak lengkap — {0}",
  /* 162 */ "penemuan: {0}",
  /* 163 */ "penemuan terhenti — {0}",
  /* 164 */ "Tunjuk sendiri program untuk {0}",
  /* 165 */ "folder ditambah: {0}",
  /* 166 */ "folder dibuka: {0}",
  /* 167 */ "Folder lalai",
  /* 168 */ "Folder yang ditambah",
  /* 169 */ "Esc",
  /* 170 */ "Slot {0}",
  /* 171 */ "slot {0} — {1}",
  /* 172 */ "Emulator yang digunakan untuk folder ini",
  /* 173 */ "emulator luaran",
  /* 174 */ "sedang berjalan",
  /* 175 */ "sudah ada",
  /* 176 */ "gagal menyimpan — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi boleh memuat turunnya daripada tapak binaan rasmi libretro. Pilih konsol yang anda minati.",
  /* 179 */ "EvaChi terhenti ketika melancarkan “{0}”, dengan emulator {1}.",
  /* 180 */ "EvaChi terhenti, dengan emulator {0}.",
  /* 181 */ "external_systems → {0} emulator didaftarkan",
  /* 182 */ "Kegemaran",
  /* 183 */ "Kegemaran",
  /* 184 */ "fail sistem tidak dapat dibaca — {0}",
  /* 185 */ "Anak panah",
  /* 186 */ "Game Boy",
  /* 187 */ "Grid",
  /* 188 */ "{0} hilang pada konsol yang dipasang",
  /* 189 */ "pemasangan selesai: {0}",
  /* 190 */ "Memasang…",
  /* 191 */ "dipasang",
  /* 192 */ "dipasang oleh EvaChi",
  /* 193 */ "Pasang",
  /* 194 */ "pentafsir: {0}",
  /* 195 */ "menyoal teras yang dipasang…",
  /* 196 */ "Main",
  /* 197 */ "Mainkan permainan yang dipilih",
  /* 198 */ "Lavender",
  /* 199 */ "Konsol berbaris melintang, permainan menegak, latar yang beralun. Seperti konsol ruang tamu.",
  /* 200 */ "Tepinya melebur — lebih hampir dengan televisyen lama",
  /* 201 */ "Kulit permainan dipaparkan besar, dilayari dengan pad kawalan. Dibuat untuk di sofa.",
  /* 202 */ "Piksel kekal segi empat sama, seperti pada mesin asal",
  /* 203 */ "ikatan pad kawalan dikembalikan kepada asal",
  /* 204 */ "list_cores → {0} teras diumumkan",
  /* 205 */ "Senarai",
  /* 206 */ "senarai teras tidak tersedia — {0}",
  /* 207 */ "senarai emulator tidak tersedia — {0}",
  /* 208 */ "Pad kawalan",
  /* 209 */ "pad kawalan: {0}",
  /* 210 */ "Pad kawalan: {0}",
  /* 211 */ "pad kawalan dicabut",
  /* 212 */ "TIADA",
  /* 213 */ "Pudina",
  /* 214 */ "Menu beranimasi",
  /* 215 */ "Kemas kini",
  /* 216 */ "Jadikan kegemaran",
  /* 217 */ "diketepikan: {0} · {1}",
  /* 218 */ "kurang seminit",
  /* 219 */ "Tajam",
  /* 220 */ "nama, program dan sambungan fail semuanya diperlukan",
  /* 221 */ "TIDAK",
  /* 222 */ "tidak dipasang pada mesin ini",
  /* 223 */ "Malam merah jambu",
  /* 224 */ "Lautan",
  /* 225 */ "atau",
  /* 226 */ "ya",
  /* 227 */ "gagal membuka — {0}",
  /* 228 */ "halaman web: hanya teras dalaman yang tersedia, tanpa pustaka",
  /* 229 */ "Kertas",
  /* 230 */ "lalai",
  /* 231 */ "Mengemudi grid dan menu-menu beranimasi",
  /* 232 */ "skrin penuh ditolak — {0}",
  /* 233 */ "tekan butang yang dikehendaki pada pad kawalan",
  /* 234 */ "tekan sebarang kekunci…",
  /* 235 */ "dikemaskan: {0} · {1}",
  /* 236 */ "gagal mengemas — {0}",
  /* 237 */ "carian emulator terhenti — {0}",
  /* 238 */ "Tutup tetingkap",
  /* 239 */ "gagal set semula — {0}",
  /* 240 */ "Memenuhi tetingkap sambil mengekalkan nisbahnya",
  /* 241 */ "Sambung",
  /* 242 */ "Ganti",
  /* 243 */ "Pulihkan",
  /* 244 */ "gagal memulihkan — {0}",
  /* 245 */ "Buang",
  /* 246 */ "Buang daripada kegemaran",
  /* 247 */ "Buang kulit",
  /* 248 */ "gagal membuang — {0}",
  /* 249 */ "tiada apa untuk dikemaskan",
  /* 250 */ "tiada apa yang menghalang",
  /* 251 */ "Tiada apa-apa yang sepadan dengan “{0}”.",
  /* 252 */ "Merah jambu dan putih",
  /* 253 */ "tiada imej",
  /* 254 */ "Simpan",
  /* 255 */ "Simpan di sini",
  /* 256 */ "gagal memilih — {0}",
  /* 257 */ "Saiz asal konsol, tepat piksel demi piksel",
  /* 258 */ "Buang",
  /* 259 */ "tema cerah",
  /* 260 */ "tema gelap",
  /* 261 */ "semuanya sudah dipasang",
  /* 262 */ "dijumpai: {0}",
  /* 263 */ "Satu panel bagi setiap konsol, dalam jadual. Paling padat untuk tetikus.",
  /* 264 */ "kosong",
  /* 265 */ "letakkan di sini, sama seperti romset permainan: FinalBurn Neo hanya mencari dalam folder ini",
  /* 266 */ "menambah skrin pembuka konsol",
  /* 267 */ "pemuat awal mesin",
  /* 268 */ "banyak permainan boleh hidup tanpanya; menu konsol tidak",
  /* 269 */ "BIOS Amerika",
  /* 270 */ "BIOS Amerika dan Eropah",
  /* 271 */ "BIOS Eropah",
  /* 272 */ "BIOS Jepun",
  /* 273 */ "kunci penyahsulitan; tanpanya salinan tersulit akan ditolak",
  /* 274 */ "folder Machines daripada edaran blueMSX, dengan Databases di sebelahnya",
  /* 275 */ "sama",
  /* 276 */ "wajib untuk permainan CD, tidak perlu untuk kad HuCard",
  /* 277 */ "wajib untuk permainan Mega-CD, tidak perlu untuk kartrij",
  /* 278 */ "Kickstart 1.3; jika tiada, PUAE beralih kepada AROS, bebas tetapi kurang serasi",
  /* 279 */ "Kickstart 3.1; diperlukan untuk permainan AGA, yang tidak mampu dijalankan oleh A500",
  /* 280 */ "melonDS mengemulasi BIOS secara lalai; yang tulen lebih tepat",
  /* 281 */ "mGBA boleh tanpanya; beberapa permainan memerlukannya untuk skrin pembuka",
  /* 282 */ "perisian tegar konsol",
  /* 283 */ "perisian tegar mesin",
  /* 284 */ "perisian tegar Panasonic FZ-10; nama itulah yang diambil Opera secara lalai",
  /* 285 */ "diubah oleh melonDS, yang menyimpan yang asal sebagai .bak",
  /* 286 */ "fon huruf",
  /* 287 */ "tetapan dan tarikh konsol",
  /* 288 */ "tanpanya teras berjalan tetapi skrin kekal hitam",
  /* 289 */ "jadual aksara konsol",
  /* 290 */ "varian Amerika, untuk permainan Sega CD dari Amerika Syarikat",
  /* 291 */ "varian Jepun, untuk permainan Mega-CD Jepun",
  /* 292 */ "tangkapan skrin",
  /* 293 */ "tangkapan skrin",
  /* 294 */ "tangkapan skrin",
  /* 295 */ "tangkapan skrin",
  /* 296 */ "tangkapan skrin",
  /* 297 */ "tangkapan skrin",
  /* 298 */ "teras",
  /* 299 */ "teras",
  /* 300 */ "teras",
  /* 301 */ "teras",
  /* 302 */ "teras",
  /* 303 */ "teras",
  /* 304 */ "emulator",
  /* 305 */ "emulator",
  /* 306 */ "emulator",
  /* 307 */ "emulator",
  /* 308 */ "emulator",
  /* 309 */ "emulator",
  /* 310 */ "fail",
  /* 311 */ "fail",
  /* 312 */ "fail",
  /* 313 */ "fail",
  /* 314 */ "fail",
  /* 315 */ "fail",
  /* 316 */ "permainan",
  /* 317 */ "permainan",
  /* 318 */ "permainan",
  /* 319 */ "permainan",
  /* 320 */ "permainan",
  /* 321 */ "permainan",
  /* 322 */ "<code>{rom}</code> akan digantikan dengan laluan permainan. Tanpanya, laluan itu ditambah di hujung — itulah yang dijangka oleh kebanyakan emulator.",
  /* 323 */ "<strong>Di luar permainan, semuanya dibuat dengan pad kawalan:</strong> arah mengemudi pustaka, tetingkap dan bar menu; <strong>A</strong> mengesahkan, <strong>B</strong> mengundur, <strong>Start</strong> membuka bar menu. Semasa bermain, <strong>Select dan Start serentak</strong> membawa anda kembali ke pustaka — dua butang serentak, kerana setiap satunya digunakan oleh permainan.",
  /* 324 */ "Tiada tangkapan skrin. Tekan <strong>F12</strong> semasa bermain, atau <strong>Select + Y</strong> pada pad kawalan.",
  /* 325 */ "Setiap konsol memerlukan emulatornya sendiri. EvaChi mengambilnya daripada tapak binaan rasmi projek libretro, <code>buildbot.libretro.com</code>, lalu memasangnya dalam foldernya sendiri. Tiada apa-apa yang diedarkan semula: inilah versi yang diterbitkan oleh pembuatnya.",
  /* 326 */ "Empat slot bagi setiap permainan, disimpan pada cakera. Setiap tindakan tertulis di bawah slot, dan menggantikan atau mengosongkan meminta pengesahan. <strong>F2</strong> dan <strong>F4</strong> — serta <strong>Select + L1</strong> / <strong>Select + R1</strong> pada pengawal — terus menuju slot bercetak tebal, tanpa bertanya apa-apa.",
  /* 327 */ "Setiap emulator berjalan dalam prosesnya sendiri: apabila ia jatuh, EvaChi melihatnya dan kembali ke pustaka. Permainan yang sedang dimainkan hilang, dan simpanan permainan mungkin belum sempat ditulis. Mengetepikan emulator ini membiarkannya tetap terpasang, tetapi berhenti menawarkannya. Anda boleh memulihkannya bila-bila masa melalui <strong>Fail → Emulator</strong>, di bahagian bawah tetingkap.",
  /* 328 */ "Satu fail sahaja bagi setiap permainan pada cakera <small> Permainan CD datang sebagai satu helaian <code>.cue</code> dan sebanyak fail <code>.bin</code> seperti bilangan trek pada cakeranya. Hanya helaian itu yang boleh dimainkan: treknya disembunyikan selagi helaian itu ada. Tanpa helaian itu, tiada apa yang disembunyikan. </small>",
  /* 329 */ "(kosong) atau --fullscreen {rom}",
  /* 330 */ "Seratus peratus ialah kelajuan konsol itu sendiri. Di bawah itu permainan jadi perlahan, di atasnya ia meluru — dan bunyi turut berubah, lebih rendah atau lebih tinggi. Pada pengawal permainan, kiri dan kanan berpindah dari satu takat ke takat berikutnya. Teras dalaman sahaja: emulator luaran mengekalkan kelajuannya sendiri.",
  /* 331 */ "Lima konsol serentak",
  /* 332 */ "Pad arah",
  /* 333 */ "Dari satu huruf awal ke huruf seterusnya",
  /* 334 */ "Dalam menu-menu beranimasi, lima permainan serentak",
  /* 335 */ "Kelajuan permainan",
  /* 336 */ "Batal",
  /* 337 */ "Seret bingkai itu, atau tarik salah satu sudutnya. Kekunci anak panah menggerakkannya, dan dengan Shift ia membesar atau mengecil. Apabila bingkai terkeluar daripada gambar, jalur lutsinar ditambah di sekeliling kulit permainan: begitulah caranya memaparkan kulit yang terlalu rapat dengan lebih luas. Pada pengawal permainan, butang arah menggerakkan bingkai dan butang pemicu mengatur saiznya.",
  /* 338 */ "Pangkas",
  /* 339 */ "Pangkas kulit permainan",
  /* 340 */ "Ambil semua",
  /* 341 */ "{0} — kulit dipangkas",
  /* 342 */ "{0} — tiada kulit untuk dipangkas",
  /* 343 */ "kulit tidak terbaca — {0}",
  /* 344 */ "gagal memangkas — {0}",
  /* 345 */ "Pangkas kulit permainan…",
  /* 346 */ "Mara pantas, selagi kedua-dua stik kekal ditekan",
  /* 347 */ "{0} diketepikan",
  /* 348 */ "Emulator {0} terhenti semasa “{1}”.",
  /* 349 */ "Emulator {0} terhenti.",
  /* 350 */ "Emulator terhenti",
  /* 351 */ "gagal mengetepikan — {0}",
  /* 352 */ "letakkan di sini: {0}",
  /* 353 */ "fail sistem hilang: {0}",
  /* 354 */ "Penghargaan",
  /* 355 */ "Lesen bukan komersial, yang perlu diketahui sebelum sesiapa menyambung kerja ini: {0}.",
  /* 356 */ "EvaChi tidak menulis satu pun emulator: ia menempatkannya. Setiap satu ialah projek bebas yang berdiri sendiri, ditulis oleh orang lain, dan yang diambil oleh EvaChi daripada pembuatnya apabila diperlukan — tiada satu baris pun kod mereka disalin ke sini, tiada satu bait pun diedarkan semula. Nama dan lesen di bawah ialah yang diisytiharkan sendiri oleh setiap projek.",
  /* 357 */ "Karusel",
  /* 358 */ "Kulit permainan menghadap depan, konsol bertindan, habuk yang naik. Seperti rak pameran.",
  /* 359 */ "Sama seperti antara muka",
  /* 360 */ "Bahasa antara muka",
  /* 361 */ "Bahasa permainan",
  /* 362 */ "Bahasa permainan: {0}. Ia berkuat kuasa pada pelancaran seterusnya.",
  /* 363 */ "Kembali",
  /* 364 */ "Cari",
  /* 365 */ "Cari failnya",
  /* 366 */ "Cari satu nilai",
  /* 367 */ "Berbeza",
  /* 368 */ "Sama",
  /* 369 */ "Lebar",
  /* 370 */ "Projek libretro menerbitkan fail tipu, satu bagi setiap permainan. EvaChi hanya menyimpan yang benar-benar sepadan dengan permainan anda — tajuk sama, wilayah sama, semakan sama — dan lebih rela tidak menawarkan apa-apa daripada sesuatu yang hampir: kod yang ditulis untuk versi lain bukan menulis sedikit tersasar, tetapi menulis di tempat lain.",
  /* 371 */ "Tipu helah",
  /* 372 */ "Kurang",
  /* 373 */ "Panel tipu",
  /* 374 */ "Lebih",
  /* 375 */ "Mula semula",
  /* 376 */ "Tipu",
  /* 377 */ "Tipu…",
  /* 378 */ "Nilai",
  /* 379 */ "Sama dengan",
  /* 380 */ "{0} alamat yang mungkin",
  /* 381 */ "{0} fail dipasang, {1} ditanggalkan",
  /* 382 */ "{0} daripada {1} permainan mempunyai fail",
  /* 383 */ "{0} bait memori",
  /* 384 */ "{0} nilai diketepikan: di luar memori permainan ini",
  /* 385 */ "Tiada fail untuk permainan ini. Panel « Tipu… » dalam menu Emulasi mencarinya; jika tiada, carian nilai berfungsi pada mana-mana permainan.",
  /* 386 */ "Dibekukan",
  /* 387 */ "Bekukan",
  /* 388 */ "Main sebentar, kemudian beritahu apa yang nilai itu lakukan.",
  /* 389 */ "Permainan disimpan dahulu sebelum tipu yang pertama.",
  /* 390 */ "Sedang mencari…",
  /* 391 */ "Apa yang diletakkan dalam « drop u'r rom » akan pergi ke konsol yang ditunjuk oleh sambungan failnya. Apabila beberapa konsol berkongsi sambungan yang sama — imej cakera — EvaChi bertanya dan bukannya meneka.",
  /* 392 */ "Pengesahan",
  /* 393 */ "Padam simpanan permainan…",
  /* 394 */ "Regangan",
  /* 395 */ "Permainan menyimpan kiraannya dalam ingatan tanpa memberitahu di mana. Ia ditemui dengan menyingkir: anda beritahu apa yang berlaku kepada angka di skrin, dan EvaChi menyingkirkan alamat yang tidak mengalami perkara yang sama.",
  /* 396 */ "Ya",
  /* 397 */ "Sedikit sahaja konsol yang mempunyai nisbah skrin hari ini, dari situlah datangnya jalur hitam di tepi. Pada sifar, imej mengekalkan nisbahnya; pada seratus, ia memenuhi tetingkap walaupun terpaksa meregang.",
  /* 398 */ "Penyusunan permainan",
  /* 399 */ "Susun",
  /* 400 */ "Susun permainan yang diletakkan…",
  /* 401 */ "Anda nampak 47 nyawa: taip 47 dalam « Nilai » lalu tekan « Cari ». Hilangkan satu, taip 46 lalu tekan « Sama dengan ». Jika angka itu tidak tertulis di mana-mana, biarkan « Nilai » kosong dan sebut sahaja « Lebih », « Kurang », « Berbeza » atau « Sama » antara dua saat permainan. Selepas itu « Bekukan » menahan nilai yang ditemui. « Lebar » ialah saiz angka: 1 hingga 255, 2 melebihinya, 4 untuk pembilang besar.",
  /* 402 */ "{0} disusun",
  /* 403 */ "tiada simpanan untuk dipadam",
  /* 404 */ "Butang",
  /* 405 */ "Sudah ada dalam pustaka: {0}",
  /* 406 */ "Padam simpanan {0} dan mula semula dari awal? Permainan yang sedang berjalan akan dihentikan, dan apa yang dicatat oleh permainan akan hilang.",
  /* 407 */ "Picu",
  /* 408 */ "Simpan kedua-duanya",
  /* 409 */ "Biarkan dalam folder",
  /* 410 */ "Folder itu kosong.",
  /* 411 */ "Ganti slot {0}? Apa yang disimpan di situ akan hilang.",
  /* 412 */ "simpanan permainan dipadam — {0}",
  /* 413 */ "Sistem",
  /* 414 */ "Kosongkan slot {0}? Apa yang disimpan di situ akan hilang.",
  /* 415 */ "Zon mati ialah bahagian kayu bedik yang masih dianggap dalam keadaan rehat. Terlalu kecil, watak bergerak sendiri walaupun pengawal terletak di atas meja; terlalu besar, gerakan halus hilang. Sesetengah permainan meminta konsol digoncang: apabila pengawal tidak dapat merasainya, dua butang di bawah membuat permainan mempercayainya.",
  /* 416 */ "Kayu bedik",
  /* 417 */ "Emulator berdiri sendiri mempunyai butangnya sendiri, dalam failnya sendiri. Apa yang anda ubah di sini dibawa ke sana serta-merta, bagi yang formatnya kami kenal secara langsung: PCSX2, PPSSPP dan Dolphin. Tetapan lama diketepikan pada kali pertama, dengan nama yang sama diikuti « .avant-evachi ».",
  /* 418 */ "Bawa ke emulator luaran",
  /* 419 */ "Zon mati",
  /* 420 */ "Tayangan",
  /* 421 */ "Tanah liat",
  /* 422 */ "belum ada emulator luaran yang menulis tetapannya",
  /* 423 */ "Bara",
  /* 424 */ "Abu",
  /* 425 */ "Ceri",
  /* 426 */ "Batu karang",
  /* 427 */ "Sekeping daun terup",
  /* 428 */ "Hutan",
  /* 429 */ "Fros",
  /* 430 */ "emulator luaran sudah mempunyai butang ini",
  /* 431 */ "Tengah malam",
  /* 432 */ "Lumut",
  /* 433 */ "Neon",
  /* 434 */ "Plum",
  /* 435 */ "Pasir",
  /* 436 */ "Goncang",
  /* 437 */ "Sepia",
  /* 438 */ "butang dibawa: {0}",
  /* 439 */ "Firus",
  /* 440 */ "Kulit dipegang seperti kipas, macam sekeping daun terup di tangan. Pergelangan berpusing, dan kad yang dibaca tegak semula.",
  /* 441 */ "Bilik gelap, pancaran penuh habuk, dan permainan ditayang besar. Selebihnya menunggu dalam dulang.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Aprikot",
  /* 444 */ "Heather",
  /* 445 */ "Karamel",
  /* 446 */ "Tembaga",
  /* 447 */ "Dakwat",
  /* 448 */ "Famicom",
  /* 449 */ "Jed",
  /* 450 */ "Beri biru",
  /* 451 */ "Ribut",
  /* 452 */ "Mutiara",
  /* 453 */ "Pistasyo",
  /* 454 */ "Tiada",
  /* 455 */ "Garis imbas",
  /* 456 */ "Setiap piksel jadi tiga celah: merah, hijau dan biru",
  /* 457 */ "Gambar teras, piksel demi piksel",
  /* 458 */ "Kaca cembung, garis, celah dan tepi yang malap",
  /* 459 */ "Kekisi",
  /* 460 */ "Tiub sinar katod",
  /* 461 */ "Satu garis daripada setiap dua digelapkan, seperti pada televisyen",
  /* 462 */ "Membuka emulator dalam tetingkapnya sendiri, tanpa permainan",
  /* 463 */ "Buka",
  /* 464 */ "Kelantangan",
  /* 465 */ "Cakera",
  /* 466 */ "tidak dapat menukar cakera — {0}",
  /* 467 */ "cakera {0}",
];
