/**
 * Norvégien bokmål — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros mis en commentaire devant chaque ligne sont là pour qu'on puisse
 * le vérifier à l'œil.
 */

export const nb: readonly string[] = [
  /* 1 */ "Med kontroller",
  /* 2 */ "A start · X favoritt · Y beskjær · L1/R1 konsoller · L2/R2 bokstav · B tilbake",
  /* 3 */ "Om EvaChi",
  /* 4 */ "Om…",
  /* 5 */ "På vei: filtre for billedrør, pikselrutenett og skannelinjer. Plassen er klar, filtrene lander her.",
  /* 6 */ "Oppdater biblioteket",
  /* 7 */ "Vis",
  /* 8 */ "Vis spillenes omslag",
  /* 9 */ "Hjelp",
  /* 10 */ "Legg til en spillmappe…",
  /* 11 */ "Legg til en mappe…",
  /* 12 */ "Trykk på en knapp på kontrolleren: den tilsvarende tasten lyser opp. Vil du endre en, går du over i tilordning, klikker på tasten du vil endre, og trykker så på knappen du ønsker.",
  /* 13 */ "Argumenter",
  /* 14 */ "På tastaturet",
  /* 15 */ "Ingen spill",
  /* 16 */ "Ingen kontroller funnet.",
  /* 17 */ "Bibliotek",
  /* 18 */ "Valglyd med kontrolleren",
  /* 19 */ "Noen konsoller starter ikke uten den originale fastvaren sin. EvaChi kan ikke levere den: det er opphavsrettsbeskyttet kode, som kopieres fra maskinen man selv eier. Til gjengjeld sier den hvilken som mangler, under hvilket navn, og hvor den skal legges.",
  /* 20 */ "Disse konsollene har ingen libretro-kjerne: emulatoren deres er et eget program, som EvaChi installerer hos seg og starter rett inn i spillet — uten å gå veien om emulatorens egen meny. Spillene, nøklene og systemfilene må du sørge for selv.",
  /* 21 */ "Disse innstillingene gjelder bare de interne kjernene. En ekstern emulator har sine egne, og EvaChi blander seg ikke bort i dem.",
  /* 22 */ "Disse tilbys ikke lenger: de svarte ikke da de ble spurt, eller de fikk EvaChi til å falle. Å gjenopprette dem installerer dem ikke på nytt — det setter dem bare tilbake i listen.",
  /* 23 */ "Last inn tilstand",
  /* 24 */ "Bare interne kjerner. Klikk på en snarvei og trykk så på tasten eller knappen du vil bruke; med kontrolleren tar vi to knapper om gangen, for hver enkelt av dem brukes allerede i spillet.",
  /* 25 */ "Styring",
  /* 26 */ "Styring…",
  /* 27 */ "Nylige konsoller",
  /* 28 */ "Legg til en annen emulator",
  /* 29 */ "Retninger / venstre spak",
  /* 30 */ "Spillmapper",
  /* 31 */ "Sett denne emulatoren til side",
  /* 32 */ "De hentes fra libretro-prosjektets miniatyrbildeserver, etter behov. Uten haken spør ikke biblioteket nettet om noe som helst.",
  /* 33 */ "Lagringsplasser",
  /* 34 */ "Lagringsplasser…",
  /* 35 */ "Emulatorer",
  /* 36 */ "Emulatorer satt til side",
  /* 37 */ "Eksterne emulatorer",
  /* 38 */ "Eksterne emulatorer…",
  /* 39 */ "Emulatorer…",
  /* 40 */ "Emulering",
  /* 41 */ "Under spill, tilbake til biblioteket — to knapper om gangen, for hver enkelt av dem brukes i spillet",
  /* 42 */ "Lagre",
  /* 43 */ "Filendelser",
  /* 44 */ "Lukk",
  /* 45 */ "Fil",
  /* 46 */ "Systemfiler du må installere selv",
  /* 47 */ "Galleri",
  /* 48 */ "Behandle mapper…",
  /* 49 */ "Grafikk",
  /* 50 */ "Grafikk…",
  /* 51 */ "Vis hvor mappen med spillene dine ligger.",
  /* 52 */ "Installasjon",
  /* 53 */ "Installer de valgte",
  /* 54 */ "Installer emulatorer…",
  /* 55 */ "Tolker",
  /* 56 */ "Du trenger ikke vite hvor: vis mappen der alt ligger og slenger — BIOS, nøkler, fastvare, arkiver, undermapper og det hele — så bærer EvaChi hver fil dit den hører hjemme, både for kjernene og for de frittstående emulatorene. Det ingen etterspør, blir liggende.",
  /* 57 */ "Omslag",
  /* 58 */ "Logg",
  /* 59 */ "Logg…",
  /* 60 */ "Forrige gang endte galt",
  /* 61 */ "Start spillet, bekreft",
  /* 62 */ "Språk",
  /* 63 */ "Valget huskes fra en oppstart til den neste. Hvert av dem er sjekket for lesbarhet: teksten holder overalt nok kontrast mot bakgrunnen sin.",
  /* 64 */ "Behold den",
  /* 65 */ "Emulatorene nedenfor er allerede satt opp — argumenter og formater og alt. EvaChi leter etter dem på disken din; den installerer dem ikke.",
  /* 66 */ "Standardoppsett",
  /* 67 */ "Utjevning",
  /* 68 */ "Gjør spillet til favoritt, eller ta det bort igjen",
  /* 69 */ "Musikk i de animerte menyene",
  /* 70 */ "Navn",
  /* 71 */ "Åpne menylinjen",
  /* 72 */ "Åpne mappen",
  /* 73 */ "Åpne mappen…",
  /* 74 */ "Åpne et spill…",
  /* 75 */ "per bilde",
  /* 76 */ "Kjerneinnstillinger",
  /* 77 */ "Kjerneinnstillinger…",
  /* 78 */ "Bla gjennom biblioteket, vinduene og menylinjen",
  /* 79 */ "Bla gjennom…",
  /* 80 */ "Pause",
  /* 81 */ "Fullskjerm",
  /* 82 */ "For konsoller uten libretro-kjerne. EvaChi starter programmet med spillet som argument: emulatoren starter rett inn i spillet, uten å gå veien om sin egen meny.",
  /* 83 */ "Ta et skjermbilde",
  /* 84 */ "Visning",
  /* 85 */ "Klar",
  /* 86 */ "Program",
  /* 87 */ "Noen holdte akkorder og spredte toner, satt sammen underveis heller enn spilt inn: stykket kommer aldri tilbake til samme sted. Det stopper av seg selv så snart et spill starter.",
  /* 88 */ "Rydd en mappe…",
  /* 89 */ "Tilordne på nytt…",
  /* 90 */ "Søk etter et spill…",
  /* 91 */ "Nullstill",
  /* 92 */ "Tilbake til biblioteket",
  /* 93 */ "Gå tilbake, lukk igjen",
  /* 94 */ "Hurtiglagring",
  /* 95 */ "Lagre tilstand",
  /* 96 */ "Shaders",
  /* 97 */ "Lyd",
  /* 98 */ "Start",
  /* 99 */ "Bildestørrelse",
  /* 100 */ "Temaer",
  /* 101 */ "Temaer…",
  /* 102 */ "Én fil per spill…",
  /* 103 */ "Et kort klikk når du bytter spill, og et til når du starter det. Bare med kontrolleren: med mus og tastatur kjenner du bevegelsen allerede.",
  /* 104 */ "Hastighet",
  /* 105 */ "Se skjermbildene…",
  /* 106 */ "Du kan nøye deg med å installere noen av dem — bare konsollene som har emulatoren sin installert, dukker opp i biblioteket.",
  /* 107 */ "{0} — lastet inn",
  /* 108 */ "{0} — høyreklikk for å tømme",
  /* 109 */ "{0} — gjort til favoritt",
  /* 110 */ "{0} — nullstilt",
  /* 111 */ "{0} — tatt bort fra favoritter",
  /* 112 */ "{0} — laster ned…",
  /* 113 */ "{0}: mislyktes, se loggen",
  /* 114 */ "{0} tilgjengelig",
  /* 115 */ "{0} lagret",
  /* 116 */ "{0} er en ekstern emulator: den startes, den huses ikke",
  /* 117 */ "{0} fps",
  /* 118 */ "{0} installert",
  /* 119 */ "{0} installert — {1}",
  /* 120 */ "{0} installert og klar",
  /* 121 */ "{0} installert, {1} mislyktes — se loggen",
  /* 122 */ "{0} gjenopprettet",
  /* 123 */ "{0} fjernet",
  /* 124 */ "{0} av {1}",
  /* 125 */ "{0} på disken, men ingen installert kjerne åpner dem.",
  /* 126 */ "hentes fra {0}, så «Bla gjennom…»",
  /* 127 */ "til nedlasting",
  /* 128 */ "mangler, valgfri",
  /* 129 */ "Slå på",
  /* 130 */ "Myk",
  /* 131 */ "kunne ikke legges til — {0}",
  /* 132 */ "Tilpass",
  /* 133 */ "Rav",
  /* 134 */ "Skifer",
  /* 135 */ "stopp — {0}",
  /* 136 */ "brått stopp forrige gang — {0}",
  /* 137 */ "ingen",
  /* 138 */ "ingen kjerner kom tilbake, enda {0} var kjent — forrige liste beholdt",
  /* 139 */ "ingen emulator",
  /* 140 */ "Ingen emulator installert",
  /* 141 */ "Ingen spill gjenkjent",
  /* 142 */ "Ingen treff",
  /* 143 */ "ingen",
  /* 144 */ "biblioteket kunne ikke leses — {0}",
  /* 145 */ "tilkoblet",
  /* 146 */ "skjermbilde",
  /* 147 */ "Bytt omslag…",
  /* 148 */ "Bytt…",
  /* 149 */ "Hver piksel blir til ni",
  /* 150 */ "Hver piksel blir til fire: skarpt, uten forvrengning",
  /* 151 */ "Hver piksel blir til seksten — for store skjermer",
  /* 152 */ "Last inn",
  /* 153 */ "Velg et omslag…",
  /* 154 */ "velg først et spill i biblioteket",
  /* 155 */ "kjerne: {0}",
  /* 156 */ "kjerne ikke installert",
  /* 157 */ "Installerte kjerner",
  /* 158 */ "libretro-kjerner",
  /* 159 */ "Høy kontrast",
  /* 160 */ "innebygd skall: {0}",
  /* 161 */ "ufullstendig utlasting — {0}",
  /* 162 */ "leting: {0}",
  /* 163 */ "leting avbrutt — {0}",
  /* 164 */ "Peke ut programmet for {0} selv",
  /* 165 */ "mappe lagt til: {0}",
  /* 166 */ "mappe åpnet: {0}",
  /* 167 */ "Standardmappe",
  /* 168 */ "Mapper lagt til",
  /* 169 */ "Esc",
  /* 170 */ "Plass {0}",
  /* 171 */ "plass {0} — {1}",
  /* 172 */ "Emulator brukt for denne mappen",
  /* 173 */ "eksterne emulatorer",
  /* 174 */ "pågår",
  /* 175 */ "på plass",
  /* 176 */ "kunne ikke lagres — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi kan laste dem ned fra libretros offisielle byggeserver. Velg konsollene du er ute etter.",
  /* 179 */ "EvaChi stoppet mens den startet «{0}», med emulatoren {1}.",
  /* 180 */ "EvaChi stoppet, med emulatoren {0}.",
  /* 181 */ "external_systems → {0} emulatorer oppgitt",
  /* 182 */ "Favoritt",
  /* 183 */ "Favoritter",
  /* 184 */ "systemfilene kunne ikke leses — {0}",
  /* 185 */ "Piltaster",
  /* 186 */ "Game Boy",
  /* 187 */ "Rutenett",
  /* 188 */ "det mangler {0} for installerte konsoller",
  /* 189 */ "installasjon ferdig: {0}",
  /* 190 */ "Installerer…",
  /* 191 */ "installert",
  /* 192 */ "installert av EvaChi",
  /* 193 */ "Installer",
  /* 194 */ "tolker: {0}",
  /* 195 */ "spør de installerte kjernene…",
  /* 196 */ "Start",
  /* 197 */ "Start det valgte spillet",
  /* 198 */ "Lavendel",
  /* 199 */ "Konsollene på rad, spillene i kolonne, en bakgrunn som bølger. Som på en stuekonsoll.",
  /* 200 */ "Kantene flyter sammen — nærmere et gammelt fjernsyn",
  /* 201 */ "Omslagene i stort format, blad gjennom med kontrolleren. Tenkt for sofaen.",
  /* 202 */ "Pikslene forblir firkantede, som på den opprinnelige maskinen",
  /* 203 */ "kontrollertilordningene satt tilbake til standard",
  /* 204 */ "list_cores → {0} kjerner meldt",
  /* 205 */ "Liste",
  /* 206 */ "kjernelisten er utilgjengelig — {0}",
  /* 207 */ "emulatorlisten er utilgjengelig — {0}",
  /* 208 */ "Kontroller",
  /* 209 */ "kontroller: {0}",
  /* 210 */ "Kontroller: {0}",
  /* 211 */ "kontrolleren koblet fra",
  /* 212 */ "MANGLER",
  /* 213 */ "Mynte",
  /* 214 */ "Animert meny",
  /* 215 */ "Oppdater",
  /* 216 */ "Gjør til favoritt",
  /* 217 */ "satt til side: {0} · {1}",
  /* 218 */ "mindre enn ett minutt",
  /* 219 */ "Skarp",
  /* 220 */ "navn, program og filendelser må alle fylles ut",
  /* 221 */ "NEI",
  /* 222 */ "ikke installert på denne maskinen",
  /* 223 */ "Rosa natt",
  /* 224 */ "Hav",
  /* 225 */ "eller",
  /* 226 */ "ja",
  /* 227 */ "kunne ikke åpnes — {0}",
  /* 228 */ "nettside: bare de interne kjernene er tilgjengelige, uten bibliotek",
  /* 229 */ "Papir",
  /* 230 */ "standard",
  /* 231 */ "Bla gjennom rutenettet og de animerte menyene",
  /* 232 */ "fullskjerm avvist — {0}",
  /* 233 */ "trykk på knappen du vil bruke, på kontrolleren",
  /* 234 */ "trykk på en tast…",
  /* 235 */ "rydding: {0} · {1}",
  /* 236 */ "kunne ikke ryddes — {0}",
  /* 237 */ "søket etter emulatorer avbrutt — {0}",
  /* 238 */ "Lukke et vindu",
  /* 239 */ "kunne ikke nullstilles — {0}",
  /* 240 */ "Fyller vinduet og beholder proporsjonene",
  /* 241 */ "Fortsett",
  /* 242 */ "Fortsett fra denne lagringen — høyreklikk for å tømme den",
  /* 243 */ "Gjenopprett",
  /* 244 */ "kunne ikke gjenopprettes — {0}",
  /* 245 */ "Fjern",
  /* 246 */ "Ta bort fra favoritter",
  /* 247 */ "Fjern omslaget",
  /* 248 */ "kunne ikke fjernes — {0}",
  /* 249 */ "ingenting å rydde",
  /* 250 */ "ingenting står i veien",
  /* 251 */ "Ingen treff for «{0}».",
  /* 252 */ "Rosa og hvitt",
  /* 253 */ "uten bilde",
  /* 254 */ "Lagre",
  /* 255 */ "Lagre her",
  /* 256 */ "kunne ikke velges — {0}",
  /* 257 */ "Konsollens opprinnelige størrelse, piksel for piksel",
  /* 258 */ "Ferdig",
  /* 259 */ "lyst tema",
  /* 260 */ "mørkt tema",
  /* 261 */ "alt er installert",
  /* 262 */ "funnet: {0}",
  /* 263 */ "Én seksjon per konsoll, i tabell. Det tetteste med mus.",
  /* 264 */ "tom",
  /* 265 */ "legges her, som spillenes romsett: FinalBurn Neo leter bare i denne mappen",
  /* 266 */ "legger til konsollens oppstartsskjerm",
  /* 267 */ "maskinens oppstartskode",
  /* 268 */ "mange spill starter uten; konsollens meny gjør det ikke",
  /* 269 */ "amerikansk BIOS",
  /* 270 */ "amerikansk og europeisk BIOS",
  /* 271 */ "europeisk BIOS",
  /* 272 */ "japansk BIOS",
  /* 273 */ "dekrypteringsnøkler; uten dem blir et kryptert dump avvist",
  /* 274 */ "maskinmappen fra blueMSX-distribusjonen, med Databases ved siden av",
  /* 275 */ "det samme",
  /* 276 */ "nødvendig for CD-spill, unødvendig for HuCard-kort",
  /* 277 */ "nødvendig for Mega-CD-spill, unødvendig for kassetter",
  /* 278 */ "Kickstart 1.3; ellers faller PUAE tilbake på AROS, som er fri, men mindre kompatibel",
  /* 279 */ "Kickstart 3.1; nødvendig for AGA-spill, som A500 ikke klarer å kjøre",
  /* 280 */ "melonDS emulerer BIOS-en som standard; den ekte er mer tro mot originalen",
  /* 281 */ "mGBA klarer seg uten; noen spill krever den for oppstartsskjermen sin",
  /* 282 */ "konsollens fastvare",
  /* 283 */ "maskinens fastvare",
  /* 284 */ "fastvare fra Panasonic FZ-10; det er dette navnet Opera bruker som standard",
  /* 285 */ "endres av melonDS, som tar vare på originalen som .bak",
  /* 286 */ "skrifttyper",
  /* 287 */ "konsollens innstillinger og dato",
  /* 288 */ "uten den går kjernen, men skjermen forblir svart",
  /* 289 */ "konsollens tegntabell",
  /* 290 */ "amerikansk variant, for Sega CD-spill fra USA",
  /* 291 */ "japansk variant, for japanske Mega-CD-spill",
  /* 292 */ "skjermbilder",
  /* 293 */ "skjermbilder",
  /* 294 */ "skjermbilde",
  /* 295 */ "skjermbilder",
  /* 296 */ "skjermbilder",
  /* 297 */ "skjermbilder",
  /* 298 */ "kjerner",
  /* 299 */ "kjerner",
  /* 300 */ "kjerne",
  /* 301 */ "kjerner",
  /* 302 */ "kjerner",
  /* 303 */ "kjerner",
  /* 304 */ "emulatorer",
  /* 305 */ "emulatorer",
  /* 306 */ "emulator",
  /* 307 */ "emulatorer",
  /* 308 */ "emulatorer",
  /* 309 */ "emulatorer",
  /* 310 */ "filer",
  /* 311 */ "filer",
  /* 312 */ "fil",
  /* 313 */ "filer",
  /* 314 */ "filer",
  /* 315 */ "filer",
  /* 316 */ "spill",
  /* 317 */ "spill",
  /* 318 */ "spill",
  /* 319 */ "spill",
  /* 320 */ "spill",
  /* 321 */ "spill",
  /* 322 */ "<code>{rom}</code> blir erstattet av stien til spillet. Uten den legges stien til på slutten — og det er det de fleste emulatorer venter seg.",
  /* 323 */ "<strong>Utenfor spillet gjøres alt med kontrolleren:</strong> retningene fører deg gjennom biblioteket, vinduene og menylinjen; <strong>A</strong> bekrefter, <strong>B</strong> går tilbake, <strong>Start</strong> åpner menylinjen. Under spill fører <strong>Select og Start sammen</strong> deg tilbake til biblioteket — to knapper om gangen, for hver enkelt av dem brukes i spillet.",
  /* 324 */ "Ingen skjermbilder. Trykk <strong>F12</strong> under spill, eller <strong>Select + Y</strong> på kontrolleren.",
  /* 325 */ "Hver konsoll trenger emulatoren sin. EvaChi henter dem fra libretro-prosjektets offisielle byggeserver, <code>buildbot.libretro.com</code>, og installerer dem i sin egen mappe. Ingenting videreformidles: det er utgavene som forfatterne selv har gitt ut.",
  /* 326 */ "Fire plasser per spill, tatt vare på disken. Plassen med fet skrift er den <strong>F2</strong> og <strong>F4</strong> bruker — og <strong>Select + L1</strong> / <strong>Select + R1</strong> på kontrolleren. Høyreklikk på en plass for å tømme den.",
  /* 327 */ "Hver emulator kjører i sin egen prosess: når den faller, ser EvaChi det og går tilbake til biblioteket. Spillet som var i gang, er tapt, og spillets egen lagring er kanskje ikke skrevet. Å sette denne emulatoren til side lar den bli stående installert, men den tilbys ikke lenger. Du kan gjenopprette den når som helst fra <strong>Fil → Emulatorer</strong>, nederst i vinduet.",
  /* 328 */ "Én fil per spill på disken <small> Et spill på CD kommer som ett <code>.cue</code>-ark og like mange <code>.bin</code>-filer som platen hadde spor. Bare arket starter: sporene er skjult så lenge det er der. Uten ark er ingenting skjult. </small>",
  /* 329 */ "(tom) eller --fullscreen {rom}",
  /* 330 */ "Hundre prosent er konsollens egen fart. Under den går spillet saktere, over den suser det av gårde – og lyden følger med, dypere eller lysere. På kontrolleren flytter venstre og høyre deg fra ett trinn til det neste. Bare for interne kjerner: en ekstern emulator holder sin egen fart.",
  /* 331 */ "Fem konsoller om gangen",
  /* 332 */ "Styrekors",
  /* 333 */ "Fra én forbokstav til den neste",
  /* 334 */ "I de animerte menyene, fem spill om gangen",
  /* 335 */ "Spillfart",
  /* 336 */ "Avbryt",
  /* 337 */ "Dra i rammen, eller trekk i et hjørne. Piltastene flytter den, og med Shift blir den større eller mindre. Går den utenfor bildet, legges det til gjennomsiktige striper – slik zoomer du ut et omslag som er for tett beskåret. På håndkontrolleren flytter retningsknappene rammen, og skulderknappene styrer størrelsen.",
  /* 338 */ "Beskjær",
  /* 339 */ "Beskjær omslaget",
  /* 340 */ "Hele bildet",
  /* 341 */ "{0} — omslaget beskåret",
  /* 342 */ "{0} — ikke noe omslag å beskjære",
  /* 343 */ "uleselig omslag — {0}",
  /* 344 */ "kunne ikke beskjære — {0}",
  /* 345 */ "Beskjær omslaget…",
  /* 346 */ "Hurtigspoling, så lenge begge spakene holdes inne",
  /* 347 */ "{0} satt til side",
  /* 348 */ "Emulatoren {0} stoppet under «{1}».",
  /* 349 */ "Emulatoren {0} stoppet.",
  /* 350 */ "Emulatoren stoppet",
  /* 351 */ "kunne ikke settes til side — {0}",
  /* 352 */ "legges her: {0}",
  /* 353 */ "det mangler en systemfil: {0}",
  /* 354 */ "Anerkjennelser",
  /* 355 */ "Ikke-kommersiell lisens, verdt å vite før noen bygger videre på dette arbeidet: {0}.",
  /* 356 */ "EvaChi skriver ingen emulator: den huser dem. Hver eneste er et fritt prosjekt i egen rett, skrevet av andre, og EvaChi henter det hos forfatterne når det trengs — ikke én linje av koden deres er kopiert inn her, ikke én byte videreformidlet. Navnene og lisensene nedenfor er dem hvert prosjekt selv oppgir.",
  /* 357 */ "Karusell",
  /* 358 */ "Omslagene forfra, konsollene i en stabel, støv som stiger. Som en utstilling.",
  /* 359 */ "Som grensesnittet",
  /* 360 */ "Grensesnittets språk",
  /* 361 */ "Spillenes språk",
  /* 362 */ "Spillenes språk: {0}. Det gjelder fra neste start.",
  /* 363 */ "Tilbake",
];
