/**
 * Néerlandais — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * de rang, en commentaire devant chaque ligne, sont là pour qu'on puisse le
 * vérifier à l'œil.
 */

export const nl: readonly string[] = [
  /* 1 */ "Met de controller",
  /* 2 */ "A starten · X favoriet · Y bijsnijden · L1/R1 consoles · L2/R2 letter · B terug",
  /* 3 */ "Over EvaChi",
  /* 4 */ "Over…",
  /* 5 */ "Binnenkort: beeldbuisfilters, rasters, scanlijnen. De plek is klaar, de filters komen hier.",
  /* 6 */ "Bibliotheek verversen",
  /* 7 */ "Weergave",
  /* 8 */ "Covers van de spellen tonen",
  /* 9 */ "Help",
  /* 10 */ "Spelmap toevoegen…",
  /* 11 */ "Map toevoegen…",
  /* 12 */ "Druk op een knop van de controller: de bijbehorende toets licht op. Wil je er een wijzigen, ga dan naar opnieuw toewijzen, klik op de toets en druk daarna op de gewenste knop.",
  /* 13 */ "Argumenten",
  /* 14 */ "Met het toetsenbord",
  /* 15 */ "Geen spellen",
  /* 16 */ "Geen controller gevonden.",
  /* 17 */ "Bibliotheek",
  /* 18 */ "Geluidjes bij kiezen met de controller",
  /* 19 */ "Sommige consoles starten niet zonder hun oorspronkelijke firmware. EvaChi kan die niet meeleveren: het is auteursrechtelijk beschermde code, die je kopieert van het apparaat dat je zelf hebt. Wat EvaChi wel doet: zeggen welk bestand ontbreekt, onder welke naam, en waar je het neerzet.",
  /* 20 */ "Deze consoles hebben geen libretro-core: hun emulator is een apart programma, dat EvaChi bij zich installeert en rechtstreeks in het spel start — zonder langs het eigen menu te gaan. De spellen, de sleutels en de systeembestanden blijven jouw zaak.",
  /* 21 */ "Deze instellingen gelden alleen voor de interne cores. Een externe emulator heeft zijn eigen instellingen, en daar bemoeit EvaChi zich niet mee.",
  /* 22 */ "Deze worden niet meer aangeboden: ze gaven geen antwoord, of ze hebben EvaChi laten vallen. Terugzetten installeert ze niet opnieuw — het zet ze alleen weer in de lijst.",
  /* 23 */ "Staat laden",
  /* 24 */ "Alleen voor de interne cores. Klik op een sneltoets en druk dan op de gewenste toets of knop; op de controller nemen we twee knoppen tegelijk, want elke knop is al voor het spel.",
  /* 25 */ "Besturing",
  /* 26 */ "Besturing…",
  /* 27 */ "Recente consoles",
  /* 28 */ "Een andere emulator opgeven",
  /* 29 */ "Richtingsknoppen / linkerstick",
  /* 30 */ "Spelmappen",
  /* 31 */ "Deze emulator opzijzetten",
  /* 32 */ "Ze komen op aanvraag van de miniaturenserver van het libretro-project. Uitgevinkt vraagt de bibliotheek niets meer aan het netwerk.",
  /* 33 */ "Opslagslots",
  /* 34 */ "Slots…",
  /* 35 */ "Emulators",
  /* 36 */ "Opzijgezette emulators",
  /* 37 */ "Externe emulators",
  /* 38 */ "Externe emulators…",
  /* 39 */ "Emulators…",
  /* 40 */ "Emulatie",
  /* 41 */ "Tijdens het spelen terug naar de bibliotheek — twee knoppen tegelijk, want elke knop is voor het spel",
  /* 42 */ "Opslaan",
  /* 43 */ "Extensies",
  /* 44 */ "Sluiten",
  /* 45 */ "Bestand",
  /* 46 */ "Systeembestanden die je zelf plaatst",
  /* 47 */ "Galerij",
  /* 48 */ "Mappen beheren…",
  /* 49 */ "Beeld",
  /* 50 */ "Beeld…",
  /* 51 */ "Wijs de map aan waar je spellen staan.",
  /* 52 */ "Installatie",
  /* 53 */ "Selectie installeren",
  /* 54 */ "Emulators installeren…",
  /* 55 */ "Interpreter",
  /* 56 */ "Je hoeft niet te weten waar: wijs de map aan waar alles rondslingert — BIOS-bestanden, sleutels, firmware, archieven, submappen inbegrepen — en EvaChi brengt elk bestand naar de juiste plek, voor de cores zowel als voor de zelfstandige emulators. Wat niemand vraagt, blijft liggen.",
  /* 57 */ "Covers",
  /* 58 */ "Logboek",
  /* 59 */ "Logboek…",
  /* 60 */ "De vorige keer liep het mis",
  /* 61 */ "Spel starten, bevestigen",
  /* 62 */ "Taal",
  /* 63 */ "De keuze blijft bewaard van de ene keer op de andere. Elk thema is op leesbaarheid gecontroleerd: de tekst houdt overal genoeg contrast met zijn achtergrond.",
  /* 64 */ "Behouden",
  /* 65 */ "De emulators hieronder zijn al ingesteld — argumenten en formaten inbegrepen. EvaChi zoekt ze op je schijf; installeren doet het ze niet.",
  /* 66 */ "Oorspronkelijke toewijzingen",
  /* 67 */ "Verzachting",
  /* 68 */ "Het spel favoriet maken, of dat ongedaan maken",
  /* 69 */ "Muziek van het animatiemenu",
  /* 70 */ "Naam",
  /* 71 */ "Menubalk openen",
  /* 72 */ "Map openen",
  /* 73 */ "Map openen…",
  /* 74 */ "Spel openen…",
  /* 75 */ "per frame",
  /* 76 */ "Core-instellingen",
  /* 77 */ "Core-instellingen…",
  /* 78 */ "Door de bibliotheek, de vensters en de menubalk bewegen",
  /* 79 */ "Bladeren…",
  /* 80 */ "Pauze",
  /* 81 */ "Volledig scherm",
  /* 82 */ "Voor consoles zonder libretro-core. EvaChi start het programma met het spel als argument: de emulator begint meteen in het spel, zonder langs zijn eigen menu te gaan.",
  /* 83 */ "Schermafbeelding maken",
  /* 84 */ "Indeling",
  /* 85 */ "Klaar",
  /* 86 */ "Programma",
  /* 87 */ "Een paar aangehouden akkoorden en wat losse noten, ter plekke bedacht in plaats van opgenomen: het stuk komt nooit twee keer op dezelfde plek. Zodra een spel start, houdt het vanzelf op.",
  /* 88 */ "Een map opruimen…",
  /* 89 */ "Opnieuw toewijzen…",
  /* 90 */ "Een spel zoeken…",
  /* 91 */ "Resetten",
  /* 92 */ "Terug naar de bibliotheek",
  /* 93 */ "Teruggaan, sluiten",
  /* 94 */ "Snel opslaan",
  /* 95 */ "Staat opslaan",
  /* 96 */ "Shaders",
  /* 97 */ "Geluid",
  /* 98 */ "Start",
  /* 99 */ "Beeldgrootte",
  /* 100 */ "Thema's",
  /* 101 */ "Thema's…",
  /* 102 */ "Eén bestand per spel…",
  /* 103 */ "Een kort tikje bij het wisselen van spel, nog een bij het starten. Alleen op de controller: met muis en toetsenbord voel je de beweging al.",
  /* 104 */ "Snelheid",
  /* 105 */ "Schermafbeeldingen bekijken…",
  /* 106 */ "Je hoeft er maar een deel van te installeren — alleen consoles waarvan de emulator geïnstalleerd is, verschijnen in de bibliotheek.",
  /* 107 */ "{0} — geladen",
  /* 108 */ "{0} — rechtsklik om te wissen",
  /* 109 */ "{0} — favoriet gemaakt",
  /* 110 */ "{0} — gereset",
  /* 111 */ "{0} — uit favorieten gehaald",
  /* 112 */ "{0} — downloaden…",
  /* 113 */ "{0}: mislukt, zie het logboek",
  /* 114 */ "{0} beschikbaar",
  /* 115 */ "{0} opgeslagen",
  /* 116 */ "{0} is een externe emulator: die wordt gestart, niet ondergebracht",
  /* 117 */ "{0} fps",
  /* 118 */ "{0} geïnstalleerd",
  /* 119 */ "{0} geïnstalleerd — {1}",
  /* 120 */ "{0} geïnstalleerd en klaar",
  /* 121 */ "{0} geïnstalleerd, {1} mislukt — zie het logboek",
  /* 122 */ "{0} teruggezet",
  /* 123 */ "{0} verwijderd",
  /* 124 */ "{0} van {1}",
  /* 125 */ "{0} op de schijf, maar geen enkele geïnstalleerde core kan ze openen.",
  /* 126 */ "te halen bij {0}, daarna “Bladeren…”",
  /* 127 */ "te downloaden",
  /* 128 */ "ontbreekt, niet verplicht",
  /* 129 */ "Inschakelen",
  /* 130 */ "Zacht",
  /* 131 */ "toevoegen mislukt — {0}",
  /* 132 */ "Passend",
  /* 133 */ "Amber",
  /* 134 */ "Leisteen",
  /* 135 */ "gestopt — {0}",
  /* 136 */ "vorige keer abrupt gestopt — {0}",
  /* 137 */ "geen",
  /* 138 */ "geen enkele core teruggekregen terwijl er {0} bekend waren — vorige lijst behouden",
  /* 139 */ "geen emulator",
  /* 140 */ "Geen emulator geïnstalleerd",
  /* 141 */ "Geen spel herkend",
  /* 142 */ "Geen resultaten",
  /* 143 */ "geen",
  /* 144 */ "bibliotheek onleesbaar — {0}",
  /* 145 */ "aangesloten",
  /* 146 */ "schermafbeelding",
  /* 147 */ "Cover wijzigen…",
  /* 148 */ "Wijzigen…",
  /* 149 */ "Elke pixel op negen",
  /* 150 */ "Elke pixel op vier: scherp, zonder vervorming",
  /* 151 */ "Elke pixel op zestien — voor grote schermen",
  /* 152 */ "Laden",
  /* 153 */ "Een cover kiezen…",
  /* 154 */ "kies eerst een spel in de bibliotheek",
  /* 155 */ "core: {0}",
  /* 156 */ "core niet geïnstalleerd",
  /* 157 */ "Geïnstalleerde cores",
  /* 158 */ "libretro-cores",
  /* 159 */ "Hoog contrast",
  /* 160 */ "native schil: {0}",
  /* 161 */ "uitladen onvolledig — {0}",
  /* 162 */ "verkenning: {0}",
  /* 163 */ "verkenning afgebroken — {0}",
  /* 164 */ "Zelf het programma van {0} aanwijzen",
  /* 165 */ "map toegevoegd: {0}",
  /* 166 */ "map geopend: {0}",
  /* 167 */ "Standaardmap",
  /* 168 */ "Toegevoegde mappen",
  /* 169 */ "Esc",
  /* 170 */ "Slot {0}",
  /* 171 */ "slot {0} — {1}",
  /* 172 */ "Emulator voor deze map",
  /* 173 */ "externe emulators",
  /* 174 */ "bezig",
  /* 175 */ "aanwezig",
  /* 176 */ "opslaan mislukt — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi kan ze downloaden van de officiële bouwserver van libretro. Kies de consoles die je interesseren.",
  /* 179 */ "EvaChi is gestopt bij het starten van “{0}”, met de emulator {1}.",
  /* 180 */ "EvaChi is gestopt, met de emulator {0}.",
  /* 181 */ "external_systems → {0} emulators opgegeven",
  /* 182 */ "Favoriet",
  /* 183 */ "Favorieten",
  /* 184 */ "systeembestanden onleesbaar — {0}",
  /* 185 */ "Pijltoetsen",
  /* 186 */ "Game Boy",
  /* 187 */ "Raster",
  /* 188 */ "geïnstalleerde consoles missen {0}",
  /* 189 */ "installatie klaar: {0}",
  /* 190 */ "Installeren…",
  /* 191 */ "geïnstalleerd",
  /* 192 */ "door EvaChi geïnstalleerd",
  /* 193 */ "Installeren",
  /* 194 */ "interpreter: {0}",
  /* 195 */ "geïnstalleerde cores bevragen…",
  /* 196 */ "Starten",
  /* 197 */ "Het gekozen spel starten",
  /* 198 */ "Lavendel",
  /* 199 */ "De consoles op een rij, de spellen in een kolom, een achtergrond die golft. Als op een huiskamerconsole.",
  /* 200 */ "De randen vloeien in elkaar — dichter bij een oude televisie",
  /* 201 */ "De covers groot, doorlopen met de controller. Bedacht voor op de bank.",
  /* 202 */ "De pixels blijven vierkant, net als op de oorspronkelijke machine",
  /* 203 */ "controllertoewijzingen terug op standaard",
  /* 204 */ "list_cores → {0} cores aangekondigd",
  /* 205 */ "Lijst",
  /* 206 */ "lijst met cores niet beschikbaar — {0}",
  /* 207 */ "lijst met emulators niet beschikbaar — {0}",
  /* 208 */ "Controller",
  /* 209 */ "controller: {0}",
  /* 210 */ "Controller: {0}",
  /* 211 */ "controller losgekoppeld",
  /* 212 */ "ONTBREEKT",
  /* 213 */ "Munt",
  /* 214 */ "Animatiemenu",
  /* 215 */ "Bijwerken",
  /* 216 */ "Favoriet maken",
  /* 217 */ "opzijgezet: {0} · {1}",
  /* 218 */ "minder dan een minuut",
  /* 219 */ "Scherp",
  /* 220 */ "naam, programma en extensies zijn alle drie nodig",
  /* 221 */ "NEE",
  /* 222 */ "niet geïnstalleerd op deze machine",
  /* 223 */ "Roze nacht",
  /* 224 */ "Oceaan",
  /* 225 */ "of",
  /* 226 */ "ja",
  /* 227 */ "openen mislukt — {0}",
  /* 228 */ "webpagina: alleen de interne cores zijn beschikbaar, zonder bibliotheek",
  /* 229 */ "Papier",
  /* 230 */ "standaard",
  /* 231 */ "Door het raster en het animatiemenu bewegen",
  /* 232 */ "volledig scherm geweigerd — {0}",
  /* 233 */ "druk op de gewenste knop van de controller",
  /* 234 */ "druk op een toets…",
  /* 235 */ "opgeruimd: {0} · {1}",
  /* 236 */ "opruimen mislukt — {0}",
  /* 237 */ "zoeken naar emulators afgebroken — {0}",
  /* 238 */ "Een venster sluiten",
  /* 239 */ "resetten mislukt — {0}",
  /* 240 */ "Vult het venster met behoud van de verhoudingen",
  /* 241 */ "Hervatten",
  /* 242 */ "Deze opslag hervatten — rechtsklik om hem te legen",
  /* 243 */ "Terugzetten",
  /* 244 */ "terugzetten mislukt — {0}",
  /* 245 */ "Verwijderen",
  /* 246 */ "Uit favorieten halen",
  /* 247 */ "Cover verwijderen",
  /* 248 */ "verwijderen mislukt — {0}",
  /* 249 */ "niets op te ruimen",
  /* 250 */ "niets in de weg",
  /* 251 */ "Niets komt overeen met “{0}”.",
  /* 252 */ "Roze en wit",
  /* 253 */ "zonder afbeelding",
  /* 254 */ "Opslaan",
  /* 255 */ "Hier opslaan",
  /* 256 */ "selecteren mislukt — {0}",
  /* 257 */ "De oorspronkelijke grootte van de console, tot op de pixel",
  /* 258 */ "Voltooien",
  /* 259 */ "licht thema",
  /* 260 */ "donker thema",
  /* 261 */ "alles is geïnstalleerd",
  /* 262 */ "gevonden: {0}",
  /* 263 */ "Eén sectie per console, in een tabel. Het dichtst opeen met de muis.",
  /* 264 */ "leeg",
  /* 265 */ "hier neerzetten, net als de romsets van de spellen: FinalBurn Neo kijkt alleen in deze map",
  /* 266 */ "voegt het opstartscherm van de console toe",
  /* 267 */ "opstartcode van de machine",
  /* 268 */ "veel spellen starten er zonder; het menu van de console niet",
  /* 269 */ "Amerikaanse BIOS",
  /* 270 */ "Amerikaanse en Europese BIOS",
  /* 271 */ "Europese BIOS",
  /* 272 */ "Japanse BIOS",
  /* 273 */ "ontsleutelingssleutels; zonder die wordt een versleutelde dump geweigerd",
  /* 274 */ "map met de machines uit de blueMSX-distributie, met Databases ernaast",
  /* 275 */ "idem",
  /* 276 */ "onmisbaar voor cd-spellen, overbodig voor HuCard-kaarten",
  /* 277 */ "onmisbaar voor Mega-CD-spellen, overbodig voor cartridges",
  /* 278 */ "Kickstart 1.3; anders valt PUAE terug op AROS, vrij maar minder compatibel",
  /* 279 */ "Kickstart 3.1; nodig voor AGA-spellen, die de A500 niet kan draaien",
  /* 280 */ "melonDS bootst de BIOS standaard na; de echte is getrouwer",
  /* 281 */ "mGBA kan zonder; een paar spellen eisen hem voor hun opstartscherm",
  /* 282 */ "firmware van de console",
  /* 283 */ "firmware van de machine",
  /* 284 */ "firmware van de Panasonic FZ-10; die naam gebruikt Opera standaard",
  /* 285 */ "wordt door melonDS gewijzigd, dat het origineel als .bak bewaart",
  /* 286 */ "lettertypen",
  /* 287 */ "instellingen en datum van de console",
  /* 288 */ "zonder dit draait de core wel, maar blijft het scherm zwart",
  /* 289 */ "tekentabel van de console",
  /* 290 */ "Amerikaanse variant, voor de Sega CD-spellen uit de Verenigde Staten",
  /* 291 */ "Japanse variant, voor de Japanse Mega-CD-spellen",
  /* 292 */ "schermafbeeldingen",
  /* 293 */ "schermafbeeldingen",
  /* 294 */ "schermafbeelding",
  /* 295 */ "schermafbeeldingen",
  /* 296 */ "schermafbeeldingen",
  /* 297 */ "schermafbeeldingen",
  /* 298 */ "cores",
  /* 299 */ "cores",
  /* 300 */ "core",
  /* 301 */ "cores",
  /* 302 */ "cores",
  /* 303 */ "cores",
  /* 304 */ "emulators",
  /* 305 */ "emulators",
  /* 306 */ "emulator",
  /* 307 */ "emulators",
  /* 308 */ "emulators",
  /* 309 */ "emulators",
  /* 310 */ "bestanden",
  /* 311 */ "bestanden",
  /* 312 */ "bestand",
  /* 313 */ "bestanden",
  /* 314 */ "bestanden",
  /* 315 */ "bestanden",
  /* 316 */ "spellen",
  /* 317 */ "spellen",
  /* 318 */ "spel",
  /* 319 */ "spellen",
  /* 320 */ "spellen",
  /* 321 */ "spellen",
  /* 322 */ "<code>{rom}</code> wordt vervangen door het pad van het spel. Zonder dat wordt het pad achteraan toegevoegd — wat de meeste emulators verwachten.",
  /* 323 */ "<strong>Buiten het spel gaat alles met de controller:</strong> de richtingen lopen door de bibliotheek, de vensters en de menubalk; <strong>A</strong> bevestigt, <strong>B</strong> gaat terug, <strong>Start</strong> opent de menubalk. Tijdens het spelen brengen <strong>Select en Start samen</strong> je terug naar de bibliotheek — twee knoppen tegelijk, want elke knop is voor het spel.",
  /* 324 */ "Nog geen schermafbeeldingen. Druk tijdens het spelen op <strong>F12</strong>, of op <strong>Select + Y</strong> met de controller.",
  /* 325 */ "Elke console heeft zijn eigen emulator nodig. EvaChi haalt die op bij de officiële bouwserver van het libretro-project, <code>buildbot.libretro.com</code>, en installeert ze in haar eigen map. Er wordt niets opnieuw verspreid: het zijn de versies die de makers zelf hebben uitgebracht.",
  /* 326 */ "Vier slots per spel, bewaard op de schijf. Het vetgedrukte slot is het slot dat <strong>F2</strong> en <strong>F4</strong> gebruiken — en <strong>Select + L1</strong> / <strong>Select + R1</strong> op de controller. Rechtsklik op een slot om het te legen.",
  /* 327 */ "Een emulator draait in hetzelfde venster als EvaChi: als hij valt, sleurt hij EvaChi mee, zonder bericht. Deze emulator opzijzetten laat hem geïnstalleerd staan, maar biedt hem niet meer aan. Je kunt hem op elk moment terugzetten via <strong>Bestand → Emulators</strong>, onderaan het venster.",
  /* 328 */ "Eén bestand per spel op de schijf <small> Een spel op cd komt als één <code>.cue</code>-blad en als evenveel <code>.bin</code>-bestanden als de schijf sporen had. Alleen het blad start: de sporen worden verborgen zodra het er is. Zonder blad wordt er niets verborgen. </small>",
  /* 329 */ "(leeg) of --fullscreen {rom}",
  /* 330 */ "Honderd procent is de snelheid van de console zelf. Daaronder gaat het spel langzamer, daarboven vliegt het – en het geluid gaat mee, lager of hoger. Op de controller ga je met links en rechts van de ene stand naar de volgende. Alleen voor interne cores: een externe emulator houdt zijn eigen snelheid.",
  /* 331 */ "Vijf consoles tegelijk",
  /* 332 */ "Richtingskruis",
  /* 333 */ "Van de ene beginletter naar de volgende",
  /* 334 */ "In het geanimeerde menu, vijf spellen tegelijk",
  /* 335 */ "Spelsnelheid",
  /* 336 */ "Annuleren",
  /* 337 */ "Sleep het kader, of trek aan een hoek. Met de pijltjestoetsen verschuif je het, met Shift maak je het groter of kleiner. Valt het buiten de afbeelding, dan komen er doorzichtige randen bij: zo zoom je uit bij een cover die te strak in beeld zit. Op de controller verplaatsen de richtingsknoppen het kader en regelen de triggers de grootte.",
  /* 338 */ "Bijsnijden",
  /* 339 */ "Hoes bijsnijden",
  /* 340 */ "Hele afbeelding",
  /* 341 */ "{0} — hoes bijgesneden",
  /* 342 */ "{0} — geen hoes om bij te snijden",
  /* 343 */ "hoes onleesbaar — {0}",
  /* 344 */ "bijsnijden mislukt — {0}",
  /* 345 */ "Hoes bijsnijden…",
];
