/**
 * Polonais — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros portés en commentaire sont là pour qu'on puisse le vérifier à
 * l'œil, ligne à ligne.
 */

export const pl: readonly string[] = [
  /* 1 */ "Na padzie",
  /* 2 */ "A uruchom · X ulubione · Y przytnij · L1/R1 konsole · L2/R2 litera · B powrót",
  /* 3 */ "O programie EvaChi",
  /* 4 */ "O programie…",
  /* 5 */ "To, co kineskopowy telewizor robił z obrazem i co ówczesne gry brały za pewnik. Dotyczy tylko rdzeni uruchamianych tutaj: samodzielny emulator rysuje swój obraz sam.",
  /* 6 */ "Odśwież bibliotekę",
  /* 7 */ "Widok",
  /* 8 */ "Pokazuj okładki gier",
  /* 9 */ "Pomoc",
  /* 10 */ "Dodaj folder z grami…",
  /* 11 */ "Dodaj folder…",
  /* 12 */ "Naciśnij przycisk na kontrolerze: odpowiadające mu polecenie się zaświeci. Aby zmienić któreś, kliknij pole poniżej, a potem naciśnij wybrany przycisk. Przycisk zmienia wtedy właściciela: dwa polecenia na jednym przycisku wyglądałyby jak usterka.",
  /* 13 */ "Argumenty",
  /* 14 */ "Na klawiaturze",
  /* 15 */ "Brak gier",
  /* 16 */ "Nie wykryto pada.",
  /* 17 */ "Biblioteka",
  /* 18 */ "Dźwięki wyboru na padzie",
  /* 19 */ "Niektóre konsole nie ruszą bez swojego oryginalnego firmware'u. EvaChi nie może go dostarczyć: to kod objęty prawem autorskim, który kopiuje się z własnego sprzętu. Powie za to, którego brakuje, pod jaką nazwą i gdzie go położyć.",
  /* 20 */ "Te konsole nie mają rdzenia libretro: ich emulator to osobny program, który EvaChi instaluje u siebie i uruchamia od razu w grze — z pominięciem jego menu. Gry, klucze i pliki systemowe zostają po twojej stronie.",
  /* 21 */ "Te ustawienia dotyczą tylko rdzeni wewnętrznych. Emulator zewnętrzny ma własne i EvaChi się do nich nie miesza.",
  /* 22 */ "Te nie są już proponowane: nie odpowiedziały na zapytanie albo położyły EvaChi. Przywrócenie nie instaluje ich na nowo — po prostu wracają na listę.",
  /* 23 */ "Wczytaj stan…",
  /* 24 */ "Tylko rdzenie wewnętrzne. Kliknij skrót, a potem naciśnij wybrany klawisz lub przycisk; na padzie bierzemy dwa przyciski naraz, bo każdy z nich służy już grze.",
  /* 25 */ "Sterowanie",
  /* 26 */ "Sterowanie…",
  /* 27 */ "Ostatnie konsole",
  /* 28 */ "Dodaj własny emulator",
  /* 29 */ "Kierunki / lewa gałka",
  /* 30 */ "Foldery z grami",
  /* 31 */ "Odstaw ten emulator",
  /* 32 */ "Przychodzą na żądanie z serwera miniatur projektu libretro. Po odznaczeniu biblioteka nie sięga już do sieci.",
  /* 33 */ "Miejsca zapisu",
  /* 34 */ "Miejsca zapisu…",
  /* 35 */ "Emulatory",
  /* 36 */ "Odstawione emulatory",
  /* 37 */ "Emulatory zewnętrzne",
  /* 38 */ "Emulatory zewnętrzne…",
  /* 39 */ "Emulatory…",
  /* 40 */ "Emulacja",
  /* 41 */ "Powrót do biblioteki w trakcie gry — dwa przyciski naraz, bo każdy z nich służy grze",
  /* 42 */ "Zapisz",
  /* 43 */ "Rozszerzenia",
  /* 44 */ "Zamknij",
  /* 45 */ "Plik",
  /* 46 */ "Pliki systemowe do wgrania samodzielnie",
  /* 47 */ "Galeria",
  /* 48 */ "Zarządzaj folderami…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Wskaż folder, w którym leżą twoje gry.",
  /* 52 */ "Instalacja",
  /* 53 */ "Zainstaluj zaznaczone",
  /* 54 */ "Zainstaluj emulatory…",
  /* 55 */ "Interpreter",
  /* 56 */ "Nie musisz wiedzieć gdzie: pokaż folder, w którym wszystko się poniewiera — BIOS-y, klucze, firmware, archiwa, razem z podfolderami — a EvaChi zaniesie każdy plik na właściwe miejsce, tak dla rdzeni, jak i dla samodzielnych emulatorów. Czego nikt nie szuka, zostaje na miejscu.",
  /* 57 */ "Okładki",
  /* 58 */ "Dziennik",
  /* 59 */ "Dziennik…",
  /* 60 */ "Poprzednim razem skończyło się źle",
  /* 61 */ "Uruchomienie gry, zatwierdzenie",
  /* 62 */ "Język",
  /* 63 */ "Wybór zostaje zapamiętany między uruchomieniami. Każdy sprawdziliśmy pod kątem czytelności: tekst wszędzie zachowuje wystarczający kontrast na swoim tle.",
  /* 64 */ "Zachowaj go",
  /* 65 */ "Poniższe emulatory są już skonfigurowane — razem z argumentami i formatami. EvaChi szuka ich na twoim dysku; nie instaluje ich.",
  /* 66 */ "Domyślne przypisania",
  /* 67 */ "Wygładzanie",
  /* 68 */ "Dodanie gry do ulubionych lub usunięcie jej z nich",
  /* 69 */ "Muzyka menu animowanych",
  /* 70 */ "Nazwa",
  /* 71 */ "Otwarcie paska menu",
  /* 72 */ "Otwórz folder",
  /* 73 */ "Otwórz folder…",
  /* 74 */ "Otwórz grę…",
  /* 75 */ "na klatkę",
  /* 76 */ "Ustawienia rdzenia",
  /* 77 */ "Ustawienia rdzenia…",
  /* 78 */ "Poruszanie się po bibliotece, oknach i pasku menu",
  /* 79 */ "Przeglądaj…",
  /* 80 */ "Pauza",
  /* 81 */ "Pełny ekran",
  /* 82 */ "Dla konsol bez rdzenia libretro. EvaChi uruchamia program z grą jako argumentem: emulator startuje od razu w grze, z pominięciem własnego menu.",
  /* 83 */ "Zrób zrzut ekranu",
  /* 84 */ "Układ",
  /* 85 */ "Gotowe",
  /* 86 */ "Program",
  /* 87 */ "Kilka przeciągniętych akordów i rozsiane dźwięki, układane na bieżąco, a nie nagrane: utwór nigdy nie wraca w to samo miejsce. Milknie sam, gdy tylko ruszy gra.",
  /* 88 */ "Uporządkuj folder…",
  /* 89 */ "Opróżnij",
  /* 90 */ "Szukaj gry…",
  /* 91 */ "Zresetuj",
  /* 92 */ "Powrót do biblioteki",
  /* 93 */ "Cofnięcie, zamknięcie",
  /* 94 */ "Szybki zapis",
  /* 95 */ "Zapisz stan…",
  /* 96 */ "Shadery",
  /* 97 */ "Dźwięk",
  /* 98 */ "Start",
  /* 99 */ "Rozmiar obrazu",
  /* 100 */ "Motywy",
  /* 101 */ "Motywy…",
  /* 102 */ "Jeden plik na grę…",
  /* 103 */ "Krótkie stuknięcie przy zmianie gry, drugie przy jej uruchomieniu. Tylko na padzie: przy myszy i klawiaturze gest czuć i tak.",
  /* 104 */ "Prędkość",
  /* 105 */ "Zobacz zrzuty…",
  /* 106 */ "Możesz zainstalować tylko część — w bibliotece pojawiają się wyłącznie konsole, których emulator jest zainstalowany.",
  /* 107 */ "{0} — wczytano",
  /* 108 */ "{0} — prawym przyciskiem wyczyścisz",
  /* 109 */ "{0} — dodano do ulubionych",
  /* 110 */ "{0} — przywrócono domyślne",
  /* 111 */ "{0} — usunięto z ulubionych",
  /* 112 */ "{0} — pobieranie…",
  /* 113 */ "{0}: nie udało się, zajrzyj do dziennika",
  /* 114 */ "{0} do dyspozycji",
  /* 115 */ "{0} zapisano",
  /* 116 */ "{0} to emulator zewnętrzny: uruchamia się osobno, w środku nie działa",
  /* 117 */ "{0} kl./s",
  /* 118 */ "{0} zainstalowano",
  /* 119 */ "{0} zainstalowano — {1}",
  /* 120 */ "{0} zainstalowano, wszystko gotowe",
  /* 121 */ "{0} zainstalowano, {1} bez powodzenia — zajrzyj do dziennika",
  /* 122 */ "{0} przywrócono",
  /* 123 */ "{0} usunięto",
  /* 124 */ "{0} z {1}",
  /* 125 */ "{0} na dysku, ale żaden zainstalowany rdzeń tego nie otworzy.",
  /* 126 */ "do wzięcia z {0}, potem „Przeglądaj…”",
  /* 127 */ "do pobrania",
  /* 128 */ "brak, opcjonalny",
  /* 129 */ "Włącz",
  /* 130 */ "Miękki",
  /* 131 */ "nie udało się dodać — {0}",
  /* 132 */ "Dopasuj",
  /* 133 */ "Bursztyn",
  /* 134 */ "Łupek",
  /* 135 */ "zatrzymano — {0}",
  /* 136 */ "poprzednio nagłe zatrzymanie — {0}",
  /* 137 */ "brak",
  /* 138 */ "żaden rdzeń nie wrócił, choć znanych było {0} — zachowano poprzednią listę",
  /* 139 */ "brak emulatorów",
  /* 140 */ "Nie zainstalowano żadnego emulatora",
  /* 141 */ "Nie rozpoznano żadnej gry",
  /* 142 */ "Brak wyników",
  /* 143 */ "brak",
  /* 144 */ "biblioteki nie da się odczytać — {0}",
  /* 145 */ "podłączony",
  /* 146 */ "zrzut",
  /* 147 */ "Zmień okładkę…",
  /* 148 */ "Zmień…",
  /* 149 */ "Każdy piksel na dziewięć",
  /* 150 */ "Każdy piksel na cztery: ostro, bez zniekształceń",
  /* 151 */ "Każdy piksel na szesnaście — na duże ekrany",
  /* 152 */ "Wczytaj",
  /* 153 */ "Wybierz okładkę…",
  /* 154 */ "najpierw wybierz grę w bibliotece",
  /* 155 */ "rdzeń: {0}",
  /* 156 */ "rdzeń niezainstalowany",
  /* 157 */ "Zainstalowane rdzenie",
  /* 158 */ "rdzenie libretro",
  /* 159 */ "Wysoki kontrast",
  /* 160 */ "powłoka natywna: {0}",
  /* 161 */ "niepełne zwolnienie rdzenia — {0}",
  /* 162 */ "wykryto: {0}",
  /* 163 */ "wykrywanie przerwane — {0}",
  /* 164 */ "Wskaż samodzielnie program dla {0}",
  /* 165 */ "dodano folder: {0}",
  /* 166 */ "otwarto folder: {0}",
  /* 167 */ "Folder domyślny",
  /* 168 */ "Dodane foldery",
  /* 169 */ "Esc",
  /* 170 */ "Miejsce {0}",
  /* 171 */ "miejsce {0} — {1}",
  /* 172 */ "Emulator używany dla tego folderu",
  /* 173 */ "emulatory zewnętrzne",
  /* 174 */ "w toku",
  /* 175 */ "na miejscu",
  /* 176 */ "nie udało się zapisać — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi może je pobrać z oficjalnej kuźni libretro. Wybierz konsole, które cię interesują.",
  /* 179 */ "EvaChi zamknęła się nagle przy uruchamianiu „{0}”, z emulatorem {1}.",
  /* 180 */ "EvaChi zamknęła się nagle, z emulatorem {0}.",
  /* 181 */ "external_systems → zgłoszonych emulatorów: {0}",
  /* 182 */ "Ulubiona",
  /* 183 */ "Ulubione",
  /* 184 */ "plików systemowych nie da się odczytać — {0}",
  /* 185 */ "Strzałki",
  /* 186 */ "Game Boy",
  /* 187 */ "Siatka",
  /* 188 */ "zainstalowanym konsolom brakuje: {0}",
  /* 189 */ "instalacja zakończona: {0}",
  /* 190 */ "Instalowanie…",
  /* 191 */ "zainstalowany",
  /* 192 */ "zainstalowany przez EvaChi",
  /* 193 */ "Zainstaluj",
  /* 194 */ "interpreter: {0}",
  /* 195 */ "odpytywanie zainstalowanych rdzeni…",
  /* 196 */ "Uruchom",
  /* 197 */ "Uruchom wybraną grę",
  /* 198 */ "Lawenda",
  /* 199 */ "Konsole w rzędzie, gry w kolumnie, falujące tło. Jak na konsoli pod telewizorem.",
  /* 200 */ "Kontury są rozmyte — bliżej starego telewizora",
  /* 201 */ "Duże okładki, przeglądane padem. Pomyślane pod kanapę.",
  /* 202 */ "Piksele zostają kwadratowe, jak na oryginalnym sprzęcie",
  /* 203 */ "przypisania pada przywrócone do domyślnych",
  /* 204 */ "list_cores → zapowiedzianych rdzeni: {0}",
  /* 205 */ "Lista",
  /* 206 */ "lista rdzeni niedostępna — {0}",
  /* 207 */ "lista emulatorów niedostępna — {0}",
  /* 208 */ "Pad",
  /* 209 */ "pad: {0}",
  /* 210 */ "Pad: {0}",
  /* 211 */ "pad odłączony",
  /* 212 */ "BRAK",
  /* 213 */ "Mięta",
  /* 214 */ "Menu animowane",
  /* 215 */ "Zaktualizuj",
  /* 216 */ "Dodaj do ulubionych",
  /* 217 */ "odstawiono: {0} · {1}",
  /* 218 */ "mniej niż minuta",
  /* 219 */ "Ostry",
  /* 220 */ "nazwa, program i rozszerzenia — wszystkie są potrzebne",
  /* 221 */ "NIE",
  /* 222 */ "nie ma go na tym komputerze",
  /* 223 */ "Różowa noc",
  /* 224 */ "Ocean",
  /* 225 */ "lub",
  /* 226 */ "tak",
  /* 227 */ "nie udało się otworzyć — {0}",
  /* 228 */ "strona internetowa: dostępne są tylko rdzenie wewnętrzne, bez biblioteki",
  /* 229 */ "Papier",
  /* 230 */ "domyślnie",
  /* 231 */ "Poruszanie się po siatce i menu animowanych",
  /* 232 */ "pełny ekran odrzucony — {0}",
  /* 233 */ "naciśnij wybrany przycisk na padzie",
  /* 234 */ "naciśnij klawisz…",
  /* 235 */ "uporządkowano: {0} · {1}",
  /* 236 */ "nie udało się uporządkować — {0}",
  /* 237 */ "szukanie emulatorów przerwane — {0}",
  /* 238 */ "Zamknięcie okna",
  /* 239 */ "nie udało się zresetować — {0}",
  /* 240 */ "Wypełnia okno z zachowaniem proporcji",
  /* 241 */ "Wznów",
  /* 242 */ "Zastąp",
  /* 243 */ "Przywróć",
  /* 244 */ "nie udało się przywrócić — {0}",
  /* 245 */ "Usuń",
  /* 246 */ "Usuń z ulubionych",
  /* 247 */ "Usuń okładkę",
  /* 248 */ "nie udało się usunąć — {0}",
  /* 249 */ "nie ma czego porządkować",
  /* 250 */ "nic nie blokuje",
  /* 251 */ "Nic nie pasuje do „{0}”.",
  /* 252 */ "Róż i biel",
  /* 253 */ "bez obrazka",
  /* 254 */ "Zapisz",
  /* 255 */ "Zapisz tutaj",
  /* 256 */ "nie udało się wybrać — {0}",
  /* 257 */ "Oryginalny rozmiar konsoli, co do piksela",
  /* 258 */ "Wyrzuć",
  /* 259 */ "motyw jasny",
  /* 260 */ "motyw ciemny",
  /* 261 */ "wszystko zainstalowane",
  /* 262 */ "znaleziono: {0}",
  /* 263 */ "Jeden panel na konsolę, w tabeli. Najgęściej przy myszy.",
  /* 264 */ "puste",
  /* 265 */ "połóż tutaj, tak jak romsety gier: FinalBurn Neo szuka tylko w tym folderze",
  /* 266 */ "dodaje ekran powitalny konsoli",
  /* 267 */ "program rozruchowy maszyny",
  /* 268 */ "wiele gier ruszy bez niego; menu konsoli już nie",
  /* 269 */ "BIOS amerykański",
  /* 270 */ "BIOS amerykański i europejski",
  /* 271 */ "BIOS europejski",
  /* 272 */ "BIOS japoński",
  /* 273 */ "klucze deszyfrujące; bez nich zaszyfrowany zrzut zostanie odrzucony",
  /* 274 */ "folder maszyn z dystrybucji blueMSX, z Databases obok",
  /* 275 */ "to samo",
  /* 276 */ "niezbędny do gier CD, zbędny przy kartach HuCard",
  /* 277 */ "niezbędny do gier Mega-CD, zbędny przy kartridżach",
  /* 278 */ "Kickstart 1.3; bez niego PUAE sięga po AROS, wolny, ale mniej zgodny",
  /* 279 */ "Kickstart 3.1; potrzebny do gier AGA, których A500 nie umie uruchomić",
  /* 280 */ "melonDS domyślnie emuluje BIOS; prawdziwy jest wierniejszy",
  /* 281 */ "mGBA obywa się bez niego; kilka gier wymaga go do ekranu powitalnego",
  /* 282 */ "firmware konsoli",
  /* 283 */ "firmware maszyny",
  /* 284 */ "firmware Panasonic FZ-10; tę nazwę Opera przyjmuje domyślnie",
  /* 285 */ "zmieniany przez melonDS, który zachowuje oryginał jako .bak",
  /* 286 */ "czcionki",
  /* 287 */ "ustawienia i data konsoli",
  /* 288 */ "bez niego rdzeń działa, ale ekran zostaje czarny",
  /* 289 */ "tablica znaków konsoli",
  /* 290 */ "wersja amerykańska, do gier Sega CD ze Stanów",
  /* 291 */ "wersja japońska, do japońskich gier Mega-CD",
  /* 292 */ "zrzuty",
  /* 293 */ "zrzutów",
  /* 294 */ "zrzut",
  /* 295 */ "zrzutu",
  /* 296 */ "zrzuty",
  /* 297 */ "zrzutów",
  /* 298 */ "rdzenie",
  /* 299 */ "rdzeni",
  /* 300 */ "rdzeń",
  /* 301 */ "rdzenia",
  /* 302 */ "rdzenie",
  /* 303 */ "rdzeni",
  /* 304 */ "emulatory",
  /* 305 */ "emulatorów",
  /* 306 */ "emulator",
  /* 307 */ "emulatora",
  /* 308 */ "emulatory",
  /* 309 */ "emulatorów",
  /* 310 */ "pliki",
  /* 311 */ "plików",
  /* 312 */ "plik",
  /* 313 */ "pliku",
  /* 314 */ "pliki",
  /* 315 */ "plików",
  /* 316 */ "gry",
  /* 317 */ "gier",
  /* 318 */ "gra",
  /* 319 */ "gry",
  /* 320 */ "gry",
  /* 321 */ "gier",
  /* 322 */ "<code>{rom}</code> zostanie zastąpione ścieżką gry. Bez niego ścieżka trafia na koniec — a tego właśnie oczekuje większość emulatorów.",
  /* 323 */ "<strong>Poza grą wszystko robi się padem:</strong> kierunki prowadzą po bibliotece, oknach i pasku menu; <strong>A</strong> zatwierdza, <strong>B</strong> cofa, <strong>Start</strong> otwiera pasek menu. W trakcie gry <strong>Select i Start naraz</strong> wracają do biblioteki — dwa przyciski jednocześnie, bo każdy z nich służy grze.",
  /* 324 */ "Brak zrzutów. Naciśnij <strong>F12</strong> w trakcie gry albo <strong>Select + Y</strong> na padzie.",
  /* 325 */ "Każda konsola potrzebuje swojego emulatora. EvaChi pobiera je z oficjalnej kuźni projektu libretro, <code>buildbot.libretro.com</code>, i instaluje we własnym folderze. Nic nie jest rozpowszechniane dalej: to wersje wydane przez ich autorów.",
  /* 326 */ "Cztery miejsca na grę, przechowywane na dysku. Każda czynność jest wypisana pod miejscem, a zastąpienie lub opróżnienie prosi o potwierdzenie. <strong>F2</strong> i <strong>F4</strong> — oraz <strong>Select + L1</strong> / <strong>Select + R1</strong> na kontrolerze — idą prosto do miejsca wyróżnionego pogrubieniem, o nic nie pytając.",
  /* 327 */ "Każdy emulator działa we własnym procesie: kiedy pada, EvaChi to widzi i wraca do biblioteki. Trwająca rozgrywka przepada, a zapis gry mógł nie trafić na dysk. Po odstawieniu zostaje zainstalowany, przestaje się tylko pojawiać w wyborze. Możesz go przywrócić w każdej chwili przez <strong>Plik → Emulatory</strong>, na dole okna.",
  /* 328 */ "Jeden plik na grę na dysku <small> Gra z płyty przychodzi jako arkusz <code>.cue</code> i tyle plików <code>.bin</code>, ile ścieżek miała płyta. Uruchamia się tylko arkusz: przy nim ścieżki są ukryte. Bez arkusza nic nie jest ukryte. </small>",
  /* 329 */ "(puste) lub --fullscreen {rom}",
  /* 330 */ "Sto procent to prędkość samej konsoli. Niżej gra zwalnia, wyżej pędzi — a dźwięk idzie za nią, niżej albo wyżej. Na padzie lewo i prawo przeskakują z jednego stopnia na następny. Tylko rdzenie wewnętrzne: zewnętrzny emulator trzyma się własnej prędkości.",
  /* 331 */ "Pięć konsol naraz",
  /* 332 */ "Krzyżak kierunkowy",
  /* 333 */ "Od jednej litery do następnej",
  /* 334 */ "W animowanych menu pięć gier naraz",
  /* 335 */ "Prędkość gry",
  /* 336 */ "Anuluj",
  /* 337 */ "Przeciągnij ramkę albo pociągnij za róg. Strzałki ją przesuwają, a ze Shiftem powiększają lub zmniejszają. Gdy ramka wyjdzie poza obraz, dokładają się przezroczyste pasy: tak właśnie oddalisz zbyt ciasną okładkę. Na padzie kierunki przesuwają ramkę, a spusty ustawiają jej rozmiar.",
  /* 338 */ "Przytnij",
  /* 339 */ "Przytnij okładkę",
  /* 340 */ "Cały obraz",
  /* 341 */ "{0} — okładka przycięta",
  /* 342 */ "{0} — brak okładki do przycięcia",
  /* 343 */ "okładka nie do odczytu — {0}",
  /* 344 */ "nie udało się przyciąć — {0}",
  /* 345 */ "Przytnij okładkę…",
  /* 346 */ "Szybkie przewijanie, dopóki obie gałki pozostają wciśnięte",
  /* 347 */ "{0} odstawiono",
  /* 348 */ "Emulator {0} zatrzymał się w trakcie „{1}”.",
  /* 349 */ "Emulator {0} zatrzymał się.",
  /* 350 */ "Emulator się zatrzymał",
  /* 351 */ "nie udało się odstawić — {0}",
  /* 352 */ "połóż tutaj: {0}",
  /* 353 */ "brakuje pliku systemowego: {0}",
  /* 354 */ "Podziękowania",
  /* 355 */ "Licencja niekomercyjna, o czym warto wiedzieć przed przejęciem tego projektu: {0}.",
  /* 356 */ "EvaChi nie pisze żadnego emulatora: gości je u siebie. Każdy z nich to pełnoprawny wolny projekt, napisany przez kogoś innego, po który EvaChi sięga do jego autorów na żądanie — ani jedna linijka ich kodu nie jest tu przepisana, ani jeden bajt nie jest rozpowszechniany dalej. Nazwy i licencje poniżej to te, które każdy projekt podaje sam.",
  /* 357 */ "Karuzela",
  /* 358 */ "Okładki od frontu, konsole w stosie, unoszący się kurz. Niczym witryna.",
  /* 359 */ "Jak interfejs",
  /* 360 */ "Język interfejsu",
  /* 361 */ "Język gier",
  /* 362 */ "Język gier: {0}. Zadziała od następnego uruchomienia.",
  /* 363 */ "Wstecz",
  /* 364 */ "Szukaj",
  /* 365 */ "Znajdź pliki",
  /* 366 */ "Szukaj wartości",
  /* 367 */ "Inna",
  /* 368 */ "Taka sama",
  /* 369 */ "Szerokość",
  /* 370 */ "Projekt libretro publikuje pliki z kodami, po jednym na grę. EvaChi zachowuje tylko te, które pasują dokładnie do twojej gry — ten sam tytuł, ten sam region, ta sama wersja — i woli nie zaproponować niczego niż coś przybliżonego: kody napisane dla innego wydania nie zapisują odrobinę obok, tylko zupełnie gdzie indziej.",
  /* 371 */ "Kody",
  /* 372 */ "Mniej",
  /* 373 */ "Panel kodów",
  /* 374 */ "Więcej",
  /* 375 */ "Zacznij od nowa",
  /* 376 */ "Kody",
  /* 377 */ "Kody…",
  /* 378 */ "Wartość",
  /* 379 */ "Równa się",
  /* 380 */ "{0} możliwych adresów",
  /* 381 */ "Wgrano {0} plików, usunięto {1}",
  /* 382 */ "{0} z {1} gier ma plik",
  /* 383 */ "{0} bajtów pamięci",
  /* 384 */ "Odrzucono {0} wartości: poza pamięcią tej gry",
  /* 385 */ "Brak pliku dla tej gry. Panel „Kody…” w menu Emulacja go szuka; a jeśli nie ma, szukanie wartości działa w każdej grze.",
  /* 386 */ "Zamrożona",
  /* 387 */ "Zamroź",
  /* 388 */ "Pograj chwilę, a potem powiedz, co zrobiła wartość.",
  /* 389 */ "Grę odłożono na bok przed pierwszym kodem.",
  /* 390 */ "Szukanie…",
  /* 391 */ "To, co zostanie położone w « drop u'r rom », trafia do konsoli wskazanej przez rozszerzenie pliku. Gdy to samo rozszerzenie dzieli kilka konsol — obrazy płyt — EvaChi raczej zapyta, niż zgadnie.",
  /* 392 */ "Potwierdzenie",
  /* 393 */ "Usuń zapis gry…",
  /* 394 */ "Rozciągnięcie",
  /* 395 */ "Gra trzyma swoje liczniki w pamięci, nie mówiąc gdzie. Znajduje się je przez odsiewanie: mówisz, co zrobiła liczba na ekranie, a EvaChi odrzuca adresy, które nie zrobiły tego samego.",
  /* 396 */ "Tak",
  /* 397 */ "Niewiele konsol ma proporcje dzisiejszego ekranu, stąd czarne pasy po bokach. Przy zerze obraz zachowuje swoje proporcje; przy stu wypełnia okno, choćby się rozciągnął.",
  /* 398 */ "Porządkowanie gier",
  /* 399 */ "Uporządkuj",
  /* 400 */ "Uporządkuj odłożone gry…",
  /* 401 */ "Widzisz 47 żyć: wpisz 47 w pole « Wartość » i naciśnij « Szukaj ». Strać jedno, wpisz 46 i naciśnij « Równa się ». Jeśli liczba nigdzie nie jest wypisana, zostaw « Wartość » pustą i między dwiema chwilami gry powiedz tylko « Więcej », « Mniej », « Inna » albo « Taka sama ». Znalezioną wartość utrzyma potem « Zamroź ». « Szerokość » to wielkość liczby: 1 do 255, 2 powyżej, 4 dla dużych liczników.",
  /* 402 */ "uporządkowano: {0}",
  /* 403 */ "brak zapisu do usunięcia",
  /* 404 */ "Przyciski",
  /* 405 */ "Już w bibliotece: {0}",
  /* 406 */ "Usunąć zapis gry {0} i zacząć od nowa? Trwająca rozgrywka zostanie zatrzymana, a to, co gra zanotowała, przepadnie.",
  /* 407 */ "Spusty",
  /* 408 */ "Zachowaj oba",
  /* 409 */ "Zostaw w katalogu",
  /* 410 */ "Katalog jest pusty.",
  /* 411 */ "Zastąpić miejsce {0}? To, co tam leży, przepadnie.",
  /* 412 */ "zapis gry usunięty — {0}",
  /* 413 */ "System",
  /* 414 */ "Opróżnić miejsce {0}? To, co tam leży, przepadnie.",
  /* 415 */ "Martwa strefa to ta część gałki, w której uznaje się ją jeszcze za spoczywającą. Za mała — postać rusza sama, choć pad leży na stole; za duża — drobne ruchy giną. Niektóre gry proszą, by potrząsnąć konsolą: kiedy pad nie potrafi tego wyczuć, dwa poniższe przyciski każą grze w to uwierzyć.",
  /* 416 */ "Gałka",
  /* 417 */ "Samodzielne emulatory mają własne przyciski, we własnych plikach. To, co zmienisz tutaj, jest tam przenoszone od razu — dla tych, których format znamy z pierwszej ręki: PCSX2, PPSSPP i Dolphin. Stare ustawienie odkłada się przy pierwszym przejściu na bok, pod tą samą nazwą z końcówką « .avant-evachi ».",
  /* 418 */ "Przenieś do zewnętrznych emulatorów",
  /* 419 */ "Martwa strefa",
  /* 420 */ "Seans",
  /* 421 */ "Glina",
  /* 422 */ "żaden zewnętrzny emulator nie zapisał jeszcze swoich ustawień",
  /* 423 */ "Żar",
  /* 424 */ "Popiół",
  /* 425 */ "Wiśnia",
  /* 426 */ "Koral",
  /* 427 */ "Talia",
  /* 428 */ "Las",
  /* 429 */ "Szron",
  /* 430 */ "zewnętrzne emulatory miały już te przyciski",
  /* 431 */ "Północ",
  /* 432 */ "Mech",
  /* 433 */ "Neon",
  /* 434 */ "Śliwka",
  /* 435 */ "Piasek",
  /* 436 */ "Potrząśnij",
  /* 437 */ "Sepia",
  /* 438 */ "przeniesione przyciski: {0}",
  /* 439 */ "Turkus",
  /* 440 */ "Okładki trzymane wachlarzem, jak karty w ręce. Nadgarstek się obraca, a czytana karta prostuje.",
  /* 441 */ "Ciemna sala, smuga pełna kurzu i gra wyświetlana w powiększeniu. Reszta czeka w magazynku.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Morela",
  /* 444 */ "Wrzos",
  /* 445 */ "Karmel",
  /* 446 */ "Miedź",
  /* 447 */ "Atrament",
  /* 448 */ "Famicom",
  /* 449 */ "Jadeit",
  /* 450 */ "Borówka",
  /* 451 */ "Burza",
  /* 452 */ "Perła",
  /* 453 */ "Pistacja",
  /* 454 */ "Brak",
  /* 455 */ "Linie",
  /* 456 */ "Każdy piksel w trzech szczelinach: czerwonej, zielonej i niebieskiej",
  /* 457 */ "Obraz rdzenia, piksel w piksel",
  /* 458 */ "Wypukłe szkło, linie, szczeliny i wygaszone brzegi",
  /* 459 */ "Maska szczelinowa",
  /* 460 */ "Kineskop",
  /* 461 */ "Co druga linia przyciemniona, jak w telewizorze",
  /* 462 */ "Otwiera emulator w jego własnym oknie, bez gry",
  /* 463 */ "Otwórz",
  /* 464 */ "Głośność",
  /* 465 */ "Płyta",
  /* 466 */ "nie udało się zmienić płyty — {0}",
  /* 467 */ "płyta {0}",
];
