/**
 * Polonais — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros portés en commentaire sont là pour qu'on puisse le vérifier à
 * l'œil, ligne à ligne.
 */

export const pl: readonly string[] = [
  /* 1 */ "Na padzie",
  /* 2 */ "A uruchom · X ulubione · Y przytnij · L1/R1 konsole · L2/R2 litera · B powrót",
  /* 3 */ "O programie EvaChi",
  /* 4 */ "O programie…",
  /* 5 */ "Wkrótce: filtry kineskopowe, siatka maski, linie obrazu. Miejsce jest gotowe, filtry trafią tutaj.",
  /* 6 */ "Odśwież bibliotekę",
  /* 7 */ "Widok",
  /* 8 */ "Pokazuj okładki gier",
  /* 9 */ "Pomoc",
  /* 10 */ "Dodaj folder z grami…",
  /* 11 */ "Dodaj folder…",
  /* 12 */ "Naciśnij przycisk pada: odpowiadający mu klawisz się zaświeci. Aby go zmienić, włącz przypisywanie na nowo, kliknij klawisz do zmiany, a potem naciśnij wybrany przycisk.",
  /* 13 */ "Argumenty",
  /* 14 */ "Na klawiaturze",
  /* 15 */ "Brak gier",
  /* 16 */ "Nie wykryto pada.",
  /* 17 */ "Biblioteka",
  /* 18 */ "Dźwięki wyboru na padzie",
  /* 19 */ "Niektóre konsole nie ruszą bez swojego oryginalnego firmware'u. EvaChi nie może go dostarczyć: to kod objęty prawem autorskim, który kopiuje się z własnego sprzętu. Powie za to, którego brakuje, pod jaką nazwą i gdzie go położyć.",
  /* 20 */ "Te konsole nie mają rdzenia libretro: ich emulator to osobny program, który EvaChi instaluje u siebie i uruchamia od razu w grze — z pominięciem jego menu. Gry, klucze i pliki systemowe zostają po twojej stronie.",
  /* 21 */ "Te ustawienia dotyczą tylko rdzeni wewnętrznych. Emulator zewnętrzny ma własne i EvaChi się do nich nie miesza.",
  /* 22 */ "Te nie są już proponowane: nie odpowiedziały na zapytanie albo położyły EvaChi. Przywrócenie nie instaluje ich na nowo — po prostu wracają na listę.",
  /* 23 */ "Wczytaj stan",
  /* 24 */ "Tylko rdzenie wewnętrzne. Kliknij skrót, a potem naciśnij wybrany klawisz lub przycisk; na padzie bierzemy dwa przyciski naraz, bo każdy z nich służy już grze.",
  /* 25 */ "Sterowanie",
  /* 26 */ "Sterowanie…",
  /* 27 */ "Ostatnie konsole",
  /* 28 */ "Dodaj własny emulator",
  /* 29 */ "Kierunki / lewa gałka",
  /* 30 */ "Foldery z grami",
  /* 31 */ "Odstaw ten emulator",
  /* 32 */ "Przychodzą na żądanie z serwera miniatur projektu libretro. Po odznaczeniu biblioteka nie sięga już do sieci.",
  /* 33 */ "Miejsca zapisu",
  /* 34 */ "Miejsca zapisu…",
  /* 35 */ "Emulatory",
  /* 36 */ "Odstawione emulatory",
  /* 37 */ "Emulatory zewnętrzne",
  /* 38 */ "Emulatory zewnętrzne…",
  /* 39 */ "Emulatory…",
  /* 40 */ "Emulacja",
  /* 41 */ "Powrót do biblioteki w trakcie gry — dwa przyciski naraz, bo każdy z nich służy grze",
  /* 42 */ "Zapisz",
  /* 43 */ "Rozszerzenia",
  /* 44 */ "Zamknij",
  /* 45 */ "Plik",
  /* 46 */ "Pliki systemowe do wgrania samodzielnie",
  /* 47 */ "Galeria",
  /* 48 */ "Zarządzaj folderami…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Wskaż folder, w którym leżą twoje gry.",
  /* 52 */ "Instalacja",
  /* 53 */ "Zainstaluj zaznaczone",
  /* 54 */ "Zainstaluj emulatory…",
  /* 55 */ "Interpreter",
  /* 56 */ "Nie musisz wiedzieć gdzie: pokaż folder, w którym wszystko się poniewiera — BIOS-y, klucze, firmware, archiwa, razem z podfolderami — a EvaChi zaniesie każdy plik na właściwe miejsce, tak dla rdzeni, jak i dla samodzielnych emulatorów. Czego nikt nie szuka, zostaje na miejscu.",
  /* 57 */ "Okładki",
  /* 58 */ "Dziennik",
  /* 59 */ "Dziennik…",
  /* 60 */ "Poprzednim razem skończyło się źle",
  /* 61 */ "Uruchomienie gry, zatwierdzenie",
  /* 62 */ "Język",
  /* 63 */ "Wybór zostaje zapamiętany między uruchomieniami. Każdy sprawdziliśmy pod kątem czytelności: tekst wszędzie zachowuje wystarczający kontrast na swoim tle.",
  /* 64 */ "Zachowaj go",
  /* 65 */ "Poniższe emulatory są już skonfigurowane — razem z argumentami i formatami. EvaChi szuka ich na twoim dysku; nie instaluje ich.",
  /* 66 */ "Domyślne przypisania",
  /* 67 */ "Wygładzanie",
  /* 68 */ "Dodanie gry do ulubionych lub usunięcie jej z nich",
  /* 69 */ "Muzyka menu animowanego",
  /* 70 */ "Nazwa",
  /* 71 */ "Otwarcie paska menu",
  /* 72 */ "Otwórz folder",
  /* 73 */ "Otwórz folder…",
  /* 74 */ "Otwórz grę…",
  /* 75 */ "na klatkę",
  /* 76 */ "Ustawienia rdzenia",
  /* 77 */ "Ustawienia rdzenia…",
  /* 78 */ "Poruszanie się po bibliotece, oknach i pasku menu",
  /* 79 */ "Przeglądaj…",
  /* 80 */ "Pauza",
  /* 81 */ "Pełny ekran",
  /* 82 */ "Dla konsol bez rdzenia libretro. EvaChi uruchamia program z grą jako argumentem: emulator startuje od razu w grze, z pominięciem własnego menu.",
  /* 83 */ "Zrób zrzut ekranu",
  /* 84 */ "Układ",
  /* 85 */ "Gotowe",
  /* 86 */ "Program",
  /* 87 */ "Kilka przeciągniętych akordów i rozsiane dźwięki, układane na bieżąco, a nie nagrane: utwór nigdy nie wraca w to samo miejsce. Milknie sam, gdy tylko ruszy gra.",
  /* 88 */ "Uporządkuj folder…",
  /* 89 */ "Przypisz na nowo…",
  /* 90 */ "Szukaj gry…",
  /* 91 */ "Zresetuj",
  /* 92 */ "Powrót do biblioteki",
  /* 93 */ "Cofnięcie, zamknięcie",
  /* 94 */ "Szybki zapis",
  /* 95 */ "Zapisz stan",
  /* 96 */ "Shadery",
  /* 97 */ "Dźwięk",
  /* 98 */ "Start",
  /* 99 */ "Rozmiar obrazu",
  /* 100 */ "Motywy",
  /* 101 */ "Motywy…",
  /* 102 */ "Jeden plik na grę…",
  /* 103 */ "Krótkie stuknięcie przy zmianie gry, drugie przy jej uruchomieniu. Tylko na padzie: przy myszy i klawiaturze gest czuć i tak.",
  /* 104 */ "Prędkość",
  /* 105 */ "Zobacz zrzuty…",
  /* 106 */ "Możesz zainstalować tylko część — w bibliotece pojawiają się wyłącznie konsole, których emulator jest zainstalowany.",
  /* 107 */ "{0} — wczytano",
  /* 108 */ "{0} — prawym przyciskiem wyczyścisz",
  /* 109 */ "{0} — dodano do ulubionych",
  /* 110 */ "{0} — przywrócono domyślne",
  /* 111 */ "{0} — usunięto z ulubionych",
  /* 112 */ "{0} — pobieranie…",
  /* 113 */ "{0}: nie udało się, zajrzyj do dziennika",
  /* 114 */ "{0} do dyspozycji",
  /* 115 */ "{0} zapisano",
  /* 116 */ "{0} to emulator zewnętrzny: uruchamia się osobno, w środku nie działa",
  /* 117 */ "{0} kl./s",
  /* 118 */ "{0} zainstalowano",
  /* 119 */ "{0} zainstalowano — {1}",
  /* 120 */ "{0} zainstalowano, wszystko gotowe",
  /* 121 */ "{0} zainstalowano, {1} bez powodzenia — zajrzyj do dziennika",
  /* 122 */ "{0} przywrócono",
  /* 123 */ "{0} usunięto",
  /* 124 */ "{0} z {1}",
  /* 125 */ "{0} na dysku, ale żaden zainstalowany rdzeń tego nie otworzy.",
  /* 126 */ "do wzięcia z {0}, potem „Przeglądaj…”",
  /* 127 */ "do pobrania",
  /* 128 */ "brak, opcjonalny",
  /* 129 */ "Włącz",
  /* 130 */ "Miękki",
  /* 131 */ "nie udało się dodać — {0}",
  /* 132 */ "Dopasuj",
  /* 133 */ "Bursztyn",
  /* 134 */ "Łupek",
  /* 135 */ "zatrzymano — {0}",
  /* 136 */ "poprzednio nagłe zatrzymanie — {0}",
  /* 137 */ "brak",
  /* 138 */ "żaden rdzeń nie wrócił, choć znanych było {0} — zachowano poprzednią listę",
  /* 139 */ "brak emulatorów",
  /* 140 */ "Nie zainstalowano żadnego emulatora",
  /* 141 */ "Nie rozpoznano żadnej gry",
  /* 142 */ "Brak wyników",
  /* 143 */ "brak",
  /* 144 */ "biblioteki nie da się odczytać — {0}",
  /* 145 */ "podłączony",
  /* 146 */ "zrzut",
  /* 147 */ "Zmień okładkę…",
  /* 148 */ "Zmień…",
  /* 149 */ "Każdy piksel na dziewięć",
  /* 150 */ "Każdy piksel na cztery: ostro, bez zniekształceń",
  /* 151 */ "Każdy piksel na szesnaście — na duże ekrany",
  /* 152 */ "Wczytaj",
  /* 153 */ "Wybierz okładkę…",
  /* 154 */ "najpierw wybierz grę w bibliotece",
  /* 155 */ "rdzeń: {0}",
  /* 156 */ "rdzeń niezainstalowany",
  /* 157 */ "Zainstalowane rdzenie",
  /* 158 */ "rdzenie libretro",
  /* 159 */ "Wysoki kontrast",
  /* 160 */ "powłoka natywna: {0}",
  /* 161 */ "niepełne zwolnienie rdzenia — {0}",
  /* 162 */ "wykryto: {0}",
  /* 163 */ "wykrywanie przerwane — {0}",
  /* 164 */ "Wskaż samodzielnie program dla {0}",
  /* 165 */ "dodano folder: {0}",
  /* 166 */ "otwarto folder: {0}",
  /* 167 */ "Folder domyślny",
  /* 168 */ "Dodane foldery",
  /* 169 */ "Esc",
  /* 170 */ "Miejsce {0}",
  /* 171 */ "miejsce {0} — {1}",
  /* 172 */ "Emulator używany dla tego folderu",
  /* 173 */ "emulatory zewnętrzne",
  /* 174 */ "w toku",
  /* 175 */ "na miejscu",
  /* 176 */ "nie udało się zapisać — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi może je pobrać z oficjalnej kuźni libretro. Wybierz konsole, które cię interesują.",
  /* 179 */ "EvaChi zamknęła się nagle przy uruchamianiu „{0}”, z emulatorem {1}.",
  /* 180 */ "EvaChi zamknęła się nagle, z emulatorem {0}.",
  /* 181 */ "external_systems → zgłoszonych emulatorów: {0}",
  /* 182 */ "Ulubiona",
  /* 183 */ "Ulubione",
  /* 184 */ "plików systemowych nie da się odczytać — {0}",
  /* 185 */ "Strzałki",
  /* 186 */ "Game Boy",
  /* 187 */ "Siatka",
  /* 188 */ "zainstalowanym konsolom brakuje: {0}",
  /* 189 */ "instalacja zakończona: {0}",
  /* 190 */ "Instalowanie…",
  /* 191 */ "zainstalowany",
  /* 192 */ "zainstalowany przez EvaChi",
  /* 193 */ "Zainstaluj",
  /* 194 */ "interpreter: {0}",
  /* 195 */ "odpytywanie zainstalowanych rdzeni…",
  /* 196 */ "Uruchom",
  /* 197 */ "Uruchom wybraną grę",
  /* 198 */ "Lawenda",
  /* 199 */ "Konsole w rzędzie, gry w kolumnie, falujące tło. Jak na konsoli pod telewizorem.",
  /* 200 */ "Kontury są rozmyte — bliżej starego telewizora",
  /* 201 */ "Duże okładki, przeglądane padem. Pomyślane pod kanapę.",
  /* 202 */ "Piksele zostają kwadratowe, jak na oryginalnym sprzęcie",
  /* 203 */ "przypisania pada przywrócone do domyślnych",
  /* 204 */ "list_cores → zapowiedzianych rdzeni: {0}",
  /* 205 */ "Lista",
  /* 206 */ "lista rdzeni niedostępna — {0}",
  /* 207 */ "lista emulatorów niedostępna — {0}",
  /* 208 */ "Pad",
  /* 209 */ "pad: {0}",
  /* 210 */ "Pad: {0}",
  /* 211 */ "pad odłączony",
  /* 212 */ "BRAK",
  /* 213 */ "Mięta",
  /* 214 */ "Menu animowane",
  /* 215 */ "Zaktualizuj",
  /* 216 */ "Dodaj do ulubionych",
  /* 217 */ "odstawiono: {0} · {1}",
  /* 218 */ "mniej niż minuta",
  /* 219 */ "Ostry",
  /* 220 */ "nazwa, program i rozszerzenia — wszystkie są potrzebne",
  /* 221 */ "NIE",
  /* 222 */ "nie ma go na tym komputerze",
  /* 223 */ "Różowa noc",
  /* 224 */ "Ocean",
  /* 225 */ "lub",
  /* 226 */ "tak",
  /* 227 */ "nie udało się otworzyć — {0}",
  /* 228 */ "strona internetowa: dostępne są tylko rdzenie wewnętrzne, bez biblioteki",
  /* 229 */ "Papier",
  /* 230 */ "domyślnie",
  /* 231 */ "Poruszanie się po siatce i menu animowanym",
  /* 232 */ "pełny ekran odrzucony — {0}",
  /* 233 */ "naciśnij wybrany przycisk na padzie",
  /* 234 */ "naciśnij klawisz…",
  /* 235 */ "uporządkowano: {0} · {1}",
  /* 236 */ "nie udało się uporządkować — {0}",
  /* 237 */ "szukanie emulatorów przerwane — {0}",
  /* 238 */ "Zamknięcie okna",
  /* 239 */ "nie udało się zresetować — {0}",
  /* 240 */ "Wypełnia okno z zachowaniem proporcji",
  /* 241 */ "Wznów",
  /* 242 */ "Wznów z tego zapisu — prawym przyciskiem go wyczyścisz",
  /* 243 */ "Przywróć",
  /* 244 */ "nie udało się przywrócić — {0}",
  /* 245 */ "Usuń",
  /* 246 */ "Usuń z ulubionych",
  /* 247 */ "Usuń okładkę",
  /* 248 */ "nie udało się usunąć — {0}",
  /* 249 */ "nie ma czego porządkować",
  /* 250 */ "nic nie blokuje",
  /* 251 */ "Nic nie pasuje do „{0}”.",
  /* 252 */ "Róż i biel",
  /* 253 */ "bez obrazka",
  /* 254 */ "Zapisz",
  /* 255 */ "Zapisz tutaj",
  /* 256 */ "nie udało się wybrać — {0}",
  /* 257 */ "Oryginalny rozmiar konsoli, co do piksela",
  /* 258 */ "Zakończ",
  /* 259 */ "motyw jasny",
  /* 260 */ "motyw ciemny",
  /* 261 */ "wszystko zainstalowane",
  /* 262 */ "znaleziono: {0}",
  /* 263 */ "Jeden panel na konsolę, w tabeli. Najgęściej przy myszy.",
  /* 264 */ "puste",
  /* 265 */ "połóż tutaj, tak jak romsety gier: FinalBurn Neo szuka tylko w tym folderze",
  /* 266 */ "dodaje ekran powitalny konsoli",
  /* 267 */ "program rozruchowy maszyny",
  /* 268 */ "wiele gier ruszy bez niego; menu konsoli już nie",
  /* 269 */ "BIOS amerykański",
  /* 270 */ "BIOS amerykański i europejski",
  /* 271 */ "BIOS europejski",
  /* 272 */ "BIOS japoński",
  /* 273 */ "klucze deszyfrujące; bez nich zaszyfrowany zrzut zostanie odrzucony",
  /* 274 */ "folder maszyn z dystrybucji blueMSX, z Databases obok",
  /* 275 */ "to samo",
  /* 276 */ "niezbędny do gier CD, zbędny przy kartach HuCard",
  /* 277 */ "niezbędny do gier Mega-CD, zbędny przy kartridżach",
  /* 278 */ "Kickstart 1.3; bez niego PUAE sięga po AROS, wolny, ale mniej zgodny",
  /* 279 */ "Kickstart 3.1; potrzebny do gier AGA, których A500 nie umie uruchomić",
  /* 280 */ "melonDS domyślnie emuluje BIOS; prawdziwy jest wierniejszy",
  /* 281 */ "mGBA obywa się bez niego; kilka gier wymaga go do ekranu powitalnego",
  /* 282 */ "firmware konsoli",
  /* 283 */ "firmware maszyny",
  /* 284 */ "firmware Panasonic FZ-10; tę nazwę Opera przyjmuje domyślnie",
  /* 285 */ "zmieniany przez melonDS, który zachowuje oryginał jako .bak",
  /* 286 */ "czcionki",
  /* 287 */ "ustawienia i data konsoli",
  /* 288 */ "bez niego rdzeń działa, ale ekran zostaje czarny",
  /* 289 */ "tablica znaków konsoli",
  /* 290 */ "wersja amerykańska, do gier Sega CD ze Stanów",
  /* 291 */ "wersja japońska, do japońskich gier Mega-CD",
  /* 292 */ "zrzuty",
  /* 293 */ "zrzutów",
  /* 294 */ "zrzut",
  /* 295 */ "zrzutu",
  /* 296 */ "zrzuty",
  /* 297 */ "zrzutów",
  /* 298 */ "rdzenie",
  /* 299 */ "rdzeni",
  /* 300 */ "rdzeń",
  /* 301 */ "rdzenia",
  /* 302 */ "rdzenie",
  /* 303 */ "rdzeni",
  /* 304 */ "emulatory",
  /* 305 */ "emulatorów",
  /* 306 */ "emulator",
  /* 307 */ "emulatora",
  /* 308 */ "emulatory",
  /* 309 */ "emulatorów",
  /* 310 */ "pliki",
  /* 311 */ "plików",
  /* 312 */ "plik",
  /* 313 */ "pliku",
  /* 314 */ "pliki",
  /* 315 */ "plików",
  /* 316 */ "gry",
  /* 317 */ "gier",
  /* 318 */ "gra",
  /* 319 */ "gry",
  /* 320 */ "gry",
  /* 321 */ "gier",
  /* 322 */ "<code>{rom}</code> zostanie zastąpione ścieżką gry. Bez niego ścieżka trafia na koniec — a tego właśnie oczekuje większość emulatorów.",
  /* 323 */ "<strong>Poza grą wszystko robi się padem:</strong> kierunki prowadzą po bibliotece, oknach i pasku menu; <strong>A</strong> zatwierdza, <strong>B</strong> cofa, <strong>Start</strong> otwiera pasek menu. W trakcie gry <strong>Select i Start naraz</strong> wracają do biblioteki — dwa przyciski jednocześnie, bo każdy z nich służy grze.",
  /* 324 */ "Brak zrzutów. Naciśnij <strong>F12</strong> w trakcie gry albo <strong>Select + Y</strong> na padzie.",
  /* 325 */ "Każda konsola potrzebuje swojego emulatora. EvaChi pobiera je z oficjalnej kuźni projektu libretro, <code>buildbot.libretro.com</code>, i instaluje we własnym folderze. Nic nie jest rozpowszechniane dalej: to wersje wydane przez ich autorów.",
  /* 326 */ "Cztery miejsca zapisu na grę, trzymane na dysku. Z pogrubionego miejsca korzystają <strong>F2</strong> i <strong>F4</strong> — oraz <strong>Select + L1</strong> / <strong>Select + R1</strong> na padzie. Miejsce wyczyścisz prawym przyciskiem.",
  /* 327 */ "Każdy emulator działa we własnym procesie: kiedy pada, EvaChi to widzi i wraca do biblioteki. Trwająca rozgrywka przepada, a zapis gry mógł nie trafić na dysk. Po odstawieniu zostaje zainstalowany, przestaje się tylko pojawiać w wyborze. Możesz go przywrócić w każdej chwili przez <strong>Plik → Emulatory</strong>, na dole okna.",
  /* 328 */ "Jeden plik na grę na dysku <small> Gra z płyty przychodzi jako arkusz <code>.cue</code> i tyle plików <code>.bin</code>, ile ścieżek miała płyta. Uruchamia się tylko arkusz: przy nim ścieżki są ukryte. Bez arkusza nic nie jest ukryte. </small>",
  /* 329 */ "(puste) lub --fullscreen {rom}",
  /* 330 */ "Sto procent to prędkość samej konsoli. Niżej gra zwalnia, wyżej pędzi — a dźwięk idzie za nią, niżej albo wyżej. Na padzie lewo i prawo przeskakują z jednego stopnia na następny. Tylko rdzenie wewnętrzne: zewnętrzny emulator trzyma się własnej prędkości.",
  /* 331 */ "Pięć konsol naraz",
  /* 332 */ "Krzyżak kierunkowy",
  /* 333 */ "Od jednej litery do następnej",
  /* 334 */ "W animowanym menu pięć gier naraz",
  /* 335 */ "Prędkość gry",
  /* 336 */ "Anuluj",
  /* 337 */ "Przeciągnij ramkę albo pociągnij za róg. Strzałki ją przesuwają, a ze Shiftem powiększają lub zmniejszają. Gdy ramka wyjdzie poza obraz, dokładają się przezroczyste pasy: tak właśnie oddalisz zbyt ciasną okładkę. Na padzie kierunki przesuwają ramkę, a spusty ustawiają jej rozmiar.",
  /* 338 */ "Przytnij",
  /* 339 */ "Przytnij okładkę",
  /* 340 */ "Cały obraz",
  /* 341 */ "{0} — okładka przycięta",
  /* 342 */ "{0} — brak okładki do przycięcia",
  /* 343 */ "okładka nie do odczytu — {0}",
  /* 344 */ "nie udało się przyciąć — {0}",
  /* 345 */ "Przytnij okładkę…",
  /* 346 */ "Szybkie przewijanie, dopóki obie gałki pozostają wciśnięte",
  /* 347 */ "{0} odstawiono",
  /* 348 */ "Emulator {0} zatrzymał się w trakcie „{1}”.",
  /* 349 */ "Emulator {0} zatrzymał się.",
  /* 350 */ "Emulator się zatrzymał",
  /* 351 */ "nie udało się odstawić — {0}",
];
