/**
 * Portugais du Brésil — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * numérotées en commentaire sont là pour qu'on puisse le vérifier à l'œil.
 */

export const ptBR: readonly string[] = [
  /* 1 */ "No controle",
  /* 2 */ "A jogar · X favorito · Y recortar · L1/R1 consoles · L2/R2 letra · B voltar",
  /* 3 */ "Sobre o EvaChi",
  /* 4 */ "Sobre…",
  /* 5 */ "O que uma televisão de tubo fazia com a imagem, e que os jogos da época davam como certo. Vale só para os núcleos jogados aqui: um emulador autônomo desenha a própria imagem.",
  /* 6 */ "Atualizar a biblioteca",
  /* 7 */ "Exibição",
  /* 8 */ "Mostrar as capas dos jogos",
  /* 9 */ "Ajuda",
  /* 10 */ "Adicionar uma pasta de jogos…",
  /* 11 */ "Adicionar pasta…",
  /* 12 */ "Pressione um botão do controle: o comando correspondente se acende. Para trocar algum, clique na caixa de baixo e pressione o botão desejado. O botão muda então de dono: dois comandos no mesmo botão pareceriam um defeito.",
  /* 13 */ "Argumentos",
  /* 14 */ "No teclado",
  /* 15 */ "Nenhum jogo",
  /* 16 */ "Nenhum controle detectado.",
  /* 17 */ "Biblioteca",
  /* 18 */ "Sons de seleção no controle",
  /* 19 */ "Alguns consoles não iniciam sem o firmware original. O EvaChi não pode fornecê-lo: é código protegido por direitos autorais, que se copia da máquina que se tem em casa. Em compensação, ele diz qual está faltando, com que nome, e onde colocá-lo.",
  /* 20 */ "Estes consoles não têm núcleo libretro: o emulador deles é um programa à parte, que o EvaChi instala na própria pasta e abre direto no jogo — sem passar pelo menu dele. Os jogos, as chaves e os arquivos de sistema ficam por sua conta.",
  /* 21 */ "Estes ajustes só valem para os núcleos internos. Um emulador externo tem os seus, e o EvaChi não se mete neles.",
  /* 22 */ "Estes não são mais oferecidos: não responderam à consulta, ou derrubaram o EvaChi. Restaurá-los não os reinstala — apenas os devolve à lista.",
  /* 23 */ "Carregar estado…",
  /* 24 */ "Apenas núcleos internos. Clique num atalho e pressione a tecla ou o botão desejado; no controle são dois botões de uma vez, porque cada um deles já serve ao jogo.",
  /* 25 */ "Comandos",
  /* 26 */ "Comandos…",
  /* 27 */ "Consoles recentes",
  /* 28 */ "Declarar outro emulador",
  /* 29 */ "Direcionais / analógico esquerdo",
  /* 30 */ "Pastas de jogos",
  /* 31 */ "Dispensar este emulador",
  /* 32 */ "Elas vêm do servidor de miniaturas do projeto libretro, conforme a necessidade. Desmarcada, a biblioteca não pede mais nada à rede.",
  /* 33 */ "Slots de salvamento",
  /* 34 */ "Slots…",
  /* 35 */ "Emuladores",
  /* 36 */ "Emuladores dispensados",
  /* 37 */ "Emuladores externos",
  /* 38 */ "Emuladores externos…",
  /* 39 */ "Emuladores…",
  /* 40 */ "Emulação",
  /* 41 */ "Durante a partida, voltar à biblioteca — dois botões de uma vez, porque cada um deles serve ao jogo",
  /* 42 */ "Salvar",
  /* 43 */ "Extensões",
  /* 44 */ "Fechar",
  /* 45 */ "Arquivo",
  /* 46 */ "Arquivos de sistema a instalar por conta própria",
  /* 47 */ "Galeria",
  /* 48 */ "Gerenciar as pastas…",
  /* 49 */ "Gráficos",
  /* 50 */ "Gráficos…",
  /* 51 */ "Indique a pasta onde estão os seus jogos.",
  /* 52 */ "Instalação",
  /* 53 */ "Instalar a seleção",
  /* 54 */ "Instalar os emuladores…",
  /* 55 */ "Interpretador",
  /* 56 */ "Não precisa saber onde: mostre a pasta em que tudo está jogado — BIOS, chaves, firmwares, arquivos compactados, subpastas incluídas — e o EvaChi leva cada arquivo ao lugar certo, tanto para os núcleos quanto para os emuladores autônomos. O que ninguém pede não sai do lugar.",
  /* 57 */ "Capas",
  /* 58 */ "Registro",
  /* 59 */ "Registro…",
  /* 60 */ "A última vez terminou mal",
  /* 61 */ "Iniciar o jogo, confirmar",
  /* 62 */ "Idioma",
  /* 63 */ "A escolha é lembrada de uma sessão para outra. Todos foram conferidos quanto à leitura: o texto mantém em toda parte um contraste suficiente sobre o fundo.",
  /* 64 */ "Manter",
  /* 65 */ "Os emuladores abaixo já vêm configurados — argumentos e formatos incluídos. O EvaChi os procura no seu disco; ele não os instala.",
  /* 66 */ "Atribuições originais",
  /* 67 */ "Suavização",
  /* 68 */ "Marcar o jogo como favorito, ou tirá-lo",
  /* 69 */ "Música dos menus animados",
  /* 70 */ "Nome",
  /* 71 */ "Abrir a barra de menus",
  /* 72 */ "Abrir a pasta",
  /* 73 */ "Abrir a pasta…",
  /* 74 */ "Abrir um jogo…",
  /* 75 */ "por quadro",
  /* 76 */ "Ajustes do núcleo",
  /* 77 */ "Ajustes do núcleo…",
  /* 78 */ "Percorrer a biblioteca, as janelas e a barra de menus",
  /* 79 */ "Procurar…",
  /* 80 */ "Pausar",
  /* 81 */ "Tela cheia",
  /* 82 */ "Para os consoles sem núcleo libretro. O EvaChi abre o programa com o jogo como argumento: o emulador começa direto na partida, sem passar pelo próprio menu.",
  /* 83 */ "Tirar uma captura",
  /* 84 */ "Apresentação",
  /* 85 */ "Pronto",
  /* 86 */ "Programa",
  /* 87 */ "Alguns acordes sustentados e notas esparsas, compostos na hora em vez de gravados: a música nunca passa duas vezes pelo mesmo ponto. Ela para sozinha assim que um jogo começa.",
  /* 88 */ "Organizar uma pasta…",
  /* 89 */ "Esvaziar",
  /* 90 */ "Buscar um jogo…",
  /* 91 */ "Reiniciar",
  /* 92 */ "Voltar à biblioteca",
  /* 93 */ "Voltar atrás, fechar",
  /* 94 */ "Salvamento rápido",
  /* 95 */ "Salvar estado…",
  /* 96 */ "Shaders",
  /* 97 */ "Som",
  /* 98 */ "Start",
  /* 99 */ "Tamanho da imagem",
  /* 100 */ "Temas",
  /* 101 */ "Temas…",
  /* 102 */ "Um só arquivo…",
  /* 103 */ "Um tique curto ao trocar de jogo, outro ao iniciá-lo. Só no controle: no mouse e no teclado, o gesto já se sente.",
  /* 104 */ "Velocidade",
  /* 105 */ "Ver as capturas…",
  /* 106 */ "Você pode instalar só uma parte deles — só os consoles cujo emulador está instalado aparecem na biblioteca.",
  /* 107 */ "{0} — carregado",
  /* 108 */ "{0} — clique direito para apagar",
  /* 109 */ "{0} — marcado como favorito",
  /* 110 */ "{0} — reiniciado",
  /* 111 */ "{0} — tirado dos favoritos",
  /* 112 */ "{0} — baixando…",
  /* 113 */ "{0}: falhou, veja o registro",
  /* 114 */ "{0} à disposição",
  /* 115 */ "{0} salvo",
  /* 116 */ "{0} é um emulador externo: ele se abre à parte, não roda aqui dentro",
  /* 117 */ "{0} FPS",
  /* 118 */ "{0} instalado",
  /* 119 */ "{0} instalado — {1}",
  /* 120 */ "{0} instalado e pronto",
  /* 121 */ "{0} instalados, {1} com falha — veja o registro",
  /* 122 */ "{0} restaurado",
  /* 123 */ "{0} removido",
  /* 124 */ "{0} de {1}",
  /* 125 */ "{0} no disco, mas nenhum núcleo instalado consegue abrir.",
  /* 126 */ "pegar em {0}, depois \"Procurar…\"",
  /* 127 */ "a baixar",
  /* 128 */ "ausente, opcional",
  /* 129 */ "Ativar",
  /* 130 */ "Suavizado",
  /* 131 */ "não deu para adicionar — {0}",
  /* 132 */ "Ajustar",
  /* 133 */ "Âmbar",
  /* 134 */ "Ardósia",
  /* 135 */ "parada — {0}",
  /* 136 */ "parada brusca na última vez — {0}",
  /* 137 */ "nenhum",
  /* 138 */ "nenhum núcleo retornado, sendo que {0} eram conhecidos — lista anterior mantida",
  /* 139 */ "nenhum emulador",
  /* 140 */ "Nenhum emulador instalado",
  /* 141 */ "Nenhum jogo reconhecido",
  /* 142 */ "Nenhum resultado",
  /* 143 */ "nenhuma",
  /* 144 */ "biblioteca ilegível — {0}",
  /* 145 */ "conectado",
  /* 146 */ "captura",
  /* 147 */ "Trocar a capa…",
  /* 148 */ "Trocar…",
  /* 149 */ "Cada pixel em nove",
  /* 150 */ "Cada pixel em quatro: nítido, sem deformação",
  /* 151 */ "Cada pixel em dezesseis — para as telas grandes",
  /* 152 */ "Carregar",
  /* 153 */ "Escolher uma capa…",
  /* 154 */ "escolha antes um jogo na biblioteca",
  /* 155 */ "núcleo: {0}",
  /* 156 */ "núcleo não instalado",
  /* 157 */ "Núcleos instalados",
  /* 158 */ "núcleos libretro",
  /* 159 */ "Alto contraste",
  /* 160 */ "invólucro nativo: {0}",
  /* 161 */ "descarregamento incompleto — {0}",
  /* 162 */ "descoberta: {0}",
  /* 163 */ "descoberta interrompida — {0}",
  /* 164 */ "Indicar você mesmo o programa de {0}",
  /* 165 */ "pasta adicionada: {0}",
  /* 166 */ "pasta aberta: {0}",
  /* 167 */ "Pasta padrão",
  /* 168 */ "Pastas adicionadas",
  /* 169 */ "Esc",
  /* 170 */ "Slot {0}",
  /* 171 */ "slot {0} — {1}",
  /* 172 */ "Emulador usado para esta pasta",
  /* 173 */ "emuladores externos",
  /* 174 */ "em andamento",
  /* 175 */ "no lugar",
  /* 176 */ "não deu para salvar — {0}",
  /* 177 */ "Enter",
  /* 178 */ "O EvaChi pode baixá-los do servidor oficial do libretro. Escolha os consoles que lhe interessam.",
  /* 179 */ "O EvaChi parou ao iniciar \"{0}\", com o emulador {1}.",
  /* 180 */ "O EvaChi parou, com o emulador {0}.",
  /* 181 */ "external_systems → {0} emuladores declarados",
  /* 182 */ "Favorito",
  /* 183 */ "Favoritos",
  /* 184 */ "arquivos de sistema ilegíveis — {0}",
  /* 185 */ "Setas",
  /* 186 */ "Game Boy",
  /* 187 */ "Grade",
  /* 188 */ "{0} em falta para consoles instalados",
  /* 189 */ "instalação concluída: {0}",
  /* 190 */ "Instalando…",
  /* 191 */ "instalado",
  /* 192 */ "instalado pelo EvaChi",
  /* 193 */ "Instalar",
  /* 194 */ "interpretador: {0}",
  /* 195 */ "consultando os núcleos instalados…",
  /* 196 */ "Iniciar",
  /* 197 */ "Iniciar o jogo escolhido",
  /* 198 */ "Lavanda",
  /* 199 */ "Os consoles em linha, os jogos em coluna, um fundo que ondula. Ao jeito dos consoles de sala.",
  /* 200 */ "Os contornos se misturam — mais perto de uma TV antiga",
  /* 201 */ "As capas em tamanho grande, percorridas no controle. Pensado para o sofá.",
  /* 202 */ "Os pixels continuam quadrados, como na máquina original",
  /* 203 */ "atribuições do controle de volta ao original",
  /* 204 */ "list_cores → {0} núcleos anunciados",
  /* 205 */ "Lista",
  /* 206 */ "lista dos núcleos indisponível — {0}",
  /* 207 */ "lista dos emuladores indisponível — {0}",
  /* 208 */ "Controle",
  /* 209 */ "controle: {0}",
  /* 210 */ "Controle: {0}",
  /* 211 */ "controle desconectado",
  /* 212 */ "FALTANDO",
  /* 213 */ "Menta",
  /* 214 */ "Menu animado",
  /* 215 */ "Atualizar",
  /* 216 */ "Marcar como favorito",
  /* 217 */ "dispensado: {0} · {1}",
  /* 218 */ "menos de um minuto",
  /* 219 */ "Nítido",
  /* 220 */ "nome, programa e extensões são todos necessários",
  /* 221 */ "NÃO",
  /* 222 */ "não instalado nesta máquina",
  /* 223 */ "Noite rosa",
  /* 224 */ "Oceano",
  /* 225 */ "ou",
  /* 226 */ "sim",
  /* 227 */ "não deu para abrir — {0}",
  /* 228 */ "página web: só os núcleos internos estão disponíveis, sem biblioteca",
  /* 229 */ "Papel",
  /* 230 */ "padrão",
  /* 231 */ "Percorrer a grade e os menus animados",
  /* 232 */ "tela cheia recusada — {0}",
  /* 233 */ "pressione o botão desejado no controle",
  /* 234 */ "pressione uma tecla…",
  /* 235 */ "organização: {0} · {1}",
  /* 236 */ "não deu para organizar — {0}",
  /* 237 */ "busca dos emuladores interrompida — {0}",
  /* 238 */ "Fechar uma janela",
  /* 239 */ "não deu para reiniciar — {0}",
  /* 240 */ "Preenche a janela mantendo as proporções",
  /* 241 */ "Continuar",
  /* 242 */ "Substituir",
  /* 243 */ "Restaurar",
  /* 244 */ "não deu para restaurar — {0}",
  /* 245 */ "Remover",
  /* 246 */ "Tirar dos favoritos",
  /* 247 */ "Remover a capa",
  /* 248 */ "não deu para remover — {0}",
  /* 249 */ "nada a organizar",
  /* 250 */ "nada impede",
  /* 251 */ "Nada corresponde a \"{0}\".",
  /* 252 */ "Rosa e branco",
  /* 253 */ "sem imagem",
  /* 254 */ "Salvar",
  /* 255 */ "Salvar aqui",
  /* 256 */ "não deu para selecionar — {0}",
  /* 257 */ "Tamanho original do console, pixel a pixel",
  /* 258 */ "Descartar",
  /* 259 */ "tema claro",
  /* 260 */ "tema escuro",
  /* 261 */ "está tudo instalado",
  /* 262 */ "encontrado: {0}",
  /* 263 */ "Uma seção por console, em tabela. O mais denso no mouse.",
  /* 264 */ "vazio",
  /* 265 */ "colocar aqui, como os romsets dos jogos: o FinalBurn Neo só procura nesta pasta",
  /* 266 */ "acrescenta a tela de abertura do console",
  /* 267 */ "inicialização da máquina",
  /* 268 */ "muitos jogos iniciam sem ele; o menu do console não",
  /* 269 */ "BIOS americano",
  /* 270 */ "BIOS americano e europeu",
  /* 271 */ "BIOS europeu",
  /* 272 */ "BIOS japonês",
  /* 273 */ "chaves de descriptografia; sem elas uma cópia criptografada é recusada",
  /* 274 */ "pasta das máquinas da distribuição blueMSX, com Databases ao lado",
  /* 275 */ "idem",
  /* 276 */ "indispensável aos jogos em CD, inútil para os cartões HuCard",
  /* 277 */ "indispensável aos jogos Mega-CD, inútil para os cartuchos",
  /* 278 */ "Kickstart 1.3; sem ele o PUAE recorre ao AROS, livre mas menos compatível",
  /* 279 */ "Kickstart 3.1; necessário aos jogos AGA, que o A500 não consegue rodar",
  /* 280 */ "o melonDS emula o BIOS por padrão; o verdadeiro é mais fiel",
  /* 281 */ "o mGBA dispensa; alguns jogos o exigem para a tela de abertura",
  /* 282 */ "firmware do console",
  /* 283 */ "firmware da máquina",
  /* 284 */ "firmware Panasonic FZ-10; é esse nome que o Opera usa por padrão",
  /* 285 */ "modificado pelo melonDS, que preserva o original em .bak",
  /* 286 */ "fontes de caracteres",
  /* 287 */ "ajustes e data do console",
  /* 288 */ "sem ele o núcleo roda mas a tela fica preta",
  /* 289 */ "tabela de caracteres do console",
  /* 290 */ "variante americana, para os jogos Sega CD dos Estados Unidos",
  /* 291 */ "variante japonesa, para os jogos Mega-CD japoneses",
  /* 292 */ "capturas",
  /* 293 */ "capturas",
  /* 294 */ "captura",
  /* 295 */ "capturas",
  /* 296 */ "capturas",
  /* 297 */ "capturas",
  /* 298 */ "núcleos",
  /* 299 */ "núcleos",
  /* 300 */ "núcleo",
  /* 301 */ "núcleos",
  /* 302 */ "núcleos",
  /* 303 */ "núcleos",
  /* 304 */ "emuladores",
  /* 305 */ "emuladores",
  /* 306 */ "emulador",
  /* 307 */ "emuladores",
  /* 308 */ "emuladores",
  /* 309 */ "emuladores",
  /* 310 */ "arquivos",
  /* 311 */ "arquivos",
  /* 312 */ "arquivo",
  /* 313 */ "arquivos",
  /* 314 */ "arquivos",
  /* 315 */ "arquivos",
  /* 316 */ "jogos",
  /* 317 */ "jogos",
  /* 318 */ "jogo",
  /* 319 */ "jogos",
  /* 320 */ "jogos",
  /* 321 */ "jogos",
  /* 322 */ "<code>{rom}</code> será substituído pelo caminho do jogo. Sem ele, o caminho é acrescentado no fim — que é o que a maioria dos emuladores espera.",
  /* 323 */ "<strong>Fora do jogo, tudo se faz no controle:</strong> os direcionais percorrem a biblioteca, as janelas e a barra de menus; <strong>A</strong> confirma, <strong>B</strong> volta atrás, <strong>Start</strong> abre a barra de menus. Durante a partida, <strong>Select e Start juntos</strong> levam de volta à biblioteca — dois botões de uma vez, porque cada um deles serve ao jogo.",
  /* 324 */ "Nenhuma captura. Pressione <strong>F12</strong> durante a partida, ou <strong>Select + Y</strong> no controle.",
  /* 325 */ "Cada console precisa do seu emulador. O EvaChi vai buscá-los no servidor oficial do projeto libretro, <code>buildbot.libretro.com</code>, e os instala na própria pasta. Nada é redistribuído: são as versões publicadas pelos seus autores.",
  /* 326 */ "Quatro slots por jogo, guardados no disco. Cada gesto está escrito sob o slot, e substituir ou esvaziar pede confirmação. <strong>F2</strong> e <strong>F4</strong> — e <strong>Select + L1</strong> / <strong>Select + R1</strong> no controle — vão direto ao slot em negrito, sem perguntar nada.",
  /* 327 */ "Cada emulador roda no próprio processo: quando ele cai, o EvaChi percebe e volta à biblioteca. A partida em andamento se perde, e o salvamento do jogo pode não ter sido gravado. Dispensar este emulador o deixa instalado, mas para de oferecê-lo. Você poderá restaurá-lo a qualquer momento em <strong>Arquivo → Emuladores</strong>, no rodapé da janela.",
  /* 328 */ "Um só arquivo por jogo no disco <small> Um jogo em CD vem como uma folha <code>.cue</code> e tantos arquivos <code>.bin</code> quantas faixas o disco tinha. Só a folha é que abre: as faixas ficam escondidas quando ela está lá. Sem folha, nada fica escondido. </small>",
  /* 329 */ "(vazio) ou --fullscreen {rom}",
  /* 330 */ "Cem por cento é a velocidade do próprio console. Abaixo disso o jogo fica mais lento, acima ele dispara — e o som acompanha, mais grave ou mais agudo. No controle, esquerda e direita passam de um nível para o seguinte. Só os núcleos internos: um emulador externo segue a própria velocidade.",
  /* 331 */ "Cinco consoles de uma vez",
  /* 332 */ "Botão direcional",
  /* 333 */ "De uma inicial para a seguinte",
  /* 334 */ "Nos menus animados, cinco jogos de uma vez",
  /* 335 */ "Velocidade do jogo",
  /* 336 */ "Cancelar",
  /* 337 */ "Arraste a moldura ou puxe por um canto. As setas movem a moldura; com Shift, ela cresce ou encolhe. Se passar da imagem, entram faixas transparentes: é assim que você dá menos zoom numa capa apertada demais. No controle, as direções movem a moldura e os gatilhos ajustam o tamanho.",
  /* 338 */ "Recortar",
  /* 339 */ "Recortar a capa",
  /* 340 */ "Imagem inteira",
  /* 341 */ "{0} — capa recortada",
  /* 342 */ "{0} — nenhuma capa para recortar",
  /* 343 */ "capa ilegível — {0}",
  /* 344 */ "não foi possível recortar — {0}",
  /* 345 */ "Recortar a capa…",
  /* 346 */ "Avanço rápido, enquanto os dois analógicos ficarem pressionados",
  /* 347 */ "{0} dispensado",
  /* 348 */ "O emulador {0} parou durante \"{1}\".",
  /* 349 */ "O emulador {0} parou.",
  /* 350 */ "O emulador parou",
  /* 351 */ "não deu para dispensar — {0}",
  /* 352 */ "colocar aqui: {0}",
  /* 353 */ "falta um arquivo de sistema: {0}",
  /* 354 */ "Créditos",
  /* 355 */ "Licença não comercial, bom saber antes de reaproveitar este trabalho: {0}.",
  /* 356 */ "O EvaChi não escreve nenhum emulador: ele os hospeda. Cada um é um projeto livre por inteiro, escrito por outras pessoas, que o EvaChi vai buscar com os próprios autores sob demanda — nem uma linha do código deles é copiada aqui, nem um byte é redistribuído. Os nomes e as licenças abaixo são os que cada projeto declara por si mesmo.",
  /* 357 */ "Carrossel",
  /* 358 */ "As capas de frente, os consoles empilhados, uma poeira que sobe. No estilo de uma vitrine.",
  /* 359 */ "Como a interface",
  /* 360 */ "Idioma da interface",
  /* 361 */ "Idioma dos jogos",
  /* 362 */ "Idioma dos jogos: {0}. Valerá a partir da próxima execução.",
  /* 363 */ "Voltar",
  /* 364 */ "Buscar",
  /* 365 */ "Buscar as fichas",
  /* 366 */ "Buscar um valor",
  /* 367 */ "Diferente",
  /* 368 */ "Igual",
  /* 369 */ "Largura",
  /* 370 */ "O projeto libretro publica fichas de trapaça, uma por jogo. O EvaChi guarda apenas as que servem exatamente ao seu — mesmo título, mesma região, mesma revisão — e prefere não propor nada a propor algo aproximado: códigos escritos para outra versão não escrevem um pouco ao lado, escrevem em outro lugar.",
  /* 371 */ "As trapaças",
  /* 372 */ "Menos",
  /* 373 */ "Painel de trapaças",
  /* 374 */ "Mais",
  /* 375 */ "Recomeçar",
  /* 376 */ "Trapaças",
  /* 377 */ "Trapaças…",
  /* 378 */ "Valor",
  /* 379 */ "Vale",
  /* 380 */ "{0} endereços possíveis",
  /* 381 */ "{0} fichas instaladas, {1} removidas",
  /* 382 */ "{0} de {1} jogos têm ficha",
  /* 383 */ "{0} bytes de memória",
  /* 384 */ "{0} valores descartados: fora da memória deste jogo",
  /* 385 */ "Nenhuma ficha para este jogo. O painel « Trapaças… » do menu Emulação procura uma; na falta dela, a busca de valores funciona em qualquer jogo.",
  /* 386 */ "Congelada",
  /* 387 */ "Congelar",
  /* 388 */ "Jogue um pouco e diga depois o que o valor fez.",
  /* 389 */ "A partida foi guardada à parte antes da primeira trapaça.",
  /* 390 */ "Buscando…",
  /* 391 */ "O que for deixado em « drop u'r rom » vai para o console que a extensão indica. Quando vários consoles compartilham a mesma — as imagens de disco — o EvaChi pergunta em vez de apostar.",
  /* 392 */ "Confirmação",
  /* 393 */ "Apagar o save do jogo…",
  /* 394 */ "Esticamento",
  /* 395 */ "O jogo guarda suas contagens na memória sem dizer onde. Elas se encontram por eliminação: você diz o que o número na tela fez, e o EvaChi descarta os endereços que não fizeram o mesmo.",
  /* 396 */ "Sim",
  /* 397 */ "Poucos consoles têm as proporções de uma tela de hoje, daí as faixas pretas nas laterais. Em zero a imagem mantém suas proporções; em cem ela preenche a janela, mesmo esticada.",
  /* 398 */ "Organização dos jogos",
  /* 399 */ "Organizar",
  /* 400 */ "Organizar os jogos depositados…",
  /* 401 */ "Você vê 47 vidas: digite 47 em « Valor » e pressione « Buscar ». Perca uma, digite 46 e pressione « Vale ». Se o número não estiver escrito em lugar nenhum, deixe « Valor » vazio e diga apenas « Mais », « Menos », « Diferente » ou « Igual » entre dois momentos de jogo. Depois, « Congelar » mantém o valor encontrado. « Largura » é o tamanho do número: 1 até 255, 2 acima disso, 4 para os contadores grandes.",
  /* 402 */ "{0} organizados",
  /* 403 */ "nenhum save para apagar",
  /* 404 */ "Botões",
  /* 405 */ "Já está na biblioteca: {0}",
  /* 406 */ "Apagar o save de {0} e recomeçar do zero? A partida em andamento será encerrada, e o que o jogo tinha anotado será perdido.",
  /* 407 */ "Gatilhos",
  /* 408 */ "Manter os dois",
  /* 409 */ "Deixar no depósito",
  /* 410 */ "O depósito está vazio.",
  /* 411 */ "Substituir o slot {0}? O que estiver guardado nele será perdido.",
  /* 412 */ "save apagado — {0}",
  /* 413 */ "Sistema",
  /* 414 */ "Esvaziar o slot {0}? O que estiver guardado nele será perdido.",
  /* 415 */ "A zona morta é a parte da alavanca em que ela ainda é considerada em repouso. Pequena demais, o personagem anda sozinho com o controle largado na mesa; grande demais, os movimentos pequenos se perdem. Alguns jogos pedem para sacudir o console: quando o controle não sabe sentir isso, os dois botões abaixo fazem o jogo acreditar.",
  /* 416 */ "A alavanca",
  /* 417 */ "Os emuladores autônomos têm seus próprios botões, nos seus próprios arquivos. O que você mudar aqui é levado para lá na hora, para aqueles cujo formato conhecemos em primeira mão: PCSX2, PPSSPP e Dolphin. A configuração antiga é posta de lado na primeira passagem, com o mesmo nome seguido de « .avant-evachi ».",
  /* 418 */ "Levar aos emuladores externos",
  /* 419 */ "Zona morta",
  /* 420 */ "Sessão",
  /* 421 */ "Argila",
  /* 422 */ "nenhum emulador externo escreveu ainda suas configurações",
  /* 423 */ "Brasa",
  /* 424 */ "Cinza",
  /* 425 */ "Cereja",
  /* 426 */ "Coral",
  /* 427 */ "Baralho",
  /* 428 */ "Floresta",
  /* 429 */ "Geada",
  /* 430 */ "os emuladores externos já tinham esses botões",
  /* 431 */ "Meia-noite",
  /* 432 */ "Musgo",
  /* 433 */ "Neon",
  /* 434 */ "Ameixa",
  /* 435 */ "Areia",
  /* 436 */ "Sacudir",
  /* 437 */ "Sépia",
  /* 438 */ "botões levados: {0}",
  /* 439 */ "Turquesa",
  /* 440 */ "As capas seguras em leque, como uma mão de cartas. O pulso gira e a carta que se lê fica de pé.",
  /* 441 */ "Uma sala escura, um feixe cheio de poeira e o jogo projetado em grande. O resto espera no carrossel.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Damasco",
  /* 444 */ "Urze",
  /* 445 */ "Caramelo",
  /* 446 */ "Cobre",
  /* 447 */ "Tinta",
  /* 448 */ "Famicom",
  /* 449 */ "Jade",
  /* 450 */ "Mirtilo",
  /* 451 */ "Tempestade",
  /* 452 */ "Pérola",
  /* 453 */ "Pistache",
  /* 454 */ "Nenhum",
  /* 455 */ "Varredura",
  /* 456 */ "Cada pixel em três fendas: vermelha, verde e azul",
  /* 457 */ "A imagem do núcleo, pixel a pixel",
  /* 458 */ "O vidro abaulado, as linhas, as fendas e as bordas apagadas",
  /* 459 */ "Grade",
  /* 460 */ "Tubo de raios catódicos",
  /* 461 */ "Uma linha a cada duas escurecida, como numa televisão",
  /* 462 */ "Abre o emulador na própria janela, sem jogo",
  /* 463 */ "Abrir",
  /* 464 */ "Volume",
];
