/**
 * Portugais — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * numérotées en commentaire sont là pour qu'on puisse le vérifier à l'œil.
 */

export const pt: readonly string[] = [
  /* 1 */ "No comando",
  /* 2 */ "A iniciar · X favorito · L1/R1 consolas · L2/R2 letra · B voltar · Start",
  /* 3 */ "Acerca do EvaChi",
  /* 4 */ "Acerca…",
  /* 5 */ "Ainda por chegar: filtros de tubo de raios catódicos, grelha, varrimento. O lugar está pronto, os filtros virão para aqui.",
  /* 6 */ "Atualizar a biblioteca",
  /* 7 */ "Ver",
  /* 8 */ "Mostrar as capas dos jogos",
  /* 9 */ "Ajuda",
  /* 10 */ "Adicionar uma pasta de jogos…",
  /* 11 */ "Adicionar uma pasta…",
  /* 12 */ "Carregue num botão do comando: a tecla correspondente acende-se. Para mudar uma, passe à reatribuição, clique na tecla a alterar e depois carregue no botão que quiser.",
  /* 13 */ "Argumentos",
  /* 14 */ "No teclado",
  /* 15 */ "Nenhum jogo",
  /* 16 */ "Nenhum comando detetado.",
  /* 17 */ "Biblioteca",
  /* 18 */ "Sons de seleção no comando",
  /* 19 */ "Algumas consolas não arrancam sem o firmware de origem. O EvaChi não o pode fornecer: é código protegido por direitos de autor, que se copia da máquina que se possui. Diz-lhe, em contrapartida, qual falta, com que nome, e onde o deixar.",
  /* 20 */ "Estas consolas não têm núcleo libretro: o seu emulador é um programa à parte, que o EvaChi instala em casa e lança diretamente no jogo — sem passar pelo menu dele. Os jogos, as chaves e os ficheiros de sistema ficam a seu cargo.",
  /* 21 */ "Estas definições só tocam nos núcleos internos. Um emulador externo tem os seus, e o EvaChi não se mete neles.",
  /* 22 */ "Estes já não são propostos: não responderam à interrogação, ou deitaram o EvaChi abaixo. Restaurá-los não os reinstala — apenas os volta a pôr na lista.",
  /* 23 */ "Carregar o estado",
  /* 24 */ "Só para os núcleos internos. Clique num atalho e depois carregue na tecla ou no botão que quiser; no comando tomam-se dois botões ao mesmo tempo, porque cada um deles já serve ao jogo.",
  /* 25 */ "Controlos",
  /* 26 */ "Controlos…",
  /* 27 */ "Consolas recentes",
  /* 28 */ "Declarar outro emulador",
  /* 29 */ "Direções / stick esquerdo",
  /* 30 */ "Pastas de jogos",
  /* 31 */ "Pôr este emulador de parte",
  /* 32 */ "Vêm do servidor de miniaturas do projeto libretro, a pedido. Desmarcada, a biblioteca deixa de pedir seja o que for à rede.",
  /* 33 */ "Espaços de gravação",
  /* 34 */ "Espaços…",
  /* 35 */ "Emuladores",
  /* 36 */ "Emuladores postos de parte",
  /* 37 */ "Emuladores externos",
  /* 38 */ "Emuladores externos…",
  /* 39 */ "Emuladores…",
  /* 40 */ "Emulação",
  /* 41 */ "Durante a partida, voltar à biblioteca — dois botões ao mesmo tempo, porque cada um deles serve ao jogo",
  /* 42 */ "Guardar",
  /* 43 */ "Extensões",
  /* 44 */ "Fechar",
  /* 45 */ "Ficheiro",
  /* 46 */ "Ficheiros de sistema a instalar por si",
  /* 47 */ "Galeria",
  /* 48 */ "Gerir as pastas…",
  /* 49 */ "Gráficos",
  /* 50 */ "Gráficos…",
  /* 51 */ "Indique a pasta onde estão os seus jogos.",
  /* 52 */ "Instalação",
  /* 53 */ "Instalar a seleção",
  /* 54 */ "Instalar os emuladores…",
  /* 55 */ "Interpretador",
  /* 56 */ "Não é preciso saber onde: mostre a pasta onde tudo anda espalhado — BIOS, chaves, firmwares, arquivos, subpastas incluídas — e o EvaChi leva cada ficheiro ao sítio certo, tanto para os núcleos como para os emuladores autónomos. O que ninguém pede não é movido.",
  /* 57 */ "Capas",
  /* 58 */ "Registo",
  /* 59 */ "Registo…",
  /* 60 */ "A vez anterior acabou mal",
  /* 61 */ "Iniciar o jogo, confirmar",
  /* 62 */ "Idioma",
  /* 63 */ "A escolha fica guardada de um arranque para o outro. Cada um foi verificado como legível: o texto mantém em toda a parte contraste suficiente sobre o seu fundo.",
  /* 64 */ "Mantê-lo",
  /* 65 */ "Os emuladores abaixo já vêm configurados — argumentos e formatos incluídos. O EvaChi procura-os no seu disco; não os instala.",
  /* 66 */ "Atribuições de origem",
  /* 67 */ "Suavização",
  /* 68 */ "Pôr o jogo nos favoritos, ou tirá-lo de lá",
  /* 69 */ "Música do menu animado",
  /* 70 */ "Nome",
  /* 71 */ "Abrir a barra de menus",
  /* 72 */ "Abrir a pasta",
  /* 73 */ "Abrir a pasta…",
  /* 74 */ "Abrir um jogo…",
  /* 75 */ "por fotograma",
  /* 76 */ "Definições do núcleo",
  /* 77 */ "Definições do núcleo…",
  /* 78 */ "Percorrer a biblioteca, as janelas e a barra de menus",
  /* 79 */ "Procurar…",
  /* 80 */ "Pausa",
  /* 81 */ "Ecrã inteiro",
  /* 82 */ "Para as consolas sem núcleo libretro. O EvaChi lança o programa com o jogo como argumento: o emulador arranca diretamente na partida, sem passar pelo seu próprio menu.",
  /* 83 */ "Tirar uma captura",
  /* 84 */ "Apresentação",
  /* 85 */ "Pronto",
  /* 86 */ "Programa",
  /* 87 */ "Uns acordes sustidos e notas esparsas, compostos à medida em vez de gravados: a peça nunca volta a passar no mesmo sítio. Para-se por si assim que um jogo arranca.",
  /* 88 */ "Arrumar uma pasta…",
  /* 89 */ "Reatribuir…",
  /* 90 */ "Procurar um jogo…",
  /* 91 */ "Repor",
  /* 92 */ "Voltar à biblioteca",
  /* 93 */ "Voltar atrás, fechar",
  /* 94 */ "Gravação rápida",
  /* 95 */ "Guardar o estado",
  /* 96 */ "Shaders",
  /* 97 */ "Som",
  /* 98 */ "Start",
  /* 99 */ "Tamanho da imagem",
  /* 100 */ "Temas",
  /* 101 */ "Temas…",
  /* 102 */ "Um só ficheiro…",
  /* 103 */ "Um tique breve ao mudar de jogo, outro ao lançá-lo. Só no comando: com o rato e o teclado, o gesto já se sente.",
  /* 104 */ "Velocidade",
  /* 105 */ "Ver as capturas…",
  /* 106 */ "Pode instalar só uma parte — na biblioteca aparecem apenas as consolas cujo emulador está instalado.",
  /* 107 */ "{0} — carregado",
  /* 108 */ "{0} — clique direito para apagar",
  /* 109 */ "{0} — posto nos favoritos",
  /* 110 */ "{0} — reposto",
  /* 111 */ "{0} — retirado dos favoritos",
  /* 112 */ "{0} — a transferir…",
  /* 113 */ "{0}: falhou, ver o registo",
  /* 114 */ "{0} à disposição",
  /* 115 */ "{0} guardado",
  /* 116 */ "{0} é um emulador externo: lança-se, não se aloja",
  /* 117 */ "{0} img/s",
  /* 118 */ "{0} instalado",
  /* 119 */ "{0} instalado — {1}",
  /* 120 */ "{0} instalado e pronto",
  /* 121 */ "{0} instalados, {1} falhados — ver o registo",
  /* 122 */ "{0} restaurado",
  /* 123 */ "{0} retirado",
  /* 124 */ "{0} de {1}",
  /* 125 */ "{0} no disco, mas nenhum núcleo instalado o abre.",
  /* 126 */ "a tirar de {0}, depois «Procurar…»",
  /* 127 */ "por transferir",
  /* 128 */ "ausente, facultativo",
  /* 129 */ "Ativar",
  /* 130 */ "Suavizado",
  /* 131 */ "adição impossível — {0}",
  /* 132 */ "Ajustar",
  /* 133 */ "Âmbar",
  /* 134 */ "Ardósia",
  /* 135 */ "paragem — {0}",
  /* 136 */ "paragem brusca na vez anterior — {0}",
  /* 137 */ "nenhum",
  /* 138 */ "nenhum núcleo devolvido quando {0} eram conhecidos — lista anterior conservada",
  /* 139 */ "nenhum emulador",
  /* 140 */ "Nenhum emulador instalado",
  /* 141 */ "Nenhum jogo reconhecido",
  /* 142 */ "Nenhum resultado",
  /* 143 */ "nenhum",
  /* 144 */ "biblioteca ilegível — {0}",
  /* 145 */ "ligado",
  /* 146 */ "captura",
  /* 147 */ "Mudar a capa…",
  /* 148 */ "Mudar…",
  /* 149 */ "Cada pixel em nove",
  /* 150 */ "Cada pixel em quatro: nítido, sem deformação",
  /* 151 */ "Cada pixel em dezasseis — para os ecrãs grandes",
  /* 152 */ "Carregar",
  /* 153 */ "Escolher uma capa…",
  /* 154 */ "escolha primeiro um jogo na biblioteca",
  /* 155 */ "núcleo: {0}",
  /* 156 */ "núcleo não instalado",
  /* 157 */ "Núcleos instalados",
  /* 158 */ "núcleos libretro",
  /* 159 */ "Contraste elevado",
  /* 160 */ "invólucro nativo: {0}",
  /* 161 */ "descarregamento incompleto — {0}",
  /* 162 */ "descoberta: {0}",
  /* 163 */ "descoberta interrompida — {0}",
  /* 164 */ "Indicar à mão o programa de {0}",
  /* 165 */ "pasta adicionada: {0}",
  /* 166 */ "pasta aberta: {0}",
  /* 167 */ "Pasta predefinida",
  /* 168 */ "Pastas adicionadas",
  /* 169 */ "Esc",
  /* 170 */ "Espaço {0}",
  /* 171 */ "espaço {0} — {1}",
  /* 172 */ "Emulador usado para esta pasta",
  /* 173 */ "emuladores externos",
  /* 174 */ "em uso",
  /* 175 */ "no lugar",
  /* 176 */ "gravação impossível — {0}",
  /* 177 */ "Enter",
  /* 178 */ "O EvaChi pode transferi-los da forja oficial libretro. Escolha as consolas que lhe interessam.",
  /* 179 */ "O EvaChi parou ao lançar «{0}», com o emulador {1}.",
  /* 180 */ "O EvaChi parou, com o emulador {0}.",
  /* 181 */ "external_systems → {0} emuladores declarados",
  /* 182 */ "Favorito",
  /* 183 */ "Favoritos",
  /* 184 */ "ficheiros de sistema ilegíveis — {0}",
  /* 185 */ "Setas",
  /* 186 */ "Game Boy",
  /* 187 */ "Grelha",
  /* 188 */ "{0} em falta em consolas instaladas",
  /* 189 */ "instalação terminada: {0}",
  /* 190 */ "A instalar…",
  /* 191 */ "instalado",
  /* 192 */ "instalado pelo EvaChi",
  /* 193 */ "Instalar",
  /* 194 */ "interpretador: {0}",
  /* 195 */ "interrogação dos núcleos instalados…",
  /* 196 */ "Iniciar",
  /* 197 */ "Iniciar o jogo escolhido",
  /* 198 */ "Lavanda",
  /* 199 */ "As consolas em fila, os jogos em coluna, um fundo que ondula. À maneira das consolas de sala.",
  /* 200 */ "Os contornos ficam esbatidos — mais perto de um televisor antigo",
  /* 201 */ "As capas em grande, percorridas com o comando. Pensado para o sofá.",
  /* 202 */ "Os pixels mantêm-se quadrados, como na máquina de origem",
  /* 203 */ "atribuições do comando repostas de origem",
  /* 204 */ "list_cores → {0} núcleos anunciados",
  /* 205 */ "Lista",
  /* 206 */ "lista dos núcleos indisponível — {0}",
  /* 207 */ "lista dos emuladores indisponível — {0}",
  /* 208 */ "Comando",
  /* 209 */ "comando: {0}",
  /* 210 */ "Comando: {0}",
  /* 211 */ "comando desligado",
  /* 212 */ "EM FALTA",
  /* 213 */ "Menta",
  /* 214 */ "Menu animado",
  /* 215 */ "Atualizar",
  /* 216 */ "Pôr nos favoritos",
  /* 217 */ "posto de parte: {0} · {1}",
  /* 218 */ "menos de um minuto",
  /* 219 */ "Nítido",
  /* 220 */ "nome, programa e extensões são todos necessários",
  /* 221 */ "NÃO",
  /* 222 */ "não instalado nesta máquina",
  /* 223 */ "Noite rosa",
  /* 224 */ "Oceano",
  /* 225 */ "ou",
  /* 226 */ "sim",
  /* 227 */ "abertura impossível — {0}",
  /* 228 */ "página web: só os núcleos internos estão disponíveis, sem biblioteca",
  /* 229 */ "Papel",
  /* 230 */ "predefinido",
  /* 231 */ "Percorrer a grelha e o menu animado",
  /* 232 */ "ecrã inteiro recusado — {0}",
  /* 233 */ "carregue no botão que quiser no comando",
  /* 234 */ "carregue numa tecla…",
  /* 235 */ "arrumação: {0} · {1}",
  /* 236 */ "arrumação impossível — {0}",
  /* 237 */ "procura dos emuladores interrompida — {0}",
  /* 238 */ "Fechar uma janela",
  /* 239 */ "reposição impossível — {0}",
  /* 240 */ "Enche a janela mantendo as proporções",
  /* 241 */ "Retomar",
  /* 242 */ "Retomar esta gravação — clique direito para a esvaziar",
  /* 243 */ "Restaurar",
  /* 244 */ "restauro impossível — {0}",
  /* 245 */ "Retirar",
  /* 246 */ "Retirar dos favoritos",
  /* 247 */ "Retirar a capa",
  /* 248 */ "remoção impossível — {0}",
  /* 249 */ "nada para arrumar",
  /* 250 */ "nada bloqueia",
  /* 251 */ "Nada corresponde a «{0}».",
  /* 252 */ "Rosa e branco",
  /* 253 */ "sem imagem",
  /* 254 */ "Guardar",
  /* 255 */ "Guardar aqui",
  /* 256 */ "seleção impossível — {0}",
  /* 257 */ "Tamanho de origem da consola, ao pixel",
  /* 258 */ "Terminar",
  /* 259 */ "tema claro",
  /* 260 */ "tema escuro",
  /* 261 */ "está tudo instalado",
  /* 262 */ "encontrado: {0}",
  /* 263 */ "Uma secção por consola, em tabela. O mais denso com o rato.",
  /* 264 */ "vazio",
  /* 265 */ "a pôr aqui, como os romsets dos jogos: o FinalBurn Neo só procura nesta pasta",
  /* 266 */ "acrescenta o ecrã inicial da consola",
  /* 267 */ "arranque da máquina",
  /* 268 */ "muitos jogos arrancam sem ele; o menu da consola não",
  /* 269 */ "BIOS americana",
  /* 270 */ "BIOS americana e europeia",
  /* 271 */ "BIOS europeia",
  /* 272 */ "BIOS japonesa",
  /* 273 */ "chaves de desencriptação; sem elas um depósito encriptado é recusado",
  /* 274 */ "pasta das máquinas da distribuição blueMSX, com Databases ao lado",
  /* 275 */ "idem",
  /* 276 */ "indispensável aos jogos em CD, inútil para os cartões HuCard",
  /* 277 */ "indispensável aos jogos Mega-CD, inútil para os cartuchos",
  /* 278 */ "Kickstart 1.3; sem ela o PUAE recorre ao AROS, livre mas menos compatível",
  /* 279 */ "Kickstart 3.1; necessária aos jogos AGA, que o A500 não consegue correr",
  /* 280 */ "o melonDS emula a BIOS por predefinição; a verdadeira é mais fiel",
  /* 281 */ "o mGBA passa sem ela; alguns jogos exigem-na para o seu ecrã inicial",
  /* 282 */ "firmware da consola",
  /* 283 */ "firmware da máquina",
  /* 284 */ "firmware Panasonic FZ-10; é este o nome que o Opera toma por predefinição",
  /* 285 */ "modificado pelo melonDS, que guarda o original em .bak",
  /* 286 */ "tipos de letra",
  /* 287 */ "definições e data da consola",
  /* 288 */ "sem ele o núcleo corre mas o ecrã fica preto",
  /* 289 */ "tabela de caracteres da consola",
  /* 290 */ "variante americana, para os jogos Sega CD dos Estados Unidos",
  /* 291 */ "variante japonesa, para os jogos Mega-CD japoneses",
  /* 292 */ "capturas",
  /* 293 */ "capturas",
  /* 294 */ "captura",
  /* 295 */ "capturas",
  /* 296 */ "capturas",
  /* 297 */ "capturas",
  /* 298 */ "núcleos",
  /* 299 */ "núcleos",
  /* 300 */ "núcleo",
  /* 301 */ "núcleos",
  /* 302 */ "núcleos",
  /* 303 */ "núcleos",
  /* 304 */ "emuladores",
  /* 305 */ "emuladores",
  /* 306 */ "emulador",
  /* 307 */ "emuladores",
  /* 308 */ "emuladores",
  /* 309 */ "emuladores",
  /* 310 */ "ficheiros",
  /* 311 */ "ficheiros",
  /* 312 */ "ficheiro",
  /* 313 */ "ficheiros",
  /* 314 */ "ficheiros",
  /* 315 */ "ficheiros",
  /* 316 */ "jogos",
  /* 317 */ "jogos",
  /* 318 */ "jogo",
  /* 319 */ "jogos",
  /* 320 */ "jogos",
  /* 321 */ "jogos",
  /* 322 */ "<code>{rom}</code> será substituído pelo caminho do jogo. Sem ele, o caminho é acrescentado no fim — que é o que a maioria dos emuladores espera.",
  /* 323 */ "<strong>Fora do jogo, tudo se faz com o comando:</strong> as direções percorrem a biblioteca, as janelas e a barra de menus; <strong>A</strong> confirma, <strong>B</strong> volta atrás, <strong>Start</strong> abre a barra de menus. Durante a partida, <strong>Select e Start juntos</strong> trazem de volta à biblioteca — dois botões ao mesmo tempo, porque cada um deles serve ao jogo.",
  /* 324 */ "Nenhuma captura. Carregue em <strong>F12</strong> durante a partida, ou em <strong>Select + Y</strong> no comando.",
  /* 325 */ "Cada consola precisa do seu emulador. O EvaChi vai buscá-los à forja oficial do projeto libretro, <code>buildbot.libretro.com</code>, e instala-os na sua própria pasta. Nada é redistribuído: são as versões publicadas pelos seus autores.",
  /* 326 */ "Quatro espaços por jogo, guardados no disco. O espaço a negrito é o que usam <strong>F2</strong> e <strong>F4</strong> — e <strong>Select + L1</strong> / <strong>Select + R1</strong> no comando. Clique direito num espaço para o esvaziar.",
  /* 327 */ "Um emulador corre na mesma janela que o EvaChi: quando cai, leva-a consigo, sem aviso. Pôr este emulador de parte deixa-o instalado mas deixa de o propor. Poderá restaurá-lo a qualquer momento em <strong>Ficheiro → Emuladores</strong>, no fundo da janela.",
  /* 328 */ "Um só ficheiro por jogo no disco <small> Um jogo em CD chega numa folha <code>.cue</code> e em tantos ficheiros <code>.bin</code> quantas as faixas que o disco tinha. Só a folha se lança: as faixas ficam escondidas quando ela está lá. Sem folha, nada fica escondido. </small>",
  /* 329 */ "(vazio) ou --fullscreen {rom}",
];
