/**
 * Roumain — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les marques
 * numérotées en commentaire sont là pour qu'on puisse le vérifier à l'œil.
 */

export const ro: readonly string[] = [
  /* 1 */ "Cu controlerul",
  /* 2 */ "A pornește · X favorit · Y reîncadrează · L1/R1 console · L2/R2 literă · B înapoi",
  /* 3 */ "Despre EvaChi",
  /* 4 */ "Despre…",
  /* 5 */ "În curând: filtre de tub catodic, grilaj, linii de scanare. Locul e pregătit, filtrele vor veni aici.",
  /* 6 */ "Actualizează biblioteca",
  /* 7 */ "Vizualizare",
  /* 8 */ "Arată coperțile jocurilor",
  /* 9 */ "Ajutor",
  /* 10 */ "Adaugă un folder cu jocuri…",
  /* 11 */ "Adaugă un folder…",
  /* 12 */ "Apasă un buton al controlerului: tasta care îi răspunde se aprinde. Ca să schimbi una, treci în reatribuire, dă clic pe tasta de schimbat, apoi apasă butonul dorit.",
  /* 13 */ "Argumente",
  /* 14 */ "Cu tastatura",
  /* 15 */ "Niciun joc",
  /* 16 */ "Niciun controler găsit.",
  /* 17 */ "Bibliotecă",
  /* 18 */ "Sunete de selecție la controler",
  /* 19 */ "Unele console nu pornesc fără firmware-ul lor original. EvaChi nu ți-l poate da: e cod protejat de drepturi de autor, care se copiază de pe mașina pe care o ai. În schimb, îți spune care lipsește, sub ce nume și unde să-l pui.",
  /* 20 */ "Aceste console nu au un nucleu libretro: emulatorul lor e un program separat, pe care EvaChi îl instalează la ea și îl pornește direct în joc — fără să treacă prin meniul lui. Jocurile, cheile și fișierele de sistem rămân în grija ta.",
  /* 21 */ "Aceste setări privesc doar nucleele interne. Un emulator extern le are pe ale lui, iar EvaChi nu se amestecă.",
  /* 22 */ "Acestea nu mai sunt propuse: fie nu au răspuns la interogare, fie au făcut EvaChi să cadă. Restabilirea lor nu le reinstalează — doar le pune la loc în listă.",
  /* 23 */ "Încarcă starea",
  /* 24 */ "Doar nucleele interne. Dă clic pe o scurtătură, apoi apasă tasta sau butonul dorit; la controler se iau două butoane deodată, fiindcă fiecare dintre ele slujește deja jocului.",
  /* 25 */ "Comenzi",
  /* 26 */ "Comenzi…",
  /* 27 */ "Console recente",
  /* 28 */ "Declară un alt emulator",
  /* 29 */ "Direcții / stick stâng",
  /* 30 */ "Foldere cu jocuri",
  /* 31 */ "Lasă deoparte acest emulator",
  /* 32 */ "Vin de pe serverul de miniaturi al proiectului libretro, la cerere. Debifată, biblioteca nu mai cere nimic din rețea.",
  /* 33 */ "Sloturi de salvare",
  /* 34 */ "Sloturi…",
  /* 35 */ "Emulatoare",
  /* 36 */ "Emulatoare lăsate deoparte",
  /* 37 */ "Emulatoare externe",
  /* 38 */ "Emulatoare externe…",
  /* 39 */ "Emulatoare…",
  /* 40 */ "Emulare",
  /* 41 */ "În timpul partidei, întoarcerea la bibliotecă — două butoane deodată, fiindcă fiecare dintre ele slujește jocului",
  /* 42 */ "Salvează",
  /* 43 */ "Extensii",
  /* 44 */ "Închide",
  /* 45 */ "Fișier",
  /* 46 */ "Fișiere de sistem de pus singur",
  /* 47 */ "Galerie",
  /* 48 */ "Gestionează folderele…",
  /* 49 */ "Grafică",
  /* 50 */ "Grafică…",
  /* 51 */ "Arată folderul în care se află jocurile tale.",
  /* 52 */ "Instalare",
  /* 53 */ "Instalează selecția",
  /* 54 */ "Instalează emulatoarele…",
  /* 55 */ "Interpretor",
  /* 56 */ "Nu trebuie să știi unde: arată folderul în care zace totul — BIOS-uri, chei, firmware, arhive, subfoldere cu tot — și EvaChi duce fiecare fișier la locul potrivit, atât pentru nuclee, cât și pentru emulatoarele autonome. Ce nu cere nimeni rămâne pe loc.",
  /* 57 */ "Coperți",
  /* 58 */ "Jurnal",
  /* 59 */ "Jurnal…",
  /* 60 */ "Data trecută s-a terminat prost",
  /* 61 */ "Pornește jocul, confirmă",
  /* 62 */ "Limbă",
  /* 63 */ "Alegerea se păstrează de la o pornire la alta. Fiecare a fost verificată că se citește: textul păstrează peste tot un contrast destul de bun față de fundal.",
  /* 64 */ "Păstrează-l",
  /* 65 */ "Emulatoarele de mai jos sunt deja configurate — argumente și formate cu tot. EvaChi le caută pe discul tău; nu le instalează.",
  /* 66 */ "Legături inițiale",
  /* 67 */ "Netezire",
  /* 68 */ "Pune jocul la favorite sau scoate-l de acolo",
  /* 69 */ "Muzica meniului animat",
  /* 70 */ "Nume",
  /* 71 */ "Deschide bara de meniuri",
  /* 72 */ "Deschide folderul",
  /* 73 */ "Deschide folderul…",
  /* 74 */ "Deschide un joc…",
  /* 75 */ "pe cadru",
  /* 76 */ "Setările nucleului",
  /* 77 */ "Setările nucleului…",
  /* 78 */ "Parcurge biblioteca, ferestrele și bara de meniuri",
  /* 79 */ "Răsfoiește…",
  /* 80 */ "Pauză",
  /* 81 */ "Ecran complet",
  /* 82 */ "Pentru consolele fără nucleu libretro. EvaChi pornește programul cu jocul ca argument: emulatorul intră direct în partidă, fără să treacă prin propriul meniu.",
  /* 83 */ "Fă o captură",
  /* 84 */ "Prezentare",
  /* 85 */ "Gata",
  /* 86 */ "Program",
  /* 87 */ "Câteva acorduri ținute și note răzlețe, compuse pe loc, nu înregistrate: bucata nu trece niciodată de două ori prin același loc. Se oprește singură de îndată ce pornește un joc.",
  /* 88 */ "Rânduiește un folder…",
  /* 89 */ "Reatribuie…",
  /* 90 */ "Caută un joc…",
  /* 91 */ "Resetează",
  /* 92 */ "Înapoi la bibliotecă",
  /* 93 */ "Mergi înapoi, închide",
  /* 94 */ "Salvare rapidă",
  /* 95 */ "Salvează starea",
  /* 96 */ "Shaders",
  /* 97 */ "Sunet",
  /* 98 */ "Start",
  /* 99 */ "Mărimea imaginii",
  /* 100 */ "Teme",
  /* 101 */ "Teme…",
  /* 102 */ "Un singur fișier…",
  /* 103 */ "Un ticăit scurt când schimbi jocul, altul când îl pornești. Doar la controler: la mouse și la tastatură, gestul se simte deja.",
  /* 104 */ "Viteză",
  /* 105 */ "Vezi capturile…",
  /* 106 */ "Poți instala doar o parte dintre ele — în bibliotecă apar numai consolele al căror emulator e instalat.",
  /* 107 */ "{0} — încărcat",
  /* 108 */ "{0} — clic dreapta ca să golești",
  /* 109 */ "{0} — pus la favorite",
  /* 110 */ "{0} — resetat",
  /* 111 */ "{0} — scos de la favorite",
  /* 112 */ "{0} — se descarcă…",
  /* 113 */ "{0}: a eșuat, vezi jurnalul",
  /* 114 */ "{0} la dispoziție",
  /* 115 */ "{0} salvat",
  /* 116 */ "{0} e un emulator extern: se pornește, nu se găzduiește",
  /* 117 */ "{0} cadre/s",
  /* 118 */ "{0} instalat",
  /* 119 */ "{0} instalat — {1}",
  /* 120 */ "{0} instalat și gata",
  /* 121 */ "{0} instalate, {1} eșuate — vezi jurnalul",
  /* 122 */ "{0} restabilit",
  /* 123 */ "{0} scos",
  /* 124 */ "{0} din {1}",
  /* 125 */ "{0} pe disc, dar niciun nucleu instalat nu le deschide.",
  /* 126 */ "de luat de pe {0}, apoi „Răsfoiește…”",
  /* 127 */ "de descărcat",
  /* 128 */ "lipsă, opțional",
  /* 129 */ "Activează",
  /* 130 */ "Estompat",
  /* 131 */ "nu s-a putut adăuga — {0}",
  /* 132 */ "Ajustare",
  /* 133 */ "Chihlimbar",
  /* 134 */ "Ardezie",
  /* 135 */ "oprire — {0}",
  /* 136 */ "oprire brutală data trecută — {0}",
  /* 137 */ "niciunul",
  /* 138 */ "niciun nucleu întors, deși {0} erau cunoscute — s-a păstrat lista de dinainte",
  /* 139 */ "niciun emulator",
  /* 140 */ "Niciun emulator instalat",
  /* 141 */ "Niciun joc recunoscut",
  /* 142 */ "Niciun rezultat",
  /* 143 */ "niciuna",
  /* 144 */ "bibliotecă ilizibilă — {0}",
  /* 145 */ "conectat",
  /* 146 */ "captură",
  /* 147 */ "Schimbă coperta…",
  /* 148 */ "Schimbă…",
  /* 149 */ "Fiecare pixel pe nouă",
  /* 150 */ "Fiecare pixel pe patru: clar, fără deformare",
  /* 151 */ "Fiecare pixel pe șaisprezece — pentru ecranele mari",
  /* 152 */ "Încarcă",
  /* 153 */ "Alege o copertă…",
  /* 154 */ "alege întâi un joc din bibliotecă",
  /* 155 */ "nucleu: {0}",
  /* 156 */ "nucleu neinstalat",
  /* 157 */ "Nuclee instalate",
  /* 158 */ "nuclee libretro",
  /* 159 */ "Contrast ridicat",
  /* 160 */ "carcasă nativă: {0}",
  /* 161 */ "eliberare incompletă — {0}",
  /* 162 */ "descoperire: {0}",
  /* 163 */ "descoperire întreruptă — {0}",
  /* 164 */ "Arată tu programul pentru {0}",
  /* 165 */ "folder adăugat: {0}",
  /* 166 */ "folder deschis: {0}",
  /* 167 */ "Folder implicit",
  /* 168 */ "Foldere adăugate",
  /* 169 */ "Esc",
  /* 170 */ "Slotul {0}",
  /* 171 */ "slotul {0} — {1}",
  /* 172 */ "Emulatorul folosit pentru acest folder",
  /* 173 */ "emulatoare externe",
  /* 174 */ "în curs",
  /* 175 */ "la locul lui",
  /* 176 */ "nu s-a putut salva — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi le poate descărca de pe serverul oficial libretro. Alege consolele care te interesează.",
  /* 179 */ "EvaChi s-a oprit pornind „{0}”, cu emulatorul {1}.",
  /* 180 */ "EvaChi s-a oprit, cu emulatorul {0}.",
  /* 181 */ "external_systems → {0} emulatoare declarate",
  /* 182 */ "Favorit",
  /* 183 */ "Favorite",
  /* 184 */ "fișiere de sistem ilizibile — {0}",
  /* 185 */ "Săgeți",
  /* 186 */ "Game Boy",
  /* 187 */ "Grilă",
  /* 188 */ "{0} lipsesc unor console instalate",
  /* 189 */ "instalare încheiată: {0}",
  /* 190 */ "Se instalează…",
  /* 191 */ "instalat",
  /* 192 */ "instalat de EvaChi",
  /* 193 */ "Instalează",
  /* 194 */ "interpretor: {0}",
  /* 195 */ "se interoghează nucleele instalate…",
  /* 196 */ "Pornește",
  /* 197 */ "Pornește jocul ales",
  /* 198 */ "Lavandă",
  /* 199 */ "Consolele pe un rând, jocurile pe o coloană, un fundal care unduiește. Ca la o consolă de living.",
  /* 200 */ "Contururile se topesc — mai aproape de un televizor vechi",
  /* 201 */ "Coperțile mari, răsfoite cu controlerul. Gândit pentru canapea.",
  /* 202 */ "Pixelii rămân pătrați, ca pe mașina de la început",
  /* 203 */ "legăturile controlerului readuse la cele inițiale",
  /* 204 */ "list_cores → {0} nuclee anunțate",
  /* 205 */ "Listă",
  /* 206 */ "lista nucleelor nu e disponibilă — {0}",
  /* 207 */ "lista emulatoarelor nu e disponibilă — {0}",
  /* 208 */ "Controler",
  /* 209 */ "controler: {0}",
  /* 210 */ "Controler: {0}",
  /* 211 */ "controler deconectat",
  /* 212 */ "LIPSĂ",
  /* 213 */ "Mentă",
  /* 214 */ "Meniu animat",
  /* 215 */ "Actualizează",
  /* 216 */ "Pune la favorite",
  /* 217 */ "lăsat deoparte: {0} · {1}",
  /* 218 */ "mai puțin de un minut",
  /* 219 */ "Clar",
  /* 220 */ "numele, programul și extensiile sunt toate necesare",
  /* 221 */ "NU",
  /* 222 */ "neinstalat pe această mașină",
  /* 223 */ "Noapte roz",
  /* 224 */ "Ocean",
  /* 225 */ "sau",
  /* 226 */ "da",
  /* 227 */ "nu s-a putut deschide — {0}",
  /* 228 */ "pagină web: doar nucleele interne sunt la îndemână, fără bibliotecă",
  /* 229 */ "Hârtie",
  /* 230 */ "implicit",
  /* 231 */ "Parcurge grila și meniul animat",
  /* 232 */ "ecran complet refuzat — {0}",
  /* 233 */ "apasă butonul dorit pe controler",
  /* 234 */ "apasă o tastă…",
  /* 235 */ "rânduire: {0} · {1}",
  /* 236 */ "nu s-a putut rândui — {0}",
  /* 237 */ "căutarea emulatoarelor a fost întreruptă — {0}",
  /* 238 */ "Închide o fereastră",
  /* 239 */ "nu s-a putut reseta — {0}",
  /* 240 */ "Umple fereastra păstrând proporțiile",
  /* 241 */ "Reia",
  /* 242 */ "Reia această salvare — clic dreapta ca s-o golești",
  /* 243 */ "Restabilește",
  /* 244 */ "nu s-a putut restabili — {0}",
  /* 245 */ "Scoate",
  /* 246 */ "Scoate de la favorite",
  /* 247 */ "Scoate coperta",
  /* 248 */ "nu s-a putut scoate — {0}",
  /* 249 */ "nimic de rânduit",
  /* 250 */ "nimic nu stă în cale",
  /* 251 */ "Nimic nu se potrivește cu „{0}”.",
  /* 252 */ "Roz și alb",
  /* 253 */ "fără imagine",
  /* 254 */ "Salvează",
  /* 255 */ "Salvează aici",
  /* 256 */ "nu s-a putut alege — {0}",
  /* 257 */ "Mărimea de la început a consolei, pixel cu pixel",
  /* 258 */ "Încheie",
  /* 259 */ "temă deschisă",
  /* 260 */ "temă închisă",
  /* 261 */ "totul e instalat",
  /* 262 */ "găsit: {0}",
  /* 263 */ "Un panou pentru fiecare consolă, în tabel. Cel mai dens la mouse.",
  /* 264 */ "gol",
  /* 265 */ "de pus aici, ca romset-urile de jocuri: FinalBurn Neo caută doar în acest folder",
  /* 266 */ "adaugă ecranul de pornire al consolei",
  /* 267 */ "codul de pornire al mașinii",
  /* 268 */ "multe jocuri pornesc fără el; meniul consolei nu",
  /* 269 */ "BIOS american",
  /* 270 */ "BIOS american și european",
  /* 271 */ "BIOS european",
  /* 272 */ "BIOS japonez",
  /* 273 */ "chei de decriptare; fără ele, un depozit criptat e refuzat",
  /* 274 */ "folderul cu mașinile din distribuția blueMSX, cu Databases alături",
  /* 275 */ "la fel",
  /* 276 */ "neapărat pentru jocurile pe CD, de prisos pentru cardurile HuCard",
  /* 277 */ "neapărat pentru jocurile Mega-CD, de prisos pentru cartușe",
  /* 278 */ "Kickstart 1.3; altfel, PUAE se mulțumește cu AROS, liber, dar mai puțin compatibil",
  /* 279 */ "Kickstart 3.1; necesar jocurilor AGA, pe care A500 nu le poate rula",
  /* 280 */ "melonDS emulează BIOS-ul în mod implicit; cel adevărat e mai fidel",
  /* 281 */ "mGBA se descurcă fără el; câteva jocuri îl cer pentru ecranul lor de pornire",
  /* 282 */ "firmware-ul consolei",
  /* 283 */ "firmware-ul mașinii",
  /* 284 */ "firmware Panasonic FZ-10; acesta e numele pe care Opera îl ia implicit",
  /* 285 */ "schimbat de melonDS, care păstrează originalul în .bak",
  /* 286 */ "fonturi",
  /* 287 */ "setările și data consolei",
  /* 288 */ "fără el, nucleul merge, dar ecranul rămâne negru",
  /* 289 */ "tabela de caractere a consolei",
  /* 290 */ "variantă americană, pentru jocurile Sega CD din Statele Unite",
  /* 291 */ "variantă japoneză, pentru jocurile Mega-CD japoneze",
  /* 292 */ "capturi",
  /* 293 */ "de capturi",
  /* 294 */ "captură",
  /* 295 */ "de capturi",
  /* 296 */ "capturi",
  /* 297 */ "capturi",
  /* 298 */ "nuclee",
  /* 299 */ "de nuclee",
  /* 300 */ "nucleu",
  /* 301 */ "de nuclee",
  /* 302 */ "nuclee",
  /* 303 */ "nuclee",
  /* 304 */ "emulatoare",
  /* 305 */ "de emulatoare",
  /* 306 */ "emulator",
  /* 307 */ "de emulatoare",
  /* 308 */ "emulatoare",
  /* 309 */ "emulatoare",
  /* 310 */ "fișiere",
  /* 311 */ "de fișiere",
  /* 312 */ "fișier",
  /* 313 */ "de fișiere",
  /* 314 */ "fișiere",
  /* 315 */ "fișiere",
  /* 316 */ "jocuri",
  /* 317 */ "de jocuri",
  /* 318 */ "joc",
  /* 319 */ "de jocuri",
  /* 320 */ "jocuri",
  /* 321 */ "jocuri",
  /* 322 */ "<code>{rom}</code> va fi înlocuit cu calea jocului. Fără el, calea se adaugă la sfârșit — ce așteaptă majoritatea emulatoarelor.",
  /* 323 */ "<strong>În afara jocului, totul se face la controler:</strong> direcțiile parcurg biblioteca, ferestrele și bara de meniuri; <strong>A</strong> confirmă, <strong>B</strong> te duce înapoi, <strong>Start</strong> deschide bara de meniuri. În timpul partidei, <strong>Select și Start deodată</strong> te aduc la bibliotecă — două butoane deodată, fiindcă fiecare dintre ele slujește jocului.",
  /* 324 */ "Nicio captură. Apasă <strong>F12</strong> în timpul partidei sau <strong>Select + Y</strong> la controler.",
  /* 325 */ "Fiecare consolă are nevoie de emulatorul ei. EvaChi le aduce de pe serverul oficial al proiectului libretro, <code>buildbot.libretro.com</code>, și le instalează în folderul ei. Nimic nu e redistribuit: sunt versiunile publicate de autorii lor.",
  /* 326 */ "Patru sloturi pentru fiecare joc, ținute pe disc. Slotul îngroșat e cel pe care îl folosesc <strong>F2</strong> și <strong>F4</strong> — și <strong>Select + L1</strong> / <strong>Select + R1</strong> la controler. Clic dreapta pe un slot ca să-l golești.",
  /* 327 */ "Fiecare emulator rulează în propriul proces: când cade, EvaChi îl vede și se întoarce la bibliotecă. Partida în curs e pierdută, iar salvarea jocului poate să nu fi fost scrisă. Dacă îl lași deoparte, rămâne instalat, dar nu mai e propus. Îl poți restabili oricând din <strong>Fișier → Emulatoare</strong>, în josul ferestrei.",
  /* 328 */ "Un singur fișier pentru fiecare joc pe disc <small> Un joc pe CD vine cu o filă <code>.cue</code> și cu atâtea fișiere <code>.bin</code> câte piste avea discul. Se pornește doar fila: pistele sunt ascunse când ea e acolo. Fără filă, nu se ascunde nimic. </small>",
  /* 329 */ "(gol) sau --fullscreen {rom}",
  /* 330 */ "O sută la sută este viteza consolei. Mai jos jocul încetinește, mai sus zboară — iar sunetul îl urmează, mai grav sau mai ascuțit. Pe controler, stânga și dreapta trec de la o treaptă la următoarea. Doar nucleele interne: un emulator extern își păstrează propria viteză.",
  /* 331 */ "Cinci console deodată",
  /* 332 */ "Cruce direcțională",
  /* 333 */ "De la o inițială la următoarea",
  /* 334 */ "În meniul animat, cinci jocuri deodată",
  /* 335 */ "Viteza jocului",
  /* 336 */ "Anulează",
  /* 337 */ "Trage de chenar sau de un colț. Săgețile îl mută, iar cu Shift îl mărești sau îl micșorezi. Dacă iese din imagine, se adaugă benzi transparente: așa reduci zoomul la o copertă prea strânsă. Pe controller, direcțiile mută chenarul, iar trăgacele reglează dimensiunea.",
  /* 338 */ "Reîncadrează",
  /* 339 */ "Reîncadrează coperta",
  /* 340 */ "Toată imaginea",
  /* 341 */ "{0} — copertă reîncadrată",
  /* 342 */ "{0} — nicio copertă de reîncadrat",
  /* 343 */ "copertă ilizibilă — {0}",
  /* 344 */ "reîncadrare imposibilă — {0}",
  /* 345 */ "Reîncadrează coperta…",
  /* 346 */ "Avans rapid, cât timp ambele stickuri rămân apăsate",
  /* 347 */ "{0} lăsat deoparte",
  /* 348 */ "Emulatorul {0} s-a oprit în timpul „{1}”.",
  /* 349 */ "Emulatorul {0} s-a oprit.",
  /* 350 */ "Emulatorul s-a oprit",
  /* 351 */ "nu s-a putut lăsa deoparte — {0}",
  /* 352 */ "de pus aici: {0}",
  /* 353 */ "lipsește un fișier de sistem: {0}",
];
