/**
 * Slovaque — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros portés en commentaire sont là pour qu'on puisse le vérifier à
 * l'œil, ligne à ligne.
 */

export const sk: readonly string[] = [
  /* 1 */ "Na ovládači",
  /* 2 */ "A spustiť · X obľúbené · Y orezať · L1/R1 konzoly · L2/R2 písmeno · B späť",
  /* 3 */ "O programe EvaChi",
  /* 4 */ "O programe…",
  /* 5 */ "Chystá sa: filtre katódovej obrazovky, mriežka, riadkovanie. Miesto je pripravené, filtre pribudnú sem.",
  /* 6 */ "Obnoviť knižnicu",
  /* 7 */ "Zobrazenie",
  /* 8 */ "Zobrazovať obaly hier",
  /* 9 */ "Pomocník",
  /* 10 */ "Pridať priečinok s hrami…",
  /* 11 */ "Pridať priečinok…",
  /* 12 */ "Stlačte tlačidlo na ovládači: príslušný príkaz sa rozsvieti. Ak chcete nejaký zmeniť, kliknite na políčko pod ním a stlačte želané tlačidlo. Tlačidlo vtedy zmení majiteľa: dva príkazy na jednom tlačidle by vyzerali ako porucha.",
  /* 13 */ "Argumenty",
  /* 14 */ "Na klávesnici",
  /* 15 */ "Žiadne hry",
  /* 16 */ "Nenašiel sa žiadny ovládač.",
  /* 17 */ "Knižnica",
  /* 18 */ "Zvuky výberu na ovládači",
  /* 19 */ "Niektoré konzoly sa bez pôvodného firmwaru nespustia. EvaChi ho nemôže dodať: je to chránený kód, ktorý sa kopíruje z prístroja, ktorý človek vlastní. Povie však, ktorý chýba, pod akým názvom a kam ho položiť.",
  /* 20 */ "Tieto konzoly nemajú libretro jadro: ich emulátor je samostatný program, ktorý si EvaChi nainštaluje k sebe a spúšťa priamo v hre — bez prechádzania jeho ponukou. Hry, kľúče a systémové súbory zostávajú na vás.",
  /* 21 */ "Tieto nastavenia sa týkajú len vnútorných jadier. Externý emulátor má svoje vlastné a EvaChi do nich nezasahuje.",
  /* 22 */ "Tieto sa už neponúkajú: neodpovedali na dotaz, alebo zhodili EvaChi. Obnovením sa znovu nenainštalujú — len sa vrátia do zoznamu.",
  /* 23 */ "Načítať stav…",
  /* 24 */ "Len vnútorné jadrá. Kliknite na skratku a stlačte požadovaný kláves alebo tlačidlo; na ovládači sa berú dve tlačidlá naraz, pretože každé z nich už slúži hre.",
  /* 25 */ "Ovládanie",
  /* 26 */ "Ovládanie…",
  /* 27 */ "Nedávne konzoly",
  /* 28 */ "Pridať ďalší emulátor",
  /* 29 */ "Smery / ľavá páčka",
  /* 30 */ "Priečinky s hrami",
  /* 31 */ "Vyradiť tento emulátor",
  /* 32 */ "Berú sa na vyžiadanie zo servera s náhľadmi projektu libretro. Bez zaškrtnutia si knižnica zo siete nevyžiada nič.",
  /* 33 */ "Pozície uloženia",
  /* 34 */ "Pozície uloženia…",
  /* 35 */ "Emulátory",
  /* 36 */ "Vyradené emulátory",
  /* 37 */ "Externé emulátory",
  /* 38 */ "Externé emulátory…",
  /* 39 */ "Emulátory…",
  /* 40 */ "Emulácia",
  /* 41 */ "Počas hry návrat do knižnice — dve tlačidlá naraz, pretože každé z nich slúži hre",
  /* 42 */ "Uložiť",
  /* 43 */ "Prípony",
  /* 44 */ "Zavrieť",
  /* 45 */ "Súbor",
  /* 46 */ "Systémové súbory, ktoré doplníte sami",
  /* 47 */ "Galéria",
  /* 48 */ "Správa priečinkov…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Určte priečinok, kde máte hry.",
  /* 52 */ "Inštalácia",
  /* 53 */ "Nainštalovať vybrané",
  /* 54 */ "Nainštalovať emulátory…",
  /* 55 */ "Interpret",
  /* 56 */ "Nemusíte vedieť kam: ukážte priečinok, kde sa to všetko povaľuje — BIOSy, kľúče, firmware, archívy aj s podpriečinkami — a EvaChi odnesie každý súbor na správne miesto, pre jadrá aj pre samostatné emulátory. Čo nikto nežiada, zostane ležať.",
  /* 57 */ "Obaly",
  /* 58 */ "Záznam",
  /* 59 */ "Záznam…",
  /* 60 */ "Minule to skončilo zle",
  /* 61 */ "Spustiť hru, potvrdiť",
  /* 62 */ "Jazyk",
  /* 63 */ "Voľba sa pamätá medzi spusteniami. Pri každom je overená čitateľnosť: text má všade dostatočný kontrast voči svojmu pozadiu.",
  /* 64 */ "Ponechať",
  /* 65 */ "Emulátory nižšie sú už nastavené — vrátane argumentov a formátov. EvaChi ich hľadá na vašom disku; neinštaluje ich.",
  /* 66 */ "Predvolené priradenia",
  /* 67 */ "Vyhladzovanie",
  /* 68 */ "Pridať hru k obľúbeným alebo ju odobrať",
  /* 69 */ "Hudba animovaných ponúk",
  /* 70 */ "Názov",
  /* 71 */ "Otvoriť panel ponúk",
  /* 72 */ "Otvoriť priečinok",
  /* 73 */ "Otvoriť priečinok…",
  /* 74 */ "Otvoriť hru…",
  /* 75 */ "na snímok",
  /* 76 */ "Nastavenia jadra",
  /* 77 */ "Nastavenia jadra…",
  /* 78 */ "Prechádzať knižnicu, okná a panel ponúk",
  /* 79 */ "Prehľadávať…",
  /* 80 */ "Pauza",
  /* 81 */ "Celá obrazovka",
  /* 82 */ "Pre konzoly bez libretro jadra. EvaChi spustí program s hrou ako argumentom: emulátor naskočí priamo do hry, bez toho, aby prechádzal vlastnou ponukou.",
  /* 83 */ "Urobiť snímku",
  /* 84 */ "Rozloženie",
  /* 85 */ "Pripravené",
  /* 86 */ "Program",
  /* 87 */ "Pár držaných akordov a rozptýlené tóny, skladané za chodu namiesto nahrané: skladba sa nikdy nevráti na to isté miesto. Sama utíchne, len čo sa spustí hra.",
  /* 88 */ "Upratať priečinok…",
  /* 89 */ "Vyprázdniť",
  /* 90 */ "Hľadať hru…",
  /* 91 */ "Vrátiť predvolené",
  /* 92 */ "Späť do knižnice",
  /* 93 */ "Vrátiť sa späť, zavrieť",
  /* 94 */ "Rýchle uloženie",
  /* 95 */ "Uložiť stav…",
  /* 96 */ "Shadery",
  /* 97 */ "Zvuk",
  /* 98 */ "Start",
  /* 99 */ "Veľkosť obrazu",
  /* 100 */ "Témy",
  /* 101 */ "Témy…",
  /* 102 */ "Jeden súbor…",
  /* 103 */ "Krátke cvaknutie pri prechode na inú hru, ďalšie pri jej spustení. Len na ovládači: pri myši a klávesnici je pohyb cítiť aj tak.",
  /* 104 */ "Rýchlosť",
  /* 105 */ "Zobraziť snímky…",
  /* 106 */ "Nemusíte nainštalovať všetky — v knižnici sa objavia len konzoly, ktorých emulátor je nainštalovaný.",
  /* 107 */ "{0} — načítané",
  /* 108 */ "{0} — pravým tlačidlom vymažete",
  /* 109 */ "{0} — pridané k obľúbeným",
  /* 110 */ "{0} — vrátené na predvolené",
  /* 111 */ "{0} — odobrané z obľúbených",
  /* 112 */ "{0} — sťahovanie…",
  /* 113 */ "{0}: nepodarilo sa, pozri záznam",
  /* 114 */ "{0} k dispozícii",
  /* 115 */ "{0} uložené",
  /* 116 */ "{0} je externý emulátor: spúšťa sa zvlášť, nebeží vnútri",
  /* 117 */ "{0} sn/s",
  /* 118 */ "{0} nainštalované",
  /* 119 */ "{0} nainštalované — {1}",
  /* 120 */ "{0} nainštalované a pripravené",
  /* 121 */ "{0} nainštalované, {1} sa nepodarilo — pozri záznam",
  /* 122 */ "{0} obnovené",
  /* 123 */ "{0} odobrané",
  /* 124 */ "{0} z {1}",
  /* 125 */ "{0} na disku, ale žiadne nainštalované jadro ich neotvorí.",
  /* 126 */ "vezmite z {0}, potom „Prehľadávať…“",
  /* 127 */ "na stiahnutie",
  /* 128 */ "chýba, nepovinné",
  /* 129 */ "Zapnúť",
  /* 130 */ "Mäkké",
  /* 131 */ "nedá sa pridať — {0}",
  /* 132 */ "Prispôsobiť",
  /* 133 */ "Jantár",
  /* 134 */ "Bridlica",
  /* 135 */ "zastavené — {0}",
  /* 136 */ "minule náhly pád — {0}",
  /* 137 */ "žiadny",
  /* 138 */ "nevrátili sa žiadne jadrá, hoci {0} boli známe — ponechaný predchádzajúci zoznam",
  /* 139 */ "žiadny emulátor",
  /* 140 */ "Nie je nainštalovaný žiadny emulátor",
  /* 141 */ "Žiadna rozpoznaná hra",
  /* 142 */ "Žiadny výsledok",
  /* 143 */ "žiadna",
  /* 144 */ "knižnica sa nedá prečítať — {0}",
  /* 145 */ "pripojený",
  /* 146 */ "snímka",
  /* 147 */ "Zmeniť obal…",
  /* 148 */ "Zmeniť…",
  /* 149 */ "Každý pixel na deväť",
  /* 150 */ "Každý pixel na štyri: ostré, bez deformácie",
  /* 151 */ "Každý pixel na šestnásť — pre veľké obrazovky",
  /* 152 */ "Načítať",
  /* 153 */ "Vybrať obal…",
  /* 154 */ "najprv vyberte hru v knižnici",
  /* 155 */ "jadro: {0}",
  /* 156 */ "jadro nie je nainštalované",
  /* 157 */ "Nainštalované jadrá",
  /* 158 */ "libretro jadrá",
  /* 159 */ "Vysoký kontrast",
  /* 160 */ "natívny obal: {0}",
  /* 161 */ "neúplné uvoľnenie — {0}",
  /* 162 */ "objavené: {0}",
  /* 163 */ "hľadanie prerušené — {0}",
  /* 164 */ "Určiť program pre {0} ručne",
  /* 165 */ "priečinok pridaný: {0}",
  /* 166 */ "priečinok otvorený: {0}",
  /* 167 */ "Predvolený priečinok",
  /* 168 */ "Pridané priečinky",
  /* 169 */ "Esc",
  /* 170 */ "Pozícia {0}",
  /* 171 */ "pozícia {0} — {1}",
  /* 172 */ "Emulátor pre tento priečinok",
  /* 173 */ "externé emulátory",
  /* 174 */ "prebieha",
  /* 175 */ "na mieste",
  /* 176 */ "nedá sa uložiť — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi ich vie stiahnuť z oficiálnej dielne libretro. Vyberte konzoly, ktoré vás zaujímajú.",
  /* 179 */ "EvaChi sa zastavila pri spúšťaní „{0}“ s emulátorom {1}.",
  /* 180 */ "EvaChi sa zastavila, s emulátorom {0}.",
  /* 181 */ "external_systems → ohlásených emulátorov: {0}",
  /* 182 */ "Obľúbená",
  /* 183 */ "Obľúbené",
  /* 184 */ "systémové súbory sa nedajú prečítať — {0}",
  /* 185 */ "Šípky",
  /* 186 */ "Game Boy",
  /* 187 */ "Mriežka",
  /* 188 */ "nainštalovaným konzolám chýba {0}",
  /* 189 */ "inštalácia dokončená: {0}",
  /* 190 */ "Inštalácia…",
  /* 191 */ "nainštalované",
  /* 192 */ "nainštalovala EvaChi",
  /* 193 */ "Nainštalovať",
  /* 194 */ "interpret: {0}",
  /* 195 */ "dotaz na nainštalované jadrá…",
  /* 196 */ "Spustiť",
  /* 197 */ "Spustiť vybranú hru",
  /* 198 */ "Levanduľa",
  /* 199 */ "Konzoly v riadku, hry v stĺpci, vlniace sa pozadie. Po vzore hernej konzoly.",
  /* 200 */ "Obrysy sú rozmazané — bližšie starému televízoru",
  /* 201 */ "Obaly vo veľkom, prechádzané ovládačom. Myslené pre gauč.",
  /* 202 */ "Pixely zostávajú hranaté, ako na pôvodnom prístroji",
  /* 203 */ "priradenia ovládača vrátené na predvolené",
  /* 204 */ "list_cores → ohlásených jadier: {0}",
  /* 205 */ "Zoznam",
  /* 206 */ "zoznam jadier nie je dostupný — {0}",
  /* 207 */ "zoznam emulátorov nie je dostupný — {0}",
  /* 208 */ "Ovládač",
  /* 209 */ "ovládač: {0}",
  /* 210 */ "Ovládač: {0}",
  /* 211 */ "ovládač odpojený",
  /* 212 */ "CHÝBA",
  /* 213 */ "Mäta",
  /* 214 */ "Animovaná ponuka",
  /* 215 */ "Aktualizovať",
  /* 216 */ "Pridať k obľúbeným",
  /* 217 */ "vyradené: {0} · {1}",
  /* 218 */ "menej ako minúta",
  /* 219 */ "Ostré",
  /* 220 */ "názov, program aj prípony sú potrebné všetky",
  /* 221 */ "NIE",
  /* 222 */ "na tomto počítači nie je nainštalovaný",
  /* 223 */ "Ružová noc",
  /* 224 */ "Oceán",
  /* 225 */ "alebo",
  /* 226 */ "áno",
  /* 227 */ "nedá sa otvoriť — {0}",
  /* 228 */ "webová stránka: dostupné sú len vnútorné jadrá, bez knižnice",
  /* 229 */ "Papier",
  /* 230 */ "predvolené",
  /* 231 */ "Prechádzať mriežku a animované ponuky",
  /* 232 */ "celá obrazovka odmietnutá — {0}",
  /* 233 */ "stlačte požadované tlačidlo na ovládači",
  /* 234 */ "stlačte kláves…",
  /* 235 */ "upratovanie: {0} · {1}",
  /* 236 */ "upratovanie sa nepodarilo — {0}",
  /* 237 */ "hľadanie emulátorov prerušené — {0}",
  /* 238 */ "Zavrieť okno",
  /* 239 */ "nedá sa vrátiť predvolené — {0}",
  /* 240 */ "Vyplní okno so zachovaním pomeru strán",
  /* 241 */ "Pokračovať",
  /* 242 */ "Nahradiť",
  /* 243 */ "Obnoviť",
  /* 244 */ "nedá sa obnoviť — {0}",
  /* 245 */ "Odobrať",
  /* 246 */ "Odobrať z obľúbených",
  /* 247 */ "Odobrať obal",
  /* 248 */ "nedá sa odobrať — {0}",
  /* 249 */ "nie je čo upratovať",
  /* 250 */ "nič neprekáža",
  /* 251 */ "Nič nezodpovedá „{0}“.",
  /* 252 */ "Ružová a biela",
  /* 253 */ "bez obrázka",
  /* 254 */ "Uložiť",
  /* 255 */ "Uložiť sem",
  /* 256 */ "nedá sa vybrať — {0}",
  /* 257 */ "Pôvodná veľkosť konzoly, pixel na pixel",
  /* 258 */ "Zahodiť",
  /* 259 */ "svetlá téma",
  /* 260 */ "tmavá téma",
  /* 261 */ "všetko je nainštalované",
  /* 262 */ "nájdené: {0}",
  /* 263 */ "Jeden oddiel pre každú konzolu, v tabuľke. S myšou najhustejšie.",
  /* 264 */ "prázdne",
  /* 265 */ "položte sem, rovnako ako romsety hier: FinalBurn Neo hľadá len v tomto priečinku",
  /* 266 */ "pridá úvodnú obrazovku konzoly",
  /* 267 */ "zavádzač prístroja",
  /* 268 */ "veľa hier sa spustí aj bez neho; ponuka konzoly nie",
  /* 269 */ "americký BIOS",
  /* 270 */ "americký a európsky BIOS",
  /* 271 */ "európsky BIOS",
  /* 272 */ "japonský BIOS",
  /* 273 */ "dešifrovacie kľúče; bez nich sa zašifrovaná kópia odmietne",
  /* 274 */ "priečinok Machines z distribúcie blueMSX, vedľa neho Databases",
  /* 275 */ "to isté",
  /* 276 */ "nutný pre hry na CD, pre karty HuCard zbytočný",
  /* 277 */ "nutný pre hry Mega-CD, pre kazety zbytočný",
  /* 278 */ "Kickstart 1.3; inak PUAE siahne po AROS, slobodnom, ale menej kompatibilnom",
  /* 279 */ "Kickstart 3.1; nutný pre hry AGA, ktoré A500 nezvládne",
  /* 280 */ "melonDS predvolene BIOS emuluje; ten pravý je vernejší",
  /* 281 */ "mGBA sa bez neho obíde; pár hier ho vyžaduje kvôli úvodnej obrazovke",
  /* 282 */ "firmware konzoly",
  /* 283 */ "firmware prístroja",
  /* 284 */ "firmware Panasonic FZ-10; práve tento názov berie Opera ako predvolený",
  /* 285 */ "upravuje ho melonDS, pôvodný zachová ako .bak",
  /* 286 */ "písma",
  /* 287 */ "nastavenia a dátum konzoly",
  /* 288 */ "bez neho jadro beží, ale obrazovka zostane čierna",
  /* 289 */ "znaková sada konzoly",
  /* 290 */ "americký variant, pre hry Sega CD zo Spojených štátov",
  /* 291 */ "japonský variant, pre japonské hry Mega-CD",
  /* 292 */ "snímky",
  /* 293 */ "snímky",
  /* 294 */ "snímka",
  /* 295 */ "snímok",
  /* 296 */ "snímky",
  /* 297 */ "snímok",
  /* 298 */ "jadrá",
  /* 299 */ "jadra",
  /* 300 */ "jadro",
  /* 301 */ "jadier",
  /* 302 */ "jadrá",
  /* 303 */ "jadier",
  /* 304 */ "emulátory",
  /* 305 */ "emulátora",
  /* 306 */ "emulátor",
  /* 307 */ "emulátorov",
  /* 308 */ "emulátory",
  /* 309 */ "emulátorov",
  /* 310 */ "súbory",
  /* 311 */ "súboru",
  /* 312 */ "súbor",
  /* 313 */ "súborov",
  /* 314 */ "súbory",
  /* 315 */ "súborov",
  /* 316 */ "hry",
  /* 317 */ "hry",
  /* 318 */ "hra",
  /* 319 */ "hier",
  /* 320 */ "hry",
  /* 321 */ "hier",
  /* 322 */ "<code>{rom}</code> sa nahradí cestou k hre. Bez neho sa cesta pripojí na koniec — čo väčšina emulátorov očakáva.",
  /* 323 */ "<strong>Mimo hru sa všetko robí ovládačom:</strong> smery prechádzajú knižnicu, okná aj panel ponúk; <strong>A</strong> potvrdzuje, <strong>B</strong> vracia späť, <strong>Start</strong> otvára panel ponúk. Počas hry vráti do knižnice <strong>Select a Start naraz</strong> — dve tlačidlá naraz, pretože každé z nich slúži hre.",
  /* 324 */ "Žiadne snímky. Počas hry stlačte <strong>F12</strong>, alebo <strong>Select + Y</strong> na ovládači.",
  /* 325 */ "Každá konzola potrebuje svoj emulátor. EvaChi ich hľadá v oficiálnej dielni projektu libretro, <code>buildbot.libretro.com</code>, a inštaluje ich do svojho vlastného priečinka. Nič sa nešíri ďalej: sú to verzie vydané ich autormi.",
  /* 326 */ "Štyri pozície na hru, uložené na disku. Každý úkon je napísaný pod pozíciou a nahradenie či vyprázdnenie si pýta potvrdenie. <strong>F2</strong> a <strong>F4</strong> — a <strong>Select + L1</strong> / <strong>Select + R1</strong> na ovládači — idú rovno na tučnú pozíciu, bez toho aby sa na čokoľvek pýtali.",
  /* 327 */ "Každý emulátor beží vo vlastnom procese: keď spadne, EvaChi to vidí a vráti sa do knižnice. Rozohraná hra je stratená a uloženie hry sa možno nezapísalo. Vyradením zostane nainštalovaný, len sa prestane ponúkať. Kedykoľvek ho môžete obnoviť cez <strong>Súbor → Emulátory</strong>, dole v okne.",
  /* 328 */ "Jeden súbor na hru na disku <small> Hra na CD prichádza ako súpis <code>.cue</code> a toľko súborov <code>.bin</code>, koľko malo CD stôp. Spúšťa sa len súpis: stopy sa skryjú, keď je na mieste. Bez súpisu sa neskryje nič. </small>",
  /* 329 */ "(prázdne) alebo --fullscreen {rom}",
  /* 330 */ "Sto percent je rýchlosť samotnej konzoly. Pod ňou hra spomalí, nad ňou letí — a zvuk ide s ňou, hlbšie alebo vyššie. Na ovládači vľavo a vpravo prechádzajú z jedného stupňa na ďalší. Platí len pre vnútorné jadrá: externý emulátor si drží tú svoju.",
  /* 331 */ "Päť konzol naraz",
  /* 332 */ "Smerový krížik",
  /* 333 */ "Z jedného písmena na ďalšie",
  /* 334 */ "V animovaných ponukách päť hier naraz",
  /* 335 */ "Rýchlosť hry",
  /* 336 */ "Zrušiť",
  /* 337 */ "Potiahnite rámček alebo jeho roh. Šípky ním pohybujú, so Shiftom ho zväčšujú alebo zmenšujú. Keď presiahne obrázok, pribudnú priehľadné pruhy: takto oddialite priveľmi tesný obal hry. Na ovládači pohybujú rámčekom smerové tlačidlá a veľkosť nastavujú spúšte.",
  /* 338 */ "Orezať",
  /* 339 */ "Orezať obal",
  /* 340 */ "Celý obrázok",
  /* 341 */ "{0} — obal orezaný",
  /* 342 */ "{0} — žiadny obal na orezanie",
  /* 343 */ "nečitateľný obal — {0}",
  /* 344 */ "orezanie zlyhalo — {0}",
  /* 345 */ "Orezať obal…",
  /* 346 */ "Rýchly posun vpred, kým sú obe páčky stlačené",
  /* 347 */ "{0} vyradené",
  /* 348 */ "Emulátor {0} sa zastavil počas „{1}“.",
  /* 349 */ "Emulátor {0} sa zastavil.",
  /* 350 */ "Emulátor sa zastavil",
  /* 351 */ "nedá sa vyradiť — {0}",
  /* 352 */ "položte sem: {0}",
  /* 353 */ "chýba systémový súbor: {0}",
  /* 354 */ "Zásluhy",
  /* 355 */ "Nekomerčná licencia, dobré vedieť pred akýmkoľvek prevzatím: {0}.",
  /* 356 */ "EvaChi nepíše žiadny emulátor: hostí ich u seba. Každý z nich je samostatný slobodný projekt, napísaný inými, ktorý si EvaChi na vyžiadanie vyzdvihne u jeho autorov — ani riadok ich kódu tu nie je prepísaný, ani bajt sa nešíri ďalej. Názvy a licencie nižšie sú tie, ktoré si každý projekt uvádza sám.",
  /* 357 */ "Kolotoč",
  /* 358 */ "Obaly spredu, konzoly na sebe, stúpajúci prach. V štýle výkladného stojana.",
  /* 359 */ "Ako rozhranie",
  /* 360 */ "Jazyk rozhrania",
  /* 361 */ "Jazyk hier",
  /* 362 */ "Jazyk hier: {0}. Prejaví sa pri nasledujúcom spustení.",
  /* 363 */ "Späť",
  /* 364 */ "Hľadať",
  /* 365 */ "Nájsť súbory",
  /* 366 */ "Hľadať hodnotu",
  /* 367 */ "Iné",
  /* 368 */ "Rovnaké",
  /* 369 */ "Šírka",
  /* 370 */ "Projekt libretro zverejňuje súbory s podvodmi, jeden na hru. EvaChi ponechá len tie, ktoré sa k vašej hre hodia presne — rovnaký názov, rovnaký región, rovnaká revízia — a radšej nenavrhne nič než niečo približné: kódy písané pre inú verziu nezapisujú kúsok vedľa, zapisujú inam.",
  /* 371 */ "Podvody",
  /* 372 */ "Menej",
  /* 373 */ "Panel podvodov",
  /* 374 */ "Viac",
  /* 375 */ "Začať odznova",
  /* 376 */ "Podvody",
  /* 377 */ "Podvody…",
  /* 378 */ "Hodnota",
  /* 379 */ "Rovná sa",
  /* 380 */ "{0} možných adries",
  /* 381 */ "{0} súborov uložených, {1} odstránených",
  /* 382 */ "{0} z {1} hier má súbor",
  /* 383 */ "{0} bajtov pamäte",
  /* 384 */ "{0} hodnôt vyradených: mimo pamäte tejto hry",
  /* 385 */ "Pre túto hru nie je súbor. Panel „Podvody…“ v ponuke Emulácia ho hľadá; inak hľadanie hodnoty funguje pri každej hre.",
  /* 386 */ "Zmrazená",
  /* 387 */ "Zmraziť",
  /* 388 */ "Chvíľu hrajte a potom povedzte, čo hodnota urobila.",
  /* 389 */ "Hra bola odložená pred prvým podvodom.",
  /* 390 */ "Hľadá sa…",
  /* 391 */ "To, čo sa položí do « drop u'r rom », putuje ku konzole, ktorú určuje prípona. Keď tú istú príponu zdieľa viac konzol — obrazy diskov — EvaChi sa radšej spýta, než by hádala.",
  /* 392 */ "Potvrdenie",
  /* 393 */ "Zmazať uloženú hru…",
  /* 394 */ "Roztiahnutie",
  /* 395 */ "Hra si svoje počty drží v pamäti, ale nepovie kde. Nájdu sa vylučovaním: poviete, čo urobilo zobrazené číslo, a EvaChi vyradí adresy, ktoré to neurobili tiež.",
  /* 396 */ "Áno",
  /* 397 */ "Málo konzol má pomery dnešnej obrazovky, odtiaľ čierne pruhy po stranách. Na nule si obraz svoje pomery zachová; na sto vyplní okno, hoci aj roztiahnutý.",
  /* 398 */ "Upratovanie hier",
  /* 399 */ "Upratať",
  /* 400 */ "Upratať odložené hry…",
  /* 401 */ "Vidíte 47 životov: napíšte 47 do poľa « Hodnota » a stlačte « Hľadať ». Jeden strate, napíšte 46 a stlačte « Rovná sa ». Ak číslo nie je nikde napísané, nechajte « Hodnota » prázdne a medzi dvoma okamihmi hry povedzte len « Viac », « Menej », « Iné » alebo « Rovnaké ». Nájdenú hodnotu potom udrží « Zmraziť ». « Šírka » je veľkosť čísla: 1 do 255, 2 vyššie, 4 pre veľké počítadlá.",
  /* 402 */ "upratané: {0}",
  /* 403 */ "niet čo mazať",
  /* 404 */ "Tlačidlá",
  /* 405 */ "Už v knižnici: {0}",
  /* 406 */ "Zmazať uloženú hru {0} a začať odznova? Prebiehajúca hra sa zastaví a to, čo si hra poznamenala, sa stratí.",
  /* 407 */ "Spúšte",
  /* 408 */ "Ponechať oboje",
  /* 409 */ "Nechať v odkladacom priečinku",
  /* 410 */ "Odkladací priečinok je prázdny.",
  /* 411 */ "Nahradiť pozíciu {0}? To, čo je tam uložené, sa stratí.",
  /* 412 */ "uložená hra zmazaná — {0}",
  /* 413 */ "Systém",
  /* 414 */ "Vyprázdniť pozíciu {0}? To, čo je tam uložené, sa stratí.",
  /* 415 */ "Mŕtva zóna je tá časť páčky, v ktorej sa ešte považuje za v pokoji. Priveľmi malá — postava sa sama pohne, aj keď ovládač leží na stole; priveľmi veľká — drobné pohyby sa stratia. Niektoré hry žiadajú zatriasť konzolou: keď to ovládač nevie cítiť, dve tlačidlá nižšie o tom hru presvedčia.",
  /* 416 */ "Páčka",
  /* 417 */ "Samostatné emulátory majú vlastné tlačidlá, vo vlastných súboroch. To, čo tu zmeníte, sa k nim prenesie hneď — pre tie, ktorých formát poznáme z prvej ruky: PCSX2, PPSSPP a Dolphin. Staré nastavenie sa pri prvom prechode odloží bokom, pod rovnakým názvom s príponou « .avant-evachi ».",
  /* 418 */ "Preniesť do externých emulátorov",
  /* 419 */ "Mŕtva zóna",
  /* 420 */ "Súostrovie",
  /* 421 */ "Hlina",
  /* 422 */ "žiadny externý emulátor ešte nezapísal svoje nastavenia",
  /* 423 */ "Pahreba",
  /* 424 */ "Popol",
  /* 425 */ "Čerešňa",
  /* 426 */ "Koral",
  /* 427 */ "Polica",
  /* 428 */ "Les",
  /* 429 */ "Inovať",
  /* 430 */ "externé emulátory už tieto tlačidlá mali",
  /* 431 */ "Polnoc",
  /* 432 */ "Mach",
  /* 433 */ "Neón",
  /* 434 */ "Slivka",
  /* 435 */ "Piesok",
  /* 436 */ "Zatriasť",
  /* 437 */ "Sépia",
  /* 438 */ "prenesené tlačidlá: {0}",
  /* 439 */ "Tyrkys",
  /* 440 */ "Stena políc: jedna doska na konzolu, a škatule hrubé ako ich súbor.",
  /* 441 */ "Jeden ostrov na konzolu, hry rozosiate okolo, a kamera, ktorá preletuje. Miesto hry sa nikdy nemení.",
  /* 442 */ "Virtual Boy",
];
