/**
 * Slovène — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros portés en commentaire sont là pour qu'on puisse le vérifier à
 * l'œil, ligne à ligne.
 */

export const sl: readonly string[] = [
  /* 1 */ "Na krmilniku",
  /* 2 */ "A zaženi · X priljubljeno · Y obreži · L1/R1 konzole · L2/R2 črka · B nazaj",
  /* 3 */ "O EvaChi",
  /* 4 */ "O programu…",
  /* 5 */ "Kar je slikovna cev počela s sliko in kar so igre tistega časa jemale za samoumevno. Velja le za jedra, ki tečejo tukaj: samostojen emulator svojo sliko nariše sam.",
  /* 6 */ "Osveži knjižnico",
  /* 7 */ "Prikaz",
  /* 8 */ "Prikazuj ovitke iger",
  /* 9 */ "Pomoč",
  /* 10 */ "Dodaj mapo z igrami…",
  /* 11 */ "Dodaj mapo…",
  /* 12 */ "Pritisnite gumb na krmilniku: ustrezni ukaz zasveti. Če ga želite spremeniti, kliknite polje spodaj in nato pritisnite želeni gumb. Gumb tedaj zamenja lastnika: dva ukaza na istem gumbu bi bila videti kot okvara.",
  /* 13 */ "Argumenti",
  /* 14 */ "Na tipkovnici",
  /* 15 */ "Ni iger",
  /* 16 */ "Ni zaznanega krmilnika.",
  /* 17 */ "Knjižnica",
  /* 18 */ "Zvoki izbire na krmilniku",
  /* 19 */ "Nekatere konzole se brez izvirne vdelane programske opreme ne zaženejo. EvaChi je ne more priskrbeti: to je avtorsko zaščitena koda, ki se prepiše iz naprave, ki jo imate. Povedala pa vam bo, katera manjka, pod katerim imenom in kam jo odložiti.",
  /* 20 */ "Te konzole nimajo jedra libretro: njihov emulator je samostojen program, ki ga EvaChi namesti k sebi in zažene naravnost v igro — brez vmesnega menija. Za igre, ključe in sistemske datoteke poskrbite sami.",
  /* 21 */ "Te nastavitve veljajo samo za notranja jedra. Zunanji emulator ima svoje in EvaChi se vanje ne vtika.",
  /* 22 */ "Ti niso več na voljo: bodisi se niso odzvali na poizvedbo, bodisi so podrli EvaChi. Če jih obnovite, se ne namestijo znova — le vrnejo se na seznam.",
  /* 23 */ "Naloži stanje…",
  /* 24 */ "Samo notranja jedra. Kliknite bližnjico in pritisnite želeno tipko ali gumb; na krmilniku vzamemo dva gumba hkrati, saj vsak od njiju že služi igri.",
  /* 25 */ "Upravljanje",
  /* 26 */ "Upravljanje…",
  /* 27 */ "Nedavne konzole",
  /* 28 */ "Dodaj drug emulator",
  /* 29 */ "Smeri / leva palica",
  /* 30 */ "Mape z igrami",
  /* 31 */ "Umakni ta emulator",
  /* 32 */ "Prihajajo s strežnika sličic projekta libretro, po potrebi. Če polje odkljukate, knjižnica od omrežja ne zahteva več ničesar.",
  /* 33 */ "Mesta shranjevanja",
  /* 34 */ "Mesta…",
  /* 35 */ "Emulatorji",
  /* 36 */ "Umaknjeni emulatorji",
  /* 37 */ "Zunanji emulatorji",
  /* 38 */ "Zunanji emulatorji…",
  /* 39 */ "Emulatorji…",
  /* 40 */ "Emulacija",
  /* 41 */ "Med igro vrnitev v knjižnico — dva gumba hkrati, saj vsak od njiju služi igri",
  /* 42 */ "Shrani",
  /* 43 */ "Končnice",
  /* 44 */ "Zapri",
  /* 45 */ "Datoteka",
  /* 46 */ "Sistemske datoteke, ki jih namestite sami",
  /* 47 */ "Galerija",
  /* 48 */ "Upravljanje map…",
  /* 49 */ "Grafika",
  /* 50 */ "Grafika…",
  /* 51 */ "Pokažite mapo, v kateri so vaše igre.",
  /* 52 */ "Namestitev",
  /* 53 */ "Namesti izbrano",
  /* 54 */ "Namesti emulatorje…",
  /* 55 */ "Tolmač",
  /* 56 */ "Ni treba vedeti, kam: pokažite mapo, kjer vse leži — BIOS, ključi, vdelana programska oprema, arhivi, tudi podmape — in EvaChi vsako datoteko odnese na pravo mesto, za jedra in za samostojne emulatorje. Kar nihče ne zahteva, ostane, kjer je.",
  /* 57 */ "Ovitki",
  /* 58 */ "Dnevnik",
  /* 59 */ "Dnevnik…",
  /* 60 */ "Prejšnjič se je slabo končalo",
  /* 61 */ "Zaženi igro, potrdi",
  /* 62 */ "Jezik",
  /* 63 */ "Izbira se ohrani od zagona do zagona. Vsaka je preverjeno berljiva: besedilo ima povsod dovolj kontrasta na svojem ozadju.",
  /* 64 */ "Obdrži ga",
  /* 65 */ "Spodnji emulatorji so že nastavljeni — z argumenti in formati. EvaChi jih poišče na vašem disku; ne namesti jih.",
  /* 66 */ "Prvotne vezave",
  /* 67 */ "Glajenje",
  /* 68 */ "Dodaj igro med priljubljene ali jo odstrani",
  /* 69 */ "Glasba gibljivih menijev",
  /* 70 */ "Ime",
  /* 71 */ "Odpri menijsko vrstico",
  /* 72 */ "Odpri mapo",
  /* 73 */ "Odpri mapo…",
  /* 74 */ "Odpri igro…",
  /* 75 */ "na sličico",
  /* 76 */ "Nastavitve jedra",
  /* 77 */ "Nastavitve jedra…",
  /* 78 */ "Premikanje po knjižnici, oknih in menijski vrstici",
  /* 79 */ "Prebrskaj…",
  /* 80 */ "Premor",
  /* 81 */ "Cel zaslon",
  /* 82 */ "Za konzole brez jedra libretro. EvaChi zažene program z igro kot argumentom: emulator se zbudi naravnost v igri, brez svojega menija.",
  /* 83 */ "Zajemi posnetek",
  /* 84 */ "Postavitev",
  /* 85 */ "Pripravljeno",
  /* 86 */ "Program",
  /* 87 */ "Nekaj zadržanih akordov in posamezne note, sestavljene sproti in ne posnete: skladba nikoli ne gre dvakrat po isti poti. Ko se igra začne, utihne sama.",
  /* 88 */ "Pospravi mapo…",
  /* 89 */ "Izprazni",
  /* 90 */ "Poišči igro…",
  /* 91 */ "Ponastavi",
  /* 92 */ "Nazaj v knjižnico",
  /* 93 */ "Korak nazaj, zapri",
  /* 94 */ "Hitro shranjevanje",
  /* 95 */ "Shrani stanje…",
  /* 96 */ "Shaders",
  /* 97 */ "Zvok",
  /* 98 */ "Start",
  /* 99 */ "Velikost slike",
  /* 100 */ "Teme",
  /* 101 */ "Teme…",
  /* 102 */ "Samo ena datoteka…",
  /* 103 */ "Kratek klik ob menjavi igre, še eden ob zagonu. Samo na krmilniku: pri miški in tipkovnici se gib že čuti.",
  /* 104 */ "Hitrost",
  /* 105 */ "Ogled posnetkov…",
  /* 106 */ "Namestite jih lahko tudi le nekaj — v knjižnici se pokažejo samo konzole, katerih emulator je nameščen.",
  /* 107 */ "{0} — naloženo",
  /* 108 */ "{0} — desni klik za izbris",
  /* 109 */ "{0} — med priljubljenimi",
  /* 110 */ "{0} — ponastavljeno",
  /* 111 */ "{0} — odstranjeno iz priljubljenih",
  /* 112 */ "{0} — prenašanje…",
  /* 113 */ "{0}: spodletelo, poglejte dnevnik",
  /* 114 */ "{0} na voljo",
  /* 115 */ "{0} shranjeno",
  /* 116 */ "{0} je zunanji emulator: zaženemo ga, ne gostimo ga",
  /* 117 */ "{0} sl/s",
  /* 118 */ "{0} nameščeno",
  /* 119 */ "{0} nameščeno — {1}",
  /* 120 */ "{0} nameščeno in pripravljeno",
  /* 121 */ "{0} nameščenih, {1} spodletelih — poglejte dnevnik",
  /* 122 */ "{0} obnovljeno",
  /* 123 */ "{0} odstranjeno",
  /* 124 */ "{0} od {1}",
  /* 125 */ "{0} na disku, a nobeno nameščeno jedro jih ne odpre.",
  /* 126 */ "vzemite z {0}, nato »Prebrskaj…«",
  /* 127 */ "za prenos",
  /* 128 */ "manjka, ni nujno",
  /* 129 */ "Vklopi",
  /* 130 */ "Mehko",
  /* 131 */ "dodajanje ni mogoče — {0}",
  /* 132 */ "Prilagodi",
  /* 133 */ "Jantar",
  /* 134 */ "Skrilavec",
  /* 135 */ "ustavitev — {0}",
  /* 136 */ "prejšnjič nasilna ustavitev — {0}",
  /* 137 */ "noben",
  /* 138 */ "vrnjeno ni bilo nobeno jedro, čeprav jih je bilo znanih {0} — prejšnji seznam ohranjen",
  /* 139 */ "ni emulatorja",
  /* 140 */ "Ni nameščenega emulatorja",
  /* 141 */ "Nobena igra ni prepoznana",
  /* 142 */ "Ni zadetkov",
  /* 143 */ "nobena",
  /* 144 */ "knjižnica ni berljiva — {0}",
  /* 145 */ "priključen",
  /* 146 */ "posnetek",
  /* 147 */ "Zamenjaj ovitek…",
  /* 148 */ "Zamenjaj…",
  /* 149 */ "Vsak piksel v devet",
  /* 150 */ "Vsak piksel v štiri: ostro, brez popačenja",
  /* 151 */ "Vsak piksel v šestnajst — za velike zaslone",
  /* 152 */ "Naloži",
  /* 153 */ "Izberi ovitek…",
  /* 154 */ "najprej izberite igro v knjižnici",
  /* 155 */ "jedro: {0}",
  /* 156 */ "jedro ni nameščeno",
  /* 157 */ "Nameščena jedra",
  /* 158 */ "jedra libretro",
  /* 159 */ "Visok kontrast",
  /* 160 */ "izvorna lupina: {0}",
  /* 161 */ "jedro ni bilo povsem razloženo — {0}",
  /* 162 */ "odkrivanje: {0}",
  /* 163 */ "odkrivanje prekinjeno — {0}",
  /* 164 */ "Sami določite program za {0}",
  /* 165 */ "mapa dodana: {0}",
  /* 166 */ "mapa odprta: {0}",
  /* 167 */ "Privzeta mapa",
  /* 168 */ "Dodane mape",
  /* 169 */ "Esc",
  /* 170 */ "Mesto {0}",
  /* 171 */ "mesto {0} — {1}",
  /* 172 */ "Emulator za to mapo",
  /* 173 */ "zunanji emulatorji",
  /* 174 */ "poteka",
  /* 175 */ "na mestu",
  /* 176 */ "shranjevanje ni mogoče — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi jih lahko prenese z uradnega strežnika libretro. Izberite konzole, ki vas zanimajo.",
  /* 179 */ "EvaChi se je ustavila med zagonom »{0}«, z emulatorjem {1}.",
  /* 180 */ "EvaChi se je ustavila, z emulatorjem {0}.",
  /* 181 */ "external_systems → {0} navedenih emulatorjev",
  /* 182 */ "Priljubljena",
  /* 183 */ "Priljubljene",
  /* 184 */ "sistemske datoteke niso berljive — {0}",
  /* 185 */ "Puščice",
  /* 186 */ "Game Boy",
  /* 187 */ "Mreža",
  /* 188 */ "pri nameščenih konzolah manjka {0}",
  /* 189 */ "namestitev končana: {0}",
  /* 190 */ "Namestitev…",
  /* 191 */ "nameščeno",
  /* 192 */ "namestila EvaChi",
  /* 193 */ "Namesti",
  /* 194 */ "tolmač: {0}",
  /* 195 */ "poizvedba pri nameščenih jedrih…",
  /* 196 */ "Zaženi",
  /* 197 */ "Zaženi izbrano igro",
  /* 198 */ "Sivka",
  /* 199 */ "Konzole v vrsti, igre v stolpcu, ozadje, ki valovi. Kot pri domači konzoli.",
  /* 200 */ "Robovi so zabrisani — bliže staremu televizorju",
  /* 201 */ "Ovitki na veliko, brskanje s krmilnikom. Mišljeno za kavč.",
  /* 202 */ "Piksli ostanejo kvadratni, kot na izvirni napravi",
  /* 203 */ "vezave krmilnika vrnjene na prvotne",
  /* 204 */ "list_cores → {0} najavljenih jeder",
  /* 205 */ "Seznam",
  /* 206 */ "seznam jeder ni dosegljiv — {0}",
  /* 207 */ "seznam emulatorjev ni dosegljiv — {0}",
  /* 208 */ "Krmilnik",
  /* 209 */ "krmilnik: {0}",
  /* 210 */ "Krmilnik: {0}",
  /* 211 */ "krmilnik odklopljen",
  /* 212 */ "MANJKA",
  /* 213 */ "Meta",
  /* 214 */ "Gibljivi meni",
  /* 215 */ "Posodobi",
  /* 216 */ "Dodaj med priljubljene",
  /* 217 */ "umaknjeno: {0} · {1}",
  /* 218 */ "manj kot minuta",
  /* 219 */ "Ostro",
  /* 220 */ "potrebni so ime, program in končnice",
  /* 221 */ "NE",
  /* 222 */ "ni nameščeno na tej napravi",
  /* 223 */ "Rožnata noč",
  /* 224 */ "Ocean",
  /* 225 */ "ali",
  /* 226 */ "da",
  /* 227 */ "odpiranje ni mogoče — {0}",
  /* 228 */ "spletna stran: na voljo so samo notranja jedra, brez knjižnice",
  /* 229 */ "Papir",
  /* 230 */ "privzeto",
  /* 231 */ "Premikanje po mreži in gibljivih menijih",
  /* 232 */ "cel zaslon zavrnjen — {0}",
  /* 233 */ "pritisnite želeni gumb na krmilniku",
  /* 234 */ "pritisnite tipko…",
  /* 235 */ "pospravljanje: {0} · {1}",
  /* 236 */ "pospravljanje ni mogoče — {0}",
  /* 237 */ "iskanje emulatorjev prekinjeno — {0}",
  /* 238 */ "Zapri okno",
  /* 239 */ "ponastavitev ni mogoča — {0}",
  /* 240 */ "Zapolni okno in ohrani razmerja",
  /* 241 */ "Nadaljuj",
  /* 242 */ "Zamenjaj",
  /* 243 */ "Obnovi",
  /* 244 */ "obnovitev ni mogoča — {0}",
  /* 245 */ "Odstrani",
  /* 246 */ "Odstrani iz priljubljenih",
  /* 247 */ "Odstrani ovitek",
  /* 248 */ "odstranitev ni mogoča — {0}",
  /* 249 */ "ni česa pospraviti",
  /* 250 */ "nič ne ovira",
  /* 251 */ "Nič se ne ujema z »{0}«.",
  /* 252 */ "Rožnato in belo",
  /* 253 */ "brez slike",
  /* 254 */ "Shrani",
  /* 255 */ "Shrani sem",
  /* 256 */ "izbira ni mogoča — {0}",
  /* 257 */ "Izvirna velikost konzole, na piksel natančno",
  /* 258 */ "Zavrzi",
  /* 259 */ "svetla tema",
  /* 260 */ "temna tema",
  /* 261 */ "vse je nameščeno",
  /* 262 */ "najdeno: {0}",
  /* 263 */ "En razdelek na konzolo, v tabeli. Najgostejše pri miški.",
  /* 264 */ "prazno",
  /* 265 */ "odložite sem, kot romsete iger: FinalBurn Neo išče samo v tej mapi",
  /* 266 */ "doda pozdravni zaslon konzole",
  /* 267 */ "zagonski program naprave",
  /* 268 */ "veliko iger se zažene brez nje; meni konzole ne",
  /* 269 */ "ameriški BIOS",
  /* 270 */ "ameriški in evropski BIOS",
  /* 271 */ "evropski BIOS",
  /* 272 */ "japonski BIOS",
  /* 273 */ "ključi za dešifriranje; brez njih je šifrirana kopija zavrnjena",
  /* 274 */ "mapa Machines iz distribucije blueMSX, z mapo Databases ob njej",
  /* 275 */ "enako",
  /* 276 */ "nujno za igre na CD, nepotrebno za kartice HuCard",
  /* 277 */ "nujno za igre Mega-CD, nepotrebno za kartuše",
  /* 278 */ "Kickstart 1.3; sicer se PUAE zateče k AROS, ki je prost, a manj združljiv",
  /* 279 */ "Kickstart 3.1; potreben za igre AGA, ki jih A500 ne zmore poganjati",
  /* 280 */ "melonDS privzeto emulira BIOS; pravi je bolj zvest",
  /* 281 */ "mGBA ga ne potrebuje; nekatere igre ga zahtevajo za svoj pozdravni zaslon",
  /* 282 */ "vdelana programska oprema konzole",
  /* 283 */ "vdelana programska oprema naprave",
  /* 284 */ "vdelana programska oprema Panasonic FZ-10; to ime Opera privzeto pričakuje",
  /* 285 */ "melonDS jo spremeni in izvirnik ohrani kot .bak",
  /* 286 */ "pisave",
  /* 287 */ "nastavitve in datum konzole",
  /* 288 */ "brez nje jedro teče, a zaslon ostane črn",
  /* 289 */ "nabor znakov konzole",
  /* 290 */ "ameriška različica, za igre Sega CD iz Združenih držav",
  /* 291 */ "japonska različica, za japonske igre Mega-CD",
  /* 292 */ "posnetki",
  /* 293 */ "posnetkov",
  /* 294 */ "posnetek",
  /* 295 */ "posnetkov",
  /* 296 */ "posnetka",
  /* 297 */ "posnetkov",
  /* 298 */ "jedra",
  /* 299 */ "jeder",
  /* 300 */ "jedro",
  /* 301 */ "jeder",
  /* 302 */ "jedri",
  /* 303 */ "jeder",
  /* 304 */ "emulatorji",
  /* 305 */ "emulatorjev",
  /* 306 */ "emulator",
  /* 307 */ "emulatorjev",
  /* 308 */ "emulatorja",
  /* 309 */ "emulatorjev",
  /* 310 */ "datoteke",
  /* 311 */ "datotek",
  /* 312 */ "datoteka",
  /* 313 */ "datotek",
  /* 314 */ "datoteki",
  /* 315 */ "datotek",
  /* 316 */ "igre",
  /* 317 */ "iger",
  /* 318 */ "igra",
  /* 319 */ "iger",
  /* 320 */ "igri",
  /* 321 */ "iger",
  /* 322 */ "<code>{rom}</code> bo zamenjan s potjo do igre. Brez njega se pot doda na konec — tako pričakuje večina emulatorjev.",
  /* 323 */ "<strong>Zunaj igre gre vse s krmilnikom:</strong> smeri vodijo po knjižnici, oknih in menijski vrstici; <strong>A</strong> potrdi, <strong>B</strong> se vrne nazaj, <strong>Start</strong> odpre menijsko vrstico. Med igro <strong>Select in Start skupaj</strong> vrneta v knjižnico — dva gumba hkrati, saj vsak od njiju služi igri.",
  /* 324 */ "Ni posnetkov. Med igro pritisnite <strong>F12</strong> ali <strong>Select + Y</strong> na krmilniku.",
  /* 325 */ "Vsaka konzola potrebuje svoj emulator. EvaChi jih poišče na uradnem strežniku projekta libretro, <code>buildbot.libretro.com</code>, in jih namesti v svojo mapo. Nič se ne razširja naprej: to so izdaje, ki so jih objavili njihovi avtorji.",
  /* 326 */ "Štiri mesta na igro, shranjena na disku. Vsako dejanje je zapisano pod mestom, zamenjava ali praznjenje pa zahtevata potrditev. <strong>F2</strong> in <strong>F4</strong> — ter <strong>Select + L1</strong> / <strong>Select + R1</strong> na krmilniku — gredo naravnost na krepko označeno mesto, ne da bi karkoli vprašali.",
  /* 327 */ "Vsak emulator teče v svojem procesu: ko pade, EvaChi to vidi in se vrne v knjižnico. Igra v teku je izgubljena, shranjena igra pa morda ni bila zapisana. Če ga umaknete, ostane nameščen, le ponujen ni več. Kadar koli ga lahko obnovite pod <strong>Datoteka → Emulatorji</strong>, na dnu okna.",
  /* 328 */ "Samo ena datoteka za igro na disku <small> Igra na CD-ju pride kot list <code>.cue</code> in toliko datotek <code>.bin</code>, kolikor je imel disk sledi. Zažene se samo list: sledi so skrite, dokler je ta tu. Brez lista ni skrito nič. </small>",
  /* 329 */ "(prazno) ali --fullscreen {rom}",
  /* 330 */ "Sto odstotkov je hitrost same konzole. Pod tem se igra upočasni, nad tem zdrvi — in zvok ji sledi, nižji ali višji. Na igralnem ploščku levo in desno preklapljata s stopnje na naslednjo. Velja samo za notranja jedra: zunanji emulator obdrži svojo.",
  /* 331 */ "Pet konzol hkrati",
  /* 332 */ "Smerni križec",
  /* 333 */ "Od začetnice do naslednje",
  /* 334 */ "V animiranih menijih pet iger hkrati",
  /* 335 */ "Hitrost igre",
  /* 336 */ "Prekliči",
  /* 337 */ "Povlecite okvir ali njegov vogal. S puščicami ga premikate, s tipko Shift pa povečate ali pomanjšate. Če seže čez sliko, se dodajo prosojni pasovi: tako odmaknete pretesen ovitek igre. Na igralnem ploščku okvir premikajo smeri, sprožilci pa nastavljajo velikost.",
  /* 338 */ "Obreži",
  /* 339 */ "Obreži ovitek",
  /* 340 */ "Cela slika",
  /* 341 */ "{0} — ovitek obrezan",
  /* 342 */ "{0} — ni ovitka za obrezovanje",
  /* 343 */ "neberljiv ovitek — {0}",
  /* 344 */ "obrezovanje ni uspelo — {0}",
  /* 345 */ "Obreži ovitek…",
  /* 346 */ "Hitro previjanje naprej, dokler sta obe palici pritisnjeni",
  /* 347 */ "{0} umaknjeno",
  /* 348 */ "Emulator {0} se je ustavil med »{1}«.",
  /* 349 */ "Emulator {0} se je ustavil.",
  /* 350 */ "Emulator se je ustavil",
  /* 351 */ "umik ni mogoč — {0}",
  /* 352 */ "odložite sem: {0}",
  /* 353 */ "manjka sistemska datoteka: {0}",
  /* 354 */ "Zasluge",
  /* 355 */ "Nekomercialna licenca, dobro vedeti pred vsakim prevzemom: {0}.",
  /* 356 */ "EvaChi ne piše nobenega emulatorja: gosti jih. Vsak je samostojen prost projekt, ki so ga napisali drugi in ga EvaChi po potrebi prinese od njegovih avtorjev — niti vrstica njihove kode ni prepisana sem, niti bajt se ne razširja naprej. Imena in licence spodaj so tisti, ki jih vsak projekt navede sam.",
  /* 357 */ "Vrtiljak",
  /* 358 */ "Ovitki od spredaj, konzole na kupu, prah, ki se dviga. Kot razstavni pult.",
  /* 359 */ "Kot vmesnik",
  /* 360 */ "Jezik vmesnika",
  /* 361 */ "Jezik iger",
  /* 362 */ "Jezik iger: {0}. Veljal bo od naslednjega zagona.",
  /* 363 */ "Nazaj",
  /* 364 */ "Išči",
  /* 365 */ "Poišči datoteke",
  /* 366 */ "Išči vrednost",
  /* 367 */ "Drugačna",
  /* 368 */ "Enaka",
  /* 369 */ "Širina",
  /* 370 */ "Projekt libretro objavlja datoteke z goljufijami, eno na igro. EvaChi obdrži le tiste, ki se vaši igri natančno prilegajo — isti naslov, ista regija, ista različica — in raje ne ponudi ničesar kot nekaj približnega: kode, napisane za drugo izdajo, ne pišejo malo vstran, temveč povsem drugam.",
  /* 371 */ "Goljufije",
  /* 372 */ "Manj",
  /* 373 */ "Plošča goljufij",
  /* 374 */ "Več",
  /* 375 */ "Začni znova",
  /* 376 */ "Goljufije",
  /* 377 */ "Goljufije…",
  /* 378 */ "Vrednost",
  /* 379 */ "Je enako",
  /* 380 */ "{0} mogočih naslovov",
  /* 381 */ "{0} datotek nameščenih, {1} odstranjenih",
  /* 382 */ "{0} od {1} iger ima datoteko",
  /* 383 */ "{0} bajtov pomnilnika",
  /* 384 */ "{0} vrednosti izločenih: zunaj pomnilnika te igre",
  /* 385 */ "Za to igro ni datoteke. Plošča „Goljufije…“ v meniju Emulacija jo poišče; sicer iskanje vrednosti deluje pri vsaki igri.",
  /* 386 */ "Zamrznjena",
  /* 387 */ "Zamrzni",
  /* 388 */ "Malo igrajte in nato povejte, kaj je vrednost naredila.",
  /* 389 */ "Igra je bila shranjena ob strani pred prvo goljufijo.",
  /* 390 */ "Iskanje…",
  /* 391 */ "Kar odložite v « drop u'r rom », gre h konzoli, ki jo določa končnica. Kadar si isto končnico deli več konzol — odtisi diskov — EvaChi raje vpraša, kot da bi ugibala.",
  /* 392 */ "Potrditev",
  /* 393 */ "Izbriši shranjeno igro…",
  /* 394 */ "Raztegnitev",
  /* 395 */ "Igra svoje števce hrani v pomnilniku, a ne pove kje. Najdemo jih z izločanjem: poveste, kaj se je zgodilo s številko na zaslonu, EvaChi pa zavrže naslove, pri katerih se ni zgodilo isto.",
  /* 396 */ "Da",
  /* 397 */ "Malo konzol ima razmerja današnjega zaslona, od tod črni pasovi ob straneh. Pri nič slika ohrani svoja razmerja; pri sto zapolni okno, pa čeprav se raztegne.",
  /* 398 */ "Pospravljanje iger",
  /* 399 */ "Pospravi",
  /* 400 */ "Pospravi odložene igre…",
  /* 401 */ "Vidite 47 življenj: v polje « Vrednost » vpišite 47 in pritisnite « Išči ». Izgubite eno, vpišite 46 in pritisnite « Je enako ». Če številka ni nikjer zapisana, pustite « Vrednost » prazno in med dvema trenutkoma igre recite le « Več », « Manj », « Drugačna » ali « Enaka ». Najdeno vrednost nato zadrži « Zamrzni ». « Širina » je velikost številke: 1 do 255, 2 nad tem, 4 za velike števce.",
  /* 402 */ "pospravljeno: {0}",
  /* 403 */ "ni shranjene igre za brisanje",
  /* 404 */ "Gumbi",
  /* 405 */ "Že v knjižnici: {0}",
  /* 406 */ "Izbrišem shranjeno igro {0} in začnem od začetka? Igra, ki teče, se bo ustavila, tisto, kar si je igra zapisala, pa bo izgubljeno.",
  /* 407 */ "Sprožilca",
  /* 408 */ "Obdrži oboje",
  /* 409 */ "Pusti v mapi",
  /* 410 */ "Mapa je prazna.",
  /* 411 */ "Zamenjam mesto {0}? Kar je shranjeno tam, bo izgubljeno.",
  /* 412 */ "shranjena igra izbrisana — {0}",
  /* 413 */ "Sistem",
  /* 414 */ "Izpraznim mesto {0}? Kar je shranjeno tam, bo izgubljeno.",
  /* 415 */ "Mrtva cona je tisti del ročice, v katerem velja, da še miruje. Premajhna — lik se sam premakne, čeprav krmilnik leži na mizi; prevelika — drobni gibi se izgubijo. Nekatere igre zahtevajo, da konzolo stresete: kadar krmilnik tega ne zna začutiti, spodnji dve tipki igro o tem prepričata.",
  /* 416 */ "Ročica",
  /* 417 */ "Samostojni emulatorji imajo svoje tipke, v svojih datotekah. Kar spremenite tukaj, se tja prenese takoj — za tiste, katerih zapis poznamo iz prve roke: PCSX2, PPSSPP in Dolphin. Stara nastavitev se ob prvem prehodu odloži vstran, pod istim imenom s končnico « .avant-evachi ».",
  /* 418 */ "Prenesi v zunanje emulatorje",
  /* 419 */ "Mrtva cona",
  /* 420 */ "Projekcija",
  /* 421 */ "Glina",
  /* 422 */ "noben zunanji emulator še ni zapisal svojih nastavitev",
  /* 423 */ "Žerjavica",
  /* 424 */ "Pepel",
  /* 425 */ "Češnja",
  /* 426 */ "Korala",
  /* 427 */ "Sveženj kart",
  /* 428 */ "Gozd",
  /* 429 */ "Ivje",
  /* 430 */ "zunanji emulatorji so te tipke že imeli",
  /* 431 */ "Polnoč",
  /* 432 */ "Mah",
  /* 433 */ "Neon",
  /* 434 */ "Sliva",
  /* 435 */ "Pesek",
  /* 436 */ "Stresi",
  /* 437 */ "Sepija",
  /* 438 */ "prenesene tipke: {0}",
  /* 439 */ "Turkiz",
  /* 440 */ "Ovitki, držani v pahljači, kot karte v roki. Zapestje se zasuka in karta, ki jo bereš, se vzravna.",
  /* 441 */ "Temna dvorana, snop, poln prahu, in igra, projicirana na veliko. Preostale čakajo v predalu.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Marelica",
  /* 444 */ "Vresje",
  /* 445 */ "Karamela",
  /* 446 */ "Baker",
  /* 447 */ "Črnilo",
  /* 448 */ "Famicom",
  /* 449 */ "Žad",
  /* 450 */ "Borovnica",
  /* 451 */ "Nevihta",
  /* 452 */ "Biser",
  /* 453 */ "Pistacija",
  /* 454 */ "Brez",
  /* 455 */ "Vrstice",
  /* 456 */ "Vsaka slikovna pika v treh režah: rdeči, zeleni in modri",
  /* 457 */ "Slika jedra, piko za piko",
  /* 458 */ "Izbočeno steklo, vrstice, reže in ugasli robovi",
  /* 459 */ "Rešetka",
  /* 460 */ "Slikovna cev",
  /* 461 */ "Vsaka druga vrstica potemnjena, kot na televiziji",
  /* 462 */ "Odpre emulator v njegovem lastnem oknu, brez igre",
  /* 463 */ "Odpri",
];
