/**
 * Suédois — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * numéros mis en commentaire devant chaque ligne sont là pour qu'on puisse
 * le vérifier à l'œil.
 */

export const sv: readonly string[] = [
  /* 1 */ "Med handkontroll",
  /* 2 */ "A starta · X favorit · L1/R1 konsoler · L2/R2 bokstav · B tillbaka · Start",
  /* 3 */ "Om EvaChi",
  /* 4 */ "Om…",
  /* 5 */ "På väg: filter för bildrör, pixelrutnät och sveplinjer. Platsen är förberedd, filtren landar här.",
  /* 6 */ "Uppdatera biblioteket",
  /* 7 */ "Visa",
  /* 8 */ "Visa spelens omslag",
  /* 9 */ "Hjälp",
  /* 10 */ "Lägg till en spelmapp…",
  /* 11 */ "Lägg till en mapp…",
  /* 12 */ "Tryck på en knapp på handkontrollen: motsvarande tangent tänds. Vill du ändra en, slår du på omtilldelning, klickar på tangenten du vill ändra och trycker sedan på knappen du vill ha.",
  /* 13 */ "Argument",
  /* 14 */ "Med tangentbord",
  /* 15 */ "Inga spel",
  /* 16 */ "Ingen handkontroll hittad.",
  /* 17 */ "Bibliotek",
  /* 18 */ "Valljud med handkontrollen",
  /* 19 */ "Vissa konsoler startar inte utan sin ursprungliga firmware. EvaChi kan inte tillhandahålla den: det är upphovsrättsskyddad kod, som kopieras från den maskin man själv äger. Däremot säger den vilken som saknas, under vilket namn, och var den ska läggas.",
  /* 20 */ "Dessa konsoler har ingen libretro-kärna: deras emulator är ett eget program, som EvaChi installerar hos sig och startar rakt in i spelet — utan att gå via emulatorns egen meny. Spelen, nycklarna och systemfilerna får du ordna själv.",
  /* 21 */ "Dessa inställningar rör bara de interna kärnorna. En extern emulator har sina egna, och EvaChi blandar sig inte i dem.",
  /* 22 */ "Dessa erbjuds inte längre: de svarade inte när de tillfrågades, eller de fick EvaChi att falla. Att ta tillbaka dem installerar dem inte om — det sätter dem bara tillbaka i listan.",
  /* 23 */ "Läs in tillstånd",
  /* 24 */ "Bara interna kärnor. Klicka på ett kortkommando och tryck sedan på tangenten eller knappen du vill ha; med handkontrollen tar vi två knappar i taget, för var och en av dem används redan i spelet.",
  /* 25 */ "Styrning",
  /* 26 */ "Styrning…",
  /* 27 */ "Senaste konsolerna",
  /* 28 */ "Lägg till en annan emulator",
  /* 29 */ "Riktningar / vänster spak",
  /* 30 */ "Spelmappar",
  /* 31 */ "Ställ undan den här emulatorn",
  /* 32 */ "De hämtas från libretro-projektets miniatyrbildsserver, vid behov. Utan bock frågar biblioteket inte nätet om någonting.",
  /* 33 */ "Sparplatser",
  /* 34 */ "Sparplatser…",
  /* 35 */ "Emulatorer",
  /* 36 */ "Undanställda emulatorer",
  /* 37 */ "Externa emulatorer",
  /* 38 */ "Externa emulatorer…",
  /* 39 */ "Emulatorer…",
  /* 40 */ "Emulering",
  /* 41 */ "Under spel, tillbaka till biblioteket — två knappar i taget, för var och en av dem används i spelet",
  /* 42 */ "Spara",
  /* 43 */ "Filändelser",
  /* 44 */ "Stäng",
  /* 45 */ "Arkiv",
  /* 46 */ "Systemfiler du installerar själv",
  /* 47 */ "Galleri",
  /* 48 */ "Hantera mappar…",
  /* 49 */ "Grafik",
  /* 50 */ "Grafik…",
  /* 51 */ "Visa mappen där dina spel ligger.",
  /* 52 */ "Installation",
  /* 53 */ "Installera de valda",
  /* 54 */ "Installera emulatorer…",
  /* 55 */ "Tolk",
  /* 56 */ "Du behöver inte veta vart: visa mappen där allt ligger huller om buller — BIOS, nycklar, firmware, arkiv, undermappar och allt — och EvaChi bär varje fil dit den hör hemma, både för kärnorna och för de fristående emulatorerna. Det ingen efterfrågar blir liggande.",
  /* 57 */ "Omslag",
  /* 58 */ "Logg",
  /* 59 */ "Logg…",
  /* 60 */ "Förra gången slutade illa",
  /* 61 */ "Starta spelet, bekräfta",
  /* 62 */ "Språk",
  /* 63 */ "Valet behålls från en start till nästa. Vart och ett har kontrollerats läsbart: texten håller överallt tillräcklig kontrast mot sin bakgrund.",
  /* 64 */ "Behåll den",
  /* 65 */ "Emulatorerna nedan är redan inställda — argument och format och allt. EvaChi letar efter dem på din disk; den installerar dem inte.",
  /* 66 */ "Ursprungliga tilldelningar",
  /* 67 */ "Utjämning",
  /* 68 */ "Gör spelet till favorit, eller ta bort det igen",
  /* 69 */ "Musik i den rörliga menyn",
  /* 70 */ "Namn",
  /* 71 */ "Öppna menyraden",
  /* 72 */ "Öppna mappen",
  /* 73 */ "Öppna mappen…",
  /* 74 */ "Öppna ett spel…",
  /* 75 */ "per bildruta",
  /* 76 */ "Kärnans inställningar",
  /* 77 */ "Kärnans inställningar…",
  /* 78 */ "Bläddra i biblioteket, fönstren och menyraden",
  /* 79 */ "Bläddra…",
  /* 80 */ "Pausa",
  /* 81 */ "Helskärm",
  /* 82 */ "För konsoler utan libretro-kärna. EvaChi startar programmet med spelet som argument: emulatorn startar rakt in i spelet, utan att gå via sin egen meny.",
  /* 83 */ "Ta en skärmbild",
  /* 84 */ "Visning",
  /* 85 */ "Klar",
  /* 86 */ "Program",
  /* 87 */ "Några utdragna ackord och spridda toner, satta ihop under vägen snarare än inspelade: stycket kommer aldrig tillbaka till samma ställe. Det tystnar av sig själv så snart ett spel startar.",
  /* 88 */ "Röj upp en mapp…",
  /* 89 */ "Tilldela om…",
  /* 90 */ "Sök efter ett spel…",
  /* 91 */ "Nollställ",
  /* 92 */ "Tillbaka till biblioteket",
  /* 93 */ "Gå tillbaka, stäng igen",
  /* 94 */ "Snabbsparning",
  /* 95 */ "Spara tillstånd",
  /* 96 */ "Shaders",
  /* 97 */ "Ljud",
  /* 98 */ "Start",
  /* 99 */ "Bildstorlek",
  /* 100 */ "Teman",
  /* 101 */ "Teman…",
  /* 102 */ "En fil per spel…",
  /* 103 */ "Ett kort tick när du byter spel, ett till när du startar det. Bara med handkontrollen: med mus och tangentbord känns rörelsen redan.",
  /* 104 */ "Hastighet",
  /* 105 */ "Se skärmbilderna…",
  /* 106 */ "Du kan nöja dig med att installera några av dem — bara konsoler vars emulator är installerad syns i biblioteket.",
  /* 107 */ "{0} — inläst",
  /* 108 */ "{0} — högerklicka för att tömma",
  /* 109 */ "{0} — gjord till favorit",
  /* 110 */ "{0} — nollställd",
  /* 111 */ "{0} — tagen ur favoriterna",
  /* 112 */ "{0} — hämtas…",
  /* 113 */ "{0}: misslyckades, se loggen",
  /* 114 */ "{0} tillgängliga",
  /* 115 */ "{0} har sparats",
  /* 116 */ "{0} är en extern emulator: den startas, den bor inte här",
  /* 117 */ "{0} bilder/s",
  /* 118 */ "{0} installerad",
  /* 119 */ "{0} installerad — {1}",
  /* 120 */ "{0} installerad och klar",
  /* 121 */ "{0} installerade, {1} misslyckades — se loggen",
  /* 122 */ "{0} tillbaka i listan",
  /* 123 */ "{0} borttagen",
  /* 124 */ "{0} av {1}",
  /* 125 */ "{0} på disken, men ingen installerad kärna öppnar dem.",
  /* 126 */ "hämtas från {0}, sedan ”Bläddra…”",
  /* 127 */ "att hämta",
  /* 128 */ "saknas, valfri",
  /* 129 */ "Aktivera",
  /* 130 */ "Mjuk",
  /* 131 */ "gick inte att lägga till — {0}",
  /* 132 */ "Anpassa",
  /* 133 */ "Bärnsten",
  /* 134 */ "Skiffer",
  /* 135 */ "stopp — {0}",
  /* 136 */ "tvärstopp förra gången — {0}",
  /* 137 */ "ingen",
  /* 138 */ "ingen kärna kom tillbaka, fast {0} var kända — tidigare lista behållen",
  /* 139 */ "ingen emulator",
  /* 140 */ "Ingen emulator installerad",
  /* 141 */ "Inget spel känns igen",
  /* 142 */ "Inga träffar",
  /* 143 */ "ingen",
  /* 144 */ "biblioteket gick inte att läsa — {0}",
  /* 145 */ "ansluten",
  /* 146 */ "skärmbild",
  /* 147 */ "Byt omslag…",
  /* 148 */ "Byt…",
  /* 149 */ "Varje pixel blir nio",
  /* 150 */ "Varje pixel blir fyra: skarpt, utan förvrängning",
  /* 151 */ "Varje pixel blir sexton — för stora skärmar",
  /* 152 */ "Läs in",
  /* 153 */ "Välj ett omslag…",
  /* 154 */ "välj först ett spel i biblioteket",
  /* 155 */ "kärna: {0}",
  /* 156 */ "kärnan är inte installerad",
  /* 157 */ "Installerade kärnor",
  /* 158 */ "libretro-kärnor",
  /* 159 */ "Hög kontrast",
  /* 160 */ "inbyggt skal: {0}",
  /* 161 */ "ofullständig urlastning — {0}",
  /* 162 */ "letar: {0}",
  /* 163 */ "letandet avbröts — {0}",
  /* 164 */ "Peka själv ut programmet för {0}",
  /* 165 */ "mapp tillagd: {0}",
  /* 166 */ "mapp öppnad: {0}",
  /* 167 */ "Standardmapp",
  /* 168 */ "Tillagda mappar",
  /* 169 */ "Esc",
  /* 170 */ "Plats {0}",
  /* 171 */ "plats {0} — {1}",
  /* 172 */ "Emulator för den här mappen",
  /* 173 */ "externa emulatorer",
  /* 174 */ "pågår",
  /* 175 */ "på plats",
  /* 176 */ "gick inte att spara — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi kan hämta dem från libretros officiella byggserver. Välj de konsoler du är ute efter.",
  /* 179 */ "EvaChi stannade medan den startade ”{0}”, med emulatorn {1}.",
  /* 180 */ "EvaChi stannade, med emulatorn {0}.",
  /* 181 */ "external_systems → {0} emulatorer angivna",
  /* 182 */ "Favorit",
  /* 183 */ "Favoriter",
  /* 184 */ "systemfilerna gick inte att läsa — {0}",
  /* 185 */ "Piltangenter",
  /* 186 */ "Game Boy",
  /* 187 */ "Rutnät",
  /* 188 */ "det saknas {0} för installerade konsoler",
  /* 189 */ "installationen klar: {0}",
  /* 190 */ "Installerar…",
  /* 191 */ "installerad",
  /* 192 */ "installerad av EvaChi",
  /* 193 */ "Installera",
  /* 194 */ "tolk: {0}",
  /* 195 */ "frågar de installerade kärnorna…",
  /* 196 */ "Starta",
  /* 197 */ "Starta det valda spelet",
  /* 198 */ "Lavendel",
  /* 199 */ "Konsolerna på rad, spelen i kolumn, en bakgrund som böljar. Som på en vardagsrumskonsol.",
  /* 200 */ "Kanterna flyter ihop — närmare en gammal tv",
  /* 201 */ "Omslagen i stort format, bläddrade med handkontrollen. Tänkt för soffan.",
  /* 202 */ "Pixlarna förblir kvadratiska, som på den ursprungliga maskinen",
  /* 203 */ "handkontrollens tilldelningar satta tillbaka till ursprunget",
  /* 204 */ "list_cores → {0} kärnor anmälda",
  /* 205 */ "Lista",
  /* 206 */ "kärnlistan är inte tillgänglig — {0}",
  /* 207 */ "emulatorlistan är inte tillgänglig — {0}",
  /* 208 */ "Handkontroll",
  /* 209 */ "handkontroll: {0}",
  /* 210 */ "Handkontroll: {0}",
  /* 211 */ "handkontrollen kopplades ur",
  /* 212 */ "SAKNAS",
  /* 213 */ "Mynta",
  /* 214 */ "Rörlig meny",
  /* 215 */ "Uppdatera",
  /* 216 */ "Gör till favorit",
  /* 217 */ "ställd undan: {0} · {1}",
  /* 218 */ "mindre än en minut",
  /* 219 */ "Skarp",
  /* 220 */ "namn, program och filändelser behövs alla tre",
  /* 221 */ "NEJ",
  /* 222 */ "inte installerad på den här maskinen",
  /* 223 */ "Rosa natt",
  /* 224 */ "Ocean",
  /* 225 */ "eller",
  /* 226 */ "ja",
  /* 227 */ "gick inte att öppna — {0}",
  /* 228 */ "webbsida: bara de interna kärnorna finns, utan bibliotek",
  /* 229 */ "Papper",
  /* 230 */ "standard",
  /* 231 */ "Bläddra i rutnätet och den rörliga menyn",
  /* 232 */ "helskärm nekades — {0}",
  /* 233 */ "tryck på knappen du vill ha på handkontrollen",
  /* 234 */ "tryck på en tangent…",
  /* 235 */ "upprensning: {0} · {1}",
  /* 236 */ "gick inte att röja upp — {0}",
  /* 237 */ "letandet efter emulatorer avbröts — {0}",
  /* 238 */ "Stänga ett fönster",
  /* 239 */ "gick inte att nollställa — {0}",
  /* 240 */ "Fyller fönstret och behåller proportionerna",
  /* 241 */ "Fortsätt",
  /* 242 */ "Fortsätt från den här sparningen — högerklicka för att tömma den",
  /* 243 */ "Ta tillbaka",
  /* 244 */ "gick inte att ta tillbaka — {0}",
  /* 245 */ "Ta bort",
  /* 246 */ "Ta bort från favoriter",
  /* 247 */ "Ta bort omslaget",
  /* 248 */ "gick inte att ta bort — {0}",
  /* 249 */ "inget att röja upp",
  /* 250 */ "inget hindrar",
  /* 251 */ "Inget matchar ”{0}”.",
  /* 252 */ "Rosa och vitt",
  /* 253 */ "utan bild",
  /* 254 */ "Spara",
  /* 255 */ "Spara här",
  /* 256 */ "gick inte att välja — {0}",
  /* 257 */ "Konsolens ursprungliga storlek, pixel för pixel",
  /* 258 */ "Avsluta",
  /* 259 */ "ljust tema",
  /* 260 */ "mörkt tema",
  /* 261 */ "allt är installerat",
  /* 262 */ "hittade: {0}",
  /* 263 */ "En avdelning per konsol, i tabell. Tätast med mus.",
  /* 264 */ "tom",
  /* 265 */ "läggs här, som spelens romset: FinalBurn Neo letar bara i den här mappen",
  /* 266 */ "lägger till konsolens startskärm",
  /* 267 */ "maskinens startkod",
  /* 268 */ "många spel startar utan den; konsolens meny gör det inte",
  /* 269 */ "amerikanskt BIOS",
  /* 270 */ "amerikanskt och europeiskt BIOS",
  /* 271 */ "europeiskt BIOS",
  /* 272 */ "japanskt BIOS",
  /* 273 */ "avkrypteringsnycklar; utan dem avvisas en krypterad avbild",
  /* 274 */ "mappen med maskinerna från blueMSX-distributionen, med Databases intill",
  /* 275 */ "detsamma",
  /* 276 */ "nödvändigt för CD-spel, onödigt för HuCard-kort",
  /* 277 */ "nödvändigt för Mega-CD-spel, onödigt för kassetter",
  /* 278 */ "Kickstart 1.3; annars faller PUAE tillbaka på AROS, fritt men mindre kompatibelt",
  /* 279 */ "Kickstart 3.1; behövs för AGA-spel, som A500 inte kan köra",
  /* 280 */ "melonDS emulerar BIOS som standard; det äkta är mer trovärdigt",
  /* 281 */ "mGBA klarar sig utan; några spel kräver den för sin startskärm",
  /* 282 */ "konsolens firmware",
  /* 283 */ "maskinens firmware",
  /* 284 */ "firmware från Panasonic FZ-10; det är det namnet Opera tar som standard",
  /* 285 */ "ändras av melonDS, som bevarar originalet som .bak",
  /* 286 */ "teckensnitt",
  /* 287 */ "konsolens inställningar och datum",
  /* 288 */ "utan den går kärnan, men skärmen förblir svart",
  /* 289 */ "konsolens teckentabell",
  /* 290 */ "amerikansk variant, för Sega CD-spel från USA",
  /* 291 */ "japansk variant, för japanska Mega-CD-spel",
  /* 292 */ "skärmbilder",
  /* 293 */ "skärmbilder",
  /* 294 */ "skärmbild",
  /* 295 */ "skärmbilder",
  /* 296 */ "skärmbilder",
  /* 297 */ "skärmbilder",
  /* 298 */ "kärnor",
  /* 299 */ "kärnor",
  /* 300 */ "kärna",
  /* 301 */ "kärnor",
  /* 302 */ "kärnor",
  /* 303 */ "kärnor",
  /* 304 */ "emulatorer",
  /* 305 */ "emulatorer",
  /* 306 */ "emulator",
  /* 307 */ "emulatorer",
  /* 308 */ "emulatorer",
  /* 309 */ "emulatorer",
  /* 310 */ "filer",
  /* 311 */ "filer",
  /* 312 */ "fil",
  /* 313 */ "filer",
  /* 314 */ "filer",
  /* 315 */ "filer",
  /* 316 */ "spel",
  /* 317 */ "spel",
  /* 318 */ "spel",
  /* 319 */ "spel",
  /* 320 */ "spel",
  /* 321 */ "spel",
  /* 322 */ "<code>{rom}</code> ersätts med spelets sökväg. Utan den läggs sökvägen till på slutet — och det är vad de flesta emulatorer väntar sig.",
  /* 323 */ "<strong>Utanför spelet sköts allt med handkontrollen:</strong> riktningarna för dig genom biblioteket, fönstren och menyraden; <strong>A</strong> bekräftar, <strong>B</strong> går tillbaka, <strong>Start</strong> öppnar menyraden. Under spel för <strong>Select och Start tillsammans</strong> dig tillbaka till biblioteket — två knappar i taget, för var och en av dem används i spelet.",
  /* 324 */ "Inga skärmbilder. Tryck <strong>F12</strong> under spel, eller <strong>Select + Y</strong> på handkontrollen.",
  /* 325 */ "Varje konsol behöver sin emulator. EvaChi hämtar dem från libretro-projektets officiella byggserver, <code>buildbot.libretro.com</code>, och installerar dem i sin egen mapp. Ingenting sprids vidare: det är de utgåvor som upphovsmännen själva har gett ut.",
  /* 326 */ "Fyra platser per spel, sparade på disken. Platsen i fetstil är den som <strong>F2</strong> och <strong>F4</strong> använder — och <strong>Select + L1</strong> / <strong>Select + R1</strong> på handkontrollen. Högerklicka på en plats för att tömma den.",
  /* 327 */ "En emulator körs i samma fönster som EvaChi: när den faller tar den EvaChi med sig, utan ett ord. Att ställa undan emulatorn låter den vara installerad men slutar erbjuda den. Du kan ta tillbaka den när du vill från <strong>Arkiv → Emulatorer</strong>, längst ned i fönstret.",
  /* 328 */ "En fil per spel på disken <small> Ett CD-spel kommer som ett <code>.cue</code>-blad och lika många <code>.bin</code>-filer som skivan hade spår. Bara bladet startas: spåren göms när det finns. Utan blad göms ingenting. </small>",
  /* 329 */ "(tomt) eller --fullscreen {rom}",
];
