/**
 * Swahili — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * marques numérotées sont là pour qu'on puisse le vérifier à l'œil.
 */

export const sw: readonly string[] = [
  /* 1 */ "Kwa kidhibiti",
  /* 2 */ "A anzisha · X kipendwa · Y punguza · L1/R1 konsoli · L2/R2 herufi · B rudi",
  /* 3 */ "Kuhusu EvaChi",
  /* 4 */ "Kuhusu…",
  /* 5 */ "Yanakuja: vichujio vya mrija wa katodi, gridi ya pikseli, mistari ya kuchanganua. Nafasi ipo tayari, vichujio vitawekwa hapa.",
  /* 6 */ "Sasisha maktaba",
  /* 7 */ "Onyesho",
  /* 8 */ "Onyesha majalada ya michezo",
  /* 9 */ "Msaada",
  /* 10 */ "Ongeza folda ya michezo…",
  /* 11 */ "Ongeza folda…",
  /* 12 */ "Bonyeza kitufe chochote cha kidhibiti: kitufe cha kibodi kinacholingana kinawaka. Ili kubadilisha kimoja, ingia katika hali ya kupanga upya, bofya kitufe unachotaka kubadilisha, kisha bonyeza kitufe cha kidhibiti unachokitaka.",
  /* 13 */ "Vigezo",
  /* 14 */ "Kwa kibodi",
  /* 15 */ "Hakuna mchezo",
  /* 16 */ "Hakuna kidhibiti kilichotambuliwa.",
  /* 17 */ "Maktaba",
  /* 18 */ "Sauti za uteuzi kwa kidhibiti",
  /* 19 */ "Konsoli nyingine haziwashi bila programu yao ya awali ya kudumu. EvaChi haiwezi kuitoa: ni msimbo wenye hakimiliki, unaonakiliwa kutoka kwenye mashine unayomiliki. Badala yake, inakuambia ipi inakosekana, kwa jina gani, na wapi kuiweka.",
  /* 20 */ "Konsoli hizi hazina kiini cha libretro: emulata yao ni programu ya pekee, ambayo EvaChi inaisakinisha kwenye folda yake na kuianzisha moja kwa moja kwenye mchezo — bila kupitia menyu yake. Michezo, funguo na faili za mfumo zinasalia kuwa jukumu lako.",
  /* 21 */ "Mipangilio hii inagusa viini vya ndani pekee. Emulata ya nje ina yake, na EvaChi haiingilii.",
  /* 22 */ "Hizi hazipendekezwi tena: hazikujibu maswali, au ziliangusha EvaChi. Kuzirejesha hakuzisakinishi upya — kunazirudisha tu kwenye orodha.",
  /* 23 */ "Pakia hali",
  /* 24 */ "Viini vya ndani pekee. Bofya njia ya mkato kisha bonyeza kitufe au kitufe cha kidhibiti unachokitaka; kwa kidhibiti tunachukua vitufe viwili kwa pamoja, kwa sababu kila kimoja kinatumika tayari kwenye mchezo.",
  /* 25 */ "Udhibiti",
  /* 26 */ "Udhibiti…",
  /* 27 */ "Konsoli za hivi karibuni",
  /* 28 */ "Tangaza emulata nyingine",
  /* 29 */ "Mielekeo / kijiti cha kushoto",
  /* 30 */ "Folda za michezo",
  /* 31 */ "Weka emulata hii kando",
  /* 32 */ "Yanatoka kwenye seva ya vijipicha ya mradi wa libretro, yanapohitajika. Ukiondoa alama, maktaba haiombi kitu chochote kwenye mtandao.",
  /* 33 */ "Nafasi za kuhifadhi",
  /* 34 */ "Nafasi…",
  /* 35 */ "Emulata",
  /* 36 */ "Emulata zilizowekwa kando",
  /* 37 */ "Emulata za nje",
  /* 38 */ "Emulata za nje…",
  /* 39 */ "Emulata…",
  /* 40 */ "Uigaji",
  /* 41 */ "Wakati wa mchezo, kurudi kwenye maktaba — vitufe viwili kwa pamoja, kwa sababu kila kimoja kinatumika kwenye mchezo",
  /* 42 */ "Hifadhi",
  /* 43 */ "Viendelezi",
  /* 44 */ "Funga",
  /* 45 */ "Faili",
  /* 46 */ "Faili za mfumo za kuweka mwenyewe",
  /* 47 */ "Matunzio",
  /* 48 */ "Dhibiti folda…",
  /* 49 */ "Grafiki",
  /* 50 */ "Grafiki…",
  /* 51 */ "Onyesha folda ambapo michezo yako imo.",
  /* 52 */ "Usakinishaji",
  /* 53 */ "Sakinisha zilizochaguliwa",
  /* 54 */ "Sakinisha emulata…",
  /* 55 */ "Mkalimani",
  /* 56 */ "Si lazima ujue wapi: onyesha folda ambapo kila kitu kimetapakaa — BIOS, funguo, programu za kudumu, faili zilizobanwa, pamoja na folda ndogo — na EvaChi inapeleka kila faili mahali pake, kwa viini na kwa emulata za pekee. Kile ambacho hakuna anayekihitaji hakiondolewi.",
  /* 57 */ "Majalada",
  /* 58 */ "Kumbukumbu",
  /* 59 */ "Kumbukumbu…",
  /* 60 */ "Mara iliyopita haikuisha vizuri",
  /* 61 */ "Anzisha mchezo, thibitisha",
  /* 62 */ "Lugha",
  /* 63 */ "Chaguo lako linakumbukwa kila unapoanzisha tena. Kila mandhari imepimwa isomeke: maandishi yanabaki na utofautishaji wa kutosha juu ya rangi ya nyuma.",
  /* 64 */ "Ibakize",
  /* 65 */ "Emulata zilizo hapa chini zimeandaliwa tayari — vigezo na miundo ya faili pia. EvaChi inazitafuta kwenye diski yako; haizisakinishi.",
  /* 66 */ "Mipangilio ya awali",
  /* 67 */ "Ulainishaji",
  /* 68 */ "Weka au ondoa mchezo kwenye vipendwa",
  /* 69 */ "Muziki wa menyu ya mwendo",
  /* 70 */ "Jina",
  /* 71 */ "Fungua mwambaa menyu",
  /* 72 */ "Fungua folda",
  /* 73 */ "Fungua folda…",
  /* 74 */ "Fungua mchezo…",
  /* 75 */ "kwa fremu",
  /* 76 */ "Mipangilio ya kiini",
  /* 77 */ "Mipangilio ya kiini…",
  /* 78 */ "Pitia maktaba, madirisha na mwambaa menyu",
  /* 79 */ "Vinjari…",
  /* 80 */ "Simamisha",
  /* 81 */ "Skrini kamili",
  /* 82 */ "Kwa konsoli zisizo na kiini cha libretro. EvaChi inaanzisha programu na mchezo kama kigezo: emulata inaingia moja kwa moja kwenye mchezo, bila kupitia menyu yake yenyewe.",
  /* 83 */ "Piga picha ya skrini",
  /* 84 */ "Mwonekano",
  /* 85 */ "Tayari",
  /* 86 */ "Programu",
  /* 87 */ "Miguno michache iliyoshikiliwa na noti zilizotawanyika, zinazotungwa papo hapo badala ya kurekodiwa: kipande hakipitii mahali pamoja mara mbili. Kinajisimamisha mara mchezo unapoanza.",
  /* 88 */ "Panga folda…",
  /* 89 */ "Panga upya…",
  /* 90 */ "Tafuta mchezo…",
  /* 91 */ "Anzisha upya",
  /* 92 */ "Rudi kwenye maktaba",
  /* 93 */ "Rudi nyuma, funga",
  /* 94 */ "Hifadhi haraka",
  /* 95 */ "Hifadhi hali",
  /* 96 */ "Shaders",
  /* 97 */ "Sauti",
  /* 98 */ "Start",
  /* 99 */ "Ukubwa wa picha",
  /* 100 */ "Mandhari",
  /* 101 */ "Mandhari…",
  /* 102 */ "Faili moja…",
  /* 103 */ "Mtiko mfupi unapobadilisha mchezo, mwingine unapouanzisha. Kwa kidhibiti pekee: kwa kipanya na kibodi, mguso wenyewe unahisiwa.",
  /* 104 */ "Kasi",
  /* 105 */ "Tazama picha za skrini…",
  /* 106 */ "Unaweza kusakinisha chache tu — ni konsoli zenye emulata iliyosakinishwa pekee zinazoonekana kwenye maktaba.",
  /* 107 */ "{0} — imepakiwa",
  /* 108 */ "{0} — bonyeza kulia kufuta",
  /* 109 */ "{0} — imewekwa kipendwa",
  /* 110 */ "{0} — imeanzishwa upya",
  /* 111 */ "{0} — imeondolewa kwenye vipendwa",
  /* 112 */ "{0} — inapakuliwa…",
  /* 113 */ "{0}: imeshindikana, tazama kumbukumbu",
  /* 114 */ "{0} vinapatikana",
  /* 115 */ "{0} imehifadhiwa",
  /* 116 */ "{0} ni emulata ya nje: inaanzishwa tu, haiwekwi ndani ya EvaChi",
  /* 117 */ "{0} fps",
  /* 118 */ "{0} imesakinishwa",
  /* 119 */ "{0} imesakinishwa — {1}",
  /* 120 */ "{0} imesakinishwa na iko tayari",
  /* 121 */ "{0} zimesakinishwa, {1} zimeshindikana — tazama kumbukumbu",
  /* 122 */ "{0} imerejeshwa",
  /* 123 */ "{0} imeondolewa",
  /* 124 */ "{0} kati ya {1}",
  /* 125 */ "{0} zipo kwenye diski, lakini hakuna kiini kilichosakinishwa kinachozifungua.",
  /* 126 */ "ichukue kwenye {0}, kisha “Vinjari…”",
  /* 127 */ "ya kupakua",
  /* 128 */ "haipo, si lazima",
  /* 129 */ "Wezesha",
  /* 130 */ "Laini",
  /* 131 */ "kuongeza kumeshindikana — {0}",
  /* 132 */ "Toshesha",
  /* 133 */ "Kaharabu",
  /* 134 */ "Jivu",
  /* 135 */ "imesimama — {0}",
  /* 136 */ "ilikatika ghafla mara iliyopita — {0}",
  /* 137 */ "hakuna",
  /* 138 */ "hakuna kiini kilichorudishwa ilhali {0} vilijulikana — orodha ya awali imehifadhiwa",
  /* 139 */ "hakuna emulata",
  /* 140 */ "Hakuna emulata iliyosakinishwa",
  /* 141 */ "Hakuna mchezo uliotambuliwa",
  /* 142 */ "Hakuna matokeo",
  /* 143 */ "hakuna",
  /* 144 */ "maktaba haisomeki — {0}",
  /* 145 */ "imeunganishwa",
  /* 146 */ "picha ya skrini",
  /* 147 */ "Badilisha jalada…",
  /* 148 */ "Badilisha…",
  /* 149 */ "Kila pikseli inakuwa tisa",
  /* 150 */ "Kila pikseli inakuwa nne: kali, bila kupotoshwa",
  /* 151 */ "Kila pikseli inakuwa kumi na sita — kwa skrini kubwa",
  /* 152 */ "Pakia",
  /* 153 */ "Chagua jalada…",
  /* 154 */ "chagua kwanza mchezo kwenye maktaba",
  /* 155 */ "kiini: {0}",
  /* 156 */ "kiini hakijasakinishwa",
  /* 157 */ "Viini vilivyosakinishwa",
  /* 158 */ "viini vya libretro",
  /* 159 */ "Utofautishaji mkubwa",
  /* 160 */ "ganda asilia: {0}",
  /* 161 */ "kuondoa kiini hakukukamilika — {0}",
  /* 162 */ "ugunduzi: {0}",
  /* 163 */ "ugunduzi umekatika — {0}",
  /* 164 */ "Onyesha mwenyewe programu ya {0}",
  /* 165 */ "folda imeongezwa: {0}",
  /* 166 */ "folda imefunguliwa: {0}",
  /* 167 */ "Folda chaguo-msingi",
  /* 168 */ "Folda zilizoongezwa",
  /* 169 */ "Esc",
  /* 170 */ "Nafasi {0}",
  /* 171 */ "nafasi {0} — {1}",
  /* 172 */ "Emulata inayotumika kwa folda hii",
  /* 173 */ "emulata za nje",
  /* 174 */ "inaendelea",
  /* 175 */ "ipo",
  /* 176 */ "kuhifadhi kumeshindikana — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi inaweza kuzipakua kutoka kwenye seva rasmi ya ujenzi ya libretro. Chagua konsoli zinazokuvutia.",
  /* 179 */ "EvaChi ilisimama ilipoanzisha “{0}”, kwa emulata {1}.",
  /* 180 */ "EvaChi ilisimama, kwa emulata {0}.",
  /* 181 */ "external_systems → emulata {0} zilizotangazwa",
  /* 182 */ "Kipendwa",
  /* 183 */ "Vipendwa",
  /* 184 */ "faili za mfumo hazisomeki — {0}",
  /* 185 */ "Mishale",
  /* 186 */ "Game Boy",
  /* 187 */ "Gridi",
  /* 188 */ "konsoli zilizosakinishwa zinakosa {0}",
  /* 189 */ "usakinishaji umekamilika: {0}",
  /* 190 */ "Inasakinisha…",
  /* 191 */ "imesakinishwa",
  /* 192 */ "imesakinishwa na EvaChi",
  /* 193 */ "Sakinisha",
  /* 194 */ "mkalimani: {0}",
  /* 195 */ "kuuliza viini vilivyosakinishwa…",
  /* 196 */ "Anzisha",
  /* 197 */ "Anzisha mchezo uliochaguliwa",
  /* 198 */ "Lavenda",
  /* 199 */ "Konsoli mstari mmoja, michezo safu moja, mandhari ya nyuma inayoyumba. Kama konsoli ya sebuleni.",
  /* 200 */ "Kingo zinalainishwa — karibu zaidi na televisheni ya zamani",
  /* 201 */ "Majalada makubwa, yanapitiwa kwa kidhibiti. Yamefikiriwa kwa sofa.",
  /* 202 */ "Pikseli zinabaki mraba, kama kwenye mashine ya awali",
  /* 203 */ "mipangilio ya kidhibiti imerejeshwa ya awali",
  /* 204 */ "list_cores → viini {0} vilivyotangazwa",
  /* 205 */ "Orodha",
  /* 206 */ "orodha ya viini haipatikani — {0}",
  /* 207 */ "orodha ya emulata haipatikani — {0}",
  /* 208 */ "Kidhibiti",
  /* 209 */ "kidhibiti: {0}",
  /* 210 */ "Kidhibiti: {0}",
  /* 211 */ "kidhibiti kimechomolewa",
  /* 212 */ "HAIPO",
  /* 213 */ "Mnanaa",
  /* 214 */ "Menyu ya mwendo",
  /* 215 */ "Sasisha",
  /* 216 */ "Weka kipendwa",
  /* 217 */ "imewekwa kando: {0} · {1}",
  /* 218 */ "chini ya dakika moja",
  /* 219 */ "Kali",
  /* 220 */ "jina, programu na viendelezi vyote vinahitajika",
  /* 221 */ "HAPANA",
  /* 222 */ "haijasakinishwa kwenye mashine hii",
  /* 223 */ "Usiku wa waridi",
  /* 224 */ "Bahari",
  /* 225 */ "au",
  /* 226 */ "ndiyo",
  /* 227 */ "kufungua kumeshindikana — {0}",
  /* 228 */ "ukurasa wa tovuti: viini vya ndani pekee vinapatikana, bila maktaba",
  /* 229 */ "Karatasi",
  /* 230 */ "chaguo-msingi",
  /* 231 */ "Pitia gridi na menyu ya mwendo",
  /* 232 */ "skrini kamili imekataliwa — {0}",
  /* 233 */ "bonyeza kitufe unachokitaka kwenye kidhibiti",
  /* 234 */ "bonyeza kitufe…",
  /* 235 */ "upangaji: {0} · {1}",
  /* 236 */ "upangaji umeshindikana — {0}",
  /* 237 */ "utafutaji wa emulata umekatika — {0}",
  /* 238 */ "Funga dirisha",
  /* 239 */ "kuanzisha upya kumeshindikana — {0}",
  /* 240 */ "Hujaza dirisha bila kuharibu uwiano",
  /* 241 */ "Endelea",
  /* 242 */ "Endelea kutoka hapa — bonyeza kulia kufuta",
  /* 243 */ "Rejesha",
  /* 244 */ "kurejesha kumeshindikana — {0}",
  /* 245 */ "Ondoa",
  /* 246 */ "Ondoa kwenye vipendwa",
  /* 247 */ "Ondoa jalada",
  /* 248 */ "kuondoa kumeshindikana — {0}",
  /* 249 */ "hakuna cha kupanga",
  /* 250 */ "hakuna kinachozuia",
  /* 251 */ "Hakuna kinacholingana na “{0}”.",
  /* 252 */ "Waridi na nyeupe",
  /* 253 */ "hakuna picha",
  /* 254 */ "Hifadhi",
  /* 255 */ "Hifadhi hapa",
  /* 256 */ "kuchagua kumeshindikana — {0}",
  /* 257 */ "Ukubwa halisi wa konsoli, pikseli kwa pikseli",
  /* 258 */ "Maliza",
  /* 259 */ "mandhari angavu",
  /* 260 */ "mandhari nyeusi",
  /* 261 */ "vyote vimesakinishwa",
  /* 262 */ "imepatikana: {0}",
  /* 263 */ "Kijopo kimoja kwa kila konsoli, katika jedwali. Mpangilio mnene zaidi, kwa kipanya.",
  /* 264 */ "tupu",
  /* 265 */ "iwekwe hapa, kama romsets za michezo: FinalBurn Neo inatafuta katika folda hii pekee",
  /* 266 */ "huongeza skrini ya kuanza ya konsoli",
  /* 267 */ "kianzio cha mashine",
  /* 268 */ "michezo mingi huanza bila hii; menyu ya konsoli haianzi",
  /* 269 */ "BIOS ya Marekani",
  /* 270 */ "BIOS ya Marekani na ya Ulaya",
  /* 271 */ "BIOS ya Ulaya",
  /* 272 */ "BIOS ya Japani",
  /* 273 */ "funguo za kusimbua; bila hizo nakala iliyosimbwa inakataliwa",
  /* 274 */ "folda ya mashine ya usambazaji wa blueMSX, na Databases kando yake",
  /* 275 */ "vivyo hivyo",
  /* 276 */ "lazima kwa michezo ya CD, si lazima kwa kadi za HuCard",
  /* 277 */ "lazima kwa michezo ya Mega-CD, si lazima kwa katriji",
  /* 278 */ "Kickstart 1.3; bila hiyo PUAE inatumia AROS, huru lakini haipatani na michezo mingi",
  /* 279 */ "Kickstart 3.1; inahitajika kwa michezo ya AGA, ambayo A500 haiwezi kuiendesha",
  /* 280 */ "melonDS inaiga BIOS kwa chaguo-msingi; ya kweli ni sahihi zaidi",
  /* 281 */ "mGBA inaweza bila hiyo; michezo michache inaihitaji kwa skrini yao ya kuanza",
  /* 282 */ "programu ya kudumu ya konsoli",
  /* 283 */ "programu ya kudumu ya mashine",
  /* 284 */ "programu ya kudumu ya Panasonic FZ-10; ni jina hili ambalo Opera hutumia kwa chaguo-msingi",
  /* 285 */ "inabadilishwa na melonDS, ambayo huhifadhi ya awali kama .bak",
  /* 286 */ "fonti",
  /* 287 */ "mipangilio na tarehe ya konsoli",
  /* 288 */ "bila hiyo kiini hufanya kazi lakini skrini inabaki nyeusi",
  /* 289 */ "jedwali la herufi za konsoli",
  /* 290 */ "aina ya Marekani, kwa michezo ya Sega CD ya Marekani",
  /* 291 */ "aina ya Japani, kwa michezo ya Mega-CD ya Japani",
  /* 292 */ "picha za skrini",
  /* 293 */ "picha za skrini",
  /* 294 */ "picha ya skrini",
  /* 295 */ "picha za skrini",
  /* 296 */ "picha za skrini",
  /* 297 */ "picha za skrini",
  /* 298 */ "viini",
  /* 299 */ "viini",
  /* 300 */ "kiini",
  /* 301 */ "viini",
  /* 302 */ "viini",
  /* 303 */ "viini",
  /* 304 */ "emulata",
  /* 305 */ "emulata",
  /* 306 */ "emulata",
  /* 307 */ "emulata",
  /* 308 */ "emulata",
  /* 309 */ "emulata",
  /* 310 */ "faili",
  /* 311 */ "faili",
  /* 312 */ "faili",
  /* 313 */ "faili",
  /* 314 */ "faili",
  /* 315 */ "faili",
  /* 316 */ "michezo",
  /* 317 */ "michezo",
  /* 318 */ "mchezo",
  /* 319 */ "michezo",
  /* 320 */ "michezo",
  /* 321 */ "michezo",
  /* 322 */ "<code>{rom}</code> itabadilishwa na njia ya mchezo. Bila hiyo, njia huongezwa mwishoni — ndivyo emulata nyingi zinavyotarajia.",
  /* 323 */ "<strong>Nje ya mchezo, kila kitu kinafanyika kwa kidhibiti:</strong> mielekeo hupitia maktaba, madirisha na mwambaa menyu; <strong>A</strong> huthibitisha, <strong>B</strong> hurudi nyuma, <strong>Start</strong> hufungua mwambaa menyu. Wakati wa mchezo, <strong>Select na Start kwa pamoja</strong> hurudisha kwenye maktaba — vitufe viwili kwa pamoja, kwa sababu kila kimoja kinatumika kwenye mchezo.",
  /* 324 */ "Hakuna picha za skrini. Bonyeza <strong>F12</strong> wakati wa mchezo, au <strong>Select + Y</strong> kwenye kidhibiti.",
  /* 325 */ "Kila konsoli inahitaji emulata yake. EvaChi inazitafuta kwenye seva rasmi ya ujenzi ya mradi wa libretro, <code>buildbot.libretro.com</code>, na kuzisakinisha kwenye folda yake yenyewe. Hakuna kinachosambazwa tena: hizi ni nakala zilizotolewa na waandishi wao.",
  /* 326 */ "Nafasi nne kwa kila mchezo, zimehifadhiwa kwenye diski. Nafasi iliyokolezwa ni ile inayotumiwa na <strong>F2</strong> na <strong>F4</strong> — na <strong>Select + L1</strong> / <strong>Select + R1</strong> kwenye kidhibiti. Bonyeza kulia nafasi ili kuifuta.",
  /* 327 */ "Emulata inafanya kazi katika dirisha lile moja la EvaChi: inapoanguka, inaiangusha nayo, bila neno lolote. Kuweka emulata hii kando inaibakiza imesakinishwa lakini inaacha kuipendekeza. Unaweza kuirejesha wakati wowote kutoka <strong>Faili → Emulata</strong>, chini ya dirisha.",
  /* 328 */ "Faili moja tu kwa kila mchezo kwenye diski <small> Mchezo wa CD huja kama karatasi ya <code>.cue</code> na faili za <code>.bin</code> nyingi kama vipande vilivyokuwa kwenye diski. Ni karatasi pekee inayoanzishwa: vipande vinafichwa ikiwa ipo. Bila karatasi, hakuna kinachofichwa. </small>",
  /* 329 */ "(wazi) au --fullscreen {rom}",
  /* 330 */ "Asilimia mia moja ni kasi ya konsoli yenyewe. Chini ya hapo mchezo hupunguza mwendo, juu yake hukimbia — na sauti hufuata, nzito zaidi au nyembamba zaidi. Kwenye kidhibiti, kushoto na kulia husogeza hatua moja kwa wakati. Ni kwa viini vya ndani tu: emulator ya nje huhifadhi kasi yake.",
  /* 331 */ "Konsoli tano kwa wakati mmoja",
  /* 332 */ "Vitufe vya mwelekeo",
  /* 333 */ "Kutoka herufi moja hadi nyingine",
  /* 334 */ "Kwenye menyu inayosogea, michezo mitano kwa wakati mmoja",
  /* 335 */ "Kasi ya mchezo",
  /* 336 */ "Ghairi",
  /* 337 */ "Buruta fremu, au vuta pembe yake. Mishale huihamisha, na kwa Shift huikuza au kuipunguza. Ikitoka nje ya picha, huongeza kingo za uwazi – ndivyo unavyoonyesha kwa upana zaidi jalada lililobana sana. Kwenye kidhibiti cha mchezo, vitufe vya pande huhamisha, na vifyatuo hurekebisha ukubwa.",
  /* 338 */ "Punguza",
  /* 339 */ "Punguza jalada",
  /* 340 */ "Picha nzima",
  /* 341 */ "{0} — jalada limepunguzwa",
  /* 342 */ "{0} — hakuna jalada la kupunguza",
  /* 343 */ "jalada halisomeki — {0}",
  /* 344 */ "kupunguza kumeshindikana — {0}",
  /* 345 */ "Punguza jalada…",
];
