/**
 * Le turc — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * marques numérotées sont là pour qu'on puisse le vérifier à l'œil.
 *
 * Le turc garde le nom au singulier après un nombre — « 3 oyun », jamais
 * « 3 oyunlar » : les six catégories de pluriel portent donc la même forme.
 */

export const tr: readonly string[] = [
  /* 1 */ "Kumandayla",
  /* 2 */ "A başlat · X favori · L1/R1 konsollar · L2/R2 harf · B geri · Start",
  /* 3 */ "EvaChi hakkında",
  /* 4 */ "Hakkında…",
  /* 5 */ "Yakında: tüplü ekran filtreleri, piksel ızgarası, tarama çizgileri. Yer hazır, filtreler buraya gelecek.",
  /* 6 */ "Kitaplığı yenile",
  /* 7 */ "Görünüm",
  /* 8 */ "Oyun kapaklarını göster",
  /* 9 */ "Yardım",
  /* 10 */ "Oyun klasörü ekle…",
  /* 11 */ "Klasör ekle…",
  /* 12 */ "Kumandanın bir düğmesine basın: karşılık gelen tuş yanar. Bir tuşu değiştirmek için yeniden atamaya geçin, değiştireceğiniz tuşa tıklayın, sonra istediğiniz düğmeye basın.",
  /* 13 */ "Argümanlar",
  /* 14 */ "Klavyeyle",
  /* 15 */ "Oyun yok",
  /* 16 */ "Kumanda algılanmadı.",
  /* 17 */ "Kitaplık",
  /* 18 */ "Kumandada seçim sesleri",
  /* 19 */ "Bazı konsollar özgün üretici yazılımı olmadan açılmaz. EvaChi onu veremez: telif hakkıyla korunan, elinizdeki makineden kopyalanan bir koddur. Ama hangisinin eksik olduğunu, hangi adla ve nereye konacağını söyler.",
  /* 20 */ "Bu konsolların libretro çekirdeği yok: emülatörleri ayrı bir programdır; EvaChi onu kendi klasörüne kurar ve doğrudan oyunun içinde başlatır — kendi menüsüne hiç uğramadan. Oyunlar, anahtarlar ve sistem dosyaları size kalır.",
  /* 21 */ "Bu ayarlar yalnızca dahili çekirdekleri etkiler. Harici bir emülatörün kendi ayarları vardır, EvaChi onlara karışmaz.",
  /* 22 */ "Bunlar artık sunulmuyor: sorguya yanıt vermediler ya da EvaChi'yi çökerttiler. Geri getirmek onları yeniden kurmaz — yalnızca listeye döndürür.",
  /* 23 */ "Durumu yükle",
  /* 24 */ "Yalnızca dahili çekirdekler. Bir kısayola tıklayın, sonra istediğiniz tuşa ya da düğmeye basın; kumandada iki düğme birlikte alınır, çünkü her biri oyunda zaten kullanılıyor.",
  /* 25 */ "Kontroller",
  /* 26 */ "Kontroller…",
  /* 27 */ "Son konsollar",
  /* 28 */ "Başka bir emülatör tanımla",
  /* 29 */ "Yön tuşları / sol çubuk",
  /* 30 */ "Oyun klasörleri",
  /* 31 */ "Bu emülatörü kenara al",
  /* 32 */ "Kapaklar, libretro projesinin küçük resim sunucusundan, istendiği anda gelir. İşaret kaldırılınca kitaplık ağdan hiçbir şey istemez.",
  /* 33 */ "Kayıt yuvaları",
  /* 34 */ "Kayıt yuvaları…",
  /* 35 */ "Emülatörler",
  /* 36 */ "Kenara alınan emülatörler",
  /* 37 */ "Harici emülatörler",
  /* 38 */ "Harici emülatörler…",
  /* 39 */ "Emülatörler…",
  /* 40 */ "Emülasyon",
  /* 41 */ "Oyun sırasında kitaplığa dön — iki düğme birlikte, çünkü her biri oyunda kullanılıyor",
  /* 42 */ "Kaydet",
  /* 43 */ "Uzantılar",
  /* 44 */ "Kapat",
  /* 45 */ "Dosya",
  /* 46 */ "Kendiniz kuracağınız sistem dosyaları",
  /* 47 */ "Galeri",
  /* 48 */ "Klasörleri yönet…",
  /* 49 */ "Görüntü",
  /* 50 */ "Görüntü…",
  /* 51 */ "Oyunlarınızın bulunduğu klasörü gösterin.",
  /* 52 */ "Kurulum",
  /* 53 */ "Seçileni kur",
  /* 54 */ "Emülatörleri kur…",
  /* 55 */ "Yorumlayıcı",
  /* 56 */ "Nereye gittiğini bilmeniz gerekmez: her şeyin dağınık durduğu klasörü gösterin — BIOS'lar, anahtarlar, üretici yazılımları, arşivler, alt klasörler dahil — EvaChi her dosyayı doğru yere taşır; çekirdekler için de bağımsız emülatörler için de. Kimsenin istemediği dosya yerinden oynatılmaz.",
  /* 57 */ "Kapaklar",
  /* 58 */ "Günlük",
  /* 59 */ "Günlük…",
  /* 60 */ "Geçen sefer kötü bitti",
  /* 61 */ "Oyunu başlat, onayla",
  /* 62 */ "Dil",
  /* 63 */ "Seçiminiz bir açılıştan diğerine korunur. Her biri okunaklılık sınavından geçti: metin her yerde zemininden yeterince ayrılıyor.",
  /* 64 */ "Kalsın",
  /* 65 */ "Aşağıdaki emülatörler zaten ayarlı — argümanları ve biçimleri dahil. EvaChi onları diskinizde arar; kurmaz.",
  /* 66 */ "Varsayılan atamalar",
  /* 67 */ "Yumuşatma",
  /* 68 */ "Oyunu favorilere ekle ya da çıkar",
  /* 69 */ "Dalgalı menü müziği",
  /* 70 */ "Ad",
  /* 71 */ "Menü çubuğunu aç",
  /* 72 */ "Klasörü aç",
  /* 73 */ "Klasörü aç…",
  /* 74 */ "Oyun aç…",
  /* 75 */ "kare başına",
  /* 76 */ "Çekirdek ayarları",
  /* 77 */ "Çekirdek ayarları…",
  /* 78 */ "Kitaplıkta, pencerelerde ve menü çubuğunda dolaş",
  /* 79 */ "Gözat…",
  /* 80 */ "Duraklat",
  /* 81 */ "Tam ekran",
  /* 82 */ "libretro çekirdeği olmayan konsollar için. EvaChi programı, oyunu argüman vererek başlatır: emülatör kendi menüsüne uğramadan doğrudan oyunun içinde açılır.",
  /* 83 */ "Ekran görüntüsü al",
  /* 84 */ "Düzen",
  /* 85 */ "Hazır",
  /* 86 */ "Program",
  /* 87 */ "Birkaç uzun akor ve dağınık notalar; kaydedilmiş değil, çalındıkça oluşuyor: parça hiçbir zaman aynı yere dönmez. Bir oyun başlar başlamaz kendiliğinden susar.",
  /* 88 */ "Bir klasörü topla…",
  /* 89 */ "Yeniden ata…",
  /* 90 */ "Oyun ara…",
  /* 91 */ "Sıfırla",
  /* 92 */ "Kitaplığa dön",
  /* 93 */ "Geri git, kapat",
  /* 94 */ "Hızlı kayıt",
  /* 95 */ "Durumu kaydet",
  /* 96 */ "Shaderler",
  /* 97 */ "Ses",
  /* 98 */ "Start",
  /* 99 */ "Görüntü boyutu",
  /* 100 */ "Temalar",
  /* 101 */ "Temalar…",
  /* 102 */ "Tek dosya…",
  /* 103 */ "Oyun değiştirirken kısa bir tık, başlatırken bir tane daha. Yalnızca kumandada: farede ve klavyede hareket kendini zaten hissettiriyor.",
  /* 104 */ "Hız",
  /* 105 */ "Ekran görüntülerine bak…",
  /* 106 */ "Hepsini kurmak zorunda değilsiniz — kitaplıkta yalnızca emülatörü kurulu konsollar görünür.",
  /* 107 */ "{0} — yüklendi",
  /* 108 */ "{0} — silmek için sağ tık",
  /* 109 */ "{0} — favorilere eklendi",
  /* 110 */ "{0} — sıfırlandı",
  /* 111 */ "{0} — favorilerden çıkarıldı",
  /* 112 */ "{0} — indiriliyor…",
  /* 113 */ "{0}: başarısız, günlüğe bakın",
  /* 114 */ "{0} var",
  /* 115 */ "{0} kaydedildi",
  /* 116 */ "{0} harici bir emülatör: başlatılır, içeride barındırılmaz",
  /* 117 */ "{0} kare/s",
  /* 118 */ "{0} kuruldu",
  /* 119 */ "{0} kuruldu — {1}",
  /* 120 */ "{0} kuruldu ve hazır",
  /* 121 */ "{0} kuruldu, {1} başarısız — günlüğe bakın",
  /* 122 */ "{0} geri getirildi",
  /* 123 */ "{0} kaldırıldı",
  /* 124 */ "{0} / {1}",
  /* 125 */ "{0} diskte var, ama kurulu hiçbir çekirdek onu açmıyor.",
  /* 126 */ "{0} üzerinden alınır, sonra “Gözat…”",
  /* 127 */ "indirilecek",
  /* 128 */ "yok, isteğe bağlı",
  /* 129 */ "Etkinleştir",
  /* 130 */ "Yumuşak",
  /* 131 */ "eklenemedi — {0}",
  /* 132 */ "Sığdır",
  /* 133 */ "Kehribar",
  /* 134 */ "Arduvaz",
  /* 135 */ "durdu — {0}",
  /* 136 */ "geçen sefer ani kapanma — {0}",
  /* 137 */ "yok",
  /* 138 */ "hiç çekirdek dönmedi, oysa {0} biliniyordu — önceki liste korundu",
  /* 139 */ "emülatör yok",
  /* 140 */ "Kurulu emülatör yok",
  /* 141 */ "Tanınan oyun yok",
  /* 142 */ "Sonuç yok",
  /* 143 */ "yok",
  /* 144 */ "kitaplık okunamadı — {0}",
  /* 145 */ "bağlı",
  /* 146 */ "ekran görüntüsü",
  /* 147 */ "Kapağı değiştir…",
  /* 148 */ "Değiştir…",
  /* 149 */ "Her piksel dokuz piksel olur",
  /* 150 */ "Her piksel dört piksel olur: net, bozulma yok",
  /* 151 */ "Her piksel on altı piksel olur — büyük ekranlar için",
  /* 152 */ "Yükle",
  /* 153 */ "Kapak seç…",
  /* 154 */ "önce kitaplıktan bir oyun seçin",
  /* 155 */ "çekirdek: {0}",
  /* 156 */ "çekirdek kurulu değil",
  /* 157 */ "Kurulu çekirdekler",
  /* 158 */ "libretro çekirdekleri",
  /* 159 */ "Yüksek kontrast",
  /* 160 */ "yerel kabuk: {0}",
  /* 161 */ "boşaltma yarım kaldı — {0}",
  /* 162 */ "keşif: {0}",
  /* 163 */ "keşif yarıda kaldı — {0}",
  /* 164 */ "{0} programını kendiniz gösterin",
  /* 165 */ "klasör eklendi: {0}",
  /* 166 */ "klasör açıldı: {0}",
  /* 167 */ "Varsayılan klasör",
  /* 168 */ "Eklenen klasörler",
  /* 169 */ "Esc",
  /* 170 */ "Yuva {0}",
  /* 171 */ "yuva {0} — {1}",
  /* 172 */ "Bu klasör için kullanılan emülatör",
  /* 173 */ "harici emülatörler",
  /* 174 */ "sürüyor",
  /* 175 */ "yerinde",
  /* 176 */ "kaydedilemedi — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi bunları libretro'nun resmî derleme sunucusundan indirebilir. İlginizi çeken konsolları seçin.",
  /* 179 */ "EvaChi, “{0}” oyununu {1} emülatörüyle başlatırken kapandı.",
  /* 180 */ "EvaChi, {0} emülatörü çalışırken kapandı.",
  /* 181 */ "external_systems → {0} emülatör bildirildi",
  /* 182 */ "Favori",
  /* 183 */ "Favoriler",
  /* 184 */ "sistem dosyaları okunamadı — {0}",
  /* 185 */ "Yön tuşları",
  /* 186 */ "Game Boy",
  /* 187 */ "Izgara",
  /* 188 */ "kurulu konsollarda {0} eksik",
  /* 189 */ "kurulum bitti: {0}",
  /* 190 */ "Kuruluyor…",
  /* 191 */ "kurulu",
  /* 192 */ "EvaChi kurdu",
  /* 193 */ "Kur",
  /* 194 */ "yorumlayıcı: {0}",
  /* 195 */ "kurulu çekirdekler sorgulanıyor…",
  /* 196 */ "Başlat",
  /* 197 */ "Seçili oyunu başlat",
  /* 198 */ "Lavanta",
  /* 199 */ "Konsollar bir sırada, oyunlar bir kolonda, dalgalanan bir arka plan. Salon konsolu tadında.",
  /* 200 */ "Kenarlar yumuşar — eski bir televizyona daha yakın",
  /* 201 */ "Kapaklar kocaman, kumandayla gezilir. Koltuk için düşünülmüş.",
  /* 202 */ "Pikseller kare kalır, özgün makinedeki gibi",
  /* 203 */ "kumanda atamaları varsayılana döndü",
  /* 204 */ "list_cores → {0} çekirdek bildirildi",
  /* 205 */ "Liste",
  /* 206 */ "çekirdek listesi alınamadı — {0}",
  /* 207 */ "emülatör listesi alınamadı — {0}",
  /* 208 */ "Kumanda",
  /* 209 */ "kumanda: {0}",
  /* 210 */ "Kumanda: {0}",
  /* 211 */ "kumanda çıkarıldı",
  /* 212 */ "EKSİK",
  /* 213 */ "Nane",
  /* 214 */ "Dalgalı menü",
  /* 215 */ "Güncelle",
  /* 216 */ "Favorilere ekle",
  /* 217 */ "kenara alındı: {0} · {1}",
  /* 218 */ "bir dakikadan az",
  /* 219 */ "Net",
  /* 220 */ "ad, program ve uzantılar; üçü de gerekli",
  /* 221 */ "HAYIR",
  /* 222 */ "bu makinede kurulu değil",
  /* 223 */ "Pembe gece",
  /* 224 */ "Okyanus",
  /* 225 */ "ya da",
  /* 226 */ "evet",
  /* 227 */ "açılamadı — {0}",
  /* 228 */ "web sayfası: yalnızca dahili çekirdekler var, kitaplık yok",
  /* 229 */ "Kâğıt",
  /* 230 */ "varsayılan",
  /* 231 */ "Izgarada ve dalgalı menüde dolaş",
  /* 232 */ "tam ekran reddedildi — {0}",
  /* 233 */ "kumandada istediğiniz düğmeye basın",
  /* 234 */ "bir tuşa basın…",
  /* 235 */ "toplandı: {0} · {1}",
  /* 236 */ "toplanamadı — {0}",
  /* 237 */ "emülatör araması yarıda kaldı — {0}",
  /* 238 */ "Pencereyi kapat",
  /* 239 */ "sıfırlanamadı — {0}",
  /* 240 */ "Oranları koruyarak pencereyi doldurur",
  /* 241 */ "Devam et",
  /* 242 */ "Bu kayıttan devam et — boşaltmak için sağ tık",
  /* 243 */ "Geri getir",
  /* 244 */ "geri getirilemedi — {0}",
  /* 245 */ "Kaldır",
  /* 246 */ "Favorilerden çıkar",
  /* 247 */ "Kapağı kaldır",
  /* 248 */ "kaldırılamadı — {0}",
  /* 249 */ "toplanacak bir şey yok",
  /* 250 */ "engel yok",
  /* 251 */ "“{0}” ile eşleşen bir şey yok.",
  /* 252 */ "Pembe ve beyaz",
  /* 253 */ "resim yok",
  /* 254 */ "Kaydet",
  /* 255 */ "Buraya kaydet",
  /* 256 */ "seçilemedi — {0}",
  /* 257 */ "Konsolun özgün boyutu, piksel piksel",
  /* 258 */ "Bitir",
  /* 259 */ "açık tema",
  /* 260 */ "koyu tema",
  /* 261 */ "her şey kurulu",
  /* 262 */ "bulundu: {0}",
  /* 263 */ "Her konsol için bir bölüm, tablo düzeninde. Fareyle en yoğunu.",
  /* 264 */ "boş",
  /* 265 */ "oyun romset'leri gibi buraya konur: FinalBurn Neo yalnızca bu klasöre bakar",
  /* 266 */ "konsolun açılış ekranını ekler",
  /* 267 */ "makinenin açılış ROM'u",
  /* 268 */ "çoğu oyun onsuz açılır; konsolun menüsü açılmaz",
  /* 269 */ "Amerikan BIOS'u",
  /* 270 */ "Amerikan ve Avrupa BIOS'u",
  /* 271 */ "Avrupa BIOS'u",
  /* 272 */ "Japon BIOS'u",
  /* 273 */ "şifre çözme anahtarları; onlar olmadan şifreli bir döküm geri çevrilir",
  /* 274 */ "blueMSX dağıtımının Machines klasörü, yanında Databases ile",
  /* 275 */ "aynısı",
  /* 276 */ "CD oyunları için şart, HuCard kartları için gereksiz",
  /* 277 */ "Mega-CD oyunları için şart, kartuşlar için gereksiz",
  /* 278 */ "Kickstart 1.3; yoksa PUAE, özgür ama daha az uyumlu olan AROS'a döner",
  /* 279 */ "Kickstart 3.1; A500'ün çalıştıramadığı AGA oyunları için gerekli",
  /* 280 */ "melonDS varsayılan olarak BIOS'u taklit eder; gerçeği daha sadık",
  /* 281 */ "mGBA onsuz idare eder; birkaç oyun açılış ekranı için ister",
  /* 282 */ "konsolun üretici yazılımı",
  /* 283 */ "makinenin üretici yazılımı",
  /* 284 */ "Panasonic FZ-10 üretici yazılımı; Opera varsayılan olarak bu adı bekler",
  /* 285 */ "melonDS bunu değiştirir, özgün hâlini .bak olarak saklar",
  /* 286 */ "yazı tipleri",
  /* 287 */ "konsolun ayarları ve tarihi",
  /* 288 */ "o olmadan çekirdek çalışır ama ekran karanlık kalır",
  /* 289 */ "konsolun karakter tablosu",
  /* 290 */ "Amerikan sürümü, ABD'nin Sega CD oyunları için",
  /* 291 */ "Japon sürümü, Japon Mega-CD oyunları için",
  /* 292 */ "ekran görüntüsü",
  /* 293 */ "ekran görüntüsü",
  /* 294 */ "ekran görüntüsü",
  /* 295 */ "ekran görüntüsü",
  /* 296 */ "ekran görüntüsü",
  /* 297 */ "ekran görüntüsü",
  /* 298 */ "çekirdek",
  /* 299 */ "çekirdek",
  /* 300 */ "çekirdek",
  /* 301 */ "çekirdek",
  /* 302 */ "çekirdek",
  /* 303 */ "çekirdek",
  /* 304 */ "emülatör",
  /* 305 */ "emülatör",
  /* 306 */ "emülatör",
  /* 307 */ "emülatör",
  /* 308 */ "emülatör",
  /* 309 */ "emülatör",
  /* 310 */ "dosya",
  /* 311 */ "dosya",
  /* 312 */ "dosya",
  /* 313 */ "dosya",
  /* 314 */ "dosya",
  /* 315 */ "dosya",
  /* 316 */ "oyun",
  /* 317 */ "oyun",
  /* 318 */ "oyun",
  /* 319 */ "oyun",
  /* 320 */ "oyun",
  /* 321 */ "oyun",
  /* 322 */ "<code>{rom}</code> yerine oyunun yolu geçer. O olmadan yol sonuna eklenir — emülatörlerin çoğu da bunu bekler.",
  /* 323 */ "<strong>Oyun dışında her şey kumandayla yapılır:</strong> yön tuşları kitaplıkta, pencerelerde ve menü çubuğunda dolaşır; <strong>A</strong> onaylar, <strong>B</strong> geri döner, <strong>Start</strong> menü çubuğunu açar. Oyun sırasında <strong>Select ile Start birlikte</strong> kitaplığa geri getirir — iki düğme birden, çünkü her biri oyunda kullanılıyor.",
  /* 324 */ "Ekran görüntüsü yok. Oyun sırasında <strong>F12</strong>'ye, kumandada ise <strong>Select + Y</strong>'ye basın.",
  /* 325 */ "Her konsol kendi emülatörünü ister. EvaChi onları libretro projesinin resmî derleme sunucusundan, <code>buildbot.libretro.com</code> adresinden alır ve kendi klasörüne kurar. Hiçbir şey yeniden dağıtılmıyor: bunlar yazarlarının yayımladığı sürümler.",
  /* 326 */ "Oyun başına dört yuva, diskte saklanır. Kalın yazılmış yuva, <strong>F2</strong> ile <strong>F4</strong>'ün — kumandada da <strong>Select + L1</strong> / <strong>Select + R1</strong>'in kullandığı yuvadır. Bir yuvayı boşaltmak için üzerine sağ tıklayın.",
  /* 327 */ "Emülatör, EvaChi ile aynı pencerede çalışır: çöktüğünde tek söz etmeden onu da beraberinde götürür. Bu emülatörü kenara almak onu kurulu bırakır, yalnızca artık önerilmez. Dilediğiniz zaman, pencerenin altındaki <strong>Dosya → Emülatörler</strong> üzerinden geri getirebilirsiniz.",
  /* 328 */ "Diskte oyun başına tek dosya <small> CD'deki bir oyun, bir <code>.cue</code> künyesi ve diskin iz sayısı kadar <code>.bin</code> dosyası olarak gelir. Yalnızca künye başlatılır: künye varken izler gizlenir. Künye yoksa hiçbir şey gizlenmez. </small>",
  /* 329 */ "(boş) veya --fullscreen {rom}",
];
