/**
 * Vietnamien — les phrases de l'interface, dans l'ordre des clés.
 *
 * Écrit dans l'ordre de `CLES` : c'est le rang qui fait le lien, pas la
 * phrase française, et une ligne oubliée décalerait tout le reste. Les
 * marques numérotées sont là pour qu'on puisse le vérifier à l'œil.
 */

export const vi: readonly string[] = [
  /* 1 */ "Trên tay cầm",
  /* 2 */ "A chạy · X yêu thích · Y cắt ảnh · L1/R1 máy · L2/R2 chữ cái · B quay lại",
  /* 3 */ "Giới thiệu về EvaChi",
  /* 4 */ "Giới thiệu…",
  /* 5 */ "Điều mà chiếc tivi đèn hình làm với hình ảnh, và các trò chơi thời ấy coi là đương nhiên. Chỉ áp dụng cho các lõi chạy ở đây: trình giả lập độc lập tự vẽ hình của nó.",
  /* 6 */ "Làm mới thư viện",
  /* 7 */ "Hiển thị",
  /* 8 */ "Hiện ảnh bìa trò chơi",
  /* 9 */ "Trợ giúp",
  /* 10 */ "Thêm thư mục trò chơi…",
  /* 11 */ "Thêm thư mục…",
  /* 12 */ "Bấm một nút trên tay cầm: lệnh tương ứng sẽ sáng lên. Muốn đổi một lệnh, hãy bấm vào ô bên dưới rồi nhấn nút bạn muốn. Nút đó sẽ đổi chủ: hai lệnh trên cùng một nút trông chẳng khác gì một hỏng hóc.",
  /* 13 */ "Tham số",
  /* 14 */ "Trên bàn phím",
  /* 15 */ "Chưa có trò chơi nào",
  /* 16 */ "Không thấy tay cầm nào.",
  /* 17 */ "Thư viện",
  /* 18 */ "Tiếng động khi chọn bằng tay cầm",
  /* 19 */ "Một số hệ máy không khởi động được nếu thiếu firmware gốc. EvaChi không thể cung cấp firmware đó: nó là mã có bản quyền, phải chép ra từ chính chiếc máy mình có. Bù lại, EvaChi cho biết đang thiếu tệp nào, tên gì, và đặt vào đâu.",
  /* 20 */ "Những hệ máy này không có core libretro: trình giả lập của chúng là một chương trình riêng, EvaChi cài vào thư mục của mình rồi chạy thẳng vào trò chơi — không qua menu của chương trình đó. Trò chơi, khoá và tệp hệ thống thì bạn tự lo.",
  /* 21 */ "Các thiết lập này chỉ chạm đến core nội bộ. Trình giả lập ngoài có thiết lập riêng của nó, và EvaChi không xen vào.",
  /* 22 */ "Những cái này không còn được đề nghị nữa: chúng đã không trả lời khi được hỏi, hoặc đã làm EvaChi sập. Khôi phục chúng không có nghĩa là cài lại — chỉ là đưa chúng trở vào danh sách.",
  /* 23 */ "Nạp trạng thái…",
  /* 24 */ "Chỉ dành cho core nội bộ. Bấm vào một phím tắt rồi nhấn phím hoặc nút mong muốn; trên tay cầm thì lấy hai nút một lượt, vì mỗi nút đều đã có việc trong trò chơi.",
  /* 25 */ "Điều khiển",
  /* 26 */ "Điều khiển…",
  /* 27 */ "Hệ máy gần đây",
  /* 28 */ "Khai báo một trình giả lập khác",
  /* 29 */ "Phím hướng / cần trái",
  /* 30 */ "Thư mục trò chơi",
  /* 31 */ "Ngưng dùng trình giả lập này",
  /* 32 */ "Ảnh được lấy từ máy chủ ảnh thu nhỏ của dự án libretro, khi cần đến. Bỏ chọn thì thư viện không hỏi gì trên mạng nữa.",
  /* 33 */ "Ô lưu trạng thái",
  /* 34 */ "Ô lưu…",
  /* 35 */ "Trình giả lập",
  /* 36 */ "Trình giả lập đã ngưng dùng",
  /* 37 */ "Trình giả lập ngoài",
  /* 38 */ "Trình giả lập ngoài…",
  /* 39 */ "Trình giả lập…",
  /* 40 */ "Giả lập",
  /* 41 */ "Đang chơi thì quay về thư viện — hai nút một lượt, vì mỗi nút đều có việc trong trò chơi",
  /* 42 */ "Lưu",
  /* 43 */ "Phần mở rộng",
  /* 44 */ "Đóng",
  /* 45 */ "Tệp",
  /* 46 */ "Tệp hệ thống phải tự cài lấy",
  /* 47 */ "Trưng bày",
  /* 48 */ "Quản lý thư mục…",
  /* 49 */ "Hình ảnh",
  /* 50 */ "Hình ảnh…",
  /* 51 */ "Hãy chỉ ra thư mục chứa trò chơi của bạn.",
  /* 52 */ "Cài đặt",
  /* 53 */ "Cài những mục đã chọn",
  /* 54 */ "Cài trình giả lập…",
  /* 55 */ "Trình thông dịch",
  /* 56 */ "Không cần biết chỗ nào: cứ chỉ ra thư mục đang chứa mọi thứ — BIOS, khoá, firmware, tệp nén, kể cả thư mục con — rồi EvaChi sẽ đưa từng tệp về đúng chỗ, cho core cũng như cho trình giả lập độc lập. Thứ gì không ai cần đến thì không bị dời đi.",
  /* 57 */ "Ảnh bìa",
  /* 58 */ "Nhật ký",
  /* 59 */ "Nhật ký…",
  /* 60 */ "Lần trước kết thúc không êm xuôi",
  /* 61 */ "Chạy trò chơi, xác nhận",
  /* 62 */ "Ngôn ngữ",
  /* 63 */ "Lựa chọn được giữ lại từ lần mở này sang lần mở khác. Mỗi chủ đề đều đã được kiểm tra về độ dễ đọc: ở đâu chữ cũng đủ tương phản với nền của nó.",
  /* 64 */ "Giữ lại",
  /* 65 */ "Các trình giả lập dưới đây đã được cấu hình sẵn — cả tham số lẫn định dạng. EvaChi tìm chúng trên đĩa của bạn; nó không cài chúng.",
  /* 66 */ "Gán phím mặc định",
  /* 67 */ "Làm mượt",
  /* 68 */ "Đánh dấu yêu thích trò chơi, hoặc bỏ dấu",
  /* 69 */ "Nhạc của các menu động",
  /* 70 */ "Tên",
  /* 71 */ "Mở thanh menu",
  /* 72 */ "Mở thư mục",
  /* 73 */ "Mở thư mục…",
  /* 74 */ "Mở một trò chơi…",
  /* 75 */ "mỗi khung hình",
  /* 76 */ "Thiết lập của core",
  /* 77 */ "Thiết lập của core…",
  /* 78 */ "Duyệt thư viện, các cửa sổ và thanh menu",
  /* 79 */ "Duyệt…",
  /* 80 */ "Tạm dừng",
  /* 81 */ "Toàn màn hình",
  /* 82 */ "Dành cho những hệ máy không có core libretro. EvaChi chạy chương trình với trò chơi làm tham số: trình giả lập vào thẳng ván chơi, không qua menu riêng của nó.",
  /* 83 */ "Chụp màn hình",
  /* 84 */ "Cách hiển thị",
  /* 85 */ "Sẵn sàng",
  /* 86 */ "Chương trình",
  /* 87 */ "Vài hợp âm ngân dài và ít nốt rải rác, được soạn ngay lúc nghe chứ không phải bản thu sẵn: bản nhạc không bao giờ trở lại đúng chỗ cũ. Nó tự ngừng ngay khi một trò chơi bắt đầu.",
  /* 88 */ "Sắp xếp một thư mục…",
  /* 89 */ "Dọn trống",
  /* 90 */ "Tìm một trò chơi…",
  /* 91 */ "Đặt lại",
  /* 92 */ "Về lại thư viện",
  /* 93 */ "Quay lại, đóng",
  /* 94 */ "Lưu nhanh",
  /* 95 */ "Lưu trạng thái…",
  /* 96 */ "Shaders",
  /* 97 */ "Âm thanh",
  /* 98 */ "Start",
  /* 99 */ "Kích thước hình",
  /* 100 */ "Chủ đề",
  /* 101 */ "Chủ đề…",
  /* 102 */ "Chỉ một tệp…",
  /* 103 */ "Một tiếng tách nhẹ khi chuyển trò chơi, một tiếng nữa khi chạy trò chơi. Chỉ có trên tay cầm: với chuột và bàn phím thì cử chỉ đã đủ cảm nhận rồi.",
  /* 104 */ "Tốc độ",
  /* 105 */ "Xem ảnh chụp màn hình…",
  /* 106 */ "Bạn có thể chỉ cài một phần — chỉ những hệ máy đã có trình giả lập mới hiện ra trong thư viện.",
  /* 107 */ "{0} — đã nạp",
  /* 108 */ "{0} — bấm chuột phải để xoá",
  /* 109 */ "{0} — đã cho vào yêu thích",
  /* 110 */ "{0} — đã đặt lại",
  /* 111 */ "{0} — đã bỏ khỏi yêu thích",
  /* 112 */ "{0} — đang tải về…",
  /* 113 */ "{0}: thất bại, xem nhật ký",
  /* 114 */ "có sẵn {0}",
  /* 115 */ "đã lưu {0}",
  /* 116 */ "{0} là trình giả lập ngoài: nó được chạy lên, chứ không chạy bên trong EvaChi",
  /* 117 */ "{0} hình/giây",
  /* 118 */ "đã cài {0}",
  /* 119 */ "đã cài {0} — {1}",
  /* 120 */ "đã cài {0}, sẵn sàng",
  /* 121 */ "đã cài {0}, {1} thất bại — xem nhật ký",
  /* 122 */ "đã khôi phục {0}",
  /* 123 */ "đã bỏ {0}",
  /* 124 */ "{0} trên {1}",
  /* 125 */ "{0} có trên đĩa, nhưng không core nào đã cài mở được nó.",
  /* 126 */ "lấy từ {0}, rồi bấm “Duyệt…”",
  /* 127 */ "cần tải về",
  /* 128 */ "không có, không bắt buộc",
  /* 129 */ "Bật",
  /* 130 */ "Mượt",
  /* 131 */ "không thêm được — {0}",
  /* 132 */ "Vừa khung",
  /* 133 */ "Hổ phách",
  /* 134 */ "Đá phiến",
  /* 135 */ "dừng — {0}",
  /* 136 */ "lần trước dừng đột ngột — {0}",
  /* 137 */ "không có",
  /* 138 */ "không core nào được trả về dù trước đó đã biết {0} — giữ lại danh sách cũ",
  /* 139 */ "không có trình giả lập",
  /* 140 */ "Chưa cài trình giả lập nào",
  /* 141 */ "Không nhận ra trò chơi nào",
  /* 142 */ "Không có kết quả",
  /* 143 */ "không có",
  /* 144 */ "không đọc được thư viện — {0}",
  /* 145 */ "đã cắm",
  /* 146 */ "ảnh chụp màn hình",
  /* 147 */ "Đổi ảnh bìa…",
  /* 148 */ "Đổi…",
  /* 149 */ "Mỗi điểm ảnh thành chín",
  /* 150 */ "Mỗi điểm ảnh thành bốn: sắc nét, không méo",
  /* 151 */ "Mỗi điểm ảnh thành mười sáu — dành cho màn hình lớn",
  /* 152 */ "Nạp",
  /* 153 */ "Chọn ảnh bìa…",
  /* 154 */ "hãy chọn một trò chơi trong thư viện trước đã",
  /* 155 */ "core: {0}",
  /* 156 */ "core chưa được cài",
  /* 157 */ "Core đã cài",
  /* 158 */ "core libretro",
  /* 159 */ "Tương phản cao",
  /* 160 */ "lớp vỏ gốc: {0}",
  /* 161 */ "gỡ nạp chưa xong — {0}",
  /* 162 */ "dò tìm: {0}",
  /* 163 */ "dò tìm bị gián đoạn — {0}",
  /* 164 */ "Tự chỉ ra chương trình của {0}",
  /* 165 */ "đã thêm thư mục: {0}",
  /* 166 */ "đã mở thư mục: {0}",
  /* 167 */ "Thư mục mặc định",
  /* 168 */ "Thư mục đã thêm",
  /* 169 */ "Esc",
  /* 170 */ "Ô lưu {0}",
  /* 171 */ "ô lưu {0} — {1}",
  /* 172 */ "Trình giả lập dùng cho thư mục này",
  /* 173 */ "trình giả lập ngoài",
  /* 174 */ "đang chạy",
  /* 175 */ "đã có",
  /* 176 */ "không lưu được — {0}",
  /* 177 */ "Enter",
  /* 178 */ "EvaChi có thể tải chúng về từ kho chính thức của libretro. Hãy chọn những hệ máy bạn quan tâm.",
  /* 179 */ "EvaChi đã dừng khi đang chạy “{0}”, với trình giả lập {1}.",
  /* 180 */ "EvaChi đã dừng, với trình giả lập {0}.",
  /* 181 */ "external_systems → {0} trình giả lập được khai báo",
  /* 182 */ "Yêu thích",
  /* 183 */ "Yêu thích",
  /* 184 */ "không đọc được tệp hệ thống — {0}",
  /* 185 */ "Phím mũi tên",
  /* 186 */ "Game Boy",
  /* 187 */ "Lưới",
  /* 188 */ "một số hệ máy đã cài còn thiếu {0}",
  /* 189 */ "cài xong: {0}",
  /* 190 */ "Đang cài…",
  /* 191 */ "đã cài",
  /* 192 */ "do EvaChi cài",
  /* 193 */ "Cài",
  /* 194 */ "trình thông dịch: {0}",
  /* 195 */ "đang hỏi các core đã cài…",
  /* 196 */ "Chạy",
  /* 197 */ "Chạy trò chơi đã chọn",
  /* 198 */ "Oải hương",
  /* 199 */ "Hệ máy xếp hàng ngang, trò chơi xếp hàng dọc, nền gợn sóng. Kiểu máy chơi game phòng khách.",
  /* 200 */ "Đường viền nhoè đi — gần với chiếc tivi cũ hơn",
  /* 201 */ "Ảnh bìa cỡ lớn, lật bằng tay cầm. Nghĩ cho những lúc ngồi ghế sofa.",
  /* 202 */ "Điểm ảnh vẫn vuông vức, như trên máy gốc",
  /* 203 */ "đã trả tay cầm về gán phím mặc định",
  /* 204 */ "list_cores → {0} core được báo",
  /* 205 */ "Danh sách",
  /* 206 */ "không lấy được danh sách core — {0}",
  /* 207 */ "không lấy được danh sách trình giả lập — {0}",
  /* 208 */ "Tay cầm",
  /* 209 */ "tay cầm: {0}",
  /* 210 */ "Tay cầm: {0}",
  /* 211 */ "tay cầm đã rút",
  /* 212 */ "THIẾU",
  /* 213 */ "Bạc hà",
  /* 214 */ "Menu động",
  /* 215 */ "Cập nhật",
  /* 216 */ "Cho vào yêu thích",
  /* 217 */ "đã ngưng dùng: {0} · {1}",
  /* 218 */ "chưa đầy một phút",
  /* 219 */ "Sắc nét",
  /* 220 */ "cần đủ cả tên, chương trình và phần mở rộng",
  /* 221 */ "KHÔNG",
  /* 222 */ "chưa cài trên máy này",
  /* 223 */ "Đêm hồng",
  /* 224 */ "Đại dương",
  /* 225 */ "hoặc",
  /* 226 */ "có",
  /* 227 */ "không mở được — {0}",
  /* 228 */ "trang web: chỉ có core nội bộ, không có thư viện",
  /* 229 */ "Giấy",
  /* 230 */ "mặc định",
  /* 231 */ "Duyệt lưới và các menu động",
  /* 232 */ "toàn màn hình bị từ chối — {0}",
  /* 233 */ "hãy nhấn nút mong muốn trên tay cầm",
  /* 234 */ "hãy nhấn một phím…",
  /* 235 */ "sắp xếp: {0} · {1}",
  /* 236 */ "không sắp xếp được — {0}",
  /* 237 */ "việc tìm trình giả lập bị gián đoạn — {0}",
  /* 238 */ "Đóng một cửa sổ",
  /* 239 */ "không đặt lại được — {0}",
  /* 240 */ "Lấp đầy cửa sổ mà vẫn giữ tỉ lệ",
  /* 241 */ "Chơi tiếp",
  /* 242 */ "Thay thế",
  /* 243 */ "Khôi phục",
  /* 244 */ "không khôi phục được — {0}",
  /* 245 */ "Bỏ",
  /* 246 */ "Bỏ khỏi yêu thích",
  /* 247 */ "Bỏ ảnh bìa",
  /* 248 */ "không bỏ được — {0}",
  /* 249 */ "không có gì để sắp xếp",
  /* 250 */ "không có gì cản trở",
  /* 251 */ "Không có gì khớp với “{0}”.",
  /* 252 */ "Hồng và trắng",
  /* 253 */ "không có ảnh",
  /* 254 */ "Lưu",
  /* 255 */ "Lưu vào đây",
  /* 256 */ "không chọn được — {0}",
  /* 257 */ "Đúng kích thước gốc của hệ máy, từng điểm ảnh một",
  /* 258 */ "Bỏ đi",
  /* 259 */ "chủ đề sáng",
  /* 260 */ "chủ đề tối",
  /* 261 */ "đã cài đủ",
  /* 262 */ "tìm thấy: {0}",
  /* 263 */ "Mỗi hệ máy một mục, xếp thành bảng. Dày đặc nhất, hợp với chuột.",
  /* 264 */ "trống",
  /* 265 */ "đặt vào đây, như các romset trò chơi: FinalBurn Neo chỉ tìm trong thư mục này",
  /* 266 */ "thêm màn hình chào của hệ máy",
  /* 267 */ "phần khởi động của máy",
  /* 268 */ "nhiều trò chơi chạy được khi thiếu nó; menu của máy thì không",
  /* 269 */ "BIOS Mỹ",
  /* 270 */ "BIOS Mỹ và châu Âu",
  /* 271 */ "BIOS châu Âu",
  /* 272 */ "BIOS Nhật",
  /* 273 */ "khoá giải mã; thiếu chúng thì bản dump đã mã hoá sẽ bị từ chối",
  /* 274 */ "thư mục Machines của bản blueMSX, có Databases nằm bên cạnh",
  /* 275 */ "như trên",
  /* 276 */ "bắt buộc với trò chơi trên CD, không cần với thẻ HuCard",
  /* 277 */ "bắt buộc với trò chơi Mega-CD, không cần với băng game",
  /* 278 */ "Kickstart 1.3; nếu không có, PUAE quay sang AROS, tự do nhưng kém tương thích hơn",
  /* 279 */ "Kickstart 3.1; cần cho các trò chơi AGA mà A500 không chạy nổi",
  /* 280 */ "melonDS giả lập BIOS theo mặc định; bản thật thì trung thực hơn",
  /* 281 */ "mGBA không cần đến nó; vài trò chơi lại đòi có để hiện màn hình chào",
  /* 282 */ "firmware của hệ máy",
  /* 283 */ "firmware của máy",
  /* 284 */ "firmware Panasonic FZ-10; đó là cái tên Opera lấy theo mặc định",
  /* 285 */ "bị melonDS sửa đổi, bản gốc được giữ lại dưới dạng .bak",
  /* 286 */ "bộ phông chữ",
  /* 287 */ "thiết lập và ngày giờ của hệ máy",
  /* 288 */ "thiếu nó thì core vẫn chạy nhưng màn hình vẫn đen",
  /* 289 */ "bảng ký tự của hệ máy",
  /* 290 */ "bản Mỹ, dành cho các trò chơi Sega CD của Hoa Kỳ",
  /* 291 */ "bản Nhật, dành cho các trò chơi Mega-CD của Nhật",
  /* 292 */ "ảnh chụp màn hình",
  /* 293 */ "ảnh chụp màn hình",
  /* 294 */ "ảnh chụp màn hình",
  /* 295 */ "ảnh chụp màn hình",
  /* 296 */ "ảnh chụp màn hình",
  /* 297 */ "ảnh chụp màn hình",
  /* 298 */ "core",
  /* 299 */ "core",
  /* 300 */ "core",
  /* 301 */ "core",
  /* 302 */ "core",
  /* 303 */ "core",
  /* 304 */ "trình giả lập",
  /* 305 */ "trình giả lập",
  /* 306 */ "trình giả lập",
  /* 307 */ "trình giả lập",
  /* 308 */ "trình giả lập",
  /* 309 */ "trình giả lập",
  /* 310 */ "tệp",
  /* 311 */ "tệp",
  /* 312 */ "tệp",
  /* 313 */ "tệp",
  /* 314 */ "tệp",
  /* 315 */ "tệp",
  /* 316 */ "trò chơi",
  /* 317 */ "trò chơi",
  /* 318 */ "trò chơi",
  /* 319 */ "trò chơi",
  /* 320 */ "trò chơi",
  /* 321 */ "trò chơi",
  /* 322 */ "<code>{rom}</code> sẽ được thay bằng đường dẫn của trò chơi. Nếu không có nó, đường dẫn được thêm vào cuối — đúng như phần lớn trình giả lập mong đợi.",
  /* 323 */ "<strong>Ngoài lúc chơi, mọi thứ đều làm được bằng tay cầm:</strong> các phím hướng duyệt thư viện, các cửa sổ và thanh menu; <strong>A</strong> xác nhận, <strong>B</strong> quay lại, <strong>Start</strong> mở thanh menu. Đang chơi thì <strong>Select và Start cùng lúc</strong> đưa bạn về thư viện — hai nút một lượt, vì mỗi nút đều có việc trong trò chơi.",
  /* 324 */ "Chưa có ảnh chụp nào. Hãy nhấn <strong>F12</strong> khi đang chơi, hoặc <strong>Select + Y</strong> trên tay cầm.",
  /* 325 */ "Mỗi hệ máy cần trình giả lập của riêng nó. EvaChi tìm chúng trên kho chính thức của dự án libretro, <code>buildbot.libretro.com</code>, rồi cài vào thư mục riêng của mình. Không có gì được phát tán lại: đó là các bản do chính tác giả của chúng công bố.",
  /* 326 */ "Bốn ô lưu cho mỗi trò chơi, giữ trên đĩa. Mỗi thao tác đều được ghi dưới ô lưu, và việc thay thế hay dọn trống đều hỏi lại trước. <strong>F2</strong> và <strong>F4</strong> — cùng <strong>Select + L1</strong> / <strong>Select + R1</strong> trên tay cầm — đi thẳng tới ô in đậm, không hỏi gì cả.",
  /* 327 */ "Mỗi trình giả lập chạy trong tiến trình riêng của nó: khi nó sập, EvaChi thấy được và đưa bạn về thư viện. Ván đang chơi mất đi, và bản lưu của trò chơi có thể chưa kịp ghi. Ngưng dùng trình giả lập này thì nó vẫn còn được cài, chỉ là không còn được đề nghị nữa. Bạn có thể khôi phục nó bất cứ lúc nào từ <strong>Tệp → Trình giả lập</strong>, ở cuối cửa sổ.",
  /* 328 */ "Mỗi trò chơi chỉ một tệp trên đĩa <small> Trò chơi trên CD đến dưới dạng một tờ mục lục <code>.cue</code> và nhiều tệp <code>.bin</code> đúng bằng số rãnh của đĩa. Chỉ tờ mục lục là chạy được: các rãnh bị ẩn đi khi có nó. Không có tờ mục lục thì chẳng có gì bị ẩn cả. </small>",
  /* 329 */ "(để trống) hoặc --fullscreen {rom}",
  /* 330 */ "Một trăm phần trăm là tốc độ gốc của máy. Thấp hơn thì game chạy chậm lại, cao hơn thì game lao đi — và âm thanh cũng theo đó, trầm hơn hoặc cao hơn. Trên tay cầm, trái và phải chuyển sang mức kế tiếp. Chỉ với các core nội bộ: trình giả lập bên ngoài giữ tốc độ riêng của nó.",
  /* 331 */ "Mỗi lần năm máy",
  /* 332 */ "Nút điều hướng",
  /* 333 */ "Từ chữ cái đầu này sang chữ kế tiếp",
  /* 334 */ "Trong các menu động, mỗi lần năm game",
  /* 335 */ "Tốc độ game",
  /* 336 */ "Hủy",
  /* 337 */ "Kéo khung đi, hoặc kéo một góc của nó. Phím mũi tên dùng để dời khung, giữ Shift thì phóng to hay thu nhỏ. Khi khung tràn ra ngoài ảnh, phần thừa thành viền trong suốt — đó là cách thu nhỏ một ảnh bìa bị cắt quá sát. Trên tay cầm, các nút hướng dùng để dời, còn nút cò chỉnh kích thước.",
  /* 338 */ "Cắt ảnh",
  /* 339 */ "Cắt lại ảnh bìa",
  /* 340 */ "Lấy cả ảnh",
  /* 341 */ "{0} — đã cắt lại ảnh bìa",
  /* 342 */ "{0} — không có ảnh bìa để cắt",
  /* 343 */ "không đọc được ảnh bìa — {0}",
  /* 344 */ "không cắt được — {0}",
  /* 345 */ "Cắt lại ảnh bìa…",
  /* 346 */ "Tua nhanh, chừng nào cả hai cần còn được nhấn xuống",
  /* 347 */ "đã ngưng dùng {0}",
  /* 348 */ "Trình giả lập {0} đã dừng khi đang chạy “{1}”.",
  /* 349 */ "Trình giả lập {0} đã dừng.",
  /* 350 */ "Trình giả lập đã dừng",
  /* 351 */ "không ngưng dùng được — {0}",
  /* 352 */ "đặt vào đây: {0}",
  /* 353 */ "thiếu một tệp hệ thống: {0}",
  /* 354 */ "Ghi công",
  /* 355 */ "Giấy phép phi thương mại, cần biết trước khi lấy về dùng lại: {0}.",
  /* 356 */ "EvaChi không viết trình giả lập nào: nó chỉ chứa chúng. Mỗi cái là một dự án tự do trọn vẹn, do người khác viết, và EvaChi đi lấy từ chính tác giả của nó khi cần — không một dòng mã nào của họ được chép lại ở đây, không một byte nào được phát tán lại. Tên và giấy phép dưới đây là những gì mỗi dự án tự công bố.",
  /* 357 */ "Vòng quay",
  /* 358 */ "Bìa game quay mặt ra trước, các hệ máy xếp chồng, bụi bay lên. Kiểu quầy trưng bày.",
  /* 359 */ "Như giao diện",
  /* 360 */ "Ngôn ngữ giao diện",
  /* 361 */ "Ngôn ngữ trò chơi",
  /* 362 */ "Ngôn ngữ trò chơi: {0}. Sẽ có hiệu lực từ lần chạy sau.",
  /* 363 */ "Quay lại",
  /* 364 */ "Tìm",
  /* 365 */ "Tìm các tệp",
  /* 366 */ "Tìm một giá trị",
  /* 367 */ "Khác",
  /* 368 */ "Như cũ",
  /* 369 */ "Bề rộng",
  /* 370 */ "Dự án libretro công bố các tệp mã gian lận, mỗi trò chơi một tệp. EvaChi chỉ giữ những tệp khớp chính xác với trò chơi của bạn — cùng tên, cùng vùng, cùng bản sửa đổi — và thà không đề xuất gì còn hơn đề xuất thứ gần đúng: mã viết cho bản khác không ghi lệch một chút, mà ghi sang hẳn chỗ khác.",
  /* 371 */ "Các mã",
  /* 372 */ "Ít hơn",
  /* 373 */ "Bảng mã gian lận",
  /* 374 */ "Nhiều hơn",
  /* 375 */ "Bắt đầu lại",
  /* 376 */ "Mã gian lận",
  /* 377 */ "Mã gian lận…",
  /* 378 */ "Giá trị",
  /* 379 */ "Bằng",
  /* 380 */ "{0} địa chỉ có thể",
  /* 381 */ "Đã đặt {0} tệp, gỡ {1} tệp",
  /* 382 */ "{0} trên {1} trò chơi có tệp",
  /* 383 */ "{0} byte bộ nhớ",
  /* 384 */ "Đã loại {0} giá trị: nằm ngoài bộ nhớ của trò chơi này",
  /* 385 */ "Không có tệp cho trò chơi này. Bảng « Mã gian lận… » trong trình đơn Giả lập sẽ tìm một tệp; nếu không có, việc tìm giá trị vẫn chạy với mọi trò chơi.",
  /* 386 */ "Đã khóa",
  /* 387 */ "Khóa",
  /* 388 */ "Chơi một lát, rồi cho biết giá trị đã thay đổi thế nào.",
  /* 389 */ "Ván chơi đã được cất riêng trước mã gian lận đầu tiên.",
  /* 390 */ "Đang tìm…",
  /* 391 */ "Thứ đặt vào « drop u'r rom » sẽ đi tới máy mà phần mở rộng của nó chỉ định. Khi nhiều máy dùng chung một phần mở rộng — các ảnh đĩa — EvaChi hỏi chứ không đoán.",
  /* 392 */ "Xác nhận",
  /* 393 */ "Xoá bản lưu của trò chơi…",
  /* 394 */ "Kéo giãn",
  /* 395 */ "Trò chơi giữ các con số của nó trong bộ nhớ mà không nói ở đâu. Ta tìm ra bằng cách loại dần: bạn cho biết con số trên màn hình đã thế nào, và EvaChi loại bỏ những địa chỉ không như vậy.",
  /* 396 */ "Có",
  /* 397 */ "Ít máy nào có tỷ lệ của màn hình ngày nay, vì thế mới có các dải đen hai bên. Ở mức không, hình giữ nguyên tỷ lệ; ở mức một trăm, hình lấp đầy cửa sổ dù phải giãn ra.",
  /* 398 */ "Sắp xếp các trò chơi",
  /* 399 */ "Sắp xếp",
  /* 400 */ "Sắp xếp những trò chơi đã đặt vào…",
  /* 401 */ "Bạn thấy 47 mạng: gõ 47 vào « Giá trị » rồi bấm « Tìm ». Mất một mạng, gõ 46 rồi bấm « Bằng ». Nếu con số không hiện ở đâu cả, hãy để « Giá trị » trống và chỉ nói « Nhiều hơn », « Ít hơn », « Khác » hay « Như cũ » giữa hai lúc chơi. Sau đó « Khóa » sẽ giữ nguyên giá trị đã tìm được. « Bề rộng » là cỡ của con số: 1 cho tới 255, 2 khi lớn hơn, 4 cho các bộ đếm lớn.",
  /* 402 */ "đã sắp xếp {0}",
  /* 403 */ "không có bản lưu nào để xoá",
  /* 404 */ "Nút bấm",
  /* 405 */ "Đã có trong thư viện: {0}",
  /* 406 */ "Xoá bản lưu của {0} và chơi lại từ đầu? Ván đang chơi sẽ dừng, và những gì trò chơi đã ghi lại sẽ mất.",
  /* 407 */ "Cò bấm",
  /* 408 */ "Giữ cả hai",
  /* 409 */ "Để nguyên trong thư mục",
  /* 410 */ "Thư mục trống.",
  /* 411 */ "Thay thế ô lưu {0}? Những gì cất ở đó sẽ mất.",
  /* 412 */ "đã xoá bản lưu — {0}",
  /* 413 */ "Hệ thống",
  /* 414 */ "Dọn trống ô lưu {0}? Những gì cất ở đó sẽ mất.",
  /* 415 */ "Vùng chết là phần của cần gạt mà ở đó nó vẫn được coi là đứng yên. Quá nhỏ thì nhân vật tự trôi đi dù tay cầm nằm trên bàn; quá lớn thì những cử động nhỏ mất hút. Vài trò chơi đòi lắc máy: khi tay cầm không cảm nhận được điều đó, hai nút bên dưới khiến trò chơi tin là đã lắc.",
  /* 416 */ "Cần gạt",
  /* 417 */ "Các trình giả lập độc lập có nút riêng, trong tệp riêng của chúng. Những gì bạn đổi ở đây được mang sang đó ngay lập tức, với những cái mà chúng tôi biết rõ định dạng tận nơi: PCSX2, PPSSPP và Dolphin. Thiết lập cũ được để riêng ở lần đầu, cùng tên kèm « .avant-evachi ».",
  /* 418 */ "Mang sang trình giả lập bên ngoài",
  /* 419 */ "Vùng chết",
  /* 420 */ "Buổi chiếu",
  /* 421 */ "Đất sét",
  /* 422 */ "chưa trình giả lập bên ngoài nào ghi thiết lập của nó",
  /* 423 */ "Than hồng",
  /* 424 */ "Tro",
  /* 425 */ "Anh đào",
  /* 426 */ "San hô",
  /* 427 */ "Cỗ bài",
  /* 428 */ "Rừng",
  /* 429 */ "Sương giá",
  /* 430 */ "các trình giả lập bên ngoài đã có sẵn những nút này",
  /* 431 */ "Nửa đêm",
  /* 432 */ "Rêu",
  /* 433 */ "Neon",
  /* 434 */ "Mận",
  /* 435 */ "Cát",
  /* 436 */ "Lắc",
  /* 437 */ "Nâu đỏ",
  /* 438 */ "nút đã mang sang: {0}",
  /* 439 */ "Ngọc lam",
  /* 440 */ "Các bìa game được cầm xòe như một tay bài. Cổ tay xoay, và lá bài đang đọc dựng thẳng lên.",
  /* 441 */ "Một căn phòng tối, một luồng sáng đầy bụi, và trò chơi chiếu lớn. Số còn lại chờ trong khay.",
  /* 442 */ "Virtual Boy",
  /* 443 */ "Mơ",
  /* 444 */ "Thạch nam",
  /* 445 */ "Caramel",
  /* 446 */ "Đồng",
  /* 447 */ "Mực",
  /* 448 */ "Famicom",
  /* 449 */ "Ngọc bích",
  /* 450 */ "Việt quất",
  /* 451 */ "Giông bão",
  /* 452 */ "Ngọc trai",
  /* 453 */ "Hồ trăn",
  /* 454 */ "Không dùng",
  /* 455 */ "Đường quét",
  /* 456 */ "Mỗi điểm ảnh thành ba khe: đỏ, lục và lam",
  /* 457 */ "Hình của lõi, từng điểm ảnh một",
  /* 458 */ "Mặt kính cong, các đường, các khe và mép tối dần",
  /* 459 */ "Lưới khe",
  /* 460 */ "Đèn hình",
  /* 461 */ "Cứ hai dòng thì một dòng tối đi, như trên tivi",
];
